### ISSUE TITLE
Outdated twin creation steps in the test_setup docs

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#10]
### Description

Outdated twin creation steps in the [ `test_setup`](https://github.com/threefoldtech/grid3_client_ts/blob/development/docs/test_setup.md#test-setup) docs

**Comment by AhmedHanafy725** [comment]
the docs got removed while moving the repo.

**Comment by mohamedamer453** [comment]
Verified.

The outdated docs were removed https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/grid_client/docs
