### ISSUE TITLE
The 'Add' tooltip from the Add worker button isn't working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1006]
### Description

The `Add` tooltip from the Add worker button is a glitching and once it appears, it stays there permanently.

### Steps to reproduce

1. Login
2. Go to any solution where you can add a worker (eg. Caprover)
3. Press + button
4. Navigate to anywhere in page and you will find Add label is always displayed. 

### Logs/Alerts

[Untitled_ Aug 17, 2023 10_01 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9bc3675f-3ced-4c34-9310-ab7427019aad)

**Comment by xmonader** [comment]
is this happening anywhere else?

**Comment by A-Harby** [comment]
> is this happening anywhere else?

It did occur to me in many of the solution instance listing.

Like below, when it was listing or after deleting.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c6056fba-38de-414c-9890-01d7869eeda8)

**Comment by A-Harby** [comment]
> is this happening anywhere else?

Like Caprover and Kubernetes Add button yes, but other buttons' tooltips no for now but will test all them to make sure.

**Comment by Mahmoud-Emad** [comment]
I think there is no issue, it maybe happened on your machine only due to caching or something like that.



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/9c3f6a5b-a612-4bde-9769-76225ef9923d

**Comment by A-Harby** [comment]
I did hard reset and clear the cache, and the bug still happen.

It's not about deploying or steps, it's because of the add tooltip after pressing the button it doesn't disappear like any other tooltip.

[Add bug](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2ecdbb84-346c-41a0-b8bf-9f3f09a02edf)

**Comment by khaledyoussef24** [comment]
the problem still exists after clicking on add worker for  one time the add label will always be there
[Screencast from 08-21-2023 10:15:40 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/58b38f6f-6fe1-4534-860c-c3cf59cf3a42)

**Comment by A-Harby** [comment]
Closing the issue as non-reproducible.
