### ISSUE TITLE
Can login with mnemonics only without entering a password after logging out

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1011]
### Description
Tested locally and on Devnet 2.1.0-rc10.

You can login with mnemonics only without entering a password after logging out.

### Logs/Alerts

[Untitled_ Aug 20 2023 2_47 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/785dd398-a771-4ac5-8600-8b176e6ff284)

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
[Screencast from 08-29-2023 09:49:42 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db07014f-5f70-4db8-8712-2513edc047ba)
