### ISSUE TITLE
Edit Playground Navigation Drawer to include Dashboard

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1013]
- Add project skeleton & theme
- Add a navigation drawer which should include:
  - Portal 
     - Twin:
     - Bridge
     - Transfer
     - Farms
     - Dedicated Nodes
     - DAO
  - Explorer
     - Statistics
     - Nodes
     - Farms
  - Calculators
     - Resource Pricing
     - Simulator
  - Monitoring
  - 0-Hub
  - Manual

**Comment by khaledyoussef24** [comment]
verified on the new playground
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b7764bcd-21ec-45be-aa3d-4852aca7c9fc)
and the solutions are all in a grid view once you go to the tab will be visible
