### ISSUE TITLE
Implement Bridge in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1015]

**Comment by amiraabouhadid** [comment]
On hold till transfer page is complete

**Comment by AlaaElattar** [comment]
- The implementation is done and working correctly, just waiting for the design of deposit dialog to put an indication for user that we're waiting for receiving TFTs.

**Comment by AlaaElattar** [comment]
- The design of deposit dialog is done now, waiting for review.

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2023-10-02 15-28-26](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a67c766c-535a-4e17-bfa8-62d5408316f7)
![Screenshot from 2023-10-02 15-28-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0cb82124-8452-44f9-addf-a61f8766db26)
