### ISSUE TITLE
Implement Transfer in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1016]

**Comment by amiraabouhadid** [comment]
Updated template using vuetify3.
Working on unifying get balance function.

**Comment by amiraabouhadid** [comment]
Done with getting balance from grid. Working on updating form validation in Vue3.

**Comment by amiraabouhadid** [comment]
Done with Transfer by Twin ID. Working on Transfer by Address.

**Comment by amiraabouhadid** [comment]
Working on transfer by address for validation

**Comment by khaledyoussef24** [comment]
verified transfer is now added to the new playground
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4412199b-caea-4d83-94c5-ddfb5b39e0e0)
