### ISSUE TITLE
Implement Dedicated Nodes in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1018]

**Comment by amiraabouhadid** [comment]
On hold till transfer page is complete

**Comment by amiraabouhadid** [comment]
On hold until #1090 is resolved

**Comment by AlaaElattar** [comment]
- The implementation of filters card is done, waiting to confirm the design with the rest of the team to make filters compatible in all pages.  
- Now working on implementing the table.

**Comment by AlaaElattar** [comment]
- still working on it but most of the page is done.

**Comment by AlaaElattar** [comment]
- All page is done except applying filters on table.

**Comment by AlaaElattar** [comment]
- working on apply pr comments

**Comment by AlaaElattar** [comment]
- waiting till explorer nodes pr is merged as there're methods shared between us.

**Comment by AlaaElattar** [comment]
- I've rebased my pr on explorer nodes, applied all pr comments and waiting for review.

**Comment by AlaaElattar** [comment]
- will reuse cards from node explorer pr, so i put it in draft.

**Comment by AlaaElattar** [comment]
- Cards applied and now look the same in dashboard. 
- waiting for review.

**Comment by AlaaElattar** [comment]
- Applied pr comments && fixed new issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1226

**Comment by AlaaElattar** [comment]
- working on fixing reload on gpu card.

**Comment by AlaaElattar** [comment]
- Gpu reload handled and waiting for review

**Comment by khaledyoussef24** [comment]
dedicated now is accessible 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a6e91f0c-ebc5-4ca7-8747-d0ba149765bf)
rented tab is removed 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9db030ac-58cb-4490-a54e-32128f3d2167)
gpu filtering options are also available 
info for every node (show details)is functional:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f23f78dc-f797-471a-88b4-046cec1ddfa4)
