### ISSUE TITLE
Implement DAO in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1019]

**Comment by amiraabouhadid** [comment]
On hold until transfer page is complete

**Comment by amiraabouhadid** [comment]
Done with templated. Adding voting functionality.

**Comment by amiraabouhadid** [comment]
Adding cast vote.

**Comment by amiraabouhadid** [comment]
on hold until UI design is finalized

**Comment by amiraabouhadid** [comment]
Implementing new UI design

**Comment by khaledyoussef24** [comment]
verified dao page is now in vue3

![Screenshot from 2023-10-08 10-25-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/660d00b4-49a8-4170-af2c-bf2ed0b1438a)
[Screencast from 10-08-2023 10:24:44 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/48146e15-d306-408c-a923-7505f4ea1856)
![Screenshot from 2023-10-08 10-24-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/63f803bc-a643-4424-a8f3-edd4aa312a2e)
