### ISSUE TITLE
Implement Explorer Nodes in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1020]

**Comment by Eslam-E-Hossni** [comment]
today I finished the:
- getting nodes in the table and pagination request
- Filter nodes by status

**Comment by Eslam-E-Hossni** [comment]
- Rewrite filter logic to solve multiple code
- finish filters and draw data in the table

**Comment by Eslam-E-Hossni** [comment]
- implement node details dialog
- Finished node details and added loading component
- working on node resources progress circle

**Comment by Mahmoud-Emad** [comment]
Issue updates:
- Enhanced the code logic
- Implemented a filter type
- moved the initialization of the filters inside the utils file to be with its types
- Implemented the filter component as style as @samaradel mentioned the issue

WIP:

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/e3e603f2-23b6-4b85-8a9f-f664c639f30d)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/5f3950d5-2193-4fa9-a4e1-7d982566160b)

**Comment by Mahmoud-Emad** [comment]
**Issue Update:**
- **Description:** The explorer nodes table has been implemented with the same design style, resulting in improved code structure.
- **Work in Progress (WIP):** Currently awaiting support from `http_grid_client` to incorporate the `GPU`, `Gateway`, `freePublicIps`, and `totalPublicIps` fields into the table data.

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/bb8efea8-0691-4d4f-9c1e-92a1509d30de)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b8c82575-b0a5-4275-8fec-4b03402bc4ba)

**Comment by Mahmoud-Emad** [comment]
Node details design : https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1090#issuecomment-1737415569

**Comment by Mahmoud-Emad** [comment]
WIP:
- Updated the `toReadableDate` function to return the node upTime if less than a day
- Updated the `getNodeStatus` function to return the `Stand By` nodes
- Updated the node tables
- Moved the node filters outside the explorer folder to be a reusable component
- Defined the `NodeFilters` as a global component
- Working on the node details dialog style and integration
- Set the nodeId as a query param on click to open the dialog on reload the page if there a value in the URL, and clear it when closing

**Comment by Mahmoud-Emad** [comment]
WIP: 
- Implemented the `GPU details card` [waiting on the issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1169) 
- Implemented the node public config card
- Enhanced the responsive
- refactored the code

**Comment by Mahmoud-Emad** [comment]
Update:
- Refactored the code
- Implemented the GPU card details

**Comment by Mahmoud-Emad** [comment]
Update:
- updated the `node details` component to make the request to get the node instead of requesting to get it from the `nodes` view
- updated the `node filters` component to disable the `Reset filter button` if no values in the form
- updated the `node filters` component with field validations
- worked on some comments made by @AhmedHanafy725 in the https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1129

**Comment by Mahmoud-Emad** [comment]
Update:
- Disabled the filter form while requesting for nodes
- Fix the GPU card details in the node details

**Comment by Mahmoud-Emad** [comment]
WIP:
- Update the GPU card details to accept more than one card and filter them based on the selection.
- Used the CustomToast that was created by @AlaaElattar with the custom type.

**Comment by khaledyoussef24** [comment]
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/96d512a1-237d-492c-8674-25b58c61d525)
works fine and filters also works fine
