### ISSUE TITLE
Implement Explorer Farms in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1021]

**Comment by ehab-hassan** [comment]
it'll be like that with the new filter and color 
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=528-1234&t=WHZwxIHMt9huGKI2-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by samaradel** [comment]
added selected farm and twin details

**Comment by samaradel** [comment]
working on filters

**Comment by samaradel** [comment]
worked on some UI in farms details dialog

**Comment by samaradel** [comment]
tables and filters were implemented in wrong scenario and, fixing them...

**Comment by samaradel** [comment]
The tables fixed and most of the filters

**Comment by samaradel** [comment]
fix filters and details dialog

**Comment by samaradel** [comment]
all is done and it needs pr review

**Comment by amiraabouhadid** [comment]
addressing 16 comments on PR

**Comment by amiraabouhadid** [comment]
Resolved 10 comments on PR, 6 more comments left to resolve.

**Comment by amiraabouhadid** [comment]
rewritten farm_dialog to address comments on PR.

**Comment by amiraabouhadid** [comment]
Making card details more dynamic.

**Comment by amiraabouhadid** [comment]
rewritten farm_details_card

**Comment by amiraabouhadid** [comment]
rewritten twin_details_card. Only filter farms remains to be fixed now.

**Comment by amiraabouhadid** [comment]
working on farm filters

**Comment by amiraabouhadid** [comment]
fixed farm filter by name. Working on reducing constants used.

**Comment by amiraabouhadid** [comment]
working on making filters applicable to both farms and nodes to reduce repeated code

**Comment by amiraabouhadid** [comment]
Work Completed:
submitted PR for review 

Work in Progress (WIP):
addressing comments on PR

**Comment by amiraabouhadid** [comment]
Work Completed:
Fixed filter

Work in Progress (WIP):
Pagination

**Comment by amiraabouhadid** [comment]
Work Completed:
 Pagination

Work in Progress (WIP):
Remaining comments on PR

**Comment by amiraabouhadid** [comment]
Work Completed:
Removed redundant code, made filters optional

Work in Progress (WIP):
Investigating nodes filter

**Comment by amiraabouhadid** [comment]
Work in Progress (WIP):
Investigating pagination malfunction

**Comment by amiraabouhadid** [comment]
Work Completed:
Added pricing policy and total public IP filter
Fixed pagination

Awaiting review on PR
