### ISSUE TITLE
Implement Statistics in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1022]

**Comment by maayarosama** [comment]
All done but need to make sure that Mr Ehab approves the design

**Comment by maayarosama** [comment]
Currently debugging why map component isn't showing.

**Comment by maayarosama** [comment]
Applied a  retrytofetchstats method that retries to fetch data 3 times before issuing an error alert to the user, currently waiting for a review.

**Comment by khaledyoussef24** [comment]
verified stats page is now on the new playground
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fa9bc9ca-8775-4928-b413-2bbe48224980)
