### ISSUE TITLE
Implement Calculator in Vue3

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1024]

**Comment by maayarosama** [comment]
Working on refactoring the resource pricing calculator, and still working on the simulator

**Comment by maayarosama** [comment]
Pr for resource pricing is ready and waiting for review. Currently resumed working on the simulator

**Comment by khaledyoussef24** [comment]
simulator related for this issue or got it's separate issue ?

**Comment by AhmedHanafy725** [comment]
> simulator related for this issue or got it's separate issue ?

it has a separate issue #1135

**Comment by khaledyoussef24** [comment]
calculator verified and working now

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4c991bdb-985d-47a0-92c7-2b83d90a473a)
