### ISSUE TITLE
Edit Playground Docs to include new Dashboard

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1029]

**Comment by 0oM4R** [comment]
will apply this structure in info_grid
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1464

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/info_grid/pull/303 please make sure to have a look here

**Comment by mohamedamer453** [comment]
Update:

Work In Progress:

Resolved the merge conflicts that were available in the branch and added docs for the following sections:

- Statistics.
- Nodes.
- Farms.
- Services.

**Comment by mohamedamer453** [comment]
Update:

Work In Progress:

- added docs for the calculators section.

- Updated the docs for the dashboard sub-section including:
   - wallet connector
   - dashboard home
   - twin
   - bridge
   - transfer
   - farms
   - dedicated nodes
   - contracts

- going over the solutions section and checking what needs to be updated.

**Comment by mohamedamer453** [comment]
Update:

Work In Progress:

- added missing sections from the dashboard.
- removed the old dashboard section from the docs.
- renamed the playground directory to dashboard.
- going over the docs to replace playground calls with dashboard.

**Comment by mohamedamer453** [comment]
Update:

Work in progress:

- replaced instances of playground with dashboard.
- fixed broken links that pointed to playground.

**Comment by mohamedamer453** [comment]
Update:

Issue is blocked on sidebar re-ordering https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1861 will wait till the sidebar issue is merged to re-order the docs section accordingly and update screenshots if needed

**Comment by mohamedamer453** [comment]
Update:

Work in Progress:

- Re-ordered the sidebar and added starter files for all of the new sections.
- Updated the branch and fixed merge conflicts.
- Added the following sections of the new sidebar.
   - TFGrid section
   - Deploy section
   - Farms section
   - TFChain section

**Comment by mohamedamer453** [comment]
Update:

Currently blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2104 & https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1389

Only screenshots for both pages are remaining for the docs to be completed.

**Comment by 0oM4R** [comment]
as we discussed, we will ignore #1389 currently
the remaining parts, as Amer mentioned 
- add deployment status in deployment table.
- update screenshots for all solutions 
  - vms and k8s is blocked on #1389

**Comment by 0oM4R** [comment]
Work in progress: 
updating solutions docs and screenshots

**Comment by 0oM4R** [comment]
Work completed:
all application updated

**Comment by 0oM4R** [comment]
Work In progress:
resolve conflicts on SUMMARY file

**Comment by khaledyoussef24** [comment]
verified on [dashboard](https://manual.grid.tf/dashboard/dashboard.html)
docs are now organized with the same lay out of the new dashboard
![Screenshot 2024-02-27 at 3 45 35 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ba096a87-57d5-4c65-9407-cac080ec07f5)
![Screenshot 2024-02-27 at 3 46 29 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e5ab0a84-6ecb-45c2-8a64-e91c2862497c)
checked the latest changes in organizing the docs and the deploy section for the solutions and applications to be clear
