### ISSUE TITLE
document the repo structure and configurations

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#103]
- the setup
- CI configs
- the release process

**Comment by mohamedamer453** [comment]
Verified.

All of the mentioned points were documented and can be found in the following links.

- [Setup](https://github.com/threefoldtech/tfgrid-sdk-ts#tfgrid-sdk-ts)
- [CI](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/docs/workflows.md#workflows)
- [Release Process](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/docs/release.md#releasing-process)
