### ISSUE TITLE
Adding max validation to dedicate node filter inputs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1032]
### Description

Filtering stops working when the number input to any dedicated node filter exceeds 12 digits.

### Logs/Alerts

[Untitled_ Aug 21, 2023 2_11 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/23ecc22c-8dc3-4403-ad9f-cc2c7d675f62)

**Comment by khaledyoussef24** [comment]
is it deployed on the current dashboard or pending to the newplayground ?

**Comment by AhmedHanafy725** [comment]
> is it deployed on the current dashboard or pending to the newplayground ?

it's not deployed yet on devnet

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

Max-digit validation has been added to the dedicated node resource filter.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/13f43313-c8fb-4040-870a-6c7e17ccc442)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/353d3adb-d7ff-4410-8378-42c5e7433ec4)

[TC2225 - Filter dedicated nodes by Total SRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150434)
[TC2226 - Filter dedicated nodes by Total HRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150435)
[TC2227 - Filter dedicated nodes by Total MRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150436)
[TC2228 - Filter dedicated nodes by Total CRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150437)
