### ISSUE TITLE
Should have same result when there's no dedicate node match the filter 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1034]
### Description

The result of filtering in dedicate nodes table when there's no node matches the filter is 'No data available' but in some cases it shows 'No matching records found'. 

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f75df0c8-644d-4b7a-8b89-41d9e56eabe0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c64560ae-7b23-461c-a4e1-b9120a209ad0)

**Comment by samaradel** [comment]
cannot reproduce it, @A-Harby will create a scenario

**Comment by A-Harby** [comment]
the issue is hard to reproduce but it keep causing a fail in the automation tests and it seems to be randomized, I will close the issue and try the same tests on the new dashboard when it's released.
