### ISSUE TITLE
Add Warning in Contract Lists

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1041]
Perhaps we could add warnings in the contract lists page: https://playground.grid.tf/#/contractslist

Users could easily delete a contract that is linked to their workloads.

Some contracts are add-on to the main contract.
So for example, a user deploy a full vm. In the full VM page, we see only one contract. But in the contractslist, the full VM has different contracts tied to the main contract.

We could either explain clearly which contracts are "linked" one another. Or write that to delete a contract, it is better to go to the main workload page (in this example, it would be full VM). Or simply warn users that those contracts in contracts lists are tied to one another thus it would be wise to be careful when deleting such files.

**Comment by A-Harby** [comment]
Verified, Devnet f86490f.

warning was add in the contract list, advising user to delete the deployment from its solution page
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/05d5da0d-4cb0-4d02-addd-2d7d0bd9a4ac)

Test case:
https://app.testlodge.com/a/26076/projects/40893/suites/227225?expand_section=397796#case_3958871
