### ISSUE TITLE
simulator updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1042]
- update the net profit scale to start by 0.01 to reflect the reality 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/98e8cab6-6794-4cee-9acd-eb352f66bdb9)

- token price after 5 years = 1$ as default (if not already set)
- changes to max token price should reflect on the graph x-axis
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/4ae963dd-b25c-4b15-a53d-edb7fe6aa54d)
> start at 0.01, end at max token price and choose arbitrary 10 points between

**Comment by AhmedHanafy725** [comment]
@maayarosama please check if this has been done on the new simulator

**Comment by maayarosama** [comment]
As it's not merged to the development branch in [tf-farming-calculator](https://github.com/threefoldtecharchive/tf-farming-calculator), it's not deployed on the new simulator. I'll do it tomorrow.

**Comment by khaledyoussef24** [comment]
start at 0.01, end at max token price and choose arbitrary 10 points between
![Screenshot from 2023-10-25 07-09-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/19d9ef5b-92bc-499a-a3d4-2aa0cb42ac7f)
start by 0.1
![Screenshot from 2023-10-25 07-04-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b956dcd6-be06-4f09-be2d-2a67d22017f7)
