### ISSUE TITLE
links for next cloud docs are not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1044]
docs links for next cloud are not working
https://www.manual.grid.tf/playground/nextcloud.html
![Screenshot from 2023-08-24 16-05-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6493f5f8-bddb-48b3-a1d3-64823f516a52)
https://www.manual.grid.tf/playground/nextcloud.html#set-the-dns-record
![Screenshot from 2023-08-24 16-05-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e721fa75-7d99-4a1a-9df3-d9c0681e1c72)

**Comment by Mik-TF** [comment]
Exactly it is solved with [Info_grid PR 240](https://github.com/threefoldtech/info_grid/pull/240)  but I can't merge myself since I need an approval from another code owner of info_grid.

**Comment by Mik-TF** [comment]
I updated the Nextcloud docs [here](https://github.com/threefoldtech/info_grid/pull/240) based on feedback from [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1047).

We will be able to close this issue once the PR is merged.

**Comment by Mik-TF** [comment]
This issue will be solved when the docs are updated on the manual.

Note that we will be updating the nextcloud weblet with gateway support. We will publish the docs and the new weblet when the gateway version is ready.

For this reason, I will close the issue for now.

**Comment by khaledyoussef24** [comment]
reopening the issue until it is found on the playground then we can close it

**Comment by Mik-TF** [comment]
@khaledyoussef24 I agree that makes sense.

Once the new Nextcloud version with gateway is published on the playground, with the corresponding docs in the manual, we will be able to close the issue.

Thanks Khaled!

**Comment by khaledyoussef24** [comment]
merged and verified all next cloud docs are now working @Mik-TF  thanks
