### ISSUE TITLE
Hide nextcloud

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1049]
Until all Nextcloud issues get resolved, the solution should be hidden from development.

**Comment by khaledyoussef24** [comment]
devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b05c55ce-df2b-420d-8eda-94a95abc054c)
verified on devnet waiting to be deployed on qanet too
qanet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7fedadaa-9b21-4d9a-986b-ec2f0741c912)
