### ISSUE TITLE
Add actions to vms to add/remove gateway workload to/from a vm

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1055]
Parent issue: https://github.com/threefoldtech/home/issues/1452

- User should be able to attach name gateway or FQDN gateway workloads to a VM.
- Add a link for the gateway on the vm workload so we can list the gateways attached to the vm
- From the listed gateways, the user should be able to remove any one of them.

**Comment by MohamedElmdary** [comment]
Still investigating error while listing deployments
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/5e199154-8656-44e6-9438-b97213f19b19)

**Comment by MohamedElmdary** [comment]
Issue found and fixed

**Comment by MohamedElmdary** [comment]
PR should be ready to be merged 
- Add prefix for fvm/vm deployed gateways
- add mirgration for old solutions gateways

**Comment by MohamedElmdary** [comment]
Contracts listing doesn't get updated correctly due to https://github.com/threefoldtech/tfchain_graphql/issues/135

**Comment by A-Harby** [comment]
Devnet c9f2406.

A new tab was added to add a gateway to deployment.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c4b9a82-371f-4322-86e8-ae1f2f3b939e)
And it was successfully deployed and added to the VM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1d10bbd4-4208-45ab-a9f2-d9d7dca03f64)
Listing to the gateways on FullVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/00791c01-aa40-4fea-8c1b-47dd66782669)
with TLS and on MicroVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/73b73214-a2c2-4214-b0e3-3bd7f7e928ee)
Delete option, and it was successful.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c2a2cbf9-766d-4e16-88c8-b5c19840ef17)

**Comment by xmonader** [comment]
While this looks great, the terms we are using aren't 100% accurate :(

**Comment by A-Harby** [comment]
The only issue I found is that after deploying a VM and adding a gateway to it,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/86ee73e4-71b6-47b2-adae-4f5e08ff594d)
I tried to delete it from deployment list, 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9c5772e2-b85f-4cd5-9f75-345d8e801a70)
But the gateway wasn't deleted after.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aa045185-f6ad-49a5-9f6e-14d352c6587e)

**Comment by MohamedElmdary** [comment]
@AhmedHanafy725 Should we handle deleting gateways (when we delete it's deployment) in playground or grid_client?

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 Should we handle deleting gateways (when we delete it's deployment) in playground or grid_client?

playground

**Comment by MohamedElmdary** [comment]
Should be fixed but wasn't able to test it as gql in devnet is down and for some reason qanet not fetching my balance !

**Comment by A-Harby** [comment]
Verified, Devnet 2b364e9.

Adding and listing new domains were successful.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f8a6d04a-6d16-4fbe-94a2-0e64ac699651)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6a9227f4-de94-4ea5-b77f-fc06128a095b)
And deleting the main VM deletes all domains attached to it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7b0a2e0b-fb66-4ec4-a652-850dfa5f72e4)

**Comment by MohamedElmdary** [comment]
Found an issue related to passed keys while moving a value in kvstore

**Comment by MohamedElmdary** [comment]
@A-Harby Will add docs for it

**Comment by ramezsaeed** [comment]
verified all functionality on:
    - Devnet
    - version: 5b5a870


Docs will be followed up here: https://github.com/threefoldtech/info_grid/issues/304
