### ISSUE TITLE
3script editor component

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1057]
parent issue: https://github.com/threefoldtech/home/issues/1461

should be in a new package called threefold/ui

**Comment by zaelgohary** [comment]
Created a simple form for the script editor using Tailwindcss. Will refactor the design tomorrow.

**Comment by zaelgohary** [comment]
Edited the design so it would have line numbers and a copy button. currently working on converting the editor to a web component.

**Comment by xmonader** [comment]
can't we use codemirror directly? https://codemirror.net

**Comment by zaelgohary** [comment]
@xmonader We could but using Tailwindcss was one of the requirements. That's why I've built the editor from scratch.

**Comment by zaelgohary** [comment]
Converted the editor to be a custom element which will be a web component once built. Also, included the signer and used tf-wallet-connecter to get user mnemonics. The component is ready to be used.

**Comment by zaelgohary** [comment]
Added docs.

**Comment by zaelgohary** [comment]
Edited script editor to use TF connect provider.

**Comment by A-Harby** [comment]
Verified, 
Docs were added https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/UI/README.md,

Script editor is working with mentioned steps in the docs, With threefoldSignerProvider and threefoldConnectorProvider.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b931104b-9661-4c77-9877-96d38fbc6cf5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/deda4d69-50d8-4322-b4e7-da0063dd1d09)
