### ISSUE TITLE
Network error will cause the listing inputs to load forever

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1061]
### Description

When you are trying to list a farm name, country or nodes and a network error happens the listing input will keep loading forever.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1907181-2018-4c86-8d70-545823c430d2)

**Comment by ramezsaeed** [comment]
Refresh can fix this

**Comment by maayarosama** [comment]
Closing in favour of #1306
