### ISSUE TITLE
[WordPress] The password generated shouldn't contain space

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1062]
### Description

If the password has a space the deployment will be okay, but the solution itself will be broken.

### Steps to reproduce

- Go to WordPress solution.
- Update the password to contain a space.
- Deploy the instance.

### Logs/Alerts
The password was `8 D!eomkm0RX`.

zinit logs for wp process.

```
[-] wp: Error: Too many positional arguments: D!eomkm0RX
[-] wp: + chmod +x /usr/local/bin/wp_entrypoint.sh
[-] wp: + cd /var/www/html
[-] wp: + a2enmod headers
[+] wp: Module headers already enabled
[-] wp: + /usr/local/bin/wp_entrypoint.sh apache2-foreground
```

**Comment by AhmedHanafy725** [comment]
The generated password shouldn't contain space, and the validation shouldn't allow that

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2023-09-24 11-47-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66d00c53-dc82-49b8-b524-d12dc7bb2612)
