### ISSUE TITLE
Node v18^ specified, but v20 is not supported

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1065]
The README.md specifies `Node.js 18^`, but `yarn install` shows this when using `node v20`:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@achrinza/node-ipc@9.2.6',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18 || 19'
```

**Comment by ramezsaeed** [comment]
we support the latest LTS (18)
will be fixed in the repo Dccs.

**Comment by A-Harby** [comment]
Verified,

Docs were updated `^18`, I'm using v18.16.1 and it was installed successfully.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2435413-67dc-4e2b-a744-10594b0790d1)

Test case:
https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3360449
