### ISSUE TITLE
Support gpu nodes filter and total public ips, free public ips in response in tf_gridproxy_client

### ISSUE THREAD

**Issue by Eslam-E-Hossni** [threefoldtech/tfgrid-sdk-ts#1068]
### Description

Filtering by GPU is missing in the tf_gridproxy_client supported, and the response also doesn't support total public IPs and free public IPs.

**Comment by Mahmoud-Emad** [comment]
@Eslam-E-Hossni 
Please don't assign developers to issues, new issues get sorted by component owners, and based on the priority, it get in the pipeline.

**Comment by Mahmoud-Emad** [comment]
Closed as implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1125
