### ISSUE TITLE
Add Get TFT button

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1070]
### Description

New to add a get TFT button in the new Vue3 portal integrated in playground

**Comment by AlaaElattar** [comment]
- For now it's fixed by connecting again to client before transferring with Alice account.

**Comment by khaledyoussef24** [comment]
verified 
[Screencast from 10-02-2023 01:32:53 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/303a7fe8-153b-45a7-862b-f17a768bd0eb)
