### ISSUE TITLE
Add TFT-USD exchange rate

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1072]
### Description

Need to add TFT-USD exchange rate in new Vue3 portal in playground

**Comment by AlaaElattar** [comment]
- The position of exchange rate update after merging `Get TFT` button.

**Comment by khaledyoussef24** [comment]
verified now the position of the get tft button is changed and exchange rate is added 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/17e2eb28-b2e7-41b7-914b-f3ea399f3acb)
