### ISSUE TITLE
Add package for graphql client

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1073]
package name: `@threefold/graphql_client`

package to move: https://github.com/MohamedElmdary/tfgrid-gql

**Comment by A-Harby** [comment]
Verified, development_313
Package was added, docs updated and build ran successfully.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7ca1dd7d-1bb6-4fb1-b393-9b0a041b8de7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7874ed33-88f6-46d9-9f43-57287002f288)
