### ISSUE TITLE
some UI changes at deployment 

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1082]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/2aa1641c-fb72-47ec-9215-9bbba6199755)

Please make the icons smaller by 60%.
Make icons and titles on the same line(one row).
it would be nice if we had some hover at the card(optional)

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f1565c9a-3cca-4d0c-9472-3a01853ded74)
icons are now smaller and the solution tab is more clear
