### ISSUE TITLE
Add Dao

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1087]
### Description

Add a dao module with the following functions: 
- get: gets proposals both active and inactive
- vote: casts vote on a proposal based on voter's selected farm id

### Implementation

transfer functions in threefoldtech/tfgrid-sdk-ts/packages/dashboard/src/portal/lib/dao.ts to grid client Dao module

**Comment by amiraabouhadid** [comment]
added dao to tf chain client

**Comment by amiraabouhadid** [comment]
Working on comments received on PR

**Comment by amiraabouhadid** [comment]
removing type any from modules

**Comment by A-Harby** [comment]
When I tried `get _dao_proposal` script, it returned some error first before listing the proposals like below
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/310a4f24-fcf6-4612-927c-2b99fc0970a4)

And when I checked the proposal list it showed a 16 proposal
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/69a85664-6e7a-491c-a10f-f7eb8c5a180f)

And only 9 proposal were displayed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8fd82452-c05d-48c5-a4b2-07997863edc4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9ee74926-6c42-4b6d-bc02-ee53760c47cd)

**Comment by amiraabouhadid** [comment]
Please refer to #838

**Comment by A-Harby** [comment]
Verified,
Get Dao prospal is working correctly except for 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/82291638-c133-421d-b594-e02a4197e277)
I voted twice with 2 different twins true and false.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4852434a-26d5-4a49-adbc-f5d79213d5ce)
It was reflect and updated
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/104de1fd-76f9-4d00-9a1b-0bb24fc3d907)

@amiraabouhadid but last thing missing, can log both ayes and nayes array like
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/650579b2-bc50-4759-813f-77b04a0d4984)

**Comment by amiraabouhadid** [comment]
Noted, thanks @A-Harby . Working on returning ayes and nayes array in client

**Comment by amiraabouhadid** [comment]
client returns ayes and nays as arrays that follow the ayesandnaysInterface as shown [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/47902288c319d3769a17f876af4f5286e397aabb/packages/tfchain_client/src/dao.ts#L7) so do not see an issue in ayes and nayes in client

**Comment by A-Harby** [comment]
> client returns ayes and nays as arrays that follow the ayesandnaysInterface as shown [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/47902288c319d3769a17f876af4f5286e397aabb/packages/tfchain_client/src/dao.ts#L7) so do not see an issue in ayes and nayes in client

Close issue as fixed, get, vote function were added.
