### ISSUE TITLE
Missing pages in Dashboard design

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1090]
The Figma design is missing the following pages:
- [x] dedicated nodes page & its details
- [x] DAO
- [x] portal/farms & its details
- [x] explorer/farms details
- [x] explorer/nodes details

P.S. the prototype is not working also

**Comment by ehab-hassan** [comment]
for the Dedicated nodes page & its details 
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=746-2176&t=lRw4nz0GC8f04ODp-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by ehab-hassan** [comment]
portal/farms & its details
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=27-1448&t=hEzpxi5RIPCl9UpQ-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A1248

Figma file
https://www.figma.com/file/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=1-1248&mode=design&t=hEzpxi5RIPCl9UpQ-0

**Comment by ehab-hassan** [comment]
DAO
no major changes just new color and font size
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=54-2667&t=zNC6x0dPbosoH4bW-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A1248

Figma file
https://www.figma.com/file/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=54-2667&mode=design&t=zNC6x0dPbosoH4bW-0

**Comment by ehab-hassan** [comment]
explorer/nodes details
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=995-2265&t=pseOHqmCL4lV1iTE-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by ehab-hassan** [comment]
explorer/farms details
Same at Nodes
