### ISSUE TITLE
(Mainnet Verification) Improve ux when selecting nodes

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#1091]
We should start off by showing all nodes and then narrowing it down with filters if needed.

e.g. If I'm looking for a node it doesn't matter to me if it's certified or not so I should be able to see all of them. If then I want a certified, dedicated or GPU node, I can choose those so it filters the results.

**Comment by RoberL72** [comment]
I thought the idea was for certified nodes to show up first.
And; how do we inform the benefits of silver and gold farms?

**Comment by maayarosama** [comment]
WIP:
- trying to show all certified/uncertified nodes at first without applying filters

**Comment by maayarosama** [comment]
Still investigating

**Comment by maayarosama** [comment]
Couldn't investigate on development as graphql was down

**Comment by maayarosama** [comment]
Work Completed:
- Added a chip for certified nodes
- All nodes load regardless of the certified filter at first
Work in Progress (WIP):

Investigation and Solution:
- Investigating why does it retrieve the certified nodes even when the filter is false

**Comment by maayarosama** [comment]
Work Completed:

- Added a watch for the selectedNode so it the calculator recalculates.
- Added a warning within the calculator div telling the user that a certified node is being used.
- pr is pending review.

Work in Progress (WIP):
Investigation and Solution:

**Comment by maayarosama** [comment]
Work Completed:

- Added a condition to recalculate cost when the certified filter is off but the user chooses a certified node
- pr is ready for review

Work in Progress (WIP):
Investigation and Solution:

**Comment by A-Harby** [comment]
Verified, 
Devnet, 3fc8787.

All the nodes are now shown for the user first, and three toggles have been added: GPU, dedicated, and certified to specify node type; also, node region, country, farm name, and ID can be specified.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/23fdf720-b440-4ded-8a7d-118686d7abc9)

**Comment by ramezsaeed** [comment]
cannot find a certified node to test the calculator is working as expected
- devnet
- ebf75a3

![Screenshot from 2023-12-24 12-28-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/feb27c47-2a34-4101-a566-da0d07c37f39)
![Screenshot from 2023-12-24 12-27-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/2681dbca-766b-4cd3-bc28-34cf2bef57b6)

**Comment by maayarosama** [comment]
@ramezsaeed There's no certified nodes on devnet, you should test against mainnet.

**Comment by khaledyoussef24** [comment]
verified on : dashboard.bknd1.ninja.tf
version : 2.3.0-alpha6
![Screenshot from 2024-01-22 08-47-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/402fd3e7-da10-43dd-87e0-ca03211991f9)
![Screenshot from 2024-01-22 08-46-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9ab57b1e-863e-46c6-a755-b7ea81febcca)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/547b2cbf-2441-49b2-8f84-9976a78635e0)

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet (Ninja)
- 2.3.0-alpha6


![Screenshot from 2024-01-22 12-55-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/023d79d8-16ee-4046-8dcf-1a5ac9aaed71)
