### ISSUE TITLE
GPU name filter validation in dedicate node should allow special char

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1095]
### Description

GPU'S VENDOR NAME and GPU'S DEVICE NAME Filter input validation in dedicate node should allow some special character as GPU card name can contain them like `[ ] / , .`

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1b420eae-ca68-41a4-afcf-a67daab8c7a9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/37c7a8bc-5b4a-4398-94cb-c01e7cb4d5e1)

**Comment by AlaaElattar** [comment]
- fixed and handled in dedicated node pr

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

The filter validation now accepts special char [ ] / - , .
https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up&ret_count=true&size=10&page=1&gpu_vendor_name=amd%20[gpu/test]&gpu_device_name=amd%20[gpu/test]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7f576a9c-5b71-4888-8bc8-7f987a3e4189)

[TC2230 - Filter dedicated nodes by GPU's device name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150439)
[TC2229 - Filter dedicated nodes by GPU's vendor name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150438)
