### ISSUE TITLE
UI: the Manage worker button on light mode is invisible.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1097]
### Description

the Manage worker button on light mode is invisible.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ab7947d2-daac-4b39-bfe6-240dd7db8e3b)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3085b38f-5499-42b8-9773-8eca92b60706)

**Comment by A-Harby** [comment]
A lot of buttons on different solution is like that
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a54819d4-24e7-4b9f-97f8-f4681d78f9eb)

**Comment by zaelgohary** [comment]
All action buttons are the same color now.

**Comment by A-Harby** [comment]
Verifed, 2.1.1.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/abb2a1eb-b077-4be0-80a0-46b44d0794ab)
