### ISSUE TITLE
(Mainnet Verification) Node 3988 is not working properly on Mainnet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1098]
### Description

Node 3988 is not working properly on Mainnet, (Farm name gtdu).

1. It gave an error when trying to deploy with public IPs
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b24a49ee-2771-4510-aa9a-63ddfd89d1c0)
2. It kept loading when trying to deploy with default FullVm input.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/529dbf8d-7ad6-4b6a-acaa-5466f580a530)
3. And in some cases it give an error and you can't deploy on it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a5a2647a-2d59-4ee8-a11e-a2e56cda9e88)

**Comment by AhmedHanafy725** [comment]
tried to ping the node but got no response. 

also, this farm has fake public ips

```json
[
  {
    "name": "gtdu",
    "farmId": 33,
    "twinId": 168,
    "pricingPolicyId": 1,
    "certificationType": "NotCertified",
    "stellarAddress": "GCCREPBLPLYQNKWTP4KIXYNUXU7KJMBSNDMR7Q6TE22LCFWTTXLBBDXG",
    "dedicated": false,
    "publicIps": [
      {
        "id": "0000504515-000001-2534b",
        "ip": "192.168.1.19/24",
        "farm_id": "",
        "contract_id": 0,
        "gateway": "192.168.1.1"
      },
      {
        "id": "0000456919-000003-5180b",
        "ip": "192.168.1.5/24",
        "farm_id": "",
        "contract_id": 0,
        "gateway": "192.168.1.1"
      },
      {
        "id": "0000504502-000001-e554f",
        "ip": "192.168.1.7/24",
        "farm_id": "",
        "contract_id": 0,
        "gateway": "192.168.1.1"
      },
      {
        "id": "0000504509-000001-b9c14",
        "ip": "192.168.1.14/24",
        "farm_id": "",
        "contract_id": 0,
        "gateway": "192.168.1.1"
      },
      {
        "id": "0000147533-000001-b2387",
        "ip": "192.168.1.10/24",
        "farm_id": "",
        "contract_id": 0,
        "gateway": "192.168.1.1"
      }
    ]
  }
]
```

**Comment by AhmedHanafy725** [comment]
when checking the farm from the chain, found that the public ips are deleted, but these ips still shown from gridproxy and graphql which means the data from the chain is not synced with graphql

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/d64ed0e1-2798-42a4-8f4e-654143648b23)

**Comment by A-Harby** [comment]
> 2. It kept loading when trying to deploy with default FullVm input.
>    ![image](https://user-images.githubusercontent.com/109473873/267587621-529dbf8d-7ad6-4b6a-acaa-5466f580a530.png)


Apparently in this case the deployment didn't cascade and deleted the contracts.
But I can't list them in the FullVM deployment list or ssh them.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1afff6c8-0710-4af0-ad74-01257e252fa5)

**Comment by muhamadazmy** [comment]
The Node seems to be responding to rmb pings. 

Logs does not show any errors in the last 3 hours, but the node shows this 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10920323/ef2305d8-9e96-4e74-a169-2b7c4ae0955f)

from provisiond.

I am worried that the timeout might be from the rmb client from the dashboard side! (the TS client implementation) I have no proof of course of that, someone with TS experience need to take a look.

Looks like listing works, so i guess it might be a client issue in the dashboard ?

**Comment by khaledyoussef24** [comment]
node is down 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f739d896-74e4-4d0c-a762-9dfa99ae9f3b)

can not produce the same issue again or even can not deploy anything on the node


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/441b19d4-62d1-4e91-b9c4-c0b1147d2070)
