### ISSUE TITLE
gateways to support wireguard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#11]
please check https://github.com/threefoldtech/terraform-provider-grid/issues/573#issue-1623656111

**Comment by mohamedamer453** [comment]
Verified on devnet.

Firstly i deployed a vm with the `addAccess` option set to true and ran s simple python http server on it.

Then i deployed a name gateway and passed the same network name to it and used the private ip of the vm to deploy it. and the gateway was deployed on the same gateway node where the node had its wireguard config added.

and the gateway was successfully deployed and worked without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e25724ed-91c2-4d16-a1bb-c29097f997af)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ef2efbe4-9240-43c6-84c9-24e5867eedfb)
