### ISSUE TITLE
`Invalid query:` error keep shown while listing the nodes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1100]
### Description

This error occurred to me multiple times while listing or validating the node in different solutions.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/818faad3-c8f4-4962-983e-221726270100)

**Comment by Mahmoud-Emad** [comment]
I've made multiple attempts to reproduce this issue on the Mainnet, but it appears to be working without any problems. I even recorded the process, and you can take a look at it:

[Screencast from 09-14-2023 02:31:41 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f8ee8f79-a1c2-4025-bcea-52e6fefb81b7)

Additionally, I used the same query you provided to request the grid proxy with the [exact query](https://gridproxy.grid.tf/nodes?free_mru=1073741524&free_sru=54211379200&free_hru=&free_ips=&ipv4=&ipv6=&gateway=&certification_type=&farm_ids=1&farm_name=&country=&city=&dedicated=&available_for=7885&status=up&page=&size=&has_gpu=&rented_by=&rentable=), and I received a successful response with no errors.

If you're still experiencing the same issue, could you please provide me with detailed steps to reproduce it on your end?
Thank you.

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1101

Both of this issues are related to the network being slow or connection error, same happens when trying to connect to the gridproxy or graphql and it fails.

You can see the network error in the console but playgorund doesn't display it and you can processed with deployment which cause more error after.

But this error are happening a lot on the mainnet cause it have a lot of farms and node, and I think playground need some kind of a network error handling to avoid this error.

**Comment by Mahmoud-Emad** [comment]
Update: 
I have a solution that I can do, to change/improve the error message.

**Comment by Mahmoud-Emad** [comment]
Update:
The error message should be improved here https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1111

**Comment by A-Harby** [comment]
Verified, Mainnet 2.1.1.
Error message was improved.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9da85026-6a23-4484-8dba-eba7579213d1)
