### ISSUE TITLE
Increase max number of attempts in RMB Client

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1102]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/26107be5-3410-4c9b-ac1d-856777cad901)

**Comment by zaelgohary** [comment]
I increased the max limit & the interval time. Reconnection happens [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/ac87ee3162f4d7b642e5efac2fa87def6b24db5b/packages/rmb_direct_client/lib/client.ts#L57) so no need to reconnect again.

**Comment by A-Harby** [comment]
Verified, Mainnet 2.1.1.

Tried many times and Error message didn't appear.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ebf9a31f-bd06-43c0-9655-0616b6c1ecdc)

Closing issue as fixed and re-opening if it re-appear.
