### ISSUE TITLE
(Mainnet verifications) Some nodes are shown twice in nodes explorer

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1106]
### Description
Mainnet, 2.1.0.

In some cases there is more than one node retrieved from the same node ID in the nodes explorer.

e.g Node ID 5012 show the same node twice. 
https://gridproxy.grid.tf/nodes?ret_count=true&size=10&page=1&status=up&node_id=5012

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7d641d66-8b65-43c0-9e6b-f57f3d944426)

**Comment by A-Harby** [comment]
Same happens in the dedicate node page
[Untitled_ Sep 14 2023 2_11 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f582f2e2-3613-4867-a05f-89edb3a9cee9)

**Comment by Omarabdul3ziz** [comment]
it is a problem on gridproxy, opened an issue on sdk-go repo [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/387)

**Comment by khaledyoussef24** [comment]
env used : mainnet
version : 2.2.0

verified issue is no longer reproducible 
tried many cases 
![Screenshot from 2024-01-16 13-13-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/035cf3b3-c811-45ac-8c8e-53883bf32a7e)
![Screenshot from 2024-01-16 13-12-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/47ca295e-f7d6-4f47-8384-dc55d6ce739e)
