### ISSUE TITLE
Support hex secrets in login flow (and ed25519)

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1113]
The recent update dropping Polkadot extension from Dashboard login leaves us in a bad situation:

1. Many farms were created with the TF Connect app. They belong to a twin that's associated with a hex secret only, not a mnemonic
2. Hex secrets can't be used to log into the dashboard, so farm management and the bridge aren't available (these features aren't in the app)

Supporting hex secrets for dashboard login is important to providing full services to all of our users, and I think it should be added urgently.

### ed25519

It also looks like the dashboard only supports the sr25519 key type. It was previously possible to create accounts with ed25519 key type using the Polkadot extension (I have one such account). This is perhaps less urgent because I don't think there are as many of these accounts as there are accounts created through the TF Connect app, but it still represents a fraction of users who can no longer use the Dashboard features that require authentication.

**Comment by maayarosama** [comment]
Work Completed:
- Added the select field for the keypair type
- Added The warning

Work in Progress (WIP):
- passing whatever is selected to the grid client in the keypairType option

Investigation and Solution:

**Comment by xmonader** [comment]
I think we shouldn't allow the generation of ED keys (just allow importing them)

**Comment by maayarosama** [comment]
Work Completed:
- Disabled creating nee account when using hex seed
- passed the KeypairType to the grid

Work in Progress (WIP):
- the positioning of the select field 

- saving the keypair type as a static value somewhere same as mnemonic

Investigation and Solution:

**Comment by maayarosama** [comment]
Work Completed:

- Re-validationg when keyPair change
- Enhancements to warning alert
- Adding an alert in case of choosing ED key telling the user that generation of ed keys isn't supported


Work in Progress (WIP):

Investigation and Solution:

**Comment by khaledyoussef24** [comment]
blocked on #1690 to verify that we can create a twin with a hex seed also

**Comment by khaledyoussef24** [comment]
env used : devnet
version used : 228c723
verified now user can log in and activate account from mnemonic and hex seed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31b5b19f-14ff-4354-82f9-623ead179df1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bbfad00c-793d-4b73-a6f9-22143d8d10f2)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4161528

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d
