### ISSUE TITLE
research: using bun for build, dev flow, workflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1116]
check: https://bun.sh/

**Comment by 0oM4R** [comment]
## so far we can't use bun with lerna
- bun support only package management for monorepo 
   `Bun supports [workspaces] in package.json. Workspaces make it easy to develop complex software as a monorepo consisting of several independent packages.` i tried to use `bun install`  and worked very fine 

### The impediments 
- lerna supports `yarn, npm and pnpm`only as task runner to execute the scripts e.g. `lerna run build`

- bun docs is not mentioning anything about versioning and release, i believe those features are essential  for our workflows
- bun is missing some Node js APIs, I'm not sure if this will effect our project or not please check [Node.js compatibility](https://bun.sh/docs/runtime/nodejs-apis)
