### ISSUE TITLE
Update balance after transactions

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1118]
### Description

A method to trigger balance displayed in playground to update after transactions is needed.

### Implementation

If you've a specific approach to discuss, describe it here clearly.

**Comment by khaledyoussef24** [comment]
verified now balance is updated instantly after transactions 
[Screencast from 10-02-2023 01:32:53 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1af3c24-04c1-44b5-86d2-8833e824f1bf)
