### ISSUE TITLE
Missing steps in docs of running the UI package

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1127]
### Description

I followed all the instructions below, cloned, ran the build command, and then copied the JS and CSS files from the dist into my project, but what now?

what's next because the example just jumped into the localhost and network and they weren't mention in the instructions? 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/abdb401a-d236-4bb9-a502-304c49a85cc9)

**Comment by Mahmoud-Emad** [comment]
@A-Harby,

To serve your static HTML file, you can follow the steps outlined in the linked pull request where I have updated the documentation.

**Comment by Mahmoud-Emad** [comment]
I just tried and it worked smoothly 

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/385934cf-282d-48d8-9e2e-707aed8ca242)

also you can use yarn

**Comment by A-Harby** [comment]
> I just tried and it worked smoothly
> 
> * ![image](https://user-images.githubusercontent.com/57001890/269577977-385934cf-282d-48d8-9e2e-707aed8ca242.png)
> 
> also you can use yarn

Linitng error was solved with yarn (I had some problem with my npm)

**Comment by A-Harby** [comment]
@Mahmoud-Emad 
is this the correct path?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/248e14c2-814b-45e3-8476-5b73ef938b34)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
No, the examples moved out of the src directory, i updated it in the mentioned PR

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/70921834-308b-4293-95e4-734c32e4c097)

**Comment by A-Harby** [comment]
@Mahmoud-Emad 
Path is wrong and command is for copying file not folders
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/295e6915-1c4a-4a92-8a9f-0b8400f5755a)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1174

**Comment by A-Harby** [comment]
This should be added to the steps and be in first (in both pdf signer and script editor), cause it important to be done before build.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b9d6a9a2-4b09-4a0c-a5f8-1328de1cbecf)

**Comment by A-Harby** [comment]
Also UI should be add to the repo [readme](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/README.md)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/906ea0dd-6460-4fc8-b13e-8cefb172df3c)

**Comment by A-Harby** [comment]
Docs need more clear info to descripe pdf link.
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1181

**Comment by A-Harby** [comment]
Verified, Docs were Updated with good clear detail steps and Test Suite was created beside on it https://app.testlodge.com/a/26076/projects/40893/suites/233575
