### ISSUE TITLE
Suggestion: improve UX 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#113]
When users go to dashboard.grid.tf, it immediately asks them to download the polkadot extension to access the portal. But not everyone has a farm or needs to connect this to the dashboard. Some just want to see information on the explorer.

I would suggest that the first thing you see would be:

- Button to attach your wallet/farm to the dashboard
- Button to go to the explorer

**Comment by AhmedHanafy725** [comment]
already done the current dashboard.
