### ISSUE TITLE
Implement Simulator in Vue3

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1135]
### Description

Implement simulator in vue3
### Implementation

Implementation should be in vue3/ts

**Comment by maayarosama** [comment]
Currently working on a bug where we you switch between basic and advanced, the graphs disappear.

**Comment by maayarosama** [comment]
Done with :
- Using [vue-chartjs](https://vue-chartjs.org/guide/#creating-your-first-chart) instead of chart.js 
- Adding a line chart component
- Adding a pie chart component

Currently working on converting the FarmingProfile class into a vue component

**Comment by maayarosama** [comment]
FarmingProfile is now converted to a vue component.
Fixes need to be done on:
- Line Chart component.
- ROI value isn't reflecting.

**Comment by maayarosama** [comment]
Ready for review.

**Comment by khaledyoussef24** [comment]
simulator is added to the new playground 
![Screenshot from 2023-10-25 08-43-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cc68bf0a-8ecb-44b0-a10d-8afe8b1fcc86)
![Screenshot from 2023-10-25 08-43-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/24bd9fb2-c5b7-4680-8a40-3957ccf98142)
![Screenshot from 2023-10-25 08-43-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6cbbcf03-5800-4457-a2e2-ad261944ecc1)
