### ISSUE TITLE
Caprover checking for free public IPs isn't working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1136]
### Description

Keep getting the error `FarmHasNotEnoughPublicIPsFree` when I try to deploy a caprover with a worker.

### Steps to reproduce

[Untitled_ Sep 24 2023 2_50 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/24af92e1-ab40-4300-b2cd-3df640a32023)

### Logs/Alerts

`Failed to apply {"args":{"calls":[{"args":{"node_id":"29","deployment_hash":"cf7d072645664481b17d9ced900a1794","deployment_data":"{\"type\":\"network\",\"name\":\"nwxjbs5\",\"projectName\":\"caprover\"}","public_ips":"0","solution_provider_id":"1"},"method":"createNodeContract","section":"smartContractModule"},{"args":{"node_id":"29","deployment_hash":"a386542857d73d324268a2a1f8043da3","deployment_data":"{\"type\":\"vm\",\"name\":\"cruxfc7\",\"projectName\":\"caprover\"}","public_ips":"1","solution_provider_id":"1"},"method":"createNodeContract","section":"smartContractModule"},{"args":{"node_id":"29","deployment_hash":"4d5954eeb5f0a2bb07e9950ab3bf2f74","deployment_data":"{\"type\":\"vm\",\"name\":\"cruxfc7\",\"projectName\":\"caprover\"}","public_ips":"1","solution_provider_id":"1"},"method":"createNodeContract","section":"smartContractModule"}]},"method":"batchAll","section":"utility"} due to error: FarmHasNotEnoughPublicIPsFree`

**Comment by Mahmoud-Emad** [comment]
Update:
still investigating

**Comment by Mahmoud-Emad** [comment]
Should be fixed in #1185

**Comment by Mahmoud-Emad** [comment]
The mentioned PR merged and the issue should be in the verification column now.

**Comment by A-Harby** [comment]
Verified, Devnet 03836df.
A clear error message was added to identify that required public IPs is more than the selected farm IPs
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a6d6aee-c3c0-41ae-abcf-7ca58d6decc8)
