### ISSUE TITLE
Add more info for `Get TFT` button for how to transfer the tokens to tfchain

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1143]
preferred to have inline info in a tool-tip and a link to the manual from more information

**Comment by AlaaElattar** [comment]
- still working on it.

**Comment by AlaaElattar** [comment]
- still working on it, was blocked as i was working on another issue at same time.

**Comment by AlaaElattar** [comment]
- Now the tooltlip message visible to all networks, but behavior of button still the same.

**Comment by khaledyoussef24** [comment]
verified get tft has info now
[Screencast from 10-16-2023 09:55:45 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1324b120-bb56-4689-8d29-36f9e8740baa)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/887d43b8-90da-4889-8fab-0ac580932d11)
