### ISSUE TITLE
bridge: withdraw amount should be default to at least 2 TFT

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1145]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/59af1a94-2654-43e0-961c-64095c08fd17)

the default is 0, if i change to 1 I see this error 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/5c543d39-3140-4097-b1cc-8fbc5dbf96cf)

**Comment by AlaaElattar** [comment]
- Updated, waiting for review.

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2023-10-12 12-18-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5da39268-cdc3-4d2b-9d53-b1ce93555abb)
[Screencast from 10-12-2023 12:18:14 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5d92ecbc-2b2c-4fc6-b897-103bfff4d4db)
