### ISSUE TITLE
twin page: add copy to clipboard button to address

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1147]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c2754231-111d-45cf-bb90-ee0ed2b51f03)

**Comment by AlaaElattar** [comment]
- Icon added and waiting for review.

**Comment by khaledyoussef24** [comment]
verified and working fine 
[Screencast from 10-12-2023 12:15:56 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/91b8b5c8-09d3-4a91-9383-09be4a14d23a)
