### ISSUE TITLE
toast position and the support button

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1148]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b1833543-e1a9-4b74-a447-a96e57612b43)

support button is overlapping the notification

more information: using vivaldi on 100% zoom, if it works on chrome please close the issue

**Comment by AhmedHanafy725** [comment]
it shows up at the top on chrome
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/5928b736-f1ef-4df8-b4ab-097417f14758)

**Comment by AhmedHanafy725** [comment]
found that not all toasts are shown on the top right so the issue is not related to the browser

**Comment by AlaaElattar** [comment]
- I've created custom toast to be used, the user will only add the message and choose type.
- waiting for reviews.

**Comment by khaledyoussef24** [comment]
verified while using zoom 100% in the chrome
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/621e2fe6-e2bb-4b4e-8553-c42c051c9bd0)
