### ISSUE TITLE
pricing calculator 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1149]
- change the name to pricing calculator 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/e5b64167-3042-4d7e-aa49-6b0f70bac510)

- the use balance button when toggled shows the discount and the package  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/6d06ec17-e085-4d4f-af7b-b71c417ef681)
but if i deactivate it again it stays on the gold view
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/94a8f4e3-c821-40c6-a56d-3671d9c5f28a)

- add a link to how the pricing works

**Comment by maayarosama** [comment]
- use current balance issue duplicate [#1187](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1187)

**Comment by AlaaElattar** [comment]
- Blocked as I was working on another issue #1018

**Comment by AlaaElattar** [comment]
- All done and waiting for review

**Comment by khaledyoussef24** [comment]
link added to the pricing calculator
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fd004645-eb08-417b-b177-28c5c1409610)

toggle for the golden color fixed
[Screencast from 12-25-2023 02:06:30 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a4837e6-f24d-4236-8aa8-408d438ae5b2)

testlodge:https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422341#case_4150500

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef

![Screenshot from 2024-01-01 12-13-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/59ce3f84-3c0e-45bc-a472-7e31753a772f)
