### ISSUE TITLE
rename Zero-Os bootstrap to 0-bootstrap

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1150]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ebd20038-4224-470f-8a9b-b3f3753a8e12)

**Comment by AlaaElattar** [comment]
- done and waiting for review

**Comment by khaledyoussef24** [comment]
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eeb033b1-52ea-4edc-9e09-78efc1bdf9c1)
