### ISSUE TITLE
rename grafana to Monitoring or Grid Health

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1151]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/7f04db06-00a8-4929-ac77-56f72974b57e)

the name shouldn't tie us to a specific technology, name is debatable

**Comment by khaledyoussef24** [comment]
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9ecc1184-5b69-4662-b6ee-395ff194a5a8)

verified
