### ISSUE TITLE
Add vote reminder popup to council members

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1152]
### Description

Need to add a pop that shows a council member there are new proposals to vote on

### Implementation

add pop up to playground after council member has signed in 

### More

Write more details here if needed about the feature
![Screenshot from 2023-09-26 15-09-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/67ed9872-7840-4521-992e-807f1e5abc63)

**Comment by amiraabouhadid** [comment]
UI is done, dao popup added to twin page. Only need to modify visibility filtration to be based on twins with a farm with nodes up instead of just council members.

**Comment by amiraabouhadid** [comment]
Dao popup is based on user's farms with nodes up now. Need to modify to not show pop up if user has already voted.

**Comment by amiraabouhadid** [comment]
Popup only shows if user has not voted on active proposals.
Pop up shows only number of proposals user has not voted on yet

**Comment by amiraabouhadid** [comment]
Addressing comments on PR

**Comment by amiraabouhadid** [comment]
addressed comment on PR, waiting on verification to merge_

**Comment by amiraabouhadid** [comment]
Addressed comments on PR waiting for review

**Comment by A-Harby** [comment]
I created a proposal, and I was able to see it on the DAO page, but I didn't get any reminders on the vote. I tried different accounts with farms and nodes and waited long enough, but nothing appeared.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ceec924e-4906-4e9b-ab1c-64bf2aff8075)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/64663937-4230-4de6-a4da-8afc3be17077)

**Comment by amiraabouhadid** [comment]
> I created a proposal, and I was able to see it on the DAO page, but I didn't get any reminders on the vote. I tried different accounts with farms and nodes and waited long enough, but nothing appeared.
> ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ceec924e-4906-4e9b-ab1c-64bf2aff8075)
> ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/64663937-4230-4de6-a4da-8afc3be17077)
> 

The reminder is triggered on the twin page when you first log into the dashboard. Not on the Dao page

**Comment by A-Harby** [comment]
I waited about 2 minutes on the twin page, but there was still no reminder.
> The reminder is triggered on the twin page when you first log into the dashboard. Not on the Dao page

**Comment by A-Harby** [comment]
Verified,
Devnet, e2580a5.

The reminder was displayed, but only for the account with UP nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/54a62b97-04fd-4839-99af-18b67f71e2ca)

[TC2430 - Vote proposal reminder pop up](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4160542)
