### ISSUE TITLE
Implement node filter in Vue 3, which should be reusable to be used in the explorer, dedicated views

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1155]

**Comment by Mahmoud-Emad** [comment]
Work in Progress (WIP):

- Currently working on implementing the node table component.
- The goal is to make it responsive and globally accessible for reusability.

**Comment by khaledyoussef24** [comment]
verified working fine with all options
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d443c84e-bfbd-4f63-8c36-0c48ca47aed9)
