### ISSUE TITLE
`Grid Proxy Client` free public IP field doesn't work as expected  

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1157]
The `Grid Proxy Client` free public IP field doesn't work as expected, see the screens below

- Dashboard 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/69e646e2-9717-46eb-a4a6-5d099786f68c)

- Playground (Which uses the proxy client)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/32e4716d-e668-40c3-a517-6eb69d22dfa4)

see node `106` and `107`

**Comment by coesensbert** [comment]
Just a small note that public IPs in farm ID 3 will not work for node 106 and 107. Those nodes are there to test some new hardware and where added to farm ID 3 which is a dedicated node farm (did not remember at that time). Will remove them shortly and add them to a normal farm without public IPs until [VLAN tagging is added to ZOS](https://github.com/threefoldtech/zos/issues/1174)

I also noticed that farm ID 3 had one public IP reserved in the dashboard without any nodes in the farm (before I added node 106 & 107)

**Comment by AlaaElattar** [comment]
- fixed and waiting for review.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- a16e38d
- [TC2270 - Show Farm Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150479)
- [TC2271 - Verify Farm Information from grid_proxy](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150480)

The endpoint is the correct one with the right data returned at https://gridproxy.dev.grid.tf/farms?ret_count=true&page=1&size=10.
My deployment was reserving these IPs, and after deleting them, it shows them again as free public IPs.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/698f0f75-a9f0-433b-ba9a-1d6f5ce21c3c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
