### ISSUE TITLE
[Bridge] Error message should be shown below the text field

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1158]
in case of using a valid stellar address but not in the current network, the error message replacing the address in the text field

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/f11f20cd-456b-46c3-83a6-52067631119f

**Comment by AlaaElattar** [comment]
- bug fixed and waiting for review.

**Comment by khaledyoussef24** [comment]
fixed and verified 
[Screencast from 10-12-2023 12:06:10 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/51cb43d1-0758-4ed1-be99-d02d0bc98c46)
