### ISSUE TITLE
Make the view of the portal pages consistent

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1159]
- The icon should be beside the header
- The filling should be the same
- The font sizes should be the same

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/a7494d36-8cf2-4373-85a3-7dd0c9b454af)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/955e57e2-4938-460f-a918-3a572d9e774d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/99f4b7b2-4715-4135-bc57-a9c72eaa03d4)

**Comment by ehab-hassan** [comment]
fixed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/9f356e28-fe5a-4c8b-ba81-0c4a52f6f704)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1a1c7891-ef83-4a43-abb8-578cbca1de3b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/5d044d69-ecfe-4ce8-a961-3f03fc9e1ac7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/4fdd8316-fb79-4cb0-a638-4a783fb3d043)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c85a05ed-1998-47cb-b018-d3cb4d997dc0)

**Comment by ehab-hassan** [comment]
updated Statistics to the same Style
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/951c5a67-4aad-4cdb-9e73-b809116792d2)

**Comment by A-Harby** [comment]
They all have the same font and style
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3fa2e4c1-2e7e-47d4-86d4-4a89238cbf0e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3417de0a-592a-4170-a181-fd09ab710081)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/baaa7119-293a-4aba-ae92-10af8fad635d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5286e8bd-d8e0-493c-9391-e5182fe113de)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ff47bda9-ead3-45e9-a2a1-17237a4f96d5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/08bfb5e1-2b6c-47bf-9733-e66946828d8c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c22e2e6e-a1cf-44cd-abb5-cc3f77ab67bd)

Except for Farms, it feels different, bold, and maybe has a different font size? @ehab-hassan 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b0d73aaa-eed4-4007-9b01-fe3f30ace266)
Also, should my contract follow same style or not?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/046b802e-f142-4e12-9c6b-f765050fd459)

**Comment by ehab-hassan** [comment]
farm fixed here #1680
for the contract maybe we can create a new issue because these are buttons not card title header

**Comment by zaelgohary** [comment]
@A-Harby As @ehab-hassan said, contracts headers' style should be different than the normal header. So, no need to change them.

**Comment by A-Harby** [comment]
Verified,
Devnet, a16e38d.
The farm font and style are fixed, and with [previous comment](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1159#issuecomment-1854018601) all the Portal/Dashboard page views are consistent.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2d7eb0b9-07c1-44ba-9b78-8f3e7599c2ae)
And for your contract page, the three tabs here are a tab with a click for expand and collapse.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/04bdbc52-cb26-49ff-8d12-55aa1b55a8ea)

[TC2301 - UI component](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155453)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 13-29-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8f78d354-8c3b-4960-a134-b66a71c7ef5d)
![Screenshot from 2023-12-27 13-29-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/60babc4e-2fe0-4d5e-8e45-a9df4534db7f)
![Screenshot from 2023-12-27 13-29-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4b50e57f-ee40-414c-bbd1-59d119b2cf4e)
