### ISSUE TITLE
k8s cluster token initial error

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#1166]
Cluster token initialized with an invalid value

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/839726ff-d13e-4a7d-9677-64c53ba88321)

issue:
basically we're using a generatePassword() function which including all chars and special chars and spaces
but clusterToken field doesn't allow to have spaces

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1175

**Comment by A-Harby** [comment]
Verified
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e936ca1d-e8b0-42a0-a7ad-d405f55eb462)
