### ISSUE TITLE
some info messages are in yellow 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1168]
### Description

some info messages are in yellow  while it should be green
-the deposit in the bridge
![Screenshot from 2023-10-02 15-31-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f541d9d5-c27c-4898-854a-3f061f1c4de9)

the mnemonic sign in page 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fd763eff-a877-43b0-8f2c-5646845ce9bb)

**Comment by AlaaElattar** [comment]
- colors changed and waiting for review.

**Comment by khaledyoussef24** [comment]
colors changed 
![Screenshot from 2023-10-12 10-29-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b470d674-a162-471c-a4c0-272841cefa88)
![Screenshot from 2023-10-12 10-29-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/73ac9525-931e-4e9c-ab9a-caa805cc823b)
![Screenshot from 2023-10-12 10-29-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b33b5f51-3f94-4a4f-a497-f439c943d1b5)
