### ISSUE TITLE
generating/updating ssh key gets stuck for long time

### ISSUE THREAD

**Issue by Eslam-Nawara** [threefoldtech/tfgrid-sdk-ts#1170]
every time I try to generate or update ssh key it gets stuck and never proceed.  

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/67752395/26d9b2b1-afb2-4525-afd9-bc22ac74c061)

**Comment by AhmedHanafy725** [comment]
this issue was already fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1164), but it hasn't been deployed since the fix was in the grid client, not the playground.

**Comment by AhmedHanafy725** [comment]
Triggered the workflow to deploy it.
It should be working fine now.

**Comment by A-Harby** [comment]
Verified, Devnet c894f27.

generating/updating ssh key are working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3bdea62c-0e63-42a9-95fa-6f7c6a9f11f0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6886e070-8758-4518-88a3-3462d1bdda90)
