### ISSUE TITLE
Refactor user nodes to use owned_by query

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1179]
requires: https://github.com/threefoldtech/tfgrid-sdk-go/issues/417

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02.

The request that is being called is now using ownedby https://gridproxy.dev.grid.tf/nodes?ret_count=true&page=1&size=10&owned_by=666

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1b98cd60-538d-427c-8782-a6f6bbff9114)

[TC2212 - List Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150421)

**Comment by A-Harby** [comment]
Devnet, 842ebef.

The request is still working with `owned_by` and with accounts that have nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/12fe0467-74ab-4782-8485-c74f1745082c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
