### ISSUE TITLE
Can't change PDF link in PDF Signer

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1181]
### Description

I was able to run PDF Signer successfully with no issue by the help of the pdf example (below).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e1946278-f36e-4bcf-ae7d-20c608b1c831)

But when I tried to change the pdf link to many other pdfs, it always fail.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c59a0d67-5238-4afc-8c5d-fca7c3c6a5af)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da8aec24-e476-4899-9cee-18153ef29ddc)

And the docs doesn't specify any kind of pdfs.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f5ac4569-87c2-419c-80a5-60cd8675c146)

**Comment by Mahmoud-Emad** [comment]
It appears that the encountered behavior is not a software issue. To ensure smooth operation, please make sure you provide a PDF URL with CORS-ORIGIN enabled. If CORS (Cross-Origin Resource Sharing) is not enabled on the provided URL, the issue you mentioned might occur.

However, we can for sure return an error to the user to inform him that he must provide a `PDF URL` with `CORS` enabled.

**Comment by Mahmoud-Emad** [comment]
Should be improved in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1189

**Comment by A-Harby** [comment]
it was documented to which PDF type that should be used 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da4579bc-aca0-4d1b-b639-b932e09ef704)
