### ISSUE TITLE
Presearch Playground Dashboard does not show nodes

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1182]
### Presearch Playground Dashboard does not show nodes

gogo76227 on the TF forum shares a bug that was resolved without any direct fix (after some time it resolved), but could be relevant for bug testing.

"All nodes are up and running again but now the Threefold Presearch Playground Dashboard does not show a single node anymore…"

### Steps to reproduce

The user deployed different presearch nodes. Might not be directly reproducible.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/4bf01045-f55c-47d4-8a5e-c75c51c4eb0d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/6b6d853a-5f64-4300-9478-084ca0d97b75)

### References

https://forum.threefold.io/t/the-new-playground/3982/11

**Comment by maayarosama** [comment]
Solved on the user's side
