### ISSUE TITLE
Script editor is not working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1186]
### Description

Script editor is not working for me (while the same steps worked perfectly with the PDF signer), I tried Script editor with both threefoldSignerProvider and threefoldConnectorProvider; And nothing is working for me.

### Steps to reproduce

1. Run `yarn build`.
2. Copy threefold-ui.umd.js and tailwind.css  from dist to html example folder.
3. Include both of them and include script editor.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7815f0ea-0be8-44df-95fe-5f52546935a7)4. Run server example using `npx ts-node src/server.ts`.
5. Run html using VS Code extension Live Server.
6. I Tried both threefoldSignerProvider by adding my mnemonics in .env and commenting .env to use threefoldConnectorProvider (using extension latest V9).
7. wrote something and Submit the request. 

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9596ba87-cdf9-4cbd-b922-ade3502b9eb8)

**Comment by A-Harby** [comment]
Verified.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc3b035f-39d8-4b94-ae9b-efbadb8397d4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/50eaaf2e-af36-46cd-b413-f9654b4689bb)

**Comment by A-Harby** [comment]
Extension worked as u can see above but when I tried with the mnemonics (threefoldSignerProvider) it didn't work 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5b67324c-8bd6-40cd-872d-c63a4946c01a)

**Comment by zaelgohary** [comment]
It fails when verifying. Still investigating why.

**Comment by zaelgohary** [comment]
No content was sent upon using the signer provider. Fixed by adding a content property.

**Comment by A-Harby** [comment]
Verified, 
threefoldSignerProvider is now working fine as well as the Extension.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/950717df-60f3-4ca0-8605-e62afde2a379)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/17d43c40-7fbb-4404-96d2-88e5dfa791cc)


And the example was updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7275e2b4-d6ac-44d7-aa8a-13f3549ae0b4)
