### ISSUE TITLE
use current balance toggle in calculator is not functional when disabled

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1187]
### Description

use current balance toggle turns boxes to gold but boxes does not turn back to normal when disabled
[Screencast from 10-09-2023 11:06:46 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3aa5bc49-ec86-4098-b9e7-de8cabf1f5b0)

normal view:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ea6099b9-ec55-4474-ae8c-294c4f29561c)

view after using use current balance:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f39c8e37-6f91-47f1-9b67-69621ca28443)
(boxes turn into gold)

view after disabling use current balance:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e401aaba-148a-46ba-ad0f-f4af401d5b3c)
the UI gold color for the boxes does not change neihter the cost of the deployment

**Comment by AlaaElattar** [comment]
- Blocked as I was working on another issue #1018

**Comment by AlaaElattar** [comment]
All done and waiting for review

**Comment by AlaaElattar** [comment]
- working on handling this issue in same pr https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1236

**Comment by khaledyoussef24** [comment]
is the golden color removed?

**Comment by maayarosama** [comment]
> is the golden color removed?

golden color is still available 
![Screenshot from 2023-10-25 13-55-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/bba4b937-0e34-4ac1-9e27-86c98fb56cab)

**Comment by A-Harby** [comment]
Verified,
Devnet, 14a9eaf.

The use of the current balance toggle is working fine when enabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aa18fbed-4685-4c05-9095-f28789e4251e)
And when it is disabled, the balance amount is reset to 0 and recalculated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f403f84d-36dc-4a50-b65c-cb1d1aef175c)
And also, the gold package still has the golden color.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/10e2799c-b438-4460-8cdb-56870c69de6c)

[TC2291 - Calculate Deployment Cost using the current balance](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422341#case_4150500)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3

toggle certified node filter only; shows the $/month is ok
![Screenshot from 2023-12-24 16-02-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/cf2a428f-f241-46a2-ba94-0d1cd270e6ba)

toggle certified node filter + public IPv4 filter; shows the $/month in bad shape (need better round for the value)
![Screenshot from 2023-12-24 15-59-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/39535f6f-2a1a-4a9f-98f7-23d820db2961)

**Comment by khaledyoussef24** [comment]
verified with the last changes and working fine 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e60e6cfd-5a1a-4b07-a535-100e08e80b33)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef

![Screenshot from 2024-01-01 12-15-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/3e46cf73-4c88-4946-ad35-dc77ac1afd76)
