### ISSUE TITLE
[Transfer] Error validation in tranfer by twinID

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1192]
- When i added my address in `By Twin ID` tab it didn't show any error.

![Screenshot from 2023-10-09 16-11-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/92407dbe-6e3c-4d54-b880-9a215f67acd9)

**Comment by AlaaElattar** [comment]
- Bug fixed, waiting for review.

**Comment by khaledyoussef24** [comment]
fixed and verified 
![Screenshot from 2023-10-17 12-05-10](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7a8435b8-50b3-40f2-b85b-3434be74d89b)
![Screenshot from 2023-10-17 12-04-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/87d12df6-0c31-4902-96f4-ddda554bc7fc)
