### ISSUE TITLE
Support add node to network on network module

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1196]

**Comment by A-Harby** [comment]
Verified on Devnet, development branch.
Function and script (add_node_to_network) were added and ran successfully with no errors.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a4e82a9d-c3be-4a6f-84ab-3bdefd0e11fb)

**Comment by A-Harby** [comment]
Verified, 
hasNode function before adding node to network,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d4e501da-3d77-4dcd-8fd7-cc12b379358a)
and after .
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3c251850-72fd-4ad6-9ef6-d2e829d64a87)
