### ISSUE TITLE
Iframe the status page (grid services)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1199]
Name (Grid Services?) to https://status.grid.tf/status/threefold

**Comment by mohamedamer453** [comment]
It should be added in #1232 and regarding the icon i discussed it with @ehab-hassan and it should have a new icon soon.

**Comment by mohamedamer453** [comment]
Update:
The PR was drafted until the new icon gets added.

**Comment by mohamedamer453** [comment]
Update:
The icon was added and the pr is ready for review.

**Comment by A-Harby** [comment]
@xmonader Should it have been Iframed or just a link to https://status.grid.tf/status/threefold?
And the name is now Grid Health; is that correct?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/eeaf2751-472c-404a-b865-50b09bfb1156)

**Comment by xmonader** [comment]
It should have been iframed, but I'm OK with a hyperlink. No problem. Can be closed. Thanks.

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3
