### ISSUE TITLE
Add method to calculate amount needed to unlock contract from grace

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgrid-sdk-ts#12]
Currently, it's not possible to see how much tokens are required to "unlock" a graced out contract. This info is will be added on tfchain in 2.4.0. 

A client can get the the lock attached to a contract by querying: `smartContractModule.contractLock(contract_id)`

This will return an object like: 

```
{
  amountLocked: 123123123123
  lockUpdated: 1,677,534,012
  cycles: 12
}
``` 

`amountLocked` specifies the outstanding amount "due" for the contract. We can expose this function to add this in the weblets so a user can know how much he needs to recharge his account with if he wants to unlock his contract.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The method was added and it's currently used in the playground to display the amount of tfts needed to unlock a certain contract.

[Screencast from 12-06-23 14:18:29.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/df45e580-819a-4019-ab34-c6456fcece44)
