### ISSUE TITLE
Farm Name list doesn't show all the farms

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1201]
### Description

Mainnet

Farm Name list doesn't show all the farms, 
I kept loading more till the button was removed and couldn't find the farm I was searching for MiniFarm.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/798ee501-4fdf-4259-b1c1-333019de5b4a)
 
I tried loading all the farms in different solution with default specs, but also couldn't find the farm

**Comment by AhmedHanafy725** [comment]
It depends on the resources selected, so it might not have enough resources to deploy the workload.

I could find it in the farm while deploying a full vm

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/e9afd197-309e-443f-9982-7c555ceefe50)
