### ISSUE TITLE
Withdraw or deposit dialogue can not be closed unless you press the close button

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1202]
### Description

withdraw or deposit menu can not be closed unless you press the close button even if you click outside the popup window
[Screencast from 10-12-2023 12:03:05 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e83241b1-2641-474f-a6da-95b0276a51c2)

### Steps to reproduce

1. go to the playground
2. go to portal
3. then go to bridge
4. open the withdraw or deposite 
5. try closing them by clicking anywhere on the screen
6. it will not work

**Comment by AlaaElattar** [comment]
It's intentional. why do u see it as a bug ??

**Comment by maayarosama** [comment]
If there's a transaction it shouldn't close, otherwise it should @AhmedHanafy725

**Comment by zaelgohary** [comment]
Removed persistent from dialogues. Now the behavior is unified as all other dialogues. Even if the dialogue is closed while transaction is being done, it'll still be done in the background.

**Comment by zaelgohary** [comment]
Work Completed:

The dialogue was being destroyed before unmounting. I removed this and updated the dialogue if it's closed in any way whether by using Esc, clicking outside, or clicking the close button.

**Comment by khaledyoussef24** [comment]
verified working fine now you can close the dialogue by clicking anywhere outside the msg box
[Screencast from 11-13-2023 12:07:00 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1621612b-0847-4e7d-adb2-8c6c083859da)
