### ISSUE TITLE
New option to find a farm by its Name/ID.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1203]
### Description

Add new option for the user to make it easier to find a farm by its Name or ID.

the used scenario now is that the user have to load all the farm from farm list then search for the farm name in that list, which does take a lot of time to load all the farms and waste a lot of requests just to find one farm.

**Comment by zaelgohary** [comment]
I don't think manually filtering by farm name is practical as the searching purpose is to find a node to deploy on. A manual selection for a node is currently being implemented and should be done once https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1094 is finished. Do we really need to add an extra step for searching by farm name before searching by node ID?

**Comment by A-Harby** [comment]
I know a manual node would be enough in most cases, but it would be a nice option for the user in case he wants to use a specific farm without regard to the node. Maybe it's his farm or a farm in his country, and searching for a specific farm on the mainnet is very time-consuming.

**Comment by zaelgohary** [comment]
The only logical way to implement this is to create a manual farm selection and the user can select nodes from this specific farm. This means I'll have to remove manual node selection. Should I start working on this? @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
in the automated selection, we can do the following

- allow the user to type the farm name
- disable the farm validation on resources (just make sure that this farm does exist or maybe do a quick search for the farm name to help the user with autocomplete (`name_contains` in the query would help))
- use the farm name entered to search for nodes (at this point if the farm doesn't have nodes that fit the resources, the user has to pick another farm)

**Comment by zaelgohary** [comment]
Investigation and Solution:

Still discussing possible solutions with @AhmedHanafy725.

**Comment by zaelgohary** [comment]
WIP:
Working on creating a request that gets called only on input in the farm field. The request should get all farms whose names match/contain the searched term.

**Comment by zaelgohary** [comment]
Work completed:
Return type from proxy was different than the type from grid client. Hence, it was searching for a property that didn't exist. I edited the property name to match the one in the grid and it should be fixed. PR is ready for review.

**Comment by zaelgohary** [comment]
Work completed:
Added a reload icon inside the farm field to enable the user to reset his search.

**Comment by zaelgohary** [comment]
WIP:

Working on removing the reload button and reverting to automatic farm selection once the search is empty.

**Comment by zaelgohary** [comment]
Work completed: 
- Removed reload button
- Old farm was always chosen if it's in the returned list so I removed this condition
- Refactored filters watcher
- Used clearTimeout instead of debounce in search watcher

**Comment by zaelgohary** [comment]
WIP: 

There's an issue in the filter as the selected farm doesn't update in some cases. Still investigating why this is happening.

**Comment by zaelgohary** [comment]
WIP:

Finished the following:
- Removed no data available message
- Fixed load more farms button
- Reset farms on error or if field is empty

Still working on:
- Removing old farm name while loading

**Comment by A-Harby** [comment]
Verified,
- Devnet
- dfbecf3
- [TC2452: Node Selection: Filter Nodes by Farm Name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4167536)

I tried different farm names, only the start/end and part of it, and the search worked correctly.
I also tried searching in case it was insensitive and it worked fine.
And made sure that the farm selected, after searching for it, is the farm that all nodes are being listed from.
The used endpoint is `https://gridproxy.dev.grid.tf/farms?name_contains=`
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1a066c05-4fa8-4e97-b541-23bdeed1ccfa)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/60cf8bbc-d206-48de-bf2b-dc0fc6e1745c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f83227f
