### ISSUE TITLE
The user is unable to access WireGuard on Umbrel Weblet:

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-ts#1209]
Description

The user is trying to access/enable the WireGuard network. Unfortunately, the option is not available.

![WireGuard](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/b09034ee-efe9-4bac-9210-edd831399009)

And the user is requesting to access the WireGuard on Umbrel weblet.

**Comment by Mik-TF** [comment]
Thanks for creating the issue Shang.

The [PR 1211](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1211) adds this feature. Once mergee we will be able to close this issue.
