### ISSUE TITLE
(Mainnet verification) Listing vms takes much time to load on mainnet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1213]
Require investigation into why it takes so long to finish loading.

## background

it took around 1 minute to list 2 deployments in the listing page

**Comment by AlaaElattar** [comment]
- still investigating but, sometimes it takes about 0.4 second and sometimes 8 seconds.

**Comment by AlaaElattar** [comment]
- I did investigated with 4 deployments and that's what i got


![Screenshot from 2023-10-24 11-13-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f89eaaaa-f943-42ea-bda8-432a157fce82)


![Screenshot from 2023-10-24 11-14-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/1ad013f7-08ed-48f5-a35d-171d696d7180)

- I believe that it took time in playground as there're 2 deployments failed to load.
- Also there's something that may cause problem if there're many deployments , that the pagination not handled from server side.

**Comment by AlaaElattar** [comment]
- I added race condition and timeout for 5 seconds instead of 60 and it worked fine
- But there's smth more simple is to add timeout from function in `grid_client` working on it.

**Comment by AlaaElattar** [comment]
- I added new pr against development with all changes that user can check number, name, and nodeId of failed deployments.
- waiting for review

**Comment by khaledyoussef24** [comment]
env used: mainnet 
version : 2.2.0
[Screencast from 01-16-2024 01:31:10 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/21bcbfc3-c6d0-4d63-bb01-a57aee49b03c)
wait time does not exceed 20 seconds and is acceptable now
