### ISSUE TITLE
Upgrade Vuetify to latest version

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1219]
Upon upgrading, some issues might happen in data tables and other components.

**Comment by MohamedElmdary** [comment]
Make sure to use new features of data-table instead of workarounds in `list-table.vue` file

**Comment by MohamedElmdary** [comment]
WIP:

Upgraded vuetify from 3.1.x to 3.4.x

**Comment by MohamedElmdary** [comment]
WIP:
Upgraded table in almost every part of app

**Comment by Mahmoud-Emad** [comment]
What is the status here?
