### ISSUE TITLE
Add docs for QSFS VM weblet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#122]
### Description

Docs for the new `QSFS VM` should be added and linked in the quick start docs section in the weblets. since the link currently redirects the user to the normal VM docs.

![image](https://user-images.githubusercontent.com/101194226/202431284-bd4b6557-3d09-4c24-bac8-472c9d234782.png)

**Comment by xmonader** [comment]
obsolete by the new playground too
