### ISSUE TITLE
Add notification for contracts on offline nodes 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1220]
it can affect the user balance specially in case of having public ip reservation

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1239

**Comment by Mahmoud-Emad** [comment]
### Issue update

- Added a notification helper that will notify the user every 15 minutes if there are deployments on an offline node.
- Updated the toast warning background, icon color, and text color in dark/light mode.

**Comment by Mahmoud-Emad** [comment]
Worked on some comments

- Created the `GqlContracts` interface in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1255 and used it
- Enhanced the performance by removing unneeded loops

**Comment by Mahmoud-Emad** [comment]
### Update 

- Working on some enhancement that may enhance the performance

**Comment by Mahmoud-Emad** [comment]
### Issue Update

- Returned back to in-progress because some changes requested, `Support links in the notification`

**Comment by Mahmoud-Emad** [comment]
### Issue Update 

#### Support links in the notification pop-up
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/aaed474d-6d6e-4c87-a451-454d2dbd9ad0)

should be supported in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1297 and the PR is ready for review.

**Comment by Mahmoud-Emad** [comment]
### Issue update

- Worked on some enhancement -> Close the toast when navigating to the contracts list page
- Updated the `BillReports` constant name

**Comment by Mahmoud-Emad** [comment]
@maayarosama 

I have kept this issue in the 'In Progress' column because the newly implemented feature involving the `<Link on the number of contracts>` needs to be merged into `3.13` to avoid conflicts. The last merge was performed against version `3.12`. Should we continue to work on this and keep it in the 'In Progress' column until the necessary changes are completed?

**Comment by A-Harby** [comment]
verified, 
I deployed a VM, Kubernetes master and worker, and Funkwhale (solution) on the same node 21, and when the node went offline, I got notification for the contract on that node.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/15906eaa-1306-40bf-9a5e-7a00d12c4754)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2241af6d-9ae6-40fe-8787-df926d42ab1a)
