### ISSUE TITLE
Remove rentable tab from dedicated nodes

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1226]
- There's no need for user to see rented nodes.

**Comment by AlaaElattar** [comment]
- Issue solved, waiting for review.

**Comment by khaledyoussef24** [comment]
only two tabs are available now (rentable and mine)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1d7b3506-671f-4b08-a482-fe976a0a4621)
