### ISSUE TITLE
Incorrect TFT conversion rate in the new playground

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1227]
### Description

The TFT conversion rate in the new playground is incorrect, it's displayed as `1 TFT -> 6 USD` while the actual rate from stellar is `1 TFT -> 0.006 TFT`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8f2e03d5-1a28-47f4-b641-8bcfb6c6fa64)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/18188e32-c029-48f4-a092-0471d4fe9d61)

### Steps to reproduce
- Navigate to https://new.playground.dev.grid.tf
- Check the TFT conversion rate.

**Comment by khaledyoussef24** [comment]
fixed 
![Screenshot from 2023-10-25 08-00-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cb2cb449-49c9-4db8-9bae-e7c677cf9e07)
![Screenshot from 2023-10-25 08-00-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1cf4120-05fe-432e-ab76-41b94a25f669)
it is now 1 TFT -> 0.006 USD as mentioned in [stellar](https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?asset[]=TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1&filter=markets&market=USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN-1)

and by changing tft exchange rate (1/0.006=166.66) as mentioned
![Screenshot from 2023-10-25 08-00-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b3e77d23-4632-4048-97a3-9de2eb0db9f4)
