### ISSUE TITLE
Add dedicated chip to the explorer nodes table

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1229]
chip should be added to

- nodes in a dedicated farm
- free nodes (nodes have no contracts)
- rented nodes

require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/420

**Comment by zaelgohary** [comment]
Work completed:

Added type column to show if the node is dedicated or shared.

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

Node types have been added to show if a node is Shared or Dedicated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2d94a13a-4a22-4c5e-968f-98977a2f9f2a)
[TC2250 - Nodes Table Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150459)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- ebf75a3

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/84eb8458-07c8-4cc6-8010-179b4db6807c)
