### ISSUE TITLE
Add dedicated nodes count to stats page

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1230]
the count of rentable nodes + rented nodes 

require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/421

**Comment by A-Harby** [comment]
Verified, Devnet.

Dedicate node cards have been added to the stats page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/56faa7b4-3f0c-4dee-bd58-f1adc1e0f4d4)

[TC868 - Node Distribution](https://app.testlodge.com/a/26076/projects/40893/suites/211395?expand_section=353833#case_3665279)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 12-53-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/511aa8ad-c018-4b2b-911e-c21c552add92)
