### ISSUE TITLE
Expose `all` and `filter` methods on the nodes module to list/filter all nodes

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1235]
They can call the `capacity.getAllNodes` and `capacity.filterNodes` methods

**Comment by Mahmoud-Emad** [comment]
Should be added in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1238

**Comment by Mahmoud-Emad** [comment]
### Issue update

- Created an `all` method to load all nodes from the capacity module
- Created a `filter` method to filter nodes from the capacity module
- Added one more field named `numberOfPublicIPs` to get the public ip count of the contract

**Comment by Mahmoud-Emad** [comment]
The PR has been merged and is ready to be in the verification column.

**Comment by AhmedHanafy725** [comment]
the required methods are having the `expose` decorator
