### ISSUE TITLE
Fix calculator style in light mode

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1236]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/8e3aa117-50af-43c7-a4cc-f45489561908)

**Comment by ehab-hassan** [comment]
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=1231-2466&t=lzr1NFbqRRPCajap-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

please use this color for light mode
background #E5E5E5
info text ll be dark green #1AA18F

**Comment by AlaaElattar** [comment]
- working on handling this issue in same pr https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1236

**Comment by AlaaElattar** [comment]
- fixed and waiting for review .

**Comment by khaledyoussef24** [comment]
verified the "pricing calculator" title is now in green box  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/10f8a969-4262-49be-943c-c3ff7bc578e9)
