### ISSUE TITLE
loading doesn't stop if the node is not responding

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1237]
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/b572de6a-8edf-4d41-b539-3af5f4d9ea9e

**Comment by Mahmoud-Emad** [comment]
The issue happened because of the the grid prox, but of course, it needs to be handled from our side

**Comment by Mahmoud-Emad** [comment]
PS: Waiting on new style will be provided by @ehab-hassan

**Comment by ehab-hassan** [comment]
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=1267-2525&t=MoDFEiajud7rXrwN-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by Mahmoud-Emad** [comment]
- Update the build method in the proxy client to set timeout 5000 on the request and return an error in case the node is not responding, 
- Update the node details with a re-request button to let the user re-request the node in case of not responding.
- Updated the dialog header size
- Updated the style of error loading the node

**Comment by A-Harby** [comment]
Verified,
Devnet 8c32384.

When the node is not responding or an error occurs, the try again message is shown.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0a697cbc-8d66-4899-840e-31c11c39838b)

[TC2252 - Offline/Standby Nodes Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150461)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2
