### ISSUE TITLE
New Dashboard light mode

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1241]
The light theme in the new Dashboard needs some changes:

- Most components don't have borders
- The component background color is the same as the page background color which makes it a bit off
- The drawer consistently appears dark, leading to a stark contrast with the page's background color
- Maybe we can change the primary color in light mode to another gradient of white instead of fully white? 

The previous comments go for all pages in the Dashboard.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/d3d0de21-9a5f-4759-8693-af03daf0955e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5cf212ca-8262-415a-aec5-e2ea412121fe)

**Comment by ehab-hassan** [comment]
@zaelgohary for background, we changed it before to  #E5E5E5 for all
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c39214bf-d855-42ea-8401-7026bc3fb6a6)

**Comment by Mahmoud-Emad** [comment]
### Update 

- Changed the navigation drawer to light on switch to light mode
- Working on exposing an event when changing the theme

**Comment by Mahmoud-Emad** [comment]
### Update

- Changed the `Sidebar` background to be `light` on `light-mode` instead of `dark`. 
- Changed the `AppBar` background to be `light` on `light-mode` instead of `dark`.
- Changed the `ToolTip` background to be `light` on `light-mode` instead of `dark`.

**Comment by Mahmoud-Emad** [comment]
### Update 
> * [x]  numbers need to be darker green
> 
> ![image](https://user-images.githubusercontent.com/10484295/277661714-6cda8032-3c1d-4cb8-bfb4-9ebeaecb80a6.png)
> 
> * [x]  Can u make this outline icon like others (in both light and dark modes)
> 
> ![image](https://user-images.githubusercontent.com/10484295/277662145-2ffef47e-2352-4e75-9347-c8a0703035a7.png)
> 
> * [x]  make sure the links in the drawer with dark green primary color)
> 
> * Some buttons' colors are not good in light mode but need to fix it first in dark mode then check it.

All requested changes should be done.

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf09ac93-9a62-4c1f-92ed-d4c7442bc055)
side bar and app bar and tool tip changed to light 
the links in the drawer with dark green
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1011d7b5-9cb6-4888-95e2-3b535c02617b)
background changed

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
