### ISSUE TITLE
Cannot read properties of undefined (reading 'nodeId')

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1244]
### Description

This happened multiple times, I've deleted my contracts then deployed a node and got this error.

### Logs/Alerts

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/2c863afc-a4b2-4366-9e9e-6633ed5149a7)

**Comment by Mahmoud-Emad** [comment]
Still investigate

**Comment by Mahmoud-Emad** [comment]
Still checking...

**Comment by Mahmoud-Emad** [comment]
I am unable to reproduce the issue at the moment, but I acknowledge that it still exists. Therefore, I am updating the status to `Accepted`. I will unassign myself from this task until another team member encounters the same issue and reports it.

**Comment by AlaaElattar** [comment]
- It happen with me now on mainnet, I chose node 11 and the `Deploy` button get enabled then when i clicked on it it loads then got me the error.
- when i returned back it said that `Couldn't fit the required disks in Node 11 storage pools, please select another node`
- I think this may be the reason but i will investigate it first.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/70fd6d60-3612-4960-9831-b1110884f6c1)

**Comment by AlaaElattar** [comment]
- Here it's the issue, the button get enabled while checking on node Id

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/5deb424f-8f5c-47ad-89a2-9760c0012596)

**Comment by AlaaElattar** [comment]
- Fixed and waiting for review.

**Comment by AlaaElattar** [comment]
- It's applied in all solutions to guarantee it won't happen unless the node is defined.

**Comment by 0oM4R** [comment]
this issue is one case of 
- #1300 
i guess we should hold this issue till we solve the original one in 3.12

**Comment by AlaaElattar** [comment]
- As this one solves small part of big issue, will sync it with @0oM4R  when he solve the other one.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 6d0ec3d
- [TC2306 - Deploy button is disabled while filtering](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4155950)

The deploy button was disabled while validating the capacity configured in different configurations and different solutions, and I was able to deploy multiple VMs with no error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/143a2e2d-5f42-455b-83e7-5e5fd027c636)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 13-02-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8c091a22-40c3-4110-a825-18b2732dbc62)
