### ISSUE TITLE
Enhancements at Nodes Explorer

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1245]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/2f48e782-bb45-4904-a632-fc4e5dbda141)

- [x] Please add the Filter inside the border of the Nodes.
- [x] Make all values inside the table and details font-size 14px or 0.875rem

**Comment by Mahmoud-Emad** [comment]
Should be enhanced in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1249

**Comment by khaledyoussef24** [comment]
the Filter is inside the border of the Nodes now.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2278e95b-9682-426b-b963-fb308fb08743)

font is now 14px
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/821e31c7-5ea4-48bb-84ba-fbd5d658d602)
