### ISSUE TITLE
Black background on light mode 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1260]
### Description

Consider setting the `app bar`, `navigator drawer`, and `profile manager` to light colors when switching to the light mode for improved visibility and aesthetics.

### Related issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1241

### Screenshots

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/0012b153-b51a-4402-8fa1-8d8af6d25f2d)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/887fb68c-711b-4ef5-8cce-8ae0eaa4bd1e)

**Comment by Mahmoud-Emad** [comment]
Update

- Changed the `Sidebar` background to be `light` on `light-mode` instead of `dark`. 
- Changed the `AppBar` background to be `light` on `light-mode` instead of `dark`.
- Changed the `ToolTip` background to be `light` on `light-mode` instead of `dark`.

**Comment by Mahmoud-Emad** [comment]
### Update 

> * [x]  numbers need to be darker green
> 
> ![image](https://user-images.githubusercontent.com/10484295/277661714-6cda8032-3c1d-4cb8-bfb4-9ebeaecb80a6.png)
> 
> * [x]  Can u make this outline icon like others (in both light and dark modes)
> 
> ![image](https://user-images.githubusercontent.com/10484295/277662145-2ffef47e-2352-4e75-9347-c8a0703035a7.png)
> 
> * [x]  make sure the links in the drawer with dark green primary color)
> 
> * Some buttons' colors are not good in light mode but need to fix it first in dark mode then check it.

All requested changes should be made.

**Comment by khaledyoussef24** [comment]
the black color removed from the profile manager ,side bar , app bar and the background of the tooltip
![Screenshot from 2023-12-26 08-47-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/56befd12-ad1b-4cbc-aa3a-1702ec45b463)
![Screenshot from 2023-12-25 14-11-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7d61b73a-b823-470d-8713-440ef4574096)
![Screenshot from 2023-12-26 08-51-51](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6cb8bfb7-2516-4656-957e-db9d5c2e3c14)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
