### ISSUE TITLE
Update Style of New Playground for Responsiveness

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1261]
### Description

The current playground interface lacks responsiveness, causing display issues on various devices and screen sizes. To enhance the user experience and accommodate different devices, it's crucial to update the styles and layout of the new playground to make it responsive.

### Screenshots 

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/fd13fb0f-a12e-4a2e-b87f-d3c58f7ead48)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/44a8a2bd-1a94-4ad9-a73d-eecc558305b0)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/5f7fa6b3-5af7-4959-89dd-f43612b630bc)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/4b2110b6-67af-4620-9286-83c7b2260a37)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ebdfa44a-acde-47bc-875f-c39a9941fa95)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/40c35b70-7c54-452d-b0f8-1c367c9786e6)

**Comment by 0oM4R** [comment]
will move this to blocked on #2342

**Comment by ehab-hassan** [comment]
fixed
TF Chain
![image](https://github.com/user-attachments/assets/542ab8f2-fd8b-49ac-8707-d7d9b3bcf924)

Twin Details
![image](https://github.com/user-attachments/assets/18ab1f63-e77b-436e-8ca3-4e5616a122b9)


Transfer TFT
![image](https://github.com/user-attachments/assets/da54fabf-d1fc-4e34-8092-91f5d972d30c)

Transfer TFT/Deposit
![image](https://github.com/user-attachments/assets/a37cddfb-c638-4b33-999c-28cdbf3c2446)

Transfer TFT/Withdraw
![image](https://github.com/user-attachments/assets/7751f276-7c62-4c77-adef-b7d888cf39f7)

calculator
![image](https://github.com/user-attachments/assets/96400211-e109-4eec-bb65-d013cef33dfa)

Home when login
![image](https://github.com/user-attachments/assets/acb71123-a7bb-4761-87fa-a24b93b2dcf4)

Simulation
![image](https://github.com/user-attachments/assets/90b20670-6f3c-4472-9681-525094dc3d3c)

Home without login
![image](https://github.com/user-attachments/assets/e2d0e7e0-f7b6-4cb4-8abb-2ad246583d86)

**Comment by ehab-hassan** [comment]
Work complete
all should be responsive fine now

**Comment by khaledyoussef24** [comment]
verified on devnet looks fine on 175%
Version c2d6060

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/b7360e19-f856-4789-8b6e-9e3fd5938beb" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/d1181106-db60-4da0-ac59-194507ba38bd" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/734da85a-0332-478d-a7f3-5b28a369b56a" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/1715cb08-74f5-44a4-b882-628178d4a141" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/60dffcc8-497c-4d4f-8bfa-3defd9fae241" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/eba9e474-5231-4ae2-833d-0dd060530687" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/b756772a-707b-436d-a685-ffa2b9cbe97c" />

at 200% is this  acceptable
<img width="359" alt="Image" src="https://github.com/user-attachments/assets/38315aa1-f3ee-4961-9aed-b4a8c564b3bb" />




[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4431573)
