### ISSUE TITLE
Loading of deployments fail

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1267]
![Screenshot from 2023-10-24 11-47-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/6331e2ae-1c7f-4fb0-b05a-ed1921d026dd)

**Comment by maayarosama** [comment]
Done:
- Adding conditions to check if the chunk1, chuck2 and chuck3 arrays is empty or not before adding it to the failedDeployments array, waiting for review.

**Comment by khaledyoussef24** [comment]
verified loading deployments work now fine in solutions and contracts list
env used : devnet

![Screenshot from 2024-01-02 13-49-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/de73e475-3f1f-46b1-8971-c779ebb41903)
![Screenshot from 2024-01-02 13-48-51](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6b69d5de-a87d-4f8d-befb-b683ffc1aa03)
![Screenshot from 2024-01-02 13-48-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a3be4032-528d-494c-a278-947caab8399c)
![Screenshot from 2024-01-02 13-48-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3463c23f-aa89-434c-956e-b3fa10b69acf)

test lodge : 
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4150371
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156491
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156511
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156526

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 10deaba
