### ISSUE TITLE
Pricing calculator return `[object Object]` in the package card

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1271]
Maybe this happens because the return type of the calculate method was changed in the dedicated nodes PR

### Screenshot

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b1e315e1-b13c-4d9f-8d23-0b40f4bfac39)

**Comment by mohamedamer453** [comment]
Update:

Issue should be fixed in #1273.

Status:

Pr is ready for review.

**Comment by maayarosama** [comment]
Verified on devnet 
![Screenshot from 2024-01-02 11-41-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/11b2f098-7289-4361-b79c-e12821be2e71)
![Screenshot from 2024-01-02 11-42-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/8a338e14-e99c-4bdb-aedd-c08b749706cd)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3

![Screenshot from 2024-01-02 14-06-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/74a5be61-def2-4262-8912-b68240fc8ae4)
