### ISSUE TITLE
Standby nodes on stats site

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1275]
Stats does not currently provide any info about standby nodes. Let's either:

1. Present a single set of figures that includes both online and standby nodes
2. Present two set of figures, one for online and one for standby

**Comment by 0oM4R** [comment]
Status: added to PR #1234, and ready for review

**Comment by samtaggart** [comment]
Please know that we are pulling numbers from the current stats.grid.tf site onto the live threefold.io site. Will pushing a new stats site live affect or break the information on tf.io?

**Comment by samaradel** [comment]
> Please know that we are pulling numbers from the current stats.grid.tf site onto the live threefold.io site. Will pushing a new stats site live affect or break the information on tf.io?

We pull only nodes whose status is up on the websites.. standby is different, it will not break our data.

**Comment by samtaggart** [comment]
OK thanks! (cc: @scottyeager) The next step will be to include Standby nodes on the website as well. Just so you know. :)

**Comment by A-Harby** [comment]
Verified, Devnet.

The requests that are being made to every network are for status and standby.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e34a7504-37f3-4026-b441-eb7c2c2b92fb)

**Comment by ramezsaeed** [comment]
@A-Harby 
I can't see status standby in the request; please Re-check..

![Screenshot from 2024-01-01 23-18-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/dbcfbc71-a299-437b-ba88-a37b19192e59)

**Comment by 0oM4R** [comment]
this issue was for stats website not the stats page please check it on https://stats.dev.grid.tf/

**Comment by A-Harby** [comment]
But this should also be implemented on the stats page as the standby is still an online node.

**Comment by 0oM4R** [comment]
please open a separate issue for adding standby nodes on stats playground

**Comment by A-Harby** [comment]
Verified on  https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1275#issuecomment-1873359270
New issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1843
