### ISSUE TITLE
Can't see stats node count on mobile

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1276]
When I open the stats page on mobile in portrait mode, the node count isn't visible and I can't scroll to reveal it. It might also be nicer to stack all data elements vertically in the available horizontal space rather than using horizontal scroll at all.

**Comment by scottyeager** [comment]
![CACE9CD9-AA5F-4EA6-9645-2634B5AFADA9](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/b608b6a3-755e-418e-9f3c-b9e155b0d2f5)

**Comment by maayarosama** [comment]
Fixed in the new stats website https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1234
