### ISSUE TITLE
contacts view: include node id and node status

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1277]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/857d1a88-0964-4ce4-a9f6-9af5d35fa676)

**Comment by 0oM4R** [comment]
status: 
![Screenshot from 2023-10-25 16-30-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/12040bcc-5d10-43fd-abf7-56d5a9e32454)

now i can get node status but can't handle standby nodes as it's supported on girdproxy client on 3.13; 
will handle name contracts tmw

**Comment by 0oM4R** [comment]
__Blocked__: can't handle standby nodes as it's supported on girdproxy client on 3.13;

**Comment by 0oM4R** [comment]
__Status__: PR is ready for review,

**Comment by A-Harby** [comment]
Verified, Devnet 881667d.
Node ID and node status are now displayed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8562fd24-df37-43bc-925d-65850e0a1653)
