### ISSUE TITLE
Dockerfile and chart for new stats

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1281]
### Description
Add an image,  chart and workflows for new stats package

**Comment by hossnys** [comment]
- where is this image to be created ? this repo or tf-images ? 
- where is that new stats package ? on which branch ?
- is there a docs for how it's being built ?
- workflows to be added here also ?

**Comment by xmonader** [comment]
- tf-images is for solutions only, it should be in this repo
- it needs to be configurable with a tag
- should be in the packages/stats
- for the workflows, do as you see fit for image builds, autodeploy, .. etc

**Comment by hossnys** [comment]
all comments on the PR resloved and tested chart and Dockerfile workflow on a fork and it works fine .

**Comment by A-Harby** [comment]
The last release failed: https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7371704245.

**Comment by AhmedHanafy725** [comment]
the last releases worked fine. please recheck it.

**Comment by A-Harby** [comment]
Verified on the new workflows: https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/new_stats_build.yaml
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/27e681cd-4347-4f88-8ffa-55013d02464a)
