### ISSUE TITLE
Issue in the GqlContract fix, the billReports set to an array of one static item.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1283]
### Description

I was debugging something, the `billReports` in the [contracts.ts](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development_313/packages/grid_client/src/clients/tf-grid/contracts.ts#L154C13-L154C13) as set to an array of a static element which will cause an issue, this changed by me in [this PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1255/files)

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/6ede67be-8942-4d1a-9df6-7414d73b639a)

### Related issues

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1254

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1280

**Comment by A-Harby** [comment]
> Should be fixed in #1280

This PR is merged into the 3.13 branch, which will not be included in the 3.12 release.

**Comment by Mahmoud-Emad** [comment]
@A-Harby
It's included in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1297 which will be merged against 3.12 <development> branch

**Comment by A-Harby** [comment]
Code changed to interface, and this will also be verified on the offline node issue.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9a556da2-c0ec-4b0a-9486-c01c413669f6)
