### ISSUE TITLE
Bug in loading deploymenst empty dialog

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1291]
- In k8s it said that it had 1 deployments failed, but the dialog was empty.

![Screenshot from 2023-10-26 10-17-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/169a0992-0c20-48aa-84e9-f3c1f843d342)

**Comment by AlaaElattar** [comment]
- fixed and waiting for review .

**Comment by A-Harby** [comment]
I tried deploying FullVM, MicroVm, and Funkwahle, and all the deployments were successful and lasted in the deployment list, but at the same time, they were also listed in the failed deployment list.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/81c0bdc7-767d-4c11-87b8-49f8ec9973fd)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/54e191db-b4c1-401f-9000-2c8b1776adac)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3c612c95-3237-46d1-8c25-c3dc33067b0e)

**Comment by maayarosama** [comment]
Include contract Id of the failed deployment

**Comment by A-Harby** [comment]
No, what I mean is that every time I deploy a solution, it's deployed successfully, and at the same time, it is shown in the failed deployment list.

https://drive.google.com/file/d/1Cn3g9mK5S-RLcrtGrSSD1HkomgeyJ3By/view?usp=sharing

**Comment by AlaaElattar** [comment]
still working on it

**Comment by AlaaElattar** [comment]
- Fixed and waiting for review.

**Comment by A-Harby** [comment]
Verified, Devnet 2b364e9.

I tried many deployments, and none were shown on failed deployments as before.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/17c4e30d-9eae-42a1-a3e5-2a23a728212c)
