### ISSUE TITLE
timeout contract details in 10s

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1295]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/386840d5-ef56-4554-be25-7110ef38f1ce)

that seems to be a contract we can't get the details of, it keeps spinning for 60s then 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f30d19d9-372d-4609-979f-9181b5d53a51)

It's better to be cancelled in the same UI without moving to another screen

**Comment by 0oM4R** [comment]
__Status__: 
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/2382ac8a-2fef-4358-9bd6-320dae610977)
and will check with Ehab today isA

**Comment by 0oM4R** [comment]
will make another pr to set request time out to 10s

**Comment by 0oM4R** [comment]
changes applied on pr #1336

**Comment by A-Harby** [comment]
Verified, Devnet 86b9355.

The error button appeared to retry with a failed notification, including the contract ID.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c84c8622-6ee7-4a7f-9457-9c078e03c830)
