### ISSUE TITLE
Error while deploying k8s

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1301]
### Description

I kept getting this error while trying to deploy K8s
![Screenshot from 2023-10-29 12-56-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/1ef16f8a-12a7-42d3-ab20-19c4437fd169)

### Steps to reproduce

-  Choose node 124 for the master.

**Comment by AhmedHanafy725** [comment]
node 124 will not be available to be selected by the user as it's a dedicated node, but the network workload picks any random node with a public config to deploy on. So if node 124 is selected the deployment will fail.

the suggested solution is to add `available_for` option while filtering the access nodes

**Comment by AhmedHanafy725** [comment]
the suggested solution is applied

**Comment by A-Harby** [comment]
Devnet 2b364e9.

Deployed kubernete master on node 126 but it still failed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e31e362-fb22-4bb2-b82c-02472b111409)

Node 126 is not dedicated but from logs network contract was deploying on node 124.
[playground.dev.grid.tf-1698858095293.log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/13229686/playground.dev.grid.tf-1698858095293.log)

**Comment by AhmedHanafy725** [comment]
the fix was done on grid client, so the changes didn't trigger the workflow. I'll trigger the deployment manually and put the issue back to verification.

**Comment by A-Harby** [comment]
Verified, Devnet.

I tried different Kubernetes deployments, and they all worked fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6579a91d-f186-43c9-bbc4-68ed886410f1)
