### ISSUE TITLE
Error while deploying Peertube on node 14

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1302]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f06fbe63-cc23-4280-9523-6bac3b5e1ece)

### Steps to reproduce

I tried to deploy Peertube on node 14 and it showed me the previous error. 

Suggested fix:
- The condition should happen before listing the node not after deploying.

**Comment by AhmedHanafy725** [comment]
after some investigation found that this can rarely happen with the following scenario:

- The user selected the gateway node to use (which was node 14 and the node was up for the grid proxy).
- When the user clicks on the deployment button, the grid client starts to add this node to the network.
- The grid client at this moment couldn't find this node in the up access nodes.

So the grid client raises this error as the node goes down.
