### ISSUE TITLE
consistent closing behavior for all pop ups

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1307]
All the following should close the pop up:
- close button
- escape
- click outside the pop up

**Comment by ramezsaeed** [comment]
This pop up doesn't have close button,
escape & click outside the pop up working fine.

![Screenshot from 2023-12-05 16-04-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5a7ceea0-4364-4671-a098-e8c1b07239b8)

**Comment by A-Harby** [comment]
But not done in,

Manage domains/ Add new domain.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5af998bb-13c9-42c7-9af2-0f99adb8cac9)

Farm page

[Threefold Dashboard _ Farms.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f80d50b8-24e8-41e7-9b03-7310c24db5e1)

**Comment by A-Harby** [comment]
Verified,
Devnet a16e38d.
[TC2301 - UI component](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155453)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4c1292a3-f164-4cb4-b941-41627056ceca)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1520cad-4ed8-4542-bad6-c95c9e85cbbd)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 13-25-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a6bd3251-82bb-4cc6-9eea-8749917dd53d)
