### ISSUE TITLE
Add a filter to see only nodes with GPU in dedicated nodes 

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1308]

**Comment by 0oM4R** [comment]
blocked on: https://github.com/threefoldtech/tfgrid-sdk-go/issues/420

**Comment by 0oM4R** [comment]
@ehab-hassan can you please suggest  how the new filter field will lock like ?
the current design:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/5938f6ba-2088-486d-9ac9-71ad35a3c825)

**Comment by 0oM4R** [comment]
Work Completed:
just tried the endpoint and walked through the current filter component

Work in Progress (WIP):
Asked help in the design from Ehab, will create a new type of filter field based on the design because the current filter field support only text fields 

Investigation and Solution:
after the design is completed we may add property to the `node-filter` to accept the new type of fields

**Comment by 0oM4R** [comment]
Blocked on the design, please open an issue for the design @ehab-hassan

**Comment by ehab-hassan** [comment]
@0oM4R let's keep the GPU outside the filter and make it like nodes explore 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1d399947-f41a-4c62-9dcb-b025cfc43f85)

**Comment by 0oM4R** [comment]
### status
Work Completed:
 - added toggle to dedicated nodes page, pr #1376 is ready for review

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

The toggle has been added to enable GPU node filtering only.
Without toggle, the request that is being called:The https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up&ret_count=true&size=10&page=1
With toggle on: https://gridproxy.dev.grid.tf/nodes?rentable=true&status=up&ret_count=true&size=10&page=1&has_gpu=true
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/48567132-a748-47bb-aea2-55888693470e)

[TC2219 - List Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150428)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3

filter works fine in both tabs (Rentable, Mine)

![Screenshot from 2023-12-24 15-19-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/bed457c4-f8be-41cc-b1d5-cd581420ecc0)
![Screenshot from 2023-12-24 15-19-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4e06fe40-e086-47b4-aa3a-d1d9d85a3ecc)
