### ISSUE TITLE
(Mainnet verifications) Select farms randomly while deploying any solution

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1312]
this can be done by 2 requests

- Get the available farms and their count and how many pages.
- Select a random page and get a random farm from this page.

**Comment by 0oM4R** [comment]
@AhmedHanafy725 can you mention the endpoint for the first request please?

**Comment by AhmedHanafy725** [comment]
the same as the current one but set the `ret_count` to `true`

**Comment by 0oM4R** [comment]
Investigation and Solution:
- currently we are using grid client to get the farms and the `send` method returns only the `data` we are locking for a header 
- using gridproxy client is also an option but we will have to change the filteroptions type 
- another solution is to have competition between gridporxy to get the count, then getting the farms after that by the existing option.

**Comment by 0oM4R** [comment]
Work Completed:
I implemented the needed function in gridclient and its call on utils/getfarms
implemented the randomization logic that store the selected pages and pick a new random number that isn't in the selected list 


Work in Progress (WIP):
testing the current flow and have some issue with reset the selected array when the filters got updated, also there is some requests that I didn't catch why they were called.


Investigation and Solution:
- will work on the reset section
- the two requests take so long time to pick the farm, not sure if this is a general issue or something related to my network

**Comment by 0oM4R** [comment]
Work Completed:
all needed logic is done.

Work in Progress (WIP):
 - faced an issue while testing that the website keep making requests and didn't stop,
 

[Screencast from 06 نوف, 2023 EET 05:59:33 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4833d980-0fbf-45ee-8ee2-5e8b1732d9e4)


- the `{ exclusiveFor: props.exclusiveFor }` and filtering the blocked farms on get farms count not sure how to handle this point

**Comment by 0oM4R** [comment]
## status 
Work Completed:
- requests issue is not related to the current solution and i opened an issue for it #1373 
- all needed logic are completed and pr #1370 is ready for review.

**Comment by A-Harby** [comment]
Verified on Devnet,
Every time a solution is selected, the farms are randomized, and a node is shown from that farm.
I tried on devnet, and it only had 2 farms, and both showed after a few refreshings.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/789de5f4-1a2f-434f-97b4-a89798decbfc)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ed531b11-fc06-46d5-aee5-ef1aee65669d)

I will leave it as a mainnet verification because there are more farms on the mainnet, to be sure.

**Comment by khaledyoussef24** [comment]
verified on https://dashboard.bknd1.ninja.tf
version : 2.3.0-alpha6
tried 3 times every time i got a different random node
![Screenshot from 2024-01-22 08-53-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c34fd11c-4fcd-4399-9e6b-bfbc28424d4b)
![Screenshot from 2024-01-22 08-52-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/aa663190-992f-42a6-a2b8-1212fe34f392)
![Screenshot from 2024-01-22 08-52-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/77d969f9-576d-4923-b9b6-6e50a8ae1eca)

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet (Ninja)
- 2.3.0-alpha6
