### ISSUE TITLE
Increase the memory for the `Recommended` package 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1313]
should be 16 GB

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/b6c3a3d6-b182-4469-afab-985db03cf61e)

**Comment by AlaaElattar** [comment]
- done and waiting for review.

**Comment by AlaaElattar** [comment]
### Work Completed:
pr comments applied.

**Comment by A-Harby** [comment]
Is this also to be applied to the new playground?

**Comment by AhmedHanafy725** [comment]
> Is this also to be applied to the new playground?

yes, isn't applied?

**Comment by A-Harby** [comment]
> yes, isn't applied?

No, I couldn't find it, only the old resource packages.

**Comment by AlaaElattar** [comment]
### Work Completed: 
- All solutions updated here https://github.com/threefoldtech/info_grid/pull/339.
- Waiting for review.

**Comment by AlaaElattar** [comment]
- Merged in the info_grid

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
