### ISSUE TITLE
Show sidebar in case the user is not logged in

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1314]
ask the user to log in if he selects

- portal
- solutions
- contracts

also disable the user balance in calculator in case the user is not logged in 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/af1cb645-975b-4088-902b-d7b512a70286)

**Comment by zaelgohary** [comment]
The sidebar is now shown even if not logged in but used can navigate to certain pages. PR is ready for review.

**Comment by zaelgohary** [comment]
Now calculator is broken because the grid is not defined. Will look for a fix tom.

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/996

**Comment by zaelgohary** [comment]
The issue is Blocked on #966 as mentioned in the previous comment. However, as a temporary solution, we can either hide the calculator from the menu for now till it's no longer blocked or copy the same calculator module in the playground which I don't recommend.

**Comment by zaelgohary** [comment]
WIP:
Implementing calculator methods inside Playground for now. They'll be removed once the #966 is done.

**Comment by zaelgohary** [comment]
Work completed:
Applied implemented calculator in resources pricing. The calculator can now be used with or without login.

**Comment by khaledyoussef24** [comment]
environment used :devnet
verified calculator now can be used with or without login
[Screencast from 12-18-2023 02:10:14 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/afff70ae-a072-4fa8-a590-aa92ac4e55aa)
same for all of the dashboard components 
but he asks only for to log in with wallets to process anything more

testlodge :https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155946

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 14-29-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8952e603-c78f-4e6b-a27d-e644f8ac5650)
![Screenshot from 2023-12-25 14-29-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a563334c-fb8a-4b7a-87d4-da8a037b14d8)
![Screenshot from 2023-12-25 14-29-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/f482c15b-ee93-4cc0-8cf8-a2dade9e6ac0)
