### ISSUE TITLE
Add back navigator for the solutions

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1315]
currently, if the user is in any solution and wants to go back to select another solution, there is no way to go back, and have to go solution from the sidebar. It will be easier for the user to go back from the same page.

**Comment by AlaaElattar** [comment]
- done and waiting for review

**Comment by AlaaElattar** [comment]
- applied change instead of calling component in each solution i will just check on path from component.
- so there won't be duplicated code.
- waiting for review.

**Comment by AlaaElattar** [comment]
- working on another change is to add small navigation bar with `breadcrumbs`.
- add back button in weblets.
-  nav bar can be used anywhere.

**Comment by AlaaElattar** [comment]
### Work Completed:
Added second navigation bar leads to solutions page.

**Comment by AlaaElattar** [comment]
### Work Completed:
updated colors on navigation bar in both dark and light mode to be more clear.

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
Trying to solve that when use chooses solution at bottom of solutions page and go back to solutions page, user will be redirected at same position at bottom of page.

**Comment by AlaaElattar** [comment]
### Work Completed:
Solved issue of scrolling down, so now when user navigates to solutions pages will always be navigated at the top.

**Comment by A-Harby** [comment]
Can't we add a back button on the left side? I have been using the site for a while, and it wasn't clear that the solution is the back button.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/feb1ff79-a433-40c4-a94b-8a9a9d465340)

**Comment by AlaaElattar** [comment]
### Work Completed
- Added back button at most right so user can go back from it also

**Comment by AlaaElattar** [comment]
### Work Completed 
- Swapped positions of path with button.

**Comment by xmonader** [comment]
please check https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1623#issuecomment-1848912190
