### ISSUE TITLE
Update login UI to match with new Playground Theme

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1323]
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=429-1841&t=GjNhDyQ38lXLbQeN-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A1248&show-proto-side

what about making the login pop-up smaller and not taking all the screen
<img width="1920" alt="Frame 257 (2)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a35df520-63e0-49eb-88e5-e92314e59c9f">
<img width="1920" alt="Frame 258" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/08243570-b916-4110-af7b-6f9dee4db27c">
<img width="1920" alt="Frame 259" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/0e1079de-a831-423b-a408-5970d889360a">

**Comment by xmonader** [comment]
Thought that was the case for 3.13? if you think we can have it sooner, please let's do

**Comment by ehab-hassan** [comment]
done but need  some help with the code to fix small issue

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a77378e8-f8b8-465b-8833-a02057ec27d9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c3608218-3762-41fe-8ea6-5fa3cceafc7d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/e0b9217d-1bd7-4e50-b714-3d5ce7b3f126)

**Comment by xmonader** [comment]
Incredible job @ehab-hassan tslm edek!! @maayarosama can you please assign someone to check what Ehab needs?

**Comment by maayarosama** [comment]
> Incredible job @ehab-hassan tslm edek!! @maayarosama can you please assign someone to check what Ehab needs?

@AlaaElattar is now assigned to help ehab with any issues

**Comment by ehab-hassan** [comment]
Thanks, @AlaaElattar for helping, ll create the PR

**Comment by A-Harby** [comment]
Can we add a tip for the Activate account button? Because it is confusing to have Connect, Activate, and Create an account all at once.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7f65b86c-9f60-40c4-93f1-61b9ff39a7ac)

And also, can we show the same tip below for the hex seed as before the connection?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e1b99e27-3cac-46b6-98d2-0fbef0786977)

And why don't we show the mnemonic?


And this issue is reported [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1595)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f94813bd-381b-40dc-bd49-74f0e5854e6a)

**Comment by AlaaElattar** [comment]
> Can we add a tip for the Activate account button? Because it is confusing to have Connect, Activate, and Create an account all at once. ![image](https://private-user-images.githubusercontent.com/109473873/288434394-7f65b86c-9f60-40c4-93f1-61b9ff39a7ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTU2NjQsIm5iZiI6MTcwMjU1NTM2NCwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4NDM0Mzk0LTdmNjViODZjLTlmNjAtNDBjNC05M2YxLTYxYjlmZjM5YTdhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxMjAyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWU3OGE3ZmQ5NzAwNmM3NmIwMjRmNmRiNGNmYmFlODdmY2UwZGIwZTJkOTA2ZWQ2ZDliOTc0OTQ5OGNjZWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wYNev7nI4HlIcRb96fIvAnXuFDZPxf5wvOcqslfgxb4)
> 
> And also, can we show the same tip below for the hex seed as before the connection? ![image](https://private-user-images.githubusercontent.com/109473873/288435020-e1b99e27-3cac-46b6-98d2-0fbef0786977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTU2NjQsIm5iZiI6MTcwMjU1NTM2NCwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4NDM1MDIwLWUxYjk5ZTI3LTNjYWMtNDZiNi05OGQyLTBmYmVmMDc4Njk3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxMjAyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjFhMDc4OTEyNzcxMmQxNDYwYzVkODU5Y2RiOTkwMDg1MDgyNDk4MDk2OTc4MjFiOGM2OWI0ZTE1MzE2NWYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KRW3SJNqkxTsOWirypjg1KMCOEqKhkzqt3zjzGF_Qt0)
> 
> And why don't we show the mnemonic?
> 
> And this issue is reported [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1595) ![image](https://private-user-images.githubusercontent.com/109473873/288435197-f94813bd-381b-40dc-bd49-74f0e5854e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NTU2NjQsIm5iZiI6MTcwMjU1NTM2NCwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4NDM1MTk3LWY5NDgxM2JkLTM4MWItNDBkYy1iZDQ5LTc0ZjBlNTg1NGU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNFQxMjAyNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWQ0NWM5YmVlNTdjNTUwNWE1ZTA5ODZmN2Y5OTZlN2I5MWFjZjM5NDliZWI3OGFmMTcxYWFmZTAyYTczNDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YD38E1u4iSzy2AdqjpLDfhANqBTsMS4D5EvEHidnCvQ)

about showing hex seed not mnemonic this will be fixed in this issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1696

**Comment by AlaaElattar** [comment]
### Work Completed:
- Added tooltip for `Activate Account` button.

**Comment by A-Harby** [comment]
When navigating between tabs, the validation error isn't reset.

[Threefold Dashboard: Your Farms (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/80d9394a-258f-42be-9cc0-d907569e80ef)

**Comment by A-Harby** [comment]
Verified,
Devnet, b75e477.

[TC2114 - Login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150323)
[TC2113 - Connect Wallet](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)

The validation error was fixed and reset when changing the tab or closing it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8ddda2de-c609-4ebc-b088-9b1451345eb3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5569c122-ffd7-495b-bb06-88f13b431f2c)
The responsive issue was fixed, and mnemonics replaced the hex after login.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b657ea32-66f5-4479-9ba8-b25c739c9217)
