### ISSUE TITLE
The list of full VMs is stuck in the loading in case there is an error

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1324]
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/8c1161f3-26b7-4402-b803-692585111d64)

**Comment by MohamedElmdary** [comment]
Can you provide steps to reproduce this issue? @Mahmoud-Emad

**Comment by xmonader** [comment]
critical = needs to be resolved in the same day (nobody leaves the office)
major = to be solved in 1-2 days max. 

Is it so? 

@maayarosama please make sure the team understands this too as well

**Comment by A-Harby** [comment]
Verified, Devnet 86b9355.

I tried deploying multiple VMs, and the listing was fine. I also tried the in-grace period saturation, and the listing was working with no issues.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f08948f3-c248-46c0-b2fe-b819c2d3137e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cca5e798-caac-42d0-bdcb-a17a9201b595)
