### ISSUE TITLE
Error while fetching and getting value of key (encrypted deployment)

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1325]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/103cbf5c-a239-498c-bf6f-2c10e6a04e61)

 - There're 2 deployments encrypted, so it's expected to appear as failed deployments but this doesn't happen.
 - It's because the logs are from migration.

**Comment by A-Harby** [comment]
Verified on Devnet,
The issue isn't reproducible till now; I will try more and reopen if it happens again.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f45cb1ad-da39-4f86-bb31-3e2bb63fe290)

**Comment by A-Harby** [comment]
I got the same error on qanet 2.2.0-rc2

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d30c9f13-17ad-40e0-9869-209f4b974e0a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9bad74d0-4c81-417b-935f-47360fc7b6a5)

**Comment by ramezsaeed** [comment]
Got the same error on QAnet

![Screenshot from 2023-11-28 15-46-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0cda82f5-a458-4265-9c11-ac4ce96473ba)

**Comment by ramezsaeed** [comment]
verified and cannot reproduce anymore on:
- Devnet
- version: d87cc99

**Comment by ramezsaeed** [comment]
Reproduced again!

- Devnet
- version: d87cc99

![Screenshot from 2023-11-29 11-02-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0c4c4206-8680-48a5-8075-8b4cdd5faff8)

**Comment by khaledyoussef24** [comment]
i got the same error on devnet dashboard
![Screenshot from 2024-01-02 07-20-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/265e0b24-8f81-4eb1-86ea-da1ecd9d3ada)
![Screenshot from 2024-01-02 07-20-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/caedc8ec-cdbb-4d29-833a-fe6ab12f660d)

**Comment by ramezsaeed** [comment]
Verified the failed deployment in the pop-up message;
only one concern the error message showd be shown in the pop-up.
will be followed here:
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1214

- Devnet
- 2.3.0-alpha3
