### ISSUE TITLE
Capacity flavor labels

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1326]
Right now the capacity flavors are:

* Minimum
* Standard
* Recommended

These are confusing, I think. Firstly, because it suggests that the user can't select less than the "minimum", when they can in fact choose lesser specs with the custom option. Secondly, we present a rather large VM size as "recommended", even for generic VMs where the use case is unknown.

Maybe better to keep it simple like:

* Small
* Medium
* Large

**Comment by xmonader** [comment]
I do agree. Let's update that.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 6d0ec3d
- [TC2186 - Select instance capacity](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4150395)

The Solution capacity was changed to Small, Medium, Large, and apply to reset of the solutions.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/47d48c58-5a1c-4f74-80f3-0639ae5c90e1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6e04c07c-46df-48ba-872a-62448f8d27a9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0c3472b8-f4bb-47cd-93c2-f0899386ea56)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6fa4401a-eda4-4f2c-b12f-742503d961e0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b7a1522c-96ce-4bb5-84bf-cf97356d679d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c73f55b4-c44b-4f42-88fc-39b490188653)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- 000eea2
