### ISSUE TITLE
Farm name filter should accept more characters

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1327]
The farm name filter rejects names with special characters, but some special characters are legal in farm names:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/32733337-aeb3-4792-8b5e-f397ab34044f)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/510e0c9f-7fc1-455c-b2c7-53b582638b8e)

This input field should accept all characters that can appear in farm names (I'm not sure which those are).

**Comment by amiraabouhadid** [comment]
Fixed in explorer farms PR

**Comment by maayarosama** [comment]
> Fixed in explorer farms PR

https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1240

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 6d0ec3d
- [TC2274 - Filter Farms by Farm Name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150483)

The farm name Filters accept special char in its validation.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f95c36e6-a8cf-4037-8dad-9b4c9f36f7f3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0a687f25-5c49-4410-b65b-2bc38f1bbd85)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- 000eea2
