### ISSUE TITLE
mass deployments workflow is failing 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1333]
### Description

Currently the mass deployments workflow fails since it checks out `v2.2.0` which is not released yet 

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/mass_deployments.yml

**Comment by A-Harby** [comment]
Verified,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f55679a4-d428-4203-9f73-9e23c8d14399)
