### ISSUE TITLE
Notification colors lost in incognito mode

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1338]
### Issue Description

**Problem:**
When using the playground in incognito mode, the theme does not load correctly. This issue arises because incognito mode does not have access to local storage, which is used to retrieve the current theme settings.

### Screenshots

**1. Normal Mode (Regular Browsing)**

- ![Normal Mode](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/7f965806-679f-455f-ba57-9a350eebd624)

**2. Incognito Mode (Private Browsing)**

- ![Incognito Mode](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/030151c9-1883-411c-ab3e-ee07d246172d)

**Comment by Mahmoud-Emad** [comment]
### Work Completed:
The issue should be fixed in the mentioned PR.

### Work in Progress (WIP):
No work in progress related to this issue till now.

### Investigation and Solution:
was checking if there is a `theme` key stored in the `local-storage` and yes I found that if the user does not click on the theme mode we don't set it, maybe we need to set a default value for it, so this is the solution

**Comment by A-Harby** [comment]
verified.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ddcbcd93-0dd5-4654-a860-235dd1cdebca)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7fc11f1f-d69b-44e1-be35-2743205c4fef)
