### ISSUE TITLE
Replace the `Mocha injected CSS` with CSS variables to be matched as Vuetify classes

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1340]

**Comment by AhmedHanafy725** [comment]
do we still need this?

**Comment by Mahmoud-Emad** [comment]
We can disregard this one as we now have multiple solutions:

1. @ehab-hassan adjusted the colors to work seamlessly in both dark and light modes.
2. @MohamedElmdary developed a new toast package, which we can integrate at a later stage.

Considering the available alternatives, I will proceed to close this issue for the time being.
