### ISSUE TITLE
micro vm: No indicator that the ssh key is missing

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1344]
### Description

i can't deploy a microVM. After some time, I notice that the ssh key in the env tab was empty. After I added my ssh key, the deploy button got enabled. the issue is that there is no indicator of what exactly missing 

[Screencast from 02 نوف, 2023 EET 11:47:36 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/bd12956f-e42c-4d57-9042-14fa2de51f56)

### Steps to reproduce

in the mentioned scenario, i deleted all of my keys on the chain while testing another issue, so the ssh key got deleted.
then go to micro vm in solutions tab and pick a node. After that, all fields are valid, but the deploy button is disabled.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : ac5cd85


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0bcc84eb-eab2-4a32-8588-833892622d83)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/26b1fa96-9283-455d-b3d7-23a97280d4f1)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4243816
