### ISSUE TITLE
QA: acceptable interactivity/performance

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1355]
## Acceptable interactivity/performance:

- [ ] Profile manager Login.
- [ ] Profile manager Generate account.
- [ ] Profile manager Activate account.
- [ ] Listing Farm Names.
- [ ] Listing Nodes.
- [ ] Listing Deployment List.
- [ ] Listing Contract List.
- [ ] Delete the deployment.
- [ ] Delete the contract.

**Comment by A-Harby** [comment]
I noticed a couple issues that occurred to me more frequently than they should have after the last release.

- Failed to delete the deployment.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5eea38d9-8ce7-47a6-b97f-aaf4a21a9e2a)
- Failed to load deployment details.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1bfde69f-d223-4da6-b5b5-bcf93ee4337f)
- Failed to load the deployment.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a5805111-0582-4bc6-b507-67af68841f30)
