### ISSUE TITLE
QA: prepare scenarios for data migrations

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1357]

**Comment by A-Harby** [comment]
I updated the grid update test suite to check data migration cases after the release.
https://app.testlodge.com/a/26076/projects/40893/suites/217765

**Comment by A-Harby** [comment]
Verified from these test cases.

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1291

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1401

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1400
