### ISSUE TITLE
Show total spending of user's contracts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1359]
Should show the amount spend / hr and its equivalent / month somewhere in the contracts view

**Comment by AlaaElattar** [comment]
- The amount spend/hr already exists in `Billing Rate` .

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/fc099bd7-b6b8-4bba-8729-864fa51a23ff)
 - so would u like to add another column for equivalents/month or what ?

**Comment by xmonader** [comment]
My bad it wasn't clear enough. I'm trying to figure out how much all of the deployments are costing me e.g hourly or monthly (not sure UI/UX wise) I'm suggesting it could be shown after the table?  `X TFT/hr and X TFT/month` and maybe a tooltip button that shows the equivalent in dollars?

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
Still working on the issue, trying different ideas to choose best UI of showing total spending of user.

**Comment by AlaaElattar** [comment]
### Work Completed:
I've added `v-alert` at end of table showing total cost of contracts per hours and its equivalent per month. In case the table is empty, the alert won't appear.

**Comment by AlaaElattar** [comment]
### Work Completed:
- I've modified the `NormalizedContract` to calculate consumption as number not string, so i won't have to use regular expression.
- Just checking in table if consumption == 0, so I will show `No Data Available`.

**Comment by ramezsaeed** [comment]
regarding to this comment,
is the https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1359#issuecomment-1801903260

is this implemented:
tooltip button that shows the equivalent in dollars?

**Comment by AlaaElattar** [comment]
> regarding to this comment, is the [#1359 (comment)](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1359#issuecomment-1801903260)
> 
> is this implemented: tooltip button that shows the equivalent in dollars?
- It's implemented like this.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/ee5df622-373b-413b-9a57-093b584ea836)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3
- Testlodge: https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4161190

![Screenshot from 2023-12-24 12-50-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e31ac5d3-9dab-4957-8805-025ed41ccb92)

**Comment by ramezsaeed** [comment]
Agreed with @AlaaElattar  to get it back to in progress, in order to implement this part

tooltip button that shows the equivalent in dollars

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f375bdb1-bacd-48ff-8e72-03f42537ba2a)
the tool tip is added showing equivalent dollars spent

**Comment by A-Harby** [comment]
Last comment on the issue: the USD price decimals are too big.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/976fb4b6-d6b0-4790-a04a-49033be63397)

**Comment by A-Harby** [comment]
Verified,
Devnet, 2.3.0-alpha3.

[TC2162 - List Deployments](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4150371)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f58ee2b9-9cb0-4ed8-a16e-0b091a0a8b92)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3


![Screenshot from 2024-01-01 23-03-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/683856d0-18d1-4aa2-a336-6abfd7995bff)
