### ISSUE TITLE
Adding a warning to notify the user that deleting the contract failed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1360]
### Description

I tried to delete a Kubernetes deployment twice, but it didn't do anything, and I only knew from the logs that it failed.
 
When any deployment fails to be deleted, the user should be notified.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fbd2ece6-0502-40a4-90a2-76eb0f6bd6e2)

**Comment by xmonader** [comment]
should be skipped in 3.12 testrun

**Comment by 0oM4R** [comment]
Status: 
1. Work Completed:
  - added getGrid to try block and added toast to show that something went wrong
2. Investigation and Solution:
  - for getting the grid we need to handle it in many places like contracts list; if any network issue happen will keep loading forever

**Comment by A-Harby** [comment]
Verified,
Devnet, 3fc8787.

An error message is now shown when the connection fails.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ef341aa-4453-4788-85ee-0a118461843c)
