### ISSUE TITLE
Can't ssh to any deployment on qanet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1361]
### Description
Qanet, 2.2.0-rc2.

I can't ssh into any of my deployments. I have tried many deployments with different solutions, different nodes, and different accounts, but I have not been able to ssh into any of them.

In the image below, I tried deployment on nodes 2 and 3.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e2ee843f-8f25-4b25-8321-585c3acdd72c)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/95b9b3c3-efb7-4c74-a208-043e16c55e8d)

**Comment by A-Harby** [comment]
> and on public ips?

Both public and ygg ips

**Comment by A-Harby** [comment]
> and on public ips? 

Both public and ygg ips

**Comment by khaledyoussef24** [comment]
@xmonader can not make any deployment now with or without public ip

**Comment by xmonader** [comment]
and on public ips?

**Comment by A-Harby** [comment]
Closing issue as it wasn't the network problem but it was a Ygg version problem.
and the solution was https://forum.threefold.io/t/yggdrasil-upgrade-action-required/4124.
