### ISSUE TITLE
Error on canceling multiple contracts on the Playground

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#1365]
### Description

Checking multiple contracts and canceling them return an error that the contracts don't exist.
![image_2023-11-05_12-27-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/e11cfe7d-690f-4dd1-b568-3705ee1efa54)
![image_2023-11-05_12-27-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/8a6c931b-45e7-496e-b6e0-62e15000bccf)
![image_2023-11-05_12-28-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/16d05f3e-6166-438f-9887-8f3c3a97b386)

### Steps to reproduce

- Check a contract
- Press on refresh button
- Check it again
- Delete the contract

**Comment by AlaaElattar** [comment]
- so u deleted some contracts then refreshed it and found them again ? Is that the case?
- If yes, there's already message says `Deleting contracts may take a while to complete.`
- If not, please i need more details.

**Comment by AlaaElattar** [comment]
- I misunderstood the issue, the case is true.
- It consider deleting the same contract twice.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/2e88e7d4-8743-4106-96c9-a03e32debed9)

**Comment by AlaaElattar** [comment]
### Work Completed:
It's handled that each time user will refresh, all previous selections will be removed

**Comment by AlaaElattar** [comment]
### Work Completed:
I've applied comment pr, which was resetting `selectedContracts` to empty before start loading.

**Comment by khaledyoussef24** [comment]
verified 
[Screencast from 12-26-2023 08:53:16 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7a47d33f-7ec1-4c87-bfac-8efef8faecd0)

testlodge:https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4150373

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
