### ISSUE TITLE
deployment isn't listed on the FullVM

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1369]
### Description

Qanet 2.2.0-rc2.

I got deployments on the FullVM, but it doesn't list them on the deployment list and doesn't show any error on the logs or show a failed deployment list.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f4c8c4e8-c522-4767-83a0-f3dd009ebbef)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8fafbd20-2cc5-4e92-a03a-ebc574c224f4)

**Comment by ramezsaeed** [comment]
please check if reproducible on devnet or not.
as it should e fixed there.

**Comment by A-Harby** [comment]
Verified on devnet.
Updated is done but not released yet on devnet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f3cd0540-1601-4347-80b8-6ebd9be03fd2)
