### ISSUE TITLE
Manual links is outdated

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1371]
### Description

All the manual links need to be updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e4427412-9562-4fb7-a1a7-cfe1ee54b597)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6a3db063-b321-482d-b88c-eb6b5b7478ca)

**Comment by xmonader** [comment]
Is that from the weblets? if yes please ignore

**Comment by A-Harby** [comment]
its from Weblets.
