### ISSUE TITLE
Manage Domains

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1375]
### Search first

Search for similar issues first, if you got no results, complete the following template

### Description
Might be a good idea to add a 'close' button in manage domains dialog in solutions table to be consistent with its neighboring json details dialog

### Implementation

just add a button 'close' that clears dialog related variables

### More

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/93590d96-6b69-4ee9-a812-4054e8298a2d)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622

![Screenshot from 2024-03-31 23-54-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/713370c1-3d2c-46a1-b119-94bf40754db0)
![Screenshot from 2024-03-31 23-54-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/d60777d3-f082-4244-82d9-eec9ab8e3ab5)
