### ISSUE TITLE
dedicated nodes filter

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1387]
### Description

dedicated nodes filter is not working 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/92fede07-ec89-42b3-b047-015774925eca)

### Steps to reproduce

go to dedicated nodes page in portal try to filter using any of the fields given 

### Logs/Alerts

no logs or alerts

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Just checked the filters and they seem to be working without any issues.

[Screencast from 20-11-23 15:12:07.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/406e49a8-6afe-420a-8946-08de917048da)

I've also ran the playground on mainnet to check the gpu filters and they also seem to work fine.

[Screencast from 20-11-23 15:23:11.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d7d5ac83-ca91-4bfa-b15a-4b3d07a07ec8)

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 13a87cf
- [TC2225 - Filter dedicated nodes by Total SRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150434)
- [TC2226 - Filter dedicated nodes by Total HRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150435)
- [TC2227 - Filter dedicated nodes by Total MRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150436)
- [TC2228 - Filter dedicated nodes by Total CRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150437)
- [TC2229 - Filter dedicated nodes by GPU's vendor name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150438)
- [TC2230 - Filter dedicated nodes by GPU's device name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150439)

The filters are working fine with no errors either in rent or min tabe, with resources and GPU filters.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b3444a2c-f018-478c-b5cf-f793f357e6ef)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/efd6838e-291a-4978-8e3f-4057f2017695)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
