### ISSUE TITLE
integrate perf tests results in the UI

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1388]
TBD

**Comment by zaelgohary** [comment]
WIP: 
Currently working on implementing getPerfTest in grid client. Once done, will apply it in Dashboard.

**Comment by zaelgohary** [comment]
WIP:
Added perf tests to grid client. Currently working on displaying them in node details.

**Comment by zaelgohary** [comment]
WIP: currently working on changing the iperf card style.

**Comment by zaelgohary** [comment]
Removed to in progress because perf tests are not shown in case of grid is not defined.

**Comment by A-Harby** [comment]
Devnet, 2311246.
On some nodes, the tests are repeated.
eg. Node ID 171.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b742439d-d3c6-4e7f-abdd-782d191803a7)

**Comment by zaelgohary** [comment]
Work completed:

Added a check to slice the returned result if its length > 4.

**Comment by zaelgohary** [comment]
The current behavior in zos returns tests done against gateway nodes. As a temporary fix, I sliced the array to return only results of one node. Opened a new [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2231) so we can edit this once it's changed from zos side.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 75e5a1b
![Screenshot 2024-02-26 at 11 51 01 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ac839668-3dda-433e-9f2d-04f599011d87)
![Screenshot 2024-02-26 at 11 51 10 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b80075fe-720c-4e9a-a975-de22fe2de749)
![Screenshot 2024-02-26 at 11 51 22 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ac1ddc1f-acf3-4ee9-8dca-a1d060d0976e)
![Screenshot 2024-02-26 at 11 51 28 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fa5f5158-26f3-48a0-a42c-59495d2bedbc)
<img width="1348" alt="Screenshot 2024-02-26 at 11 58 58 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7751d641-c532-487e-9cea-17cf38e8178e">

https://app.testlodge.com/a/26076/projects/40893/suites/234919?expand_section=420793#case_4219987

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 48a660d


![Screenshot from 2024-02-27 11-22-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/c0792fe3-b7df-4107-bd79-adcc43231b24)
