### ISSUE TITLE
deployments made by terraform can not be seen in deployments lists only shown in contracts lists

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1389]
### Description

deployments made by terraform can not be seen in virtual machines deployments only shown in full contacts lists

virtual machines deployment list
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/155dc890-9f65-4a32-acb8-e97565a25d0e)

full contract list (the solution type is shown correctly)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3c3a1139-ac39-4c0a-8839-39974834989f)

**Comment by xmonader** [comment]
they're using different ways to store the data, it will be addressed in upcoming version for a unified metadata format

**Comment by khaledyoussef24** [comment]
@xmonader so it is not an issue,right ?

**Comment by AhmedHanafy725** [comment]
will be handled here #23

**Comment by MohamedElmdary** [comment]
WIP
1.
  - Added ui related to k8s and virtual machine listing
  - Disabled actions for deployed deployments from outside grid_client

2.
  - Add testing path in pr and start working on it
  - Notice issue while listing deployed k8s
  
3.
  - invested issue and found that it was timingout because we need to improve how we fetch contracts (filter on graphql level no client level)

**Comment by MohamedElmdary** [comment]
- Move contracts filter to graphql level instead of client level

**Comment by MohamedElmdary** [comment]
WIP
Now all deployment lists showing `all deployments` switch to toggle between show/hide deployments from other clients

**Comment by MohamedElmdary** [comment]
WIP
investing in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2124#issuecomment-1941829846

**Comment by AhmedHanafy725** [comment]
### Work Complete

> WIP investing in [#2124 (comment)](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2124#issuecomment-1941829846)

loading the network from the contracts fixes this issue.

**Comment by A-Harby** [comment]
I deployed a VM and Kubernetes using Terraform v1.9.3.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e6985042-79cf-4410-a06b-f049985920bd)

VM isn't listing anything and Kubernetes is failing to load the deployment and doesn't even show the yellow warning message Fail to Load!.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e473c87-f971-430a-9aec-ec69998a8df0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f384ddbd-dc70-4423-910f-cb258f4d96f8)

**Comment by AhmedHanafy725** [comment]
the upcoming release for Terraform will contain the update of the metadata. then this issue can be verified

**Comment by khaledyoussef24** [comment]
version : bee662d
network : devnet
terraform version : 1.10.0

steps made  : 
made deployments for vms and k8s using terraform.
the deployments were only shown in contract lists.
![Screenshot 2024-03-28 at 9 59 47 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/53be5eed-5b41-4c74-aaaf-640827c3cae7)
![Screenshot 2024-03-28 at 10 07 00 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3994da84-27ec-4bb2-a50f-d591adff9d97)

while in deployment list : 
![Screenshot 2024-03-28 at 10 08 15 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dd229f9c-b28a-4d80-a775-beb418638854)

the k8s deployment list reproduced an old issue
[k8s deployment list does not load
](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2161)
![Screenshot 2024-03-28 at 10 03 16 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1556c815-f049-4ba6-b794-f3c4321e9585)

**Comment by MohamedElmdary** [comment]
@khaledyoussef24 can u enable `show all deployments` switch?

**Comment by khaledyoussef24** [comment]
It worked but it should all the solutions ( subsquid and other deployments) not specified to the micro vms.
It should be working this way?

**Comment by khaledyoussef24** [comment]
after discussions, it was explained that terraform by default sets the projectName to Virtual Machine while dashboard looks for vm/<name> so it still needs modifications and work.

**Comment by khaledyoussef24** [comment]
worked fine in taiga but it did not go well in k8s or this is another issue ?
> version : [efad68b](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/efad68b782e26b318d0018febaf85c74395d6d64) I made a deployment using terrafrom k8s but did not load in deployment list
> 
> ![Image](https://private-user-images.githubusercontent.com/110984055/337984102-1e9478a1-5729-4574-9b21-26d6445e4edb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDY4MzEsIm5iZiI6MTcxNzk0NjUzMSwicGF0aCI6Ii8xMTA5ODQwNTUvMzM3OTg0MTAyLTFlOTQ3OGExLTU3MjktNDU3NC05YjIxLTI2ZDY0NDVlNGVkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxNTIyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGY2Njk3N2VkNzhkMzQ2ZGYwNTg0YzY3YjQxY2M2OWU1YjAxMDc2YzZjOGVlMzIxNmVhZWE2NTU4ZjE1ODNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U0pm91JTXPzBbYWO3PwY4tKYRFiWMIIxzbvIVeIDZZU) may be it is related to [#1389](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1389)
> 
> ![Image](https://private-user-images.githubusercontent.com/110984055/337984334-6ac520a1-867c-4dff-b6d5-78f8549a50b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDY4MzEsIm5iZiI6MTcxNzk0NjUzMSwicGF0aCI6Ii8xMTA5ODQwNTUvMzM3OTg0MzM0LTZhYzUyMGExLTg2N2MtNGRmZi1iNmQ1LTc4Zjg1NDlhNTBiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxNTIyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGM5MmQ5YjRhMWMzZjQyYmNhNDhhNWFiYWVmYTQxNmFhYTBhMDEyZDJmMGMwZTc4MTExZTVjNTllOTU2YTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sbd0FmH7qdH2qljvqaN07hUb5ZJQ_k31Q-2Hrj6L9v0) ![Image](https://private-user-images.githubusercontent.com/110984055/337984335-a826b715-9361-4282-9478-6061891d9eea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDY4MzEsIm5iZiI6MTcxNzk0NjUzMSwicGF0aCI6Ii8xMTA5ODQwNTUvMzM3OTg0MzM1LWE4MjZiNzE1LTkzNjEtNDI4Mi05NDc4LTYwNjE4OTFkOWVlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxNTIyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZGYwMTlkOGY4ZWNjOWJmNGMyNWEwN2NiZjMzYmUzOGEyZmFkNThhOTQ0NDJhMDJmZWYzNzViNmFlNmRkNmY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3WYwDDtR-H0y27zFsoFCL8b42rfW50xaouXN-0peWc8)

**Comment by AhmedHanafy725** [comment]
for kubernetes, please check https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2161#issuecomment-2158734732

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9fd76a5
deployed k8s and worked fine on dashboard (followed the steps of commenting the `solution type`)
terraform version : 1.11

<img width="837" alt="Screenshot 2024-06-11 at 12 11 08 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/45495f6d-3525-4c06-b422-89c5240a9b91">

<img width="1128" alt="Screenshot 2024-06-11 at 12 01 31 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/11cf0848-e508-46c1-a283-92c3e447e206">
<img width="712" alt="Screenshot 2024-06-11 at 12 10 53 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fbc9087a-03c3-4b65-a4b1-76fde55232d5">

worked in taiga and vms as well and


[VM test](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4295961)
[k8s test](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4295958)
