### ISSUE TITLE
UI: Kubernetes Manage workers modal box doesn't display the added workers once they are added.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#139]
Tested on devnet

### Description

- In the `Manage Workers` modal box after successfully adding a worker you get a message that the deployment is successful and the worker was added.

   ![image](https://user-images.githubusercontent.com/101194226/171153565-30ec40b9-eaab-4f55-9a1d-f56d93accb4d.png)

- But when you return the worker is not visible in the workers list and you have to close the `Manage Workers` modal box and reopen it for the worker to appear.

   ![image](https://user-images.githubusercontent.com/101194226/171153868-69be062e-445b-44c1-88ad-284785b9636c.png)

- After closing and reopening the modal box the worker appears in the workers list.

   ![image](https://user-images.githubusercontent.com/101194226/171154652-b03e347b-bbd3-4663-b37b-82ca8f9f733f.png)

### Steps to reproduce

- Navigate to https://play.dev.grid.tf
- Navigate to the Kubernetes tab.
- In the deployment list click on `Manage Workers` for any deployed cluster.
- Configure and add a worker
- Wait for the worker to be added.
- After the success message click on `Back`
- The worker is not visible in the workers list and you have to close and reopen the modal box for the worker to appear

**Comment by Mahmoud-Emad** [comment]
Should be fixed now 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/38f1bf44-6f65-4173-8cfc-10f76b60bd44)
