### ISSUE TITLE
grace period for dedicated node is not clear when you try to deploy on the node

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1390]
### Description

I have a dedicated node which is in grace period ,when i try to make a deployment on it i get that no space on disks instead of that the node contract is on grace period
![Screenshot from 2023-11-09 10-25-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/274373d1-0dfe-4d3c-8c56-60caa6b6d411)
![Screenshot from 2023-11-09 10-25-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/857d4edc-99e0-4f7e-8602-1425f1ad9828)

### Steps to reproduce

1-reserve a dedicated node
2- transfer all your tfts
3-wait for it to become in grace period
4-try to make deployment on the node

**Comment by AhmedHanafy725** [comment]
the deployment didn't even start so I think this is a connection issue which is handled here #1341.

**Comment by MohamedElmdary** [comment]
Add more validation (in node_selector.vue) to check if rent contrat of node (node) is in grace_period ..

**Comment by AlaaElattar** [comment]
### Work In Progress:
- make checking grace period in UI while validating node.
- so if node in grace period deploy button won't get enabled.

**Comment by 0oM4R** [comment]
It looks like this pr causes an issue while deploying solution #2394 
`if (contractInfo.state.gracePeriod)` I assume this is the issue

**Comment by khaledyoussef24** [comment]
verified on devnet
version : a03d4ed




![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e714ae4b-e7d2-4e36-8caa-9b0b87cbc4f5)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/65732238-9f47-42d3-8a14-29885ec5d162)


the error message is now clear
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430127#case_4260717
