### ISSUE TITLE
A better message error for `account balance is too low`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1394]
### Description

The error message should be more user-readable when the account doesn't have enough TFT to submit any transition.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1ad016cf-c158-406e-bcc8-0346a8afc896)

**Comment by A-Harby** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1665

**Comment by 0oM4R** [comment]
should be resolved in playground



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/69eb7f4c-d1f8-4617-8028-5b28e23c4703

**Comment by A-Harby** [comment]
Verified,
Devnet 842ebef.
[TC2443 - Set Fee](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4164651)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/40cd5292-0bed-4a1f-9243-ed5e8d2bdc1f)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
