### ISSUE TITLE
Update toast colors to match with dark and light mode

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1399]

**Comment by ehab-hassan** [comment]
Updated toast colors with default colors used for warning and danger, info, and success. to work with both light and dark modes. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a3024ef7-b6fd-405a-9f7c-5a15d61ead6a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/9a2d27af-9b57-4462-a236-701ec8961b9f)

**Comment by A-Harby** [comment]
Verified,
Devnet, 3fc8787.

For success toast color,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/712de977-59e5-4200-b5ad-4e32ed0fc637)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/61d82d42-a41b-4b24-962f-c94c6fb6b5b3)
For informative toast color
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9f0bb474-53b4-4f1d-81fc-7ab9eb752f21)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5b6fba5c-d12c-4d80-8d43-025f1fa4550b)
For warning toast color,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c5d7ee5f-2b28-4991-8f17-813492f43a9e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ff41df8-4d1c-4199-9d78-686cdd2dd898)
For failed toast color,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4d17c514-3886-4f2b-8784-379a02f1d2ad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/103e1e9d-1970-4340-98b9-a0072f267227)

**Comment by ramezsaeed** [comment]
verified
- devnet
- ebf75a3
