### ISSUE TITLE
CapRover Worker is not appearing in the CapRover dashboard after a successful deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#14]
### Description

 Caprover Worker is not appearing in the Caprover dashboard after a successful deployment through the [ `caprover_worker.ts`](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/caprover_worker.ts) script.

After successfully deploying a working Caprover instance through the [`caprover_leader.ts`](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/caprover_leader.ts) script, i then navigated to the provided url and enabled https, then i navigated to the cluster tab and created a self hosted registry, after that  from the leader vm i executed  `docker swarm join-token worker` to get the swarm token, then i configured my worker with the provided token and leader ip and deployed it and it was deployed successfully. however the worker did not appear through the caprover interface in the cluster tab and only the master was available there.

![image](https://user-images.githubusercontent.com/101194226/227775422-f8cb2f67-2b18-45e1-9c2a-297c75760667.png)

### Logs

- [Leader](https://gist.github.com/mohamedamer453/6edacf8257ff0fa622fc83966b52a586).
- [Worker](https://gist.github.com/mohamedamer453/e992e8855c042fec6bea54689355d5f5).

### Steps to reproduce

- Configure and deploy a leader node from [`caprover_leader.ts`](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/caprover_leader.ts).
- Access the instance through the provided url after the deployment.
- Enable https.
- Create a self-hosted registry.
- ssh to the leader vm and execute `docker swarm join-token worker`.
- Configure the worker with the provided token and the leader ip in [ `caprover_worker.ts`](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/caprover_worker.ts).
- Deploy the worker.

### Environment

- Network: `Testnet`.
- Client Version: `v2.0.0-rc12`.

**Comment by xmonader** [comment]
What is the status here? given that caprover been verified recently? @AhmedHanafy725 @mohamedamer453

**Comment by mohamedamer453** [comment]
> What is the status here? given that caprover been verified recently? @AhmedHanafy725 @mohamedamer453

I was using the old method to add the worker, The new method is working fine but about the docs i'm not sure i don't think there are caprover docs for the grid client scripts but it's the same flow as the one in the playground which is documented [here](https://manual.grid.tf/weblets/weblets_caprover_worker.html).

One thing that might be updated is removing this [line](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_worker.ts#L43) from the worker script since it's not needed in the new flow, but i'm not really sure if it will affect the deployment or not.

**Comment by AhmedHanafy725** [comment]
>I was using the old method to add the worker, The new method is working fine but about the docs i'm not sure i don't think there are caprover docs for the grid client scripts but it's the same flow as the one in the playground which is documented [here](https://manual.grid.tf/weblets/weblets_caprover_worker.html).

it has docs [here](https://manual.grid.tf/javascript/grid3_javascript_caprover.html) but seems it needs to be updated

> One thing that might be updated is removing this [line](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_worker.ts#L43) from the worker script since it's not needed in the new flow, but i'm not really sure if it will affect the deployment or not.

that's true, adding a worker with the token is not used anymore so this line should be removed.

**Comment by mohamedamer453** [comment]
Verified.

The docs were updated with info about each environment variable used and the code examples were also updated. and the worker token was removed from the example [script](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/caprover_worker.ts#L40&L44) and the example in the docs.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d1b1366d-7ee4-4e51-9114-9819c0aff67f)
