### ISSUE TITLE
Discourse get stuck on loading page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1403]
### Description

I tried a few Discourse deployments, and it usually works, but sometimes it gets stuck on this page (I kept waiting for more than a day and nothing happened).

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/039b2cf6-5bb5-4a85-b628-3c75d41c7fa6)

Deployment details.

```             
[
  {
    "version": 0,
    "contractId": 25668,
    "nodeId": 5,
    "name": "dcztcjs",
    "created": 1699789151,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/forum-docker-v3.1.2.flist",
    "publicIP": null,
    "planetary": "300:9c4a:29ac:6e0b:eccf:c3c1:f392:f76e",
    "interfaces": [
      {
        "network": "nwsoxle",
        "ip": "10.20.4.2"
      }
    ],
    "capacity": {
      "cpu": 1,
      "memory": 2048
    },
    "mounts": [
      {
        "name": "disktzi",
        "mountPoint": "/var/lib/docker",
        "size": 16106127360,
        "state": "ok",
        "message": ""
      }
    ],
    "env": {
      "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvmSYj5BKWkizdNyIziMfMm0CRrgq0UxFtBfBdArUMXSFkU30rtExbg6dlVFJCufw6UsCESm/QBSwlOyYKRdpsfVARcAw5G5OG0iX/22n+tYmCcWpmOJLJZaAmSynF1kwpBx3XDy40mFL6OMXjqFcU3DirbcucIL185XfAsTzrq3tDtSvmYPwbXMVMbs1ZAZValxOQNuaLty4qGD2awxVNZq4vtAzgpz3FFo3cs2g70jsGiPq/rsH+NxZHYmqvYnF/S0aPGBrbOe2yW8Cz0mqq5CzqbjYd+Qorkmt7uyJrlCBI43ky+pUuiAYeE1eJlWl5svA+ibWk5yYoa6svLUkaL1kcOMeZWLzDjL3OCrno9gglNp8zUkdSagHROoYlGgpc5fnzMGX4MKDLpHdE9xdk4NjpjB2Iq3hV3DamexXAhLEirLYv9fSilSyKVf/2kvYAa9o+NS4DgBVvXg9J54By/mAVsydD4lbpNe/2pX/WoFGCczmoQfWdHgJPYVCf2vU= harby@ahmed-Saleh-Harby",
      "DISCOURSE_HOSTNAME": "dc579dcztcjs.gent01.test.grid.tf",
      "DISCOURSE_DEVELOPER_EMAILS": "asdf@adf.ads",
      "DISCOURSE_SMTP_ADDRESS": "smtp.gmail.com",
      "DISCOURSE_SMTP_PORT": "587",
      "DISCOURSE_SMTP_ENABLE_START_TLS": "false",
      "DISCOURSE_SMTP_USER_NAME": "asd@asdf.gfd",
      "DISCOURSE_SMTP_PASSWORD": "r%b7FgjdA$1F",
      "THREEBOT_PRIVATE_KEY": "Nx6SdiITzLTOZIvVsHGS/1RLlmF//dSCBaofe7OPpG8=",
      "FLASK_SECRET_KEY": "T8vCyOYZ"
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "{\"type\":\"vm\",\"name\":\"dcztcjs\",\"projectName\":\"discourse/dcztcjs\"}",
    "description": "",
    "rootfs_size": 524288000,
    "corex": false,
    "gpu": [],
    "deploymentName": "dcztcjs",
    "projectName": "discourse/dcztcjs",
    "billing": "No Data Available",
    "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = caBnIOkQeGb9XktnOQS/8gdfVwQfpUwQCBuN5c1bBZs=\n\n[Peer]\nPublicKey = QYq1FCJMQc52X9jysVFjR6Z94725QDWvHaBIegLuJFc=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.206.122.131:5597"
  }
]```

**Comment by ramezsaeed** [comment]
@sabrinasadik please assign someone to investigate.

**Comment by khaledyoussef24** [comment]
it worked but took to much time 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5550a9fe-4c3c-4261-a490-f917e87008db)
and then no verification mail was sent to the admin mail
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/27b0652f-bcb8-481f-84c7-44a152f091a5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e2a5e81e-a46b-4cf2-8b2f-0385f1268919)

so could not try the solution

**Comment by A-Harby** [comment]
Testnet, 2.2.0-rc6.
I deployed 3 instance and still get the same error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/17b708a9-8e9c-47a4-ab63-32261d2b2378)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1d51f767-dd01-4697-92b8-9eb165b15c8d)

**Comment by A-Harby** [comment]
> so could not try the solution

FInally the fourth one worked with me but I got stuck with the same error as khaled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/70ee5d9c-c832-4bb1-bc91-91014c408b09)

**Comment by khaledyoussef24** [comment]
![Screenshot 2024-02-12 at 9 23 03 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5ff6abd5-9f73-4e90-818b-6e794c2d52fa)
deployed many deployments always end up giving me bad gateway.
Should this be a separate issue?

**Comment by khaledyoussef24** [comment]
update : one of the deployment is reachable but still did not get the activation mail 
![Screenshot 2024-02-12 at 10 25 31 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b224f28b-3f3c-46dd-a0c0-9715fac91971)

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
version : cb47e59
deployed discourse and worked fine
the waiting time is acceptable now.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1e327db0-1086-42f7-8011-2d91928b712a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1292db93-1644-4a62-9b3d-9a7b200a2be6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b1fd18d3-84c4-4dfc-b2b9-36408fbf7f41)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/34accd6a-74f9-4f93-b148-ca218445e897)



https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150344
