### ISSUE TITLE
Remove redirection to dashboard in new playground

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1406]
### Description
- When user chooses `Dedicated` when deploying, this alert shows and directs to Dashbaord.
- It should be directed to dedicated nodes page, there's no dashbaord.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f04789c1-b249-4318-ba64-d5b317eb2c92)

**Comment by AlaaElattar** [comment]
### Work Completed: 
- Updated sentence to redirect to dedicated nodes page.

**Comment by A-Harby** [comment]
Is this removed? or where can I find it?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c25f77f-bfb1-4882-9bc5-e2a70d50fd56)

**Comment by AlaaElattar** [comment]
> Is this removed? or where can I find it? ![image](https://private-user-images.githubusercontent.com/109473873/289858175-7c25f77f-bfb1-4882-9bc5-e2a70d50fd56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODU4NDEsIm5iZiI6MTcwMjM4NTU0MSwicGF0aCI6Ii8xMDk0NzM4NzMvMjg5ODU4MTc1LTdjMjVmNzdmLWJmYjEtNDg4Mi05YmM1LWUyYTcwZDUwZmQ1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxMjUyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDM3MGYxNzkzZmYxY2JiZDE2MTUwOTliNDBkYTZkOTc5NTczM2FiMWZhM2FmNzJmZmRkOGNhZDI2NTEyZmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zDP1xKI9_5AHAuc3a0qWGMvPGOYzIwcyyn2YcNbtGdo)
- It's in the alert under the Node text field `Dedicated Nodes Page`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/38b2b233-887c-4f76-9a35-30d7dca98fc0)

**Comment by A-Harby** [comment]
Verified,
Devnet, df55f97.

When dedicate node toggle is enabled either on automated or manual selection, the alert message is now displayed and link direct you to https://dashboard.dev.grid.tf/#/dashboard/dedicated-nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1a592e0d-7558-46c4-b179-b8236d6b0bd0)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef

![Screenshot from 2024-01-01 12-34-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/99ddf42e-bac3-4ade-b56a-d59838e39d84)
