### ISSUE TITLE
Unable to select a Farm to create a Presearch deployment.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#1411]
The original Farm (244) in question could no longer be tested since the farm was indeed offline, so we were unable to test with the existing node information.

However, after further research with an alternative farm ID 3148; we were able to reproduce the suspected bug symptom.

Data indicated that there were no existing Pre deployments on nodes with this farm 3148, yet - we were unable to select this farm in the playground to create a Presearch deployment. Please see images for reference.

![Farm id_ 3148_1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/f19849be-d083-4f3a-9dce-486ca40ffd18)

![Farm id_ 3148_2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/b31c471f-27f9-4448-b880-f054762afb4c)

Additionally we observed the following when attempting to reproduce:
The list of farms projected under Presearch were much smaller than the list for a generic VM. During Presearch deployment  we were unable to expand the list to narrow down to a desired farm even with using the country filter, farm name, etc.

**Comment by amandacaster** [comment]
Hello Team, any updates on this issue?

**Comment by mohamedamer453** [comment]
> Hello Team, any updates on this issue?

Just started investigating the issue, will keep with issue updated with any further findings.

**Comment by amandacaster** [comment]
> > Hello Team, any updates on this issue?
> 
> Just started investigating the issue, will keep with issue updated with any further findings.

Thank you @mohamedamer453.

**Comment by mohamedamer453** [comment]
Update:

After running the new playground locally with the network set to mainnet, i found that the issue was already resolved there and the mentioned farm appeared normally in the farms, and the list of farms appeared normally.

[Screencast from 20-11-23 14:05:27.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/dc489f37-66c4-46c1-8b2c-1d3a2e2a2f8b)

**Comment by mohamedamer453** [comment]
> Hello Team, any updates on this issue?

The new playground is part of 3.13, so it should be fixed with the 3.13 release.

**Comment by amandacaster** [comment]
> > Hello Team, any updates on this issue?
> 
> The new playground is part of 3.13, so it should be fixed with the 3.13 release.

Thanks for the update, @mohamedamer453. We'll inform the user about the update too.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 13a87cf
- [TC2138 - Deploy Presearch Node](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150347)

The farm listing is working fine, and I was able to list and search by farm name, and both were successful.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2665ca40-068a-4dba-9a1b-7b09b66c8673)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/57bbda17-94ad-45d1-9405-6ba7871dfe9f)

And the same goes for other solutions. Listing, searching, and deploying were done with no errors.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e55ac580-5d3b-46ce-8546-a0e0206e9371)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/56ef6909-e392-4b97-b2a3-ee58737fd9a0)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
