### ISSUE TITLE
Error `maybe it's rented by another user or node is dedicated.` when dedploying any solution

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1412]
### Description

Keep getting that error when deploying any solution.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c0e87379-c6f1-47ab-9383-6b3aed7d2916)

**Comment by AhmedHanafy725** [comment]
require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/483

**Comment by AlaaElattar** [comment]
### Work Completed:
- Condition updated when requesting nodes.

**Comment by A-Harby** [comment]
Verified, 
Devnet, 3fc8787.

The `inDedicatedFarm` endpoint was added, and node searches are specified for shared farms only.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/569f09fe-a18e-440e-ba0d-8bd999878efd)
And deploying is working fine too now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0d149683-da53-4493-8a39-2497d58902b1)
