### ISSUE TITLE
Invisible button for Accept terms & conditions in dashboard generate account

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1413]
### Description

The button used to accept terms and conditions is not in the right place, as a normal human user expect.
it should be check boxes as most of the regular applications.

### Steps to reproduce

1- go to https://dashboard.grid.tf/
2- click generate account
3- will be directed to the terms and condition page
4- you will take some time clicking everywhere and the already checked boxes, until you recognize that the accept button the down at the end of the page.

### Current status

![Screenshot from 2023-11-14 11-45-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/970e8583-8d33-49a7-83cc-6c8cc3fd8f02)

### Expected

![Screenshot from 2023-11-14 12-05-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/dabbff5f-a7a5-4bac-ad4e-279806b488ad)

**Comment by ramezsaeed** [comment]
Blocked on the change behavior of iframe form the terms and conditions.

**Comment by MohamedElmdary** [comment]
We should be able to fetch markdown related to T&C page and show it in `vuetify-dialog` and only enable `accept` action if scroll reaches it's end

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work in progress

The implementation logic will be in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2373, but I'll pause work on it until I fix this more urgent issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2368.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Done

The UI transformation involved parsing the Markdown content and embedding it within a `v-dialog`. This change not only provides a more visually appealing display but also ensures a smoother interaction with the terms and conditions.

A notable addition is the dynamic behavior of the `Accept Terms and Conditions` button. It is now disabled by default and becomes active only when the user scrolls to the end of the dialog.

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Added `Go Back` button to close the dialog

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/cda48921-53d2-4928-9275-88f1018a6434)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : d2d2622



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/24816a20-f492-4ecf-a349-bc49afb02962)

The buttons are now more clear.
tried their functionality and working fine. ( either going back or accepting the terms)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150401

**Comment by khaledyoussef24** [comment]
tried the button in light mode it is so unclear and confusing.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/603b95db-8b7d-4c16-ad34-73604fff0316)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4ef95b70-d68f-4704-823e-fbf71f2cc80a)

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done:

- Changed the white color of 'Go Back' button to dark in light mode and light in dark mode

**Comment by A-Harby** [comment]
Verified, Devnet d2a2d6b.

color are changed in both mode.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0a0df588-bc82-45c1-962d-fd46957e37ec)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0064edc0-2b30-4f12-97f9-367c153dd975)
