### ISSUE TITLE
can we merge the dedicated nodes view and the explorer view together?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1418]
It seems we can merge the cost and the reserve button, but not sure how drastic that would be 🙈

**Comment by MohamedElmdary** [comment]
After investing we came out with idea to add `actions` col in node_finder table ... this col should show actions based on node is dedicated/not and/or owned by user/not

**Comment by samaradel** [comment]
WIP:
column added, just need to add some behavior

**Comment by samaradel** [comment]
WIP:
actions ui applied, working on reserving and logged methods

**Comment by samaradel** [comment]
### Work Completed
- Reserve button for rentable nodes
- Unreserve button for nodes owned by the admin
- Reserved button for nodes rented by other users
-  ```-``` mark in actions for shared and down nodes

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85

tried to reserve and unreserve from the node finder and works fine
a new action column has been added now



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2b8e7904-537f-4433-a8e9-f54890e5b45c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bc6496ad-79d0-47ac-b33f-13330dc389f6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b6056f06-e646-4d6d-8699-6cfe09c6c2f1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d9efd20f-256d-4408-9959-cd62434afa7f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5058e4a2-6cc4-49e6-8fb6-639208a1f3a3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8c310bd5-7ed9-4065-b177-7171153c3e75)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4246386
