### ISSUE TITLE
Weird behavior in second Nav bar in solutions 

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1419]
### Description

1 - It looked like that, as it's placed inside a container 

![photo_2023-11-15_12-55-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/0ea92200-cb4c-4d9a-be32-1163d05c6f2f)

2- If pages loaded when screen is minimized then maximized will look like this 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/c3bee7e0-b47e-4d1b-8f91-5b208aaf3da7)

**Comment by A-Harby** [comment]
Verified,
Devnet, df55f97.

When page is minimized and reloaded, then maximized again, navbar is back to working normally.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5b6739df-bcd8-4671-ae72-3f7148bfbdaa)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 14-36-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/2b6b4461-b9be-4bc8-80b4-b4fb3e0823ce)
