### ISSUE TITLE
Propagate retries parameter to the client

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1424]
- retries is never passed to the client.send 
- should be retries instead of retires (typo)

![Screenshot from 2023-11-16 11-19-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/9840ae74-229a-42bd-9deb-50b844e983b3)

**Comment by khaledyoussef24** [comment]
verified statically  typo is now fixed


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9ec7bd7e-7503-4b13-a6d8-31c89757d0ce)
