### ISSUE TITLE
Use grid store instead of initializing grid in each page

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1427]
Refactor the playground to use grid store instead of creating multiple instances for the grid.

**Comment by zaelgohary** [comment]
While I was refactoring, I found that each solution provides its project name while adding/deleting the machine. This is not implemented in the current store. Should the project name be provided dynamically while creating any deployment? I'm not sure if this is possible as we set the grid value only when the user logs in. What do you think? @MohamedElmdary

**Comment by MohamedElmdary** [comment]
@zaelgohary no we should use updateGrid(store.client, { projectName: "whatever" } )

**Comment by zaelgohary** [comment]
Work completed:

Replaced all new grid instances with grid store.
