### ISSUE TITLE
QA: for data migration testing execute the following

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1430]
- use an older version of the grid-client-ts e.g 2.0.0 or 2.1.0 to deploy all kinds of solutions (using scripts) 
- use the playground.dev.grid.tf to see if things are properly migrated or not

**Comment by khaledyoussef24** [comment]
data migrated with success 
tried to deploy using version 2.0.0
solutions tried : "single vm , k8s"
single vm:
![Screenshot from 2023-11-20 08-36-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bf2416f9-e0eb-4720-afeb-269fe6148cc5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/71f896e9-138a-4d23-ade4-f6a9a4a6a570)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cce88c53-91cb-41a5-a6f9-dee33ecb1690)


k8s : 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/09ddb04d-b9b9-40aa-b410-f19592708f45)

**Comment by A-Harby** [comment]
I tried using [V2.0.0](https://github.com/threefoldtech/tfgrid-sdk-ts/releases/tag/v2.0.0), but it was giving me an error with the balance.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0ea2cb24-bd14-4422-80cc-2808b4a0e99a)

So instead, I used [V2.1.0](https://github.com/threefoldtech/tfgrid-sdk-ts/releases/tag/v2.1.0) to deploy.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/86c28666-4189-4a57-9029-8b2c01105c68)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/daf401a8-f3a4-4010-aa2e-c9b0869252d4)
It was listing the deployment on the contract list on playground.dev.grid.tf.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1de76406-5d0e-4670-b051-737dac462f39)
But they were listed on the solution deployment list.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e50447a8-f00a-4af8-b060-3b1983d0983a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fa3732a9-0700-4ef4-bf7a-81db77e5d9b7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/49295d9e-6318-4f52-b5ee-8e81d175db7c)

**Comment by ramezsaeed** [comment]
Ahmed Hanafy, [11/20/23 3:08 PM]
for listing, the default backend storage for the client is the filesystem

Ahmed Hanafy, [11/20/23 3:08 PM]
and for playground, we use kvstore on the chain

Ahmed Hanafy, [11/20/23 3:08 PM]
so I prefer to deploy with playground from this version v2.1.3

v2.1.3 is the current mainnet version which is the least version on the grid.

**Comment by A-Harby** [comment]
> Ahmed Hanafy, [11/20/23 3:08 PM] so I prefer to deploy with playground from this version, v2.1.3

I used playground v2.1.3 and deployed a VM and Kubernetes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c835f05f-672c-4115-ba6b-bee4889857f5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4e8d8fd5-8c57-4aea-93e6-ce88abb2b9d6)
And listing them in the deployment list in playground.dev.grid.tf.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/94b2c560-715c-49f7-a2f0-f971ed587dff)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d8b47ebc-4bf2-40c7-974c-b9f9149e75eb)

**Comment by A-Harby** [comment]
I also tried Mattermost and it also listed:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/caf71717-7f34-4dca-9a9d-8c24ef943190)

But as said above, deploying from the client doesn't appear in the deployment.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/14282c4b-c47d-4f49-82ac-f6662ddbc33e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/064722ba-b989-4d2e-8e0f-f92d75e0aef3)

**Comment by A-Harby** [comment]
Using playground version [2.1.3](https://github.com/threefoldtech/tfgrid-sdk-ts/releases/tag/v2.1.3).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0fe4196e-b4ca-4fc3-8d2e-07c6812c8f11)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4e51dc07-39ef-4957-943b-8007fd203ae0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f21b47a7-db55-4b91-a7a7-af8bfba77225)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f2813b3-0241-43eb-992b-5213837bb0ed)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6b64d8ff-f738-43c2-94d5-d45fe4d2ea17)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9b46e768-7079-492a-a211-0f50dcd328cc)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/774a96d3-4ad2-4241-b230-3ae0db923e73)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a9424307-bb25-4185-8b40-605dd38341fd)


And from playground: https://playground.dev.grid.tf/
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b22b12bb-9c21-4a10-87c5-65acde3355fa)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da1a57b6-812b-46bc-82e5-16c8538e3a53)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6d2664c7-1e7c-4e9a-8194-4fb94d3e6aee)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d75e6150-4d12-49c7-9cd2-7681d2049c9f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0b8f18d8-e413-41a1-b01d-8afea375d5f0)

And I tried listing the same as above for the rest of the solution, and they all migrated and listed with no issue.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d8ac2175-63be-4d6e-b74e-a4f77120fa4a)
