### ISSUE TITLE
QA: for data migration (3.12 to 3.13) testing execute the following

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1434]
- use an older version of the grid-client-ts e.g 2.0.0 or 2.1.0 to deploy all kinds of solutions (using scripts) 
- use the new.playground.dev.grid.tf to see if things are properly migrated or not

related to:
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/8

**Comment by khaledyoussef24** [comment]
data migrated with success 
tried to deploy using version 2.0.0
solutions tried : "single vm , k8s"
single vm:
![Screenshot from 2023-11-20 08-36-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bf2416f9-e0eb-4720-afeb-269fe6148cc5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/71f896e9-138a-4d23-ade4-f6a9a4a6a570)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cce88c53-91cb-41a5-a6f9-dee33ecb1690)


k8s : 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/09ddb04d-b9b9-40aa-b410-f19592708f45)

**Comment by ramezsaeed** [comment]
still no progress
waiting for 3.13 to be deployed on qa net

**Comment by xmonader** [comment]
Are the scenarios done for this one?

**Comment by A-Harby** [comment]
> Are the scenarios done for this one?

Yes, the test cases have been added within the [Grid Upgrade](https://app.testlodge.com/a/26076/projects/40893/suites/217765) test suite to be run before the release.
And after the upgrid, beside verifying the deployments themselves, the migration data will also be verified in [TC2074 - Verify Data Migration VMs and solutions](https://app.testlodge.com/a/26076/projects/40893/suites/217765?expand_section=370871#case_4126959) and [TC2083 - Verify Data Migration Kubernetes and Caprover](https://app.testlodge.com/a/26076/projects/40893/suites/217765?expand_section=370871#case_4129946).
