### ISSUE TITLE
Update ssh keys button is hidden behind the pop-up notification

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1436]
### Description

pop-up information about ssh covers the buttons "update ssh keys"

### Steps to reproduce

- open https://new.playground.dev.grid.tf/#/portal/twin
- login
- try to paste new sh keys to update the field
- it will be hard to click the update button because its hidden behind the pop-up notification box

### Logs/Alerts

![Screenshot from 2023-11-19 17-17-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5e10e33c-828e-444a-9323-8e803df03eb7)

**Comment by AlaaElattar** [comment]
- added in verification as the ssh field doesn't exist in the profile manager anymore.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85
ssh has it own page now 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/203343bb-8fb0-4ab5-b9de-e355c9341056)
