### ISSUE TITLE
Unable to run the playground locally after changing the network

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1441]
### Description

After following the steps in https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/docs/build.md to run the playground locally on a different network a `TIMEOUT` parameter appears without a `,` before it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e738e0a4-6d4c-453b-bd0c-3036e998d83d)

and it can also be seen in `playground/public/config.js` at the end of the string

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2c6f73a1-fd33-4005-a394-0bbe9407f0c5)

and this prevents the playground from running with the following error.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6a2da317-460d-4769-864b-8d717696663d)

### Steps to reproduce

- Follow the steps in https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/docs/build.md 
- Run the playground locally and check the console for errors

**Comment by A-Harby** [comment]
Verified,
Devnet, development branch [68f8aa4](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/68f8aa4a43d0c93ec26841702ed85fd48891ea84).

[TC2435 - Run locally on different networks](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422337#case_4162534)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/53ce28bc-bb8e-4989-b0d4-018e115d836d)
