### ISSUE TITLE
Revamp Sidebar

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1445]
Some enhancements should be done in the sidebar.

- Rename portal to My (to be changed if a better naming is  found)
- Remove contracts inside My group
- Remove explorer group and spread its children in the sidebar
- Group monitoring, 0-hub, 0-bootstrap & grid services & manual in TF services

**Comment by amiraabouhadid** [comment]
Work Completed:
Asked for a better name for Portal

WIP:
Removing contracts from Portal

**Comment by amiraabouhadid** [comment]
Work Completed:
Changed Portal to Dashboard.
Moved Contracts to Dashboard
Moved 0-hub, 0-bootstrap, grid services & manual to Services
Removed Explorer and placed Stats, Nodes and Farms separately.

**Comment by ramezsaeed** [comment]
### Verified on:
    - Env.: DevNet
    - Version: 3dc6be3

- [ ] Remove contracts inside My group
- [ ] Remove explorer group and spread its children in the sidebar
- [ ] Group monitoring, 0-hub, 0-bootstrap & grid services & manual in TF services
- [ ] Changed Portal to Dashboard.
- [ ] Moved Contracts to Dashboard
- [ ] Moved 0-hub, 0-bootstrap, grid services & manual to Services
- [ ] Removed Explorer and placed Stats, Nodes and Farms separately.
