### ISSUE TITLE
Add support for searching for nodes by regions

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1449]
parent: https://github.com/threefoldtech/home/issues/1466

this should be before the country field and if a region is selected, the countries and farms should be with this region.

**Comment by MohamedElmdary** [comment]
Block on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1457

**Comment by Mik-TF** [comment]
Based on the new merged PRs and the playground dev, I think this can be closed. Everything is there on the Playground.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/e706b0d4-b682-4297-9bf1-d9c7369f3bf1)

**Comment by A-Harby** [comment]
Verified,
Devnet, 2.3.0-alpha3.

[TC2444 - Filter Nodes by Region](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4164673)

The request that is sent to filter the nodes is added with a region endpoint and a specific query from the list.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8ff21c52-f167-47b7-9134-5fcece90ed9b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
