### ISSUE TITLE
Grid tests workflow is failing after last update

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1451]
### Description

From the grid test [result](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/grid_client_tests.yml) you can see that all the test runs are failing with the same error: `Couldn't create TFClient without store secret` 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/084837a6-0473-484c-8938-2eaed5e68c81)

The error is usually caused when the mnemonics are not provided.

**Comment by ramezsaeed** [comment]
we need to know the updates when run this manually.
do we have same results or not ?
@A-Harby

**Comment by A-Harby** [comment]
> we need to know the updates when run this manually. do we have same results or not ? @A-Harby

Yes, when we run it manually or when we trigger it from the workflow, it works with no issue, and the tests are passing.
But the issue appears when the schedule runs it.

**Comment by A-Harby** [comment]
Verified,

The test workflow is now running fine, and the tests are working with no errors. https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/grid_client_tests.yml
