### ISSUE TITLE
Add All Regions, All Countries, All Farms in node filters

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1453]
parent: https://github.com/threefoldtech/home/issues/1466

See this reply for more information: https://github.com/threefoldtech/home/issues/1466#issuecomment-1817914864

This issue can be done once [Regions are added](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1449).

This option is almost there for Countries. In the current playground, if you do not select a country, you can see the farms and the nodes from all countries.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/c275bf06-77bb-40b9-81eb-a899ccbab480)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/b8158940-095e-4908-be0f-95440b55ce4f)

Once you choose a country, you need to "delete" the country name to access all countries and farms again.

In brief, we want to make this option obvious. By default all regions, countries and farms would be the default choice. Users can then narrow their search or deploy right away, for a quick UX.

**Comment by A-Harby** [comment]
Verified,
Devnet, df55f97.

Now there's two new options in both lists: all regions and all countries.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b8054d91-da1f-4ecb-99a3-353bf4331e8e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/567438c8-cee6-4bec-b5ed-55be9708501b)

**Comment by Mik-TF** [comment]
Amazing work to all those involved.. It looks amazing. Thanks. Closing this issue since it's on devnet, and verified.
