### ISSUE TITLE
Playground: Use error classes in error handling for better UX

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1462]
- #995
-> blocker: #1443

**Comment by 0oM4R** [comment]
Work in progress:
- replaced checking on error message literal in some places,
Not sure if we should use error classes somewhere else

**Comment by 0oM4R** [comment]
Work in progress:
prepend the error name to error message to  make it clear

**Comment by khaledyoussef24** [comment]
is there any suggested way on how to verify this ?

**Comment by AhmedHanafy725** [comment]
@khaledyoussef24 no need to verify it
