### ISSUE TITLE
Debug/Logs tab

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1468]
Currently, logs are only visible in the developer console, making it difficult to effectively debug issues or create comprehensive bug reports.

Suggestion is having a logs/debug tab to show all of these logs with the option to download it as tfgrid-dashboard-$timestamp.logs and also Clear button to clear all logs.

**Comment by AlaaElattar** [comment]
for example, this in view will get all errors when smth happen.
```ts
// Global error handler
app.config.errorHandler = (err, instance, info) => {

  // Handle the error globally
  console.err("Global error:", error);
  console.log("Vue instance:", instance);
  console.log("Error info:", info);

  // Add code for UI notifications, reporting or other error handling logic
};
```

**Comment by 0oM4R** [comment]
# Investigation and Solution:
will create a method that take the logger and override it, for now will store the messages within an array; 
for the uncaught errros this point is still under investigation;

**Comment by MohamedElmdary** [comment]
We will need to use indexed DB to avoid the limitation of localstorage (10 MB)
also avoid rewrite the entire value again everytime

**Comment by 0oM4R** [comment]
###  Work Completed:
  - used logger [interceptor](https://www.npmjs.com/package/logger-interceptor) , 
  - created indexedDB client
  - initialized the logger component ui
### Work in Progress 
read the data from indexedDb and show them in order

**Comment by MohamedElmdary** [comment]
- [x] Add scroll
- [ ] Load More Logs when scroll top = 0
- [ ] Support save all logs (as .log file in nicely formated structure)
- [ ] Support clear all logs (show dialog before clear to verify use didn't click my mistake)
- [x] Fix position of logs to be bottom - right
- [ ] serialize how messages should be shown in logs (object and arrays should be nicely formated - as much as possible- )
- [x] add virtual scroll 3rd party solution to make sure logs is fine

**Comment by 0oM4R** [comment]
### Work completed :
- enhanced UI 
- add virtual scroller to render logs item
- add delete logs data base 
- add load more logs

![Screenshot from 2024-01-28 19-01-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b54c9210-a53c-4740-8259-10cdb6670b9a)

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.

The Logs tab has been added at the bottom of the screen; it lists all the dashboard logs, has a copy, show more, load more, download, and clear the logs option.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a825e2cc-5c61-4a8b-a0fe-eb71e0c825f0)

[TC2621 - Debug Logs Tab](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4216871)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 48a660d

![Screenshot from 2024-02-27 12-59-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/beaae18f-136a-4998-8b69-c58a7a241b97)
