### ISSUE TITLE
Dashboard monitoring

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1470]
### research 

- how to collect errors / warnings ?
- how to send them to operations? should be integrated with what we have e.g promethus, grafana
- what data should we collect?
- what needs user's consent?
- should be opt-out by default

related #1469

**Comment by AhmedHanafy725** [comment]
we are using Sentry now I believe it covers all the mentioned points

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3101#issuecomment-2340487763

Also snyk is added.
![image](https://github.com/user-attachments/assets/312ebec1-2972-4d14-9028-8643d5d3ed18)
