### ISSUE TITLE
Farm details keeps loading

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1472]
Whenever you click on any farm in explorer/farms, it keeps loading infinently.

[screen-capture.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f03c1f0c-dcbb-4594-80ab-6a2281fc676a)

**Comment by A-Harby** [comment]
Verified, 
Devnet, 2d54818.
Twin details is not loading forever anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7417634f-a230-45bf-ab72-785379698206)

[TC2270 - Show Farm Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150479)

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
