### ISSUE TITLE
After successful login I see a dialog with "Connect Your Wallet" title

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1473]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b21b9d70-2bd3-4f9f-83e9-06110f506187)

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 2d54818
Title updated to `TFChain Wallet`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0da55eaf-e7d6-46b2-ae7e-85ffc4cb28a7)
