### ISSUE TITLE
Nodes filters layout

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1474]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/fdc92ccb-b4b0-4ab0-abaa-66a46c232489)

It doesn't seem aligned, maybe also we allow an option to apply filters?

**Comment by mohamedamer453** [comment]
It's currently aligned and there's a button to apply filters.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/779f624d-2b40-4d1e-9607-cec5b3594f9f)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85 
![Screenshot 2024-03-24 at 8 05 45 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b479fd3-9495-496e-880b-a9c75c687b87)
![Screenshot 2024-03-24 at 8 05 48 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6dbac7bd-0e81-42dc-9ea3-e676e29681ca)
![Screenshot 2024-03-24 at 8 05 51 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1e5ccca9-1921-4dc2-a152-f3e4f495b39c)
![Screenshot 2024-03-24 at 8 06 01 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4119302b-8c31-4082-aa25-da2b219cad6c)
![Screenshot 2024-03-24 at 8 06 12 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9362b4f1-9d8c-4809-b4f2-61fc6aa795d5)
verified the node filter is now aligned and responsive and the apply button is now added

**Comment by ramezsaeed** [comment]
I think the On/Off buttons should be on the same line;
like this i can see its still not aligned.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 
filters layout totally changed and aligned correctly



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ceb8988a-263c-40b0-b9f5-331e7e13e7ee)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/08233f9f-c7ab-4991-9b6a-211ec4189c3f)
