### ISSUE TITLE
Use title case for Statistics page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1475]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3e71fe58-9838-45d8-85c3-b5e7ae116169)

the heading is in lowercase

**Comment by A-Harby** [comment]
Verified,
Devnet, 2d54818.
The titles are in lower case.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e93787b0-7e7e-4c92-83ca-83b26f5cfa57)

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5dca701f-10d8-4b12-a847-01de1320b48b)
