### ISSUE TITLE
statistics cards layout

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1476]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/edb17af3-8185-4a95-915d-e0d38ddbcae2)

they're not evenly distributed, maybe we can make them take the space dynamically somehow?

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
- 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4afe2a9f-6d87-4758-bcda-9e5f6ff1c154)
