### ISSUE TITLE
Twin Details:  Add a hint on the relay item

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1479]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/4ed44f6a-7bef-494b-97e2-90364fb5baea)

**Comment by xmonader** [comment]
Please use this documentation link https://manual.grid.tf/internals/rmb/rmb_intro.html?highlight=RMB#introduction-to-reliable-message-bus-rmb

**Comment by mohamedamer453** [comment]
Update:

Work Done:

- Added a hint message for the relay item.
- Added a hint message for both the id and address items.

**Comment by A-Harby** [comment]
Verified,
Devnet, 911c562.

The hint messages have been added to the twin details.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/246cf7c9-e83c-4573-a9c3-970cbe3f87d7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0f02766b-2784-4c47-9684-2526b32e45b6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0cbab5aa-89dc-4e6e-b150-ad495d6f004b)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- 13a87cf
