### ISSUE TITLE
Deposit TFT: change layout

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1482]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/2618f55b-e40e-4818-8b28-2fb373bba844)

Change destination and memo text to edit fields that I can copy from easily (with clipboard button)

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

Destination and Memo text input changed to clipboard button
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6268114c-139b-411b-b1ab-1c3031957558)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3

![Screenshot from 2023-12-24 13-48-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/bae49b27-7bb9-47db-b3ac-13715a215361)
