### ISSUE TITLE
Withdraw TFT

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1483]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/a9f58e29-2c8f-4549-b758-7f99db661790)

same comment on the title not sure why it is on that far right, Add a tooltip button or a hint why it can't be lower than 2TFT

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 12-46-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/3ee19810-ae96-43bb-910b-1ad39c67cbdf)
