### ISSUE TITLE
Bridge: only has stellar chain?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1484]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/8bc21d8d-58f8-4ee2-bd68-43f0bf00824a)

There's no point of showing a combobox if it's only stellar?

maybe we should convert to tabs? or something else?

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c12e06c-b0e8-47f7-a8f7-2829c57e1137)
