### ISSUE TITLE
Portal/Transfer: Update the field hints

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1486]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/acaf84d5-be33-47f2-9b64-d5985ca330c2)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/2452f4b4-5eed-467d-83d8-c7d6f0da0158)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0cc9f487-4e34-4a4b-883e-d7e157e86ceb)

**Comment by A-Harby** [comment]
Verified, 
Devnet 911c562.

Field hints improved.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7368263e-1875-4bdd-82cf-1badfda1ddcd)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/442d2c56-82e3-499c-b919-3dfca71c51e4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/82a821ab-ed0f-4f3f-8c15-b9f7b07e5ef2)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 13a87cf
