### ISSUE TITLE
my farms page layout feels weird

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1487]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d70c9a40-e105-465e-978e-b674dbfcdb83)

or maybe it's just the position of the Create Farm button, and its blue color.

**Comment by zaelgohary** [comment]
@ehab-hassan Can you take a look at this?

**Comment by amiraabouhadid** [comment]
Made IP table header same as node details header: a gray banner

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/794f3ae4-37d2-4b98-b9bb-43da8bb6f09b)

enhancing farm page
change the "Create Farm" button color (this is the best position for the user)
change the subtitles background for the details part because it was a lot of green titles making the user confused 
still have an issue with hovering at the details part need to remove it when opening the details(need help here)

**Comment by ehab-hassan** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/7f2713c7-eae5-495a-81e9-21fa64173ffa

- Added buttons at the center and make Create Farm the primary color
- Made all details with a gray background color to avoid confusion.
- Changed background color for details to separate from other farms at the table so the user can understand that part related to the node opened.
- Made action icons bigger and more space between them, and the tooltip does not overweight the additional fees icon.

![explainer](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/0c8f7781-45f9-417e-9d5d-332e31d14059)

**Comment by ehab-hassan** [comment]
@AlaaElattar can u please help me in that 
- As @xmonader mentioned in #1488 change dedicated to (No) instate of false.
- make sure Add IP button works fine after I move it down with other button.

**Comment by AlaaElattar** [comment]
- All handled except for changing the `Add IP` button location, which will be handled here #1662 .

**Comment by khaledyoussef24** [comment]
verified my farms layout now changed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a46e6a5-9e6a-4dfe-98ad-a38c0d1330f8)

buttons positions is more comfortable now
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b15788f6-55fd-4a09-b657-e698be061403)
details back ground color also changed and titles in grey boxes
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d5bb349a-1d0e-4aac-8bf0-f4b6348eedb5)
![Screenshot from 2024-01-01 15-03-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d433985b-d898-48ac-a000-10e7c50485f9)
![Screenshot from 2024-01-01 15-03-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a4bde03-2511-46e8-9e98-cce439e730cd)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
