### ISSUE TITLE
farm details isn't usable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1488]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c32f0342-138b-4a27-8ff3-31cdbdb2acd0)

1- the down arrow next to `NotCertified` gives the feeling it's a selectbox
2- the farm details that gets expanded is too wide that it's basically not usable
	- address should be copyable
	- false -> should be shown as `No`
	- add IP is blue
	- other actions are on the row below 
	- the stellar address for instance can be editable on the details directly
	- move the Bootstrap zos node image outside of this view completely, maybe can be next to create farm or so

**Comment by Mahmoud-Emad** [comment]
I will transition it to a 'blocked' status until your update is complete.

**Comment by AlaaElattar** [comment]
> ![image](https://private-user-images.githubusercontent.com/64129/285680496-c32f0342-138b-4a27-8ff3-31cdbdb2acd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDM5NDYsIm5iZiI6MTcwMTk0MzY0NiwicGF0aCI6Ii82NDEyOS8yODU2ODA0OTYtYzMyZjAzNDItMTM4Yi00YTI3LThmZjMtMzFjZGJkYjJhY2QwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEwMDcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZWQ4NDE2NzY0ZTdjMjdkMmJlNDBkOGFjMWU3MWNlMGY3ZmMzMWQ5YmE5NmFmNzk1YWNjZWEzYTdlYTVjMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IwFK6GqHiGmvexRL1N_NwUaFr4gjSDLeoxvfXXLSFWY)
> 
> 1- the down arrow next to `NotCertified` gives the feeling it's a selectbox 2- the farm details that gets expanded is too wide that it's basically not usable - address should be copyable - false -> should be shown as `No` - add IP is blue - other actions are on the row below - the stellar address for instance can be editable on the details directly - move the Bootstrap zos node image outside of this view completely, maybe can be next to create farm or so

- About first comment, it's smth in the table itself and it's done same way in dedicated nodes page.
- For second comment, I can decrease it but i think it won't be consistent with explorer farms page. what do u think ??

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3


![Screenshot from 2024-01-01 16-08-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/aa737ec5-e387-46cd-a15e-0e79d6246c0a)
