### ISSUE TITLE
Dedicated Nodes: doesn't expand on row click

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1489]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/9d59e953-6075-48f7-9ce8-3b7f6a6efdb7)

Unlike farms which does.

**Comment by khaledyoussef24** [comment]
Fixed and verified on devnet
version : f1e3728


node details expand click on anyplace on the row.
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ccb29080-6606-465e-8b1f-c00349b38d9a
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6c2ece02-4c86-40a7-ba4e-0f836c47ec44)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430127#case_4150429
