### ISSUE TITLE
DAO: more details

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1490]
I liked what we did in the #1485 button, maybe we do something similar or whatever you guys believe is best.

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 12-17-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7af713fa-d23e-4c47-997b-104952f4236a)

**Comment by mohamedamer453** [comment]
The more details part was removed from the card and was added in the form of a button that leads to the more details route.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ec31fc60-c390-4321-ab5c-8da5c24d4235)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

the more details is removed and a button for the details was added and changed in UI.
opening another issue for devnet redirecting leads to a non existing page.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d1d91498-2cb6-49d4-9154-cec95d3df19c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31b142f2-6db8-4a56-ac46-d9b7e15ac090)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dd9b402e-ccd7-45dd-a908-a37e5c855458)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4250546
