### ISSUE TITLE
change DAO's intro message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1491]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3ffd1a5b-f3be-45f5-aab0-063afeeb1ca8)

It feels off `User, ...`

**Comment by ramezsaeed** [comment]
remove the user word from this message

**Comment by mohamedamer453** [comment]
The message is now updated and the `user` part was removed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/25642f8b-feef-4cf9-81cc-f703855ce371)

and the info icon leads to more details about DAO proposals and voting.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/91e7c0c8-c0f8-4f85-8db4-d0324820aa46)

**Comment by A-Harby** [comment]
Verified, Devnet bd6c7c5.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/918a73dd-9a56-4f97-b41c-ee0e3b6df387)

**Comment by ramezsaeed** [comment]
Verifed:
- Devnet
- d2d2622
