### ISSUE TITLE
DAO markdown info isn't properly formatted

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1492]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/4fb842b8-be26-42d3-950d-4b029779d7c7)

see the last item `- sum..`

**Comment by ramezsaeed** [comment]
this message is not cler at all:
"Sum of all nodes of the farmer: (node CU * 2 + node SU)"

**Comment by A-Harby** [comment]
Verified, 
Devnet, 2d54818.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/57ee1e71-6deb-4b47-8698-81f2eca2c512)

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
