### ISSUE TITLE
failing to load node details while being online on the nodes list

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1493]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/fa69e4f7-6c97-4ac3-aff5-6d3e2f64789d)

- need to rephrase the message: `Failed to load node with ID 28. The node might be offline or unresponsive. You can try requesting it again.`
- add the more details that the node isn't reachable over the RMB or GridProxy

**Comment by khaledyoussef24** [comment]
the issue is no longer reproducible.

Should I leave it until I find a way to check if the error handling message has changed?

**Comment by ramezsaeed** [comment]
using the farmerbot try to down a node after deploy on it, and then test the message.

**Comment by khaledyoussef24** [comment]
Will try it using the nodes we had for testing main net

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.

The tab UI was fixed, and the message were changed.
And a try again button to retry when failing is working.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc386871-9e7c-4e5d-9722-968a8b5d6107)

[TC2251 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460)
