### ISSUE TITLE
expand filters by default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1494]
I think they should be expanded by default

**Comment by ramezsaeed** [comment]
![Uploading Screenshot from 2023-11-27 12-00-52.png…]()

**Comment by ramezsaeed** [comment]
![Uploading Screenshot from 2023-11-27 12-01-53.png…]()

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 12-01-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4ae48a40-12f9-4dbe-8863-8cfd220f0b39)

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 12-01-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4ae48a40-12f9-4dbe-8863-8cfd220f0b39)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1580

**Comment by ramezsaeed** [comment]
verified on;
- devnet
- 8c32384
