### ISSUE TITLE
contract list: remove the leading pipe `|` character

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1495]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/019c2c72-21c3-4c1e-98d6-ced7fe3588b0)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : https://github.com/threefoldtech/tfgrid-sdk-ts/commit/ac5cd85b21421c70d5d37ff1207aacbfcb0d3173





![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/044ee1bc-ff31-4b5f-899a-7bba5ef038df)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/229c122a-c0ad-41b8-a4ba-8b0b1f02954e)



the leading pipe line character is now removed

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622
