### ISSUE TITLE
light mode is still unusable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1496]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/29a1bc39-a534-40f5-9e56-0ba0e87d1e45)

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 11-46-51](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/fb90a951-98fd-47b9-b9df-92ac547377a9)
