### ISSUE TITLE
subsquid solution: websocket typo

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1497]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f8b6a259-9c95-4d56-87e8-74f4774b0a09)

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 13a87cf
- [TC2179 - Subsquid Input/Configuration Validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422335#case_4150388)
- [TC2139 - Deploy Subsquid](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150348)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ca546d8-3560-4c68-ac38-f1519e8d2b61)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 13-27-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/f0c5d44c-8d9f-4320-b00a-47f7145b3b29)
