### ISSUE TITLE
contract list: doesn't show node status, and node Id for gateway contracts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1498]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ab6de362-7b20-4a60-8888-fdd83bc02cf8)

**Comment by ramezsaeed** [comment]
this is because its a name contract,
so we need a diff table for node contracts with all matching field.

**Comment by xmonader** [comment]
let's do two tables or two screens or add a note or show the nodeID/nodeStatus of the gateway node of the contract

**Comment by Mahmoud-Emad** [comment]
### Issue Update

Paused Paused working on this to work on Rabe's pull request https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1457

**Comment by Mahmoud-Emad** [comment]
### Issue Update

- Worked on displaying the export/delete buttons per table
- The export button will only export the contract type `e.g. name contracts`
- The delete button will only delete the selected contract within the table `e.g. name contracts`
- Refactored and enhanced the code by removing unused code and document it

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 13a87cf
- [TC2311 - List Node Contracts](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156491)
- [TC2312 - List Node Contracts Sorting](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156493)
- [TC2313 - List Name Contracts](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156511)
- [TC2314 - List Name Contracts Sorting](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156520)
- [TC2315 - List Rent Contracts](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156522)
- [TC2316 - List Rent Contracts Sorting](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156526)

Now there are three tables for node, name, and rent contracts.
Each with its own export and delete functions and specified columns.
Sorting is working fine, as is getting deployment data.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5e19c17f-8573-4d90-affe-449d6d7bbdd9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c1bc4fa5-f2a9-4183-862c-1a609b844889)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/058daf0d-0d30-432d-882b-d3bada7f4e7e)

I also created six new test cases for listing and sorting.
