### ISSUE TITLE
Total PubIPs -> Public IPs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1499]
change in filters Total PubIPs -> Public IPs

**Comment by AlaaElattar** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/23d2f82f-05da-4cf1-abd5-b129006a1a70)

**Comment by khaledyoussef24** [comment]
verified in devnet
version : ac5cd85

the filter is now written as `Free Public IP's`
![Screenshot 2024-03-24 at 8 46 55 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5eeacf21-c193-488c-80c8-1c030785cb56)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4152354
