### ISSUE TITLE
Gateway and GPU only, node status filters should be in filters section

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1500]
Gateway and GPU only, node status filters should be in filters section

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-27 12-09-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/f4d7d67e-b313-4f33-9e6e-540930ca73be)

**Comment by AlaaElattar** [comment]
- already happened in 3.13

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet
verified gateway and gpu only are added to filters


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31d6d618-764a-471f-bdba-b33ddef1619d)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/41a94975-1f93-41f5-a54d-b7fad8541deb)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/744c1107-b108-4177-bf37-c7fe5fe8984d)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150465
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150466
