### ISSUE TITLE
Add Free Public IPs filter

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1501]
it's the more common option to search on the farm to have free IPs not the total

**Comment by A-Harby** [comment]
Only the last comment will close it; the name is mistyped `PublIPs`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/06b56435-2c81-4920-bd26-bd853d00d1ee)

**Comment by A-Harby** [comment]
Verified, 

Based on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1501#issuecomment-1849724336 and after fixing the name.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/80039945-bc08-43c8-9065-09956f80bd8b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
