### ISSUE TITLE
Format DAO proposals

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1502]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1c956fbd-c300-4328-a3d8-134e94dd794b)

**Comment by A-Harby** [comment]
Next to the Yes option, the `No` option appears to be disabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ba496fb1-fbcc-4f76-a5b9-f5c3b27241c9)

**Comment by maayarosama** [comment]
> Next to the Yes option, the `No` option appears to be disabled.

The No button disabled, Although it has a gray color which may lead the user to think it's disabled. we can change the color to red, what do you think @ehab-hassan? 
![Peek 2023-12-24 14-18](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/62b2ac57-6c16-4e7b-a949-a4bd9cd744db)

**Comment by zaelgohary** [comment]
@maayarosama There's a [PR](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1767) where all buttons are changed. I think this one is also covered.

**Comment by A-Harby** [comment]
The only comment that searches is case-sensitive and it shouldn't be.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b584bf7d-4c0c-4681-bd6f-be0caa628f62)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e84f0b91-5fe9-4d30-b1de-4e75535525f9)

**Comment by amiraabouhadid** [comment]
Added case insensitive search

**Comment by A-Harby** [comment]
Verified,
Devnet 33c308d.

[TC2232 - Verify Proposals Search Functionality](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150441)

The search has been updated to be case-insensitive.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/32994883-5fb7-4595-be1f-51a33e8f00ee)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26ae4656-0b37-4d27-b9f6-bea7c8a86e96)
