### ISSUE TITLE
different colors for the action button and the details section

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1503]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ff1775c9-36f0-4fe2-ad1d-6a28ac1be795)

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/da19e06d-4569-46ec-aec9-19c98a995016)
Fixed at development__313_farm_enhancement branch ll create PR soon

**Comment by A-Harby** [comment]
Verified,
Devnet, f4978d7.

The style is now different between buttons and table headers.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6576ba48-2996-4965-85c6-08b78a3bf6f7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5344153e-0fe9-4c8f-9ce2-3496f7590ca8)

[TC2222 - Reserve a dedicated node](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150431)
[TC2223 - Unreserve a dedicated node](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150432)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 13-27-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/09eac5b9-b15e-4ad9-9af3-f7bf68a21fa8)
