### ISSUE TITLE
portal / farms: shows nodes if i don't have any farms

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1504]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/15c92f01-ade3-4467-87ef-c5e3afb33d33)

**Comment by A-Harby** [comment]
When the account doesn't have any nodes, it doesn't show any.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2cee2d31-6f3b-4393-8248-d6d49d491e99)

But I noticed that the network request that is being called is for the rented node, not the nodes of the twin.
https://gridproxy.dev.grid.tf/nodes?ret_count=true&page=1&size=10&rented_by=5523
So I did rent a dedicated node and went back; it did show up as my node.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d7640a92-f815-43c7-972f-b62572e304d6)

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02.

No nodes is shown and the request being called is correct
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1b98cd60-538d-427c-8782-a6f6bbff9114)

[TC2212 - List Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150421)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
