### ISSUE TITLE
Trying to setStatus for farmInput after it gets destroyed

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#1506]
### bug

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/cbbc8559-de81-4a4b-a960-b527c527698d

### Description
trying to setStatus for farmInput after it gets destroied

### Steps to reproduce
- Go  to any solution
- in select node
  - go to manual then back to auto then to manual

### Logs/Alerts
```
TypeError: Cannot read properties of null (reading 'setStatus')
    at loadFarms (select_farm.vue:180:21)
    at async resetPages (select_farm.vue:209:3)
```

**Comment by maayarosama** [comment]
fixed here https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1207

**Comment by A-Harby** [comment]
Verified,
Devnet, d88700a
I tried a few times with different solutions, and it wasn't reproducible.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e94fcbdd-150a-41ae-9d2b-e08ed50ff35e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
