### ISSUE TITLE
enhance getting user farms and user nodes

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1508]
we are getting user farms in  `UserFarms` component;

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/20430ac045834def9400139218d57aa33817aaa4/packages/playground/src/components/dashboard/portal/user_farms.vue#L207-L213

Also, we are doing the same in `UserNodes` before getting user nodes:

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/20430ac045834def9400139218d57aa33817aaa4/packages/playground/src/components/dashboard/portal/user_nodes.vue#L216-L227

we are using both component in the same view, so i suggest binding user farm ids to user nodes component to reduce the time and number of requests 

-  #1504 
- #1507

**Comment by A-Harby** [comment]
Verified, Devnet 5c12959.

The code has improved, and the listing on farms and nodes is still working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/99493ac5-1966-47b9-831c-8942268fe546)

And same for no nodes or farms.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8ee42b11-90ac-45d7-81a1-3ba5dba07d19)
