### ISSUE TITLE
[Portal/transfer]Can't perform any successful transaction on devnet 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1512]
while testing #1511 i noticed that every transaction failed and there is no logs as the error handled, but i removed the try/catch block to get the logs

### Steps to reproduce
 go to https://new.playground.dev.grid.tf/#/portal/transfer
 try to transfer any amount of TFTs by twin or address 

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/444f8efb-584e-4106-bfd3-417bb465a252)

![Screenshot from 2023-11-27 17-00-36](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1db19553-088a-4a54-83b7-1a4fba5832e2)

**Comment by AhmedHanafy725** [comment]
WIP: 
the issue is the config wasn't public on the class so the check balance decorator was complaining that can't access this config

**Comment by A-Harby** [comment]
Verified, 
Devnet 911c562.

The transfer transaction is working correctly with both twin IDs and addresses; the balance in both accounts has changed, and the notification is clear.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bfb568b9-f674-43e5-b9ab-4dde5e1f100c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc7c4e80-cee8-4f7f-9ce8-4ddfc483451a)

[TC2240 - Transfer TFT By Twin ID Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150449)
[TC2292 - Transfer TFT By Twin Address Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4151098)
[TC2204 - Transfer TFT By Twin ID](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150413)
[TC2293 - Transfer TFT By Twin Address](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4152312)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ab7962a
