### ISSUE TITLE
Show minting on all networks

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1513]
Should be visible for testing, and always to be tested with a mainnet minting hash (no problem there), but no need to wait on that until it reaches mainnet.

**Comment by A-Harby** [comment]
Verified,
Devnet, df55f97.

The [Minting site](https://alpha.minting.tfchain.grid.tf/) has been integrated into the dashboard and is printing the same data and validation is working fine.

https://alpha.minting.tfchain.grid.tf/api/v1/node/1
For the documents.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6584b796-9101-4d70-b178-60f89b3f7aeb)
For minting validation,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9ce595c8-07e8-4be5-9958-4f1a97e401cc)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b27ebc6d-0828-4cda-ac4d-938feb67645f)
For input validation,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/584b684a-c866-4f57-b8a0-cafe0a757250)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/49f544da-7062-471a-a831-b2c21197c20a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/429d0e9e-1369-4d57-bead-07b981204ed5)


[TC2295 - Grid Minting Explorer](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4153425)
[TC2296 - Grid Minting Explorer Validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4153428)
