### ISSUE TITLE
Change title to Threefold Dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1514]
Right now it shows TF Playground for 3.13

**Comment by A-Harby** [comment]
It keep changes with every navigation. Can't it just be Threefold Dashboard.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a3b1d9d6-c7a1-49f3-8c26-8a45f0384ed2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/619b84d1-c909-4c92-a9bb-296206b59727)

**Comment by xmonader** [comment]
This is fine, it show the view you're seeing that's normal e.g check on github it changes the browser's title to the issue's title. The problem was that it was called TF playground and now it's more than that

> It keep changes with every navigation. Can't it just be Threefold Dashboard. ![image](https://private-user-images.githubusercontent.com/109473873/288824456-a3b1d9d6-c7a1-49f3-8c26-8a45f0384ed2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODM1ODEsIm5iZiI6MTcwMTk4MzI4MSwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4ODI0NDU2LWEzYjFkOWQ2LWM3YTEtNDlmMy04YzI2LThhNDVmMDM4NGVkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMTA4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOWVhYTM4MGQyYjgzZWZlMjFiYTM4ZTVhYTlhNDNjNzk5NzAxZDlkYzM4N2NkMjA4YzQzMzYwN2M0MDc2Y2EzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S_SgS8v0xpHFI_OKtKxV-oL7JDCxSJmZEm7zTawE9is) ![image](https://private-user-images.githubusercontent.com/109473873/288824574-619b84d1-c909-4c92-a9bb-296206b59727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5ODM1ODEsIm5iZiI6MTcwMTk4MzI4MSwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4ODI0NTc0LTYxOWI4NGQxLWM5MDktNGM5Mi1hOWJiLTI5NjIwNmI1OTcyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwN1QyMTA4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YmYwYTc3ZGYyZGVlNDk3MTlmZjUzMmM0MWFjM2FiYWUyOGY1MmQwYjdmMGY4OGRlZDlhMzEyNTMxODQ0ZTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zpE32khPvEROiY5wqVDTX3bzVYwAIQq2RVGyGsF4l3E)
