### ISSUE TITLE
Dashboard Footer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1515]
We are missing a proper footer with links to threefold website

Example footer of threefold website https://threefold.io

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/dda8fe20-44c5-41dd-a033-0b0f4dfd6d8b)

**Comment by ehab-hassan** [comment]
Work still in progress Figma ll be ready Soon

**Comment by ehab-hassan** [comment]
@xmonader please check the options


with Details
![option1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/2068aa76-23e6-44ef-a1b0-2e118190db03)

less details with a link to Threefold
![option2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/16b0ecd8-990e-418f-9ec0-7ba65042ce65)

just copy right and link to TF
![option3](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/bd7a96dc-225b-46b2-b64b-decc00ec7c52)

https://www.figma.com/file/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=592-1881&mode=design&t=Y6KHJ5Lxih8GeaMd-0

**Comment by ehab-hassan** [comment]
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=579-1852&t=FvVM96ONvxcSUha4-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A1248

![Frame 314](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/64988e6e-598d-44f1-b31e-69f894494837)

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
Added content and tried to style it in vuetify and make sure all responsive

**Comment by ehab-hassan** [comment]
Investigation and Solution:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/20f27787-8620-4542-91b2-b3d10d49c338)

Styling and responsive finished but I have some issues and need some help
- when I made the footer a separate component in Vue it took full width behind side bar and other  error with reading img
- The color attribute not working need to make the text header a secondary color and link white (and match light mode also)

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
got help from @mohamedamer453 and @MohamedElmdary, ll create PR soon

**Comment by A-Harby** [comment]
Footer is not responsive

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/af1b4855-34fb-4cca-b0e3-a42cfee56627)

**Comment by ehab-hassan** [comment]
Work Completed
responsive fixed at small screens

**Comment by khaledyoussef24** [comment]
the footer is responsive now
network : devnet
version : 385928e
![Screenshot 2024-03-25 at 8 41 08 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5d65c427-1ae0-4421-a907-ecddc021a530)
![Screenshot 2024-03-25 at 8 44 40 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ebc8b22f-b077-4f1b-9996-0a545fa1ec22)
![Screenshot 2024-03-25 at 8 44 45 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/56f9a4a7-194d-438f-a4d7-8f5da0955cd0)
