### ISSUE TITLE
Add a logo on the splash screen

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1516]
Also maybe a fancy loading text

**Comment by ehab-hassan** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a91ce518-5191-49ce-a4c9-e348a2e32191

logo added

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

verified logo is now added to the loading page.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/28862f6b-4c73-4264-82c7-118657db19f6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5307bc89-660e-4a12-8d9a-1f972fbbd4c1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/30fedd8b-ec77-4160-af59-fd2a53693bfa)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4247651
