### ISSUE TITLE
VM Domains needs updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1518]
## Manage domains title has unneeded parenthesis 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/508fd2f8-2576-498f-b857-099845cf40a9)

What does Manage Domains () mean?

## No Gateways found

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0f18b976-08d2-40a6-973a-b993422edfab)

Should be no domains attached to this VM or something.

## Custom domain hint
Also when I click on add I see this hint

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c8ec6066-e098-43c6-8e24-660aa6cb597a)

Should be `Use a custom domain` 

## Select Domain
Says select domains and it says select gateway
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/106f6bed-2d35-442e-8a91-8dfcbfc61b55)

## Check TLS Passthrough Hint

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/35caa66f-91c4-448f-a995-86d437beb07f)
Please check for typos, casing and simpler explanation

## IP Address
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b2d6cdd0-8e73-4a4e-afe5-4c6e295c688e)

Is that a public? a wireguard? Add some hints for the user please

## Subdomain
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f6ab2fb7-2bbd-4714-a7d4-3b3d1227fb1f)

What does that even mean??

## The action button

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/9a995813-04ae-4584-9806-542c6f481ecd)

It says deploy, while it's more of Create or Add a Domain

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-11-28 11-20-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/99be3686-6476-47b9-b277-20fcf51d81d2)
Title looks fine on qanet

**Comment by MohamedElmdary** [comment]
> ## Manage domains title has unneeded parenthesis
> ![image](https://private-user-images.githubusercontent.com/64129/285956647-508fd2f8-2576-498f-b857-099845cf40a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNjg0MTQsIm5iZiI6MTcwMTE2ODExNCwicGF0aCI6Ii82NDEyOS8yODU5NTY2NDctNTA4ZmQyZjgtMjU3Ni00OThmLWI4NTctMDk5ODQ1Y2Y0MGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDEwNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5MWI1ZjFjM2EyMWFjODNiMDM0YTM2MDBlMTUzZmZkMDFmNjU2N2Y3NmQ4MDcxMjlkNTAyZjdkMTQwZjYxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LYlHNqG5oPPq1PLmD-u5c-nfDin90i_F60UdMXaAgKg)
> 
> What does Manage Domains () mean?

We include the Deployment name between `()` to tell user that we are working on that specific deployment.
Not sure why there is no name passed there but If you can reproduce it please write how to reproduce steps

**Comment by xmonader** [comment]
It's happening with my account on the new.playground.dev.grid.tf

**Comment by khaledyoussef24** [comment]
verified on version : d87cc99
network : Devnet

- manage domain title fixed from manage domain () to having the vm name between brackets
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/28dde826-fad7-4c7b-acad-36cfb6444ae6)

- custom domain hint fixed to 
`use a custom domain `
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a8d90dce-9ca3-446a-bb0b-183b4936949a)

- `please select domain` changed into `please select a gateway`
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a9a885c1-28b3-485c-8b84-f4d650d6d1e4)

- tls hint changed to be more clear:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d9c8df7b-fdb8-4260-bca2-1e0f3ff302ae)

- the ip is now mentioned as a wireguard ip
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9c450a9f-7b3d-43a7-8020-7a7366f6872c)


- sub domain hint is now more clear
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e80bf95e-05a5-4995-ac4d-c6ce996c4359)

- deploy button changed to add
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bbf32450-a14f-4138-9a98-3918d59c2002)

- no gateways found changed to `No domains attached to this virtual machine.
`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/56543394-d2ff-4dc6-862c-fda236cd5472)

**Comment by ramezsaeed** [comment]
this hint should be more clear,
its the solution name + twin_id
not project_name + twin_id

![Screenshot from 2023-11-29 12-39-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9838a120-4cb2-4562-8219-fcc9456c3474)

**Comment by ramezsaeed** [comment]
Verified and approved
- Devenet
- version: 5b5a870

![Screenshot from 2023-11-29 14-28-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/61fd44f8-0084-48fb-9248-a7ce3aaf0605)


![Screenshot from 2023-11-29 14-28-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1fb9c06b-6297-4d74-8c1b-8ac26efc4824)

**Comment by MohamedElmdary** [comment]
Reopen because of `()` no name issue appeared on 3.13

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 2d54818

I tried different deployments from FullVM and MicroVM, and it displayed the name of the VM on all of them.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3d87643e-9dfd-4e8e-a8c3-04e26a82c649)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b0c5afe8-5bc3-4707-b1f3-b7deeed24339)

[TC2150 - Check domain list and verify a clear message with no domains](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150359)

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384


![Screenshot from 2023-12-17 21-13-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5c5ae832-6060-42e7-9674-178ffe6b3ed0)
