### ISSUE TITLE
Research stricter github actions to integrate in our workflows

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1519]
check also on typescript repo 
https://github.com/microsoft/TypeScript/tree/main/.github

also check the marketplace please https://github.com/marketplace

**Comment by Mahmoud-Emad** [comment]
Could you please provide some extra details?

**Comment by zaelgohary** [comment]
I found some workflows that might be useful.

[typos-action](https://github.com/marketplace/actions/typos-action)

[codecov](https://github.com/marketplace/actions/codecov)

[yarn-lock-changes](https://github.com/marketplace/actions/yarn-lock-changes)

[AI-code-review](https://github.com/marketplace/actions/ai-code-review-action)

**Comment by samaradel** [comment]
some suggestions to discuss (updated):
- [github-checks](https://github.com/marketplace/actions/github-checks)
- [opencommit-improve-commits-with-ai](https://github.com/marketplace/actions/opencommit-improve-commits-with-ai)
- [cache](https://github.com/marketplace/actions/cache)
- [release-drafter](https://github.com/marketplace/actions/release-drafter)
- [create-pull-request](https://github.com/marketplace/actions/create-pull-request)
- [release-please-action](https://github.com/marketplace/actions/release-please-action)
- [sentry-release](https://github.com/marketplace/actions/sentry-release)
- [dependency-review](https://github.com/marketplace/actions/dependency-review)
- [trufflehog-oss](https://github.com/marketplace/actions/trufflehog-oss)
- [pull-request-title-rules](https://github.com/marketplace/actions/pull-request-title-rules)

**Comment by samaradel** [comment]
### Work in Progress (WIP):
openAI workflow integrated, need more strict workflows

**Comment by xmonader** [comment]
I'm suggesting integration of 

commitcheck
codacy
snyk


or similar as well

**Comment by samaradel** [comment]
> I'm suggesting integration of
> 
> commitcheck codacy snyk
> 
> or similar as well

I had the same suggestions but it turns out it's apps, not workflows

**Comment by khaledyoussef24** [comment]
how can we verify this ?

**Comment by samaradel** [comment]
> how can we verify this?

@AhmedHanafy725 can you help, please

**Comment by khaledyoussef24** [comment]
verified the usage of snyk(security tool) and it is added to the work flows
code scanning is working effectively
<img width="357" alt="Screenshot 2024-08-01 at 9 45 55 AM" src="https://github.com/user-attachments/assets/54a6a3fb-791e-4d68-af2f-1c0a04f70da6">

automatic issue creation for  Security Issues Detected
Server-side Request Forgery

Use of a Broken or Weak Cryptographic Algorithm

Missing Rate Limiting

Use of Password Hash with Insufficient Computational Effort

Clear Text Storage of Sensitive Information
<img width="977" alt="Screenshot 2024-08-01 at 9 55 00 AM" src="https://github.com/user-attachments/assets/38abb0bb-3b6a-4aea-afc6-2773044a8b2e">
