### ISSUE TITLE
include codeQL 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1520]
https://codeql.github.com/docs/codeql-overview/about-codeql/

**Comment by khaledyoussef24** [comment]
codeQL integrated
code scanning is working effectively
<img width="357" alt="Screenshot 2024-08-01 at 9 45 55 AM" src="https://github.com/user-attachments/assets/54a6a3fb-791e-4d68-af2f-1c0a04f70da6">

automatic issue creation for  Security Issues Detected using codeQL and detecting threats
Server-side Request Forgery

Use of a Broken or Weak Cryptographic Algorithm

Missing Rate Limiting

Use of Password Hash with Insufficient Computational Effort

Clear Text Storage of Sensitive Information
<img width="977" alt="Screenshot 2024-08-01 at 9 55 00 AM" src="https://github.com/user-attachments/assets/38abb0bb-3b6a-4aea-afc6-2773044a8b2e">
