### ISSUE TITLE
Inconsistent tooltip buttons

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1521]
This goes for all solutions.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d1fb999f-1849-4be8-8ec4-2ed6fb8e8671)

**Comment by zaelgohary** [comment]
The tooltip in the dedicated switch is actually a link where the one in certified is just a normal tooltip, that's why they're different.

**Comment by xmonader** [comment]
They need to be the same, with a link or not, the looks should be consistent :(

**Comment by A-Harby** [comment]
Verified, Devnet, 2d54818.
Except for the tooltip in the navbar.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/394a8b29-10cc-40c2-94e3-33038fc4ebea)
All the tooltips on every page, tab, and solution have the same icon.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9173df5b-d04b-468a-a7fb-44d8786ea5a5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/dda139ce-2116-4985-ab73-4aafd66a7c25)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2d49bbfd-3953-424d-a7c2-f14f5c1c6888)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6103c358-6bfa-4140-bba2-187a4ec05750)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0e54504c-1d92-4019-981f-36772cfb13fa)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a81c39db-1496-4b7a-94ce-77212f8ba1c7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8680fc4a-60b9-4a89-9e87-73622ce6c914)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ce9c689f-1018-47e7-bbf3-41da46392881)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5917b72d-da68-47f2-be59-f88ff7a98fcb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1cfb438-66d0-422f-b0d2-25a2b93a173a)

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384
