### ISSUE TITLE
Different color for info mark in create full VM page

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1522]
![Screenshot from 2023-11-28 09-54-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/901fb1a1-8360-4d1d-a663-f1eb37db5c49)

The info mark beside the dedicated node is white color however the other marks are transparent.

**Comment by zaelgohary** [comment]
Duplicate for: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1521
