### ISSUE TITLE
enhance explorer farms table

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1524]
- is there any need to have free, used, and total ips in the same table? we can go with only two of them, i suggest total and free
- `free` public ip we may change this to something like `available` ips

**Comment by A-Harby** [comment]
Verified.
Devnet, 2d54818.
Used IPs was removed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/99f09908-876e-4105-a0a4-69dea0d08a11)

[TC2269 - Farms Table Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150478)

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
