### ISSUE TITLE
Explorer farm filters are broken

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1526]
Explorer farm filters have some issues:

- It only searches with the first character/digit of the search input
- Sometimes it returns no data available while it should not
- The correct data are being returned only if the search is pasted to the field

[explorer_farm_filters.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/534d34f6-2e59-4076-8300-20756a255c64)

**Comment by A-Harby** [comment]
Verified, 
Devnet, 2d54818.

Farm ID is searching for the correct farm and waiting for one second after finishing writing to start filtering.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b557b06c-477b-4b13-a89c-7c3655f06f95)
Same for the farm name, and it also works for non-sensitive cases.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/24a10c79-d06e-48a7-9a57-08044ca8a94a)

[TC2273 - Filter Farms by ID](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150482)
[TC2274 - Filter Farms by Farm Name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150483)

**Comment by ramezsaeed** [comment]
verified on:
- Devenet
- 6d0ec3d
