### ISSUE TITLE
Cannot add new domain for existing VM

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1529]
### Description

Regarding to:
Add actions to vms to add/remove gateway workload to/from a vm

Failed to add gateway to Vm in all networks
Devnet
Qanet
Testnet

### Steps to reproduce

![Screenshot from 2023-11-28 15-23-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/63e0a1f0-7cc3-483b-b512-11519a01c72f)

**Comment by khaledyoussef24** [comment]
faced the same issue even when trying to deploy with custom domain 
![Screenshot from 2023-11-28 16-00-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/102db95f-c0f9-4141-b72e-d824c8c7d26a)
![Screenshot from 2023-11-28 15-59-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39411113-1683-4eec-957b-80223a7c02a2)

**Comment by ramezsaeed** [comment]
Verified and working fine with more than 20 domains till now
- Devenet
- version: d87cc99
