### ISSUE TITLE
Getting domain list for a VM doesn't timeout

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1531]
Env.: Qanet
Version: 2.2.0-rc4

### Description

When a VM has multiple domain name, getting the list take a lot of time and doesn't even fail.

![Screenshot from 2023-11-28 16-27-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/3018cc23-d3f3-4dd5-ae02-1219eb363a69)

**Comment by xmonader** [comment]
Changing to 20seconds timeout fixed it (given the time to load deployment information along with the creation of the name contract)

**Comment by khaledyoussef24** [comment]
it works fine now in listing ( it may take too long time some times)
![Screenshot from 2023-11-29 07-10-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4204e39e-01d6-4759-bbf9-bf9ea154dc89)
but every time i use the refresh button it fails to reload the domain list
[Screencast from 11-29-2023 07:10:32 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/993c1dcc-63b5-4f22-9fb1-189afdd1afd5)

![Screenshot from 2023-11-29 07-11-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/125c436a-cd92-460a-85de-3392d568449b)


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/aaf5967d-d174-4f85-b51a-1eaa84c8ea24)

**Comment by khaledyoussef24** [comment]
fixed in version: d87cc99
[Screencast from 11-29-2023 09:57:56 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c95f7314-6973-4ff8-8aa5-2095c60ce90a)

**Comment by ramezsaeed** [comment]
Verified and working fine now on 
- Devnet
- version: d87cc99

![Screenshot from 2023-11-29 10-20-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7e0689b4-a56b-4f55-b6e6-2b2bde61defe)

**Comment by ramezsaeed** [comment]
Verified as can't hist this error again after more than 10 domains added to multiple VMs.

- Devnet
- version: 5b5a870
