### ISSUE TITLE
statistics website: networks order

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1535]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/325e07de-cba6-4821-8fd4-333e28e23b5a)

it shows dev, main, test and I'm not sure how was that ordered (dev, test, main) is a more realistic order.

**Comment by A-Harby** [comment]
Was that removed?
Where is that can't find it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc4a3650-ea90-454b-9bf0-bf9ced5ebd3c)

**Comment by A-Harby** [comment]
Verified,
Devnet https://stats.dev.grid.tf/.

Correct order is abled and selecting is working correct.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fd2bb098-0b7e-4cb6-a299-36115ce0502d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/837b579b-f061-412f-a0f5-ff4c50f4400f)


[TC2297 - Choosing Nodes stats network](https://app.testlodge.com/a/26076/projects/40893/suites/211395?expand_section=353833#case_4153959)
