### ISSUE TITLE
Contracts: Change Export My Data button to Export

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1536]
Please change Export My Data button to `Export`

**Comment by A-Harby** [comment]
Verified,
Devnet, 2d54818.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bd872ab0-6432-41a3-92ce-1d41cec1f90b)

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384

![Screenshot from 2023-12-17 21-22-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1d0e9057-1282-4d12-aa24-c2e2991beea7)
