### ISSUE TITLE
Publish the UI package on npm, create v server for the verification 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1542]

**Comment by A-Harby** [comment]
I keep getting this error when I run the Node.js example server, despite running yarn install and build.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6c68c9e1-dd1d-45c5-9e94-c844861a370f)

And can you also add documents for the vlang server, or just make the Node.js server work for both of them?

**Comment by Mahmoud-Emad** [comment]
@A-Harby

Hello Harby 😊,

Addressing the first point, it seems like there might be a dependency error. Kindly verify the successful installation of the `cors` package by checking the `node_modules` folder.

Regarding the second point, the `v server` is intended to replicate the behavior of the `Node server` without verification. It simply logs the request payload. To enhance clarity, I'll update the server documentation with step-by-step instructions on how to run it.  thanks for bringing these points to my attention. I'll get to work on the updates.

**Comment by A-Harby** [comment]
Yes, the nodejs error was from my npm, and after I updated it, it worked fine.

> @A-Harby
> 
> Hello Harby 😊,
> 
> Addressing the first point, it seems like there might be a dependency error. Kindly verify the successful installation of the `cors` package by checking the `node_modules` folder.
