### ISSUE TITLE
Responsive twin page

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1556]
### Description

info tooltips in twin details page are unresponsive to different page sizes

### Implementation

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/8eac5dc3-cc58-4d1e-8b20-34d597047fe4)

**Comment by A-Harby** [comment]
Should be pending deployment I think?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bbb21c09-4184-4f9e-b873-4207b7d4f196)

**Comment by A-Harby** [comment]
Verified,
Devnet, 0b2f0d3.

Twin details is now responsive.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4a1aa829-f619-4aeb-bc38-0d8d26cb86bb)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
