### ISSUE TITLE
Warnings font are not the same

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1560]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5906e0c6-dc75-4ab4-8f1f-fc027810695c)

there is also typo here: "contract/ contracts"

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

The message font have the same size now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/541fdae8-b89c-432e-aa82-181fcf87e60b)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/652b6c1e-f41a-4cae-84d7-6f7a1ab4b60e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3
