### ISSUE TITLE
Bugs in dedicated nodes

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1561]
- Filters do not reset after changing page then mounting the dedicated nodes again.
- Reset filters button does not clear data from the filters
- Filters dropdown is always closed by default, so if user filtered and no data returned, he might think no data are being returned without filtering

[dedicated_nodes_filter.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/1541f9ea-9993-406a-90bb-9255b699b86f)

Filters do not apply unless the tab is changed. This goes for GPU too.

[filters2.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c34399b7-b24c-4821-bf99-d5029c28300f)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1580

**Comment by Mahmoud-Emad** [comment]
### Issue Update 


- Resolved the reset filter issues by implementing a function that returns an object with the default values. This approach replaces the previous direct object usage `() => obj`.
- Reset filters in the farms page, updated the nodes page, and addressed an issue related to the max integer value in the filters.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 2d54818

All the filters are opened by default when you select the page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2ed27c38-db28-4bfa-810a-781053bb5446)
The request is done after 1 second
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5cd5ac4d-03f5-4562-a6c5-04041915d078)
And changing tabs when filter is applied does re-request with new filters
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e374bc5b-e85d-4102-b371-38a8d742a387)

Test cases:
- [TC2225 - Filter dedicated nodes by Total SRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150434)
- [TC2226 - Filter dedicated nodes by Total HRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150435)
- [TC2227 - Filter dedicated nodes by Total MRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150436)
- [TC2228 - Filter dedicated nodes by Total CRU](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150437)
- [TC2229 - Filter dedicated nodes by GPU's vendor name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150438)
- [TC2230 - Filter dedicated nodes by GPU's device name](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150439)

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384
