### ISSUE TITLE
Transfer page: Add validations for account address and twin_id 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1562]
in the transfer page

**Comment by xmonader** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/08b5537a-d977-4d11-b251-b75085812d17)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b9ddedef-9e2b-41b3-bdf0-e5f5a523ba49)

there's some validations in place, will leave for QA to verify

**Comment by A-Harby** [comment]
Verified, 
- 2d54818
- Devnet

For the Twin ID:
- For the same twin ID.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8712692f-4889-4dec-bc63-00214280a4bf)
- Not a number.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/17796f3d-f1bf-4714-982d-bded74be4642)
- Twin ID that doesn't exist.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/62125e89-0449-45f5-98c6-03f22cc2c4fe)
- Negative numbers.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a5d1aedc-ac89-4317-b7ba-0fe1e1c9539d)

For the Twin Address:
- For the same twin address.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/813fafc0-0f34-4dab-925a-6e14d833fc57)
- For an invalid address.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7e1d33c1-0ccc-4184-8ea6-a73d507272a2)

[TC2292 - Transfer TFT By Twin Address Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4151098)
[TC2240 - Transfer TFT By Twin ID Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150449)
