### ISSUE TITLE
Sidebar reordering

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1565]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/08dc0c04-3841-4984-8de5-da25f838d751)

move Manual to be the last item on the toplevel sidebar (outside of Service menu) -> should be on the top level menu (How can the user find the help link or the manual? if not very visible on the sidebar?

rename Grid Services -> Grid Health

Order:
- 0-Bootstrap (hint: Download Zero-OS Images)
- 0-Hub (hint: Find or Publish your Flist)
- Minting (hint: TFGrid Minting Explorer)
- Monitoring (hint: Monitor Zero-OS nodes)
- Grid Health (hint: Status of Threefold Services)

**Comment by A-Harby** [comment]
Verified, 
Devnet, 2d54818.

The Manual link is moved outside and the services link are re-ordered.
And the tooltip is added to each of them.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0bb6d261-d659-46c1-81b2-e9468a00d139)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/04edc0d2-bbe9-49d6-81aa-7b3a0ac35b81)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ab7962a
