### ISSUE TITLE
Farm name maximum character limit

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1568]
### Description

The current max length of farm name in the new playground in 15 character while it's 40 characters from the chain and the old dashboard also had a max of 40 characters.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7df4210c-3458-48ef-974c-0afe615c510e)

also here are some of the farms that were created from the old dashboard that exceeded the 15 character limit and they were created without any issue.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/64e08744-73b2-4db1-a373-220142ef2664)

and from the chain here's a farm that has a 40 char name that was created successfully.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4ede4494-4ec0-45a7-95cd-25f5d2d9fb0e)
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/99323756-8384-49ba-bf5d-4b148e31f019)

### Steps to reproduce

- Login to your account.
- Navigate to Dashboard then to Farms.
- Click on the `Create Farm` button.
- Enter a name that has more than 15 char

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

The maximum char limit is upgraded to 40 char now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fe55cf7a-bb3b-4c35-b773-708caeb6ed51)

[TC2241 - Farms Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150450)
[TC2205 - Create a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150414)
