### ISSUE TITLE
(Mainnet Verification) Incorrect node uptime value in the `Your Nodes` table

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1569]
### Description

The current value of node uptime is incorrect in the new playground.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/14fbb31b-bc96-413b-96e7-a9b0ea2c2577)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/34b98316-e22f-4de9-8324-d89a9d6feab3)

This goes for all nodes either up or down as seen in the images above.

### Steps to reproduce

- Login to your account.
- Navigate to Dashboard then to Farms.
- In the `Your Nodes` table, check the uptime of any node.

### Environment 
- Network: `Devnet`

**Comment by 0oM4R** [comment]
investigation:
this is not calculation issue, this happens only after reloading the user nodes after a time out 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/8df79cc241b75160649caeade8e46cc2100fe3fc/packages/playground/src/dashboard/components/user_nodes.vue#L212-L214

not sure why this is happening yet

**Comment by A-Harby** [comment]
Can you help on how this value `3568977` converted to `23.56%`?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da22383f-127f-4747-8817-526884c1c89d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9632536d-b2c8-483f-abc6-b114e184e218)

**Comment by A-Harby** [comment]
I was able to get the calculation but couldn't find any documents or explanations on how it was calculated.
  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bbd535c7-3771-4f5e-8cd9-4c65106f069a)

**Comment by ramezsaeed** [comment]
@0oM4R 
please check Harby comment

**Comment by 0oM4R** [comment]
https://github.com/threefoldtecharchive/tfgrid_dashboard/issues/366#issuecomment-1304436906

@A-Harby  this should explain

**Comment by A-Harby** [comment]
For the documents, I create an issue [here]: https://github.com/threefoldtech/info_grid/issues/354.

**Comment by A-Harby** [comment]
For the documents, I created an issue [here]: https://github.com/threefoldtech/info_grid/issues/354.

**Comment by A-Harby** [comment]
Verified on Devnet,

The percentage value is back to normal, and the calculation seems to be okay.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/68b00b21-9107-447b-b2cc-aab1f43c6181)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d71501df-1960-4608-ad89-0ab2b6ccd89f)

I will wait to be verified on Mainnet for more node uptime values.

**Comment by A-Harby** [comment]
Verified, Testnet 2.3.0.

[TC2214 - Verify Node details](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150423)

The percentage is normal and was calculated correctly given that the node was down after start-up. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/748113b5-32dc-493e-9a15-d7fbed96a9ea)
