### ISSUE TITLE
Node availability check in the farms page is done twice

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1570]
### Description

The node availability check that checks the uptime of the node when the user enters the farms page is done twice. and with the second time if the node details is expanded it will close it.

[Screencast from 04-12-23 13:01:31.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3b284073-c5dd-4578-b6e9-f8b55c582ae6)

### Steps to reproduce

- Log in to your account.
- Navigate to the dashboard from the side bar.
- Navigate to farms.
- Expand the details of any node.
- Check the console.

**Comment by A-Harby** [comment]
Verified,

Node requests are only being called once.
https://gridproxy.dev.grid.tf/nodes?ret_count=true&page=1&size=10&owned_by=162
https://gridproxy.dev.grid.tf/nodes/72
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d6842e00-9cb0-4632-8df0-1355a08519f7)
