### ISSUE TITLE
Items per page is not working for the `Your Nodes` table

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1571]
### Description

Items per page is not working for the `Your Nodes` table and it shows all nodes no matter what node count is selected per page. 

[Screencast from 04-12-23 13:51:35.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a43d384b-df77-4f0d-bf9c-2db46bfdf1df)

### Steps to reproduce

- login to your account.
- Select Dashboard from the sidebar then select Farms.
- Check the your nodes table (twin must have 15 or more nodes to test all cases)
- Select different values for items per page.

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/fdb769da-a7db-4aa7-8c57-a7bf4ee3fd8b)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/df8bd186-c5c3-4a24-bd71-7f2f44beedc6)

**Comment by A-Harby** [comment]
Verified,
Devnet, 3fc8787.

Item per page is working fine, as is navigation.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/650e6b11-b0fa-4c45-a3e4-3122a1a8e175)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
