### ISSUE TITLE
Minting: TFT Farmed field is confusing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1575]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3b31a39f-4ae6-4376-a5c3-754ddbc7fde0)

**Comment by A-Harby** [comment]
Verified,
Devnet 842ebef.

There was some clarification added.  
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1a40db5-1afc-4468-922d-5535a4205236)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
