### ISSUE TITLE
The error message in the farms page for not being able to load the user's nodes appears twice

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1579]
### Description

In the farms page if there's an issue and the loads failed to load the error message appears twice.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ea416ef7-2d69-4743-bbbc-9766b5b7f133)

### Steps to reproduce

- Navigate to Dashboard from the sidebar then to Farms.
- There must be an error that prevents the nodes from loading.
- Check the error message in the top right corner.

**Comment by maayarosama** [comment]
Can we add more steps on how to reproduce it, because I've tried multiple scenarios the notification is only showed once as follows 
![Peek 2023-12-12 19-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/5dec56ed-6e1a-4d0c-ace3-7c130327e321)

**Comment by mohamedamer453** [comment]
> Can we add more steps on how to reproduce it, because I've tried multiple scenarios the notification is only showed once as follows 

It was during development so there was no specific scenario that i followed, however i tried to reproduce it again and i wasn't able to and indeed it only appeared once. my guess is it was related to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1570 and got resolved with it.

**Comment by khaledyoussef24** [comment]
could not repreduce the same issue again
the farms page works fine and even another issue of uplicated requests were fixed

**Comment by ramezsaeed** [comment]
could not reproduce.
