### ISSUE TITLE
Error message not handled in `Grid Client`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1585]
- I got this error 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/dbffa764-e850-431b-af4f-d9599fec3402)
from here :
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/de5154c3-3a1c-4264-8379-26ad87876e90)

**Comment by AhmedHanafy725** [comment]
the error message is shown correctly
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/d6c87301-3148-4e37-926f-44151fe07b70)
