### ISSUE TITLE
Second nav bar appears after log out 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1586]
![Screenshot from 2023-12-05 14-35-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/83ea5a7d-777b-4380-821a-2a868d611a6a)

**Comment by AlaaElattar** [comment]
### Work Completed:
- Added condition that second navbar won't appear until user logged in.

**Comment by A-Harby** [comment]
Verified,
Devnet 0b2f0d3.

The second nav bar doesn't show when the user logs out.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a5fa505-22b5-4faf-b52e-0b5e92feae80)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 13a87cf

![Screenshot from 2023-12-19 11-33-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/aa81cbd2-5ff1-4f70-b694-4b33d1fa5cff)
