### ISSUE TITLE
Confusing two Farms tabs in the playground sidebar

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1587]
its confusing to see two tabs with the same name "Farms"
beter to change the one in dashbpard to "Your Farms

"1- sidebar --> Dashboard --> Farms
2- sidebar --> Farms

![photo_2023-12-05_15-27-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/d281f589-f597-499d-aeaa-6f5480e45935)

Env.: DevNet
Version: 3dc6be3

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e4c742a1-b37f-4e7d-8628-e5c2b752b75f)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 14-24-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e7258fc4-8f86-41d0-862f-52c81479e046)
