### ISSUE TITLE
Pagination works in explorer nodes when there is no data

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1588]
[Screencast from 12-06-2023 11:20:57 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/16958ca0-c42e-4c0a-85f3-50ae31fd0df2)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/49d0ed2c-099d-4de2-bfcc-0adc6cbed60f
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4250318
