### ISSUE TITLE
Explorer grid button pointing to the dashboard

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1589]
### Description

New playground, Devnet.

Why is this button linked to the old dashboard? If this is the new UI, it shouldn't be connected to the old one.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/60ca5c20-8dc7-4379-b3a7-ef4e4f369b23)

**Comment by A-Harby** [comment]
Its now pointing to https://dashboard.dev.grid.tf/explorer/statistics, which can't be found.

**Comment by mohamedamer453** [comment]
Update:

Currently blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1314 since the user can't access the stats page without logging in.

**Comment by khaledyoussef24** [comment]
verified now opens stats page correctly
enviroment used : devnet
<img width="388" alt="Screenshot 2023-12-19 at 11 04 07 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ecf69508-3549-4ef2-bbab-4e744080ea3a">
<img width="451" alt="Screenshot 2023-12-19 at 11 06 07 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/884eb641-934a-482e-af9c-baa199cbcf52">

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4156941

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- c9a726e

All Links in landing page working fine:
- explorer threefold grid capacity
- learn about the grid
- Use the grid

![Screenshot from 2023-12-19 16-01-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ccfbcc49-84f4-46cc-bf94-f2c412dc3a69)
![Screenshot from 2023-12-19 16-01-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/dcc7d03a-787a-4c24-9887-7d5938686cf8)
![Screenshot from 2023-12-19 16-01-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1071cf75-2fa5-430b-b75f-22377e3f3fa1)
