### ISSUE TITLE
Adding a way to explore grid capacity

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1590]
### Description

New playground, Devnet.

There should be an option for the user to see the grid capacity; the explorer page should be available to the user without the need to connect a wallet.

Showing the grid capacity to the new users would be encouraging to get them to sign up.

Like the dashboard, there's a way to reach that information without logging in.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ac7785d6-e861-48cc-9457-29822ffe73b2)

**Comment by zaelgohary** [comment]
Should be done [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1314)
