### ISSUE TITLE
Change close button UI in connect your wallet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1591]
## Description

New playground,

The close button in the Connect wallet really does look like it is disabled in dark mode.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/825e49a5-35ef-4e33-a3b7-93ac6b72e814)

**Comment by ehab-hassan** [comment]
Fixed at development_tooltip__color https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1626
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b1714113-55e6-4b6f-ba76-19e7aefa3c23)

**Comment by A-Harby** [comment]
2d54818 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/46a9118a-50d6-40ce-b9f8-68d9d035d846)

**Comment by ehab-hassan** [comment]
it seems my code overwritten :)
https://github.com/threefoldtech/tfgrid-sdk-ts/commit/6819bfbc2c9e70e12eb4030fde22f28693fa7bf1 
created new PR
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1634

**Comment by A-Harby** [comment]
Verified, 
Devnet 911c562.

Close button UI improved.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/225e6155-3d18-40b3-8d99-5973ce20fd53)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ac2e5bc4-f15d-401e-8e58-edd900bd96ef)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ab455aab-058b-48ad-989e-3a1b4a7c138a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/49111755-8d84-4c59-8827-a6f0cad1d242)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 13a87cf

![Screenshot from 2023-12-19 14-07-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/db3f99a1-a70f-4d46-8492-a138bb9ec3f1)
