### ISSUE TITLE
The hint in explorer farms for Farm ID is different from hint in explorer nodes.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1592]
- The hint in explorer farms for `Farm ID` is different from hint in explorer nodes.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/cce47b5e-ee03-4048-a651-db018570adee)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/9259dc7d-46d5-4e6b-8fc6-8a569690e2ed)

- I think we should make them compatible.

**Comment by AlaaElattar** [comment]
### Work Completed
- make `Farm ID` filter in nodes page accepts only one id as in farms page.

**Comment by A-Harby** [comment]
Verified,
Devnet 0b2f0d3.

Both filter have the same message hint now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5749f556-7e1e-4bd9-9563-3c1d5fbd1319)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0cb8184e-85e7-4f8a-bad6-aaf22c3159e3)

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
