### ISSUE TITLE
Contracts List Solution Type

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1593]
### Description

The solution type in the contracts table should be Full VM, MicroVM etc . Instead it shows this 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/841ef9ce-6e94-404e-a333-0035acf19d8b)

### Steps to reproduce
Deploy a VM from solutions then go to Contracts under Dashboard in new Playground

**Comment by Mahmoud-Emad** [comment]
### Issue update

Should be fixed [here ](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1567)

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/cbe883ca-30b8-48a8-93de-1757f8b71918)

**Comment by khaledyoussef24** [comment]
verified contracts list now provide solution type
<img width="197" alt="Screenshot 2023-12-20 at 12 33 56 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a9ffb260-7c22-4af1-b01e-405c468696b8">
test lodge :https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4157417

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 14-01-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e2a967be-7c18-4f41-88b0-18bee6041eff)
