### ISSUE TITLE
connect your wallet dialog isn't responsive

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1595]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/104bc3ee-fdce-4bb9-914b-18f301fa7d02)

chrome 100%

**Comment by A-Harby** [comment]
Verified,

Devnet, a16e38d.

[TC2113 - Connect Wallet](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)
[TC2117 - Verify Wallet Login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150326)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6adb1618-0a74-4ae1-b585-782971d0568a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/29e9cd6f-ae44-4c99-a1a8-8e9d233cbae8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/83729413-9c81-4aad-b42d-80a8b5b09e32)
