### ISSUE TITLE
Mnemonic failed to validate 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1597]
### Description

New dashboard, Devnet.
I got this error while trying to connect my wallet, and I tried again and it worked fine, but it failed more than once.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ba103646-8baa-4e59-ad6c-34aa7761073f)

**Comment by A-Harby** [comment]
Also this happened after trying to connect.
[Threefold Dashboard _ Owncloud.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6be76314-fd34-490d-a92b-d9238e63166f)

**Comment by 0oM4R** [comment]
Investigation and Solution:
trying to reproduce but couldn't show that error in the hint, will investigate tmw

**Comment by 0oM4R** [comment]
The `validateMnInput` got triggered twice, first time, the `isConnecting` was set to true and failed while creating rmb connection, so in the second time, it not create an rmb connection as the `isConnection` is true. so we couldn't even got this error for now
- need to delete the key in finally <if the connection failed> 
-  need to fix inputValidator to validate mnem once

**Comment by 0oM4R** [comment]
Work Completed: enhanced error handling in the clients and added new error types to types package
Work in Progress (WIP): handle the errors in a proper way in playground

**Comment by A-Harby** [comment]
Verified,
Devnet, 93374f0.
[TC2113 - Connect Wallet](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)

I used the same mnemonic and a different one, and I didn't get the error while validating or connecting after.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/79081144-1a20-41b9-8beb-c8494862b342)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/96b38414-a119-44d8-befb-de797d5bcb7b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
