### ISSUE TITLE
Farm page doesn't show all of my farms

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1598]
### Description

New Dashboard, Devnet.

It only shows that I have 10 farms, while I do have a lot more.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/043174ef-1eaf-442b-8ce5-0c1a092ff6b0)

And if I change the item to 15, it shows that I only have 15, and so on.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/89ffcae3-3d00-48c4-9b93-2a6d935f40bb)

And also, the next page button is disabled, so I can't get to my other farms.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/56fb5bb1-fa6d-427c-852b-7deced2504a3)

**Comment by A-Harby** [comment]
Verified,
- Devnet
- e2580a5
- [TC2246 - List farms](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150455)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/71e260ef-357d-42cb-9778-32294693a5ef)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e3fafd95-0337-4269-af2a-da5e4319bc36)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9527d749-8dbe-4aec-b013-cf306f3ae60b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/395d338a-78c8-4d78-94a7-5b63791573d7)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- ebf75a3
