### ISSUE TITLE
`Failed to get the user farms` when changing number of items per table on the farm page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1599]
### Description

I got this error while changing items per table on the farm page. It occurred randomly, and the error message was unclear.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2a0baeb5-13cf-4bc1-b19a-13c70e44ad5d)

**Comment by AlaaElattar** [comment]
###Investigation and Solution:
- I got this error in a different way, It came from `getUserNodes`, which is really wierd. If the error from there, it should be `Failed to get user nodes!`. 
- still investigating in it.

![Screenshot from 2023-12-12 10-25-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/e549d538-ec5e-4c02-9004-d4f5e79fe1bf)

**Comment by AlaaElattar** [comment]
### Investigation and Solution:
- It occured here because of bad internet connection and there were no farms at the table.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f8446882-ff3f-41f4-89d4-82698175b9cc)

**Comment by AlaaElattar** [comment]
> ### Description
> I got this error while changing items per table on the farm page. It occurred randomly, and the error message was unclear. ![image](https://private-user-images.githubusercontent.com/109473873/288414030-2a0baeb5-13cf-4bc1-b19a-13c70e44ad5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzIwNjUsIm5iZiI6MTcwMjM3MTc2NSwicGF0aCI6Ii8xMDk0NzM4NzMvMjg4NDE0MDMwLTJhMGJhZWI1LTEzY2YtNGJjMS1iMTlhLTEzYzcwZTQ0YWQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQwOTAyNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTVjOGM4YzEyM2U5MzFiYWRjYjY2OWZhM2VkMjhkYWQ4ZTliNzgwZTM1NzEzYmIyMTIwNGIwMjdmOTlkNTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0XcosvYzFxapd327Y92zW_rQ-hxDdLWKYN_xHfd64a8)

- Maybe this error occurred when u tried to change items per page, as we send request to gridproxy each time (Internet connection error).

**Comment by AlaaElattar** [comment]
> ### Investigation and Solution:
> * I got this error in a different way, It came from `getUserNodes`, which is really wierd. If the error from there, it should be `Failed to get user nodes!`.
> * Also, all farms were displayed.
> * still investigating in it.
> 
> ![Screenshot from 2023-12-12 10-25-55](https://private-user-images.githubusercontent.com/54944491/289796879-e549d538-ec5e-4c02-9004-d4f5e79fe1bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzE5NDQsIm5iZiI6MTcwMjM3MTY0NCwicGF0aCI6Ii81NDk0NDQ5MS8yODk3OTY4NzktZTU0OWQ1MzgtZWM1ZS00YzAyLTkwMDQtZDRmNWU3OWZlMWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA5MDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ZDcwZTA2OTQwY2Y2MmM4ZDAzODkxZjc4MDlkMGQwZjA1NjM4YmU2YzIzOWU1YjRkMWQyNmE5MmUzZmRkODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OtoYsxm6MsDpMAAdYXfqgRaOUpM7bTraPfT4u4EBzxs)

- I will open separate issue for this.

**Comment by A-Harby** [comment]
> ### Investigation and Solution:
> * It occured here because of bad internet connection and there were no farms at the table.
> * Same logs same as the one provided in the issue, which means this happens when there's a bad internet connection.

Can't we reload or retry again to list these farms when this error happens to the user?

Or, if not possible, maybe change the error message from `Failed to get the user farms` to a more user-friendly message telling the user to reload the page because some error happened from a network connection error.

**Comment by AlaaElattar** [comment]
### Work in Progress: 
working on add error msg and see what can i do about reload.

**Comment by AlaaElattar** [comment]
### Work Completed:
- I updated the error msg to be more friendly.

**Comment by AlaaElattar** [comment]
### Work Completed: 
- will check on error if it's connecction error, will show that to the user.
- otherwise it will be error from gridproxy, will just show user we failed to get farms.

**Comment by AlaaElattar** [comment]
### Work Completed:
- I removed the connection check on error as when this pr https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1735 merged, this will happen with any case of internet connection.
- The other possibility of error to be from gridproxy.

**Comment by AlaaElattar** [comment]
- There's no change. 
- so will close this issue.
