### ISSUE TITLE
The title of the info section for the solutions is clipped

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1600]
### Description

The title of the info section for the solutions appears to be clipped by another component. this applies for all solutions.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8d9e5a80-1c44-444c-8051-c6ef9959b196)

### Steps to reproduce

- Navigate to the dashboard and login to your account.
- From the sidebar select solutions then select any solution.
- On the top right corner click on the `i` icon.
- Check the title.

**Comment by ehab-hassan** [comment]
fixed at development_tooltip__color #1626

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d0fd2b64-a239-4cfa-94e8-550f27c5c2e1)

**Comment by A-Harby** [comment]
Verified,
Devnet 0b2f0d3.

The title in all the solutions isn't clipped anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d77f4c93-064f-46a3-b171-e92e8ca95e15)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1366d484-4e10-435d-b564-953be3806138)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b9e2630f-f1ac-48b9-81b1-56873c3d4ed6)

**Comment by ramezsaeed** [comment]
verified on:
- Devnet
- 13a87cf
