### ISSUE TITLE
All close buttons should be on the left

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1601]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/16fff469-bab7-4658-b32f-e7a4c7e2fbe8)

This goes for all dialogues.

**Comment by A-Harby** [comment]
Verified,
Devnet, 28d6c07.

All the close buttons are positioned on the left.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/034fb44c-1cfb-4203-b423-9e4c85b7bfc8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d771322c-b96a-444b-9b87-6742323ba8dd)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d089f5b5-048c-4f0b-bba1-ded033a27f6d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/40f88c1d-da80-497b-9d46-0aa948306df2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8252883e-68ca-4a3a-a28f-c366dd66ab9d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8a6d77f0-990e-433d-b043-1ae7c8055d5a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d59c65a7-be54-41f8-b71e-83733091d32d)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ebf75a3
