### ISSUE TITLE
Twin details in node in node page is always loading

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1603]
### Description

Devnet, 2d54818.
The Twin details in any node is always loading, like it is still getting the data

### Steps to reproduce

1. Connect your wallet.
2. Navigate to the Nodes page from the sidebar.
3. Click on any node and scroll down to the Twin Details section.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/825b0222-90ba-4983-b763-88ca546a0b48)

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02.

Loading stopped once the tab opened.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a8d6cc1b-2512-4077-8696-11aa552a9193)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/840c2e5c-ab62-441c-9cee-c7e71850a892)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
