### ISSUE TITLE
Reset nodes table count and pages

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1604]
### Description

Devnet, https://github.com/threefoldtech/tfgrid-sdk-ts/commit/2d54818c4c44cb4111462b8cd3daea60c60c602a.

Filtering, applying toggles, or selecting the node status doesn't reset table counts or disable page navigation on it.

### Steps to reproduce

1. Connect your wallet.
2. Navigate to the Nodes page from the sidebar.
3. Click on any node and scroll down to the Twin Details section.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/43380107-dbaa-4ae0-a510-a555e403b1f9)

[Threefold Dashboard _ Nodes.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bdc2f0f7-e4b0-4d48-b612-ecd919bea6bc)

**Comment by mohamedamer453** [comment]
Update

Work in Progress(WIP):

Still under investigation, trying to find out how to update the `item-length` property when the status change and there're no nodes available since this is the scenario where it displays the number from the previous table while there are no nodes available.

**Comment by A-Harby** [comment]
Not all the cases have been reset.

[Threefold Dashboard _ Nodes (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/995e5058-d5a7-41a6-9a0d-23f18044f69b)

**Comment by amiraabouhadid** [comment]
Investigative Work: 
Looked for the reset triggers in nodes.vue

**Comment by A-Harby** [comment]
Waiting for https://github.com/threefoldtech/tfgrid-sdk-ts/issues/770

**Comment by zaelgohary** [comment]
@A-Harby Should be working fine now after https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1819 is merged.

**Comment by khaledyoussef24** [comment]
node count fixed to change to zero when there is no nodes:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/293a124c-99c9-4faf-ab13-0d19df015836)
checked for down, standby and up.
![Screenshot from 2024-01-02 12-58-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4e60b071-fad5-438f-a100-436156bebdf0)
![Screenshot from 2024-01-02 12-58-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/84e0b21c-812b-4aff-9d5c-93a739e4a8bd)

![Screenshot from 2024-01-02 12-58-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9bf16ea3-abfd-4c95-9f3b-ee98909d73a3)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150459

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d
