### ISSUE TITLE
Unexpected Error: `Node ID is Required` After Deselecting Node and Loading Nodes in New `Node Selection` Feature

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1605]
### Description:

As mentioned in [this PR discussion](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1457#pullrequestreview-1764929532), a concern has been identified in the recently introduced `Node Selection` feature.

### Steps to Reproduce:

1. Select a node.
2. Remove the selected node.
3. Click on the `Load Nodes` button.

### Observed Behavior:

An error message appears, stating `Node ID is required.` This behavior is unexpected and does not align with user expectations.

### Expected Behavior:

Upon removing the selected node and clicking `Load Nodes` the system should revert to its initial state without displaying an error. Users should not encounter an error when reloading nodes

**Comment by khaledyoussef24** [comment]
selection scenario has no problem now and verified in #1632  #1341 
[Screencast from 01-03-2024 01:50:58 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/05b4c499-ce65-42f9-a0c6-7ead6fc3a41f)
users now should not encounter an error when reloading nodes.

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150329
