### ISSUE TITLE
Link in `offline or standby` nodes leads to empty page

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1607]
- I clicked on `contracts` on toast 
![Screenshot from 2023-12-07 11-19-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/8146d692-3b2a-492e-8e45-6304f3206a40)
- and I got this 
![Screenshot from 2023-12-07 11-19-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/fdf4b884-dcbb-4fc1-b934-cde25cddb79d)

**Comment by AhmedHanafy725** [comment]
should be done after #1587

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 8b2c863
- [TC2437 - Get notified if contract gone grace period or node went down](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4162897).

The link is now pointing to your contract page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8063f3d3-75a4-482e-94a6-ef6d0beaa1b3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1061baf7-c4ad-473b-96a0-074c43643021)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
