### ISSUE TITLE
Dialog should be closed after creating farm or disable `create` button

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1609]
- It's confusing, either close the dialog while the farm is being craeted or disable button and show it's loading then close the dialog when the farm is created.
- There's no point of keeping it open.

[Screencast from 12-07-2023 11:57:17 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/15441c2f-f0a4-4a13-aa15-6c08ba4526e0)

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02.

The Create Farm dialogue is closed once farm creation is done.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0c8fb889-d108-409f-befc-abd699f7dbf5)

[TC2205 - Create a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150414)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
