### ISSUE TITLE
Can't read 'publicIP' in Umbrel deployment

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1611]
### Description

Devnet, 2d54818.
After deploying the Umbrel solution, I get this error: can't read public, and it doesn't display anything on the site but only in the console.
And for some reason, the action button icon disappeared.

When any error happens, the action button shouldn't disappear, and the site should notify the user of the error.

### Logs/Alerts

[Threefold Dashboard: Twin.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0555ec3d-7e64-4471-8abd-6faff538e951)

**Comment by 0oM4R** [comment]
fixed on #1715

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 46eb8ac
- [TC2132 - Deploy Peertube](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150341)

I tried different deployments and refreshing and click the buttons and no error was shown and Icon didn't disappear. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/19b5e0a9-c8c1-4797-931a-5e578e7a35d8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/59a61da7-448d-4978-892c-d753291c278f)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
