### ISSUE TITLE
UI solution card isn't responsive

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1612]
### Description

Devnet, 2d54818.

The solution card text is not responsive.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9de064b9-a294-41c9-895b-e35577368345)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 10f9f49

<img width="1680" alt="Screenshot 2024-01-31 at 3 44 35 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b9bf4199-8dfd-492c-9f65-d1288d2d54aa">
<img width="1680" alt="Screenshot 2024-01-31 at 3 44 40 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c409b4d7-55a5-4a3d-b2de-3fd3f7068ab3">
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4193918

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 3b91b1f
