### ISSUE TITLE
UI balance buttons on bridge page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1615]
### Description

Can we balance the height, width, and sizes between these three buttons?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8abfd7f3-f178-4d24-8489-91c9c23cae81)

**Comment by mohamedamer453** [comment]
The height, width and the sizes of the buttons are now balanced.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/75eba2b6-baf4-4b2d-ad19-56ed9b5288ad)
