### ISSUE TITLE
Can't add public configuration to my node

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1618]
### Description

Devnet, 2d54818.

I can't add any public configuration to my node and keep getting this error.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/86b3436c-4ca4-46a7-a932-f712bb0f2fb1)

And also the error message must be more clearer to the user!

### Steps to reproduce

1. Connect your wallet (your account must have a node).
2. Navigate to the farms by expanding the dashboard from the sidebar.
3. From your node table, click on Add public IP from within your node.
4. Fill in the input and press save.

**Comment by ramezsaeed** [comment]
Ipv4 should not be the same as the gateway

**Comment by coesensbert** [comment]
and should be in the subnet mask range because of on-chain validation

**Comment by AlaaElattar** [comment]
### Work Completed 
- Added condition to check they're different before sending the request.

**Comment by AlaaElattar** [comment]
### Work Complete: 
- The error msg was triggered at wrong cases and that is fixed now.

**Comment by A-Harby** [comment]
Verified,
Devnet 33c308d.

[TC2218 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150427)

The same IP and gateway validation were added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ca991f29-2e24-49ee-b6d6-18af01a79bdd)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f9fb5cd3-c972-4530-8e08-c2543a4c574d)

After fixing the wrong input, IP was added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/27b83e3e-2d83-4fd9-8bc2-6e83cd09493d)
