### ISSUE TITLE
Show error when one of the IPV6/Gateway input is empty

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1619]
### Description

Devnet, 2d54818.

When adding IPV6 to your public config, the user must add both IP and gateway, not just one of them.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b52ba290-71fd-454e-b392-46fb3c192cb5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5f25bb9d-e1f3-4a04-ac69-c2134aba5fde)

**Comment by mohamedamer453** [comment]
Issue was resolved on devnet `e3e188c` and now when one of the fields is entered an error appears in the second field until it's added.

[Screencast from 06-02-24 11:39:10.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/65573574-8141-49c6-a8f3-47dfc7dbc573)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
