### ISSUE TITLE
If the input is invalid, don't make a request 

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1621]
### Description

if the input is invalid, a request is made to validate the manual node Id which shouldn't be the case

[288754910-2eaf062b-d427-482c-9e2e-1986d1a707e5.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/d11fd11f-f4f1-4284-bdda-5c0d7c4acdf9)

**Comment by maayarosama** [comment]
Blocked on refactoring select node component

**Comment by A-Harby** [comment]
Verified,
- Devnet
- ec2ed3d
- [TC2439 - Input validation doesn't send requests](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422335#case_4163091)

The wrong input in any of the resources or any solution doesn't perform a request.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc304992-d4bb-4e63-9dd9-883e710669c7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da58dfd6-7265-46da-b37f-d576e11dd29a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7fafe55f-a86e-494b-9e01-345ab6a899be)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/75f46c72-40c9-46cf-aca5-573f2ea1f163)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
