### ISSUE TITLE
Lerna build is failing

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1624]
### Description

I can't build a playground without having this error; just do yarn install and yarn lerna run build.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1be1ad94-1008-4464-8ca1-76585cb886e0)

And this command solved it: `export NODE_OPTIONS="--max-old-space-size=8192"`.

**Comment by ramezsaeed** [comment]
please update docs for node options needed.

**Comment by A-Harby** [comment]
Verified,

Docs updated.
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/README.md
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/README.md
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b949bae2-448b-4082-bae8-d66896085d8c)
