### ISSUE TITLE
Change manual link to be visible to the new user 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1625]
### Description

The manual link is not visible to the new user, while the main purpose of the manual is to help the new user get started.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ae59ae5e-32d9-4967-916c-8f2e8e7231ae)
It's only shown to already-signed users.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4b05cbe3-eca2-4da5-9f03-a93a3fa6c98a)

**Comment by A-Harby** [comment]
Verified,
Devnet, d9d6f02

Manual link is now displayed in both tabs.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/276b3ea4-00b3-4391-9229-d3f026ccae32)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
