### ISSUE TITLE
Grid Client won't disconnect with the use of `connect()`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1627]
- I've tried this script and the client won't disconnect, after typing `disconnecting` will try to connect again then stuck.
```bash
import { getClient } from "./client_loader";

async function main() {
  const grid3 = await getClient();
  grid3.clientOptions.deploymentTimeoutMinutes = 2;
  await grid3.connect();
  console.log("Hello");

  await grid3.disconnect();
}

main();
```

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/4bd5c9e7-3427-42a7-ba90-471773e234c2)

**Comment by AhmedHanafy725** [comment]
Work Completed:

there is an event handler that restores the connection to tfchain in case the connection fails for any reason. this handler has a signature that changes when creating a new instance from the tfchain client. when the user calls the connect method on the grid client, it creates a new client from tfchain, and this is what breaks the signature of the event handler. So to fix this, the handler is stored beside the api on the tfchain client to be able to remove it from the api when trying to disconnect the client.

**Comment by A-Harby** [comment]
Verified on devnet [da46d82](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/da46d82076f4e3f7b66a72adf958d5ae2d65b5c2),
 
I tried the same code, and it worked fine with no errors.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2288863d-87d0-4313-84ff-21f1e175051b)

The code was originally made to test some functionality in the mass deployment workflow, but it was fixed, and the workflow is now working fine.
