### ISSUE TITLE
Add a link to the contracts page in the grace period contracts warning message

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1628]
### Description

The warning message for contracts in grace period doesn't redirect the user to the contracts page unlike the message for contracts on offline nodes. so it should have a link for the contracts page for the sake of consistency.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2ffc8f9a-4935-4748-8125-94d2dcc7c17d)

**Comment by A-Harby** [comment]
Verified on Devnet.

A link was added directing to my contract page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/14b2b5e5-8c48-4bbe-9a90-1eeb97d47325)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
