### ISSUE TITLE
Improve ux for select node in all solutions

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#1630]
We're dealing with a single form in all solutions right now which not allowing us to disable `<SelectNode />` if user entered some invalid data.

todo:
- Move `<SelectNode />` into it's own form and allow to disable it based on other form's validation value

**Comment by khaledyoussef24** [comment]
verified
select node has it's own from now
automated and manual
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/43e4370c-d121-4fa5-97c5-558ca8d2dec0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9509f5b5-0783-4015-b4b4-67e7cb94f012)

in the automated selection load node button is enabled when the user insert new data or change specifications 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b86fb526-5499-4779-ae96-00e88453f21a)

testlodge:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4164692
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4164673

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
