### ISSUE TITLE
Double requests when searching a farm

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1635]
When searching for a farm, the request is done twice.

**Comment by A-Harby** [comment]
Devnet, 9e7fa15.

It still does request the farm twice, and the only difference I found between them is the endpoint `ret_count`, one is sent empty and the other is true.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/340680e7-958a-41aa-b1b0-e616a9dc6f3c)

### Step to reproduce:

1. Navigate to the dashboard.
2. Connect your wallet.
3. click on Solution
4. Select FullVM.
5. Open network.

**Comment by MohamedElmdary** [comment]
@A-Harby I think issue doesn't related to initial loading of farms because initial loading requires  2 requests . 1st for count and 2nd to load a random page

for searching you need  to write in farm input and it will issue a debounced request with your query

**Comment by A-Harby** [comment]
Verified,
Devnet 760289d.
When searching only on request is being done for the search, and beside on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1635#issuecomment-1872922018 the inital loading should do 2 requests and thats normal.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2f5db27-b0c1-42cb-93d5-e65dfd02bde2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7b66ea4f-ee90-4138-a100-4c479e2f6878)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
![Screenshot from 2024-01-01 12-39-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0614125e-8743-4d42-9807-1e61ea91ad60)
