### ISSUE TITLE
Error canceling contracts on the dashboard

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#1636]
### Description

Canceling contracts on the dashboard that was canceled somewhere else returns an error `Cannot read properties of undefined (reading 'resultSections')`

### Steps to reproduce

- Create any contracts.
- Open the dashboard and list the contracts.
- Cancel a contract using any tool other than the dashboard (polkadot, ts-client, etc..)
- Try canceling the contract on the dashboard, it should fail.

### Logs/Alerts
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/232d2807-8e04-4491-bf04-b5507204556f)

**Comment by A-Harby** [comment]
Verified,
Devnet, 0b2f0d3.

I tried deleting it from Polka, and the contract listing worked fine. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b3c205df-2f14-4b54-81a7-3ed3f6e437b5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c48e65c-4081-4e15-9fc3-e2db52510745)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5bb3d5a0-02fb-4099-a5ad-f862e65f9372)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f128da6d-dfff-420f-9eb3-88c827a8dc74)

**Comment by A-Harby** [comment]
I deleted the contract from Polka.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da63fdea-49c2-46fe-8f5b-eb23d21e5dd2)
Then I deleted the same contract from the dashboard.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ea0afe3-1346-4380-abcc-2a5b5b59dc89)
Both deletions were successful with no errors, just like listing the contracts.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/943af4fa-ff21-4442-ae35-d820beefb90c)

Updated test case to apply same concept [TC2318 - Delete deployment elsewhere.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4156837)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 13a87cf
