### ISSUE TITLE
Error message for network issues need enhancement

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1641]
### Description

The error message for this kind of network error used to be better than this, telling the user to try again or contact support instead of the last part of the error, which isn't user-friendly.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/59e45da8-8e45-45e0-9fa5-8261a9e6fedc)

**Comment by A-Harby** [comment]
Verified, 
Devnet, d9d6f02

Error messages are improved to be more user-friendly.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/09db035f-9b24-45af-9ba4-2bdfe77e5adc)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
