### ISSUE TITLE
Change button name at unreserve 

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1642]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/396b8426-1bbe-4bdc-a9a9-e48b862c842c)

I think the buttons here need to be Confirm(red color)  & Cancel (white color)

**Comment by ramezsaeed** [comment]
take care that "Are you sure" question,
the answer must be be Yes or No

**Comment by ehab-hassan** [comment]
@ramezsaeed I Agree with so let's change the question to "Unreserve this dedicated node?"

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6e8ddf24-150a-436b-a9a8-dd3018845e1a)

**Comment by A-Harby** [comment]
Verified,
Devnet, f4978d7.
[TC2223 - Unreserve a dedicated node](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150432)
Style changed and functionality work fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c25e9c23-be19-471f-a16b-98d3b2d4b40d)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
