### ISSUE TITLE
Make all buttons consistent 

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1643]
make sure all buttons consistent in design and color

**Comment by ehab-hassan** [comment]
To make all buttons consistent
- we ll use primary(filled) and secodery(outline) colors for main action 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d8629ef0-a050-4090-bdf0-475df7840553)

- ll use error(red) color filled or outlined for alert , cancel, confirm delete delete (any action need to alert the user)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/36ac4425-9ee2-4a5d-b487-6cd72f6ac244) 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/0ff0235f-dd31-4cfe-bbd7-5c77bfd4a795)

- ll use white for normal action like Close, Clear, Export
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/7d57e430-c182-498b-a344-1dea545a67dd)

- I don't recommend tonal effect in color not good at light mode
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1af206f7-dbd0-405b-8292-b10472eb1c9f)

**Comment by ehab-hassan** [comment]
Work in Progress

**Comment by ehab-hassan** [comment]
all buttons inside the dashboard (Yor Farms - Your Contracts -Bridge _transfear- Deedeacated Nodes -DAO) are finished with all pop-ups sections inside

**Comment by ehab-hassan** [comment]
all updated
replace all tonal with outline button 
some button with background color if it important action need from user
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a807269d-b459-43fb-be6a-213658bf8e03)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/adcf6eaa-3b6f-41c9-8899-d74a0193f081)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b2c08187-a33a-4b38-ac57-6c9fcad799c6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/beb4f219-087f-4268-bd2c-e7cf25bc488d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/89418dc0-f0a6-421e-9977-1933689b3ea6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/abaccb1a-0581-4e74-8666-d64da33f0d4a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b4619960-7ee3-44d9-900f-d6ce9f20d877)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/bd783202-3752-45cb-b495-95944f57c211)

**Comment by khaledyoussef24** [comment]
verified all buttons now changed
environment used : devnet
![Screenshot from 2024-01-01 09-59-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1e4adfb-087b-4ec7-8e28-5a7cb0f0479b)
![Screenshot from 2024-01-01 09-59-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/47b6846c-4b80-4e98-9e96-4ff9d1fb88d9)
![Screenshot from 2024-01-01 09-59-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9fc957c2-53a1-477e-b0e8-563c35179885)
![Screenshot from 2024-01-01 09-58-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c76182b4-9f66-499e-997c-0dc8927bad70)
![Screenshot from 2024-01-01 09-58-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d1de5692-bfb8-4436-b23c-4cddcc6a84c4)
![Screenshot from 2024-01-01 09-58-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06487c5b-8e82-4edf-ac78-bed29213beb3)
![Screenshot from 2024-01-01 09-58-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f74c1040-733d-4c4f-9d6e-0b31bc9b196d)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
