### ISSUE TITLE
Phase out old Stats

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1646]
Since new Stats is now deployed on https://stats.dev.grid.tf/ we need to remove old Stats.

**Comment by MohamedElmdary** [comment]
We need to rename `new_stats` to `stats`

**Comment by khaledyoussef24** [comment]
verified statically `stats` is removed and `new_stats` is renamed to `stats`

**Comment by khaledyoussef24** [comment]
https://stats.dev.grid.tf/ is working fine with latest updates.
<img width="1680" alt="Screenshot 2024-03-26 at 2 17 53 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6d762437-cbc9-43ac-ad50-9a49452bb386">
