### ISSUE TITLE
Include alpha releases in publish workflow

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1649]
Alpha releases need to be included in the workflow as well as the edge release.

**Comment by A-Harby** [comment]
Verified,

The [workflow](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/1bad0b632f3957c51bb4fe8729ebd1e92a8f7743/.github/workflows/publish.yml) condition was updated to include alpha for RC releases.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/80a9f148-76e9-4e72-95cd-5b405217fd4e)
