### ISSUE TITLE
(Mainnet) Display Default Information for Unresponsive Nodes in New Dashboard

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1651]
### Description

**Current Behavior:**
The new dashboard shows an error message with buttons to re-request the node when it doesn't respond, as seen in the provided screenshot:

![Error Message](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a2f885c0-fef9-46f6-89c2-75d0203ceb9f)

**Desired Behavior:**
The old dashboard displayed the node details with default values for the stats and hid the node deployments/workloads and GPU cards when a node didn't respond, as shown in the provided screenshot:

![Default Node Information](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/9878bebb-6404-4e87-ba50-c0c032fca998)

**Comment by Mahmoud-Emad** [comment]
It's possible that this issue arises because we currently retrieve the load statistics directly from the node in real-time through a request. If the node is unavailable, the request fails, resulting in a display of "NA." To address this, I propose that we continue with the current request approach, but in cases where the node doesn't respond, we should fallback to loading the statistics from the grid proxy instead of displaying "NA." This ensures a more seamless and reliable display of information even when individual nodes are temporarily unreachable.

**Comment by Mahmoud-Emad** [comment]
### Issue Update 

Enhanced the node details page by dynamically fetching node information from the grid proxy, eliminating error displays. Additionally, introduced a warning alert to notify users when the node seems operational but is physically offline—possibly due to entering an offline mode. This enhancement aims to provide a more seamless user experience and informative feedback on the node's status.

PS: The changes related to this enhancement are included in [this pull request](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1701).

Note: Unable to reproduce the errors related to loading cards; testing is required on another node containing a GPU card that appears as 'online' but is physically 'down'.

**Comment by maayarosama** [comment]
1. Work Completed:
- Removing N/A in node resources when the node is unreachable and added the resources returned from grid proxy

2. Work in Progress (WIP):
- Adding an error message and a refresh button in case of failure of retrieving gpu when node is unreachable
3. Investigation and Solution:
- when node is unreachable the offline chip and warning disappears on opening and closing node details dialogue multiple times

**Comment by maayarosama** [comment]
Work Completed:
- Added an error message and a refresh button in case of failure of retrieving gpu when node is unreachable

Work in Progress (WIP):
- retrieving the gpu details when the refresh button is pressed
- when node is unreachable the offline chip and warning disappears on opening and closing node details dialogue multiple times

**Comment by khaledyoussef24** [comment]
verified
env used : devnet
version : 2.3.0-alpha3
displaying the information for nodes (up,down and standby)  is working fine.
show health button is working fine also.
can not test the gpu options so will wait until main net release to verify.
![Screenshot from 2024-01-02 15-34-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/feaab648-f0c5-448d-a633-6cc719b9161b)
![Screenshot from 2024-01-02 15-34-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ceb2bc6c-611b-4b4f-b11f-2f99654c87e6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c289c27e-54a3-4974-a3c8-dbbd149b7eba)

**Comment by khaledyoussef24** [comment]
also verified on :https://dashboard.bknd1.ninja.tf/#/deploy/nodes?nodeId=14
displaying the information for nodes (up,down and standby) is working fine.
show health button is working fine also.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/559f3796-dde2-4b8b-b8d8-7d14eeae807d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/176e8d1f-8b5a-4642-9587-4d71dc20f8ce)

the gpu option
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/77385f6a-85eb-4a14-9d2f-a4345163078c)
