### ISSUE TITLE
Separate `AddIP` component from inside `PublicIPsTable`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1662]
- To make enhancements in page `My Farms`, we need to change `Add IP` button location but it's a component inside another component so they should be separated to make page looks better.

**Comment by AlaaElattar** [comment]
### Work Completed: 
- `AddIP` is separated from `PublicIPsTable` component.

**Comment by A-Harby** [comment]
Verified,
- Devnet.
- 5a1b57a
- [TC2207 - Add IP to Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150416)

The IP component update was done, and the add IPs functionality is still working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/569b6980-89f3-4adb-8356-f902b4447a06)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6fb7f5be-9e07-4880-bef5-7dcf8a53c37c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f1afd272-cbd8-44d3-942b-4ab0efaf939d)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 13-42-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/278508d2-fa3a-4732-9e1f-7fb19d448fc5)
