### ISSUE TITLE
CapRover Docs Link Update

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1664]
The link to the CapRover documentation should be updated:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/e69c746d-9896-478e-86ce-8f04b7530096)

Quick start documentation link leads to this: https://manual.grid.tf/weblets/weblets_caprover.html?highlight=caprover#caprover

But it should lead to this: https://manual.grid.tf/playground/caprover.html

**Comment by Mik-TF** [comment]
Fixed in #1676

**Comment by khaledyoussef24** [comment]
verified 
environment used : devnet
the link now leads to
https://manual.grid.tf/playground/caprover.html
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b662ad94-51db-4fc2-80b8-d14d05927f3f)
testlodge:
https://app.testlodge.com/a/26076/projects/40893/suites/234374

**Comment by Mik-TF** [comment]
Thanks! @zaelgohary and @khaledyoussef24 
Closing the issue.
