### ISSUE TITLE
Weird Behavior in `Add a public config` in my farms page  

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1668]
### Description

 There's weird behavior as its seen below in the validations.
Why when i type in IPv4 gateway validation is working ?

[Screencast from 12-12-2023 12:05:13 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/4ae9ec23-4758-4bac-84f4-af4b8c73d5fe)

**Comment by zaelgohary** [comment]
All validation is triggered if one input is being validated.

**Comment by AlaaElattar** [comment]
- It's not actually an issue, it's implemented like this for a reason.
- ipv4 & gw4 are a must in form. I can't submit any input unless they're full
- if ipv4 triggered -> gw4 should be too and vice versa
- if ipv6 triggered -> gw6 should be too and vice versa
- domain optiona
- This explains the behavior of the form.

**Comment by 0oM4R** [comment]
should we trigger the validation if the other value is valid only ?

> * It's not actually an issue, it's implemented like this for a reason.
> * ipv4 & gw4 are a must in form. I can't submit any input unless they're full
> * if ipv4 triggered -> gw4 should be too and vice versa
> * if ipv6 triggered -> gw6 should be too and vice versa
> * domain optiona
> * This explains the behavior of the form.

**Comment by AlaaElattar** [comment]
### Work In Progess (WIP):
- Working in that comment https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1668#issuecomment-1860253027

**Comment by AlaaElattar** [comment]
### Work Completed :
- About ipv4 && gw4 as both are must i think they should be both triggered once user types at any one.
- same for ipv6 and gw6, excepty they're not a must untile they come together.
- As long as the button is not enabled until all are valid, i don't see this will make a difference https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1668#issuecomment-1860253027

**Comment by A-Harby** [comment]
One case is not fixed yet: when any other input is being typed and validated and there is already a wrong validation on the other inputs, all of them will be affected and revalidated.

[Threefold Dashboard: Your Farms.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f3e0a37e-2106-4cf1-ab0e-e1c32bcd0668)

[Threefold Dashboard: Your Farms (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/16a410cf-1595-468d-b16f-068e45a9b5d3)

**Comment by AlaaElattar** [comment]
### Investigation and Solution:
- after investigation, we can't choose specific field to validate from inside the `formRef`, so will be handled here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1818 .

**Comment by AlaaElattar** [comment]
- Blocked until #1818 is done.

**Comment by A-Harby** [comment]
Beside on the comment this issue is fixed and weird reverifying should be fixed on an other issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1668#issuecomment-1870426179.

[TC2216 - Add Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150425)
