### ISSUE TITLE
Input validation for the TFT decimals amount in the transfer page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1670]
### Description

Devnet, df55f97.

Transfer TFT in both by twin ID and address; when the number of decimals in the amount is large, it gives this error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e386c674-4f4c-4d96-ba1d-90cbc68343a1)

The old dashboard had a 3-decimal-digit limit for validation to prevent this kind of error.

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2


![Screenshot from 2023-12-25 14-38-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/736a1a5f-ffb0-4b1a-8069-fe7f2419bcd8)
