### ISSUE TITLE
[Grid Client] need to delete the key in finally <if the connection failed> 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1672]
The `validateMnInput` got triggered twice, first time, the `isConnecting` was set to true and failed while creating rmb connection, so in the second time, it not create an rmb connection as the `isConnection` is true. so we couldn't even got this error for now
- need to delete the key in finally <if the connection failed> 

_Originally posted by @0oM4R in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1597#issuecomment-1851916434_

**Comment by 0oM4R** [comment]
[isConnecting_issue.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/c54b9147-87ca-4015-95de-35c162db5e72)

**Comment by AhmedHanafy725** [comment]
Work Completed:

this key is removed and now depending on the other clients to block the connect method when connecting more than once at the same time

**Comment by khaledyoussef24** [comment]
verified user now connect on low balance
[Screencast from 01-01-2024 01:03:57 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e9a89aca-f862-4799-8ca1-62c85b3962f6)
![Screenshot from 2024-01-01 13-03-43](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b025d8c-41ad-4b03-bcb9-5d8587873a4d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4d353d17-e49e-4170-a45f-bf89c09730d3)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3

**Comment by AhmedHanafy725** [comment]
this issue was to not let the user login if the connection was down. it was allowed to login if the user clicked the connect button twice (which was wrong) as mentioned in the attached video

**Comment by khaledyoussef24** [comment]
is there any way to produce the scenario?
i used slow connection and all i am getting this box shows up and the login button is disabled until the login completes
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5920c24c-c280-48da-8733-c8b08310acaf)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31971b40-b1e8-42fa-8380-bd8def39a8cd)

**Comment by khaledyoussef24** [comment]
the issue is no longer reproducible  the button gets disabled after the first click
![Screenshot from 2024-01-02 10-30-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7d422d4a-6483-44a8-9ee3-b0d99230b7bf)
or the whole page is disabled
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/724fdffc-0196-471e-894b-b29302b8a704)

**Comment by ramezsaeed** [comment]
No longer reproducible due to the new loading page of dashboard.
