### ISSUE TITLE
Loading page gets stuck when a network issue happens

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1674]
### Description

When there's a network issue, the loading page gets stuck forever.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/640f6215-f4ec-456e-a298-243b5739ca39)

**Comment by khaledyoussef24** [comment]
is not producable any more
tried it on edge connection and still loads fine but takes time
<img width="1440" alt="Screenshot 2023-12-19 at 10 34 53 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bded5574-4573-4e3e-8d60-6317861c8b51">
