### ISSUE TITLE
less fractions for the billing rate in contracts page

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1679]
maybe 3 digits is enough like the hourly one.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/ce8da927-926c-4e55-9324-47870243b247)

**Comment by zaelgohary** [comment]
Should use normalizeBalance from [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/helpers.ts#L29)

**Comment by zaelgohary** [comment]
Work completed:
Used toFixed(3) to limit decimals.

**Comment by AhmedHanafy725** [comment]
can we check if it's 0 to not do that rounding? as it will look like that
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/375b719d-99e6-49c8-bd3e-cd53643f9865)

**Comment by khaledyoussef24** [comment]
environment used: devnet
verfied now 3 decimals are only viewed
![Screenshot from 2023-12-18 13-59-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/19688639-a543-4ef4-90ee-ffde0c3e9aaf)
![Screenshot from 2023-12-18 13-59-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9af47bcd-9521-49b2-83c6-3c9fe9401645)

testlodge:
https://app.testlodge.com/a/26076/projects/40893/suites/234374

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2
zeros working fine too

![Screenshot from 2023-12-25 14-24-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/fd8cd840-8ed5-42dd-8ab3-d2558de9c390)
