### ISSUE TITLE
Add sorting to Farms & Nodes tables

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1685]
### Description

Add sorting in Your Farms to be consistent with Farms and Nodes pages. 

Just need to add sorting by Farm ID and Farm Name.

**Comment by zaelgohary** [comment]
Sorting can be done from the queries mentioned [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/350)

**Comment by amiraabouhadid** [comment]
At the moment neither nodes finder nor farms finder tables have sorting. 
Do you want me to add sorting to the following three tables?
- Your Farms
- Node Finder
- Farm Finder

**Comment by xmonader** [comment]
everywhere xD

**Comment by amiraabouhadid** [comment]
node finder already has sorting enabled, will be adding sorting to your farms and farms finder

**Comment by amiraabouhadid** [comment]
No sorting by ips available on gridproxy for farms, so just added sorting by farm id and farm name 
https://github.com/threefoldtech/tfgrid-sdk-go/issues/1125

**Comment by khaledyoussef24** [comment]
verified sorting now is working but i think the third click (which removes the sorting)shall return the table to it's original order

![Image](https://github.com/user-attachments/assets/cec40fef-288b-4a40-8524-b538226fd096)
![Image](https://github.com/user-attachments/assets/9a145f2e-c857-4b14-aa56-a5e0cb94984c)
![Image](https://github.com/user-attachments/assets/1d57b9eb-58bb-4284-a224-edfefe1c1708)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : cddbd85

the third click now returns the tables to default


![Image](https://github.com/user-attachments/assets/aaa11c3b-f3f5-4b4c-b64c-71653b5e846a)
![Image](https://github.com/user-attachments/assets/f70b5838-2c38-448b-9c85-bbe970f54141)
![Image](https://github.com/user-attachments/assets/e53d8955-b53e-474d-9059-1312129bed0c)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150463)
