### ISSUE TITLE
Farm Name input validation

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1686]
### Description
Devnet, 28d6c07.

Adding farm input validation will prevent this error message.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/836ca834-b6fa-480f-a10a-6632d6573b08)

The old input validation for Farm Name was [maximum 40 ascii characters, no spaces, only -, _ are allowed as special characters]. I don't know if it was changed or not.

**Comment by zaelgohary** [comment]
Check validation in tf chain and same validation should be applied here.

**Comment by amiraabouhadid** [comment]
Investigative work:
looked for validation on the tf chain

**Comment by amiraabouhadid** [comment]
fixed: 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/356d908a-2e4b-4ed4-bb4a-8de4f16e2b49)
![Screenshot from 2023-12-17 16-36-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/66ab1d7f-28fb-4f46-8304-bbb44907f125)
![Screenshot from 2023-12-17 14-06-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/812d6bc4-a657-4f3c-b196-b26c006b2459)

**Comment by A-Harby** [comment]
6d0ec3d
Not released yet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/34157b4c-f042-4f0b-b402-1a306d7ec79d)

**Comment by amiraabouhadid** [comment]
moved back to pending review, was put in verification by mistake

**Comment by A-Harby** [comment]
Verified,
- Devnet
- e2580a5
- [TC2241 - Farms Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150450)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7b7100c5-a055-452f-a5fd-ace08f23f498)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/92197312-3c6f-44c7-97e2-118cf2a1e051)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/294e3f12-ecdc-461e-8fe1-369109948047)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/90d6c4ab-1dae-496d-b65a-737a03d9fd2d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a7cd7846-3d2a-4b08-9eb3-9c0e65689d34)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- ebf75a3
