### ISSUE TITLE
owncloud action buttons not appears

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1687]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/750e0153-3181-4031-90df-393af5e9e2aa)

After deploying an owncloud instance in the deployment list, you can see the action button has disappeared.

### Logs/Alerts
```
index-574de645.js:6 TypeError: Cannot read properties of undefined (reading 'env')
```

**Comment by zaelgohary** [comment]
Issue may happen in other solutions.

**Comment by zaelgohary** [comment]
Work completed:
- Edited the href to be item.value.env.hostName instead of item.value[0].env.hostName

**Comment by khaledyoussef24** [comment]
verified 
enviroment used : devnet
<img width="1137" alt="Screenshot 2023-12-19 at 9 50 07 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ce3b7a29-2cb7-4335-96ee-f98e53c4c924">
testlodge :https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150346
