### ISSUE TITLE
Farm details dialog is so wide

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1688]
I think this dialog should be smaller

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/7f956bd8-0f06-4e42-9ff3-7afd95be97b2)

**Comment by zaelgohary** [comment]
Should include a minimum width and be responsive on smaller screens.

**Comment by zaelgohary** [comment]
Will be closed as it'll be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1692
