### ISSUE TITLE
Close the add ip dialog after adding the IP

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#1689]
### Description

The add IP dialog stays open after successfully adding an ip.

[Screencast from 13-12-23 16:38:28.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3211f636-fad9-4226-8715-56c6a218313f)

The dialog should be closed after successfully adding an ip/ip range

### Steps to reproduce

- Navigate to the dashboard and login to your account.
- from the sidebar select Dashboard then  Your Farms
- Click on one of your farms then click on add ip.
- Enter a valid ip then click on add.

**Comment by khaledyoussef24** [comment]
verified on devnet now the ip dialog closes after finishing 

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d4bffe33-c493-4a4a-b22e-972524bd2d76
