### ISSUE TITLE
Activate button doesn't get enabled

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1690]
[activate_btn.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b376e8c0-f790-41cc-8f41-53d695093fc3)

**Comment by khaledyoussef24** [comment]
it did not work with me 
took more than 10 mins loading and no response
<img width="865" alt="Screenshot 2023-12-19 at 10 44 39 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5afec3e5-ac54-4ee1-8627-b90d12050275">

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1665

**Comment by zaelgohary** [comment]
Should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1742#pullrequestreview-1790669763).

**Comment by khaledyoussef24** [comment]
verified and fixed 
[Screencast from 12-25-2023 01:37:56 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/54ad367c-e6a4-4330-b532-9df2862390c8)
user now can activate a user after generating mnemonics on polkadot extension

testlodge:https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4161528

**Comment by khaledyoussef24** [comment]
the same issue exists again
![Screenshot from 2024-01-01 13-01-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f1c1e7d7-c4c9-4f5d-8500-38940f993548)
[Screencast from 01-01-2024 12:37:26 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a2bb3efc-fdb1-4a4f-99c6-d9fedfdd32c2)

**Comment by 0oM4R** [comment]
Work completed: all logic done should works fine now, the new method will determine if the account should be activated or not based on the `TwinNotExistError`

just need to test some edge cases to make the pr ready for review

**Comment by khaledyoussef24** [comment]
env used : devnet
version used : 228c723
verified now user can log in and activate account from mnemonic and hex seed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31b5b19f-14ff-4354-82f9-623ead179df1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bbfad00c-793d-4b73-a6f9-22143d8d10f2)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4161528

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d
