### ISSUE TITLE
enhance list requests in data tables 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1691]
### Description

Currently, we are adding `ret_count` to every request on the table, which effects the performance, so if there is no change in the parameters, there is no change in the total count, and there is no need to make the requests heavier with ret_count.
  

### Implementation

we can get the total count on_mount and on any change of filters or delete\add actions

**Comment by khaledyoussef24** [comment]
verified on devent dashboard node finder that the request is made.
verified also on gridproxy using swagger `ret_count` is found and enabled as a default(set as true).

swagger:
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/088962c3-8d62-469f-a5de-818829b3471c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2e6f8806-a83c-4ea2-92c5-d74efbb46628)

[gridproxy](https://gridproxy.dev.grid.tf/nodes?page=1&size=20&ret_count=true&sort_by=status&sort_order=asc):


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5003e8c7-9818-4ac3-af7b-236fd6a2c674)



dashboard:
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6943e218-73f1-43e4-99f2-c88cf4e5130f)
