### ISSUE TITLE
Add Vuetify defaults 

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1692]
https://vuetifyjs.com/en/features/global-configuration/

**Comment by MohamedElmdary** [comment]
related https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1219

**Comment by samaradel** [comment]
### Work in progress:
Component default has been added for the ```button```  and the ```card```

**Comment by samaradel** [comment]
### Work in Progress (WIP):
@ehab-hassan had some comments on the components, will discuss it tomorrow in a meeting

**Comment by samaradel** [comment]
### Work in Progress (WIP):
Cards actions updated as per discussion with @ehab-hassan

**Comment by samaradel** [comment]
### Work Completed:
vuetify default values applied on all components

**Comment by samaradel** [comment]
### Work Completed:
vuetify default values applied on all components
