### ISSUE TITLE
The public keys generated for the twin by the mnemonic and its seed are different

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1694]
same as https://github.com/threefoldtech/rmb-rs/issues/181

it's happening here 

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/14a9eafa5b722c88d5653acc717a3f97da3c9d36/packages/rmb_direct_client/lib/util.ts#L20

**Comment by khaledyoussef24** [comment]
is there a way i can verify this ?

**Comment by AhmedHanafy725** [comment]
### Verification Steps
- Create an RMB client using your mnemonic then connect it. (you can check the example script in the RMB direct client)
- Check the pk field on your twin on TFChain.
- Get the hex seed of your mnemonic.
- Use the hex seed to create an RMB client instead of the mnemonic then connect it.
- Check the pk field on your twin on TFChain again (it should be the same).

**Comment by AhmedHanafy725** [comment]
already verified and the pk on the twin doesn't change
