### ISSUE TITLE
Show mnemonic in profile manager instead of Hex seed

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1696]
![Screenshot from 2023-12-14 14-30-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/04b6d5bd-810e-4013-b82b-015598cb03fd)

**Comment by khaledyoussef24** [comment]
enviroment : devnet
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4d71163f-d1a4-4b2b-bb93-f9d42c38f15b)

test lodge: https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155957

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2
