### ISSUE TITLE
[Direct client]  update tsconfig-node file 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1698]
![Screenshot from 2023-12-14 14-43-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/8b78cf17-a4b9-42ff-9257-895a48fe05ea)

but when I used the configuration of the grid client it works fine

**Comment by AhmedHanafy725** [comment]
config updated and the script is working
