### ISSUE TITLE
Create twin script logs says that twin have a pk while proxy says not.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#17]
### Description

The create twin script is working correctly but logs says that twin have a pk while proxy says not.
https://github.com/threefoldtech/grid3_client_ts/issues/512

### Steps to reproduce

use create_account.ts

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/223936995-c3a1776c-694b-4268-8bc7-071eb8b4fb7d.png)
![image](https://user-images.githubusercontent.com/109473873/223937012-acdc0794-635e-4ae3-b310-02e1e2584a18.png)

**Comment by xmonader** [comment]
can this be closed now?

**Comment by A-Harby** [comment]
Closing issue, PK is automatically update with RMB.
