### ISSUE TITLE
grid_client tests are failing

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1702]
* The [grid_client tests](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/grid_client_tests.yml) are all failing
* Please remove or redirect if needed.
* The first mention of this that I know of what in [this issue](https://github.com/threefoldtech/info_grid/issues/138)

**Comment by zaelgohary** [comment]
Duplicate for https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1673.
