### ISSUE TITLE
Wireguard ip doesn't appears on deployment list table 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1716]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/6ea184cf-5c32-4776-83aa-99780fd5485b)

but if we open the deployment details:
![Screenshot from 2023-12-18 08-41-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/75dfb73c-5f99-4d53-9cb5-7968270db4da)

This happens on VM, Full VM, and Umbrel, not sure if there are any other solutions affected by this bug

**Comment by khaledyoussef24** [comment]
verified
env used : devnet
wire guard ip is now appearing in the deployment list
<img width="1440" alt="Screenshot 2023-12-20 at 1 09 14 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6d4f82f7-b125-4c8f-9d1b-7583e9c013a9">
<img width="117" alt="Screenshot 2023-12-20 at 1 09 21 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2a25c6e5-f7d9-47a6-9969-2d6d84382a14">

testlodge:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4157424

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
