### ISSUE TITLE
Explorer node detail not working 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#1717]
### Description

On dashboard.grid.tf/explorer/nodes

### Logs/Alerts
![photo_2023-12-18 09 07 35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31733464/f76fe03b-4054-4e00-81a3-1a69104b2478)

**Comment by AhmedHanafy725** [comment]
It works fine. The error says that you can't reach https://graphql.grid.tf/graphql, is it accessible for you?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/a1b7a5f5-6acc-47e3-b6c5-726c2a28017d)

**Comment by sabrinasadik** [comment]
Yes I can reach it, issue was escalated to me by Dylan. I asked him, awaiting his response.

**Comment by ramezsaeed** [comment]
please re-open if still exists.
