### ISSUE TITLE
Kubernetes: got a deployment error after a successful deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#172]
### Description

After deploying a kubernetes cluster i got the following error even though the cluster was deployed successfully.

```
Failed to deploy K8s. Please contact our support with the message 'Cannot read properties of undefined (reading 'data')'.
```

![image](https://user-images.githubusercontent.com/101194226/233061244-a653fa4e-81f5-4c4b-9a39-0e6f87d64695.png)

Everything in the cluster is working fine and i was able to ssh to the master and workers without any issues and executing `kubectl get nodes` in the master returns that the status of all workers is `Ready`

![image](https://user-images.githubusercontent.com/101194226/233062479-17f6d893-7056-4471-b110-791a153420eb.png)

Deployment Details: https://gist.github.com/mohamedamer453/2462e7b4217f7998405de44312c04b27

### Environment

- Network: `Devnet`
- Weblets Version: `830c472`
- Gridproxy Version: `v1.8.0-rc2`

**Comment by A-Harby** [comment]
Verified on Devnet,
Tried to deploy multiple instance of the Kubernetes master and error wasn't reproduicble,
![image](https://user-images.githubusercontent.com/109473873/235353044-f3d2a40c-da81-4c45-86a0-037477ad0007.png)
