### ISSUE TITLE
Adding CPU filter to farm page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1724]
### Description
Devnet, 13a87cf.

Why isn't there a CPU (CRU) resource filter on the farm page?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/29dda3df-7851-4a69-849e-92be65d26553)

**Comment by scottyeager** [comment]
It's also missing from the node finder.

**Comment by MohamedElmdary** [comment]
We should add this filter in `node finder`

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85

cpu filter is now added

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/73683c1d-a771-4795-b6d0-a9776460427d)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4243812

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622

OLD
![Screenshot from 2024-04-01 00-07-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a4a69d4b-9118-4734-b743-727408c37c4e)

New
![Screenshot from 2024-04-01 00-07-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/49be10fe-6502-4bd7-b1d8-4a6c05572936)
