### ISSUE TITLE
Decimal validation on the dedicate node resources filters

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1725]
### Description

Devnet, 13a87cf.

Dedicate node table filters: entering a decimal number with more than 1 digit doesn't filter or give an error.
This applies to all the resource filters on the page, too.

[Threefold Dashboard: Nodes.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1758f495-a7f1-43db-b125-13f490fd0e92)

**Comment by ramezsaeed** [comment]
![Screenshot from 2023-12-21 14-22-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/914118d6-5088-458b-b5fe-01a250720907)

**Comment by khaledyoussef24** [comment]
verified now decimal validations works well with dedicated node 
![Screenshot from 2023-12-26 13-24-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1f6a131c-d3ec-4380-88ac-2374e4a4ff61)
![Screenshot from 2023-12-26 13-23-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c9fb9acf-cc7e-427b-ad8c-f691661df939)

testlodge :https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422335#case_4162539

**Comment by ramezsaeed** [comment]
Verified:
- DEvnet
- ec2ed3d

![Screenshot from 2023-12-27 12-16-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/45c67255-e646-4291-b868-860cda18396c)
