### ISSUE TITLE
`Explore ThreeFold Grid Capacity` button leads to not found page.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1729]
[Screencast from 12-19-2023 10:56:43 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/4e1e66ca-2727-4495-ab54-83280614a356)

**Comment by AhmedHanafy725** [comment]
this has been solved on #1589

**Comment by AlaaElattar** [comment]
> this has been solved on #1589

Yes, u're right.
