### ISSUE TITLE
More enhancement for the mass deployment script

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1731]
- use `Promise.allSettled` 

as `Promise.all` will reject once one of the promises is rejected, so we don't need to stop the deployment if that happens, just report that they are failing and continue with the succeeded ones. 

this should be applied in the following:

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/13a87cfb8fb21aced31cd2eab5aa4f597a84fc25/packages/grid_client/scripts/mass_deployments.ts#L28

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/13a87cfb8fb21aced31cd2eab5aa4f597a84fc25/packages/grid_client/scripts/mass_deployments.ts#L157

- #1730 should also enhance the performance

**Comment by zaelgohary** [comment]
Work Completed:
Replaced Promise.all with Promise.Settled

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
- still working on fixing number of success and failed deployments, as they're not up to the total vms.

**Comment by AlaaElattar** [comment]
### Work Completed:
- counters fixed.

**Comment by AhmedHanafy725** [comment]
already applied
