### ISSUE TITLE
`IPv6` can be added to public config of node without `Gateway IPv6`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1732]
- was trying to add this to my node in `My Farms` page but that occured.

![Screenshot from 2023-12-19 11-55-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/2db2b307-1425-4dfa-b589-3008937a22dc)

**Comment by AlaaElattar** [comment]
### Work Completed :
- IPv6 and Gateway IPv6 are optional but they are must together. 
- As long as user types at any oneof them, error msg that other one is required will be triggered.

**Comment by A-Harby** [comment]
When IPV6 is entered, not only IPV4 is validated but all of them too. Was that meant?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bf8d5dbb-265e-4f1f-8d0c-3ae49d22f2e1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/69155e95-ea97-4f61-8147-7e560137d349)

**Comment by AlaaElattar** [comment]
> When IPV6 is entered, not only IPV4 is validated but all of them too. Was that meant? ![image](https://private-user-images.githubusercontent.com/109473873/293062506-bf8d5dbb-265e-4f1f-8d0c-3ae49d22f2e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDg2OTcsIm5iZiI6MTcwMzc0ODM5NywicGF0aCI6Ii8xMDk0NzM4NzMvMjkzMDYyNTA2LWJmOGQ1ZGJiLTI2NWUtNGYxZi04ZDBjLTNhZTQ5ZDIyZjJlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwNzI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmZjNzI4MjczMWQyNzc2MGFmMzQ2NjcyZmNiOTBlZWUxNTk0ZGU3OGQyN2UzMTg5NjI2ZWM0MzY3NjdlM2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p18Y5eWvj5eR1PIoJn8guPFGNm_knVkc8Qs1nGYCYOs) ![image](https://private-user-images.githubusercontent.com/109473873/293062571-69155e95-ea97-4f61-8147-7e560137d349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NDg2OTcsIm5iZiI6MTcwMzc0ODM5NywicGF0aCI6Ii8xMDk0NzM4NzMvMjkzMDYyNTcxLTY5MTU1ZTk1LWVhOTctNGY2MS04MTQ3LTdlNTYwMTM3ZDM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOFQwNzI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzU0ZTJjNzAwODdmMTA3ZDg3NzZiMjk2NzQ1Njg2ZTJhODFiOTBlZTAzYWE0ZjA5ZDM4ZDMwYmIyOWU2ODk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x-jNNpi2CkdPS9thpMSKs2mtj5nW5whOo49hX-Yl4zM)

- In all cases there should be IPV4 and gateway IPv4, If u entered anything before them they will be triggered. (base case)
- u can't add IPv6 without gateway IPv6 , so the gateway was triggered also. 
- IPv6 and gateway IPv6 are optional but should be together.

**Comment by A-Harby** [comment]
Verified, 
Devnet, 8d3e706.

[TC2218 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150427)

The IPV6 and its gateway have to be added together, and the validation will give you an error if one of them is missing.
And for the IPV4, Mandontry first needs to be able to add IPV6: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1668#issuecomment-1859975144.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7ac99585-6823-4a34-8e51-3894b5969b23)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7abc6cdd-a426-4e0e-974d-4a2066b2232d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9397b7c4-e8f1-43a7-b5ce-2b1897577afd)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
