### ISSUE TITLE
User farms not displaying even after loging in 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1733]
### Description
I am logged in but user farms is not showing 

We need a toast or something to show user the errors in the console below

### Steps to reproduce

- set network to slow 3G
- reload page
- wait until you have logged in then set network to offline then set it back to slow 3G

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/40789daf-93a8-42d1-a361-190859e3d095)

**Comment by A-Harby** [comment]
Verified,
Devnet, 93374f0.

I tried with a slower network (slow 3G) and logged in, navigation and listing were fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7930cb59-e8f0-4ef2-a52a-7b5628fb7166)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0bddea59-c40a-4c27-8da5-d915f565b96d)

And whenever I try to go offline, I get this pop-up preventing me from doing anything until the network is back.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bc7f5e1b-07fa-4d42-81e0-b58683f59dd3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/670ef559-6878-4170-8648-c118f963256a)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
