### ISSUE TITLE
feat: handle network offline/online

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#1734]
We should show a toast for user telling him connection is offline when it is and another one to tell him connection restored

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a1fa5bf4-9601-4a5d-bc4d-07907f49b95a)



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c591bac8-2f14-4cf7-9f06-c1dd760e8681

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4250319
