### ISSUE TITLE
Can't delete rent contracts in batch

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1736]
### Description

Devnet, a16e38d.

I get this error: `Failed to apply {"args":{"calls":[{"args":{"contract_id":"51,827"},"method":"cancelContract","section":"smartContractModule"}]},"method":"batchAll","section":"utility"}` when I try to delete the rent contract in batch.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/edd173e4-4da5-46f9-8e89-07fb30072232)

### Steps to reproduce

[Untitled_ Dec 19, 2023 6_40 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a432d8a4-f6c2-44ff-9f99-c3d9e95a4f6a)

**Comment by AhmedHanafy725** [comment]
After checking the error index found that this rented node has a node contract that made it fail to delete. But the error message should be clear.

**Comment by khaledyoussef24** [comment]
verified renting is working fine and functional
[Screencast from 01-01-2024 01:58:39 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e800fce-d833-4d34-b390-53dad357b5b2)
![Screenshot from 2024-01-01 13-58-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/50be702f-e719-4f22-a412-cb92e2106eb8)
![Screenshot from 2024-01-01 13-58-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/59d5f9ed-7348-42d4-adf3-893b76476772)
[Screencast from 01-01-2024 01:57:40 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/303c2865-c986-4dc8-b65b-c177563b8988)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3

**Comment by khaledyoussef24** [comment]
### verified creating and deleting rent contracts is working fine and functional 

[Screencast from 01-01-2024 01:58:39 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e800fce-d833-4d34-b390-53dad357b5b2) 
![Screenshot from 2024-01-01 13-58-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/50be702f-e719-4f22-a412-cb92e2106eb8) 
![Screenshot from 2024-01-01 13-58-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/59d5f9ed-7348-42d4-adf3-893b76476772) 
[Screencast from 01-01-2024 01:57:40 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/303c2865-c986-4dc8-b65b-c177563b8988)
in case of deleting rent contract with deployments on it
a clear error message appears
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e1f9c5e1-c382-4ee7-995c-925de3c1aa8a)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
where is the testlodge link

**Comment by khaledyoussef24** [comment]
Sure here it is
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150432

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
