### ISSUE TITLE
UI: show solutions after connect your wallet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1737]
### Description

Small fix to show solution name after view, as it does with any of the dashboard pages.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/606c6e90-5f11-4d9a-8594-0cb239c30900)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5781306f-dd2c-4600-90e9-07de3e3c73b4)

**Comment by zaelgohary** [comment]
Work completed:

Added a meta object that contains a title to the solutions route.

**Comment by A-Harby** [comment]
Verified,
Devnet, 000eea2.

The route name has been added, and the rest of the pages are still being displayed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ca0d58f-2f88-4cab-b5b8-fb9d9c224d74)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5c8fc902-4c6e-4338-b693-c8d1dcbbb463)

**Comment by ramezsaeed** [comment]
Verified:
- devnet
- ec2ed3d

![Screenshot from 2023-12-27 12-02-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4522c0f8-d7c7-4cc5-9f37-af111fee43f9)
