### ISSUE TITLE
Add the contract manual list to Your Contracts page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1739]
### Description

Add the https://manual.grid.tf/playground/contracts_list.html link to the information on your contract page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f1bdb2f7-56c0-4376-b2f5-3d63d8f8fd67)

**Comment by A-Harby** [comment]
Verified,
Devnet, 000eea2.

[TC2162 - List Deployments](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4150371)

https://manual.grid.tf/playground/contracts_list.html
https://manual.grid.tf/tfchain/tfchain.html

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0e5a763a-d33b-4611-820b-fa5a610911de)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
