### ISSUE TITLE
Remove unnecessary space before breadcrumbs

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1743]
### Description

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a402be99-2634-4529-aca5-ec8691ace6c9)

suggested fix: replace the v-container with less margin

**Comment by A-Harby** [comment]
Verified,
Devnet, fb00e24.

[TC2301 - UI component](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155453)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a03146a-ff61-4722-b85c-f68cb8d1e6b5)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2

![Screenshot from 2023-12-25 13-18-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e7c69abf-634e-43c0-8b9b-faf45685c5b8)
