### ISSUE TITLE
Infinite Grid Proxy requests in offline network

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1746]
### Description

Sometimes, when the network disconnects before the page is reloaded, an infinite loop of requests to the grid proxy keeps happening. More than 7000 requests were made in under 10 mins.

### Steps to reproduce

- Go to https://dashboard.dev.grid.tf/#/nodes or any other page that requests data from the grid proxy
- Make sure to set the network to slow 3G then offline 

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c1403ad3-93d7-4597-a658-2161aa0c5721)

Request: https://gridproxy.dev.grid.tf/version

**Comment by khaledyoussef24** [comment]
only small number of requests were made after waiting 10 minutes
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/36c9ca33-1dc2-4360-91ae-76faec6ce3e2)
i think it is acceptable now

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
