### ISSUE TITLE
Error handling in validating flist url

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1747]
### Description

Devnet, e2580a5.
When I tried to use another flist in the FullVM, I received the error `Could not find flist with the provided url.` due to a slow connection or network problems, rather than a message telling me that a network connection error occurred and to try again.

### Steps to reproduce

1. Navigate to https://dashboard.dev.grid.tf/.
2. Connect your wallet.
3. Navigate to Solutions from the sidebar.
4. Select FullVM.
5. From configuration, change flist to others.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7fba6439-2649-4c14-85b7-1ec7addf889e)

**Comment by xmonader** [comment]
Also the error message sounds to be improper and needing some rephrasing too.

**Comment by maayarosama** [comment]
Couldn't reproduce it with slow internet connection
![2023-12-24_14-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/510043fc-1c3a-49eb-acd8-29598bd3ba2b)
please add more steps to reproduce @A-Harby

**Comment by maayarosama** [comment]
> Also the error message sounds to be improper and needing some rephrasing too.

After discussions, we decidec that the current error message is the best for now

**Comment by ramezsaeed** [comment]
can't reproduce
