### ISSUE TITLE
new dashboard 'Check node health' button not functional in custom mode

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-ts#1748]
### Description
Using playground:2.3.0-alpha2 with a custom domain, at the node page the url for 'Check node health' is wrongly generated for each node.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/04e779c2-5dfd-40e4-8238-38cdbe34a569)

https://dashboard.bknd1.dev.ava.tf/#/nodes

While this works correctly at the dashboard started with 'dev' as network
https://dashboard.dev.grid.tf/#/nodes

### Steps to reproduce

- Click on a node at https://dashboard.bknd1.dev.ava.tf/#/nodes
- Click 'Check node health'

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/16a58aea71f597341f9dfba01ed9ea38c9ae5736/packages/gridproxy_client/src/modules/client.ts#L24-L31

**Comment by zaelgohary** [comment]
Work completed:
The issue happened because we used to create a new Grid Proxy instance without passing the URL. Fixed by using an already-made instance that has the URL.

**Comment by khaledyoussef24** [comment]
verified 
check node health button now opens an external url to  garfana to check the node health

[Screencast from 12-26-2023 02:32:27 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b99ca520-ff83-4ab0-a11e-62cb767d0faa)
![Screenshot from 2023-12-26 14-31-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3fccf307-4c49-48e9-8e6d-c2833451e467)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
- Test: https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4163764

![Screenshot from 2023-12-27 12-08-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/19492df8-1876-4b7a-b371-9a5609e7097f)
![Screenshot from 2023-12-27 12-07-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/94219ede-f4cc-49ff-af05-1df90cb399b6)
