### ISSUE TITLE
did not have enough balance to delete contracts but  were deleted successfully

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1749]
enviroment used : qanet
### Description

a message showing that i did not have enough balance to delete contracts but then contracts  were deleted successfully and balance changed to 0
![Screenshot from 2023-12-21 09-15-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ed2169ed-0084-4f95-9166-61158f639c1c)
![Screenshot from 2023-12-21 09-15-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6194fea4-c5a2-4eb0-bff3-7f08353c0602)
![Screenshot from 2023-12-21 09-15-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f6658cc8-0f11-435c-9c30-e2946e8fadd9)

![Screenshot from 2023-12-21 09-17-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/54aca7cd-588d-4697-9f71-82f704c15b5f)
![Screenshot from 2023-12-21 09-16-36](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/97ea605c-49f7-4d26-a52c-f39717cae985)

**Comment by 0oM4R** [comment]
I noticed that the snake bar was removed, and I think it was a mistake. I will return it.
we have balance error in types package, will check on the type of the error and only show the snakebar if it match the error type; 

this error type is on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1738 I will move this to blocked until it got merged

**Comment by khaledyoussef24** [comment]
the same issue still exists contracts deleted successfully and deducted all the tfts and they reached 0
![Screenshot from 2024-01-01 09-36-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d18ecf06-f348-4fdf-8281-58d5446b10ff)
[Screencast from 01-01-2024 09:36:28 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66c76871-da83-4f0a-b071-a8a3c40402ca)
![Screenshot from 2024-01-01 09-38-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3d0038fc-8650-4b35-b9ff-5159d004c5b7)
![Screenshot from 2024-01-01 09-38-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fb6b0b88-694a-4338-a6f6-91c9b2e78d68)
![Screenshot from 2024-01-01 09-37-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/299d1aed-047b-4eee-b583-abd66def03e7)

or this is the method which it should work ?

**Comment by 0oM4R** [comment]
yes this is the wanted flow, contracts deleted successfully, but we couldn't delete deployment caches.
want to make sure that all contract got deleted right, try to reload after few minutes please  ?

**Comment by khaledyoussef24** [comment]
Yes all the contracts were deleted and all of the balance in the wallet was deducted wanted only to make sure of the mechanism.

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3
