### ISSUE TITLE
Make the http and rmb servers able to run without setting the store secret

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#175]
the storeSecret is not mandatory now to create an instance from the grid client as it uses the mnemonic instead.

**Comment by mohamedamer453** [comment]
Verified on devnet.

After the store secret was removed in #174 i ran both servers and they are working without any issues.

- http

   ![image](https://user-images.githubusercontent.com/101194226/233356242-4936b08f-147d-40e1-9d0d-059f9c32d1f1.png)

- rmb

   ![image](https://user-images.githubusercontent.com/101194226/233357599-47f20acf-5a49-4443-87df-ded9255b709b.png)
