### ISSUE TITLE
Change the way how we get the solutions images from the HUB

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1751]
### Description

We need to avoid fixing the tags in each environment (DEv, QA, Test, Main) in case of update or add new image for any soultion.
currently if we have a defected image on the HUB; and we need to update it; we do two steps:
1- update the image on the HUB itself
2- update the tag in the playground for each Env.

### Implementation

- we can use fixed suffix on all Environments playground. (Ex. TF-Caprover, TF-owncloud)
- and we change the image name with this suffix only in the HUB.

By this we don't need to wait for the next release to have the image updated on all Environments.

**Comment by A-Harby** [comment]
Verified,
On all the networks, they are using the same latest version, and for the caprover issue, I just deployed an instance on the devnet, and it did use the latest caprover version.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/883908ee-0085-4cb2-887f-3296447ac3f0)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
