### ISSUE TITLE
password field in login turns to red after inserting wrong password in login

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1752]
### Description
the password field get cleared in changing from login to connect your wallet
but the warning is not removed
![Screenshot from 2023-12-21 11-13-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/91052793-c86b-4a35-a8dc-1834601986ac)

### Steps to reproduce

1. open the dashboard
2. insert wrong password in the login tab
3. a warning will be shown that the password is wrong
4. go to  connect your wallet tab
5. all the filed are cleared but the password filed still in red and showing password warning
[Screencast from 12-21-2023 11:14:23 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4720fbb3-b390-4a14-bdc2-31eee357e561)

**Comment by AlaaElattar** [comment]
- The issue not reproducible any more.

[Screencast from 02-11-2024 01:47:32 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/262853ec-347d-492c-bbab-5044263e112f)

**Comment by khaledyoussef24** [comment]
verfied on devnet
version: ac5cd85
the issue is not reproducible anymore warnings are getting reseted.
![Screenshot 2024-03-24 at 8 30 33 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/300051ec-7c7b-4a46-8263-c7cbe4bab466)
![Screenshot 2024-03-24 at 8 30 36 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a8d39e22-4a5a-439b-a0af-ced36b1ffab7)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4246383
