### ISSUE TITLE
feature request : making the three fold logo redirects to the home page or landing page  

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1753]
### Description

![Screenshot from 2023-12-21 12-32-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c92a2167-408f-471d-a696-b6d9dafe5610)
making the threefold logo clickable and redirecting to the dashboard home page or to user twin details

**Comment by A-Harby** [comment]
Verified, Devnet 21ef1d6.

The Threefold logo is now navigating the landing page if logged in and homepage if not.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/53883dea-f533-4be5-b5f7-4a8ae6499559)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c
