### ISSUE TITLE
Update DAO Proposals Information 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1757]
### Description

Devnet,e2580a5.

Despite the fact that this account has more than 5 farms and a node, I can't see any of my farms on the 'select a farm' list on the DAO page and am unable to vote yes or no.

I also tried different accounts, and the same happened: no farms are listed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6a0a490e-b56a-4728-a7fe-2b3e15072411)

**Comment by AhmedHanafy725** [comment]
Do these farms have online nodes?

**Comment by A-Harby** [comment]
> Do these farms have online nodes?

No, but the farm list before was listing all the farms, and then only the farms with nodes (up or down) were allowed to vote.

**Comment by amiraabouhadid** [comment]
only farms with online nodes are allowed to vote

**Comment by A-Harby** [comment]
Can we update proposal information to inform the users that votes are only limited to farms with UP nodes?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/25ae8382-149e-4632-bbe9-49009c7ef775)

**Comment by zaelgohary** [comment]
Work completed:

Updated proposal info to include that Only farms with one up node or more are allowed to vote.

**Comment by A-Harby** [comment]
Verified,
- Devnet, ec2ed3d.
- [TC2235 - Vote on DAO Proposals With a Farm That Has No Online Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150444)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5c0f2330-5ae5-403e-954a-540c043b64fb)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
