### ISSUE TITLE
TFT exchange price shown as 0 USD

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1758]
### Search first

Devnet, e2580a5.

The TFT exchange price is shown as 0 USD.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d0e9cfd1-e9f6-498c-a9e9-55e9ff42b146)

**Comment by khaledyoussef24** [comment]
fixed and verified works fine now
[Screencast from 12-26-2023 02:00:46 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/20dcffc3-0a1c-495d-88cf-45e0899b8e6f)
![Screenshot from 2023-12-26 14-00-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5ea515b6-1d6c-445f-ba79-e08638d307d8)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d

![Screenshot from 2023-12-27 11-56-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8ecf13a1-b9a4-4f85-88c0-28aeddf9fffc)
