### ISSUE TITLE
Review all the solution introduced in the new dashboard

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1759]
Maybe we need to review if we still need all these solutions on the dashboard; or something is deprecated and we can decrease the effort maintaining it.

**Comment by xmonader** [comment]
@ramezsaeed where can I find the progress of this ticket? please make sure this gets updated.

**Comment by ramezsaeed** [comment]
Work already done.
and we updated all the not important solutions with alpha flag.
Ex.: 
- Mattermost
- Nextcloud

![Screenshot from 2024-04-14 18-29-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5b4ab480-b0a5-4040-b7ed-55eaf1ca02c9)
