### ISSUE TITLE
Limit validation tasks' tries to 1

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#1760]
useAsync by default tries 3 times which is not needed in case of validation

**Comment by khaledyoussef24** [comment]
is there a way i can verify this ?

**Comment by MohamedElmdary** [comment]
> is there a way i can verify this ?

Yes basically check if network making a single request while select a node manually (if node is not valid)

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2024-01-02 07-11-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d9bfdf95-c773-4e8a-a8e3-aab100c1e2d8)
![Screenshot from 2024-01-02 07-10-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e33b9402-db72-4998-b8b8-a3bffe50ce3c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
-  2.3.0-alpha3
