### ISSUE TITLE
swap price websocket error

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1762]
### Description

Got this error when i refreshed dashboard/twin

### Steps to reproduce

- go to twin page
- refresh page 
- check console

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/fe275c12-6ef4-406d-bce3-ccd2f1ad77e9)

**Comment by AhmedHanafy725** [comment]
should recheck this after #1758

**Comment by AhmedHanafy725** [comment]
this was happening as there were a race condition from 2 different clients try to create connection at the same time. There was a lock already to prevent this but the decision to create a new the connection and close the old one was done outside the lock.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- 000eea2
- [TC2434 - Verify Twin Page](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4161529)
NO error is shown after or before the refresh.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1abba635-48ce-4409-a933-f0542ad1a5c4)

**Comment by ramezsaeed** [comment]
@amiraabouhadid 
no errors anymore when refresh;
But what about the warning for no decoration ?
![Screenshot from 2023-12-25 14-41-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ea3b472c-de0e-44c9-a5c0-b8925025aa47)

**Comment by AhmedHanafy725** [comment]
it's a normal warning
