### ISSUE TITLE
new dashboard node page scrolls up after closing node details

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-ts#1764]
### Description

After expanding the node page from 10 to 50 items and after closing a node resources 'popup', the page is scrolled to the top every time.

### Steps to reproduce

- open https://dashboard.dev.grid.tf/#/nodes
- expand 'items per page' from 10 to 50
- scroll down and click on one of the nodes below
- close the node resources
- page is scrolled to the top

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/e24048d7-7f93-4a42-8be4-15283d7091e2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/151f6d45-494f-439e-9e5b-96acadf97b1b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/7999924f-27de-46ef-945a-42086cfa7cd2)

**Comment by khaledyoussef24** [comment]
verified in devnet
version : ac5cd85
the issue is no longer reproducible.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/743a7334-52bc-48c2-93b4-e34740e3b47e
