### ISSUE TITLE
Can't add new node to caprover cluster

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1768]
### Description

Every time I try to add a node to the caprover, I get this error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9cc4203d-e220-4819-aedc-714b2b3b5e6d)
I did everything: enabled https, activated Docker Registry Configuration, updated Caprover, and deployed a worker from the playground.
I also tried on all the networks and got the same result.

### Steps to reproduce

1. Deploy a caprover master and worker.
2. Open the Caprover dashboard, log in, and enable HTTP, then docker registry.
3. In the cluster page, under the node tab, add work IP to the new node IP address and add your shh key.
4. Click on join cluster.

**Comment by AhmedHanafy725** [comment]
I could add work to the cluster without any issues. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/61eb68ba-c7f8-4830-8633-5208f6dcd827)

Please make sure you are adding the private sshkey (not the public one) while adding the node. Also, the sshkey should be of type RSA as mentioned on the caprover dashboard

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/d45293b4-69f5-4b56-99c7-72d3b228d6fa)

**Comment by A-Harby** [comment]
I was able to successfully add the node and see it on the Caprover dashboard using the Alternative method.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ae07d7e2-85cc-4e1d-8998-c16649b4d8a2)

But the Caprover instructions were outdated, which caused the issue from the start.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f6f49b97-5e90-4029-a84e-b452d2e2f9f1)

So the documents need to be updated with the latest changes.

**Comment by ramezsaeed** [comment]
where did u you get this docs link, 
this is outdated docs for a year now.
please update the new docs in the testsuite if still use the old one.

**Comment by A-Harby** [comment]
I got it from the dashboard itself.
https://manual.grid.tf/playground/caprover_admin.html#step-5-add-nodes-to-caprover
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ec1711fb-2847-4b6f-8d61-b2c1c456c572)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/472e76f2-ef79-41ff-9119-f0bb749eb77b)

**Comment by xmonader** [comment]
@0oM4R please make sure things are linked properly

**Comment by 0oM4R** [comment]
adding node in the mentioned way was failing randomly With different erros, I was able to reproduce this one 
![Screenshot from 2023-12-27 17-03-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/17c57840-b860-4e97-9027-cfd2c49c3cb5)
and after refresh the page node appeared on the cluster normally 

i suggest to recommend the `Alternative method` in the docs,


also sometimes I wasn't able to access the admin panel without VPN

**Comment by 0oM4R** [comment]
Work completed: Updated caprover documentation 

![Screenshot from 2023-12-27 18-26-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/30db5d2f-1722-4e98-bc70-ebcd06e52f8f)
![Screenshot from 2023-12-27 18-25-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/f9b019cb-8dcf-47b5-afef-236bcf94bf75)

https://github.com/threefoldtech/info_grid/pull/347

**Comment by A-Harby** [comment]
Verified, Devnet 7f4d8ea.

The documents have been updated with the new add-worker steps.
https://manual.grid.tf/playground/caprover_worker.html
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/dabaa2af-2899-414a-8272-fb99b8d093d3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6a4ddb82-8bce-40a5-ab08-dc150dbb427d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/22838c27-188c-4a1c-830c-aee34f42903d)
