### ISSUE TITLE
Refreshing the page will always log account mnemonics with key type sr25519 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1771]
### Description

Refreshing the page will change mnemonic key type from ed25519 to sr25519, even when I logged in using ed25519.

[Threefold Dashboard: Your Farms.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d563103c-cf78-45c1-a836-3829418098c1)

**Comment by zaelgohary** [comment]
Store key type in session storage and use it from there if found.

**Comment by A-Harby** [comment]
Verified,
- Devnet
- ec2ed3d
- [TC2113: Connect Wallet] (https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)

I finished the reshesing, closed the page, and relogged in and navigated, and the key pair type should be the same.

[Threefold Dashboard: Your Farms.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2af97132-8021-4662-b6fc-22eacd56143e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
