### ISSUE TITLE
Add Nextcloud to New Playground

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1773]
The Nextcloud weblet is now displayed on the Test playground. It isn't available on dev playground, which is the new playground.

Can we add the Nextcloud weblet to the new playground? Many users asked for this weblet so I think it would be appreciated.

@scottyeager and I can help on this if needed.

**Comment by ramezsaeed** [comment]
Will be enable with a community flair to it.

**Comment by scottyeager** [comment]
> Will be enable with a community flair to it.

Why "community" flair?

**Comment by khaledyoussef24** [comment]
the solution gets deployed successfully
![Screenshot from 2023-12-27 08-06-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/85bca6d7-034f-4e62-bb98-ebf7f80067ed)
![Screenshot from 2023-12-27 08-06-10](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/047cc1aa-f879-466a-b59f-e47ad9cbcda1)
and the user can login
but then it takes 5-10 minutes (as written in the documentation). to install version 27 or 28 from next cloud
![Screenshot from 2023-12-27 08-11-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b8c47bb-7f04-48e3-8d53-813850e30d9b)
![Screenshot from 2023-12-27 08-11-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/316db6b7-73fb-4aea-a98c-adfacb1b3147)
and then the solution works
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/68eeef88-155e-48b7-b4ee-ae8f4e301f75)
![Screenshot from 2023-12-27 08-30-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6f68bf09-03f7-44b4-b04e-6e07c5f0eb66)
![Screenshot from 2023-12-27 08-29-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/772203a1-ddfa-4edf-9b94-b9d5bfc4eadb)

**Comment by xmonader** [comment]
> > Will be enable with a community flair to it.
> 
> Why "community" flair?

Because this wasn't developed by the dev team and got exposed to minimal testing, hence the disclaimer :)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef
