### ISSUE TITLE
Enhance filter field UX

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1775]
While typing the needed value in the filter field, the request may be sent while typing, and after that, I have to click on the field to complete the needed value.

[Screencast from 24 ديس, 2023 EET 12:25:30 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/a9c5d0d7-a3e0-4968-8c06-3a8d0b124899)

**Comment by ramezsaeed** [comment]
Add button to apply filter

**Comment by amiraabouhadid** [comment]
Rewrote filter to use apply filters button.
Will have to rewrite nodes, farms and dedicated nodes to use updated filter

**Comment by amiraabouhadid** [comment]
Addressing issues on PR
