### ISSUE TITLE
Node filters fields should accept decimal field

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1776]
except cors field all field should accept decimal field
![Screenshot from 2023-12-24 12-16-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/dfe0eb52-ec81-4598-abe5-e7e698e9011f)

**Comment by zaelgohary** [comment]
Will close in favor of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1783

**Comment by khaledyoussef24** [comment]
verified and works fine and accurate 
![Screenshot from 2023-12-26 13-33-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e8e77007-2b50-4078-b775-eb3ad4cc58ab)
![Screenshot from 2023-12-26 13-33-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b3852eef-67be-4d0a-ab27-42ac9865c894)
![Screenshot from 2023-12-26 13-33-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/41035bda-dca9-4b6c-9333-f47a9c03439a)



testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422335#case_4162539
