### ISSUE TITLE
Enhance disconnect method 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1781]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/832d4d9ee5e944d677db392f6e015579f55704d2/packages/grid_client/src/client.ts#L124

this line should moved to `this.disconnect` method

**Comment by 0oM4R** [comment]
### Investigation and Solution

- the current solution make the client disconnect twice
- will remove event listeners from grid client as each client has its own event listeners.

**Comment by 0oM4R** [comment]
couldn't reproduce disconnecting twice issue, will check with Hanafy later for this point

**Comment by AhmedHanafy725** [comment]
the example script on the direct client is not working as the close method has been removed

**Comment by AhmedHanafy725** [comment]
requested changes are done
