### ISSUE TITLE
Taiga: Can't login with credentials from deployment details into the admin panel

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1782]
### Description

Testnet, 2.2.0-rc6

I tried it twice, and the same error happened: I couldn't login to the admin panel with my username and password from the deployment details.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0789dcbc-175c-4c39-84af-49a1c3a5d75c)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/359bce2a-85bd-4fa6-a49a-c3434780a4cc)

### Steps to reproduce

1. Navigate to the playground.
2. Connect your wallet.
3. Navigate to Taiga.
4. Fill in the config and deploy.
5. Click on the admin icon.
6. Copy and paste the username and password.
7. Login.

**Comment by ramezsaeed** [comment]
try normal passwd with all lower case as in example.
if so the passwd generation is the problem

**Comment by A-Harby** [comment]
I tried several times, and the issue wasn't reproducible, but I was able to login successfully in all of them.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d380626b-d376-4c0a-8c70-a35e2cd6c3b6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ba6b6fb4-353e-4614-9322-3a9e465bf3fb)
