### ISSUE TITLE
Node Filters Doesn't work as expected

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1783]
[nodes_filter.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c3d3ff29-2887-4c4c-8871-682dc2e07ad8)

- Resource filters don't accept decimal values
- Filtered nodes don't include all available nodes

**Comment by zaelgohary** [comment]
Work completed:

- Added filter by total resources
- fix filter by decimal values

**Comment by khaledyoussef24** [comment]
verified and works fine and accurate 
![Screenshot from 2023-12-26 13-33-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e8e77007-2b50-4078-b775-eb3ad4cc58ab)
![Screenshot from 2023-12-26 13-33-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b3852eef-67be-4d0a-ab27-42ac9865c894)
![Screenshot from 2023-12-26 13-33-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/41035bda-dca9-4b6c-9333-f47a9c03439a)



testlodge : https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1725

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
