### ISSUE TITLE
is your twin the most suitable page to redirect to after login?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1784]

**Comment by mohamedamer453** [comment]
The user is now redirected to a home page with different shortcuts of pages that exist in the dashboard instead of redirecting the user to the Your Twin page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0bf2ca96-a90d-441d-90ff-f61226731ef9)

**Comment by khaledyoussef24** [comment]
verified on all networks
version : ac5cd85
The user is now redirected to a home page with shortcuts to navigate through the dashboard.
![Screenshot 2024-03-24 at 8 36 02 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9011f721-bbf2-4901-9c21-bfe316fd2b58)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4156941
