### ISSUE TITLE
investigate internet download upload (farms/DAO pages)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#179]
https://forum.threefold.io/t/mysterious-internet-usage-on-dashboard/3910

**Comment by UnholyChrysalis** [comment]
Hello, I am unsure what is being uploaded/downloaded from these pages.  I was asked to show screenshots of the developer tool when loading the page.  Not s
![image](https://user-images.githubusercontent.com/82938079/233913064-3984d229-0ba5-4712-9e70-4b5d281c6da0.png)
ure what to show in the screenshot, so request what you need and I'll get it to you.

**Comment by UnholyChrysalis** [comment]
Here is a screenshot of the task manager.  
![image](https://user-images.githubusercontent.com/82938079/233913235-5ed64b68-8ddc-434e-b5ea-e40f1ad785dd.png)

**Comment by AhmedHanafy725** [comment]
related to #59 
this issue is already solved on devnet and it will be on mainnet when 3.10 is released

**Comment by A-Harby** [comment]
Issue if fixed, verified and released on Devnet as in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/59#issuecomment-1506874116
