### ISSUE TITLE
Farm name is case sensitive, which allow to create two farms with the same name

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1790]
Create farm in your farms tab is case senestive;
which means the one user can crerate mutltiple farms with the same name !
and when come to search by name (its not case sensitive)

rtest1
Rtest1
rTest1

all these farms have the same name but different in upper/lower cases

![Screenshot from 2023-12-25 14-19-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/fe09b4b3-7d63-4b2c-aae6-50dd5ea010bd)

**Comment by xmonader** [comment]
This is allowed on the chain @sameh-farouk

**Comment by sameh-farouk** [comment]
> This is allowed on the chain @sameh-farouk

Yes!

https://github.com/threefoldtech/tfchain/blob/36c891c02a1758a6bd6769357fdef230886940ff/substrate-node/pallets/pallet-tfgrid/src/farm.rs#L31-L34

https://github.com/threefoldtech/tfchain/blob/36c891c02a1758a6bd6769357fdef230886940ff/substrate-node/pallets/pallet-tfgrid/src/farm.rs#L55

**Comment by xmonader** [comment]
can be limited from the UI for now (if the user doesn't have multiple farms with different cases)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 
the user can not create farms with the same name using any combination of lower and upper cases.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7b651b41-836f-4fcf-8e6d-e7d6841ba11a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1a6e232f-359f-480e-9ef6-5b0bde8e5db2)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150450
