### ISSUE TITLE
Typo: "Node statuses" is very weird looking in node page 

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1791]
"Node statuses are updated every 90 minutes. For a realtime status, please click on the row."
change:
- Node statuses --> nodes status

![Screenshot from 2023-12-25 14-30-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9b9ba2cb-ed4c-41a8-8fdb-3f150e5dbc98)

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1798

**Comment by A-Harby** [comment]
Verified,
Devnet, 75231de.
Status typo fixed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d5f6d0db-a2f3-4638-9a40-11887c8d5d21)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef

![Screenshot from 2024-01-01 12-52-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7eb4da3f-7fe3-4946-88cf-69f7910b8519)
