### ISSUE TITLE
Add Workload card to stats 

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1792]
Add Workloads card to both Stats page & website.

**Comment by Mahmoud-Emad** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/985

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done 

Include the Workloads info in the stats view in the dashboard and the stats project. 

####  Changes

- Included the `workloads_number` attr in the stats view in the dashboard
- Included the `workloads_number` attr in the stats project 

#### Screenshots
- Dashboard

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f7b928da-06b8-4ea7-a1d2-55e0e129d0b1)


- Stats project 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/bad98d6e-695a-4278-8d4c-9695e36f21c2)

**Comment by A-Harby** [comment]
The numbers aren't matching.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/95d158ad-fad6-4b76-89fd-d1de2200591e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/437f7ee8-0407-44e7-bca5-05c07e2351d3)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
Which network/project?

**Comment by Mahmoud-Emad** [comment]
@A-Harby Please note that The idea is that we request to get the workloads number of the up status then we request to get the status of the standby status then sum the numbers

in this case, you requested without adding the status filter so you got this value `571` [see here](https://gridproxy.dev.grid.tf/stats)
but if you changed the URL and added the status filter [as here ](https://gridproxy.dev.grid.tf/stats?status=up) you'll see the actual value

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945
used the link with [status up](https://gridproxy.dev.grid.tf/stats?status=up) for workloads


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8e1d62af-1e29-47b8-99a6-02249911c6f5)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f68c553a-47ad-42e7-96d5-bcef8d58752c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ff0b7a3a-222a-4a35-9593-67fb09e11ba2)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4150457
