### ISSUE TITLE
Transfer fees not applied  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1793]
on low balance the mentioned fee `0.01` not applied on the sender
![Screenshot from 2023-12-25 14-04-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/af939c2c-c0fb-4e85-a571-5d1e7aaf5daa)

[Screencast from 25 ديس, 2023 EET 02:00:29 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/3ccec0f2-a061-4d1d-9dd8-072a83985509)

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2023-12-31 09-50-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d210eb06-7d73-4df1-9880-d986c0ce690c)
![Screenshot from 2023-12-31 09-50-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d3901d97-bd8a-48be-9e38-7dd75694d3d5)
transfer can not be made if you do not have the transfer balance
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a0387be8-d93e-4e1d-bad3-404ded2c0e1b)

**Comment by khaledyoussef24** [comment]
can we make the validation before the transfer request ?

**Comment by 0oM4R** [comment]
we can't predict the fee, we only can check on the minimal fee which is 0.001, but this will not prevent that failure

**Comment by 0oM4R** [comment]
I checked with Hanafy, will make the validation on the maximum fee = 0.01

**Comment by khaledyoussef24** [comment]
verified now 
![Screenshot from 2024-01-01 13-50-00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/68aee880-3592-4960-bb2e-3cd77d135380)
![Screenshot from 2024-01-01 13-49-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fdb77ef4-8618-4805-85e7-02f5963a8778)
![Screenshot from 2024-01-01 13-49-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/829b5aa1-e2ba-4573-b65b-d65fd63b0a57)
the validation is made with 0.1 which gives a better user experience.

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 2.3.0-alpha3

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : 33c308d

transfer amount is getting cleared after transfer
[Screencast from 01-02-2024 03:01:03 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4bf9c917-542a-4655-9db5-467d4081447d)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150413

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d

![Screenshot from 2024-01-02 17-20-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/495857b2-a15d-48b2-8845-b60538bdd72a)
