### ISSUE TITLE
Edit Nodes hint

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1797]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c73eb927-f966-4091-bf72-f7c364000ba1)

Should be "Node status" instead of "Node statuses"

**Comment by khaledyoussef24** [comment]
fixed and verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1059dd7c-b4fe-4277-96fd-0c419e3de0a4)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
