### ISSUE TITLE
kubernetes :deleting worker change status to not ready

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1799]
### Description

after deleting worker the worker is not removed from master it only changes the status to not ready.
should it be removed ?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cb107573-00af-484d-ae4b-b529a8356e6c)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f3237eca-6a9f-4b83-94b7-eae960b70ba8)

**Comment by xmonader** [comment]
The delete, only deletes the Virtual machine, It doesn't/can't reconfigure the cluster with the info, the NotReady if good enough
