### ISSUE TITLE
`certified` filter in the capacity planner is only used when the farmerbot is used

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#18]
this requires to be supported on gridproxy first

**Comment by A-Harby** [comment]
Verifed,
Endpoint was added to the gridproxy and verified https://github.com/threefoldtech/tfgrid-sdk-go/issues/45#issuecomment-1505308369
![image](https://user-images.githubusercontent.com/109473873/234881300-08238ddc-1c71-4a56-81d6-3c5527e5fad4.png)
And FilterOptions was added in the ts grid client 
![image](https://user-images.githubusercontent.com/109473873/234881499-a947450c-bb26-40d9-a7e0-c81e001358bf.png)
And can be called through certified filter in capacity filterNodes function
![image](https://user-images.githubusercontent.com/109473873/234881556-357155f8-b66d-473d-9db4-75208c7d5d26.png)
