### ISSUE TITLE
(Qanet) Cannot rent a node

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#1804]
### Description

When I try to rent a node on Qanet, it gets stuck loading
### Steps to reproduce

- Go to Dedicated Nodes in the dashboard
- go to the rentable section and try to reserve a node
### Logs/Alerts
![2023-12-26_14-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/19c288ab-f0b4-4caf-9aad-ff0ba40b24d6)
- tried to rent a node through the grid_client, the error should be reflected in the tost
![2023-12-26_15-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/88065154-e5e2-44ef-bd1b-3e56d02b8bd4)

**Comment by maayarosama** [comment]
Work in Progress (WIP):
- Trying to figure out why an undefined value is being sent to the toast component

Investigation and Solution:
- The error is being sent to the toast as a string but in the createCustomToast method is not seen as a string

**Comment by khaledyoussef24** [comment]
verified on qa net 
version : 2.3.0-alpha12
![Screenshot 2024-02-27 at 3 55 36 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5b0dd6e9-a4b2-4ddc-ad2a-27f5d55610cd)
![Screenshot 2024-02-27 at 3 55 46 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/497881ef-aac6-4b94-8138-fb451b38e007)
![Screenshot 2024-02-27 at 3 56 07 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/17cc9368-8018-4ae7-bd05-b12ab59d573f)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430127#case_4150431
