### ISSUE TITLE
FullVM DevNet AMD GPU not working

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#1806]
# Setup

* I deploy on the dedicated node 147 on dev net (on my own farm) (R720 dell server)
* I deploy a full VM on the new playground (devnet) and follow the steps [here](https://manual.grid.tf/gpu/gpu.html)
* I set the recommended kernel: 5.18.13
* I download the driver from the link in the manual: https://repo.radeon.com/amdgpu-install/23.30.2/ubuntu/focal/amdgpu-install_5.7.50702-1_all.deb

# Outcome

I get the following outcome with the lines: 
* rocm-smi
* rocminfo

```

root@vmezc1n:~# rocm-smi


========================= ROCm System Management Interface =========================
WARNING: No AMD GPUs specified
=================================== Concise Info ===================================
GPU  Temp (DieEdge)  AvgPwr  SCLK  MCLK  Fan  Perf  PwrCap  VRAM%  GPU%  
====================================================================================
=============================== End of ROCm SMI Log ================================
root@vmezc1n:~# rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          NO

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
  Uuid:                    CPU-XX                             
  Marketing Name:          Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    32870372(0x1f58fe4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    32870372(0x1f58fe4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    32870372(0x1f58fe4) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*** Done ***             
root@vmezc1n:~# uname -r
5.18.13-051813-generic


```
# Question

Any idea what I am doing wrong or some troubleshoot avenues?

Thanks a lot!

**Comment by A-Harby** [comment]
First, I could see that the node is down and can't retrieve the GPU details.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d01f7f72-e326-41fe-9b7e-c705f68901a7)


Second, did you choose the correct driver? It depends on the model.

Did you also face any errors while installing anything? and did you see your GPU card when you tried `lspci | grep VGA` or `lshw -c video`

**Comment by ramezsaeed** [comment]
@Mik-TF

**Comment by Mik-TF** [comment]
@A-Harby 

Yes I know the node is currently down. I did many tests and ended up trying to set everything on bare metal to make sure the error wasn't from the grid itself. The results haven't been fruitful yet.

I put the node on main net now and will try GPU there instead of dev net to see if things get better (node ID 6245)

I chose the correct drive and even tried different methods. I did not see any errors when doing the method described above in the issue. Yes the card is there when I do either lspci | grep VGA or lshw -c video.

Please let me know if you want to test it yourself or if you have any ideas how to troubleshoot further.

I will continue testing on my end.

**Comment by Mik-TF** [comment]
Here is the output I had running Ubuntu in Try mode after installing the graphics card.

![dellrackserveramdgpu_1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/0d9aec56-c8cc-43b3-81cb-8678150ba9aa)


![dellrackserveramdgpu_2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/3b47172a-9af1-4028-8678-31cde335e36b)

**Comment by Mik-TF** [comment]
With GPU node in the explorer, I can see the new node 154, aftere having used wipefs and retested the command above:

![gpu_dedicated](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/9d407bb2-ce05-4727-aa70-c3695e3e6dbf)

![gpu_node_explorer](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/9a1c653f-cbed-451a-bfa1-8be6b1810ce4)


But the GPU is at 0.

**Comment by Mik-TF** [comment]
@ramezsaeed 
Do you want to test it directly by renting the node as dedicated?

I can also retry on my end. Let me know!

**Comment by A-Harby** [comment]
Just to be sure, is the driver you tried https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580? or was it a different one?

**Comment by Mik-TF** [comment]
Yes. I tried this one with 22.04.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/aa30d551-b55b-4951-b38f-a09cf15c474c)

**Comment by A-Harby** [comment]
@Mik-TF Can I rent it or have access to it so I can test it myself?

**Comment by Mik-TF** [comment]
@A-Harby 
Yes! That would be amazing actually. It's available on dev net, you should be able to reserve it.
Let me know if I can help any more.

**Comment by A-Harby** [comment]
I tried a lot of different configurations to try to install this GPU card, but I couldn't do it.
I tried different Ubuntu versions, different kernel versions, and different drivers, but none of them worked.

I was able to get to the point where the AMD driver was installed successfully with no error, but the GPU was still not installed.
Ubuntu version is `22.04.3 LTS (Jammy Jellyfish)`, kernel version is `5.18.13-051813-generic` and driver version is `5.7.50702-1683306.22.04` from https://www.amd.com/en/support/graphics/radeon-500-series/radeon-rx-500-series/radeon-rx-580.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a46351c7-c83a-4937-8412-95eb2ab4e326) 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4a05cd37-4658-4ad3-aa29-8fc2613e99d2)


The GPU Card details:
```
root@test6gpu:~# lshw -c video
  *-display UNCLAIMED       
       description: VGA compatible controller
       product: Polaris 20 XL [Radeon RX 580 2048SP]
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 7
       bus info: pci@0000:00:07.0
       version: ef
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi vga_controller cap_list
       configuration: latency=0
       resources: iomemory:3fff0-3ffef iomemory:3fff0-3ffef memory:3fff20000000-3fff2fffffff memory:3fff3fc00000-3fff3fdfffff ioport:ff00(size=256) memory:e7e40000-e7e7ffff memory:c0000-dffff
root@test6gpu:~# lspci | grep VGA
00:07.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Polaris 20 XL [Radeon RX 580 2048SP] (rev ef)
```

**Comment by xmonader** [comment]
As we are passing the device fully as a passthrough, it's completely up to the device, device implementation, kernel support and the code to be compatible, not sure what we can do as it's all out of our hands?

**Comment by Mik-TF** [comment]
@xmonader 
I can test the AMD node outside of the grid and then put it back on the grid to try it once more, then let you know how it went.
Should be able to test this in the next 24 hours.

**Comment by Mik-TF** [comment]
@xmonader So after testing once more with few other methods, it still doesn't work.
I will try the AMD gpu on another computer (desktop computer this time). We'll see.

I read at many different places online that people had this kind of error with AMD so it's not unique.

We can close the issue if you want. Thanks!
