### ISSUE TITLE
pre existing values when adding public config

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1807]
- Why there are values when opening the dialog ? 
- They should be removed on mounting. 

[Screencast from 12-27-2023 11:09:32 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/98939382-68a6-41de-ae73-54ca769ecad7)

**Comment by xmonader** [comment]
They should be reset indeed.

**Comment by AlaaElattar** [comment]
- It's not actually an issue. 
- what really happens if there's already public config will be rendered to user in dialog, so user can remove or update it. 
- what is shown in the video is the public config of my node.
