### ISSUE TITLE
remove old weblets, dashboard, stats 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1811]

**Comment by zaelgohary** [comment]
Blocked till 3.13 reaches mainnet.

**Comment by zaelgohary** [comment]
Work completed:

Removed Weblets, Dashboard & updated docs & workflows.  Old stats were already removed.

**Comment by khaledyoussef24** [comment]
verified statically files are removed from packages and also there workflows.
![Screenshot 2024-03-25 at 8 59 32 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cdb651a7-5209-42a0-8e66-e3c1d5f9e165)
the old stats is being replaced with the new one recently ( 2 weeks ago)
