### ISSUE TITLE
Add currency abstraction

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1815]
We keep doing the conversions manually, and .toFixed calls way too often, let's introduce some sort of Tft class or Currency that can handle the logic of conversion, hourly, monthly, yearly calculations, and the string representation, .. etc

**Comment by zaelgohary** [comment]
WIP:

Added the TFT class which contains conversions to/from USD alongside monthly and yearly conversions. Currently working on implementing the script to use the mentioned functions.

**Comment by zaelgohary** [comment]
WIP:

Used decimal in the abstraction and updated the script. Currently working on adding unit tests.

**Comment by zaelgohary** [comment]
WIP: 

Edited the TFT module and updated its script and added some tests. However, some of the tests are not working and I'm working on fixing them.

**Comment by zaelgohary** [comment]
Work completed:

Changed the class name and removed the calculator completely and got TFT directly from TFChain instead. Applied changes in the script and its tests. Also, added more tests.

**Comment by zaelgohary** [comment]
Changed the previous flow so the user would need to get the rate himself before creating a currency instance (Now the Grid Client is not needed to create the instance). Also added the possibility for the user to change the decimal value for all the method results.
