### ISSUE TITLE
Solve issue of validating specific field from inside `useFormRef();`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1818]
### Description
- Add inputs map so we can access specific value to validate from inside form. 
- One case is not fixed yet: when any other input is being typed and validated and there is already a wrong validation on the other inputs, all of them will be affected and revalidated.

[Threefold Dashboard: Your Farms.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f3e0a37e-2106-4cf1-ab0e-e1c32bcd0668)

[Threefold Dashboard: Your Farms (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/16a410cf-1595-468d-b16f-068e45a9b5d3)

**Comment by A-Harby** [comment]
Verified, Devnet 935d56a.

[TC2218 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150427)

[screen-capture (26).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/62ebf7fd-adce-4841-9f0e-fccdee67cad2)
