### ISSUE TITLE
Creating a tfchain account from the grid client without an active twin 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#182]
### Description

Is there a way to create a tfchain account from the grid client without adding a mnemonic of an already existing twin to create it. (Same flow as the create account from the weblets).

**Comment by AhmedHanafy725** [comment]
yes, check this script https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/create_account.ts

**Comment by costarassco** [comment]
thanks for the reply @AhmedHanafy725, It creates the Twin ID perfectly if I've already used the polkadot account

the problem is that when I use a polkadot account which hasn't been used in grid before, I face with such an error:
> Error: Unable to connect due to twin does not exist, please create a twin first

can I just use the mnemonic phrase of my wallet?

**Comment by costarassco** [comment]
or should I invoke that method without the mnemonic phrase and it responds with a new twin id and a new account like it's address and it's mnemonic phrase ?
