### ISSUE TITLE
Check if the farm has enough public ips before creating the extrinsics

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1822]
Alongside checking the node resources before proceeding with creating the extrinsic, we should check if the deployments require public IPs and validate that against the farm.

**Comment by A-Harby** [comment]
Verified, Devnet branch.

The farm public IP validation is added to run first.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/61ab663b-92ae-40e2-a510-dc8cf0d7765e)
