### ISSUE TITLE
calculator colors are confusing  and strange color appears

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1824]
### Description

calculator colors are confusing  normal and silver are so much a like user will not notice the difference.
silver:![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4fbc3726-2b0a-4978-afb7-7fb4fbe5eedd)
default:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9477bedf-09ea-4eca-80fe-bb92962cfe1e)

and there is another color only appears when i insert the range of 200 tft  and it makes the text unclear
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/295c0633-492f-4856-bd83-b17680f4d37e)

**Comment by ehab-hassan** [comment]
I made it clearly white so there is a difference between default and Silver
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c4a01e04-7387-493d-b14a-d0fde5d709d5)

Default
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b0f414ef-e156-41ca-b260-8e1da127c3e2)

Silver
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/533ef466-dc12-472b-ba7d-6ed921cbbccb)

Gold
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/df803db6-20a0-49dc-a48b-cb080ec4d1a6)

Bronze
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/cf1e4e76-0bac-42f2-b9b3-109f68891ff9)

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

colors are now different and unique 

![Screenshot 2024-03-25 at 12 38 59 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cecad578-438a-4409-8c82-76adab6f7d6e)
![Screenshot 2024-03-25 at 12 39 11 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b98679da-d7a5-44c3-b864-c052299f69de)
![Screenshot 2024-03-25 at 12 39 25 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2abb9582-452e-47a6-ab2c-8e136830d60b)
![Screenshot 2024-03-25 at 12 39 35 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c442c6ab-a361-4a66-a4db-a8f65195c4ee)
![Screenshot 2024-03-26 at 10 20 04 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/49e1bd80-5c3f-41c4-b486-7da170a705a0)
