### ISSUE TITLE
after transferring insufficient balance warning appears

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1827]
### Description

after transferring insufficient balance warning appears and then transfer failed message appears after transferring successfully.
[Screencast from 12-31-2023 05:17:04 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c5fdca11-dc33-4e76-ada7-2f61d9d97601)
![Screenshot from 2023-12-31 17-16-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f38f6d8a-00ea-4c7b-9221-13751573170e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/97e05829-375f-4f85-a6e5-58bfec876172)

and this warning is annoying after the transfer is already done.

in my opinion i think fields should be cleared
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/24c9d9bb-e7d3-48e8-ad5f-4b99bf894ef5)

**Comment by khaledyoussef24** [comment]
now the transfer field message ' transfer failed' does not pop up
but on throttle connection before the value is getting cleared the insufficient fund warning appears
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f869b335-7ea9-41e1-8e1d-0e9071bdebaf)
for 1 second is it acceptable  ?

**Comment by khaledyoussef24** [comment]
verified
env used : devnet
version : https://github.com/threefoldtech/tfgrid-sdk-ts/commit/e2fa190db7f0f70c80b397ad8c44e2a023afd640

the clearing of the value is now more smooth.

[Screencast from 01-08-2024 12:52:45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e8bac2ca-8e8d-486d-ada3-2c58f84b4c2f)


test lodge
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4169746

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- da46d82
