### ISSUE TITLE
Publish workflow failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1829]
Full Clients Publish workflow failed for the latest 2 consecutive releases.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7371654991/job/20059256567#step:6:1165

**Comment by 0oM4R** [comment]
works fine on https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7406776821

**Comment by A-Harby** [comment]
True, it worked fine on the last run.
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7406776821 
I will close, and please reopen if it reproduces.
