### ISSUE TITLE
Show node health button when the node is down

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1831]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/35562a6c-34ce-4796-98d8-9b871e8d057b)

**Comment by khaledyoussef24** [comment]
it is not added yet

offline node:
![Screenshot from 2024-01-02 10-27-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/774d5d50-f6c8-4730-a53c-837a333b5487)
Online node:
![Screenshot from 2024-01-02 10-27-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b28257dc-d750-4a52-add1-37b5c2f46291)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 10deaba
