### ISSUE TITLE
[Research] Investigate searching for certain events starting from certain block

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1834]
The tfchain client has an event listener that listens for a certain event with some conditions. it's required to do the same but starting from a specific block number.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/703ae34412f3c3d951e984e3fa3dfa6c46cc0080/packages/tfchain_client/src/client.ts#L196

**Comment by 0oM4R** [comment]
I was able to run init script to start searching at specific block hash/number, and based on method and section will return the event. anyways me can add conditions like the one on listenForEvent, also i think we can't use the listenForEvent method

```ts
import { ApiPromise, WsProvider } from "@polkadot/api";
import { ApiDecoration } from "@polkadot/api/types";
import { BlockHash } from "@polkadot/types/interfaces";

type Block = {
  header: {
    parentHash: string;
    number: number;
    stateRoot: string;
    extrinsicsRoot: string;
    digest: { logs: [] };
  };
  extrinsics: string[];
};

async function listenForEvent<T>(api: ApiDecoration<"promise">, section: string, method: string): Promise<T> {
  return new Promise<T>(async (resolve, reject) => {
    const unsubscribe = (await api.query.system.events(events => {
      for (const { event } of events) {
        if (event.section === section && event.method === method) {
          try {
            resolve(event as unknown as T);
            return;
          } catch (error) {
            reject(`Cannot reach the key with error:\n\t${error}`);
            return;
          } finally {
            unsubscribe();
          }
        }
      }
      unsubscribe();
      resolve(undefined as T);
    })) as unknown as () => void;
  });
}

const startingHash = "0x632421eafd2571b954a8a8e91e71360b246508e4fb1db4e3f758df6778a81f4a";
const startingBlockNumber = undefined;
async function main() {

  const provider = new WsProvider("wss://tfchain.dev.grid.tf");
  const api = await ApiPromise.create({ provider });
  let blockHash: BlockHash | string = startingHash;

  if (!startingHash && startingBlockNumber) {
    blockHash = await api.rpc.chain.getBlockHash(startingBlockNumber);
  }
  // eslint-disable-next-line no-constant-condition
  while (true) {
    const NextBlockNumber = ((await api.rpc.chain.getBlock(blockHash)).toJSON().block as Block).header.number;
    const newestBlockNumber = ((await api.rpc.chain.getBlock()).toJSON().block as Block).header.number;
    if (newestBlockNumber <= NextBlockNumber) {
      console.log("waiting");
      await new Promise(resolve => setTimeout(resolve, 6000));
      continue;
    }

    blockHash = (await api.rpc.chain.getBlockHash(NextBlockNumber + 1)).toString();
    console.log(NextBlockNumber, blockHash);
    const events = await listenForEvent(await api.at(blockHash), "balances", "Deposit");
    if (events) {
      console.log(events.toString());
      break;
    }
  }
  process.exit(0);
}

main().catch(error => {
  console.error(error);
  process.exit(-1);
});


```

**Comment by 0oM4R** [comment]
Work completed: 
we can start from the current block, this will allow us to start listing from the current block if the user didn't provide a block number/hash. 
that was only investigating and research

TODO: will rewrite the current method to apply the logic mentioned above

**Comment by 0oM4R** [comment]
Work completed:
enhanced the listing logic to sync the newest block with the newest one on polkadot UI,
I tried to merge that logic to the current event listener but looks like we aren't apple to do so, 
we can rewrite the current `listenForEvent` but this will leads to breaking changes like different args and different returns
will check with Hanafy to decide what should we do

Investigation and Solution: based on the decision will apply the required changes on the tfchain client

**Comment by sameh-farouk** [comment]
The squid stack (graphql stack) has two built-in GraphQL servers. One of them is the one we all know that queries the processed data, while the other, which is lesser-known, queries the raw data from the indexer. This second server is quite powerful as it allows you to query and filter any chain-related data, such as blocks, extrinsics, and events.
I thought this could be useful for you and it will be more performant than traversing the blocks as the whole data is already pre-ingested.

Here is an example of queuing all billed events for a specific contract
![Screenshot_20240205_133906](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/42457449/86b0e9f2-ba8b-4f41-a123-cd6427e91824)

So maybe, based on what you want to achieve, you can come up with a client that can simply query this server directly instead of chain RPC ingestion which is heavier, and slower.

**Comment by 0oM4R** [comment]
> The squid stack (graphql stack) has two built-in GraphQL servers. One of them is the one we all know that queries the processed data, while the other, which is lesser-known, queries the raw data from the indexer. This second server is quite powerful as it allows you to query and filter any chain-related data, such as blocks, extrinsics, and events. I thought this could be useful for you and it will be more performant than traversing the blocks as the whole data is already pre-ingested.
> 
> Here is an example of queuing all billed events for a specific contract ![302280406-86b0e9f2-ba8b-4f41-a123-cd6427e91824](https://private-user-images.githubusercontent.com/42457449/302321645-3380f880-1dc1-487c-a02d-ad1f244b0320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTc2NzMsIm5iZiI6MTcwNzM5NzM3MywicGF0aCI6Ii80MjQ1NzQ0OS8zMDIzMjE2NDUtMzM4MGY4ODAtMWRjMS00ODdjLWEwMmQtYWQxZjI0NGIwMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzMDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZjRkMmEzNzU2OWRkNmYwODQwZTk2NGFjNTRiYmEyMDcyZDhjNGNkMTVjYjdkNzYyM2M4MTY4N2RhNTA3NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6hZboqhPh1hSwi9b0VBj_63Os8n-niJ-2j9TwpifjZY)
> 
> So maybe, based on what you want to achieve, you can come up with a client that can simply query this server directly instead of chain RPC ingestion which is heavier, and slower.

can you please provide the mentioned endpoint ?

**Comment by sameh-farouk** [comment]
PM you a test endpoint. You can experiment with it if you like to see if it satisfies your requirements

The operations team can expose the same endpoint for the deployed stack and assign a DNS if we request this. currently, they running its container `subsquid/substrate-explorer:firesquid` unexposed.
