### ISSUE TITLE
Adding disk name in the deployment details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1835]
### Description

After adding a disk to the FullVM or MicroVM and deploying, in the deployment details, the disk label should have the disk name, not only 'Disk', which makes it hard to identify.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/45099d16-baca-416f-a981-5c504406a32d)

**Comment by xmonader** [comment]
Good one! not sure if it should just be the name, could be the mount point too

**Comment by ramezsaeed** [comment]
Also missing unit for disk capacity.

**Comment by mohamedamer453** [comment]
Update:

Work Done:

Now there're 2 main cases, first case is a disk that has mount point like the disks that are added for micro vm or the default disk for full vm. in this case the mount point will be displayed which also includes the disk name.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e9dafe8d-4432-4f8c-a381-68eedce63818)

The second case is mainly for full vm disks where they don't have a mount point so their disk names will be displayed as an identifier.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/db6b9429-0a97-4afe-aac5-6389baf6beb6)

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.

The disk name, mount point, and size unit have been added to the deployment details.

FullVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/694d5183-c0e7-4c15-be8e-06fbf8c35d36)
MicroVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0411ab9d-ed17-4efe-9835-e85115dff93c)


[TC2121 - Deploy Full Virtual Machine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330)

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.3.0-alpha12


Adding disk for micro VM is missing the mount point field

![Screenshot from 2024-02-27 13-58-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ce549a48-46ba-448f-a22e-67b528e8f92c)
