### ISSUE TITLE
Why dashboard doesn't have created_date column to sort in solution

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1838]
When user open any solutions; He expect he can list all his deployed solution by Date_created

![Screenshot from 2024-01-01 21-55-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/b223894d-a97b-462b-be92-e8d5da7f3ab0)

**Comment by xmonader** [comment]
Cool suggestion, there's a created field in contracts that can get exposed 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/61d5a8ed-9a97-41cd-8cbb-3882c2bf3e62)

**Comment by mohamedamer453** [comment]
Update:

Work in Progress:

- Added a `Created At` column that displays the date and time for each deployment.
- Added the column for both the vm and k8s deployment tables.
- Sorting is still not working, trying to figure out what's wrong with the sorting and how to fix it.

**Comment by khaledyoussef24** [comment]
![Screenshot 2024-02-12 at 9 31 59 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fd20d964-89ae-4454-992c-0caed6d56ffa)
![Screenshot 2024-02-12 at 9 32 03 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5502b930-aa32-4f26-944e-58497febbcb0)
![Screenshot 2024-02-12 at 9 33 33 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c0e8bca8-cbe9-4acd-8603-1ca2f0a39451)
verified on devnet
version : b994468
also verified the sorting and it is working fine

[TC2121 - Deploy Full Virtual Machine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330)

**Comment by ramezsaeed** [comment]
it should be "Created Date" or "Created On"
Didn't think "Created At" looks very weird.

Verified:
- Devnet
- 76f44e6

![Screenshot from 2024-02-13 13-29-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5a14ed0c-b991-4f3d-9161-6cf3044b43cd)

**Comment by ramezsaeed** [comment]
@xmonader 
I found its "created At" everywhere else; so up to to to decide keep it like that or change it everywhere.
