### ISSUE TITLE
Deployment JSON view: JSON not Json

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1839]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/6473306d-6db3-4c72-b065-1f10b621661f)
It says Json, but it's called JSON (JavaScript Object Notation)

https://www.json.org/

**Comment by A-Harby** [comment]
Verified,
Devnet 14deff7.


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3d9bc582-aaf8-4b35-b0e8-be251dd6107f)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- dfbecf3

![Screenshot from 2024-01-03 14-51-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/b32a32ef-bc57-43f2-b267-3153162da37d)
