### ISSUE TITLE
Add standby node in the stats page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1843]
### Description

Add the standby node to the online node on the stats page
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/056aacd4-4a3c-41f8-af42-28d5534f4d91)
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1275

**Comment by A-Harby** [comment]
Verified,
Devnet, 7f4d8ea.
[TC2247 - Explorer should show Nodes Statistics and Distribution Map](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150456)
[TC2248 - Verify Statistics](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422340#case_4150457)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a8f4f448-368d-46ba-a511-a4a93691ffa8)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7f4d8ea

![Screenshot from 2024-01-08 12-22-10](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/2dfe6dc4-30d8-411b-8bc2-a607d9ee673a)
