### ISSUE TITLE
shouldn't the twin ID be reset after transfer is done?

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1846]
shouldn't the twin ID be reset after transfer is done?

_Originally posted by @amiraabouhadid in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1842#pullrequestreview-1800229985_

**Comment by A-Harby** [comment]
Verified,
- Devnet 
- da46d82
- [TC2204 - Transfer TFT By Twin ID](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150413)
- [TC2293 - Transfer TFT By Twin Address](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4152312)

After the transfer is done, both ID and balance are cleared in both the By ID and By Address tabs.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b5ff20a3-7b8c-4b74-91fe-d7f2b5504795)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bdf9aca0-13d6-4a35-a33b-aed23257cc52)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- da46d82
