### ISSUE TITLE
Trigger Minting hash validation before clicking view

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1848]
The validation for minting should be initiated before clicking the view button.

Not only should the validation check the hash's length, but also if the hash is valid or not.

**Comment by ramezsaeed** [comment]
look at the difference betweeen use the last char as "c" or "k"

![Screenshot from 2024-01-03 11-52-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/87e2712a-e4d3-4479-87ee-42c6c52e7810)
![Screenshot from 2024-01-03 11-52-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/da0f0445-ad13-4b99-a059-ffeb4aa180d1)
![Screenshot from 2024-01-03 11-52-26](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/dfeac06a-dcb1-454b-97fd-22bf319b76a4)
![Screenshot from 2024-01-03 11-52-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/b7aa31e7-97f1-40ec-a032-9ecb7d4f90df)

**Comment by AlaaElattar** [comment]
### Work In Progress(WIP):
- Working on validating if the hash exists or not before clicking on view button.
