### ISSUE TITLE
Unable to navigate any page

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#1850]
Sometimes, when the Dashboard tab is left, the user can't navigate to any page and the console is filled with unusual errors

### Steps to reproduce

- Go to https://staging.dashboard.dev.grid.tf/#/
- Connect your wallet
- Leave that tab for some time then try to navigate any page

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/db976f8d-ed73-42df-a20c-1ea5c7a1270b)

**Comment by ramezsaeed** [comment]
I think this only happens when a new code pushed to devnet; as refresh fix the problem and can see version changed.

**Comment by ramezsaeed** [comment]
Lets Re-open if reproduced on devnet dashboard
