### ISSUE TITLE
Replace dedicated chip in nodes page to be Rented

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1851]
### Description

- If the node is dedicated and rented, we show chip as rented instead of dedicated.
- We can add card for rent contracts and rented by whom.
- If node is dedicated and still available, we show it as dedicated.
- with that user will know which dedicated nodes are rented instead of rented tab in dedicated nodes page.

**Comment by mohamedamer453** [comment]
There's a type column that was added and for each node there's one of three options either the node is `Rented`, `Rentable`, or `Shared` and at the bottom of the table there's a legend that discusses the difference between the three types.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cb071ff7-08a9-497a-a45d-06b9ce2bdec6)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85
![Screenshot 2024-03-24 at 9 04 59 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/161cdb9b-76ac-4dab-a976-e3986d9c293c)
![Screenshot 2024-03-24 at 9 04 06 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/67dc62cc-8b65-433d-98ef-4c7b69eb6539)
dedicated chip is replaced with rented now
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4246384
