### ISSUE TITLE
Mainnet weblets: 

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-ts#186]
### Description

On entering a manual node id, the node is checked for resources based on the required resources. This check seems to be happening, but one a node seems to be ok there is no visual confirmation. If the node is not ok, there is a confirmation.

![image](https://user-images.githubusercontent.com/88312671/234514508-2e834e13-ee3a-415e-9161-20ebdd5dfbd8.png)

### Steps to reproduce

Full virtual machine -> enter resources -> manual node selection -> enter a node that you know will work -> you see a check happening but once ok no confirmation. In the past, it stated if a node was ok for deployment.

If you select a node that will not work:
![image](https://user-images.githubusercontent.com/88312671/234514779-caa831a5-e688-4dfb-a158-1cef157f6efe.png)

### Logs/Alerts

No obvious logs in the development tools

**Comment by xmonader** [comment]
should be fixed on the new playground, let's reverify

**Comment by mohamedamer453** [comment]
Node Selection was removed in the new playground and now the filtering is done with the country/farm.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b060c916-5118-4d7c-8d8a-6db7f56be1c2)

If the farm has nodes with enough resources it'll appear in the farm list and if it doesn't then another farm will be automatically selected, and if there are no farms with the desired resources then it will show the following message.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a6aad5fa-cb50-4c14-b1b8-7a5b0014e00c)
