### ISSUE TITLE
Reordering the sidebar

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1861]
```
- TFGrid
 - grid status
 - node statistics
 - node monitoring

- Deploy
 - Pricing Calculator
 - Node Finder
 - Virtual Machines
 - Dedicated Machines
 - Applications (the solutions)
 - Your Contracts
 - Images (0-hub)
 - SSHKey (remove it from the profile view and make it separate)

- Farms
 - farms
 - node installer (0-bootstrap)
 - Simulator

- TF Chain
 - My Profile
 - TF DAO
 - TF Token Bridge
 - TF Token Transfer
 - TF Minting Reports


-Manual
```

**Comment by amiraabouhadid** [comment]
@xmonader do you want the dashboard to still open to the My profile page(aka twin page)?

**Comment by xmonader** [comment]
> Is My profile page the twin page in the current playground?

Yes

> If yes, do you want the playground to still open to the My profile page (aka twin page)?

Yes

> For the Virtual Machines, do you want us to extract it from the Solutions (aka Applications)?

Yup, or at least make a direct link to it

> If yes, then do we remove the deployments table in the VM section of the solutions or do we have duplicates there and in the Virtual Machines page mentioned above?

Didn't get it I should still be able to list my deployments (VMs) if in separate or if it stays in Applications page too

**Comment by AhmedHanafy725** [comment]
@amiraabouhadid 
virtual machines should show the same grid cards as the applications.
virtual machines should  contain full vm and micro vm 
applications should contain the rest

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/6e10e839-9d2d-4b99-a12b-987e0e8edfc3)

**Comment by amiraabouhadid** [comment]
Addition:
under Deploy add an Orchestrators with Kubernetes and Caprover cards

**Comment by A-Harby** [comment]
> virtual machines should show the same grid cards as the applications.
> virtual machines should contain full vm and micro vm
> applications should contain the rest

Why are FullVM and MicroVM in both virtual machines and applications?
And the same for Caprover and Kubernetes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a66bf670-ed36-40ec-bf8d-6ac171cc1248)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/97895e96-eaa9-4e9f-84aa-4b3e871fda8a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6c24ce6c-e0f2-4b75-a825-f9030009e8fa)

**Comment by AhmedHanafy725** [comment]
agreed to remove them from the applications

**Comment by A-Harby** [comment]
Verified Devnet da46d82,

[TC2197 - Verify Sidebar](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150406)

The sidebar has been reordered, and FullVm, MicroVM, Caprover, and Kubernetes have been separated and removed from applications.

![photo_2024-01-08_13-46-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/909fdd87-88ca-4ff6-a0ea-86af181477c3)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0f3f0aa6-221a-4ee3-bc5a-9a881a4ed007)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- da46d82

**Comment by A-Harby** [comment]
The page Your farms, which contain the table of my farm and my nodes, aren't available for the new reordering.

This page, https://dashboard.dev.grid.tf/#/dashboard/farms, I can't find it here https://staging.dashboard.dev.grid.tf/#/dashboard/twin.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e8811a0-1e3b-4d1f-8f4e-362811cf76f5)

**Comment by A-Harby** [comment]
Verified, Devnet 5bf71ea.

[TC2197 - Verify Sidebar](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150406)

Your farms page is back.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aca65f26-fb54-45a7-85df-98b987b7ea1c)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-15 15-17-51](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ad200ca8-a7f3-4c12-b890-0f962d878cc4)
![Screenshot from 2024-01-15 15-17-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7934cb3c-425d-4fd2-bdb3-bcc1afb2820c)
