### ISSUE TITLE
separate profile page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1862]
when you login don't show anything, can maybe redirect to the profile page (in tfchain menu), it shouldn't include ssh keys

**Comment by AlaaElattar** [comment]
- Include QR code in profile page.

**Comment by ehab-hassan** [comment]
I think when the user login needs to go to something like home this

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/67f66d07-ddfc-46a9-9c0e-94006430f03a)

then he chooses to go to profile or anything else at the dashboard

**Comment by ehab-hassan** [comment]
which one is better here?

<img width="1920" alt="Frame 270" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/3a584d07-b508-4959-98aa-360cf1521542">
<img width="1920" alt="Frame 271" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/900acf30-cbf8-49b2-a8d1-9df86375aa44">

**Comment by ehab-hassan** [comment]
I prefer this one because the details is the same style of table, and it is easy to respond to mobile size

<img width="1920" alt="Frame 272 (1)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/8572079f-9663-4d45-831f-523be3205f90">

**Comment by MohamedElmdary** [comment]
actually when user login we shouldn't redirect him to some page ... imagine I sent your `nodes` page for example
when you login u will be redirected from /nodes and refresh will do that too 
doesn't make sense

**Comment by ehab-hassan** [comment]
https://www.figma.com/proto/PzOjPW17TZ9tO13DGNqdH7/profile?type=design&node-id=0-1&t=FRAGQsh5qzXAlyVS-0&scaling=min-zoom&page-id=0%3A1

**Comment by AhmedHanafy725** [comment]
part of this issue is to hide the login popup after login.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/9737796a-d751-40d9-acae-e9fee4283183)

**Comment by amiraabouhadid** [comment]
Work done:
- update profile page to this [design](https://www.figma.com/proto/PzOjPW17TZ9tO13DGNqdH7/profile?type=design&node-id=1-2&t=FRAGQsh5qzXAlyVS-0&scaling=min-zoom&page-id=0%3A1) 
- removed popup when user is logged in
Work in progress:
- update landing page to this [design ](https://www.figma.com/proto/KRuoLPftqoCykuHkbw6XmQ/Untitled?type=design&node-id=1-60&t=PDmRvccfShhr6B84-0&scaling=min-zoom&page-id=0%3A1)

**Comment by A-Harby** [comment]
> when you login don't show anything, can maybe redirect to the profile page (in tfchain menu), it shouldn't include ssh keys

From what I get from the issue and comment, the main purpose was to remove the login popup, but it still shows up with everything in it the same and the data (QR code, twin ID, and address) repeated in your profile page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/60a32666-e234-4af3-aa2e-32a832e0d536)

**Comment by xmonader** [comment]
So far this looks good, i want the popup to be hidden but that's in another issue according to @AlaaElattar

**Comment by AlaaElattar** [comment]
> So far this looks good, i want the popup to be hidden but that's in another issue according to @AlaaElattar

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1862

**Comment by A-Harby** [comment]
Verified, Devnet 21ef1d6.

The SSH key was removed, and login directs the user to the homepage (which will be important after closing the popup at https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1862).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1b968d59-7d38-4d0a-a007-275be36ba61f)

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 21ef1d6

now the profile page is more clear and separated from the ssh key.
and can be accessed from the home page or the side menu also.

![Screenshot from 2024-01-14 15-20-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b01fecc-0998-4a56-a175-89857e2b8987)
![Screenshot from 2024-01-14 15-20-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a26d7b56-d422-4f1d-b0c7-785f38514fe0)
![Screenshot from 2024-01-14 15-21-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/da9c57f5-ff95-40b1-bb18-dce3b415736d)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150323

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c
- no more pop-up when login

![Screenshot from 2024-01-15 15-11-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e7aa6a66-1065-4a25-9546-c53e27bbc05a)
![Screenshot from 2024-01-15 15-02-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0e1c3ea8-6911-4d4b-80e6-615a8b14db07)
