### ISSUE TITLE
calculator: default to the user balance

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1863]
should toggle on the user balance if the user is logged in

**Comment by AlaaElattar** [comment]
- Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1886
- there's bug in balance reflection in profile manager should be solved there.
- If someone sent tfts to me won't be reflected at same time in profile manager but if user opened calculator will be reflected in balance field.

**Comment by AlaaElattar** [comment]
### Work Completed:
- Get balance from `profileManagerController`.

**Comment by A-Harby** [comment]
Verified, 
- Devnet
- 3711f82
- [TC2284: The user can access calculator from the dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422341#case_4150493)

Tired with an account and balance toggle turned on and then without logging in, the balance toggle was off.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c109ea2-4344-4ac1-a715-d351feead3ab)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a8ae3f74-a6f0-4597-8ec3-456a318b3345)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-15 14-49-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/15aca240-16a3-43e3-9016-661d6f96f4e5)
