### ISSUE TITLE
nodes on mainnet are not loading

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1864]
maybe we should index healthy nodes (responsive ones) on the grid proxy

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/issues/603 

the proxy will provide another query param to help achieving that too

**Comment by Omarabdul3ziz** [comment]
work is done from the proxy side & deployed now on devnet.
changes:
- boolean field `healthy` is added on the `/nodes` and `/nodes/<id>` endpoint responses
- boolean query `healthy` is added on the node filters

`healthy=true` indicates that the node responded to an rmb call in the last 5 minutes

**Comment by khaledyoussef24** [comment]
should this query should be added to swagger ?

**Comment by khaledyoussef24** [comment]
the endpoint is working fine but i think it should be added to swagger too 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cc625bf2-9387-476e-b982-b3247dfec498)

**Comment by AlaaElattar** [comment]
- I opened this issue in tfgrid-go

**Comment by khaledyoussef24** [comment]
okay we shall close this for now since there is another issue for the swagger

testlodge
https://app.testlodge.com/a/26076/projects/40893/suites/211680?expand_section=354530#case_4189153
