### ISSUE TITLE
total ram, total disk, .. etc is confusing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1867]
is it total or min?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/90ffebea-30a2-4c3b-b035-ec6b5a1e70e2)

**Comment by AlaaElattar** [comment]
- In dedicated nodes page , remove total .

**Comment by mohamedamer453** [comment]
> So, Max, you mean what causes it to be more confusing now?

Indeed it's wrongly labeled, the correct label would be minimum since how it works is by filtering the number if it's less than or equal to the total amount.

Will update it soon

**Comment by A-Harby** [comment]
Verified, 
Devnet aac2542.

The label was changed to min instead of total.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1ae4cf44-7991-48f0-ba2d-a685b413f633)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a35c4a7f-5f22-44f0-a899-770aa0ee044d)

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-15 14-52-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8af4f8d0-f46a-4232-93a3-2d3c147c0181)
