### ISSUE TITLE
allow sorting on the usd price in dedicated nodes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1868]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0a60ce48-eed2-4c67-bfef-8fa83ef3216f)

are these prices before or after applying or discounts as well?

**Comment by AhmedHanafy725** [comment]
There are 2 options to do that
1- Get all nodes and do the sorting and filtering on the client side
2- Make gridproxy do the calculations. https://github.com/threefoldtech/tfgrid-sdk-go/issues/608

**Comment by AlaaElattar** [comment]
- Blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/608

**Comment by 0oM4R** [comment]
blocked on #2285

**Comment by A-Harby** [comment]
Devnet, 0d1e63f.

The node 161 has a value of 0.11 USD per month, and it is between 113 and 72 USD.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6138215e-0357-4b9a-8bc8-57e371292839)

So some cases are now covered maybe.

**Comment by MohamedElmdary** [comment]
@A-Harby it's 0.11 USD/hour not month
so 0.11 * 24 *30 = 79.2 USD/month so it's correct

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2773

> @A-Harby it's 0.11 USD/hour not month so 0.11 * 24 *30 = 79.2 USD/month so it's correct

**Comment by khaledyoussef24** [comment]
verified on devnet
version: 17d861b


User should be able to sort nodes by price from high to low and low to high



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e44bc178-b88b-4adb-b543-a078e38f7bf2)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/990fdd3d-28be-46dc-80af-2559f9b6f2ca)
