### ISSUE TITLE
regions don't exist in the nodes view filters

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1869]
need to add region in the filters too

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1877

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:
- Added the `region` query in the `proxyClient` package.
### Work in Progress (WIP):
Detail all ongoing efforts and remaining tasks related to this issue. Clearly outline the items that are currently being worked on and those that still need to be addressed.

### Investigation and Solution:
If there has been no work completed or work in progress, elaborate on the investigative work undertaken to address the issue. Provide insights into the problem and, if a solution was reached, include it.

**Comment by A-Harby** [comment]
Can you change this input into list selection (as node status) since all the regions are already specified and can't be changed, and it's better for the UX?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2402e2e7-0570-4252-b81c-39724b383be4)

**Comment by 0oM4R** [comment]
> Can you change this input into list selection (as node status) since all the regions are already specified and can't be changed, and it's better for the UX?
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/296547236-2402e2e7-0570-4252-b81c-39724b383be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDk3OTMsIm5iZiI6MTcwNTMwOTQ5MywicGF0aCI6Ii8xMDk0NzM4NzMvMjk2NTQ3MjM2LTI0MDJlMmU3LTA1NzAtNDI1Mi1iODFjLTM5NzI0YjM4M2JlNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwOTA0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTdjZDdkMDY5ZmQ0OWU2Y2E3MjU0NTg0N2Q3YWMxYTk3ODhkNjAyZjVhMTgwZjE5ZTRmZDU5ZTIxOTQxMDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ySZEQoYXTemiCg3fqKETP_3h7sTj68O-Wu05kt0AyG4)

in #1975 I used the same components as the node selector.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 9d076f1

regions are now available in filters
choosing as a list makes filtering much easier
<img width="242" alt="Screenshot 2024-01-23 at 9 19 11 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ab2224f9-c94d-4c26-b1aa-20842c86c72b">

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150464

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-24 15-08-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/29eab4d1-9b9f-4db1-b971-7f5fcd0e35e2)
