### ISSUE TITLE
load Nodes buttun should retun an error if the selected farm doesn't have a node with the needed resources

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1870]
### Description

load nodes button doesn't retun any feedback if the selected farm doesn't have a node with the needed resources

### Steps to reproduce
- Go to solution tab
- select Micro VM
- select freefarm
- press load nodes (working fine and automatically select a node)
- go back and change the farm to select animalfarm
- press load nodes (can't find a node)

### Fix
A clear message should be shown to the user:
" this farm doesn't have a node with the needed resources.!"

### Logs/Alerts

![Screenshot from 2024-01-03 16-23-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8b0f2271-a43d-4839-8be1-4ee35d0921ca)

**Comment by A-Harby** [comment]
Verified, Devnet 21ef1d6.

[TC2460 - Filter a farm with no online nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4177820)

If the farm doesn't have any nodes, a red warning error will appear with the message 'No nodes were found!'.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/dc239b5c-bcc1-43e4-b9d7-a2e08b4e5d2b)

**Comment by ramezsaeed** [comment]
Verified:
- devnet
- b43ea4c

![Screenshot from 2024-01-15 15-33-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/939c1536-e6b6-46c2-ae6a-ef0c1aba10fc)
