### ISSUE TITLE
you can not transfer new added balance while you are in transfer page

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1871]
env used   :devnet
version : f83227f
### Description

you can not transfer new added balance in transfer page unless you used refresh or to go to another page then return to the transfer page

### Steps to reproduce

1. go to the dashboard
2. go to transfer
3. used get tft
4. check that the balance added
5. try to transfer this balance
6. you can not use the balance unless you refresh the page

[Screencast from 01-03-2024 04:38:55 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c84fbe33-7e02-44d3-9c32-015b274100e9)

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : e2fa190
[Screencast from 01-08-2024 12:52:45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5971e179-aca0-43f3-b5dd-4a7f8dab4fa1)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4169741

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- da46d82
