### ISSUE TITLE
Verifiy what happens to billing pakages after the TFT amount decreased

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1875]
- while renting a node yo get offer packages depends on the TFT amoun balance (silver, gold, ...)
- its not clear enough to the user that this packages are hourly calculated which means in the next hout if the amount of TFT decreased the user will be billed with the default price.
- this must be clear in the package information for the user as user expect the discount for a month not hourly.

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1879

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1880

**Comment by A-Harby** [comment]
Verified,
- Devnet 
- 2.3.0-alpha5.
- [TC2453 - Discount package](https://app.testlodge.com/a/26076/projects/40893/suites/204782?expand_section=335850#case_4168218)


I tried with a 4000 TFT balance and had a discount on the node while renting it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1fdf13f0-f2f0-40ac-928a-df8b70f22a99)
Then I transferred all the balance, and the node value was brought back to its original value.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/83e1fc33-a8d2-483c-8ec5-c0d2ac6173c9)
And after that, I increased the balance more (7000 TFT) and had a higher discount than the first time.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bdc931df-af60-4ea9-af56-212e8f8752dd)

**Comment by Mik-TF** [comment]
"its not clear enough to the user that this packages are hourly calculated which means in the next hout if the amount of TFT decreased the user will be billed with the default price."

Very good point.

Two things to add here:

First, we could then add a clear statement on this fact in the manual, [here](https://www.manual.grid.tf/wiki/cloudunits/pricing/pricing.html?highlight=discount#staking-discount). I will create an issue in info_grid.

Second, there is a proposition to add a calculator to take into account hourly calculated discount, see #773. This would make it easy for users to check the discount available.

**Comment by A-Harby** [comment]
The two issues, https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1879 and https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1880 were verified and closed.

And the PR is merged.
