### ISSUE TITLE
Create home page after login

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1878]
Design a new page to redirect the user to it after logging in. This page should contain quick navigations to: 
- Deploy virtual machines
- Deploy applications
- Explore the grid capacity
- Explore grid nodes
- My profile

**Comment by ehab-hassan** [comment]
Working in progress

**Comment by ehab-hassan** [comment]
option1
https://www.figma.com/proto/KRuoLPftqoCykuHkbw6XmQ/Untitled?type=design&node-id=1-60&t=PDmRvccfShhr6B84-0&scaling=min-zoom&page-id=0%3A1

option2
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?type=design&node-id=529-1888&t=nwQokxvUNfKTnEKP-0&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A1248

**Comment by ehab-hassan** [comment]
according to the vote at the telegram, all agreed on option 1
https://www.figma.com/proto/KRuoLPftqoCykuHkbw6XmQ/Untitled?type=design&node-id=1-60&t=PDmRvccfShhr6B84-0&scaling=min-zoom&page-id=0%3A1

**Comment by A-Harby** [comment]
Verified, 
Devnet 21ef1d6.

[TC2457 - Homepage before login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177817)
[TC2458 - Homepage after login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177818)

The homepage is added after login, including your profile, deploy virtual machines, deploy applications, deploy orchestrators, explore grid capacity, and explore grid nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7401a141-e047-42ef-bb42-fea14e8289bb)

**Comment by ramezsaeed** [comment]
Verified:
- Devent
- b43ea4c


![Screenshot from 2024-01-15 15-11-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/73deded4-5806-455a-9884-9d2734fe729c)
