### ISSUE TITLE
Update The discount levels link in Dedicated node page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1879]
### Description

Devnet.

The discount levels link is outdated.
https://manual.grid.tf/cloud/cloudunits_pricing.html#staking-discount
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26d3a593-a668-40eb-a861-7074d1bd708e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/95ea1156-8e86-4dfe-b78a-4d3512a76a40)

**Comment by AhmedHanafy725** [comment]
let's use this one https://manual.grid.tf/wiki/cloudunits/pricing/staking_discount_levels.html#staking-discount-levels and also change `discount levels` to `staking discounts`

**Comment by khaledyoussef24** [comment]
enviroment used : devnet
version used : 7f4d8ea
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8fba96ef-55b5-4cab-af6d-e0c12ec2f791)
links also are working correctly
https://manual.grid.tf/wiki/cloudunits/pricing/staking_discount_levels.html#staking-discount-levels
https://manual.grid.tf/dashboard/portal/dashboard_portal_dedicated_nodes.html#billing--pricing

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150429

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7f4d8ea

![Screenshot from 2024-01-08 12-37-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/31e1f07c-d2f4-4e03-a4ce-88ac693d7f91)
