### ISSUE TITLE
Discount level on the dedicate node isn't updating

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1880]
### Description

Devnet, 2.3.0-alpha5.

I found an issue that the discount level isn't updated on the dedicated node, despite that the value itself is changed with a different TFT balance amount.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/08960d7f-c636-4515-b8b8-d08ca84886e8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cf2847d8-3cf6-4882-b31d-44063a3d4108)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work in Progress (WIP):

I am still investigating this issue. The strange thing is that the discount level is working correctly in the [Devnet Dashboard](https://dashboard.dev.grid.tf/#/dashboard/dedicated-nodes), but not in the Development branch code.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Investigation and Solution:
- An unnecessary condition was causing the discount level to always display as 0%. This condition has now been removed.

**Comment by Mahmoud-Emad** [comment]
## Issue update

After my call with @khaledyoussef24, we found out that the discount only applied to the first machine when the balance reached 4500TFT. We suspect there is an issue with the discount calculation and I'm currently investigating.

**Comment by Mahmoud-Emad** [comment]
I've tried the scenario you mentioned and it seems to be working as expected. Please take a look at the screencast I recorded at 11:46 AM on January 16th, 2024 https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/2e3a7ad8-59f8-4d0f-902e-766cd6d8b382. 

I want to clarify that it's not just the first node that is reflected, but each node has its package - either `none`, `default`, `bronze`, `silver`, or `gold`. As a result, you receive a discount based on your package's price.

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work completed

The issue should be fixed in [#2022](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2022), the issue was in the dedicated package discount, we were using the shared package discount

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9d076f1
![Screenshot from 2024-01-22 23-20-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e7759927-d868-4aa1-881c-86e185ec0bc7)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4187678

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-24 15-28-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/88f72b3c-807c-4407-90a5-2b7624f6fc2b)
