### ISSUE TITLE
Enhancement Request: Implementing Multiple SSH Keys with Enhanced Management Features

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1882]
### Description

The current SSH key page offers limited functionality with support for only a single SSH key. To improve user experience and flexibility, I propose the implementation of a feature that allows users to manage multiple SSH keys.

**Enhancements Proposed**

1. **Multiple SSH Keys:**
   - Users should be able to save and manage more than one SSH key.
   - The option to activate only one SSH key at a time should be available.

2. **Key Activation:**
   - Users can easily switch between SSH keys and activate/deactivate one.
   - Each SSH key should have a generated fingerprint, and users must enter the fingerprint when activating a key.

3. **Adding SSH Keys:**
   - Users should have the ability to add multiple SSH keys with no set limitations.

4. **Deletion Options:**
   - Users can delete individual SSH keys.
   - Batch deletion should be supported, allowing users to select multiple keys for deletion.

**Benefits:**
- Enhanced flexibility in managing multiple SSH keys.
- Improved security with unique fingerprints for each key.
- Streamlined user experience with the ability to add, activate, and delete keys conveniently.

**Additional Context:**
This enhancement aims to provide users with a more robust and user-friendly interface for managing their SSH keys, catering to scenarios where multiple keys are used for different purposes.

Here are some designs we can stand for generating our design by @ehab-hassan 

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/d06144ca-87ee-4ba8-bc44-ba968ceb1253)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/cc94ff19-d460-47b6-bd5b-8e269732c673)

**Comment by AhmedHanafy725** [comment]
after trying to deploy a vm with more than one ssh key, it works fine. Just set the sshkey env var with all required sshkeys separated by `\n`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/f922f623-b626-4f1b-98e1-2c241c38cdc3)

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work in progress

Working on the design of adding the multiple ssh-keys feature

[Screencast from 03-18-2024 04:59:50 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/d273ed5c-8e4c-4668-b08f-caf7fbe02cd9)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:

- Implemented a helper function to generate a unique name for the generated key, enhancing the user experience by providing descriptive names.
- Added activation and deletion logic, enabling users to activate or deactivate keys and delete them when necessary.
- Developed the feature to delete all selected keys, with preparations underway to delete keys based on types such as active or all keys.

### Work in Progress (WIP):

- Refining the deletion process to ensure seamless removal of keys based on user-selected types (active or all keys).
- Testing the functionality to ensure proper activation, deactivation, and deletion of keys across different scenarios.

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work in progress

during the call with @ehab-hassan we have updated the whole style of the view to be like that

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/68ff981c-1a95-40ce-b4fc-014368165ef2)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/48d9cd26-379f-4527-9645-e2e9e4129574)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b26087f2-71ea-422f-9c7b-8799bcb3ba47)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/75fbfbcc-f78c-423e-a4b8-d5da1e9f2d5f)

**Comment by Mahmoud-Emad** [comment]
Issue Update:

Work in Progress (WIP):

1. Enhanced the UI by adding a new dialog for importing SSH keys and updating the colors of the table.
2. Calculated the SSH key fingerprint, consolidated form dialogs, and introduced a key details dialog. Also removed a redundant dialog.
3. Refined the copy input wrapper to conditionally display the copy icon based on field data presence and improved the functionality of the generate dialog.


- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/01440a42-acc5-4c0a-bee5-d91b86094c27)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/edbe6fba-d9c4-4191-854a-6cdf0821ad25)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/9e3ce9f2-9d81-4275-938f-6071124c966b)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed

- Resolved the issue related to saving the SSH key in the chain.
- Implemented loading of SSH keys directly from the chain, eliminating the use of dummy data.

### Work in Progress

- Implementing the functionality to display all keys when deploying a deployment, with the requirement that `active keys` must be selected.
- Working on updating the chain appropriately when activating, deactivating, or deleting any key to maintain data integrity.
- Planning to remove the `fingerprint` from the chain data and calculate it dynamically during loading from the chain instead of storing it directly.
- Addressing the issue related to the "Close" button in the SSH dialog view to ensure proper functionality.

**Comment by Mahmoud-Emad** [comment]
Working on https://github.com/codescalers/CSHR/issues/353#issuecomment-2019144595

**Comment by Mahmoud-Emad** [comment]
## Issue Update:

### Work Completed:
- Implemented a helper function to generate a name for the generated key to be saved with the key.
- Added activation and deletion logic for SSH keys.
- Worked on the feature to delete all selected keys, preparing to delete keys based on types like active or all keys.
- Unified UI elements by removing the tonal theme from cards to maintain consistency with the contracts list view.
- Enhanced UI by adding another dialog for importing SSH keys and updated the colors of the table.
- Calculated SSH key fingerprints, consolidated form dialogs, and introduced a key details dialog while removing redundant dialog.
- Refined the copy input wrapper to conditionally display the copy icon based on field data presence and improved the functionality of the generate dialog.
- Migrated old SSH keys to the new SSH key type and set them as active keys.
- Fixed the issue when saving SSH keys by loading them from the chain instead. Work in progress on updating the chain when pressing on active/inactive or deleting keys.
- Enhanced the way of saving/removing the keys and improved the import key form by adding a rule to validate the entered SSH key.
- Merged SSH key management functionality into all applications.

**Comment by khaledyoussef24** [comment]
@Mahmoud-Emad @samaradel 
the id also was duplicated after this issue
<img width="126" alt="Screenshot 2024-04-15 at 3 47 37 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/13a4c8d9-7d18-4351-a8d2-b9df691cd047">

**Comment by khaledyoussef24** [comment]
verified on devnet
version : dd92950
User now can have more than key
he can activate which keys are active for deployments , manage keys before deploying


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e9fbbd0e-19c7-41d3-95d1-63a1ce9806b8)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/53f09e48-d5d4-4596-9772-60a8f8a53113)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db7ba150-64d1-4464-b277-434182f4d83d)

provided tests covering it
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#suite_section_430164

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- e7030e6
