### ISSUE TITLE
Update routes to match new sidebar

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#1883]
### Description

Need to update routes throughout the new playground to match new sidebar in #1861

**Comment by A-Harby** [comment]
[Screencast from 01-08-2024 01:50:45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/be602047-9e55-4a85-a967-a638a5eb0a65)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work in Progress
Currently engaged in the process of replacing hardcoded routes throughout the application. The strategy involves creating an interface to consolidate and manage all route values.

**Comment by Mahmoud-Emad** [comment]
### Issue Update

**Work Completed:**
- Updated routes to match the new sidebar in #1861.
- Documentation for the updated routes.

**Work in Progress (WIP):**
- Additional testing to ensure the routes align with the new sidebar is ongoing.

**Investigation and Solution:**
- Investigated the changes in the new sidebar layout introduced in #1861.
- Identified the routes that needed to be updated to align with the new sidebar structure.
- The solution involved modifying existing routes to match the new sidebar.

**Comment by khaledyoussef24** [comment]
verified on devnet version : bee662d
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 09 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/71562203-8c8d-4ff5-b4d0-ff9ba9757615">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 14 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2912d3cb-96b8-48c3-ace8-dd8b36b36347">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 16 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/718ade68-a231-4422-a7b2-eb9d5a66d147">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 18 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0482f825-4ebc-45d0-9501-6127da11f83f">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 34 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/57c4e038-16cc-4b06-91e7-e5ff6e1bbc58">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 38 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4353d4cf-4203-40cc-a7e9-722e9ecd5e03">
<img width="1680" alt="Screenshot 2024-03-26 at 2 06 42 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b23ef130-4b28-4933-ad99-939e9611d2ab">
<img width="1680" alt="Screenshot 2024-03-26 at 2 12 58 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ecb630f7-ce7a-4ec3-aa75-e4e53ef788fc">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 07 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/386096e8-2318-4880-a1a3-7f15f0e0c956">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 17 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ac64dbe5-1a95-4988-b41c-7f4311fa3699">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 21 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d934576a-8e73-49e4-a44a-6ed9cea7c40b">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/62798c5f-0799-4435-bc8a-34e91a6b6cf5">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 32 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/15ba924f-d09f-44a2-919c-0e94238f4ec2">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 36 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a049d614-b754-4e3f-8d3a-acf8e40bf4dd">
<img width="1680" alt="Screenshot 2024-03-26 at 2 13 45 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7f8b59e4-c5c4-42f6-8b2c-c62d30776c97">
