### ISSUE TITLE
can't use the same GPU card after deleting the Vm that was using it

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1889]
### Description

Devnet.

I rented a dedicated node, deployed a FullVM on it, and used the GPU card of that node.
And after that, I deleted the VM, and then I tried to deploy another VM, but I couldn't because the old VM that I deleted is still on it.

Node ID: 154

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ac858676-889f-49bf-8f08-8e57021b2c37

**Comment by A-Harby** [comment]
Update:
I checked today, and I found that I can deploy on the GPU card again, but I don't know why it wasn't free the last time or how long it took to be freed, but it was not less than 2 hours.

**Comment by AlaaElattar** [comment]
- This should be solved from zos https://github.com/threefoldtech/zos/issues/2180

**Comment by xmonader** [comment]
While videos are appreciated, zos didn't continue the investigation for the lack of the data e.g contract id, which i found was in the video. I'll close and let's reopen if happens again
