### ISSUE TITLE
find a better way to show the dedicated node discount info notification

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1892]
in the dedicated node page;
I need to put the mouse on the price to see the discount info notification.
for someone doesn't know there is discount already he may not put the mouse on the price, and will end up he doesn't know there is even a discount available.

![Screenshot from 2024-01-08 12-37-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/74d3d593-a44d-4d1f-811f-ac91cb4edc3a)

**Comment by zaelgohary** [comment]
Should be done in the node finder.

**Comment by ehab-hassan** [comment]
maybe we can show a chip of the discount or just icon if there is a discount in this node and show a tooltip when hovering on it.

![Group 2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/02909a2d-e5fe-4d68-b65f-361d904a2361)

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
I think ll just icon beside the price.
Icon added but may will add a small animation(scale in/out) to get the user's attention.

**Comment by ehab-hassan** [comment]
Work Completed

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/aabb39a1-9753-45b8-b9a0-4b9bd25dc215

**Comment by ehab-hassan** [comment]
Work in Progress 
Figuring out how to make discounts at the dedicated node

**Comment by A-Harby** [comment]
discount is a lot more noticeable now than before, and different packages are applied with changing balances.
But the discount doesn't change if I log in or connect my wallet until I refresh the page and reset the filters.
And the same happens with logout.

[screen-capture (4).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/98d82dcd-ca4c-4734-9c0c-70071422c8da)

**Comment by ehab-hassan** [comment]
@A-Harby this is related to another issue here #1978

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 17d861b


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c43ecab4-ff36-49c9-8fea-f65cb96ef9f8)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e7216095-b7e1-442e-a7ec-cdfb30454721)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4288616
