### ISSUE TITLE
when clicking on any hint  in the profile manager it collapse

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1894]
### Description

when clicking on the hint for the ssh in the profile manager it collapse

### Steps to reproduce
env used : dev
version : da46d82

1. open the profile manager 
2. try to click on any helping text
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b99fee7c-4dff-4ee1-9f04-67bfaf2066d1)

3. the profile manager window collapse

[Screencast from 01-08-2024 01:25:30 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/44149d36-8612-4982-80a7-0e87faa80ab8)

should the profile manager react this way ?

**Comment by zaelgohary** [comment]
I could select the hint text multiple times and the profile did not close. @khaledyoussef24 Can you verify if the issue is still happening?

[profile-manager.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a82da718-1b3d-4059-ae38-2754e4a2dce8)

**Comment by khaledyoussef24** [comment]
the issue is no longer producible. 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/10710fa9-3fee-45f4-a580-b0919c4fd917)
