### ISSUE TITLE
after creating a new account can we add a url to add my ssh key

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1895]
### Description

after creating a new user can we add a url redirecting to ssh tab to add my publick key or in the warning message to failed deployment 
`you must provide a ssh key to deploy , go to deploy > ssh key to add your public key 
`
![Screenshot from 2024-01-08 13-29-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e35838ca-822b-401c-b7e4-b8a32901f8b7)
![Screenshot from 2024-01-08 13-24-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9730cee8-7cc2-45ad-9ed3-4ae741b4bac8)

![Screenshot from 2024-01-08 13-30-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e4accd41-83f7-4692-bb15-0dabcbe1be41)

and there is a typo in the warning 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5d5c8b10-c781-4af1-b199-599fd2343112)
 `a ssh key` instead of `an ssh key`

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 55f7c3d
verified 
![Screenshot from 2024-01-11 17-55-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e1b9e791-f5a3-4f2c-8e42-8e269f8f0ca7)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177816

**Comment by ramezsaeed** [comment]
Verified:
- devnet
- b43ea4c
- Now the message shown when try to deploy in any deployment page.
