### ISSUE TITLE
[Calculator] errors in console while typing.

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1899]
if the user removed the current value to type a new one in balance field 
it logs an error to console, and if the user moved to other fields this cause unwanted behavior.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/5d45ac81-244a-48e7-9b41-23ccfb6ce314)

Suggestion: 
prevent calculating the price if the balance is not a valid value

**Comment by AlaaElattar** [comment]
### Work In Progress : 
- Found why this happens but still trying multiple solutions.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : f530d72
console error no longer appears while typing.
<img width="1680" alt="Screenshot 2024-03-30 at 12 50 31 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4ca4bb60-d9bc-49d4-a330-57aa30317154">
<img width="1675" alt="Screenshot 2024-03-30 at 12 50 49 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f5820a29-c909-4dda-aa45-06c22bf9ce75">
