### ISSUE TITLE
Set max length for input fields if possible 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1900]
in calculator while testing an issue it tried to type a huge number, there is no limit I don't know if it is acceptable or not.

[Screencast from 08 ينا, 2024 EET 04:36:29 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0e8894ca-d00a-4887-b215-9b7def577faf)

**Comment by AlaaElattar** [comment]
### Work Completed:
- added max length to each field equal to length of its maximum value

**Comment by khaledyoussef24** [comment]
verified there is a max validation for all the fields now 
![Screenshot from 2024-01-22 09-41-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/07d20915-ef0c-40db-b582-9c5e7fb34a6e)
![Screenshot from 2024-01-22 09-41-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/387a17e2-f85c-4de8-83c5-6c2657f0d992)
![Screenshot from 2024-01-22 09-40-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d5417949-3520-4bc4-9173-a4f21e43297a)
![Screenshot from 2024-01-22 09-40-47](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9ab27d8e-8f07-4f23-b2d2-93160ce36d28)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150494
