### ISSUE TITLE
Country field: to autocomplete or to be a dropdown

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1901]
Instead of `Country full name` and to make it clear the country names in English, I suggest we show the available choices as a dropdown

**Comment by 0oM4R** [comment]
Work completed:
we decided to use the farm and location components, and it done at https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1915

Investigation and Solution:
waiting for #1877 to avoid conflicts on nodes and farms pages

**Comment by 0oM4R** [comment]
Work completed:
Applied for node finder 

Investigation and Solution:
will add those fields to farm finder page

**Comment by 0oM4R** [comment]
### Work Completed:
we decided that the current logic will not scale as wanted, we drafted the old pr and now we are enhancing the filters, almost done.

### Investigation and solution:
- will apply the new filters to the dedicated machine page 
- add query route to the filter component

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b55dd4
countries are now drop down menu
verified scenarios, you can not insert an unknown or unrecognized name.
[Screencast from 24 ينا, 2024 EET 07:34:51 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b12745fe-c922-4197-bae8-3037cecd73e6)
![Screenshot from 2024-01-24 07-34-43](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/47ad7b18-641a-42fb-8597-cec73ba95f99)
![Screenshot from 2024-01-24 07-34-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4c61ace7-34cd-433c-a27e-c6f14042a84c)
