### ISSUE TITLE
The country and farm name filter should have auto complete

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1902]
this should be applied on all pages

**Comment by 0oM4R** [comment]
this issue is blocked on #1877, need to be merged first to apply this feature

**Comment by 0oM4R** [comment]
Work completed:
Applied for node finder 

Investigation and Solution:
will add those fields to farm finder page

**Comment by 0oM4R** [comment]
### Work Completed:
we decided that the current logic will not scale as wanted, we drafted the old pr and now we are enhancing the filters, almost done.

### Investigation and solution:
- will apply the new filters to the dedicated machine page 
- add query route to the filter component

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b55dd4
farm names are auto completed and you can not insert unrecognized farm name
for the nodes the countries now are in a drop down menu
[Screencast from 23 ينا, 2024 EET 08:31:08 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/450c206a-5f77-47cb-80bb-ef2c8fa5e0f6)

[Screencast from 23 ينا, 2024 EET 08:37:54 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf69eeb6-1825-45ea-a7ee-0c7a4e7eb5eb)
![Screenshot from 2024-01-23 20-37-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39d0187c-8f81-43e4-8c87-586b7baf4acc)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-24 15-08-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/17ddaae9-2512-4da6-9b81-72e34c290462)
