### ISSUE TITLE
Improve UX when loading deployments fails

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#1907]
An error like this can occur in the Playground when loading deployment info:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/53939207-8f83-4b02-8ba5-3ebbfc1278bc)

To me, the UX here can be improved on the following points:

* The message on the bottom says no deployments found, when actually it's just an issue loading the details
* It's possible to see details about the contracts for which loading deployment data failed by clicking the document icon on the right side, but that's not obvious
* There's no way to retry without reloading the whole page

I think an approach more like the contracts page would be good here:

* When loading deployment details fails, still show them in the list with the data retrieved from querying the contracts (probably just the name)
* Replace the document icon with a retry button that retries any deployments that failed to load
* Add per deployment retry button for the failed ones (this would be a bonus, but could be nice for the case where user just cares to get some info on a single deployment)

**Comment by Mik-TF** [comment]
Data point: I had this exact same warning message on different deployments and refreshing the page worked.

**Comment by A-Harby** [comment]
A reload button has been added to the table to only reload the deployment, not the whole page.

But the failed to load icon is still not clear to the user that it is a clickable button to show the failed to load contracts.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2cb6dce-9719-413f-99b0-c6a14e52eb4a)

**Comment by A-Harby** [comment]
Verified, devnet 9280a08.

The failed icon has been changed with the reload button to refresh only the list without needing to reload the whole page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/636f5291-9038-41f4-b865-6b6f41687628)

[TC2162 - List Deployments](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4150371)

**Comment by A-Harby** [comment]
Verified, devnet 9280a08.

The failed icon has been changed with the reload button to refresh only the list without needing to reload the whole page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/636f5291-9038-41f4-b865-6b6f41687628)

[TC2162 - List Deployments](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4150371)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 48a660d
