### ISSUE TITLE
Use farm name instead of the shared farm in the node selection

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1909]
![Screenshot from 2024-01-10 11-10-00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/73428cd0-d90d-41c3-ae0b-c795cbb2efa9)

**Comment by A-Harby** [comment]
Verified, 
Devnet, 5b50681.

[TC2461 - Node details in Load Nodes List](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422336#case_4177821)

The farm name is now displayed on the node.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7449ce54-33e9-487b-8aba-b662a9569f69)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a9b0699e-7880-4658-9db5-e450fb1ef811)

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet (Ninja)
- 2.3.0-alpha6

![Screenshot from 2024-01-22 13-08-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/53a0854f-2503-48ab-acf6-2e1302d1a2fe)
