### ISSUE TITLE
Use node's healthy query while filtering nodes for deployments

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1910]
check https://github.com/threefoldtech/tfgrid-sdk-go/issues/603

it's available as a query and a field on the nodes endpoint as well

**Comment by A-Harby** [comment]
Verified,
Devnet, 5b50681.

[TC2429 - load node button](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4160499)

The health = true endpoint was added to the load nodes request.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/151dbe4a-8781-4b74-9890-2bd398f1ba18)
