### ISSUE TITLE
Update gridproxy client with the new added filters & fields

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1911]
`healthy` and `farmName` fields have been added to the nodes' endpoint.

`healthy` query has been added to the nodes' endpoint

**Comment by A-Harby** [comment]
It has been added, but it has not been used. Why?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a23076ac-e332-4bb2-abb6-8c7f1ea1bb16)

**Comment by AhmedHanafy725** [comment]
The `farmName` is added in the response data, not in the request. Also, the farm name is not used as the dashboard uses the `farm_id` while requesting which will lead to the same result.

**Comment by A-Harby** [comment]
Verified, Devnet, e567b7d.

The endpoint has been added, so the farm name and health are in the response.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e7d75c9d-849c-4d59-8747-d2aecee981e6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/52d42feb-f674-47be-9a65-0ca7283a77a3)
And it have been added in the node selector.
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/dcff5c1ac277fa664983db1f05cb8dc1414750a5/packages/playground/src/utils/nodeSelector.ts#L167
