### ISSUE TITLE
need some explanation for the keytype

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1916]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/533e7493-3b7e-4b72-b46f-b4a734bad2f8)

there's no info/hint about that dropbox and at the very bottom there's a note about keytypes

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d1adef48-6c2d-4961-9bf9-71d52a34940a)

**Comment by AlaaElattar** [comment]
- Include latest alert in the first one. (same msg)

**Comment by AlaaElattar** [comment]
- Add label to dropdown list `Keypair Type`

**Comment by khaledyoussef24** [comment]
verenv used : devnet
version : 

keypair label added
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dd3a7b6c-2edb-4c5f-aa12-81bdb66c5e8a)

no  other alert will be added ?

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c


![Screenshot from 2024-01-16 15-04-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0beed9c5-b997-428b-a47a-ad5de5ca4838)
