### ISSUE TITLE
TF DAO: is it executed or executable?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1917]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/28c056e8-4658-4841-8ca8-fef6d9b0bf8f)

**Comment by AlaaElattar** [comment]
- The voting is over, but still there's no action.
- That's why its called executable.

**Comment by xmonader** [comment]
Thank you!
