### ISSUE TITLE
Inform the user that they will be interacting with the bridge and link its docs and linkable address

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1918]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3dc11849-c4a9-4057-aaab-41d3aa27d449)

The user needs to know what that address if for so 
- add `to the bridge` after deposit
- add link to the account on stellarexpert
- add link to docs of threefoldtech on manual to assure the user he is working against reliable information about that centralized bridge

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4cc87517-3a7e-40e9-8e9d-0aca6c2cd34f)
[Screencast from 22 ينا, 2024 EET 06:24:16 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d37c2c44-b0f1-4dff-84ba-ca284dce739e)
stellar account
![Screenshot from 2024-01-22 18-25-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4fc91ba1-57b2-4f2c-b082-fc54aa0c6b5c)
![Screenshot from 2024-01-22 18-25-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/582a18a8-ddaf-4b07-8abc-7f3066be13c0)

learn more docs : 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bc8cc5fc-de49-423d-92bc-ceb2640f92d8)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150411
