### ISSUE TITLE
Invalid twin ID message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1919]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3c5c3571-49c7-483e-9519-79e4dfacee43)

the rest of the message seems a little bit off

**Comment by AlaaElattar** [comment]
- u may add `This twin id doesn't exist`.

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 755bfa4

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a0b53c0-d9f5-4624-824e-dfba4e62ef04)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-16 10-06-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/456264c5-5c86-421b-8cea-f3d60c36df73)
