### ISSUE TITLE
not easy to copy my balance information

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1921]
it immediately shows the popup but i also still can't see it in the popup and not easy to copy at all

**Comment by MohamedElmdary** [comment]
We can add balance as input(readonly) in popup

**Comment by AlaaElattar** [comment]
### Work In Progress:
- working on adding in in profile manager dialog.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85
you can now copy your balance from the profile manager dialogue


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/245739d0-a8e3-477c-a13a-1a181591d461)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06633bfa-8639-4bd9-a04b-c35184691fa9)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150326

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622
