### ISSUE TITLE
Change my farms to Your farms

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1922]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/7ef6dd89-58b5-4146-a2af-3db117cbb4fd)

**Comment by khaledyoussef24** [comment]
verified and fixed
env used : devnet
version : 21ef1d6
![Screenshot from 2024-01-14 14-17-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a10bcafc-7de0-440e-a987-0eb116d92e21)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-16 10-04-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1f12b5c8-5933-427d-b815-6ae7732c10e2)
