### ISSUE TITLE
add more hints to sidebar items 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1923]
it does a great job for things like node installer but probably need more hints on the rest

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : 755bfa4
![Screenshot from 2024-01-15 14-32-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a1793ca9-3853-46f9-b624-31c3b024c06c)
![Screenshot from 2024-01-15 14-32-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1b9aa6f9-ebae-4db4-8641-ba3fa382b7b3)
![Screenshot from 2024-01-15 14-32-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ec0c4462-b10c-47da-84ba-42d14a13ab1c)
![Screenshot from 2024-01-15 14-32-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/225b486d-68b0-4e3c-937b-ac57e1f95c5a)
![Screenshot from 2024-01-15 14-32-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/978b6bcf-ce35-48f6-8413-861ad5d465d3)
![Screenshot from 2024-01-15 14-32-34](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d955e46b-b64f-4b74-b3ac-d331e69b9b88)
![Screenshot from 2024-01-15 14-32-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/374869f5-e50d-42fd-a20f-c1dbde18bf8d)
![Screenshot from 2024-01-15 14-32-26](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/08112456-082d-47df-a08f-03457a4bf6e7)
![Screenshot from 2024-01-15 14-32-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2d5193ae-d61c-4ce3-b511-992abe216f3a)
![Screenshot from 2024-01-15 14-32-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a1870f4-155b-49d3-88ad-576a843e6ce3)
![Screenshot from 2024-01-15 14-32-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5318c551-5f30-40bf-9c95-dc6e3718d7f9)
![Screenshot from 2024-01-15 14-32-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d22bda67-8020-45b9-b150-fe362c42ea80)
