### ISSUE TITLE
add instructions on how to access the vm after deployment

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1925]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/9e1d62a7-0708-456e-bc7e-208e90a47544)

So i just deployed a vm, but i don't know how should i access it e.g which user to connect with 

from the tests chat

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/643ff981-c1e6-4113-990a-263ad2537f6b)

**Comment by AlaaElattar** [comment]
- We should explain to user that vms or k8s can be accessed through public ipv4 or public ipv6 or wirguard ip or planetary network through the command `ssh root@.......` and also provide the manual documentation of ssh and Yggdrasil part.

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : b43ea4c
![Screenshot from 2024-01-15 15-20-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f29ea1bf-2423-4576-80bd-6d8833495d59)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150330

**Comment by ehab-hassan** [comment]
- Please try to make like guide img.
- Remove arrows and add builts or dashes it looks clickable.
- Remove all the background and text white at dark mode.
![6f54f134-3137-4dfb-85c0-630af7944cb3](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/72477992-1e0e-4812-a98c-ac8f3857c39e)

**Comment by khaledyoussef24** [comment]
verified on devnet
version: 9d076f1
it looks much better now
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/311b1d1d-6b9d-46cb-8325-cb954a305c1f)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150330

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
