### ISSUE TITLE
dedicated machines listing: rows aren't clickable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1926]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c6fea3ee-b649-4921-aab7-219586bf8390)

i was expecting that i can click on the row to expand the details (apparently it's allowed by using the button on the very right)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:

- Implemented the enhancement to expand rows upon clicking, replacing the previous expand icon behavior.
- Created a function for toggling rows, ensuring a smooth transition when interacting with the rows.
- Addressed the issue of closing the expanded row upon clicking, specifically when the clicked node is equal to the incoming node.

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 21ef1d6
verified rows are now clickable 
[Screencast from 14 ينا, 2024 EET 03:13:04 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/719acbc0-4a94-4627-8b37-39285dd72ac7)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150429

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c
