### ISSUE TITLE
dedicated machines: table may take sometime to update

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1927]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0710a8c0-d771-4977-ac23-2754c118d4f7)

Are we talking about the rentable or mine? is it supposed to auto refresh?

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed
a `notifyDelaying` function is now available to notify the user that the action will be reflected shortly. This function is used in other parts of the program.

**Comment by A-Harby** [comment]
Verified, 
Devnet, 7b55dd4.

The toast message have been updated. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5cd969c7-6925-4a0f-b383-26a66afd5a3e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
