### ISSUE TITLE
contracts: should export under different names

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1929]
now there're 3 tables, we should export with 

node_contracts.json, name_contracts.json and rent_contracts.json

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:

- Rename the contracts file to the contract type

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/caefdc10-e166-461d-9ba3-04905aae828d)

[Screencast from 01-11-2024 04:20:34 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b5daed17-4a08-4777-a33b-de477dbdaae3)

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 21ef1d6
verified
[Screencast from 14 ينا, 2024 EET 03:05:25 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/60a29400-dd7b-40e1-9155-47ec8e338b03)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4155452

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-15 15-40-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/45e87a70-4997-4624-90f2-df777e1c2b0b)
