### ISSUE TITLE
expose farmID/ nodeID either in the table or the details

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1930]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/89241c73-2041-436a-821a-3336e1a83125)

to find the information of where that workload is deployed, clicking on the details ain't enough

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/08a156d0-827d-48fa-962d-27ba87c60c05)
you need to click on the json view

and probably we should expose the farmID/name too

**Comment by A-Harby** [comment]
Verified, Devnet 21ef1d6.

[TC2459 - Deployment Details](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422334#case_4177819)

Node ID is now added and visible on VMs, masters, workers and other solution.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c4646ce-21a0-490a-9cf7-1ba1ddd32608)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b7d6d7a9-d725-4b09-bfc4-bdade71522df)
