### ISSUE TITLE
visualize the node tests from iperf

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#1931]
when selecting a node and when viewing node details (and maybe we can squeeze some of them in the node finder table)

**Comment by mohamedamer453** [comment]
Duplicate https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1388

**Comment by AhmedHanafy725** [comment]
reopening as it's not added to the node selection while deploying the vm yet

**Comment by zaelgohary** [comment]
Blocked till perf tests are added to the Grid Proxy.

**Comment by zaelgohary** [comment]
WIP:

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057#issuecomment-2021510752

**Comment by zaelgohary** [comment]
Work completed:

Added network speed chip in Node details card.

**Comment by zaelgohary** [comment]
Work completed:

Edited Iperf card to get the tests from grid proxy instead of zos.

**Comment by khaledyoussef24** [comment]
verified iperf tests in the node finder
env used devnet
version : 2c8c89b



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fa2f756b-e0e2-4343-a00c-3600f9846319)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/97d4c999-2154-4980-9962-87387acce8a1)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/32891e35-b409-48c1-9fe7-6db5a36b967b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/573a80ac-6211-4173-b9e3-b76d83782290)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/82613f9e-eeff-4877-86bb-8f88afb8ea75)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4263110

**Comment by khaledyoussef24** [comment]
the speed is the same 1048565 / 1024 = 1023.9 kb

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eca3c709-1c7f-43df-95a2-f7716e5fe735)
