### ISSUE TITLE
No errors in case the playground can't connect to tfchain

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#1932]
it keeps loading forever

[Screencast from 01-11-2024 11_00_46 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/c602702f-75f9-41d1-8795-d3d66532eaa0)

**Comment by khaledyoussef24** [comment]
can not produce the same issue and now a retry button is found when you can not connect to the tf chain
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3ee7b68d-9623-4ab0-9e15-7729555f3de8)
