### ISSUE TITLE
unclear error message when deploying peertube with custom domain

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1937]
### Description

env used : mainnet
version : 2.2.0

tried to deploy a peertube solution using custom domain but got an unclear error 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4093cd60-c8f7-41d3-95c8-663b6d84668b)

**Comment by AhmedHanafy725** [comment]
The error says that the host you entered as fqdn for the gateway workload doesn't point to the gateway ip. so it might not propagated yet or badly configured.

**Comment by khaledyoussef24** [comment]
deployed multiple peertube and worked fine 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5aa03a9c-46c3-4e10-8d7b-517a7bb14ef5)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6a4ddf2d-7dd3-4884-abe8-af8b46b05e8b)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150341
