### ISSUE TITLE
caprover deployment failed

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1938]
### Description

env used : mainnet
version : 2.2.0
node id : 1
contractId : 132397
twin id :  7606 
tried to deploy caprover and the machine deployed successfully but it did not work  and waited more than 10 minutes

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5b93c09a-3b50-4449-a322-a40f7c4321a0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2a8c5e45-617c-4b92-88b8-2c471d0a7b2e)

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Still checking/trying to reproduce the issue, first couple of instances worked fine with me after waiting for a couple of minutes till everything was ready.

**Comment by khaledyoussef24** [comment]
could not produce will close it for now and will re-open if  the issue produced again
