### ISSUE TITLE
a taiga deployment failed but still can not deploy another machine with the same name

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1939]
### Description
env used : mainnet
version : 2.2.0
twin id :  7606 
contract : 132426
node : 1
was trying to deploy taiga but it was failed with this error
![Screenshot from 2024-01-11 13-08-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/627c2efd-cdb4-47e2-929e-a23396e3d44c)
then tried to make deployment on another node got that the machine was already made

![Screenshot from 2024-01-11 13-08-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39ac6032-feec-4f65-8482-852e51e552cb)

and then it shows that the deployment is made in the deployment list but the machine is un reachable
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c470dfa1-c656-4ecb-95c0-454b4bd5e9af)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94e1f3d7-fad3-4a93-8692-75243a334517)

**Comment by khaledyoussef24** [comment]
after discussions we found that a network issue was occurred before rolling back

**Comment by ramezsaeed** [comment]
Lets see if happens again please re-open this one.
