### ISSUE TITLE
Fix responsive at landing page

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#1940]
map and some text cut at the normal size screen 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/4be05d22-7a38-48a9-9ce0-11a47769c611)

**Comment by A-Harby** [comment]
Verified, Devnet 21ef1d6.

[TC2458 - Homepage after login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177818)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/acb5c666-4e38-40ee-b8c7-57cd602b05be)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a7162757-5dca-4f26-80ce-490696f779de)
