### ISSUE TITLE
Add more details in bug report template

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1941]
- There should be more details in bug report template.
- for example: nodeId, farmId ...

**Comment by A-Harby** [comment]
Could we also add some more information, like:
- Network
- Version
- Screenshots or records.
- Contract or deployment details.
- Zinit log if it's a solution error.
- In the logs, clarify to add console errors and network requests, if there are any.

**Comment by xmonader** [comment]
> Could we also add some more information, like:
> 
> * Network
> * Version
> * Screenshots or records.
> * Contract or deployment details.
> * Zinit log if it's a solution error.
> * In the logs, clarify to add console errors and network requests, if there are any.

I assigned it to you xD

**Comment by A-Harby** [comment]
Work done:
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2074

**Comment by A-Harby** [comment]
Verified, on creating a new issue.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/44c33e0a-e610-4fac-9f33-03518d056ef2)

**Comment by ramezsaeed** [comment]
Verified
