### ISSUE TITLE
In routers we're still using name `solutions` but its changed to `applications`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1942]
[Screencast from 01-08-2024 01:50:45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/be602047-9e55-4a85-a967-a638a5eb0a65)

- also should be changes in second navbar inside virtual machines and orchestration.

**Comment by khaledyoussef24** [comment]
env used : devnet
version : 21ef1d6

verified 
![Screenshot from 2024-01-14 14-04-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ef076bbf-f33a-4f7b-a950-c7325d1bf29e)
the routers is using the right name now

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c

![Screenshot from 2024-01-16 11-22-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/2d844a07-fe25-4ba1-ab80-f5abcfaa8b06)
![Screenshot from 2024-01-16 11-22-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5a95cb62-313d-4b95-8dbf-e21046dfa0bb)
![Screenshot from 2024-01-16 11-22-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/413f8acb-db7e-4554-97a2-30f6aeb8a818)
