### ISSUE TITLE
Add msg in dedicated machines page that balance maintained every hour

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1943]
- Balance is maintained each hour and use should maintain its balance to get same discount.

**Comment by A-Harby** [comment]
Devnet, 9868338.

I can't see these changes anywhere.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ef05b30e-3eb9-4141-906e-82ff1b77b7cf)

**Comment by AlaaElattar** [comment]
will appear once routing pr is merged

**Comment by khaledyoussef24** [comment]
routing pr is merged but still the msg is not visible

**Comment by AlaaElattar** [comment]
> routing pr is merged but still the msg is not visible

check https://staging.dashboard.dev.grid.tf/#/deploy/dedicated-nodes

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : 755bfa4

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0d93b76e-d75f-41ee-9712-1261d8d9094a)
