### ISSUE TITLE
Can't deploy presearch 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#195]
### Search first

using the manual node selection or the capacity filter can't get any available node for presearch, but there is actually for any other solution 
using the capacity filter it calls 
````
https://gridproxy.dev.grid.tf/nodes?free_mru=1073741824&free_sru=&free_hru=&free_ips=&ipv4=&ipv6=&gateway=&farm_ids=&farm_name=&country=&city=&dedicated=&available_for=800&status=up&page=2&size
````
i think this is invalid mru and page  in the query 
while the filters is 
![image](https://user-images.githubusercontent.com/62248851/234843680-9decc462-9dd3-44fa-80d4-7120972fa79d.png)

### Steps to reproduce

- navigate to https://play.dev.grid.tf/#/presearch
- try to use both options for node selection

**Comment by AhmedHanafy725** [comment]
a farm can only have one presearch node if public ipv4 is not selected as it requires public ip. and usually, the nodes inside the farm use the same network with one public ip behind NAT. maybe this is the issue please make sure that there are no presearch nodes deployed on the farm to be able to see its nodes in the capacity filter

**Comment by ramezsaeed** [comment]
please check that documentation reflects this.

**Comment by khaledyoussef24** [comment]
![Image](https://user-images.githubusercontent.com/110984055/236757989-aea57e8f-180b-4037-8a84-28efe12bc866.png)

deployed successfully check for nodes without previous presearch with public ip
