### ISSUE TITLE
Reload button is required to re-request in case of failure in the profile manager

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#1955]
### Description

a reload button is required to re-request in case of failure in the profile manager, i have to copy the value then enter it again by myself to re-request.

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/11e9930c-ec50-42f5-b82d-89905022d272)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
