### ISSUE TITLE
Table filters should disable apply button if the values not changed

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1957]
> * if the filter values are different than the current state values, the `apply` button should be active.

- type in any field then click on apply
- go to another field and type any thing and delete it without clicking apply 
- the expected scenario is to disable the `Apply` btn but it was enabled

[Screencast from 11 ينا, 2024 EET 05:19:37 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1d7b3b19-1d34-4040-8e26-8dd15b64bb28)

_Originally posted by @0oM4R in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1877#issuecomment-1887427122_

**Comment by 0oM4R** [comment]
Work Completed:
we decided that the current logic will not scale as wanted, we drafted the old pr and now we are enhancing the filters, almost done.

Investigation and solution:
will apply the new filters to the dedicated machine page
add query route to the filter component

**Comment by khaledyoussef24** [comment]
working and verified on devnet
version : 9d076f1
![Screenshot from 2024-01-23 07-22-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/28e5d944-42d3-463a-b8d2-deefdf34e91e)
[Screencast from 23 ينا, 2024 EET 07:22:30 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31707b1b-6024-477a-95ac-02251700b5cd)

**Comment by ramezsaeed** [comment]
why I can see a red line under the farm name !!
that feels there is something wrong!

![Screenshot from 2024-01-24 15-46-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1784e6b7-f7a7-4623-8fb0-ce603f263b41)

**Comment by khaledyoussef24** [comment]
the redline is not visible anymore 
<img width="455" alt="Screenshot 2024-01-31 at 3 56 29 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f3f8c7a7-8ccb-4c7b-93cd-f8e6a36e56cd">
<img width="408" alt="Screenshot 2024-01-31 at 3 57 09 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/de03738e-852c-4cf5-923f-650b4b1552f9">

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 3b91b1f
