### ISSUE TITLE
threefold connect can not work on mattermost

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#1958]
### Description

env used : main net
version : 2.2.0
made a mattermost deployment and then tried to login with tf connect and it shows this error
contract id :133135
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/45db879e-68b6-4342-a04c-2745d3607881)

**Comment by mohamedamer453** [comment]
Update:

Investigation:

Currently unable to try/reproduce this issue since all of the deployed instances are unable to start and giving bad gateway as seen in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1977#issuecomment-1892067483

**Comment by mohamedamer453** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1977

**Comment by 0oM4R** [comment]
![Screenshot from 2024-06-05 12-34-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b42aa15d-0c48-4964-a4fa-5dcd24ae22a7)
works fine, will move it to verification

**Comment by khaledyoussef24** [comment]
verified on devnet
version : c94d09d

deployed a mattermost and connected using threefold succesfully

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a357fd40-d4b0-44f1-b067-5c67875b7183)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6ef09efe-cefb-44cd-aba1-144a5e7d6a79)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e99f1477-b7c7-4d91-a141-34847e7dd89d)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3db38539-8b86-47e4-9ebd-e5bfe7110bd9)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150343
