### ISSUE TITLE
Profile Manager dialog should be closed once user logs in

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1964]

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : 755bfa4

[Screencast from 01-15-2024 11:31:28 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d82989bf-14a3-4374-9a6e-35c4407724cd)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150323

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b43ea4c
