### ISSUE TITLE
remove spaces between switches in `pricing calculator`

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#1967]
### Description
- The switches should be next to each other.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/c6138e1a-7300-4a3e-8765-ec876c3765a0)

**Comment by mohamedamer453** [comment]
Will be fixed once the tooltips are enabled again in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2000

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a8ba534e-e060-4be7-ab63-b20ef997255f)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9d076f1
spaces removed between switches
tool tips are now working fine
![Screenshot from 2024-01-22 23-27-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8bf5b41b-afdc-4fa3-a8b0-440a30c05c03)
![Screenshot from 2024-01-22 23-29-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9a7b3cbe-532b-4f1e-b50c-1494043c3679)
![Screenshot from 2024-01-22 23-27-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/471fdcb6-3e40-4c05-8d01-571e171c0646)
![Screenshot from 2024-01-22 23-27-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b9d75544-056c-44bb-9293-ce997ce9bb37)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-24 15-37-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/abe0a7b6-1960-4065-85ac-9e3a3ab11525)
![Screenshot from 2024-01-24 15-37-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/afbe43dc-afad-4a2f-95b0-7792f2d253a8)
