### ISSUE TITLE
[Node Finder] Clear button is not functional after opening node details dialog

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#1970]
### Description

As we discussed earlier, Clear button should update the table if the applied fields are not in the default case  

### Steps to reproduce

- go to node finder 
- select any field in this case i will select Gpu then click on apply 
- click on clear; you will notice that the table is not changed back to the init state

[Screencast from 14 ينا, 2024 EET 02:42:00 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/6b6ebf83-7e9a-4baa-b7d4-f8df5871d9e2)

### Logs/Alerts

Logs/Alerts if available

**Comment by 0oM4R** [comment]
Work Completed:
we decided that the current logic will not scale as wanted, we drafted the old pr and now we are enhancing the filters, almost done.

Investigation and solution:
will apply the new filters to the dedicated machine page
add query route to the filter component

**Comment by khaledyoussef24** [comment]
verified working fine now
env used : devnet
version :  9d076f1
[Screencast from 22 ينا, 2024 EET 11:07:48 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/860a3422-6771-4c11-9645-423d6e7520f1)

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150464

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
