### ISSUE TITLE
Mattermost: After deploying some instance aren't working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1977]
### Description

Devnet, 755bfa4.

After deploying multiple instances of Mattermost, some of them aren't working even after waiting for few hours to load.

A clear description of the bug, including relevant identifiers like:

- Twin ID: **162**

-  Node ID: **30**

-  Farm ID: **1**

- Contract ID: **60606**

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Click on Applications under the Deploy tab in the sidebar.
4. Select the Mattermost card.
5. Choose a node and domain.
6. Deploy.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6702994f-7661-4a76-abaf-57a05f1fd7ae)

[Zinit log](https://gist.github.com/A-Harby/181fe8bc196fca81fe93df5abf6129b2)

```
{
  "version": 0,
  "contractId": 60606,
  "nodeId": 30,
  "name": "mmkcidr1",
  "created": 1705239195,
  "status": "ok",
  "message": "",
  "flist": "https://hub.grid.tf/tf-official-apps/mattermost-latest.flist",
  "publicIP": null,
  "planetary": "301:a9bd:9b77:ce71:b630:5895:f0ac:ca9d",
  "interfaces": [
    {
      "network": "nwpsueo",
      "ip": "10.20.4.2"
    }
  ],
  "capacity": {
    "cpu": 1,
    "memory": 2048
  },
  "mounts": [
    {
      "name": "diskpzt",
      "mountPoint": "/var/lib/docker",
      "size": 16106127360,
      "state": "ok",
      "message": ""
    }
  ],
  "env": {
    "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvmSYj5BKWkizdNyIziMfMm0CRrgq0UxFtBfBdArUMXSFkU30rtExbg6dlVFJCufw6UsCESm/QBSwlOyYKRdpsfVARcAw5G5OG0iX/22n+tYmCcWpmOJLJZaAmSynF1kwpBx3XDy40mFL6OMXjqFcU3DirbcucIL185XfAsTzrq3tDtSvmYPwbXMVMbs1ZAZValxOQNuaLty4qGD2awxVNZq4vtAzgp755bfa4z3FFo3cs2g70jsGiPq/rsH+NxZHYmqvYnF/S0aPGBrbOe2yW8Cz0mqq5CzqbjYd+Qorkmt7uyJrlCBI43ky+pUuiAYeE1eJlWl5svA+ibWk5yYoa6svLUkaL1kcOMeZWLzDjL3OCrno9gglNp8zUkdSagHROoYlGgpc5fnzMGX4MKDLpHdE9xdk4NjpjB2Iq3hV3DamexXAhLEirLYv9fSilSyKVf/2kvYAa9o+NS4DgBVvXg9J54By/mAVsydD4lbpNe/2pX/WoFGCczmoQfWdHgJPYVCf2vU= harby@ahmed-Saleh-Harby",
    "DB_PASSWORD": "vFYr4VlG7fOn",
    "SITE_URL": "https://mm162mmkcidr1.gent02.dev.grid.tf",
    "MATTERMOST_DOMAIN": "mm162mmkcidr1.gent02.dev.grid.tf"
  },
  "entrypoint": "/sbin/zinit init",
  "metadata": "{\"type\":\"vm\",\"name\":\"mmkcidr1\",\"projectName\":\"mattermost/mmkcidr1\"}",
  "description": "",
  "rootfs_size": 524288000,
  "corex": false,
  "gpu": [],
  "deploymentName": "mmkcidr1",
  "projectName": "mattermost/mmkcidr1",
  "billing": "No Data Available",
  "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = M+gOug/onQmZCKdx96bXTK2fE/4VXeubs/1FXxA43xI=\n\n[Peer]\nPublicKey = OTIP0p/zX+t0ccNAktpCn4YzoQZ8zdIhFncIlNMD8j4=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.206.122.32:6651"
}
```

**Comment by mohamedamer453** [comment]
I faced the same issue while deploying multiple instances, after deploying 4 different instances on different nodes and with different specs all of them returned `Bad Gateway` and were unable to start after almost an hour.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/df746ede-fc5d-4e5b-abd3-970a038dc3ca)

and [here](https://gist.github.com/mohamedamer453/84457b926c77ed42964c6335c4522f34) are the full logs of one of the instances from executing `zinit log`

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/tf-images/issues/225
