### ISSUE TITLE
Wallet link on homepage doesn't open the connect your wallet dialog

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1979]
### Description

https://dashboard.bknd1.ninja.tf/#/, 2.3.0-alpha6

When pressing on wallet, it should open the Connect your wallet dialog, but it doesn't.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a34c8725-b46a-40db-86a2-8f7bf02b9b03)

**Comment by khaledyoussef24** [comment]
fixed and verified 
env used : devnet
version : 5b50681

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1c418a3e-f455-4c21-8ade-c7e977f9ba42
