### ISSUE TITLE
UI Fix for the Dedicated Machines card on stats

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1983]
### Description

https://dashboard.bknd1.ninja.tf/#/tf-grid/stats, 2.3.0-alpha6

All the cards are responsive correctly except for the Dedicated Machines card, where the icon is aligned within the left border. Just a small fix to be consistent with other cards.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/19f77bad-bacf-4e32-8030-05399aa4c625)

**Comment by ehab-hassan** [comment]
fixed ll create PR soon

**Comment by ehab-hassan** [comment]
fixed 
1920 Big screen
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/02f5ca47-ce4c-4008-bc4a-5af0c45def20)

1440 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/19afe282-7de7-4ee6-ac55-73e2220fd566)

1024
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/cd26c9a3-b761-4a9f-92a3-c8163014f1e1)

**Comment by khaledyoussef24** [comment]
fixed and verified on devnet 
version : 5b50681
<img width="1440" alt="Screenshot 2024-01-21 at 3 51 54 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/392a1fbb-a83a-4af9-859d-45010cce0e9f">
<img width="1440" alt="Screenshot 2024-01-21 at 3 57 20 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3035af27-3762-4808-a60a-a7cb17c49a5f">
<img width="1440" alt="Screenshot 2024-01-21 at 3 57 24 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dfc7e721-cc59-4954-8694-02854fc168b4">
card fixed

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 6a9a049

![Screenshot from 2024-01-22 13-22-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/13780ddd-1154-46c5-89a8-4e8d0d7670df)
