### ISSUE TITLE
Your profile page isn't responsive

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1985]
### Description

Your profile page isn't responsive.

A clear description of the bug, including relevant identifiers like:

- **Twin ID**: 11223

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Change page size.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/979989ce-53e3-4862-b87b-fb506b2012ce)

**Comment by A-Harby** [comment]
Same issue on Devnet, b43ea4c.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8a5277ff-847a-4ea6-973e-7dd3f2baf575)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b43120




![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b6956a3c-d0d7-4153-b33a-c428158a2234)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7245f604-0332-4d31-91e2-bab0c7d2394a)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99ea987d-d4c0-470a-8ff7-4101188a1bfb)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/45c192e0-8153-46f4-b1b2-e81e4c5a39d0)

**Comment by A-Harby** [comment]
I tried it on Qanet 2.3.0-alpha12 and on devnet staging, and it is still not fixed on small screens.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c66e0064-74a4-44d4-b7af-3f4e994c61d1)

**Comment by 0oM4R** [comment]
@samaradel should we move this to blocked on #2342 ?

**Comment by ehab-hassan** [comment]
Work completed 

should be fixed

**Comment by khaledyoussef24** [comment]
verified on devnet
Version c2d6060

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/6da5836b-1046-4874-a551-ef09d682ea4a" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/11846260-5f79-4c5e-b8a9-6709184c659f" />

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4431573)
