### ISSUE TITLE
Add the manual link for the DAO page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1989]
### Description

https://dashboard.bknd1.ninja.tf/#/tf-chain/dao, 2.3.0-alpha6

Add the manual link for the DAO to the DAO page.
I don't know which one is it, but I found some links: https://manual.grid.tf/dashboard/dashboard.html?highlight=dao#tfchain-dao, https://manual.grid.tf/dashboard/dao_voting/dao_voting.html?highlight=dao#an-introduction-to-the-dao-concept.

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to the DAO page.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/00fa103f-699b-4e15-9e44-a188da0ec1e6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/87d0515f-544d-4937-a323-2e7ece444ec7)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5b50681
<img width="1440" alt="Screenshot 2024-01-21 at 3 50 27 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c9e8792a-77a1-4684-8906-73ddd442f96e">
<img width="1440" alt="Screenshot 2024-01-21 at 3 50 31 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e104b690-3e4f-4e34-9760-f837f3f916ee">
<img width="1440" alt="Screenshot 2024-01-21 at 3 50 34 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7804455a-b9ad-4315-af55-28f725701075">

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 6a9a049

![Screenshot from 2024-01-22 13-21-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/188a8292-e100-4b5c-8115-565f494a4532)
