### ISSUE TITLE
Keep getting an error while trying to deploy a VM on some of the nodes.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1990]
### Description

Devnet, b43ea4c.

A clear description of the bug, including relevant identifiers like:

- **Twin ID**: 162

- **Node ID**: 128

- **Farm ID**: 1

- **Contract ID**: Couldn't create it.

I keep getting that error when I try to deploy a VM on some of the nodes (like 128).

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ce884d4-4f26-4e02-920e-e3de7a2bf093)

### Steps to reproduce

1. Navigate to the dashboard.
2. Connect your wallet.
3. Navigate to the VM from the virtual machines page.
4. Select node 128.
5. Deploy.

**Comment by ramezsaeed** [comment]
@sabrinasadik 
can ops check node 128 logs and see whats is aheppening

**Comment by hossnys** [comment]
- tried deployment on the same node 128 , and got the same error , checked the node logs and found that it's full of these logs repeating there :
![Screenshot from 2024-01-21 12-14-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26298009/38161490-ac68-4979-b5fb-f663b4647d17)

**Comment by hossnys** [comment]
- tried to deploy on many nodes on devnet , and all of them completed successfully .
![Screenshot from 2024-02-07 12-02-54](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26298009/9765d5b0-4fe8-4aa9-8436-e419b1431707)


- node 128 is not available anymore on devnet for deployment as it's already rented 
![Screenshot from 2024-02-07 12-06-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26298009/ae22db83-3d5a-4d5e-9277-983f6cd251ac)

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.
Deploy a VM on multiple nodes successfully, including the node 128.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8709efd7-ecd3-4635-9b3d-0635f9f7c66e)
