### ISSUE TITLE
You have to change Amount input value to be able to send TFT in the bridge page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1991]
### Description

https://dashboard.bknd1.ninja.tf/#/tf-chain/bridge, 2.3.0-alpha6.

After entering the address and without changing the amount (TFT), you can't send without making any changes to the amount input.

[Screencast from 01-15-2024 03:27:10 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bddcf15d-bd2a-483e-8f71-e7fcc911b87e)

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to the TF Token Bridge page.
4. Click on withdraw.
5. Add the address and try to send.

**Comment by AlaaElattar** [comment]
### Work In Progress (WIP):
- still working on the issue, had some issue in creating stellar address to test with it.

**Comment by AlaaElattar** [comment]
### Work Completed
- issue fixed

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b55dd4
[Screencast from 23 ينا, 2024 EET 07:12:36 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/05180f3e-1d54-41e4-ad51-db667c1e0cb0)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150412

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
