### ISSUE TITLE
(Mainnet Verification) Nodes with more than 1 GPU only show one of them

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1992]
### Description

https://dashboard.bknd1.ninja.tf/#/deploy/nodes, 2.3.0-alpha6.

The nodes with more than one GPU card only show one card.

**Node IDs** like: 387, 6230, 6224.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/190f119a-12c2-45cd-97cb-3682a319a5de)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/09f7786c-2e43-4989-a7f0-5382da639f76)

**Comment by samaradel** [comment]
blocked on [#2039](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2039)

**Comment by samaradel** [comment]
compared nodes between ninja and mainnet and the issue is still there .. there are no GPU cards

[Screencast from 22-01-24 12:34:45.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/5f2808e1-3338-49ea-8cf2-ebaf3dca0ce0)

**Comment by samaradel** [comment]
GPU cards on node finder are working 
for dedicated machines: blocked on [#2060](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2060)

**Comment by samaradel** [comment]
Trying to find nodes that have broken gup cards on node finder

**Comment by samaradel** [comment]
blocked on gridproxy release

**Comment by samaradel** [comment]
working on Ninja, 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/e5bf038b-6850-4d44-a1e4-2ecaca199c66)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/0a5c1f0d-d8fc-444c-b66f-f1a276404bfa)

**Comment by A-Harby** [comment]
Devnet, 9280a08.

Node ID 171 has 2 GPU cards, but it still shows only 1 of them.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f4f17c2a-aae2-46e8-a908-b04ecb0f2f3d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/19f1955c-31a0-4f67-8e23-0c1693db48ca)

**Comment by samaradel** [comment]
blocked on [#636](https://github.com/threefoldtech/tfgrid-sdk-go/issues/636#issuecomment-1963755089)

**Comment by samaradel** [comment]
### Work Completed:
it works on Devnet now and waiting till gridproxy release reaches mainnet.

**Comment by A-Harby** [comment]
Devnet doesn't have any nodes with more than 1 GPU.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/20ac63de-d2eb-400c-8cad-632617c9f691)

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

Nodes with 2 or even 3 GPU cards are now listed as normal, with all the card details displayed on the node finder and dedicated machines pages.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3fb77be5-d443-4be2-93ad-d4d2b44108e8)
Node ID: 6208.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/18670a02-a04a-4eed-ad98-bb938df3301e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/03c71aea-194f-479a-90ca-9d7a44654f3e)

[TC2257 - Filter GPU Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150466)
[TC2220 - Verify Dedicated Nodes Resources](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430127#case_4150429)
