### ISSUE TITLE
Add clear message for generate/update ssh-key cost in TFT

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1995]
### Description
I can't update/generate ssh-key because the account has zero balance;
so need a clear message for the cost of update/generate.

- **Twin ID**: 5191
- Devnet: https://staging.dashboard.dev.grid.tf/
- b43ea4c

### Steps
- For my account which already has ssh key in the dashboard and account balance 0 TFT
- when delete this ssh-key and try to update or generate a new one
- the generate and update buttons are kept disabled.
- so not allow me to update or generate a new ssh-key.
- this happen because there is no available balance; But this is doesn't mentioned or shown anywhere as an info or error message

![Screenshot from 2024-01-16 10-56-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/07d2e580-cb0d-4f1f-b04f-4bb6dc0023c0)

**Comment by 0oM4R** [comment]
the cost of updating the ssh key is `0.0011171` tfts, but looks like the cost is not constant, so i suggest to set the info value  to be `up to 0.01 tfts`
![Screenshot from 2024-01-17 18-16-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/a1600edc-9b32-47ff-9738-1d0c7e793dcb)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b55dd4
a clear message is added to the minimum value for generating and updating ssh key
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/95d05a4a-48ce-4740-b64c-372aa84d6f35)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150324

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-29 15-34-46](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8db65516-b3c3-4e14-906d-1f56b084c020)
