### ISSUE TITLE
Minting report steps isn't clear or not correct

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1996]
### Description

The manual steps aren't clear enough, and using the old minting site page, even after figuring out where the hash is in the stellar site, it still shows me that there's no receipt for that hash.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/52d630d7-b9a8-476d-93da-7fcbd3f928f8)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85d79192-7b75-42cc-85b5-c7f65066e60e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1e26d74d-43de-45a0-9c1f-0e9c095e9d11)

**Comment by Mik-TF** [comment]
@TullysInc @A-Harby good points and suggestions.

An issue has been created in info_grid, see [here](https://github.com/threefoldtech/info_grid/issues/376)

**Comment by Mik-TF** [comment]
Fixed when [this PR](https://github.com/threefoldtech/info_grid/pull/379) on info grid is merged
