### ISSUE TITLE
(Mainnet Verification) Add filter to search by number of GPUs

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#1997]
### Implementation

we need to find a way by adding filter to find the nodes by number of GPUs included.
what we have now is only a toggle button to list the nodes with GPU;
but need a filter to find a node with specific number of GPUs.
we maybe also allow sorting in gpu table

**Comment by AlaaElattar** [comment]
- This should be handled in both `Node Finder` and `Dedicated Machines`.

**Comment by mohamedamer453** [comment]
Update:

Work in Progress:

- added num gpu filter in the gridproxy client.
- Added a new field called num gpu in the node finder filters.
- the field is filtering incorrectly so i'm still figuring out what's wrong with it.
- Still need to add the same field to the `Dedicated Machines` filters.

**Comment by MohamedElmdary** [comment]
As @Omarabdul3ziz we can't filter using num_gpu right now so we will need time untill it's supported so I will turn this issue into blocked

**Comment by Omarabdul3ziz** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/issues/981

**Comment by A-Harby** [comment]
Filter was added, but no nodes are available on the devnet with GPU cards.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26d21929-5300-47ea-b624-000d3ff41778)

**Comment by khaledyoussef24** [comment]
verified on mainnet
version : 2.5.2
filtering by numbers of gpus is now working fine



![Image](https://github.com/user-attachments/assets/71256dd6-7e83-4829-9e2a-2d1bfca5b878)
![Image](https://github.com/user-attachments/assets/4a0df63c-4e11-4183-b3e1-9e7b1f4a0eae)
![Image](https://github.com/user-attachments/assets/3b6eae85-b900-4ea9-9361-679f2aa701f8)
![Image](https://github.com/user-attachments/assets/9eb3004a-4d15-49a0-b39d-1faf55d0c324)
![Image](https://github.com/user-attachments/assets/908b1c0b-3cf3-45f7-8aa9-daf8d8fe49f8)
![Image](https://github.com/user-attachments/assets/c21aae63-01f8-4880-bb3e-8680f2b95b3a)
![Image](https://github.com/user-attachments/assets/01751a6f-b7f5-4143-844d-a682f69e752f)
![Image](https://github.com/user-attachments/assets/acd6024a-c476-4c87-a3ed-9b1dd8da64b4)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4318581)
