### ISSUE TITLE
Add tooltips in the minting page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#1998]
### Description

Devnet, and Ninja 2.3.0-alpha6.

It would be better to add tooltips to the minting page for more readable content.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/796eb096-5f75-47c6-9861-b1fbaf7d690e)

**Comment by AlaaElattar** [comment]
- We won't add tooltips in table as farmers already should be aware of these details, but instead we will add link to manual once this issue is solved https://github.com/threefoldtech/info_grid/issues/375

**Comment by AlaaElattar** [comment]
### Work Completed:
- manual linked to minting page.
- opened issue in manual for adding more details about minting https://github.com/threefoldtech/info_grid/issues/492

**Comment by A-Harby** [comment]
Verified, Devnet ff9d79e.

The link is added to the manual with all the information needed.
https://www.manual.grid.tf/documentation/farmers/3node_building/minting_receipts.html
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9418e118-f207-474b-9445-31a98450f771)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/95c54da8-8baa-4d04-8581-c562d0e2c953)

[TC2295 - Grid Minting Explorer](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4153425)
