### ISSUE TITLE
All tooltips disappeared from the ui

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#2000]
### Description

All tooltips disappeared from the ui due to a [`disabled`](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/components/input_tooltip.vue#L2) boolean that was added to the input tooltip component 

### Steps to reproduce

- Navigate to the dashboard.
- Check any page that had tooltips in it.

**Comment by khaledyoussef24** [comment]
tooltips are enabled now
![Screenshot from 2024-01-22 18-18-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cd30e8a4-ef39-4a79-aaa0-15da5c89b793)
![Screenshot from 2024-01-22 18-17-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e65163a0-01b3-4883-8d90-36f7cc4cb99a)
![Screenshot from 2024-01-22 18-17-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/041beaf2-b38d-461b-b1b6-06a0959734d6)
![Screenshot from 2024-01-22 18-17-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1091f6aa-3290-4195-b387-d2c0c3220c3c)
