### ISSUE TITLE
Add `alpha` chip on mattermost.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2021]
- alpha chip should be added as it's not totally stable

**Comment by khaledyoussef24** [comment]
is there a way to verify or only to check the solution running ?

**Comment by mohamedamer453** [comment]
> is there a way to verify or only to check the solution running ?

You can check the chip from the applications page. you'll find `Alpha` next to mattermost.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9cb2669c-9c5b-4707-8e57-14bdfd5c553d)

**Comment by khaledyoussef24** [comment]
verified on devnet
alpha chip added to the solution in applications tab
env used : devnet
version : 5b50681
<img width="383" alt="Screenshot 2024-01-21 at 3 48 12 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f66a3406-0a0d-4dae-bdea-91401141ca92">

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 6a9a049

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/0b735ad7-1c54-4cc1-b222-c10c3f91b4de)
