### ISSUE TITLE
(Mainnet Verification) Some nodes show a broken country image in Load Nodes.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2024]
### Description

Devnet and Ninja 2.3.0-alpha6.

Some of the nodes show a broken country image.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ecdbce5f-fda8-4645-bacf-9ca4ae8b48a0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2848cc10-d5aa-49d6-9880-b3ec0dcb1c56)

- **Node ID**: 418, 417, 415, 414

- **Farm ID**: 77

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to Virtual Machines.
4. Select VM and Load nodes.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work in progress

Moved to the blocked column since we agreed on adding more features to the node selection card as:

- Upload/Download chip 
- Country name chip
- Country logo<Globe icon> in case the country flag does not exits

**Comment by ehab-hassan** [comment]
![Frame 324](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/8457810e-2104-4cac-9209-d0ca6268c2c3)

in case no flag
![Frame 326](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a60662d0-756f-490c-ace1-926716e7345e)

other option without Flag
![Frame 325](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/c9080568-7291-435e-befa-217cc5d55aa3)

lets keep all text 14px or 0.875rem except Node ID 16 px or 1rem

**Comment by Mahmoud-Emad** [comment]
It was initially blocked due to dependencies on the `upload/download` feature, but we have found a way to address it independently. I'll be working on resolving this tomorrow, Insha'Allah.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed:

- Resolved the issue related to image reloading, ensuring that the bug no longer occurs.
- Implemented a fix to address the error encountered while attempting to load certain images.
- Replaced the hard-coded flag source with a dynamic function call (`getCountryFlagSrc`) for improved flexibility and accuracy.
- Added a tooltip displaying the node's country information.

### Investigation and Solution:

- The issue was identified as a result of errors in the image link, leading to problems with image reloading.
- The necessary changes were made to the code, particularly in the image loading section, to rectify the issue.

### Screenshots

- old
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/460cc1e6-b18e-4dc3-af78-c0ae37424dd0)

- new
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/3a30de77-0894-45c6-a392-21c6fdd00e05)

**Comment by ehab-hassan** [comment]
@Mahmoud-Emad Nice work I think while the flag issue was fixed we can skip adding not available (NA) avatar

**Comment by Mahmoud-Emad** [comment]
@ehab-hassan, I suggest temporarily postponing this matter unless we encounter a similar issue in the future.

**Comment by A-Harby** [comment]
On Mainnet 2.3.0.

The Switzerland flag was fixed, and the image is shown.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/32ee5aab-801e-488e-93e2-65490ec3c68e)

And for other countries like the Bahamas and Czech Republic, it showed NA (but I still don't know why it didn't show the flag here). 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/be3f4ae2-ba2c-4262-b03c-2de76d5cf29b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/570da166-36c3-4df5-8f8c-3b647a91d87b)

At least it should be NA, but in the case of Greece, it still showed a broken image. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/72beb809-9bd3-474e-bd9c-65cef1afc7bb)

**Comment by Mahmoud-Emad** [comment]
> On Mainnet 2.3.0.
> 
> The Switzerland flag was fixed, and the image is shown. ![image](https://private-user-images.githubusercontent.com/109473873/312086975-32ee5aab-801e-488e-93e2-65490ec3c68e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk2NjcsIm5iZiI6MTcxMDMzOTM2NywicGF0aCI6Ii8xMDk0NzM4NzMvMzEyMDg2OTc1LTMyZWU1YWFiLTgwMWUtNDg4ZS05M2UyLTY1NDkwZWMzYzY4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGIyNDYxMGFmYjgwMzQ0OTkwZGY1ZjRjNmFmMjI1YjU1MzIzOWUzNzc3YzU1MjdmNTg5NzdjZDE3YzhmNDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VM9E8QEOjOT5JZmQVzBzXbcvo1DV3P7l3q2qxPNZf78)
> 
> And for other countries like the Bahamas and Czech Republic, it showed NA (but I still don't know why it didn't show the flag here). ![image](https://private-user-images.githubusercontent.com/109473873/312086711-be3f4ae2-ba2c-4262-b03c-2de76d5cf29b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk2NjcsIm5iZiI6MTcxMDMzOTM2NywicGF0aCI6Ii8xMDk0NzM4NzMvMzEyMDg2NzExLWJlM2Y0YWUyLWJhMmMtNDI2Mi1iMDNjLTJkZTc2ZDVjZjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWZmODhkZjU3MDY4MGZlZmI2OWNhODgzMzY1Nzg4OTdmZDgyOWRiNzVlZmRhMGIxYmQ4NGVkMGZkYzgyYTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iBCH35lRA3MPOiE3kiVpsqHeWzcmEhu2wA7dvdJWwcU) ![image](https://private-user-images.githubusercontent.com/109473873/312087114-570da166-36c3-4df5-8f8c-3b647a91d87b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk2NjcsIm5iZiI6MTcxMDMzOTM2NywicGF0aCI6Ii8xMDk0NzM4NzMvMzEyMDg3MTE0LTU3MGRhMTY2LTM2YzMtNGRmNS04ZjhjLTNiNjQ3YTkxZDg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzlhZmFkM2M5YmYzNmZiYmVmMmMyYTdmNjI4ZWFjM2E1YzE3NDRhNWI1YmU0Mjg4NGJjZDBiMzVlYzgyMTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t3jhheclxFDzH5TTmf7Mbx62egmeS85EMV5H34BPbDQ)
> 
> At least it should be NA, but in the case of Greece, it still showed a broken image. ![image](https://private-user-images.githubusercontent.com/109473873/312087825-72beb809-9bd3-474e-bd9c-65cef1afc7bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzk2NjcsIm5iZiI6MTcxMDMzOTM2NywicGF0aCI6Ii8xMDk0NzM4NzMvMzEyMDg3ODI1LTcyYmViODA5LTliZDMtNDc0ZS1iZDljLTY1Y2VmMWFmYzdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNDE2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDRiZTIzNzhkY2JmOTA2NDk0MmY1NjNlMTk5MTZhNjFjNzM2NGI5YzEyY2YzZmQ1ZjljZjE4MGFmMTM2ZWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GdQNfQ0xPk9FKR-yOGjRmbB_1S02dDm6tq6S2GpdpbA)

We decided to go with the default 'N/A' logo if any errors are loading the image. also, I tested node 635, and everything seemed to load up just fine, including the Greece flag.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1483c19c-fe25-450f-b496-17ec48bd2a63)
