### ISSUE TITLE
Inconsistencies in the serial number tag in Load Nodes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2025]
### Description

Devnet and Ninja 2.3.0-alpha6.

The nodes in the load nodes list have inconsistencies in the serial number tag. Some show it correctly, some show it unknown, and others don't show anything.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fdfc4431-df14-41da-abf4-e0e5589bd4fa)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/886afd63-477b-4c3e-aa61-d51fde3037f1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0bc55eda-5c46-49a1-9fcf-fcb13e6fec95)

A clear description of the bug, including relevant identifiers like:

Node ID: 431, 437, 460, 491.

Steps to reproduce
1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to Virtual Machines.
4. Select VM and load nodes.

**Comment by A-Harby** [comment]
I also found some other nodes with none tag.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b77b2b5f-e257-4022-9df5-27a4b0b7fb8b)

**Comment by A-Harby** [comment]
Why did it show up like this?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b311d1e3-61b1-43ec-b79c-96a7231fdb0a)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4924dcd6-612b-4282-9094-7e30a2e65aa5)

**Comment by AlaaElattar** [comment]
### Work In Progress (WIP):
- If serial number equals to `Default string`, we don't show it.

**Comment by AlaaElattar** [comment]
> Why did it show up like this?
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/297778664-b311d1e3-61b1-43ec-b79c-96a7231fdb0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI2MTYsIm5iZiI6MTcwNTkxMjMxNiwicGF0aCI6Ii8xMDk0NzM4NzMvMjk3Nzc4NjY0LWIzMTFkMWUzLTYxYjEtNDNlYy1iNzljLTk2YTcyMzFmZGIwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwODMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Y2I1OWJkNGJhN2RmNWYwZGFhNDM1ZjNjZjk1ZjFhNWE2MzIxZWQ4OWNjYTAzMzFiMTg1OTgzYjcyMGM3MDlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cWO8PVSAs-HX0uFSmHN-bQOhavqJkvOhuLsEhWWd1dg)
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/297778811-4924dcd6-612b-4282-9094-7e30a2e65aa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTI2MTYsIm5iZiI6MTcwNTkxMjMxNiwicGF0aCI6Ii8xMDk0NzM4NzMvMjk3Nzc4ODExLTQ5MjRkY2Q2LTYxMmItNDI4Mi05MDk0LTdlMzBhMmU2NWFhNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMlQwODMxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDliMWIyOTBjNjQ5ZGIzOGUwMzIzNGQyZDU0OGMwMTlhMjEwNGJmMzIwMmZkNTNkNjdhZTNjNzQzNjcxOTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6o5xO3fEmb5nz1OW04aNgWoK6ubTOGbIb9YSi2ClXts)

- After Investigation, it showed like this when the screen is small.
- When the screen is default, it's like that 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/6fd0a172-3ec5-4fa1-a925-f097d1a2125a)

**Comment by A-Harby** [comment]
@AlaaElattar Can we have more consistency? If it has a serial number, you show it, but if it has a (None, Not Specified, Unknown, or Default string), you either don't show it or have one tag for all of them?

It would be less confusing for the user.

**Comment by AlaaElattar** [comment]
### Work Completed :

- @xmonader suggested if the serial numbers contains any string, will show it as `Unknown`.

**Comment by A-Harby** [comment]
Verified, Devnet.

It now shows the serial number, and for all the other cases, it shows unknown.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/18293392-7f2b-4f13-9649-97dbacfeb3ee)

[TC2461 - Node details in Load Nodes List](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4177821)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 48a660d
