### ISSUE TITLE
No Nodes available when turning off the toggle in the GPU filter

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2026]
### Description

Devnet and Ninja 2.3.0-alpha6.

If you turn off the GPU node toggle, no node will show up.

The request that is being made is `https://gridproxy.bknd1.ninja.tf/nodes?rentable=true&status=up&ret_count=true&size=10&page=1&has_gpu=false`, the has_gpu=false is the reason.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/245e50a5-7944-42e5-8ebb-0c214bff08d4)

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to Dedicated Machines.
4. Turn the GPU Nodes toggle on and press Apply.
5. Turn the GPU Nodes toggle off and press Apply.

**Comment by Mahmoud-Emad** [comment]
## Issue Update 

### Work Completed:
I fixed the issue while working on [this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1880), so I moved it to the verification column.

**Comment by A-Harby** [comment]
Verified,
Devnet, 7b55dd4.

[TC2486 - Turning off toggles](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4191618)

The filters worked fine when turned on, and after turning them back off or pressing the clear button, they returned to their original state.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cc6da38a-fb16-4a77-a74c-5396ec03853d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/61c7d95e-0fab-45fb-97a1-a87d9450c3b2)
