### ISSUE TITLE
Can't access wordpress through IPV4

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2029]
### Description

[Ninja](https://dashboard.bknd1.ninja.tf/#/deploy/applications/wordpress), 2.3.0-alpha6

I can't access the WordPress instance through the IPV4, while I can do that normally through the yggdrasil.
`ssh: connect to host 84.255.239.246 port 22: Connection timed out`
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1401b933-5a75-4b73-8ed5-c0b840887e8c)

A clear description of the bug, including relevant identifiers like:

**Twin ID**: 7189

**Node ID**: 492

**Farm ID**: 15

**Contract ID**: 145655

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to Applications.
4. Select Wordpress.
5. Turn on IPV4 from the Network tab.
6. Select a Node and a domain.
7. Deploy.

**Comment by samaradel** [comment]
Out of tokens, I'm blocked on [#2287](https://github.com/threefoldtech/tf_operations/issues/2287)

**Comment by samaradel** [comment]
@A-Harby 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/510d4a85-b1f4-44d6-b29e-9f773491da1d)

**Comment by samaradel** [comment]
tested on node ```342``` and it works fine 

[Screencast from 11-02-24 15:03:00.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/f4b2a0f8-91b8-4f4f-b289-0e134fae2a78)

**Comment by A-Harby** [comment]
I was able to deploy and ssh to WordPress through Ygg.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1fbf271f-f4bd-4975-83a8-f0c0f6abbf75)

Will wait for the release on other networks for a free ipv4.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

made a wordpress deployment using public ip and mycelium and yggdrasil


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/257fe8b3-bf21-4ade-99dc-48f23ed81a71)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5013bab5-3b07-4589-9583-dc6d8824e8fe)

could connect to it using the 3 ips


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/18a9fb0d-d290-42f4-9830-161a550b8dd2)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/96b8da57-f80e-413f-8d9d-ffaf6e4a1644)

[wordpress deployment](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150352)
