### ISSUE TITLE
Subsquid: After deploying some instances aren't working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2033]
### Description

[Ninja](https://dashboard.bknd1.ninja.tf/#/deploy/applications/subsquid), 2.3.0-alpha6.

After deploying an instance of Subsquid and waiting for more than 3 hours, I still can't open the site given a bad gateway error.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6e286163-30e5-4253-9fb2-ec1b3df393bb)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/72e777b6-a132-4aa1-b413-bd6f2343e10f)

A clear description of the bug, including relevant identifiers like:

- **Twin ID**: 7189

- **Node ID**: 388

- **Farm ID**: 109

- **Contract ID**: 145677

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Click on Applications under the Deploy tab in the sidebar.
4. Select the Subsquid card.
5. Insert any endpoint.
6. Choose a node and domain.
7. Deploy.

### Logs/Alerts

[Zinit logs](https://gist.github.com/A-Harby/8c6fb8d534d14e7839420902149b77bc)

```
{
  "version": 0,
  "contractId": 145677,
  "nodeId": 388,
  "name": "ssb2hq0",
  "created": 1705504623,
  "status": "ok",
  "message": "",
  "flist": "https://hub.grid.tf/tf-official-apps/subsquid-latest.flist",
  "publicIP": null,
  "planetary": "300:3c91:453b:dbd9:f0db:c868:9644:2413",
  "interfaces": [
    {
      "network": "nwirc9i",
      "ip": "10.20.4.2"
    }
  ],
  "capacity": {
    "cpu": 1,
    "memory": 2048
  },
  "mounts": [
    {
      "name": "diskyc7",
      "mountPoint": "/var/lib/docker",
      "size": 53687091200,
      "state": "ok",
      "message": ""
    }
  ],
  "env": {
    "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvmSYj5BKWkizdNyIziMfMm0CRrgq0UxFtBfBdArUMXSFkU30rtExbg6dlVFJCufw6UsCESm/QBSwlOyYKRdpsfVARcAw5G5OG0iX/22n+tYmCcWpmOJLJZaAmSynF1kwpBx3XDy40mFL6OMXjqFcU3DirbcucIL185XfAsTzrq3tDtSvmYPwbXMVMbs1ZAZValxOQNuaLty4qGD2awxVNZq4vtAzgpz3FFo3cs2g70jsGiPq/rsH+NxZHYmqvYnF/S0aPGBrbOe2yW8Cz0mqq5CzqbjYd+Qorkmt7uyJrlCBI43ky+pUuiAYeE1eJlWl5svA+ibWk5yYoa6svLUkaL1kcOMeZWLzDjL3OCrno9gglNp8zUkdSagHROoYlGgpc5fnzMGX4MKDLpHdE9xdk4NjpjB2Iq3hV3DamexXAhLEirLYv9fSilSyKVf/2kvYAa9o+NS4DgBVvXg9J54By/mAVsydD4lbpNe/2pX/WoFGCczmoQfWdHgJPYVCf2vU= harby@ahmed-Saleh-Harby",
    "CHAIN_ENDPOINT": "wss://gateway.mainnet.octopus.network/myriad/a4cb0a6e30ff5233a3567eb4e8cb71e0",
    "SUBSQUID_WEBSERVER_HOSTNAME": "ss7189ssb2hq0.gent03.grid.tf"
  },
  "entrypoint": "/sbin/zinit init",
  "metadata": "{\"type\":\"vm\",\"name\":\"ssb2hq0\",\"projectName\":\"subsquid/ssb2hq0\"}",
  "description": "",
  "rootfs_size": 524288000,
  "corex": false,
  "gpu": [],
  "deploymentName": "ssb2hq0",
  "projectName": "subsquid/ssb2hq0",
  "billing": "0.368 TFT/hour",
  "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = YXb2SegwkpVfywenyBI7I2K5kE62vHyJAD0OemWKFk0=\n\n[Peer]\nPublicKey = 4uaakneMtHoPp5u/xEPcSC+NvI5QvOTBZsEqYnDrvTU=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 185.69.167.141:2716"
}
```

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

deployed and worked fine
even a link providing supported websockets can be found easily in the manual
![Screenshot 2024-03-26 at 10 58 42 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8fd04ec6-46a4-4697-a15f-79ee497a8bd2)

![Screenshot 2024-03-26 at 10 52 05 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/44eabf3c-e643-4413-9d36-da10dade78ef)
![Screenshot 2024-03-26 at 10 52 11 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/179c8928-0c1e-4ba5-9af5-4c4a8b6984e9)

updated test case : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150348
