### ISSUE TITLE
profile dialog do not update the balance 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2037]
### Description

the user have to refresh the page to update the balance or wait for two minutes which is very bad UX imo

### Steps to reproduce

- log in 
- click on the profile button <balance> 
- you will see that the balance not updated
 

### Logs/Alerts
[Screencast from 18 ينا, 2024 EET 12:55:32 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/63a9afde-2ee2-4c38-8b48-17b1270457a3)

**Comment by 0oM4R** [comment]
Work in progress: 
adding new function that handles the emits and triggers update balance if the user logged in

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

verified balance is now getting updated at the same instance.
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/897da25e-ca7e-49f5-9b85-0a6494568277

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4169741
