### ISSUE TITLE
add some sort of explainer in the node finder to explain shared, rentable and dedicated

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2038]
shared : multiple users can deploy on that node
rented : rented as full node for a single user
rentable : you can rent it exclusively for your workloads

**Comment by samaradel** [comment]
@xmonader something like a tooltip on the type chip?

**Comment by xmonader** [comment]
Can be a legend after the table too

**Comment by samaradel** [comment]
@ehab-hassan which option do you prefer?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/0a6aecaa-f467-4a59-a023-b157aeaba911)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/6db21fb4-a6b1-4949-93fa-6deb179a2f29)

**Comment by ehab-hassan** [comment]
I like option 1 but that means the user needs to scroll to see it @xmonader what do u think?

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b55dd4



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/952f640a-557e-4269-8f4a-22a053cf1479)

explanation bar added under the table

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4

![Screenshot from 2024-01-29 15-42-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a1723b32-7c93-4c4b-a0a9-81f87217868e)
