### ISSUE TITLE
Node status filter not working

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2040]
Node status filter is broken on mainnet

[Screencast from 18-01-24 16:22:43.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/fd605f31-ac87-418e-9f7e-54503127c15a)

**Comment by samaradel** [comment]
Investigation and Solution:
I see the issue is on mainnet locally, but it works in devnet and ninja, still investigating.

**Comment by samaradel** [comment]
blocked on [#2196](https://github.com/threefoldtech/tf_operations/issues/2196)

**Comment by samaradel** [comment]
For Node 309 it came as a down node with status up nodes

![image](https://github.com/threefoldtech/tf_operations/assets/11662805/edb8eff6-c79b-4f42-af85-f70b33aafae6)

**Comment by Omarabdul3ziz** [comment]
Hello ya Samar, the issue happened originally from gridproxy, it was reported on the issue here https://github.com/threefoldtech/tfgrid-sdk-go/issues/620, it should be fixed and deployed on dev/ninja.

if you need to use it locally you can run the proxy locally on the tag `v0.13.11`, and add the local server on the dashboard env file as the gridproxy url

**Comment by AlaaElattar** [comment]
verified on `https://dashboard.bknd1.ninja.tf/`.

**Comment by khaledyoussef24** [comment]
verified on https://dashboard.bknd1.ninja.tf/.
searched for more than 10 pages and still working fine

<img width="1680" alt="Screenshot 2024-01-31 at 2 11 48 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/609051ea-952a-4288-914b-dacbfc87db6f">
<img width="1680" alt="Screenshot 2024-01-31 at 2 11 50 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/09a423b5-657a-4972-b278-9ebe8e7f23d9">


<img width="1680" alt="Screenshot 2024-01-31 at 2 11 42 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1b68c791-aa5f-4b85-8332-7a6aa1ff2aa7">

**Comment by ramezsaeed** [comment]
Verified:
- https://dashboard.bknd1.ninja.tf/
- 2.3.0-alpha9
