### ISSUE TITLE
(Mainnet Verification) United States isn't shown in the Americas Region or Country filter

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2041]
### Description

https://dashboard.bknd1.ninja.tf/#/deploy/vms/fullvm, 2.3.0-alpha6

For some reason, America doesn't show up on the Regions or Countries filters, while there are many nodes of America showing up in the All filter.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1f1bb786-8d00-48a7-ba38-4f19dac574ab)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2c5f1770-4d4d-45de-b9d9-dc4dd09af1ea)

This could also be applied to different countries, but I found the issue in the United States nodes.

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to the virtual machines.
4. Configure the VM to a small capacity.
5. Load nodes.
6. Change regions to the Americas.
7. Load nodes.
8. Change countries to the United States.
9. Load nodes.

**Comment by samaradel** [comment]
Work in Progress (WIP):
knew where's the problem that caused the issue and working on the solution

**Comment by samaradel** [comment]
Work in Progress (WIP):
Now filters have the missing countries, but when select it doesn't work

**Comment by samaradel** [comment]
Work in Progress (WIP):
for some reason, the dropped countries give ```-1``` on page count... still investigating

**Comment by khaledyoussef24** [comment]
env used devnet 
version : 10f9f49
the same issue exists for canda
while choosing to deploy in node in canda it is shown successfully but when trying to choose it by region it shows that there are no nodes
<img width="1361" alt="Screenshot 2024-01-31 at 1 42 24 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2e8e3057-071c-4131-8904-0eb12a808e55">
<img width="1388" alt="Screenshot 2024-01-31 at 2 06 09 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/57975cc5-9dc1-48d7-bf53-8df7a1fcb896">

**Comment by samaradel** [comment]
WIP:
investigating...

**Comment by samaradel** [comment]
WIP:
only belgium nodes are loaded and still investigating..

**Comment by samaradel** [comment]
@khaledyoussef24 I think you may used some filters above so Canada appeared.

filters are working for all nodes detected but the load Nodes button is working on all nodes and is applicable for filters above  

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/79f21614-69f3-49b6-9219-af8fd90835a9)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/b3bb47e2-14ad-4293-8cd9-d9f713d23a4c)

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

The United States is now displayed on the regions, countries, and load nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a3a078ec-fdbc-4046-9162-b0c9b1c115d1)

[TC2444 - Filter Nodes by Region](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4164673)
[TC2637 - Filter Nodes by Country](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4235871)
