### ISSUE TITLE
Alpha Minting tool output should be in upper case

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2043]
# Issue

When we print the minting data with the Alpha minting tool, the resources should be in upper cases, as @xmonader mentioned.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/0222f969-2d4e-4507-943a-c3b286e44f46)

**Comment by xmonader** [comment]
Did you manage to check the new minting reports interface? On staging.dashboard.dev.grid.tf or https://dashboard.bknd1.ninja.tf/?

**Comment by xmonader** [comment]
Did you manage to check the new minting reports interface? On staging.dashboard.dev.grid.tf or https://dashboard.bknd1.ninja.tf/?

**Comment by Mik-TF** [comment]
Good point. On the latest versions it is in upper case. Closing the issue. Thanks!
