### ISSUE TITLE
Caprover: Can't close the Manage Worker tab after deploying or deleting a worker

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2046]
### Description

https://dashboard.bknd1.ninja.tf/#/deploy/orchestrators/caprover, 2.3.0-alpha6.

I can't close the Manage Worker tab after deploying or deleting a worker in Caprover.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/daacfb28-085b-4373-985e-3e6314b8f634

### Steps to reproduce

1. Navigate to the Dashboard.
2. Connect your wallet.
3. Navigate to Orchestrators.
4. Select Caprover.
5. Enter a domain.
6. Load nodes and deploy.
7. After deploying successfully, open the Manage Worker tab from the deployments list.
8. Deploy a worker.
9. After deploying successfully, try to close the page (you won't be able to, however you try to close, escape, or click outside the dialog).
10. Refresh the page and open the Manage Worker tab from the deployments list again.
11. Delete the worker.
12. After deleting successfully, try to close the page (you won't be able to, however you try to close, escape, or click outside the dialog).

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
-  I reproduced issue, but still trying to find why this happen.

**Comment by mohamedamer453** [comment]
Update:

Work in progress:

Was able to reproduce the issue and found a way to close the dialog by adding a `showDialog` variable that's bound to the dialog component, however now it closes but it doesn't open again, pretty sure that there's something wrong in the way that i manage the state of this variable and that's what's making it not open again after closing but still trying to figure out how to fix it.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version used : 9280a08

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7a64b871-da98-4cbb-bd0a-dfbae7d7a981

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4208504
