### ISSUE TITLE
Failed to create rent contract (devnet)

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2047]
# Setup

- Farm: 4416
- NodeID: 161
- New 3Node with nvidia geforce 1660 super GPU to test on dev net. (see #1806 for AMD)
- zos screen is not displayed since the GPU is used by zos (no issue here)
- GPU card is properly detected by zos/the dashboard.

![Screen Shot 2024-01-20 at 5 05 05 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/5a4fc3ab-e71a-4e70-8efe-74ffe8e7e156)

![Screen Shot 2024-01-20 at 5 04 53 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/e2371fea-d557-4f20-9134-c4dc5dd4b3bc)

![Screen Shot 2024-01-20 at 5 07 47 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/0ff8abc9-0059-48e9-b3b6-9e3dff45acf3)

# Situation

For the following, I tested on 161 first, then tested with 160 to check if it was recurrent. The following contains some screenshots to show what happened. In brief, first time I click reserve it seems to work, but no contracts get created. Then I get an error trying to reserve again.

Note/Feature Request: The display message should be set to last a couple more seconds. It was even hard just to screenshot the display message. Display it for 8 seconds might be sufficient, for example.

When I click **Reserve**, I get first this display message:

![Screen Shot 2024-01-20 at 4 56 10 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/00f42d63-a59d-4c78-8051-c608d327a8af)

Then nothing. And no contracts get created.

![Screen Shot 2024-01-20 at 4 56 49 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/5a19726e-99e4-4aeb-9ee4-eaa316538bd3)

If I try to reserve again, I get this:

![Screen Shot 2024-01-20 at 4 57 12 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/3e7250a6-48c7-41dc-b682-fa9dc799cc8b)

Trying to deploy on a full VM, the node is not rented:

![Screen Shot 2024-01-20 at 5 01 55 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/5e912223-6c71-4585-86f6-5f5ff6326590)

# Troubleshoot and Updates

Let me know if I can try something to fix this. I will keep this issue updated if things change on the 3Node's side.

**Comment by xmonader** [comment]
#1927 devnet is pending tfchain's upgrade to fix these issues :)

**Comment by Mik-TF** [comment]
OK thanks for the info.

I will test the node outside of the grid in the meantime then, until the fix is in.
Let me know if we can close this issue, since there are already related issues/PRs.
