### ISSUE TITLE
no contracts found while deployments are visible in the deployment list

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2048]
### Description

no contracts found while deployments are visible in the deployment list and tft locked for the contracts
env used : devnet
version : 5b50681

- **Twin ID** 201

<img width="1100" alt="Screenshot 2024-01-21 at 7 45 53 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9f2d0362-683e-48fb-bed2-0e262b470fc9">
<img width="1440" alt="Screenshot 2024-01-21 at 7 46 14 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5c97b6e1-5b7d-4844-8a80-f2621fe95dd1">
‹›
<img width="1440" alt="Screenshot 2024-01-21 at 9 07 57 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1836c55d-1ea9-4a33-bdb4-003b11ba1311">

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 2.3.0-alpha7


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/546062d6-95ef-4df8-8717-05893604147b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7b55dd4
