### ISSUE TITLE
UX: Update and add manual links on the dashboard

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/tfgrid-sdk-ts#205]
### Description

We need to update the link for the manual on the dashboard and add a new link for the manual.

### Implementation

- [x] First of all, please update the existing manual link (the third slider) to https://manual.grid.tf/
- [x] Please add a link to the manual beneath the Playground link on the left-hand sidebar

**Comment by ramezsaeed** [comment]
Duplicate to: https://github.com/threefoldtech/info_grid/issues/73

**Comment by samtaggart** [comment]
Hey any clear update on this one? Hard to see what the progress is.

**Comment by Mahmoud-Emad** [comment]
Hello @samtaggart, yeah I just paused the work here as I mentioned above until I fix the threefold connect issue

**Comment by samtaggart** [comment]
OK got it – I saw that it went from In Progress to Verification back to In Progress back to Accepted, so wasn't sure what the latest was.

This issue should be easy to execute, no? It's just a matter of adding a link and changing a link. Maybe we can see if someone else can do it, if you are busy on the ThreeFold Connect issue?

**Comment by Mahmoud-Emad** [comment]
@samtaggart 
Should be updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/243

**Comment by samtaggart** [comment]
Thank you 🙏

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
Updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/367

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
In the development and staging modes, the image and all static files are successfully loaded, as demonstrated in the following example: https://www2.manual.grid.tf/.

However, in the production mode, there seems to be an issue with the image not loading correctly. This discrepancy suggests that there might be a deployment issue specific to the production environment.

**Comment by samtaggart** [comment]
Hi all – Anything I can help with? When will this go live?

**Comment by A-Harby** [comment]
> @A-Harby In the development and staging modes, the image and all static files are successfully loaded, as demonstrated in the following example: https://www2.manual.grid.tf/.

@Mahmoud-Emad in your comment manual link is https://www2.manual.grid.tf/ while the one use in the [dashboard](https://dashboard.dev.grid.tf/) sidebar link is https://manual.grid.tf/ could be that this is different causing the error?

**Comment by Mahmoud-Emad** [comment]
@samtaggart
Hey Sam,

I wanted to bring to your attention an issue with the currently deployed version of the manual. The main page image is not loading correctly. We are aware of this problem and will work on fixing it.

@A-Harby
Yes, Harby, I understand that the links I mentioned are different. The link I provided was specifically for the staging environment, where everything is loading correctly. The reason for mentioning the error is to highlight that the production instance is experiencing this issue.

**Comment by Mahmoud-Emad** [comment]
@all, the issue should be fixed now according to  https://github.com/threefoldtech/tf_operations/issues/1705

**Comment by samtaggart** [comment]
Niceee, so when will this come alive on production?

**Comment by samtaggart** [comment]
Hi friends just checking to see when this will come live on production.
