### ISSUE TITLE
Clicking on the Grace Period Contract doesn't show the locked TFT anymore

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2053]
### Description

Devnet, 5b50681.

When clicking on the grace period contract, it doesn't show me the locked TFT like before; it's just stuck doing nothing.

[screen-capture.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/62727df4-33e4-4f7c-bab0-9f24eeb8002e)

### Steps to reproduce

1. Navigate to the dashboard.
2. Connect your wallet (Twin with a grace period contract).
3. Navigate to your contract.
4. Click on the Grace Period Contract.

**Comment by AlaaElattar** [comment]
### Work in Progress (WIP):
- found the issue and fixing it.

**Comment by A-Harby** [comment]
Verified, Devnet 2311246.

The grace period dialogue is added back with a clarifying message and amount locked.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aa687e8d-12eb-4926-86de-fff02e53f110)

[TC2618 - Grace period-locked TFT amount](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4214522)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 48a660d
