### ISSUE TITLE
Include `Upload` and `Download` rates in select node 

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2054]

**Comment by Mahmoud-Emad** [comment]
#2024

**Comment by Mahmoud-Emad** [comment]
## Issue update

Currently blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/664

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2422

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e1cdba0
upload and download speed are now found in select node



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31f90c49-3fd7-4da6-977f-e25fecb9ac53)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/decf76b7-69bd-46a1-94ab-96683d6b0dca)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4263393
