### ISSUE TITLE
Add processor type in card while selecting node

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2055]

**Comment by zaelgohary** [comment]
Blocked till it's added and deployed on Grid Proxy.

**Comment by zaelgohary** [comment]
WIP:

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057#issuecomment-2021510752

**Comment by zaelgohary** [comment]
Work completed:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/cf31f822-16b4-42e2-a124-ce2b462d61d6)

**Comment by A-Harby** [comment]
Verified, Devnet 5c12959.

The CPU model and version are now displayed on each node.
on the node finder page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/21db91b2-6e73-4724-9966-10cd62e0144b)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0385c217-ec81-47d0-84c9-7716b5ca28e1)
And load the nodes tab on the deployments pages.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3f8675dc-9b04-4a4a-a4cf-6a5367ae7e88)
And for the node with unknown CPU, it doesn't show anything.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/20a9e9b1-15a6-4921-8ce2-203eec2c18d9)

[TC2653 - CPU type is showing on node details](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4250886)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
