### ISSUE TITLE
Replace Node Finder table with node cards

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2057]
Redesign Node Finder to display node cards similar to those used when deploying an app

**Comment by zaelgohary** [comment]
@AlaaElattar Can you be more specific?

**Comment by AlaaElattar** [comment]
> @AlaaElattar Can you be more specific?

@xmonader wants node finder to look like node selection cards. 
replace table with list of cards instead.

**Comment by xmonader** [comment]
> > @AlaaElattar Can you be more specific?
> 
> @xmonader wants node finder to look like node selection cards. 
> replace table with list of cards instead.

If possible 🙈

**Comment by zaelgohary** [comment]
@xmonader something like this?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/cc906252-bddf-4967-8925-479b2f283214)

**Comment by zaelgohary** [comment]
Work in progress:

Replaced table rows w node cards. Currently working on each card details.

**Comment by zaelgohary** [comment]
Work in progress:

Still working on fixing node types.

**Comment by AhmedHanafy725** [comment]
@ehab-hassan @zaelgohary 

in addition to the current card details, the following details should be added too
- node status
- GPU 
- shared, rentable, or rented
- reserve button (maybe we can make this button always shown to the user. If the user is not logged in, we ask him to login to be able to reserve the node)
- CPU type https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2055
- memory type https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2427
- price https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2285

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/3b467b0f-15bb-4f6d-9b1c-d52ca644df7b)

**Comment by zaelgohary** [comment]
Work in progress:

Worked on the card design.

**Comment by ehab-hassan** [comment]
![Frame 327](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/82b24d34-3785-4e17-ae74-ee899a421f72)
maybe when hovering at CPU and Memory Chips show the rest of the details like the example at vast.ai

**Comment by zaelgohary** [comment]
I implemented the following design. I'm not yet sure of the chip colors but what do you think as a start? @ehab-hassan 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4d9d5cd9-504b-4a2a-8027-1cbbb598e043)


GPU nodes: 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/efa9f7fc-a020-4e54-8de2-36eff9275742)

The reserve button is not shown because none of the dedicated nodes are up. but it'll be just as shown in your screenshot.

**Comment by ehab-hassan** [comment]
@zaelgohary nice!! are these the same color for status and type we used before?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/9a08f261-f2a6-4d70-981b-fc7bf66de323)

and the rest is OK with gray and white text.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72
cpu and ram details are now integrated in node finder
node finder tables are now replaced with node cards like the 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b757e77f-5f4d-491d-becb-2c72b0b2b44e)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
please reverify regading Hanafy's comment here: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057#issuecomment-2020334358
and verifiy all related issues as well

**Comment by khaledyoussef24** [comment]
will wait for a dedicated node to be freed so i can verify

**Comment by A-Harby** [comment]
UI color need to be fixed in the light mode.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26a03973-d483-4b11-b3d9-d31071a53103)

**Comment by A-Harby** [comment]
Can you also add a message when there are no nodes available for the filters, something like 'No nodes available" instead of an empty table?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4b7c6a1c-f44e-4c2c-8088-7fda81458c0e)

**Comment by zaelgohary** [comment]
@khaledyoussef24 As for the reserve button, found some bugs and opened an [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2520) for it. You can verify it once it's in verification
