### ISSUE TITLE
when filtering with `Node ID` to node with gpu, the gpu won't appear

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2059]
### Description
- I filtered with Node ID as in the video below to see the gpu card, but i got nothing.

[Screencast from 01-22-2024 12:55:13 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/72ea6d02-b245-4d39-8161-673af076d7de)

- GPu card won't appear unless i toggled to list nodes with gpu only.

- Node ID: 387

**Comment by AlaaElattar** [comment]
- should be solved after graghql release.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/e51737f4-68fd-40d7-b5cc-ca2a4a88b4c6

**Comment by A-Harby** [comment]
Verified,
Devnet, 7b55dd4.

GPU cards appeared when filtering by Node ID or GPU toggle.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2ddacfe-304e-415e-ab2b-0b8c3caed5e8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1dd11f51-ec2b-4314-b87d-5c45ddc7fc7f)

[TC2257 - Filter GPU Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150466)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 3b91b1f

![Screenshot from 2024-02-04 15-45-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a944f32a-668e-41ca-91f2-94cd08ba3176)
![Screenshot from 2024-02-04 15-45-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/93694995-db99-4edd-8fee-9aa60b92f7e6)
![Screenshot from 2024-02-04 15-44-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ad864033-4f6d-4d67-8c9d-b75de43a3a53)
