### ISSUE TITLE
All dedicated machines have no GPU

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2060]
All dedicated machines gives 0  ```num_gpu``` on mainnet although it has on ninja

ex: ```6208```

ninja:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/fbf7bc80-9479-4a43-9a40-b372bd00a8f9)

mainnet:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/b9348fcc-8ec0-412a-8f61-0e4b9e838b4b)

**Comment by AlaaElattar** [comment]
- Blocked on gridproxy release

**Comment by AlaaElattar** [comment]
- verified on `https://dashboard.bknd1.ninja.tf/`

**Comment by khaledyoussef24** [comment]
verified on https://dashboard.bknd1.ninja.tf/
version : 2.3.0-alpha6

<img width="98" alt="Screenshot 2024-01-31 at 11 47 25 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1045cf74-a83a-46d8-b9d4-ea70f1bdff64">
<img width="1680" alt="Screenshot 2024-01-31 at 11 47 33 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf82c15b-7514-4e1d-b583-80682c9eb182">

**Comment by ramezsaeed** [comment]
Verified:
- Ninja https://dashboard.bknd1.ninja.tf/
- 2.3.0-alpha6
