### ISSUE TITLE
closing the withdraw window at bridge transfer does not clear the field 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2064]
### Description
env used : devnet
closing the withdraw window at bridge transfer does not clear the field 
[Screencast from 23 ينا, 2024 EET 08:26:46 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/51af4808-322e-4716-b788-ca3d3198c7a2)

and even clearing the filed the warning will not be cleared when you close and open again
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2c139012-df18-4f84-8724-214d92d24995)

**Comment by AlaaElattar** [comment]
### Work Completed:
- withdraw dialog is separated as component.
- when closing it, it will be destroyed.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 10f9f49

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0cf84842-cfb7-4dc6-9902-cbfa4543fe8d

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150411

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 3b91b1f
