### ISSUE TITLE
Add 'Email' in profile manager when creating account.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2066]
### Description

- The user will also save its email and should be saved in the metadata.

**Comment by samaradel** [comment]
WIP:
Email added in creating account tab and in profile manager but still investigating to get the value of email

**Comment by samaradel** [comment]
WIP: 
Email is working fine in the profile manager, now working on adding email in profile page

**Comment by samaradel** [comment]
### Work Completed:
- Email saved in metadata and added to (connect your wallet, your profile, and TFChain Wallet)
- it can be added/edited in your profile page

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85
adding email and editing it is now available when creating an account and also in my profile page you can edit or add an email.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/11459240-a1af-466b-be87-e2dd479cff72)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/91617e27-48ed-4c61-9963-ab5f5468bf55)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/be94635d-f6e1-4918-8cde-c3640859a0df)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e5a7645e-bc55-47ad-9f3c-563e8634efa2)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/00f5370c-c26b-4c78-9871-bb49d36e7396)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1bf6e54c-f2a4-48ba-937d-07f2d39a682a)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150327
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4246385

**Comment by A-Harby** [comment]
When validating a mnemonic or creating a new account, all the inputs are disabled except for the email.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9f9dbe68-ac0e-4b6b-8bf6-7434451a9dee)

**Comment by samaradel** [comment]
Done on [#2506](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2506)

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/640e5a86-a91e-4626-bdc7-0cab9886fc9d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/656faca9-027b-41ec-94db-2cac56799520)

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2066#issuecomment-2016723920

And I found an issue reported here:https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2555.
