### ISSUE TITLE
Add note that user can't create or activate mnemonic with ed25519

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2067]

**Comment by khaledyoussef24** [comment]
verified on devnet
note is added
version : 10f9f49
<img width="951" alt="Screenshot 2024-01-31 at 3 58 51 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8865df0b-3666-4c7c-a6c7-f613425fcc5c">


when i return to login(without connecting a new wallet) the note is still visible is this right or shall the note disappear 

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/351269c1-1ee3-4615-b09f-04ab9c488e26

<img width="951" alt="Screenshot 2024-01-31 at 3 58 51 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9930be90-2550-4258-9e43-3b944d10030a">

**Comment by AlaaElattar** [comment]
### Work Completed:
- added condition to make sure tooltip appears only in connect tab.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 10f9f49



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d414e131-de1d-4c27-bc68-11de309a7854

**Comment by ramezsaeed** [comment]
Verified:
- Denet
- 3b91b1f
