### ISSUE TITLE
Inconsistency messages in the dedicated node discounts info

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#2069]
### Description
in the dedicated node discounts info; there is inconsistency between the two messages:
- You receive ...........
- You're receiving ..........

### Steps to reproduce

- go to dedicated node page
- put the mouse on the price displayed for each node

![Screenshot from 2024-01-24 15-15-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/550e68b3-d129-40b3-aae5-040cd7572cb6)

**Comment by xmonader** [comment]
Having second thoughts about it

I believe it's more accurate than the suggestion. And I believe the first one should be `you will receive 50% discount if you reserve the full node`

**Comment by AhmedHanafy725** [comment]
### Work Completed

The messages are updated based on the tab as well.

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.
The message updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/41969a99-bd58-4628-b410-093765d1fcac)
