### ISSUE TITLE
grid client tries to reconnect after disconnecting in the mass deployments workflow

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#2073]
### Description

The grid client tries to connect again after disconnecting in the `mass deployments` workflow which leads the workflow to being stuck forever until it fails.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/94f1891c-77cc-4335-a18b-5deb710f39e9)

Other relevant information might be that this issue happened before in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1627 while the script was using `grid3.connect()` and now it uses [`grid3._connect()`](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/mass_deployments.ts#L40) instead.

### Steps to reproduce

- Run the mass deployments workflow.

### Logs/Alerts

Recent runs where the issue happened.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7664682848/job/20889361160#step:6:5067
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7671846150/job/20911090908#step:6:4613
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/7676870445/job/20924933191#step:6:4933

**Comment by AhmedHanafy725** [comment]
### Investigation and Solution:

After some investigation found that there were some envelopes still in the verification step in the RMB onMessage handler while the script was already done. So the disconnect was called and the handler wants to continue his task, and unfortunately the handler reopen the connection to tfchain to get the twin's pk to verify the message. Finally the script is done and nothing to close the connection again. I believe there are some promises that are called asynchronously and it didn't wait for them to finish or even cancel them. Need to take deeper look in the script.

**Comment by AhmedHanafy725** [comment]
### Work Completed

Checked the script and looks like the promises are handled, so I added a new method on the RMB client to wait for the pending responses to finish and also log them to know what are the delayed envelopes as it's not reproducible locally.

**Comment by A-Harby** [comment]
Verified, dev branch.
The issue isn't showing up anymore, and workflow is passing.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f625b4db-7708-47e4-9405-bfafc44eea48)
