### ISSUE TITLE
(Mainnet Verification) Gpu Details card looks weird

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2078]
### Description

Gpu Details card looks weird in  dedicated machines page.
Must include any relevant identifiers like:

- **Mainnet**: backend ninja

### Steps to reproduce

- Open `https://dashboard.bknd1.ninja.tf/` and navigate to dedicated machines then filter with GPU.

### Logs/Alerts

-  ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/43850165-da77-4d77-bc59-6d34f4aa78af)

**Comment by A-Harby** [comment]
What is the use of the scrollbar here?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7fbee015-58bc-41b2-a326-b6351c3fee47)

scrolled left and right and wasn't used to show anything?

**Comment by maayarosama** [comment]
> What is the use of the scrollbar here? ![image](https://private-user-images.githubusercontent.com/109473873/306266560-7fbee015-58bc-41b2-a326-b6351c3fee47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzkyMDAsIm5iZiI6MTcwODkzODkwMCwicGF0aCI6Ii8xMDk0NzM4NzMvMzA2MjY2NTYwLTdmYmVlMDE1LTU4YmMtNDFiMi1hMzI2LWI2MzUxYzNmZWU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwOTE1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2U3MDM0ZmVlZDc5N2M1NTk2MGU4N2I4MzY4NGFiNDYwNzlmYjRmZTU3NDkxNDU4YmYwNjBlZDdkM2QyOTAyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X5bFT6ZTv4L0UXpiRyvM6dgMZ55KdDUPvRigpVWRxyk)
> 
> scrolled left and right and wasn't used to show anything?

Not reproducible .
![Screenshot from 2024-02-26 11-21-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/d7a4248b-dd8d-4c31-ab62-9c660e1b895f)

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

The GPU card details are shown normally.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/47fb7c03-4364-4abc-a182-7d26e765a136)
