### ISSUE TITLE
Not all the Regions are covered

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2079]
### Description

A clear description of the bug is:

The regions that were mentioned in the [comment](https://github.com/threefoldtech/home/issues/1466#issuecomment-1802655704) are.
regions
- All Regions
- north america
- south america
- europe
- asia
- africa
- oceania

But what I can see here are only these, which don't even cover all the world's regions.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c6dda3c-b65d-451a-a9df-288c6a47eb60)

And this is applied to all the filters and load nodes.

**Comment by AhmedHanafy725** [comment]
it only shows the regions that have nodes not all the regions.

**Comment by A-Harby** [comment]
> it only shows the regions that have nodes not all the regions.

This could be applied to the deployments load nodes option, but in the filters page, it wouldn't be better to show all the regions; at least the user can know that there are no nodes in those regions.

**Comment by ramezsaeed** [comment]
@Mik-TF @scottyeager 
whats your feedback here guys:
1- show all regions
2- show only region have nodes

**Comment by Mik-TF** [comment]
I think Harby's argument is a good balance:

- Shows only the regions that have nodes for the deployment load nodes option
- Shows all the region in the Node Finder, even if the regions have no nodes.

For the second point, I could imagine a farmer realising that no nodes are available in their region, so this could incite them to add nodes to the grid, to contribute.

*** 

Note: on my end, on dashboard.dev.grid.tf, when I click Apply to all regions, I can see nodes available. But when I check each region separately, none of them display any nodes. So this looks like a bug in itself.

**Comment by khaledyoussef24** [comment]
all of the 6 regions are vied in the filter of the regions

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94620444-c441-48a8-a32c-f8fcaa5b8129)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4224439

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- efad68b


![Screenshot from 2024-06-09 16-56-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/b1977777-3935-49f1-98c4-dcec2da81671)
![Screenshot from 2024-06-09 16-56-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8442e748-04c4-41db-9625-4defafead396)
