### ISSUE TITLE
Add tooltip to the node selection

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2080]
### Description

A clear description of the bug is:

Based on the comment here, automation and manual node selection did have a tooltip: https://github.com/threefoldtech/home/issues/1466#issuecomment-1817854334.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ec8580e7-f9c2-461f-bbe7-d6fdd04a5e34)

but it doesn't anymore, and it looked a lot more helpful for the user to have them again.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d462bcd7-473d-4b05-8dcf-7e05dabc76d0)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 3b91b1f
the tool tip message is visible now and clear and not confusing 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5de6012e-837b-45c8-b3f4-3a35fd6dd273)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ff32adcd-9218-4d3d-9610-ccbae98887ab)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d395e3db-3a65-456e-b3bb-4b9ba0050ed5)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 76f44e6

![Screenshot from 2024-02-13 13-07-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9ca75b0d-198c-45b3-a724-4e107396f34d)
