### ISSUE TITLE
Add a label for the empty value in nodes details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2083]
### Description

A clear description of the bug is:

Add a dash or some default label for the non-existing value instead of the empty label in your nodes table in farms page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/51194c9d-6545-4101-81c1-cf6204dd78a7)

Must include any relevant identifiers, like:

- **Network**: Devnet

- **Version**: 2.3.0-alpha7

- **Node ID**: 59

- **Farm ID**: 1

### Logs/Alerts

Must include if available:

- Logs/Alerts.
```
{
  "id": "0003138576-000003-a5159",
  "nodeId": 59,
  "farmId": 1,
  "farmName": "Freefarm",
  "twinId": 146,
  "country": "",
  "gridVersion": 5,
  "city": "",
  "uptime": 0,
  "created": 1668086448,
  "farmingPolicyId": 3,
  "updatedAt": 1668086448,
  "capacity": {
    "total_resources": {
      "cru": 0,
      "sru": 0,
      "hru": 0,
      "mru": 0
    },
    "used_resources": {
      "cru": 0,
      "sru": 21474836480,
      "hru": 0,
      "mru": 2147483648
    }
  },
  "location": {
    "country": "",
    "city": "",
    "longitude": null,
    "latitude": null
  },
  "publicConfig": {
    "domain": "",
    "gw4": "",
    "gw6": "",
    "ipv4": "",
    "ipv6": ""
  },
  "status": "down",
  "certificationType": "Diy",
  "dedicated": false,
  "inDedicatedFarm": false,
  "rentContractId": 0,
  "rentedByTwinId": 0,
  "serialNumber": "",
  "power": {
    "state": "",
    "target": ""
  },
  "num_gpu": 0,
  "extraFee": 0,
  "healthy": false
}
```

**Comment by AlaaElattar** [comment]
### Work In Progress (WIP):
- adding `-` to all fields of data, if returned empty.

**Comment by khaledyoussef24** [comment]
verified now in all empty fields that a   `-`
version : 3b91b1f

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/70ed2322-0f62-42cf-90ea-ade8f6ffa209)
