### ISSUE TITLE
Stats cards should be responsive on small screens

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2084]
on https://stats.dev.grid.tf/

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/6296d991-51de-450c-8a8a-43c5e0af3bf7)

**Comment by khaledyoussef24** [comment]
verified on : https://stats.dev.grid.tf/



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/621ac81b-3eb3-4cc9-aaf4-237296762ce9


and even from mobile phone : 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c3ffe659-c956-4f18-aab6-7e436fedc5c6)
