### ISSUE TITLE
Support mycelium on grid client deployments

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2085]
Check the details [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/677)

**Comment by AlaaElattar** [comment]
### Work In Progress (WIP):
- working on adding mycelium and grid client and testing it.

**Comment by AlaaElattar** [comment]
### Work In Progress(WIP):
- mycelium added in grid client and working fine.
- working on adding it in UI.

**Comment by AlaaElattar** [comment]
### Work In Progress (WIP):
- working on multiple case scenarios when updating workloads.

**Comment by AlaaElattar** [comment]
### Work In Progress
- Added some scenarios but still working on the rest and linking with playground

**Comment by khaledyoussef24** [comment]
verified 
env used : devnet
version : 9280a08

deployed multiple machines
using mycelium 

![Screenshot 2024-02-21 at 12 57 48 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/16a3b3a0-752c-47a0-aac8-be8bd76697a6)
![Screenshot 2024-02-21 at 12 57 25 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/01ed0466-e352-42fb-8489-9d41954d5d43)

https://app.testlodge.com/a/26076/projects/40893/suites/235270
