### ISSUE TITLE
loading spinners are different in each component

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2086]
loading spinners should be consistent (have the same color, reasonable size, and in the correct location)

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/69668282-a50e-48a9-9d89-0ed816bca14b

**Comment by samaradel** [comment]
WIP:
getting all spinners, applying only one for all components.

**Comment by samaradel** [comment]
### Work completed:
Replace all loading with tf loading component

**Comment by MohamedElmdary** [comment]
I don't think we should have our own loader component while using vuetify

**Comment by samaradel** [comment]
### Work Completed 
Use Vuetify component instead of creating specific component for loading

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/099ce51a-f0ed-4570-86e1-e4ff127bda35)

@samaradel  is this related to the merged pr ?

**Comment by samaradel** [comment]
I see the old code is back for some reason , will check it with [#2414](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2414)

**Comment by samaradel** [comment]
### Work Completed:
- Fix loading icon size
- Fix node details charts

**Comment by samaradel** [comment]
### Work Completed:
Remove ```indeterminate``` from v-progress-circular default props

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2560fc09-f60f-4e8c-996f-e509b9ab640c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/85d8de49-1dcf-45cf-bec4-4c0ae913678a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/17302221-d4ca-4117-8889-29fcea2cd430)

loading spinners are the same and verified in both light and dark mode.
