### ISSUE TITLE
when click on reload Gpu details card, it diappears.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2087]
### Description
- when there's error loading gpu card and i click `reload`, the dialog disappears.

Must include any relevant identifiers like:

- **Mainnet**: `https://dashboard.bknd1.ninja.tf/`

- **Node ID**: 780

### Steps to reproduce

- open `https://dashboard.bknd1.ninja.tf/`
- navigate to `dedicated machines`
- filter with `GPU Node`
### Logs/Alerts

[Screencast from 01-30-2024 12:37:36 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/7f776cc4-2bf2-4a6b-9275-883934a009a2)

**Comment by A-Harby** [comment]
Verified, Devnet 9280a08.
The retry doesn't disappear anymore, and I could keep pressing until it works.
[screen-capture (1).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f77d6ef8-114b-407b-b8e1-f3011729fef5)
