### ISSUE TITLE
Static Website Solution: Create a new app to serve a directory with caddy

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2088]
- Create a docker image containing caddy, git, and zinit inside.
- This image should take the git url and clone the repo.
- Serve whatever is in the repo with caddy server.
- Convert this image to a flist.
- Use this flist and create a new app in the dashboard.

**Comment by maayarosama** [comment]
1. Work Completed:
A docker image was successfully created

2. Work in Progress (WIP):
All zinit errors are resolved now, and every process is successful. Next step is converting the image to an flist and test against a vm

**Comment by maayarosama** [comment]
Work Completed:
Converted The image to an flist and tested it against a vm and can ssh to the machine

Investigation and Solution:
The following errors need investigation

```[+] caddy: {"level":"warn","ts":1709465488.7981684,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"Caddyfile","line":4}```

```[+] caddy: {"level":"info","ts":1709465488.8023553,"logger":"http.auto_https","msg":"server is listening only on the HTTPS port but has no TLS connection policies; adding one to enable TLS","server_name":"srv0","https_port":443}```

**Comment by maayarosama** [comment]
Work Completed:
- Fixed docker image (Fixed caddyfile, fixed caddy zinit process, added a domain zinit process) https://github.com/threefoldtech/tf-images/pull/218

Work in Progress (WIP):
- A solution for caddy should be added in the dashboard

**Comment by maayarosama** [comment]
Work Completed:

- Added a solution in the dashboard

Work in Progress (WIP):

- Adding a readme file in info-grid

Investigation and Solution:

- (dashboard issue) whenever a domain is added to the deployed instance it produces a bad gateway unlike using a public ip which serves the files correctly

**Comment by maayarosama** [comment]
Work Completed:

Added a solution in the dashboard
Work in Progress (WIP):

Adding a readme file in info-grid
Investigation and Solution:

- testing with a custom domain

**Comment by maayarosama** [comment]
Work Completed:

Work in Progress (WIP):

- Docker Updates
   -  Remove node from docker image if not needed
   - Add branch flag
   - Pulling policy (not prio)
   - Ports should be default ports not 9000
   - separate ``` caddy run ``` into it's own service
   - Remove ssh service as zos takes care of it
   - add a bash script for caddyfile construction and execute it in the zinit service

- Dashboard Updates
   - change title html directory
   - check if you can add ip while using custom domain

**Comment by maayarosama** [comment]
Work Completed:
- Docker Updates
   -  Remove node from docker image if not needed
   - separate ``` caddy run ``` into it's own service
   -  Add branch service

 
- Dashboard Updates
   - change title to html directory
   - check if you can add ip while using custom domain

Work in Progress (WIP):

- Docker Updates
   -  Remove sshkey service as zos takes care of it
   - Pulling policy (not prio)
   - Ports should be default ports not 9000
   - add a bash script for caddyfile construction and execute it in the zinit service

**Comment by maayarosama** [comment]
Work in Progress (WIP):

Trying to use caddy git plugin for pulling policy

**Comment by maayarosama** [comment]
Work in Progress (WIP):

- Working on comments on the pr
- will be using crone jobs for the pulling policy instead of the plugin

**Comment by A-Harby** [comment]
Devnet, 51f43a7.

The action button is empty.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6af5305e-5f06-4296-addb-5edd7333da3c)

And the docs need to be updated to the latest changes.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1c90bb55-584d-4462-b502-726d6e35ef35)

**Comment by maayarosama** [comment]
can we Upgrade the [Flist](https://hub.grid.tf/mayarosamaa.3bot/mayarosama-caddy2-v1.flist) to an official one?  @hossnys @PeterNashaat

**Comment by hossnys** [comment]
there is a comment on your PR for that image [here](https://github.com/threefoldtech/tf-images/pull/218#issuecomment-2106855402) , then we can ask Maxime for promoting it to official apps on hub .

**Comment by maayarosama** [comment]
> there is a comment on your PR for that image [here](https://github.com/threefoldtech/tf-images/pull/218#issuecomment-2106855402) , then we can ask Maxime for promoting it to official apps on hub .

Comments are resolved now, the pr should be reviewed and merged

**Comment by hossnys** [comment]
@maayarosama another comment there please check https://github.com/threefoldtech/tf-images/pull/218#discussion_r1618725746

**Comment by hossnys** [comment]
@maayarosama PR approved

**Comment by khaledyoussef24** [comment]
caddy is now integrated to the dashboard


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6833c165-9b2c-4958-9cce-45b89b1fd490)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/576ab626-079a-4414-81a1-177502c2961b)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/65472b4e-7c26-4299-af7c-68530c906cd4)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8582e0ba-ca03-458a-b109-e5c6d65a9345)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4289467
