### ISSUE TITLE
Use wider range for wireguard ports

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2090]
grid client is using ports from 2000 to 8000 for the wireguard ports. if it works well [here](https://github.com/threefoldtech/tfgrid-sdk-go/issues/680), we should update it to a wider range.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/20430ac045834def9400139218d57aa33817aaa4/packages/grid_client/src/primitives/network.ts#L487

**Comment by Mahmoud-Emad** [comment]
As Ramez said it was a code-related issue and it should be solved now
