### ISSUE TITLE
[TFChain client] Disconnect the provider on connection  failure  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2092]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/ea9aea7610b4571d77b8742875ca37030bebbb9d/packages/tfchain_client/src/client.ts#L98-L103

if we provided an invalid url will keep trying to connect: 
![Screenshot from 2024-01-30 14-32-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/78f87e29-67ad-45ce-bed4-aaf840c9643d)

i suggest to add `provider.disconnect();` inside catch block

**Comment by 0oM4R** [comment]
works fine, changes on chain client didn't effect the solution

**Comment by Mahmoud-Emad** [comment]
As Ramez said it was a code-related issue and it should be solved now
