### ISSUE TITLE
Add a little green check after validating the hexseed

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2096]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d6ca86c4-3656-4b08-a975-ec6128af599e)

Would be cool if we append a green check to provide interaction as the text change could go unnoticed

**Comment by samaradel** [comment]
@A-Harby check mark fixed for non-supported keypair type ```ed25519```

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/b666e09b-37ac-46b8-8336-99786784349f)

for the ux we can't control icons beside validation message atm

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

verified while using Mnemonic or Hex Seed
<img width="1680" alt="Screenshot 2024-03-26 at 2 24 15 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eb893809-ce3f-4336-9362-5bc44e4f6ef5">
<img width="99" alt="Screenshot 2024-03-26 at 2 24 18 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8f5af7be-4862-4b58-8348-8956cfe809df">
<img width="125" alt="Screenshot 2024-03-26 at 2 24 53 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a6608483-f5c9-41f6-9dec-7237b8edf2ca">
<img width="95" alt="Screenshot 2024-03-26 at 2 25 01 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06e7376c-081b-4a41-b62a-7a71aa22ae93">
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
