### ISSUE TITLE
No way to filter nodes with free IPs on the Dashboard

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#2109]
### Description

On the node finder page there is no filter for nodes with free public IP. I think it would save a lot of time instead of using the grid-proxy for that.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/3da9ff67-ae94-4320-889d-2afe60fa2e58)

### More

this is on devnet version `2.3.0-alpha7`

**Comment by khaledyoussef24** [comment]
free public ip filter is added to the dashboard.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6f6be8fb-d7e0-4f7d-892b-2c4d6c3e0b71)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b8f77c5-bfce-4f0e-859b-ca654ac91368)

but still no free public ips with working nodes to verify it

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

tried the node finder with filtering 1 public ip : 
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/48eb4c02-d81a-446d-9d77-8f41933f655e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8ec64d20-9398-4705-8fa2-f0e11aba3860)
found the node :
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2b1ae971-6935-4426-bb82-021e6cdc7adc)
made a deployment using the node:
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2675b5a9-a363-454e-bcfb-2eaae89a4121)

there is no more public ip so used the filter once more
node nodes were found 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/82c29b51-4a62-4531-ac33-2e470447e58f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/be036836-8948-42cc-94b0-9978e9160f09)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4251350
