### ISSUE TITLE
Duplicate placeholder in filters

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2110]
### Description
There is a duplication in the filters with the `HDD` field

- **dev**:

### Steps to reproduce

- Go to dashboard 
- Go to the node finder page and watch the filters

### Screenshots

![image_2024-02-01_12-31-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/3433891e-3258-4190-91c7-4dd39bd435a7)

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

- Updated the placeholder of the RAM unit in the filters component

**Comment by khaledyoussef24** [comment]
the same problem exist in the free ssd 
they have the same duplicate message for the tool tip
while one should be for the free ssd and one for the minmum ssd 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2c8d1ddb-abff-488f-827f-4c117dabacc0)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/42bb17af-e137-4f3f-8783-29f6bb75b22b)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 3b91b1f



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/adc7392b-79ce-474b-bc24-88dca788b4e7)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 76f44e6

![Screenshot from 2024-02-13 13-13-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/3963a90c-2cb9-433a-8267-9c13c916d163)
