### ISSUE TITLE
All routes are broken on development and staging

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2112]
### Description

All routes are broken on development and staging

Must include any relevant identifiers like:

- **Dev & Staging**:

### Steps to reproduce

- Go to the dashboard
- Go to deploy tab then applications
- Click on any application

### Screenshots

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f43dac5d-5233-47c3-9f19-ebf6ff371678)

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work Completed

- Updated the router, adding the 'solutions/' route.
- Implemented an enum (ApplicationRoute) to assign variables to all routes, improving code quality.

### Work in Progress (WIP)

None.

### Investigation and Solution

- Investigated the need for a router update and identified the 'solutions/' route addition.
- Implemented an enum to enhance code reliability and eliminate typos in the hard-coded approach

**Comment by khaledyoussef24** [comment]
verified routes are fixed and reached all solutions and applications



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/16346046-25a7-45f1-9c75-23097c82bb5e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6a3a05f6-4330-447a-9f9d-8ae7b2cb8aec)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b11b502d-328c-4910-9cd5-79314d63c41b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7cab676e-ff12-4955-8938-89a2cf6a213e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06c704a7-0f8e-4532-9b05-f51cdb0da10b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3ae188d9-eda5-40ec-a7a6-32f28186008c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f38395a4-d51e-47cd-94b8-2d6632fe4943)
