### ISSUE TITLE
Specify contract type

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2114]
### Description

Each contract should be specified whether it's a network, gateway or a VM

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/89aa680d-3a71-4754-ac16-5cbb1f8db26c)

**Comment by zaelgohary** [comment]
Investigation:

The deployment type comes from metadata in [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/a676de16bbc7c2ba7f8ab0febe84ae8048127ed6/packages/playground/src/components/contracts_list/contracts_table.vue#L235). If we want to add it somehow to the table, we would have to make the same call * number of contracts which sounds like a lot. FYI, the same call is being used to show the deployment details but only if the user clicks on the show details icon on the right.

**Comment by AhmedHanafy725** [comment]
@zaelgohary the workload type is already in the metadata of the contract, no need to do this call to get the type.

**Comment by zaelgohary** [comment]
Work completed:

Added type column to the nodes table.

**Comment by zaelgohary** [comment]
Issue is blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1219

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

contract types and now specified on the dashboard (tried multiple of deployments)

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d9a54253-4404-4273-871f-e20d6507a4c7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4ebd7a8d-0285-4b8e-ad2e-933e5b9b0414)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4157417

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959

![Screenshot from 2024-04-02 14-47-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7d2b07cb-593d-4342-bb75-9daa436a150b)
