### ISSUE TITLE
Add searchbar in the solutions component

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2117]
To have a generic search functionality to filter out solutions

**Comment by zaelgohary** [comment]
Work completed: 

Added search input in applications. Now the cards list will be filtered based on the search term.

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet
search in now added and functional 

![Screenshot 2024-03-25 at 10 41 32 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3012cf6c-7a54-4b45-9eb2-4db46d520ecb)
![Screenshot 2024-03-25 at 10 41 39 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/673a7f0c-ec77-494d-94ad-ff5e47278b7f)
![Screenshot 2024-03-25 at 10 41 44 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e9053824-42a9-47da-b578-d82721fe1183)
![Screenshot 2024-03-25 at 10 41 52 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/36f1f2ee-8227-446c-891d-3d642c246fae)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4246719

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622

![Screenshot from 2024-04-01 00-55-18](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/af0490f3-43bb-410f-80ea-fd23ae48ab73)
