### ISSUE TITLE
while node details dialogue box is opened you can still interact with the dashboard elements 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2122]
### Description

while node details dialogue box is opened you can still interact with the dashboard elements 

network : devnet
version : 3b91b1f

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/198e1feb-0d6c-4d91-b17e-5cc6e2209825

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ffd27fe-a94b-48db-9fb0-d1accad98798

i think it should not be abled when the dialogue opens.

**Comment by MohamedElmdary** [comment]
This is default behaviour as this component is bottom sheet not dialog with overlay
