### ISSUE TITLE
Contracts page can't handle a large number of contracts

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2125]
### Description

A clear description of the bug is:

1. The contract list can't load a large amount of contracts well (contracts were made from TFRobot).
Maybe the contract list should be the same as other tables, with pages and items per page, to prevent the loading of that large amount of contracts all at once.

2. The error message should be improved because it was not me who aborted anything.

3. The total cost of contracts is stuck on loading like that.

Must include any relevant identifiers, like:

**Network**: Mainet, [Ninja](https://dashboard.bknd1.ninja.tf/#/deploy/contracts-list).

**Version**: 2.3.0-alpha6

**Twin ID**: 7189

### Steps to reproduce

1. Navigate to the dashboard.
4. Connect your wallet (account with a lot of contracts).
5. Navigate to the Your Contracts page.

### Logs/Alerts

Must include, if available:

- Logs/Alerts.

`Error while listing contracts due: The user aborted a request.`

Screenshots or screen records.

[screen-capture.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/48ba1cd1-2e08-4913-a673-9582cf720b1e)

**Comment by AlaaElattar** [comment]
### Work In Progress :
- handle pagination from `grid_client`.

**Comment by AlaaElattar** [comment]
### Work In Progress:
- The pagination won't be handled from `grid_client`.
- I will get contracts form grid proxy and it's already paginated there.
- working on preparing data from proxy and update table to paginate.

**Comment by AlaaElattar** [comment]
### Work Completed:
- I added function for getting contracts from proxy.
- added `v-data-table-server` for handling pagination

### Blocked:
- blocked on this issue `https://github.com/threefoldtech/tfgrid-sdk-go/issues/911` to be able to get and paginate on both `Created` and `GracePeriod` together.

**Comment by AlaaElattar** [comment]
### Work In Progress:
- Copying changes to new branch (old one has many conflicts).
- update changes after pagination is done from proxy client.

**Comment by AlaaElattar** [comment]
### Work In Progress:
- Table update to `v-data-table-server` to handle pagination.
- Normalized Contract Interface updated to match data from grid proxy.
- handling loading each type of contracts separately.
- updating `normalizeContract` function.
- fixing bug in pagination.
- updating gridproxy types to filter with array of contract states

**Comment by AlaaElattar** [comment]
### Work Completed:
- Pagination handled and all functionalities are working right.

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
version : ad30945

contracts pages performance enhanced and loads requests fine now,

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c73238ce-00f3-4f7e-b627-d9a6a728a4ee
