### ISSUE TITLE
Enhance Node Finder experience

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2129]
Filters take almost 100vh from the viewport and user needs to scroll to see the table.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a124565b-1f49-4251-b45b-569a44d24a6e)

Suggested solution: Let's use compact filter input instead. Also, not all filters should be shown to the user. Some should be shown as default and the others can be added if the user needs (from a dropdown menu or sth).

Reduce columns in nodes table. Users can access additional details by clicking on individual table rows anyway.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c4153ea1-97db-4a5b-b9b6-a58d258831ca)

Display node type hints above the table instead of below it. With a pagination setting of 50 items per page, placing this information below the table would require excessive scrolling for the user.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/958383fe-37e7-4759-9f48-053a8d15a4bd)

**Related Issues:**
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2255
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2056
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2369
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1892
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2285

**Comment by ramezsaeed** [comment]
Related to:
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2132

**Comment by ehab-hassan** [comment]
work in progress(WIP)

the horizontal filter was designed to take 15% of the  screen and by default closed, but while we have many items to filter we need to back to put it on the left side @MohamedElmdary suggest to give the user the option to hide the sidebar at pages contain filter( Node Finder,dedicated-nodes,farm-finder) so we can have more space for filter
 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6a003148-c76d-44ec-9d8d-ccd5e23e30f2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1d8a10c6-c8f8-4efe-bb52-629a4c782222)

Note: that'll cause scroll at the table on small screen

**Comment by A-Harby** [comment]
1. Can you change the place of the `Select Node Status` filter? It's the most used filter on the page, and for better UX, it should be easily accessible instead of being at the bottom of the page.
2. Having the apply button at the top of the filter doesn't seem like the best position for it; it doesn't feel good to keep scrolling up and down to choose filters and apply them.
3. Maybe you can also group similar inputs together instead of having the type input and list input in shuffles, and then toggles in last (and order them in the most used first).



[screen-capture (23).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b872ac7f-5141-46bf-b61c-ab46836731e1)

**Comment by A-Harby** [comment]
After discussing it with @ehab-hassan we agreed that it would be better for the apply button to be at the top and reorder the filter with most useful first (so the user scrolling would be minimal).

The order is:
1. The Toggles
  A. Dedicated
  B. Gateway
  C. GPU
2. Node status filter
3. Node ID
4. Farm ID
5. 3 other lists (farm names - regions - countries)
6. Free public IPs
7. Free resources
8. Min resources

**Comment by ehab-hassan** [comment]
Work Completed
![Untitled-1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/5e474b8b-4497-4bcc-82d7-4060fbb92b0a)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : bef3f8f
the new order of the node finder : 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f37c7608-91a4-40b9-b29e-7edafd318d35)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ef2b5e97-7355-4118-b0e9-482f3d804503)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/25af9116-d154-47e5-b4da-39befc0e713c)

1. The Toggles
2. Node status filter
3. Node ID
4. Farm ID
5. 3 other lists (farm names - regions - countries)
6. Free public IPs
7. Free resources
8. Min resources

nodes are now in cards which is better for small screens and no need for horizontal scrolling.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0e826e07-00e1-49d1-8e2c-19f4e13bd544)


toggles now only take action after clicking on apply


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/570199f2-cfa9-4558-9199-f9173464f16c

[node cards](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459)
[filtering toggle](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150465)
[filters](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150464)
