### ISSUE TITLE
some fields in the node finder  are not important and duplicated

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2132]
### Description
env used : devnet
some fields in the node selector  are not important and duplicated.
<img width="1358" alt="Screenshot 2024-02-06 at 2 31 03 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e6d7dea0-2ad6-42e3-9e98-04c9931b9bd1">

while deploying user seek for the minimum available  ssd not the node total ssd:
<img width="673" alt="Screenshot 2024-02-06 at 2 31 24 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/79d8092d-e893-49e1-85d9-7918fbd9f73b">
<img width="710" alt="Screenshot 2024-02-06 at 2 31 30 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4263629d-0114-4505-898a-b83e91ce2649">

the same for hdd and ram :
<img width="1338" alt="Screenshot 2024-02-06 at 2 34 33 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5610de58-48a2-4dd2-af16-b4cf963e7bc7">
<img width="747" alt="Screenshot 2024-02-06 at 2 34 44 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b9c4a695-1590-4c62-a55c-7665654d3f18">

so fields can be less confusing and all these filters

**Comment by MohamedElmdary** [comment]
if we merged dedicated node and node finder tables together so this issue won't be valid anymore https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1418 .. however if we didn't we might remove some of these filters

**Comment by samaradel** [comment]
blocked on merging dedicated machines

**Comment by AhmedHanafy725** [comment]
As we gonna merge the dedicated machines page into the node finder page, we will need all the filters
