### ISSUE TITLE
dashboard: remove /64 from IPv6 deployment result

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-ts#2133]
### Description

When one deploys via the dashboard and asks for a public IPv6, a /64 is added which brings confusion since it's not required to use the IP.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88312671/922e9223-2af1-47ff-b2d7-8a60825769aa)

### Implementation

Just remove the /64

**Comment by khaledyoussef24** [comment]
verified on devnet

version : ac5cd85



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39918a16-66a5-4d66-8802-0ffeb10167b0)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/073737bd-affe-40ab-8fe6-b124489ade78)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150332

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622

![Screenshot from 2024-04-01 00-05-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4e100dfa-c949-42ce-838d-08c48e78c94b)
