### ISSUE TITLE
dashboard: node finder -> set a default filter for 'Up' nodes

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/tfgrid-sdk-ts#2134]
### Description

When one visits https://dashboard.dev.grid.tf/#/deploy/nodes a list of all nodes is generated. Most visits to this page will be about online nodes. Maybe it's good to have a default filter that shows only up nodes by default?

### Implementation

On vitising the 'node finder' page, set a default filter 'Select node status' -> 'Up'

**Comment by ramezsaeed** [comment]
Maybe we can sort the up nodes first

**Comment by MohamedElmdary** [comment]
related issues
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/566
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/243

**Comment by zaelgohary** [comment]
WIP:

I added the sort_by & sort_order to grid proxy and playground however, the sorting behavior for both is different than it should be when I try from Proxy Swagger. Still looking into it.

**Comment by zaelgohary** [comment]
Investigation:

After some investigation, I found that the sorting query only works when ret_count is set to false as seen below.

When ret_count is set to false:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/82dfcb60-eb2f-4136-80c3-98ea5c58edcd)


With ret_count is set to true:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a86d108c-bcb8-4a7a-b807-4cef80631b9c)


Sorting doesn't work here. (check the scroll bar)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f40c7c4c-8ecc-455a-a069-414a546d1232)

Sorting normally works here.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f9039c5e-3ad4-40a7-963a-abad294cdb39)

**Comment by zaelgohary** [comment]
Work completed:

Set default status to 'Up'.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

now the `UP` nodes are sorted first then when all the `up nodes` are finished the down nodes start to appear


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/51aa4fdc-8a38-4d71-9ab8-946a2ecc5c4e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0247e3be-47a8-4653-8737-e5421d465b98)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e

sorted by UP nodes first now and down nodes come next.

![Screenshot from 2024-04-14 19-08-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4ab08a43-902c-4a9c-abc0-85250dc2ebae)
![Screenshot from 2024-04-14 19-08-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/24c8e686-a7f2-4f16-b995-b9d2df4fe179)
