### ISSUE TITLE
Cache the twin's info while sending and receiving envelope over RMB

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2137]
The current implementation is getting the twin's info each time the RMB client tries to send or receive an envelope which is slowing down the client's performance.

### Suggested Solution

When a twin is fetched, the RMB client should store the info in memory with an expiration time and keep using this twin's info while the expiration is not exceeded. Once it's expired, the next request should fetch the info again and store it.

**Comment by zaelgohary** [comment]
WIP:

Created a map to store twins with its timestamp. Used the twin from the created map (if its timestamps < 10 mins) in client. Currently working on implementing it in envelope class.

**Comment by zaelgohary** [comment]
Work completed:

Exported a function to check if a twin with a specific id exists in the map. If so, return it, else, get the twin from the chain as usual. Used the function in all the places where we get the twin from.

**Comment by AhmedHanafy725** [comment]
Verified. The cache was added and with 10 mins to invalidate
