### ISSUE TITLE
Have the chat icon movable, closeable or reducible

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2139]
# Feature request

A user has trouble hitting some buttons on the dashboard since the chat icon is in front.
While de-zooming is a quick fix for now, it's not user-friendly.

I guess there ar many ways to solve this, perhaps being able to move the chat icon, close it or reduce it, might all work.

# Reference and pictures

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/c50d5724-403b-4d0d-8cd1-735fafd82e8e)

[from this discussion](https://t.me/threefoldfarmers/69455)

**Comment by TullysInc** [comment]
- I observed a fix in the chat platform's widget settings and it seems to have resolved the issue.

- It doesn't overlap content across dashboard, forum & the [website](www.threefold.io). Appears on the left side of the pages.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/ca643609-ea27-4dab-8e26-87abe8b03612)


- Could however be a concern towards the new dashboard: https://next.dashboard.grid.tf/#/deploy/nodes as it overlaps the menu. It can be altered when we switch for good.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/0fea719a-243d-450a-ba50-61661be56ec9). 

Note: there are also on-going discussions/research for alternative opensource chat platforms as there are plans to migrate at some point in the future.

**Comment by TullysInc** [comment]
@ehab-hassan - In the chat platform's widget settings, I reversed the location of the icon back to the right. While there isn't a concern with overlapping the buttons in the case of the old dashboard, it currently overlaps the dashboard logs icons.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/114f2079-e915-470e-bbd2-3b5013a726ca)

I'm contuining to check the widget settings to see if the icon can be moved a little bit more away.

**Comment by TullysInc** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/3b2b1b2f-d74d-46d3-826b-135ba1fc8ae0)

The placement seems a bit more appropriate now. Please let me know if this works.

**Comment by ehab-hassan** [comment]
@TullysInc I tested it and works fine with me @Mik-TF can you check if ok we can close this issue

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0139c63
the chat icon now does not block the dashboard log or any component and not even the manual like it was occuring


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/295fecaa-207a-473d-a17c-12afb4ffa910)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4295007
