### ISSUE TITLE
[testnet]Allow renting standby nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2143]
currently, the dashboard allows renting only the online nodes, but now [tfchain is supporting renting standby nodes](https://github.com/threefoldtech/tfchain/issues/923) and the famerbot can wake the rented node up if the farm has an up-and-running farmerbot (can ping the farmerbot before renting to make sure it's running). So besides showing the online nodes, the dashboard should also show the standby nodes.

**Comment by AlaaElattar** [comment]
### Work in Progress :
allowed renting standby nodes, but still testing and comparing it with proxy.
