### ISSUE TITLE
Change mail config filters on discourse

### ISSUE THREAD

**Issue by PeterNashaat** [threefoldtech/tfgrid-sdk-ts#2152]
### Description

- There are 2 issues in discourse mail server config : 
   - Admin Email filter on accepts emails ends with @example.com, which it can be without ```@example.com or @gmail.com``` like [sendgrid can be](https://docs.sendgrid.com/for-developers/sending-email/drupal#:~:text=Under%20SMTP%20Authentication%2C%20set%20your,Password%20%2D%20SendGrid%20API%20Key) ```apikey``` only 
   - Password can't exceed 15 characters, passwords can be more that 15 characters specially it can be auto-generated ```like in sendgrid and gamil``` and will be more than 15 characters

### Steps to reproduce
- Deploy discourse instance from dashboard.

- Screenshots or screen records.
 ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/13523434/6b6a57e3-5159-42ba-bb81-56d58c044a6e)

- related issue 
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1403#issuecomment-1819108551

**Comment by zaelgohary** [comment]
@PeterNashaat Can you provide me with all valid admin mails? Also, what should the password length limit be?

**Comment by PeterNashaat** [comment]
for admin emails can vary significantly depending on the email service provider or an API key for services like SendGrid, and the password length can vary. For traditional passwords, a common recommendation is a minimum of 8 characters, but for enhanced security, some services (like gmail or sendgrid ) enforce longer lengths, up to 16, 24, or even more characters.

**Comment by zaelgohary** [comment]
Work completed: 

Edited Discourse validation and admin email label.

**Comment by khaledyoussef24** [comment]
verified on devent
version : ac5cd85
regex for the email fixed user can now use apikey not only emails.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/608338bb-3e92-4266-92e9-2a63968309a4)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9b805447-f5ba-46e2-9485-0426443274ae)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f8e7cdff-fba3-4236-88aa-0db93c191233)

**Comment by khaledyoussef24** [comment]
can we change the `Admin Email/Username` to something which hints that we can use `apikey` ?

**Comment by zaelgohary** [comment]
> can we change the `Admin Email/Username` to something which hints that we can use `apikey` ?

What do you suggest?

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/af4ea428-1965-4d32-84af-9e28feb1a4a3)

[TC2175 - Discourse Input/Configuration Validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150384)

> can we change the `Admin Email/Username` to something which hints that we can use `apikey` ?

**Comment by PeterNashaat** [comment]
- Same issue but with taiga instance smtp config.
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/3e6288ee-4900-4c50-bc7c-a221a79a43be">

**Comment by A-Harby** [comment]
> * Same issue but with taiga instance smtp config.
> 
> <img alt="image" width="1064" src="https://private-user-images.githubusercontent.com/13523434/362227998-3e6288ee-4900-4c50-bc7c-a221a79a43be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTI5MzMsIm5iZiI6MTcyNDg1MjYzMywicGF0aCI6Ii8xMzUyMzQzNC8zNjIyMjc5OTgtM2U2Mjg4ZWUtNDkwMC00YzUwLWJjN2MtYTIyMWE3OWE0M2JlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEzNDM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkYTg5MGQ1MGEyMzBlZGIxZjFiYTJkN2NhOTBiMGIyMGFlNGFjMTcyNzdhM2VhYTdjYjdmNDdkOTVlYWQzZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xAbJ7SzMFgKLofw-A60Q3Dqrzv0Uss6VVXjtLHKSTlE">

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3343 I reported it in a new issue.
