### ISSUE TITLE
K8s Master form disappears upon deleting memory field

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2154]
K8s Master form disappears upon deleting memory field.

[k8s.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e6b1435e-4c62-492f-b53d-f9a364d00345)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c295fe65-252c-418d-a23c-afdbb588f0a9)

Must include any relevant identifiers like:

- **Network**: Dev

- **Version**: 2.3.0-alpha8

- **Twin ID**: 89

### Steps to reproduce

- Go to K8s
- Select Mater tab and delete the memory input

**Comment by zaelgohary** [comment]
Work completed:

The issue happened because undefined case was not handled in case of CPU & memory. Fixed by making them optional and assigning default cu to 0.

**Comment by A-Harby** [comment]
Verified, Devnet edc4bf8.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0f3283b7-7cb8-416f-85dd-3eb1fb7212e9)

[TC2169 - Kubernetes Input/Configuration Validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4150378)

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.3.0-alpha12



![Screenshot from 2024-02-27 14-59-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9027dcc7-1d15-4967-b220-0013c46c6c1b)
