### ISSUE TITLE
k8s deployments from go-cli have the same deploymentData as the one from playground

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2158]
### Search first
k8s deployments from go-cli have the same deploymentData as the one from playground

### Description
k8s deployments from go-cli have the same deploymentData as the one from playground
so we can't differentiate between deployments

A clear description of the bug:
can't differentiate between deployments

Must include any relevant identifiers like:

- **Network**: any

- **Version**: alpha9

- **Twin ID**: any

- **Node ID**: any

- **Farm ID**: any

- **Contract ID**: any

### Steps to reproduce
1. deploy k8s cluster from go-cli
2. List k8s in dashboard
3. You won't be able to tell which deployment from outside dashboard

### Logs/Alerts

Must include if available:

- Logs/Alerts.

- Screenshots or screen records.

- Contract or deployment details.
- if it's a solution error then SSH into the vm and run `zinit log`.
- Console Errors and Network Requests from developer tools (ctrl+shift+i or F12).

**Comment by AhmedHanafy725** [comment]
### Work Complete

fixed here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2164

**Comment by khaledyoussef24** [comment]
verified made a deployment from the grid cli and added a worker easily from the dashboard


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d251fc08-edbe-4dfb-8b12-e818d67e214c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/886ce693-8ed2-473e-8854-70ef69b44a96)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2c33fdab-ebd8-4397-a795-abf7d51e8291)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/61462b6a-9334-4dff-90af-f95cd8ef6f1f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b47b43f8-8c9f-4fac-9f26-b32549ba1a3b)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4229253
