### ISSUE TITLE
Handle height of 2 cards in same row

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2160]
### Description
- when one of the cards are taller than the other, it looks really wierd.

![Screenshot from 2024-02-13 14-50-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/65019622-3a96-43d6-9f83-f3b3a14f1e17)

Must include any relevant identifiers like:

- **Network**: Dev

- **Node ID**: 31

### Steps to reproduce

- open `https://staging.dashboard.dev.grid.tf/`
- navigate to `Node Finder`
- open node 31

**Comment by samaradel** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/14126823-6c8c-4a42-a02f-bdab7e819ee3)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/2ad4d55f-d148-46ff-b7a6-b8d6b69eccb9)

@ehab-hassan what do you think ?

**Comment by ehab-hassan** [comment]
@samaradel ok let's test this option it ll be better, or we can put the small tables at the top and the tall one below in case we are sure it is always taller than others all the time

**Comment by samaradel** [comment]
### Work Completed:
- Adjust node details column height
- Decrease node details card width
- Merge location and country cards in one card 
- Decrease node resources chart dimension

**Comment by samaradel** [comment]
### Work Completed:
- Fix node details card on small screens

**Comment by A-Harby** [comment]
Verified, Devnet 5c12959.

The node details tab is responsive with all the tabs shown on it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3b8d7d91-e5f6-4c88-b7e6-70ae4e7b8157)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/32935873-2cb7-4e0e-b46a-ebcc2feaeaa6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3ad4b168-ea2e-45f1-90a5-67bcbc28ebe7)

[TC2251 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460)
