### ISSUE TITLE
deployment list in k8s does not load deployments

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2161]
### Description

after deploying k8s from the grid_client  deployment list in k8s does not load anydeployments 

- **devnet**:

-  versions :183c55a :
![Screenshot 2024-02-14 at 10 16 43 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cbb21a97-9ec1-435d-8bbf-2f6114f8b86c)

contracts id : 87479 , 87480

twin id : 201

script used : 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/kubernetes.ts

**Comment by khaledyoussef24** [comment]
the contracts after exporting
`[{"contractId":87479,"type":"node","state":"Created","createdAt":"2/15/2024, 12:42:30 PM","nodeId":168,"solutionName":"hellotest","solutionType":"network","expiration":"-","consumption":0},{"contractId":87480,"type":"node","state":"Created","createdAt":"2/15/2024, 12:42:30 PM","nodeId":168,"solutionName":"newMY","solutionType":"vm","expiration":"-","consumption":0.1097305}]
`

**Comment by AhmedHanafy725** [comment]
> the contracts after exporting `[{"contractId":87479,"type":"node","state":"Created","createdAt":"2/15/2024, 12:42:30 PM","nodeId":168,"solutionName":"hellotest","solutionType":"network","expiration":"-","consumption":0},{"contractId":87480,"type":"node","state":"Created","createdAt":"2/15/2024, 12:42:30 PM","nodeId":168,"solutionName":"newMY","solutionType":"vm","expiration":"-","consumption":0.1097305}] `

@khaledyoussef24 what I can see here is a vm, not a kubernetes deployment. are you sure of this data?

**Comment by khaledyoussef24** [comment]
I don't have any other contracts now shall i try to delete them and check if the k8s deployment list is back to normal ?
@AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
yes, please delete them, then try to deploy a new one, and check if it will be listed or not.

**Comment by khaledyoussef24** [comment]
<img width="1680" alt="Screenshot 2024-02-18 at 3 33 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66acab2a-809b-445d-9cf6-ed1a1230f398">
still getting the same even after deleting them.
 checked deployment of other apps deployment list is working fine in them all.

**Comment by khaledyoussef24** [comment]
will check the script of list all contracts

**Comment by khaledyoussef24** [comment]
after deploying k8s from the dashboard it worked again
but after deleting the deployment it returned to the same behavior
<img width="1680" alt="Screenshot 2024-02-18 at 3 40 29 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0269220c-fd3d-4c18-aaa8-4551788f352a">

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9280a08
![Screenshot 2024-02-22 at 4 48 01 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6a377c02-f19d-4a67-a7a6-ae0f4278b0e4)

now k8s deployment list working fine

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4217555

**Comment by khaledyoussef24** [comment]
the same problem started to occur again but this time the deployment was from terraform instead of gridclient
![Screenshot 2024-03-28 at 10 03 16 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a111c5ac-5101-4b14-98c8-428549c5c7e1)

**Comment by khaledyoussef24** [comment]
should we move it to 3.14 ?

**Comment by khaledyoussef24** [comment]
the contracts in the contracts list shows some metadata of the deployment and load fine
![Screenshot 2024-03-28 at 11 39 25 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d32ab87b-5ff8-4d3f-8370-504e4275703d)

the master contract
```
{
  "version": 0,
  "twin_id": 201,
  "contract_id": 104656,
  "metadata": "{\"version\":3,\"type\":\"kubernetes\",\"name\":\"mr\",\"projectName\":\"Kubernetes\"}",
  "description": "",
  "expiration": 0,
  "signature_requirement": {
    "requests": [
      {
        "twin_id": 201,
        "required": false,
        "weight": 1
      }
    ],
    "weight_required": 1,
    "signatures": [
      {
        "twin_id": 201,
        "signature": "e208019ab2351a1f4152843fe0eb244e599a2b7ea60aba9078565f6447f345332c5e29e6f714ac0805854432a54117e7cebca2e4f724ec49854322769aec1687",
        "signature_type": "sr25519"
      }
    ],
    "signature_style": ""
  },
  "workloads": [
    {
      "version": 0,
      "name": "mr",
      "type": "zmachine",
      "data": {
        "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist",
        "network": {
          "public_ip": "",
          "planetary": false,
          "mycelium": {
            "Network": "myk8s",
            "hex_seed": "2ed267408776"
          },
          "interfaces": [
            {
              "network": "myk8s",
              "ip": "10.1.3.2"
            }
          ]
        },
        "size": 0,
        "compute_capacity": {
          "cpu": 2,
          "memory": 2147483648
        },
        "mounts": [
          {
            "name": "mrdisk",
            "mountpoint": "/mydisk"
          }
        ],
        "entrypoint": "/sbin/zinit init",
        "env": {
          "K3S_DATA_DIR": "/mydisk",
          "K3S_FLANNEL_IFACE": "eth0",
          "K3S_NODE_NAME": "mr",
          "K3S_TOKEN": "12345678910122",
          "K3S_URL": "",
          "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzqacdkB4MFRT+ElXplBq0PTtVPUBQ7jimXnKmlL2zxuToE1vtq2FvcGIyyqWKg5kizARbfnBAkbfK+x52h/kfiDF2V69HJXMGGqAVcYVRnvjxc5026SC6sagwi94ZBXht8zeAdDaffLmUzjcNrd5v92qYBNGXGugPQdM6beoNYseUm6FXn8O/PHCz15RbQyUc7IC7o1uz5GzmatB3ZmW7Z/dIXS+FJ+K00JtJ8WaWsPFJfYs9X5btwm/wbNhL7ciZouk1c9HD/m2vUA6tIM6sLu8bHsdchXN4dPI5Brw8Kb+2BjrIcRUPO8mT0v4P4dWa9ObJ5oVPIFRHATGvh7Ip khaledgx96@gmail.com\n"
        },
        "corex": false
      },
      "metadata": "",
      "description": "",
      "result": {
        "created": 1711611846,
        "state": "ok",
        "message": "",
        "data": {
          "id": "201-104656-mr",
          "ip": "10.1.3.2",
          "planetary_ip": "",
          "mycelium_ip": "5ee:b286:c94e:e6a9:ff0f:2ed2:6740:8776",
          "console_url": "10.1.3.1:20002"
        }
      }
    },
    {
      "version": 0,
      "name": "mrdisk",
      "type": "zmount",
      "data": {
        "size": 2147483648
      },
      "metadata": "",
      "description": "",
      "result": {
        "created": 1711611840,
        "state": "ok",
        "message": "",
        "data": {
          "volume_id": "201-104656-mrdisk"
        }
      }
    }
  ]
}
```

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/terraform-provider-grid/pull/909
pr just merged, waiting for terraform release

**Comment by AhmedHanafy725** [comment]
there is a new version released a week ago

**Comment by khaledyoussef24** [comment]
version : efad68b
I made a deployment using terrafrom k8s but did not load in deployment list


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1e9478a1-5729-4574-9b21-26d6445e4edb)
may be it is related to #1389

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9fd76a5
deployed k8s and worked fine on dashboard (followed the steps of commenting the `solution type`)
terraform version : 1.11

<img width="837" alt="Screenshot 2024-06-11 at 12 11 08 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/45495f6d-3525-4c06-b422-89c5240a9b91">

<img width="1128" alt="Screenshot 2024-06-11 at 12 01 31 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/11cf0848-e508-46c1-a283-92c3e447e206">
<img width="712" alt="Screenshot 2024-06-11 at 12 10 53 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fbc9087a-03c3-4b65-a4b1-76fde55232d5">



https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4295958
