### ISSUE TITLE
Use better table formatting in headers

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2169]
### Description
Use new headers feature from vuetify https://vuetifyjs.com/en/components/data-tables/basics/#headers

## Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1219

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1219

**Comment by A-Harby** [comment]
Verified, Devnet 0d1e63f.

All the pages with tables have changed to this new UI table format.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/554b462f-e3a2-4cce-95a1-496c53b689b5)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/79f97130-1d3f-4742-acfd-54e34f5eaf9c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/378baf5b-b614-48e6-a6b0-403fc37d3947)
