### ISSUE TITLE
VIrtual Machines table looks weird 

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2172]
### Description

- The table looks weird

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/d6dbe878-36b6-4838-83b9-fc527cb5b589)

- **Network**: dev

### Steps to reproduce
- deploy vm, then wait for it to appear in table.
- but when i refreshed the page, it returned normal

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac5cd85



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/49921680-96b8-4419-a7fd-52586c474087)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/41642772-1f85-4537-b008-5d2f08eb3ab0)

tried multiple deployments and now the deployments in the table are all same height

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e

![Screenshot from 2024-04-14 18-56-48](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a339fbf5-9d87-4b70-b21f-b7fc7f5f5a50)
