### ISSUE TITLE
Virtual Machines table not consistent with k8s table

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2173]
### Description
- In virtual machines table if there's no public ipv4, will add `-`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/39ddf5c0-ef6e-4208-8f09-07eeec3b5e5c)

- In k8s table `None` will be added in its place.

![Screenshot from 2024-02-15 12-20-37](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/70a8c787-90f4-4b77-8282-faf8be062704)

- This should be consistent in all tables of playground not just these tables only.

- **Network**: Dev

**Comment by zaelgohary** [comment]
Work completed:

Replaced all 'None' values with a dash.

**Comment by khaledyoussef24** [comment]
all tables are consistent now :
<img width="1440" alt="Screenshot 2024-03-28 at 2 42 37 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7d007a3f-d72a-46f3-a6c7-aedfb149d9d6">
verified on devnet
version : f530d72
