### ISSUE TITLE
a hint should be added for the user to disable Yggdrasil before connecting with mycelium

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2180]
### Description
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2186
through the test run found out before connecting to mycelium vm user should disable yggdrasil 
using 
`systemctl stop yggdrasil` on linux 
'launchctl kill yggdrasil' on mac

may a clear msg help the user and save time to connect easily ( and it may be added to mycelium docs as well)
![Screenshot 2024-02-15 at 5 22 44 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b7adaf49-1634-4376-85ca-5bde004e4bd0)
may be added here

**Comment by AhmedHanafy725** [comment]
no need to do this as they can work together
