### ISSUE TITLE
New grid_client created after disconnecting fails to connect to TF Chain

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2181]
I have a script which is meant to periodically check a twin's balance using `grid_client`. On each iteration, it creates a new client and at the end it disconnects. After waiting some time, it tries again. The problem is that only the first iteration is successful without error each time the script is run.

It appears that after calling `disconnect`, the client reconnects automatically, which is unexpected.

I am running v2.2.0 on mainnet.

Here's the script (saved under `grid_client/scripts`):

```
import { getClient } from "./client_loader";
import { log } from "./utils";

async function main() {

  while (true) {
    let grid3
    try {
      grid3 = await getClient();
      log(await grid3.balance.getMyBalance())
    } catch(err) {
      log(err)
    } finally {
      if (grid3) {
        await grid3.disconnect()
      }
    }
    new Promise(resolve => setTimeout(resolve, 5000))
  }
}

main();
```

And the output:

```console
$ yarn run ts-node --project tsconfig-node.json scripts/simple_balance_loop.ts
yarn run v1.22.21
$ /home/scott/threefold/repos/tfgrid-sdk-ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/simple_balance_loop.ts
Credentials loaded from env variables...
2024-02-16 09:35:59        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-02-16 09:35:59        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
{ free: 0.0150136, reserved: 0, frozen: 0 }
disconnecting
WebSocket connection closed unexpectedly.
Reconnecting...
2024-02-16 09:36:04        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-02-16 09:36:04        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Connected!
Error: Client couldn't connect to wss://tfchain.grid.tf/ws after 10 seconds
    at TFClient.wait (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/tfchain_client/dist/node/client.js:65:19)
    at async TFClient.connect (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/tfchain_client/dist/node/client.js:92:13)
    at async GridClient.connect (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/src/client.ts:100:7)
    at async getClient (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/scripts/client_loader.ts:32:3)
    at async main (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/scripts/simple_balance_loop.ts:9:15)
{ free: 0.0150136, reserved: 0, frozen: 0 }
disconnecting
Error: Client couldn't connect to wss://tfchain.grid.tf/ws after 10 seconds
    at TFClient.wait (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/tfchain_client/dist/node/client.js:65:19)
    at async TFClient.connect (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/tfchain_client/dist/node/client.js:92:13)
    at async GridClient.connect (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/src/client.ts:100:7)
    at async getClient (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/scripts/client_loader.ts:32:3)
    at async main (/home/scott/threefold/repos/tfgrid-sdk-ts/packages/grid_client/scripts/simple_balance_loop.ts:9:15)
```

I think the underlying issue has to do with how connections are retained at the [class level](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/a4a560c48be03259fab1e928b45427df6b232e17/packages/tfchain_client/src/client.ts#L51) in the underlying TF Chain client.

Firing up a REPL:

```
$ cd ../tfchain_client
$ /home/scott/threefold/repos/tfgrid-sdk-ts/node_modules/.bin/ts-node --project tsconfig-node.json

import { QueryClient } from "."
let client = new QueryClient('wss://tfchain.grid.tf/ws')
await client.connect()
await client.nodes.get({id: 1})
await client.disconnect()

await client.connect() // This hangs
QueryClient.connections['wss://tfchain.grid.tf/ws'].connect() // This works
await client.nodes.get({id: 1})
```

So neither new clients nor existing clients are able to connect once `disconnect` is called from the client, but reconnecting by calling `connect` on the connection itself works.

-----

I also tried on `v2.3.0-alpha10`. It runs into a bit different issue after a couple of loops; this time waiting on replies to RMB messages, but I never sent any RMB messages (the final message repeats until I issue a keyboard interrupt):

```console
yarn run v1.22.21
$ /home/scott/threefold/repos/tfgrid-sdk-ts/node_modules/.bin/ts-node --project tsconfig-node.json scripts/simple_balance_loop.ts
Credentials loaded from env variables...
2024-02-16 19:43:56        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-02-16 19:43:56        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
Lock acquired
2024-02-16 19:44:06        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
phase: {"applyExtrinsic":10}, section: balances, method: Withdraw, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM",10158]
phase: {"applyExtrinsic":10}, section: tfgridModule, method: TwinUpdated, data: [{"id":5545,"accountId":"5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM","relay":"0x72656c61792e677269642e7466","entities":[],"pk":"0x0250f7007355f694edb979d1cdc7d94ecfcd3e724bd2fb92ae81bbdfdcd6796f8b"}]
phase: {"applyExtrinsic":10}, section: balances, method: Deposit, data: ["5FqHp29vhYLcAyou8nNGY9T4S8bPTyMQq5GwqkvXBgb81Qjs",10158]
phase: {"applyExtrinsic":10}, section: transactionPayment, method: TransactionFeePaid, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM",10158,0]
phase: {"applyExtrinsic":10}, section: system, method: ExtrinsicSuccess, data: [{"weight":{"refTime":287975000,"proofSize":3893},"class":"Normal","paysFee":"Yes"}]
Lock released
Lock acquired
2024-02-16 19:44:12        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
phase: {"applyExtrinsic":6}, section: balances, method: Withdraw, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM",10610]
phase: {"applyExtrinsic":6}, section: tfkvStore, method: EntrySet, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM","0x6d61696e2f353534352f6e6574776f726b732f4e5739323132656630342f696e666f2e6a736f6e","0x354a3663676136594e6c597a78744e436b69465179314d30304f6c74756d4c56595a374e495a4e505336394a6f583938497863356c4e516d7a5362784c30565545695577797a77727469324a5466693449446c3962625156705436376d4249716858786e7a4d6d684c6f6773385a7450677458446d6d6b4b324b726b4a564d4975507a686b4d63342f634b34454751736779346342576d5a584f666b66426b65744547775132316c4638377561566732546e7973734f2f797532694d"]
phase: {"applyExtrinsic":6}, section: utility, method: ItemCompleted, data: []
phase: {"applyExtrinsic":6}, section: tfkvStore, method: EntrySet, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM","0x6d65746164617461","0x3447344b785834427a686e58643571766f7479756137785979576d764c34793176434d474f574c577773624a6c5a5a3534495658303434527659507273334565314c527061714c5730356a706f6a454543356d45744862664d61764b436852702f4e72526932556f7631356c32354f6d4a686b332b6e47514267427a7435575556306a6b4e426646442f7a4a5a714638757372336431473047554871356668336858374c6a5a62525936706374355a49544e38436d5344374c74712f586274522f49504130316854554c634a682b596b67636942756e7961716275574333534331767667306379583934327530634e526f78543930614d7832556f5469513d3d"]
phase: {"applyExtrinsic":6}, section: utility, method: ItemCompleted, data: []
phase: {"applyExtrinsic":6}, section: utility, method: BatchCompleted, data: []
phase: {"applyExtrinsic":6}, section: balances, method: Deposit, data: ["5DkuYHpdkAThvgLrt9zdPh2DATodb7cXkWihzx6Toh5bbLim",10610]
phase: {"applyExtrinsic":6}, section: transactionPayment, method: TransactionFeePaid, data: ["5F9PuNdNXi7MpPs86Y8jgcGiQanhXXJrwem44aPYyqwfMjpM",10610,0]
phase: {"applyExtrinsic":6}, section: system, method: ExtrinsicSuccess, data: [{"weight":{"refTime":372323681,"proofSize":0},"class":"Normal","paysFee":"Yes"}]
Lock released
{ free: 0.0129368, reserved: 0, frozen: 0 }
disconnecting
2024-02-16 19:44:15        API/INIT: RPC methods not decorated: transaction_unstable_submitAndWatch, transaction_unstable_unwatch
2024-02-16 19:44:15        API/INIT: Not decorating runtime apis without matching versions: TransactionPaymentApi/4 (1 known), Metadata/2 (1 known)
{ free: 0.0129368, reserved: 0, frozen: 0 }
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
Waiting for the rmb responses to be received before closing the connection
...
```

**Comment by xmonader** [comment]
The main point behind WebSockets is to establish a persistent, two-way communication channel between a client and a server. This contrasts with traditional HTTP requests

Establishing a WebSocket connection involves a handshake process,  and recreating clients frequently adds unnecessary overhead to both your client and the server, and generally, not necessarily in your case, if the server maintains any information associated with a specific WS connection (e.g. session data), disconnecting and reconnecting forces you to reestablish that state again. And, definitely could be subject to rate limits 

I suggest that you move the logic outside of the loop, and the client internally when it tries to invoke a call on the chain, it will reconnect if, for whatever reason the connection is closed.  That being said, will still look into the issue to provide a way out.

**Comment by scottyeager** [comment]
This is meant to be a minimal example of an issue experienced by one of our users. Originally they were holding a connection open indefinitely. Later they switched to an approach like shown after being advised by our team that it was better to disconnect and reconnect after each request.

I believe the loop time is actually 60 seconds in the user's app. But I don't think rate limiting is at play here, because I can restart node immediately after a keyboard interrupt and it will reconnect. Also note that if I reach into `QueryClient.connections`, I have better luck reconnecting than when calling the abstraction.

The issue is that it seems our library can under some circumstances get into a state where it can never reconnect to a given TF Chain endpoint without rebooting the interpreter or doing some intervention under the hood.

**Comment by AhmedHanafy725** [comment]
### Work Complete 

The client was trying to reconnect in case the network was not reachable for 10 minutes. Now also, added a new option (`keepReconnecting`) for the client to reconnect after 10 minutes and when the network is back, the client should operate normally. (it's available on v2.3.0-rc2)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/5b457136-7787-4286-978e-c0c9929c3c01)


> Also note that if I reach into QueryClient.connections, I have better luck reconnecting than when calling the abstraction.

This issue was on v2.2.0, but it's solved on alpha releases of v2.3.0, so it should be working on v2.3.0-alpha10 or later releases.

> I also tried on v2.3.0-alpha10. It runs into a bit different issue after a couple of loops; this time waiting on replies to RMB messages, but I never sent any RMB messages (the final message repeats until I issue a keyboard interrupt):

The grid client opens an RMB connection on start and keeps sending ping messages to ensure that the connection is not broken. It waits till the pong message is received and it will close the connection and the client will exit gracefully.

**Comment by A-Harby** [comment]
Verified, Devnet branch.
Connection and disconnection seem fine, even on a slow network.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/54be1d82-a7ca-47b8-9b4c-50419832bd6a)

@scottyeager If you still have any issues, please comment.

**Comment by scottyeager** [comment]
Thanks. I'll ask the upstream user to test and report back if there's any further issue.
