### ISSUE TITLE
should we add a column in the deployment list for mycelium deployments ?

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2182]
### Description

the deployments with mycelium id are shown in the planetary column should every ip have it's own field
<img width="1680" alt="Screenshot 2024-02-18 at 10 40 10 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/58ad9323-7f22-4157-a1da-82bb8f0547bf">

env used : devnet
version : a4a560c

**Comment by ramezsaeed** [comment]
For now planetary Network IP means (yggdrasil OR Mycelium)
Both are not supported at the same time.
we can add a chip for now beside the IP to be clear its Mycelium IP.

**Comment by AhmedHanafy725** [comment]
now mycelium is supported alongside yggdrasil and each one has its column

**Comment by khaledyoussef24** [comment]
<img width="1357" alt="Screenshot 2024-03-03 at 10 47 23 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1dbe3343-ae4e-4cd4-aef6-7a3cdd0a7b4e">
verified on devnet
version : 433ad62

https://app.testlodge.com/a/26076/projects/40893/suites/235270?expand_section=429970#case_4211674

**Comment by ramezsaeed** [comment]
Verified:
- Testnet
- 2.3.0-rc1
