### ISSUE TITLE
Mycelium: Testsuite run and coverage on testlodge

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#2186]
- Create a test suite on teslodge to cover all mycelium testing scenarios:
- should inclide:
    - test section for Grid client
    - test section for dashboard

testsuite: [mycelium](https://app.testlodge.com/a/26076/projects/40893/suites/235270)

Related story:
- https://github.com/threefoldtech/home/issues/1480

**Comment by khaledyoussef24** [comment]
work done :
tested vms and installed dependencies to make sure of the connections between the vms.
tested deployments of the applications to make sure that they are working fine.
designed the test suite and added test cases to cover all of the repo.
faced some issues :
#2187
#2183



blocked on
#2198 
#2194

**Comment by khaledyoussef24** [comment]
work done :
- checked the new docs https://manual.grid.tf/mycelium/mycelium_toc.html and added a case for it.
- fixed some of the test cases.
- tried all of the apps with mycelium ip deployment.
- added more test cases .
