### ISSUE TITLE
Apply Email as default option

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2188]
As [2165](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2165) and as @zaelgohary [comment](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2165#pullrequestreview-1882444809) we recommend to add email as default option in solutions that require email.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72




![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/82fd3efa-03f5-404d-8d66-8be7a09d811e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0a1ba3b0-7aff-4b94-bad3-6add0e68beda)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150327

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622


![Screenshot from 2024-04-01 00-00-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/59160deb-0d21-4c62-9d0f-6c18ef6db781)
