### ISSUE TITLE
Set the correct pk in case of hex secret is used

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#219]
the current state is when the mnemonic is used, the pk generated by the ts client is the same as the pk generated by the rmb-peer. but when using the hex secret, the key generated by the ts client is different than the one generated by the rmb-peer which makes the e2e fails

check the implementation in rmb-peer [here](https://github.com/threefoldtech/rmb-rs/blob/main/src/peer/e2e/mod.rs#L28)

**Comment by mohamedamer453** [comment]
gridclient mnemonic validation doesn't accept hex key as a valid input.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/852cbb3e-cbdd-4343-a76e-09e29ab83b2e)

**Comment by AhmedHanafy725** [comment]
this happens after using the new tfchain client, the error check needs to be relaxed to accept hex secret as well
