### ISSUE TITLE
Dedicated is being used in /nodes/$nodeId which is not support by gridProxy

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#22]
`/modules/nodes.ts#49`

```ts
@expose
@validateInput
async getRent(options: RentContractGetModel) {
    const proxyURL = this.config.rmbClient["proxyURL"];
    return send("get", `${proxyURL}/nodes/${options.nodeId}?dedicated=true`, "", {})
        .then(res => {
            return res;
        })
        .catch(err => {
            throw err;
        });
}
```

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/tfgrid-sdk-ts/pull/811

`/nodes/$nodeId?dedicated=true` was replaced with `/nodes/$nodeId`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/802b8d00-5c2f-4b4b-bb22-2b75b3d89ad0)

and  `rentContract` was updated with `rentContractId`
