### ISSUE TITLE
Allow zero in the HDD input in Pricing calculator

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2202]
### Description

A clear description of the bug is:
The deployments now can be done without including any HDD, so the calculator should accept zero values here.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/83295d14-b37d-45a4-8268-0ca01fffefea)

**Comment by samaradel** [comment]
### Work Completed:
Allow ```0``` in disk HDD field

**Comment by khaledyoussef24** [comment]
zero is now allowed


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7611007b-1091-4a8b-bb4d-5448b19ee54f)

but if you used -ve number it leads the calculator to this : 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f0f20395-2b65-4cc9-9d66-22740e3c6949)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f1203989-1649-4a14-98fc-9b8c47045950)

can the validation be for the field as a best practice ?

**Comment by samaradel** [comment]
### Work Completed:
Add validation to ```memory``` and ```ssd storage```

**Comment by samaradel** [comment]
handled [#2518](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2518)

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.

[TC2604 - Pricing calculator input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4213523)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/80330ddf-03fc-42f0-8e98-9100af400734)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/58dd43c6-d78c-4f70-bb6e-e3b474d18604)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
