### ISSUE TITLE
Add network usage in pricing calculator

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2215]
## Description

Proposition: add network usage in pricing calculator, as explained here by @mohamedamer453: https://gist.github.com/mohamedamer453/6ac5cdac2fb35bbf3d1462e89c8bb1e7

### Implementation

Default value could be 0. Users can put the data usage to add in the total cost.

### More

Work in relation with the current manual [issue on info_grid](https://github.com/threefoldtech/info_grid/issues/424) by @A-Harby.

Please remove if duplicate, but I haven't seen it in any issues search nor on the devnet version of the dashboard.

**Comment by maayarosama** [comment]
1. Work Completed:
Adding calculate nu method in calculator model, this method should be added to the pricing method and final calculations
