### ISSUE TITLE
fetching data from stats summay endpoint failed

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2216]
### Description

fetching cards data failed due cors error
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/2b340821-ff25-4e8d-96de-d33e4f6d8276)

- **Network**: Dev

### Steps to reproduce

go to https://staging.dashboard.dev.grid.tf/#/ , and check the console

### Logs/Alerts
````
/#/:1 Access to fetch at 'https://stats.dev.grid.tf/api/stats-summary' from origin 'https://staging.dashboard.dev.grid.tf' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
````

**Comment by 0oM4R** [comment]
@hossnys can you help with this issue ?

**Comment by hossnys** [comment]
this happened after @coesensbert already added this header to our caddyfile 
```
header /api/stats-summary Access-Control-Allow-Origin "*"
```
so please @0oM4R revert that change from your nginx config so we let it handled only from our side on caddy .

**Comment by hossnys** [comment]
ok, so no need to revert it from nginx config as we'll need it in place in case we deployed it on K8s cluster , so we will remove that header from Caddyfile to avoid that duplicate , it's fixed now on both https://stats.dev.grid.tf and https://stats.02.dev.grid.tf 
removed [here](https://github.com/threefoldtech/grid_deployment/commit/2119f588394a8b50dfb22f9e1c7adba7ad382f2b)

**Comment by A-Harby** [comment]
Verified, Devnet edc4bf8.

The errors aren't shown anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ee89553-9469-4c18-bac3-280e18da6e60)
