### ISSUE TITLE
API-WS: disconnected from wss://tfchain.grid.tf/ws: 1006: connection failed.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-ts#222]
Description:
The famerbot configure successfully and has been working fine for a couple of weeks, and certainly getting this error.

### Steps to reproduce
Restart the famerbot using this command: docker compose rm -f -s -v; unfortunately, the issue remains the same.

![photo_2023-05-09_17-59-36](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/601a9faf-4ba0-4923-b8fd-36727ab1feb8)

**Comment by scottyeager** [comment]
The farmer tried running the farmerbot on a different computer and it works. Also, seeing that `rmb-peer` is also failing to connect per this screenshot, I don't think there's anything specific to the grid client happening here.

**Comment by shng4you** [comment]
Thanks, Scott, for the update. Hence I will close this ticket.
