### ISSUE TITLE
Make the manual url configurable 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2220]
- Use the staging manual for devnet, qa, and testnet. (staging's url: https://www2.manual.grid.tf/)
- Update all docs urls in the dashboard to use the configured manual url.

**Comment by zaelgohary** [comment]
Work completed:

Configured [manual URL](https://www.manual.grid.tf) as a global prop and used it in all playground pages.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0c52b77a-964f-4681-a417-6929e4237081)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ffa3db2-e71b-4208-a0d2-29c6f12561e5)

verified that all networks now leads to the [same link](https://www.manual.grid.tf/)
