### ISSUE TITLE
Wallet info dialog is not correctly responsive

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2221]
### Description

In the large screens, the qr code goes down while it has enough space to be beside the text fields to be there.

- **Network**: devnet

- **Version**: alpha12

### Steps to reproduce
- login to the dashboard.
- just click on the wallet on the top right in the dashboard.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/619fb5dc-126d-462b-8e46-cc8165db3e53)

**Comment by samaradel** [comment]
### Work Completed: 
Fix TFchain card on big screens

**Comment by khaledyoussef24** [comment]
verified and fixed the dialogue is now responsive  
version : bee662d
network : devnet



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/96f2d302-2aa7-48b1-a49d-0baabbbbc2f5

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
