### ISSUE TITLE
Minting page looks strange for the rest pages

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2224]
the header looks different

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/43bd5f56-6b42-4223-96a3-d24232e267b8)

the rest looks

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/811355a3-e665-4267-8fea-35b8a1e7b110)

**Comment by AhmedHanafy725** [comment]
Also, the view button I think should be centered beside the text field

**Comment by ehab-hassan** [comment]
WIP
all these pages need a title card 
Miniting
Node Finder
VM #2908
orchestrators #2908
Application 
Contracts
SSH Key
Farm Finder

some of theme finished

**Comment by ehab-hassan** [comment]
Work Done
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b7a84cb9-8590-4d72-bc9d-c5a608b35ed2)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac03039
now looks like rest of the pages

![Image](https://github.com/user-attachments/assets/862a793b-4dae-4376-abc6-59e25ec60f2d)
