### ISSUE TITLE
Error message in the debug / logs tab

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2227]
### Description

Devnet 9280a08.

A clear description of the bug is:

The error isn't shown as an error, and some strings aren't supposed to be shown, like %c and timeout color. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/033b54e5-b188-4a3a-ba59-3037565f101a)

**Comment by samaradel** [comment]
WIP:
still investigating...

**Comment by A-Harby** [comment]
@samaradel their is an [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2262) to update the debug tab UI. To not have a color, boxes, and all of that, so maybe check it first if you want, saving time on doing this issue if it is going to be removed anyway.

**Comment by samaradel** [comment]
@A-Harby as per discussion with @AhmedHanafy725 it will not be removed, maybe it should move somewhere else, so it's ok to be fixed.

**Comment by A-Harby** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/38b8239a-b440-4816-9739-fe19ab000222)

**Comment by zaelgohary** [comment]
Work completed:

Used console.error instead of console.log and rephrased error msg in both load vms function & load k8s.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e1cdba0
the log is now shown as error


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/01ed0e14-cb86-4cde-b98b-f946d6ea82c4)

but the ` }`at the end which follows the vm name log shall be removed also so error can be more clear

**Comment by samaradel** [comment]
### Work Completed:
Remove an extra ```}``` from logs when deployment fails

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
version : ff9d79e



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e9c374e5-31b2-4349-b477-d9245268468e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8dec4ab4-c1d0-4088-beed-82db11a6bd82)
