### ISSUE TITLE
Logs tab improvement

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2228]
### Description

A clear description of the bug is:

After pressing the load more logs button, it showed me all the logs. I thought it would have pages, not all of them, or a change button to load all.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2f4cd4ba-e3a2-4a02-b436-082fd5a80fd2)

Also, with the large number of logs, the tab gets very slow to open.

And can we change the way it closes to be consistent with the other tabs? Now you have to click on the top part only to close. On other tabs, you can click on close, oustide the tab, or esc.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 2c8c89b
logs now loads 20 by 20 so it is controllable


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ff64b98b-2990-4734-9908-8e12efdf9b9b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d80a053e-7ff0-4caa-bb11-f61a6fc2c2ca)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2aba356a-7cfa-4dc5-918c-f3fd0c394f03)
