### ISSUE TITLE
Stats website raise an error after showing part of the data 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2229]
### Description

A clear description of the bug:

the stats website calls 6 endpoints, currently one of them is failing, https://gridproxy.grid.tf/stats?status=standby
this makes the website shows field to fetch error after the timeout, i don't think this is a good UX,
we need to wait for all the results first then show the data or the error 

- **Network**: Dev

- **Version**: 2.3.0-alpha12

### Steps to reproduce

- go to https://stats.dev.grid.tf/
- make sure that main net toggle is enabled 

### Logs/Alerts

Must include if available:

[Screencast from 22 فبر, 2024 EET 03:08:29 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/5e370656-5fbb-4668-99b2-dd41e16f8ccf)

**Comment by A-Harby** [comment]
Is it fixed or deployed on the stats devnet? because its not working.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f49c741b-c6d3-4799-9ed7-3c84306762eb)

**Comment by 0oM4R** [comment]
@A-Harby  yes it got fixed, you can see that no data is shown before the error appeared, 
and if you disable the main net toggle we will have the data

**Comment by 0oM4R** [comment]
[Screencast from 04 مار, 2024 EET 04:12:36 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/c9daa8a6-c198-4935-b528-bb5b3dd7a6e5)

compare the to videos and you will got my point 
> ### Description
> A clear description of the bug:
> 
> the stats website calls 6 endpoints, currently one of them is failing, https://gridproxy.grid.tf/stats?status=standby this makes the website shows field to fetch error after the timeout, i don't think this is a good UX, we need to wait for all the results first then show the data or the error
> 
> * **Network**: Dev
> * **Version**: 2.3.0-alpha12
> 
> ### Steps to reproduce
> * go to https://stats.dev.grid.tf/
> * make sure that main net toggle is enabled
> 
> ### Logs/Alerts
> Must include if available:
> 
>  Screencast.from.22.2024.EET.03.08.29.webm

**Comment by 0oM4R** [comment]
> @0oM4R for the mainnet issue, is it reported anywhere so I could follow on?

not sure but it is related to gridproxy so @Omarabdul3ziz may help

**Comment by Omarabdul3ziz** [comment]
i suspected it is related to this one https://github.com/threefoldtech/tfgrid-sdk-go/issues/620 or at least it is part of the problem. so it should be fixed on ninja now not on main stack.

**Comment by A-Harby** [comment]
Verified, Devnet.

The site now shows an alert when one of the selected networks shows an error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5f48f8d7-0dd5-4d76-8d4d-4d05e45c0d0c)
And only display the data when networking is working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/83c4f426-3fef-42d9-866f-a240454f5ab8)


Other issue should be followed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2335).
