### ISSUE TITLE
Re-Add Minting Receipts on dashboard

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2232]
# Situation

I am testing the new super cool dashboard (next.dashboard.grid.tf) and documenting it, when I realize that I can't download minting receipts as it is possible for the current dashboard.grid.tf:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/81142b0c-2675-4f81-9c8d-8f0a4f2d8904)

# Request

Can we add this button to the new dashboard still in farm section?

**Comment by A-Harby** [comment]
Mainnet, 2.3.4.

You can find the `Download miniting receipts` button on the Your Farm page under node statistics tab.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6155e41d-e8dc-43d4-9ea9-9aae7e5609e7)
