### ISSUE TITLE
Set TFT to market price in TF Minting Reports

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2233]
# Request

Can we set the price of TFT in the minting reports page to be at the market price?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/01cc26e3-ae3f-499f-878b-65e20a5cb808)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/0fa61a59-fb25-4bdf-88d4-d2da6d125a15)

could be connected to this value on the dashboard:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/6676fa36-b553-474c-b0c6-58a73ea1b5cc)

**Comment by xmonader** [comment]
The price is fixed at 0.08, that's not related to the current market price

**Comment by Mik-TF** [comment]
I think I should used a bigger screenshot so it was clearer.

See in the next picture, it says the value of TFT from the farming at 8 cents:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/9f682d34-7005-494c-b946-a47a29411b65)

But it's not the current market price.

I am proposing to reflect this as the current market price because saying people can sell their farmed tft at 8 cents is not relevant for now with current market price.
