### ISSUE TITLE
Wrong tft value conversion on dashboard contract

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2234]
# Situation

As reported kindly by Hristo D on telegram (see [here](https://t.me/threefoldtesting/14264)), the conversion on the dashboard contracts section seems off:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/66c62ad6-3495-489a-ad2e-fe747de907ee)

# Fix

It seems it's the tft to usd value that is off.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 7b43120


now the total conversion is multiplied by .017 to give a reasonable exchange rate.
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66ca8311-9f7c-46e1-afc6-6e0ed914d24a)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f9ef3f0a-74a9-466b-ae2c-c883372966a1)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4161190

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.3.0-alpha12
