### ISSUE TITLE
Add farm id column in contracts page

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2235]
# Request

A user of the grid [suggests](https://t.me/threefoldfarmers/69776) we should add a column mentioning the farm ID on the contracts page.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/d04c5553-6d0a-48dd-98b3-7f9a575bc8e1)

So: Farm ID, Node ID, Node Status, etc.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 
a farm id column is now added next to node id


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/88af1f22-5af8-43bd-8f16-327501f06387)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4150371

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d2d2622

![Screenshot from 2024-04-01 00-01-49](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e4857013-34d8-47cd-a580-1d42b81eb462)
