### ISSUE TITLE
(Mainnet Verification) [Bug 🐞]: Can't change pages in dedicated nodes - https://next.dashboard.grid.tf/#/deploy/dedicated-nodes/

### ISSUE THREAD

**Issue by sony87** [threefoldtech/tfgrid-sdk-ts#2237]
### What happened?

https:// next.dashboard.grid.tf/#/deploy/dedicated-nodes/

can't move to next page, does not load, can't move to last page, nothing happens clicking the arrouw > >|

### What did you expect?

to be able to change pages

### What browsers are you seeing the problem on?

Chrome

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

The dedicated node table is now working fine with pagination and items per page.

[screen-capture (21).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/21569dd9-533d-466e-9d78-1d1b1a813ac6)

[TC2219 - List Dedicated Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430127#case_4150428)
