### ISSUE TITLE
(Mainnet Verification) What is a hidden node? Error message isn't clear

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2241]
### Description

A clear description of the bug is:

I was trying to deploy a Caprover 1 master with 1 workers, and I got this error. I didn't choose the node; it was selected randomly. I just pressed the deploy button.

What is the hidden node, what is the failed cause, and how do we solve it?

Must include any relevant identifiers, like:

**Network**: Mainnet Ninja

**Version**: 2.3.0-alpha9

**Twin ID**: 7885

**Node ID**: 5453

### Steps to reproduce

1. Navigate the [Dashboard](https://dashboard.bknd1.ninja.tf/#/deploy/orchestrators/caprover/).
2. Connect your wallet.
3. Navigate to the orchestrators, then caprover.
4. Type domain, navigate to the work tab and add 1 work 
5. Deploy.

### Logs/Alerts

Must include, if available:

- Logs/Alerts.
```
index-64e5d3b9.js:67 Failed to migrate all keys In Case of using a custom network, Must provide urls in GridClientOptions
/#/deploy/your-contracts/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)
3index-64e5d3b9.js:67 Failed to migrate all keys In Case of using a custom network, Must provide urls in GridClientOptions
/#/deploy/orchestrators/caprover/:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq)
2index-64e5d3b9.js:67 Failed to migrate all keys In Case of using a custom network, Must provide urls in GridClientOptions
ch-flag.jpg:1 
        
        
       GET https://www.worldatlas.com/r/w425/img/flag/ch-flag.jpg 404 (Not Found)
3index-64e5d3b9.js:67 Failed to migrate all keys In Case of using a custom network, Must provide urls in GridClientOptions
index-64e5d3b9.js:67 Start creating the machine deployment with name crejlmb
index-64e5d3b9.js:67 Adding node 5453 to network nwcs70v
index-64e5d3b9.js:67 Node 5453 reserved ports: [7377,300,80,6327,6480,4650,6095,4763,9944,2888,2148,9945,443,8082,9943,3763]
index-64e5d3b9.js:67 Generating peers for network nwcs70v
index-64e5d3b9.js:67 Creating a vm on node: 5453, network: nwcs70v with private ip: 10.20.2.2
index-64e5d3b9.js:67 Adding node 3024 to network nwcs70v
index-64e5d3b9.js:67 Node 3024 reserved ports: [9945,300,80,443,8082,7907,9943,9944,15483]
index-64e5d3b9.js:67 Generating peers for network nwcs70v
index-64e5d3b9.js:102 Couldn't get public config for node 5453 due to RMBError: Failed to send request to twinId 8543 with command: zos.network.public_config_get, payload: 
	 255 no public configuration
index-64e5d3b9.js:67 Node 5453 public config: undefined
index-64e5d3b9.js:67 Node 5453 network interfaces: {"ygg":["300:68f2:82f4:ae2b::1"],"zos":["192.168.10.212"]}
[Violation] 'setInterval' handler took 105ms
index-64e5d3b9.js:67 Failed to migrate all keys In Case of using a custom network, Must provide urls in GridClientOptions
```
- Screenshots or screen records.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/eb1c5175-90a4-43d6-8770-ddc874611151)

**Comment by 0oM4R** [comment]
### Issue update:

## Work completed: 
the issue should be fixed, but we can't test as something went wrong with node selection in next dashboard, 
all nodes couldn't respond to verify storage pool



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/5dfec98c-0de8-481f-b75e-462054c83ac6)

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3bc6aa8f-f5a1-447e-8340-cca0fa58bc8c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e60249f4-4fea-4f46-b086-d5b0d38e4dfe)

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet
- 2.3.0
