### ISSUE TITLE
`ERROR` in health of vm table is confusing

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2245]
### Description

- I deployed vms and got them into grace period and Health state in table looked liked this :

![Screenshot from 2024-02-26 00-56-26](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/1198fcca-cb3d-4b02-a15d-ab9013330c76)

- It should be paused and add any tooltip to inform user what's happening.

Must include any relevant identifiers like:

- **Network**: DEV (staging)

- **Twin ID**: 5110

- **Node ID**: 174

- **Farm ID**:  1

- **Contract ID**: 9003

### Steps to reproduce

- Deploy any vm and make its contract in grace period.

**Comment by A-Harby** [comment]
Verified, Devnet 447ee07.

When the contract is in a grace period state, its status is now changed to paused.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e1f6b545-6992-4d63-8418-f9af6a1f487c)

[TC2632 - Node status on deployment list](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4226600)

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.3.0-rc1


![Screenshot from 2024-03-05 12-39-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/2f6601da-ac10-4467-b2aa-80373db11bb6)
