### ISSUE TITLE
Node Ids not sorted in dedicated machines

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2246]
### Description

- as we added online nodes and standby nodes to get reserved, they should be all sorted by nodeIds.
Must include any relevant identifiers like:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/02399948-ef8d-43bf-a6b5-73c57565afbe)

- **Network**: Main

- **Node ID**: 20

**Comment by khaledyoussef24** [comment]
the page will be removed.
