### ISSUE TITLE
Failed deployment on GPU node: GPU is disabled on node.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#2247]
- Node ID: 1885
- Network: https://next.dashboard.grid.tf/  
 
- Issue was initially reported on [Grid tester's chat](https://t.me/threefoldtesting/14304 ).

- Replicated the issue at my end on next dashboard: 

- Error: Failed to deploy zmachine with name vmhhm8y on node 1885 due to: failed to prepare requested gpu device(s): GPU is disabled on this node.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/0ef4a7ec-13fe-4fd5-9018-81699602b1a8)

Dashboard indicates this is a GPU node, but it seems like we're unable to see the details (assuming as the deployment message says - GPU is disabled)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/095e3d9d-614e-42bc-be36-f7721b3e1275)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/6d25f9c8-c480-470b-b7e4-8a50f7f6006c)

**Comment by AhmedHanafy725** [comment]
seems this machine had a GPU card removed, but the gridproxy didn't catch this change and there is an issue with that https://github.com/threefoldtech/tfgrid-sdk-go/issues/636

**Comment by AhmedHanafy725** [comment]
check https://github.com/threefoldtech/zos/issues/2222#issuecomment-2003734047
