### ISSUE TITLE
the chat bot icon placement in the dashboard

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2249]
### Description

when un collapsing options from the side bar the chatbot icon becomes annoying.(it covers some of the items in the sidebar)
is this the best placement for it ?

devnet
version : 75e5a1b
<img width="1440" alt="Screenshot 2024-02-26 at 12 18 08 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8cbb42e2-8a4c-4b26-8454-e3e1ad2528fe">
<img width="91" alt="Screenshot 2024-02-26 at 12 18 13 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/26ddbe55-e812-4d75-b080-1f6f5d9a8fc8">

**Comment by AhmedHanafy725** [comment]
blocked on #2228

**Comment by AhmedHanafy725** [comment]
duplicated of #2139
