### ISSUE TITLE
Support mycelium beside yggdrasil

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2251]
### How To Enable 
yggdrasil -> Set the `planetary` to true on zmachine workload as before.
mycelium -> Set the mycelium config on the zmachine workload.

### Result

yggdrasil ip -> `ygg_ip` for the old vms, and `planetary_ip` for the new vms.
mycelium ip -> `mycelium_ip`

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 433ad62

created a vm uses mycelium and planetary ip and could connect to it using both ips

<img width="832" alt="Screenshot 2024-03-03 at 11 20 50 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/df8f389c-a1fa-4fe7-aded-2495fa094de1">
<img width="331" alt="Screenshot 2024-03-03 at 11 23 15 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8c6d0071-b02f-4b19-a96e-541e5431b62e">
<img width="1339" alt="Screenshot 2024-03-03 at 11 23 28 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/659a12d4-c8b0-4fca-85ac-d9576b950899">
<img width="913" alt="Screenshot 2024-03-03 at 10 50 48 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/69f09281-1b52-4a2c-ad41-d28f644a775d">
https://app.testlodge.com/a/26076/projects/40893/suites/235270?expand_section=429970#case_4226597
