### ISSUE TITLE
Remove public config popup typo

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2252]
### Description

The popup for remove public config in Your farms table should show 'This action is irreversible" not 'This action is reversible' as there is no reverse or undo button. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/9b661714-1f42-4792-bd9f-408be92fb54d)

**Comment by khaledyoussef24** [comment]
- remove the warning 
- rephrase the dialogue question to " are you sure ..."

**Comment by A-Harby** [comment]
Verified, Devnet 447ee07.

[TC2217 - Remove Public Config](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150426) 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d69b88a6-fdd7-471d-a21b-2756783670c1)
