### ISSUE TITLE
[Bug 🐞]: CPU Benchmark and IPerf does not load

### ISSUE THREAD

**Issue by sony87** [threefoldtech/tfgrid-sdk-ts#2256]
### What happened?

Opening a node from https://next.dashboard.grid.tf/#/deploy/node-finder/?node-status=up 
After page load and show node info on top right corner appear 2 errors that it cannot show the CPU Benchmark and IPerf .

![321](https://github.com/threefoldtech/test_feedback/assets/25533429/94b424c3-8e69-4236-a587-9acc3ed996e0)

### What did you expect?

probably to see the results of those bechmarks.

### What browsers are you seeing the problem on?

Chrome

**Comment by khaledyoussef24** [comment]
verified on devnet
version : bee662d



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3fcd4c67-b994-43ea-8eb5-79412fe81b5f)

cpu benchmanr and iperf results are working fine

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460
