### ISSUE TITLE
Resource units: expect empty circle when not available (`N/A`)

### ISSUE THREAD

**Issue by renauter** [threefoldtech/tfgrid-sdk-ts#2258]
### Description

When resource units are not available on a node the interface should show empty circle.

### Steps to reproduce

Go to https://next.dashboard.grid.tf/

If I go to "Farms"  "Your farms" and I select my node without HDD I see the following, which is what I expect:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/73958772/928bda46-e174-48cb-a513-3e921cf8b416)

Now if I go to "Deploy" "Node finder" and I select same node (Node ID: 4992), I see HDD circle is `N/A` but fully colored which is not expected:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/73958772/b011268d-2183-417d-8583-8381fea14a78)

Maybe this wrong behavior is also present on other resource units CPU RAM SSD...

Also I don t get why RAM circles are different in color proportion and also why SSD color is to the left in one case and to the top in the other case.

The general idea is that it should be same code for both cases to be sure to respect some interface coherency.

**Comment by A-Harby** [comment]
@0oM4R Can we also make them in the same order?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c335b0d6-08c3-4c16-941d-25830e4a25fe)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/21556e8f-84a0-4b49-8b82-7eea288b260b)

**Comment by 0oM4R** [comment]
> [@0oM4R](https://github.com/0oM4R) Can we also make them in the same order?
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/309556685-c335b0d6-08c3-4c16-941d-25830e4a25fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODE3MDMsIm5iZiI6MTcwOTQ4MTQwMywicGF0aCI6Ii8xMDk0NzM4NzMvMzA5NTU2Njg1LWMzMzViMGQ2LTA4YzMtNGMxNi05NDFkLTI1ODMwZTRhMjVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNTU2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGNkOTY1NTNkZjQ4MTBiMWE1NWM5MThhMzQ0Mjk4MzBjMGJjM2ZhMWEyY2RmNjI4ZjFlNmY1OTIzMDgwYzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s9hfXpsb1QKD175vCMnVp3mhbcnEX-uT5CCJObfRhrM)
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/309556781-21556e8f-84a0-4b49-8b82-7eea288b260b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODE3MDMsIm5iZiI6MTcwOTQ4MTQwMywicGF0aCI6Ii8xMDk0NzM4NzMvMzA5NTU2NzgxLTIxNTU2ZThmLTg0YTAtNGI0OS04YjgyLTdlZWEyODhiMjYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNTU2NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDM1Nzg5YWI1MzU1NWZiMmQ0YjA2ODQ0MzFjYTg3NDgxNTMzMzA5MTIzMzQwYWU2YWM4MzhjYWJiMmQ5ZDQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NlmsR4fl33BCm2rNPly_CP6jFwwpH1H2TGNtpw8nZZQ)

@A-Harby please open another issue for this point

**Comment by A-Harby** [comment]
Verified, Devnet e1fa2df.

New [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2315) for the resource unit order, and for the `N/A` and precenatge, there is now consistency on both https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2258#issuecomment-1975181409.
