### ISSUE TITLE
copyrights in the footer is not visible  

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2259]
### Description

the copy rights in the footer when opening the deployments or the home page only appears in the node finder and contracts.
![Screenshot 2024-02-26 at 3 18 46 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/44dcddff-b7d3-4092-bbe4-14d75efd47dd)
![Screenshot 2024-02-26 at 3 18 52 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0d6800dc-a5a1-4b72-a2a4-78a7ec1055b9)
![Screenshot 2024-02-26 at 3 19 04 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2b29960c-db41-4856-98c7-74a7268e54fb)

env used : devnet 
version : 48a660d

**Comment by 0oM4R** [comment]
#2262

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 85a6fa4
the dashboard logs now is not blocking any part of the page and the footer is more clear now and copyrights


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fc36d798-f1c6-49f1-86b1-1345cc89a233)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b55caa9b-fc72-43ce-a4a8-7565b10d517a)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4246720
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4282878
