### ISSUE TITLE
Add a margin above the footer 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2261]
### Description

A clear description of the bug:

There should be a margin between the footer and table, or on any other page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d7ed00aa-d954-49f9-b161-bb42eebb9814)

Must include any relevant identifiers like:

- **Network**: dev

- **Version**: 48a660d

**Comment by samaradel** [comment]
### Work Completed
Add some ```margin-top``` to the footer

**Comment by A-Harby** [comment]
Verified, Devnet bd6c7c5.

I checked all the pages with a table or a border, and a space was added between them and the footer.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6fd4f2e9-96ef-48e8-a0ae-f1d747a35a92)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/19a9a00c-bcc7-43e0-ae55-018043329dc3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/76a9984d-2024-49cb-af02-826003fc59af)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1c3929b-fb48-435a-af0b-92f40d6959c9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9446df0f-5b7a-40d9-8954-cda24acd59b3)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
