### ISSUE TITLE
Change the debug logs tab UI

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2262]
### Description

A clear description of the bug is:

Change the debug logs tab appearance.
They expected that it would be on the left side, without all the colors and boxes.

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
checked with Thabet ll keep it as is for now and just put the copyright at the top of the logs

**Comment by ehab-hassan** [comment]
Work Completed
I separated the logs from the footer by adding a frame border and made a small border between the footer and the copyright 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/99868a97-e34f-4fd8-b75b-0e0e13147de1)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 85a6fa4
the dashboard logs now is not blocking any part of the page and the footer is more clear now and copyrights


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fc36d798-f1c6-49f1-86b1-1345cc89a233)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b55caa9b-fc72-43ce-a4a8-7565b10d517a)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4246720
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4282878
