### ISSUE TITLE
404 page doesn't direct me back to the homepage

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2266]
### Description

Qanet, 2.3.0-alpha12 and Devnet.

A clear description of the bug is:

The 404 page doesn't direct me back to the homepage.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4a348a15-4ae3-4ce4-a253-8d86e5cdbd76)

**Comment by A-Harby** [comment]
Verified, Devnet 5e5313e.

The url is now directing to the home page.

[screen-capture (11).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3279ba53-bde0-4072-95f3-cf4da99a1e38)

[TC2633 - 404 page](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4226601)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 0c7d01d
