### ISSUE TITLE
Add new environment variable to identify the network in case custom network is used

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2267]
The target is to enable/disable the features that depend on the network environment (dev, qa, ...) for example:

- get TFT button
- minting receipts

**Comment by maayarosama** [comment]
As per discussion with @AhmedHanafy725,  the user is now restricted to using only the following four networks ```main, dev, qa and test```. 

However the user can set any of the following urls:
-   GRAPHQL_URL
-  GRIDPROXY_URL
-  SUBSTRATE_URL
-  ACTIVATION_SERVICE_URL
-  RELAY_DOMAIN
-  BRIDGE_TFT_ADDRESS
-  STATS_URL
-  STELLAR_NETWORK

If not set the network's default urls will be used.

**Comment by A-Harby** [comment]
Can you also update the docs
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b8b3348c-3090-4faa-bd74-7d4d973be449)

**Comment by hossnys** [comment]
stats url is hard coded here https://github.com/threefoldtech/tfgrid-sdk-ts/blob/v2.3.0-rc1/packages/playground/scripts/build-env.sh#L9 as it overrides stats passed env variable

**Comment by hossnys** [comment]
in network inspect of https://dashboard.02.dev.grid.tf it shows mixed connection to two different gridproxy instances , and two relays , which maybe happened because urls passed to the grid client but it's not to gridproxy or graphql clients  , so please check that also .

**Comment by A-Harby** [comment]
Verified, 
Docs.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/31b4be83-f33e-42e4-823c-a0ef6171efcb)
Testnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/42265215-0ffd-41aa-b483-663d74d1038e)
02dev
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4900c4ae-789c-4813-a46a-0c73728b741a)
