### ISSUE TITLE
In contract list, Solution Type doesn't show the Network type

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#2270]
Created multiple Micro VMs 
All are shown in contracts list with solution type "Micro Virtual Machine"
However it should show one network for each VM

![Screenshot from 2024-02-27 14-15-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9ffbdeaf-52a7-49a9-a790-d22c3d7e93d6)
![Screenshot from 2024-02-27 14-15-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a670bb58-beb5-4f9a-8a0a-dc0cba836cf0)
![Screenshot from 2024-02-27 14-15-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/476395dd-ef1e-4121-835d-5a690d53e2a2)

**Comment by zaelgohary** [comment]
The contract type column has already been added to the table as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/8687384c-a7dc-4747-ae6c-dada7b889387)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : d8050a1



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/43494357-79c7-4c28-a44e-ce98993203d8)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9a63f043-78ad-4223-adcd-b9f399f7787e)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4157417

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
