### ISSUE TITLE
Node public config validation and inputs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2271]
### Description

Devnet, 0eda4cc.

A clear description of the bug:

- The value when typed in the input is saved even when the dialog is closed and reopened.
- When a new value is typed then closed and reopened I can't save it despite it is a valid new value.

[screen-capture (7).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/690f7e53-62e0-45a1-a2f4-07b82caa5685)

-  The validation done on the dashboard is still different than the validation done on the chain.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5e91eaf0-3573-40e1-b81d-4f6add66cd8c)

**Comment by samaradel** [comment]
works fine on devnet

[Screencast from 04-03-24 16:00:40.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/a5100829-2720-4fc1-a8cb-840e242d1d14)

**Comment by A-Harby** [comment]
My bad, I didn't add the steps to reproduce, but it happens when you change the IP, then close and reopen the dialogue again.

[screen-capture (14).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/206138ac-d97e-4d36-b235-7f502ce5bbb2)

Steps to reproduce:
1. Navigate to the dashboard.
2. Connect your wallet (your account must have a node).
3. Add your public configuration, for example (IP: 198.165.15.25/16, Gateway: 198.165.15.24).
4. Click on save.
5. After saving it, open the Add a public config dialogue again.
6. Change Gateway to 198.165.15.26 (the save button will be enabled, but don't press it).
7. Close the dialogue and reopen it again; you won't be able to save the changes even though the node gateway is 198.165.15.24 and the input is 198.165.15.26.

**Comment by samaradel** [comment]
### Work Completed:
Reset ```ipv4```, ```ipv6```, ```gw4```, ```gw6```, ```domain``` values on dialog close

**Comment by A-Harby** [comment]
Verified, Devnet 5c12959.

The public config inputs are reset whenever the dialog is closed.

[screen-capture (21).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/52a618d8-8a64-4078-9a73-7886ab0fc2e1)

[TC2218 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150427)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
