### ISSUE TITLE
Can't copy my ssh key if i have 0 TFTs

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2276]
### Description
- I wanted to copy my ssh key, but it was disabled as i have zero balance.
- i see there's no relation between copying and balance

[Screencast from 02-28-2024 10:42:23 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/7a3f6e9a-ed66-449a-a045-96641019eaab)

Must include any relevant identifiers like:

- **Network**: Dev `https://staging.dashboard.dev.grid.tf/#/deploy/sshkey/`

- **Twin ID**: 5110

**Comment by khaledyoussef24** [comment]
network : devnet
version : f530d72

user can now copy his ssh even when he has 0 tfts.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/40e20e13-dc05-4d77-a39f-0dac7c9a6568

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4177816

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- f3e199e
