### ISSUE TITLE
(QA/Testnet Verification) Tooltip in the stellar bridge address is only pointing to the dev address despite changing the network

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2282]
### Description

Qanet, 2.3.0-alpha12.

A clear description of the bug is:

The tooltip in the bridge stellar address is only pointing to the dev address and doesn't change when the network changes. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a955739d-b498-4e0a-95ee-cf4edf15a9ee)

The link in the tooltip is: https://stellar.expert/explorer/testnet/account/GDHJP6TF3UXYXTNEZ2P36J5FH7W4BJJQ4AYYAXC66I2Q2AH5B6O6BCFG

**Comment by A-Harby** [comment]
Verified, Mainnet 2.3.0.

The link is changed to the correct network address.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f99bfb54-620b-413d-9a29-ef1285c0921c)

**Comment by ramezsaeed** [comment]
Verified:

- Testnet

![Screenshot from 2024-03-13 18-38-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/abf531db-7dc7-43b6-97fa-f3c1847c4ab1)

- Mainnet
![Screenshot from 2024-03-13 18-37-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/1f8e6bf4-36ea-44c5-b6df-bdbb6cecf4cc)
