### ISSUE TITLE
Discounts rate and prices of dedicated node should be added in `node finder`.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2285]
-  As dedicated machines page will be deleted, so we should include prices and discounts rates in node finder.
- also this issue should be considered https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1978

**Comment by zaelgohary** [comment]
WIP:

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057#issuecomment-2021510752

**Comment by zaelgohary** [comment]
WIP:

Added returned price from grid proxy in node card.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c873ae0d-6c8f-4685-939e-ecb2c2cc5d3f)

**Comment by zaelgohary** [comment]
Work completed:

Prices from grid proxy include discounts.
