### ISSUE TITLE
Clear the inputs in farm IPs after adding them

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2287]
### Description

A clear description of the bug is:

Clearing the input after adding IPs to the farm IPs.

### Steps to reproduce

[screen-capture (8).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/598b5586-a0a7-4382-a666-6ebd76210504)

**Comment by zaelgohary** [comment]
Work completed:

created a reset function for form inputs and used it while submitting the form.

**Comment by A-Harby** [comment]
Verified, Devnet 5c12959.

The IP inputs are cleared after successfully adding the IPs, either single or range.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7fb5f39f-58b7-4641-81f3-395efbabd19f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6135333b-5fe4-4a19-9c41-d1ed09d03d2c)

[TC2207 - Add IP to Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150416)
[TC2208 - Add Multiple IPs to a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150417)
