### ISSUE TITLE
Adjust Dashboard with manual links

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2288]
## Situation

We are updating the links of the info_grid repo (www.manual.grid.tf). See www3.manual.grid.tf for new URLs.

We would need to sync this change with  update to the Dashboard links so we do not have issues with links from the dashboard to the manual.

## Related PR

More information here: https://github.com/threefoldtech/info_grid/pull/441

**Comment by Mik-TF** [comment]
The new dashboard is now live, and all links are still with old manual.
The correct links are available on this PR: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2379

If we wait until 3.14, we'll have all broken links on dashboard. Let me know if I can help any more here.

**Comment by xmonader** [comment]
This will get sorted out tmw :)

**Comment by khaledyoussef24** [comment]
the new dashboard is adjusted with the new manual links.
links are now working fine and redirecting correctly.
<img width="1680" alt="Screenshot 2024-03-30 at 5 42 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/43ae3b3f-62ba-47fd-be81-ad018fd517d5">
also checked most of the links and are working fine.
