### ISSUE TITLE
"mycelium" flag is missing from test modules in the gridclient

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2289]
### Description

automated tests of the grid client fails due to missing mycelium flag
![Screenshot 2024-02-29 at 9 09 43 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dd034cb0-7d04-45f0-8e79-81d6f7d51f07)
tests which fails : 
- vm.test.ts
- kubernetes.test.ts

**Comment by MohamedElmdary** [comment]
WIP
 - mycelium flag is now added
 - Comment metadata assertion as it fails
 
 > Still facing an issue `timeout`
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/3f4b50d7-041e-457f-9fee-77788953ead5)

**Comment by AhmedHanafy725** [comment]
### Work in Progress
> Timed out while waiting for handshake
- this issue of the connection is solved. It was related to yggdrasil peers and starting the service before updating the config file.
- Fix the project name in kubernetes test.
- Fix qsfs tests.

**Comment by AhmedHanafy725** [comment]
### Work Complete

all tests are fixed and the workflow is passing now 
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/8256995234/job/22586740990

**Comment by A-Harby** [comment]
Verified, Devnet https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/8256995234/job/22586740990.
