### ISSUE TITLE
Pricing calculator negative value validation

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2293]
### Description

Add a validation for negative numbers in the memory, SSD, and HDD inputs. 

Must include any relevant identifiers, like:

- **Network**: Qanet

- **Version**: 2.3.0-alpha12

### Logs/Alerts

- Screenshots or screen records.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0bba4ffd-b8ef-4588-a172-29cc0b6e5769)

**Comment by khaledyoussef24** [comment]
issue still exists Validation for negative values is still needed.
<img width="859" alt="Screenshot 2024-03-30 at 6 02 19 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/77fe474b-71db-479a-b4f8-ac3533d02579">
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4213523

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.

[TC2604 - Pricing calculator input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4213523)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e6e5f88e-4d72-400a-a6d1-38984f25ed46)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
