### ISSUE TITLE
 Iperf test tabs are not shown correctly on some of the nodes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2294]
### Description

IPerf test result tabs are not consistent on all the nodes.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/11a3191e-2663-470e-8835-d3dda0212081)

Must include any relevant identifiers, like:

- **Network**: Qanet

- **Version**: 2.3.0-alpha12

- **Node ID**: eg. 5

- **Farm ID**: 3

### Steps to reproduce

1. Navigate to the Dashboard.
2. Navigate to the Node Finder page under the deploy section.
3. Click on any node.

**Comment by 0oM4R** [comment]
duplicated of #2160
