### ISSUE TITLE
cannot acces VM using yggdrasil or mycelium

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2295]
### Description
env used : devnet
version : cce70a1

made a deployment using the dashboard for a full vm with network options for planetary and mycelium
![Screenshot 2024-02-29 at 5 17 56 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7eff3374-f823-4d1b-8895-ac11020bea9f)
after machine deployed could not reach it through Yggdrasil and also after running the binary command for mycelium could not reach it through mycelium ip 
<img width="581" alt="Screenshot 2024-02-29 at 5 20 10 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0be008c4-aba7-47bf-8dee-881ea9aa4452">
![telegram-cloud-photo-size-4-5983432018412814819-x](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94d8b7e3-2bda-4916-81ca-739950b6ed4b)![telegram-cloud-photo-size-4-5983432018412814820-x](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ac015b55-e9ca-4dd8-b73d-f2c231d39a90)

**Comment by AhmedHanafy725** [comment]
are you sure you have the latest mycelium binary? also for yggdrasil, does the service is running?

**Comment by khaledyoussef24** [comment]
verified connecting using yggdrasil
<img width="913" alt="Screenshot 2024-03-03 at 10 50 48 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6f548d70-5a36-4402-8b6f-2ea854d2fb81">
will try to verify mycelium using the new binary.

**Comment by khaledyoussef24** [comment]
verified using the new binary
even the new binary worked fine on macOS

<img width="832" alt="Screenshot 2024-03-03 at 11 20 50 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ccbcfe80-ca05-4a15-a449-1d580c808bf2">

**Comment by 0oM4R** [comment]
@khaledyoussef24 how did you resolve the ygg connection issue ?

**Comment by khaledyoussef24** [comment]
> @khaledyoussef24 how did you resolve the ygg connection issue ? 

I created another machine and it worked fine.

Tried to create multiple of machines to see if i will face the same issue again, but couldn't reproduce it.

**Comment by 0oM4R** [comment]
> > @khaledyoussef24 how did you resolve the ygg connection issue ?
> 
> I created another machine and it worked fine.
> 
> Tried to create multiple of machines to see if i will face the same issue again, but couldn't reproduce it.

yes I couldn't access my vms, 
i tried to upgrade yggdrasil to 0.5.4 and works fine with me now. Thank you @khaledyoussef24  for guiding me through that!
