### ISSUE TITLE
failed to load iperf, failed to load cpu benchmarks

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2296]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1cbc935d-e2c4-455b-a9c8-caf3f3214b1e)

It's not reflecting in a good way for the testers, should be disabled, and have a release without it

**Comment by AhmedHanafy725** [comment]
The notification for loading iperf tests and the CPU benchmark had been removed and the behavior had been changed in #1388 to 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/999b5dd3-63e6-4b86-8a7e-410c74d31d3c)
