### ISSUE TITLE
full virtual machine requires public sshkey

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2297]
on a new account 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/599dd139-a8d4-4872-b8a5-df8c3ab3978f)

it should tell me what to do or where to go to have that sorted

**Comment by ramezsaeed** [comment]
Already exists

![Screenshot from 2024-03-03 11-19-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/15a1fe3b-82a4-41bd-a460-af4f09557c0e)
