### ISSUE TITLE
[TestNet] Failed message remains after reloading gpu details successfully

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2298]
Using next.dashboard.grid.tf (mainnet/2.3.0-alpha9), I still see the failed message after reloading the GPU details successfully:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/c3b702d8-b044-4ec9-9a19-086455ffc8c4)

If the reload is a success, the original failed message should be removed.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 5c12959


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/34f87fd2-7a90-47e9-a468-648681ab7730
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e1ff6251-7bee-4ae6-b0ea-5700759dfff9)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f0251e7f-b0ac-44d5-b6a5-4c8835db28b9)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a6a95542-aa45-4728-8178-4f5e5ceb4db7)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4251108
