### ISSUE TITLE
Store the deployment's info in the contract instead of kvstore

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#23]
- This should be backward compatible with the old deployment
- Migrate the data from the kvstore to the contract while listing the deployment

**Comment by MohamedElmdary** [comment]
WIP
- Added ui related to k8s and virtual machine listing
- Disabled actions for deployed deployments from outside grid_client

**Comment by MohamedElmdary** [comment]
This feature should be added by now however it still require some tests
- tested
  - fvm
  - vm
  - k8s

**Comment by MohamedElmdary** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/ebab95c3-4bb7-4673-a1a3-63efb7d386da)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/1da7333a-06e7-42da-aefc-81529c26446d)

Bug: Workers and networks not deleted

**Comment by MohamedElmdary** [comment]
WIP
- Couldn't reproduce the above issue again
- continue testing on k8s
- still need to test more on applications

**Comment by MohamedElmdary** [comment]
WIP
- Almost done with tests
- Missing only test managing k8s's workers (from different clients)

**Comment by MohamedElmdary** [comment]
WIP
investing in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2124#issuecomment-1941829846

**Comment by AhmedHanafy725** [comment]
### Investigation and Solution

currently, if the user deploys a vm and tries to get the vm's details with the client with a script, nothing will be returned as the listing now depending on the getting the contract from graphql which may be slightly delayed till the event is reflected on the graphql processor db.

as a solution maybe we can inject the newly deployed contracts returned by the chain in the contracts list once it's deployed, so it can list the new vms.

**Comment by AhmedHanafy725** [comment]
### Work Completed
> as a solution maybe we can inject the newly deployed contracts returned by the chain in the contracts list once it's deployed, so it can list the new vms.

this solution is added but not tested yet.

**Comment by AhmedHanafy725** [comment]
### Work Complete
> this solution is added but not tested yet.

The solution worked fine and the test went well
