### ISSUE TITLE
(Mainnet Verification) [Bug 🐞]: Public IP node filtering not working properly

### ISSUE THREAD

**Issue by alastairong** [threefoldtech/tfgrid-sdk-ts#2300]
### What happened?

I tried to deploy a full VM and selected "public IPv4" under the configuration options. I then clicked "load nodes" and selected one.

When I deployed I got the error that no public IPs were available. 

### What did you expect?

I expected that nodes without available public IPs would not show up when on the list after clicking "load nodes"

### Dashboard info

using next dashboard

**Comment by A-Harby** [comment]
Mainnet 2.3.0.

The issue still occurs.

[screen-capture (22).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e3e7f16-c40a-47fe-a53d-1dd9a1626796)

`InvalidResourcesError: Farm 138 doesn't have enough public IPs: requested IPs=1, available IPs=0.`

**Comment by Omarabdul3ziz** [comment]
check updates https://github.com/threefoldtech/tfgrid-sdk-go/issues/808#issuecomment-2002369077

**Comment by A-Harby** [comment]
Verified, Mainnet 2.5.2.

The old nodes where I tried before were removed from the load nodes, so the farms are reporting the public IPs correctly now.
![image](https://github.com/user-attachments/assets/ead737b8-e2d5-498b-b836-5783bec02fd5)

And I was able to successfully deploy and ssh to multiple nodes with public IPs.

[screen-capture (38).webm](https://github.com/user-attachments/assets/30376af5-b75f-4564-9213-e0dddb8bd36e)

![image](https://github.com/user-attachments/assets/69f189b7-6c35-4d15-b3dc-badb302819a5)
