### ISSUE TITLE
[Feature Request]: More flexible VM naming 

### ISSUE THREAD

**Issue by alastairong** [threefoldtech/tfgrid-sdk-ts#2303]
### What happened?

VM names are max length 15 chars and can only contain lowercase alphanumeric characters. This is a really annoying set of restrictions as it makes names hard for humans to parse. None of kebob-case, snake_case, or camelCase are accepted.

### What did you expect?

To be able to do either kebob-case or snake_case naming and have at least 50 character limits on length.

### Dashboard info

next.dashboard.tf.grid

**Comment by scottyeager** [comment]
Definitely agree this situation can be improved. We need to first check what the upstream restrictions from Zos/TF Chain are, versus what's maybe being additionally imposed by the code here.

Something related that's been on my mind for a while is that it would be nice to have some way to rename deployments after they are created. Local only to the current machine/browser would be fine.

Combining the ideas, we could add a "display name" that doesn't have the same restrictions and is tied to the unique "backend name" only on the user's machine.

**Comment by maayarosama** [comment]
1. Work Completed:
Added a custom validation decorator in grid_client to check if name is alphanumeric and if in contains ```_```

3. Investigation and Solution:
The constraints message isn't shown as follows
![2024-06-30_19-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/6baae08a-4e57-4bb3-8ccc-52e57b7492ce)

**Comment by maayarosama** [comment]
Work Completed:
Increased the accepted length of name to 50

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0d964e5


till 50 characters working fine
![Image](https://github.com/user-attachments/assets/2dcc8a0c-254c-4902-8dcd-52c0be001de7)


![Image](https://github.com/user-attachments/assets/d4db3b12-fd0c-46f7-b4a7-5dd2b656fe69)
