### ISSUE TITLE
simulator input for the token price (at start of end of 5 year period) does not accept . in decimal notation.

### ISSUE THREAD

**Issue by amandacaster** [threefoldtech/tfgrid-sdk-ts#231]
### Search first - https://github.com/threefoldtech/grid_weblets/issues/869

Search for similar issues first, if not complete the following template

### Description

The decimals are not working in the simulator.

A clear description of the bug

### Steps to reproduce

List of steps to reproduce the problem if it's a bug

### Logs/Alerts

Logs/Alerts if available

**Comment by A-Harby** [comment]
Verified on Devnet, 2.0.0-rc5.
`Price of TFT at point of registration on blockchain (USD)` input is now accepting decimals.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/32dcd151-3d8e-46f1-ae12-e8c8199c211d)
