### ISSUE TITLE
simulator input for the token price does not accept . in decimal notation.

### ISSUE THREAD

**Issue by amandacaster** [threefoldtech/tfgrid-sdk-ts#232]
The Users are trying to use the simulator and the TF Token Price tab is not accepting decimals. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/88147124/7f23f6ba-fd1e-40cf-9df9-ceaa03764e43)

**Comment by A-Harby** [comment]
Verified on Devnet, 2.0.0-rc5.
`Maximum Token Price` input is now accepting decimals.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9c119370-638c-4bf4-82ef-e2efe6cb1271)
