### ISSUE TITLE
discourse deployment giving me bad gateway

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2324]
### Description

deployed a discourse deployment and waited 15 mins the machine is telling that the service is running but the domain gives bad gateway
env used : testnet and qanet
<img width="183" alt="Screenshot 2024-03-04 at 11 49 15 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a0a5874-5b18-4e8d-9fd9-2eafca03cad3">
![Screenshot 2024-03-04 at 11 49 27 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f86dc41d-db03-4340-8da4-d09ed372ca53)
![Screenshot 2024-03-04 at 11 49 53 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0cd76e21-76d9-4498-a428-b75ce4598266)

**Comment by khaledyoussef24** [comment]
update after 25 min the discourse instance is now running and the domain is reachable
![Screenshot 2024-03-04 at 12 25 31 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d7abed01-bb7d-42f2-8057-64995a53550c)

**Comment by zaelgohary** [comment]
I tried deploying a Discourse instance and it took less than 10 mins for the domain to work.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/94e04aa8-1b77-4dc7-8d7e-a41ccd4d2dc7)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/aa36c2e3-b414-475c-800d-bce2652f8d51)
