### ISSUE TITLE
Hide owncloud from applications

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#2326]
### Description
Hide owncloud from applications

**Comment by A-Harby** [comment]
Verified, Devnet 0c7d01d.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c2550b8-d16f-4214-8385-83d2f9b6a1ce)

[TC2137 - Deploy Owncloud (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150346)
[TC2177 - ownCloud Input/Configuration Validation (SKIP)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150386)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 06b2876
