### ISSUE TITLE
Can't create a new account on devnet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2329]
### Description

A clear description of the bug is:

After pressing create account.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d48edfbc-4673-43a7-8e66-f8b349692035)

Must include any relevant identifiers, like:

- **Network**: [Devnet](https://staging.dashboard.dev.grid.tf/#/)

- **Version**: b3c2cf3

### Steps to reproduce

1. Navigate to the dashboard.
2. Open the profile manager.
3. Click on create account.

### Logs/Alerts

Must include, if available:

- Logs/Alerts.

[dashboard_logs.txt](https://github.com/threefoldtech/tfgrid-sdk-ts/files/14481023/dashboard_logs.txt)

**Comment by A-Harby** [comment]
Verified, Devnet 0c7d01d.
[TC2118 - Create a new twin](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150327)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bf992cb0-9720-4935-950d-942ae1679a8b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 06b2876
