### ISSUE TITLE
Dashboard Logs tab doesn't list the errors

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2330]
### Description

A clear description of the bug is:

The Dashboard Logs tab doesn't list the errors. I've noticed many times that there are a lot of errors shown on the console logs from the dashboard, but the dashboard logs don't show any of them, which makes it kind of useless to have.

[screen-capture (13).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/31847c14-69b5-4aa6-a446-4fa692d03a5c)

Must include any relevant identifiers, like:

- **Network**: Devnet

- **Version**: b3c2cf3

**Comment by ramezsaeed** [comment]
These errors from Iframe not included in our logs.

**Comment by A-Harby** [comment]
But as you can see from the video, the 404 error originated from the dashboard. 
And it was display on the console logs, then shouldn't be listed in the dashboard logs itself?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d4e257bd-d8f0-4f67-ad1f-c8af862dbf54)

**Comment by MohamedElmdary** [comment]
The error shown is the response of requested iframe's data not from our side ... also we can't catch browser error (http ones) or prevent them

**Comment by amiraabouhadid** [comment]
Issue has been resolved after terms and conditions has been refactored
https://www.loom.com/share/8adbcedcc101411eb42558a43f979776?sid=0a8bd8ae-b218-43ad-8e50-b7f2b4084da5

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 85a6fa4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/70322b93-ee83-4842-a580-f6acd3b7d791)
