### ISSUE TITLE
subsquid deployment gives bad gateway

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2332]
### Description

deployed multiple of subsquid solutions, the deployment is successful and the service on the machine is running fine but the domain does not work.

Must include any relevant identifiers like:

env used : testnet

version : 2.3.0-rc1
![Screenshot 2024-03-05 at 10 47 53 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/725fb6ff-f6a1-4290-924e-f23866001f3b)
![Screenshot 2024-03-05 at 10 47 57 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/993eb577-87f0-4868-b938-834c1fe6efd3)
<img width="220" alt="Screenshot 2024-03-05 at 10 48 01 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c348700f-a818-4d86-9952-4b16b14756dd">
![Screenshot 2024-03-05 at 10 48 11 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2c9f890e-b10a-4c2c-aeb3-76268e26ad82)

**Comment by maayarosama** [comment]
@khaledyoussef24 can you please provide which websocket endpoint you used?

**Comment by maayarosama** [comment]
I tried deploying multiple subsquid instances with multiple different endpoints and all of them works fine
![Peek 2024-03-20 13-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/4e445f48-7a25-4456-8002-0f6a6187af26)

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

deployed and worked fine
even a link providing supported websockets can be found easily in the manual
![Screenshot 2024-03-26 at 10 58 42 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8fd04ec6-46a4-4697-a15f-79ee497a8bd2)

![Screenshot 2024-03-26 at 10 52 05 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/44eabf3c-e643-4413-9d36-da10dade78ef)
![Screenshot 2024-03-26 at 10 52 11 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/179c8928-0c1e-4ba5-9af5-4c4a8b6984e9)

updated test case : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150348
