### ISSUE TITLE
The Alignment of Dashes in the Networks Deployment Table Appears Disruptive

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2338]
### Description
When deploying a VM with both public IPv4 and IPv6 addresses, as well as using Mycelium and Yggdrasil, it is better to have the dash in the IP fields centered. will it be better that the dash in the IP fields if it is centered?
![telegram-cloud-photo-size-4-5996770559041585188-y](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6d350a96-be45-4966-8f4d-73fa7a974a31)

**Comment by ehab-hassan** [comment]
Work in Progress
if we do that we need to make all tables align center to keep the consistent 
will go through all tables and see what is best to be centered or keep it left.

**Comment by ehab-hassan** [comment]
to solve this I aligned the table at the center I think is better, and also made all tables centered to keep consistency

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1006b5a3-0d07-4d09-89fb-027e3f2f615e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6ec1a3c9-f46b-4953-af05-b85e31164a64)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d4465681-ffb4-4dfe-a0ad-c4d9c5494fe1)

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
still, investigate the best way to reduce filter high
for the filter, we can make 6 columns a row while no need for a big width .

**Comment by ehab-hassan** [comment]
Work Completed 
and PR merged to the development

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72
now all of the tables are aligned in the middle.
![Screenshot 2024-03-28 at 11 39 25 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bff6d58a-b6c2-4f76-b96e-66d40a4fdad4)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
