### ISSUE TITLE
(Qa Verification) get tft button is not working on qanet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2339]
### Description

get tft button is not working on qanet
tried to get tfts but it is not working giving this message and this error

env used : qanet 
version : 2.3.0-rc1
![Screenshot 2024-03-05 at 1 10 20 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4280a940-59ac-41be-9b55-0830a3c571e1)
 
![Screenshot 2024-03-05 at 1 11 03 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c708390e-1035-4704-8774-cab0b0c15ec7)
![Screenshot 2024-03-05 at 1 16 56 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7e3d35e6-194b-4d8e-bd2f-0cf87c9cb318)

**Comment by maayarosama** [comment]
not reproducible 
![Peek 2024-04-03 03-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/d5309612-8765-4de5-8d73-997357896146)

**Comment by khaledyoussef24** [comment]
the issue still exist on qanet


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/02baec63-9c43-47be-81c1-60763c9e7336
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/54d965e5-a3e2-4bc3-ac16-ac0f9a5cc4ee)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8353420c-a865-48c3-9f50-3340468eafa0)

but on devnet is working fine 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/37824e7d-7f1a-45d5-a68f-0a38577a4b2f)

**Comment by A-Harby** [comment]
I also have the same error on Qanet 2.3.4 and on multiple accounts.
is it released? or should we wait for a QA release?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ec8f93bc-0ffe-443c-aa19-9830da3fe651)

**Comment by maayarosama** [comment]
> I also have the same error on Qanet 2.3.4 and on multiple accounts. is it released? or should we wait for a QA release? ![image](https://private-user-images.githubusercontent.com/109473873/319343797-ec8f93bc-0ffe-443c-aa19-9830da3fe651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjQ0ODUsIm5iZiI6MTcxMjIyNDE4NSwicGF0aCI6Ii8xMDk0NzM4NzMvMzE5MzQzNzk3LWVjOGY5M2JjLTBmZmUtNDQzYy1hYTE5LTk4MzBkYTNmZTY1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwOTQ5NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTI4MDIwMjQ0YzRjYTQxMzlhYWQzZjc0MzFmOWEyYzI3ZDU5NjdhM2I1YTMxZDE5NmY0MjQwZTVkMmRhNWFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yf0GIcmFIGbbvVyyS5W3wZr4DASUFMbL3gcHlaxgVJM)

we should wait for QA release

**Comment by khaledyoussef24** [comment]
the issue still exists
version 2.4.0-rc1
network QAnet


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ddf23765-da3a-4fc1-b769-1220014ff4fc)

**Comment by maayarosama** [comment]
Investigation and Solution:
Issue doesn't happen locally.

suspected issue is in the urls passed to the client, specifically the substrateURL

**Comment by khaledyoussef24** [comment]
verified on qanet
version 2.4.0

<img width="281" alt="Screenshot 2024-05-07 at 10 58 22 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b04d8c18-effd-4211-8891-a5244069c3d8">
<img width="1680" alt="Screenshot 2024-05-07 at 10 58 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bf9d0b9b-289f-4d63-b01e-fbfd07fbc756">
<img width="1680" alt="Screenshot 2024-05-07 at 10 58 31 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c308e2ed-c91d-44fc-a190-464ce9ace6d3">
