### ISSUE TITLE
Responsive design 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2342]
### Description

Can we have a design for small screens, We need to make the current dashboard responsive and it will be great if we have a design to guide us

### Related issues 

- #1261 
- #1987 
- #1985 
- #2410

**Comment by ehab-hassan** [comment]
WIP
Making Figma show the best way of showing the navbar on mobile

**Comment by ehab-hassan** [comment]
WIP
Figma done
https://www.figma.com/proto/KAQ6497YfczErqfh1Bz62l/Dashboard2?node-id=808-1816&t=MlsBUVOeVNGm3Woy-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A1248&show-proto-sidebar=1

**Comment by ehab-hassan** [comment]
WIP
almost done 
what needs to be fixed is
- simulator
- landing home without login

**Comment by ehab-hassan** [comment]
Work Completed

**Comment by khaledyoussef24** [comment]
verified on devnet
Version c2d6060

verified in 
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1261
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2410
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1985
also the simulator page : 
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/49f18a66-8fee-480d-b55a-497c9ef21560" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/c4bb9962-879b-423a-9254-c27835244203" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/a743a4a2-5c9f-466a-8ded-99e241c938c6" />
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4431573)
