### ISSUE TITLE
Bridge TFT Input validation doesn't show an error message as an expected result

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#2343]
**Description**:

- An error message is supposed to appear when moving from **Stellar Target Wallet Address** and leaving it blank, to the **Amount**. but this does not happen.

![Screenshot from 2024-03-05 17-11-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/fb79d74e-ab84-437f-b7af-4ab8aea44fdb)

- environment : testnet
- version : 2.3.0-rc1

**Comment by A-Harby** [comment]
Verified, Devnet bd6c7c5.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2bac8fcf-f919-4db0-a3de-0e3116f4b5e0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c9b77017-f76e-4aec-9ba8-4b7946036682)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7e083eb9-ee21-45e8-9bd4-5bd3e11e753d)

[TC2239 - Bridge TFT Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150448)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
