### ISSUE TITLE
Maintain all of manual links in one json file

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2347]
collect all of the referenced links in a single json file and import/reference the link when needed e.g

```
export links = { "vm_getstarted": "https://manual.grid.tf/deploy/vm.md",
  "threefold_connect":  "https://manual.grid.tf/intro/threefold_connect.md"
 ...
}

```

then you can use it in other components e.g

```
import links from 'manuallinks.js'

links["threefold_connect"]

```

this resulting 

1- simpler maintenance
2- controlled changes in PRs
3- allowing non-developers helping maintaining these links updated

**Comment by Mik-TF** [comment]
See this PR on manual: https://github.com/threefoldtech/info_grid/pull/444

Ideally, the manual links would be those ones. You can see www3.manual.grid.tf for staging version, and use www.manual.grid.tf/... as the template, so once we merge the PR on info_grid and we put online the new dashboard, all links will work.

**Comment by despiegk** [comment]
lets review this with timur, his framework is now the basis, we need to make sure its compatible

**Comment by Mik-TF** [comment]
WIP: https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development_314_docs

**Comment by zaelgohary** [comment]
WIP:

Currently working on adding the URLs to the manual json file.

**Comment by zaelgohary** [comment]
Work completed:

Created a const for all manual links and used it in the Dashboard files.

**Comment by A-Harby** [comment]
The file has been created and manual links have been removed from ts files.
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/manual.ts
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8a293fee-7c88-4f2e-94a2-3c68e962f9dd)
