### ISSUE TITLE
Add the last deployment date on the node details pop up

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2348]
should be added here once https://github.com/threefoldtech/tfgrid-sdk-go/issues/914 is ready

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/813467a8-ecea-4b2c-8e1d-e53e713870d6)

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done 

Add last deployment timestamp to node details card

- Updated the NodeStats interface to include last_deployment_timestamp
- Added a new field 'Last Deployment' to the node details card in the dashboard
- Display the last deployment timestamp in human-readable format if available

#### Screenshots/Video

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/c064c7b0-88b2-49d1-9889-632a5d0821be)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 0d1e63f



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4dcd0bf9-b65d-4d22-9a9d-baf9043e9639)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e9a577d-1c4c-465f-b1b0-34bf186cc1c8)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 0da6be6

![Screenshot from 2024-05-21 11-46-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9ac3b36a-8be1-410c-8799-a4978d060140)
