### ISSUE TITLE
Activate the account on connect if it doesn't have a twin

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2350]
Currently, the dashboard has many buttons on the wallet connector that may confuse the users after entering the mnemonic

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/be932721-cb78-4e8e-99a6-0be9c5c8df23)

### Suggestions
Remove the activation button. if the user provides a mnemonic that doesn't have a twin on the current network, the dashboard can trigger the activation while connecting the wallet.

**Comment by samaradel** [comment]
### WIP:
button removed .. testing invalid mnemonic

**Comment by samaradel** [comment]
###  Work in Progress (WIP):
All scenarios are done, Noticed weird behavior while the activation and working on it

**Comment by samaradel** [comment]
### Work Completed:
- Remove Activation account button
- Trigger the activation while connecting the wallet

**Comment by samaradel** [comment]
### Work Completed:
Fix error that appears when the user doesn't have ```twinid```

**Comment by samaradel** [comment]
### Work Completed:
Fix storing email in metadata

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.

The activate button is removed, and only the create account button is there. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9656f402-9bcb-416b-b0e4-d51755914c33)

And when a new mnemonic is entered, the connect button is forwarding to accept terms first. 

[screen-capture (24).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ce3bda9-76d4-4836-bce9-8238990f1d92)

[TC2433 - Activating a user from polkadot or hexseed or other networks](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4161528)
