### ISSUE TITLE
Remove the unused query parms from the request

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2353]
The query is hard to read as it contains all the query params even if it's not used. Only include the used ones.

for example

https://gridproxy.dev.grid.tf/nodes?total_cru=1&free_mru=2147483648&free_sru=28991029248&free_hru=&free_ips=&ipv4=&ipv6=&certification_type=&farm_ids=&farm_name=&country=&city=&dedicated=&available_for=26&status=up&page=1&size=20&has_gpu=&rented_by=&rentable=&randomize=&ret_count=&region=&healthy=true

https://gridproxy.dev.grid.tf/farms?node_total_cru=1&node_free_mru=2147483648&node_free_sru=28991029248&node_free_hru=&free_ips=&certification_type=&farm_name=&country=&dedicated=&node_available_for=26&node_status=up&page=1&size=20&twin_id=&node_has_gpu=&node_rented_by=&node_certified=&farm_id=&randomize=&ret_count=true&region=

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work in progress: Still investing...

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

There was an issue with the queries object. We were loading all values, even when they were empty or undefined. We added a filter function to remove those values.

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

The unit tests have been added.

**Comment by A-Harby** [comment]
Devnet, 5c12959.

Shouldn't this be applied everywhere or only on specific pages?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/163e8d2c-74f1-46b9-ba38-90e71911abe3)

`https://gridproxy.dev.grid.tf/farms?node_total_cru=&node_free_mru=&node_free_sru=&node_free_hru=&free_ips=&certification_type=&farm_name=&country=&dedicated=&node_available_for=6985&node_status=up&page=1&size=20&twin_id=&node_has_gpu=&node_rented_by=&node_certified=&farm_id=&randomize=&ret_count=true&region=
`

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Removed the undefined/empty-string values from the request URL.

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1750db70-e889-4d25-b12c-a70808bad630)

**Comment by A-Harby** [comment]
Verified, Devnet 935d56a.

All the queries sent from the dashboard now only have the used parameters on them.

Node Finder Page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/072475b9-a548-4032-bbad-0a036dba7b54)

Load Nodes Page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/35c18892-1769-4c0c-a3f8-2dea0e2787e9)

Dedicate Machine Page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/551e0c6d-4d02-4735-b20e-90d72c78b96b)

Your Farm Page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/81cec99b-b2e4-4eb3-8b24-50eb0b3f3626)

Farm Finder Page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/94eda08f-903c-4a41-8ca9-dfb7a33c8183)


[TC2666 - Check Dashboard queries](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4260068)
