### ISSUE TITLE
Sort the nodes in node selection with less cpu provisioned

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2354]
requires: https://github.com/threefoldtech/tfgrid-sdk-go/issues/918

**Comment by samaradel** [comment]
### Work Completed: 
Sort nodes in Node Finder by free CRU

**Comment by A-Harby** [comment]
Verified, Devnet 0d1e63f.

The request have been updated with a sorted by free cpu query to sort node in node finder by most free CPU first.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85e89d44-4ba7-497a-8b05-1c833c5fa696)
And it's reflected to all the other filters too.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/da6b60dd-f822-43d6-87a1-0bdd34be1c55)

[TC2249 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150458)

**Comment by AhmedHanafy725** [comment]
it should be on the node selection while deploying a vm to pick free nodes first. and revert the change in the node finder.

**Comment by samaradel** [comment]
### Work in Progress (WIP):

investigating..

**Comment by samaradel** [comment]
### Work in Progress (WIP):
As per ```devnet``` has some issues, I tried to use it on ```qanet``` but the filter is not supported there yet.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/16e7a39a-b75d-48bb-a475-5638cf733c94)

**Comment by AhmedHanafy725** [comment]
devnet fixed and you can resume on it

**Comment by samaradel** [comment]
### Work Completed:

- Sort solutions nodes by free CRU
- Sort node finder nodes by status

**Comment by atefnazmy** [comment]
Verified, Devnet, ad30945
The request has been updated to sort nodes on the node selection while deploying by most free CPU first. and the change 
 has been reverted in the node finder to be sorted by Node Status.

[TC2249 - Explorer should show Nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150458)

![0](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/62164f27-72d0-4db2-abc7-45102d7e1ecf)

![00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/ed4dd574-d309-4d0a-b601-116e3842aa7f)

**Comment by A-Harby** [comment]
Verified, Devnet 1b19f4f.

It was removed from the node finder.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/21b79ad0-de1f-4f0d-9cb7-a2b289c9a68f)

And only applied in deployments load nodes.
In vms.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6b847bc0-f2c2-47fc-b976-5f3b4a4e5a2a)
In orchestrators.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/27e61e5c-6c77-45b2-aff1-571e37385140)
in applications.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/65c50926-d28f-4e66-bb78-0953ec441115)
