### ISSUE TITLE
Stats number aren't display on the cards

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2357]
### Description

A clear description of the bug is:

The stats number is not shown on the cards anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0cca5d2a-f4f6-4181-9152-51b3024a45a9)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by A-Harby** [comment]
Also on the landing page, so before and after login.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bdb33921-461e-427b-be94-08c89420e6bd)

**Comment by A-Harby** [comment]
Verified, 9e745f8.

The numbers are now displayed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1c2f8849-66d5-480f-8125-590641fd1cc7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e0834b2e-adac-4ce8-8fcd-3e7f3c47faca)

[TC2457 - Homepage before login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177817)
[TC2458 - Homepage after login](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4177818)

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet
- 2.3.0
![Screenshot from 2024-03-13 18-43-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/9a228900-5d34-4a32-8f15-04cdcd549f7c)
