### ISSUE TITLE
TF Connect manual link is still outdated

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2358]
### Description

A clear description of the bug is:

The manual TF Connect link is still outdated. https://manual.grid.tf/getstarted/TF_Connect/TF_Connect.html
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/667d3913-8506-4f22-b6a1-40a1df0d1b03)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by ramezsaeed** [comment]
will be fixed here https://github.com/threefoldtech/info_grid/pull/444
