### ISSUE TITLE
Grid links on landing page are incorrect

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2359]
### Description

A clear description of the bug is:

Both links are redirecting to a 404 page. 
https://www.threefold.io/build/
https://www.threefold.io/grid/
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b8780d80-ce55-47eb-bf9b-dc7396bb0eca)

Must include any relevant identifiers, like:

- **Network**: testnet

- **Version**: 2.3.0-rc3

**Comment by samaradel** [comment]
### Work Completed:
- Remove ```Use the grid``` button
- Update ```learn about the grid``` link to [manual](https://manual.grid.tf/)

**Comment by samaradel** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2376#issuecomment-1987174096

**Comment by A-Harby** [comment]
The links after logging in are fixed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85dc8283-886c-44c9-8d9b-7b7314819eeb)
But the ones before logins aren't.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b706fef3-97eb-42dc-bf12-080d89a8f04c)

**Comment by samaradel** [comment]
### Work Completed
- Update ```Learn about the grid``` button with manual link.
- Remove ```Use the grid``` button.

**Comment by A-Harby** [comment]
Verified, Devnet d965ce4.

The links now direct to the manual page, before and after the login.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a0b54892-e220-4cd4-8e6c-ec20e03a9a1e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f7cf02c2-50ab-4960-a9f1-6bdc4b3e1361)

[TC2319 - welcome page in dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4156941)

**Comment by ramezsaeed** [comment]
Verified
- Devnet
- c98400f
![Screenshot from 2024-03-13 18-55-18](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/87e8b58a-4440-498d-91c8-1822a5281cb6)
