### ISSUE TITLE
Online node is different between stats and node finder

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2360]
### Description

A clear description of the bug is:

Online node count is different between stats page and node finder 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/03350ca9-7a3a-4766-bf9d-8f020dc3bc6c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2ff6c70d-5bed-464e-84fe-e0fe695f1f1c)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by ramezsaeed** [comment]
I think you didn't noticed the standby nodes as well.
the number is the same when you add the standby nodes.
