### ISSUE TITLE
The old proposals are removed from DAO

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2362]
### Description

A clear description of the bug is:

I can't see the old votes now on the DAO page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ce7390ac-f65e-45ab-bc30-958fed378601)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by ramezsaeed** [comment]
Its by design it shows only the proposal for certain period.

**Comment by A-Harby** [comment]
On devnet, the proposal is still listed, even from 2022 and 2023, and I believe testnet at least had a single vote in the past 2 years, right?.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d183dda3-e67c-4571-85c0-1d5163cfb84d)

And even though, what's the expiration date for them? @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
@sameh-farouk

**Comment by sameh-farouk** [comment]
Per design, Dao pallet keeps proposals that are currently open. We do not retain proposals that have been closed or completed to keep the storage cost low.
If you can retrieve some proposals in one network this means that these proposals aren't closed.
