### ISSUE TITLE
Manual in miniting page is still outdated

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2363]
### Description

A clear description of the bug is:

The support manual link on the miniting page is still outdated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f6093ea8-6416-4b0f-ba3a-854d92a6f75c)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by samaradel** [comment]
### Work Completed: 
Update ```minting support``` link to [threefoldfaq](https://threefoldfaq.crisp.help/en/)

**Comment by samaradel** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2376#issuecomment-1987174096

**Comment by 0oM4R** [comment]
> Blocked on [#2376 (comment)](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2376#issuecomment-1987174096)
> 
> `verify` link is outdated too
@samaradel 

please ignore this link for now, update the other links and merge the branch, 
will check keep this link till tomorrow

**Comment by A-Harby** [comment]
> ### Work Completed:
> Update `minting support` link to [threefoldfaq](https://threefoldfaq.crisp.help/en/)

support link is pointing to https://threefold.io/ not https://threefoldfaq.crisp.help/en/
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e284860a-8a32-41c3-b0c2-8ec134a033e4)

**Comment by samaradel** [comment]
@A-Harby comment updated

**Comment by A-Harby** [comment]
Verified, Devnet d965ce4.

The support link is now directing to https://threefold.io/.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/52e96ece-6eff-49e9-9b76-feedcce5892d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/58740dbb-a5d2-4f14-a732-62e842e1d5c7)

[TC2295 - Grid Minting Explorer](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4153425)
