### ISSUE TITLE
Validation error when listing deployments in the dashboard from other clients

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2364]
### Description

A clear description of the bug is:

Validation error from deployments made outside of the TS client, either go or terraform (name validation is different from go compared with the TS).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/78362868-8f01-4edd-82ac-db6f5ffb357f)

Must include any relevant identifiers like:

- **Network**: Devnet

- **Version**: ea66380

### Steps to reproduce

- Deploy a VM or K8s from a Go client, CLI, TFRobot, or even Terraform.
- Navigate to the dashboard.
- Connect your wallet with the same account.
- Navigate to the deployment page and check the logs.

**Comment by ramezsaeed** [comment]
@A-Harby 
this is only for logs, or the deployment is not shown if the validation is different ?

**Comment by A-Harby** [comment]
No, The deployments were listed, but I was only testing listing from other clients so maybe it could cause a problem with adding a domain in vms or works in the kubernetes from ts client

**Comment by Mahmoud-Emad** [comment]
What is the status here?

**Comment by amiraabouhadid** [comment]
Sorry for the delay took some time to do investigative work done, was able to duplicate the error. Identifying source of error in client.

**Comment by amiraabouhadid** [comment]
Might be caused by inconsistent type casting in client.

**Comment by amiraabouhadid** [comment]
error is due to missing validations for number of characters in name in go client which is inconsistent with the validation implemented in the ts client.  @A-Harby please list any other missing validations in go client. Please also let us know if validations are missing in terraform

**Comment by A-Harby** [comment]
The naming validation is different for every client (TS, GO, and Terraform). Only the TS client has an alphanumeric validation naming for any deployment name, disk name, and network name with a minimum and maximum length.

while the terraform doesn't have any length validation and can accept underscores only beside alphanumeric, and the same goes for the Go client so far(there could be a difference in some cases).

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26a6da90-2732-4496-81ca-716aa677a99c)

**Comment by amiraabouhadid** [comment]
opened an issue for it in the go sdk [here ](https://github.com/threefoldtech/tfgrid-sdk-go/issues/1055)

**Comment by AhmedHanafy725** [comment]
check https://github.com/threefoldtech/tfgrid-sdk-go/issues/1055#issuecomment-2419558915

**Comment by 0oM4R** [comment]
should set the name length to 35 characters 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/95f7469f4daa462fc410f8ebb466e8cc80216783/packages/grid_client/src/modules/models.ts#L28

and check for dashboard name length validation as well

**Comment by A-Harby** [comment]
Verified, Devnet a004c81.

The Go client now has a length validation.
![image](https://github.com/user-attachments/assets/b93906ca-ae9f-4601-a148-76d5599ffb58)
And the VM is showing successfully without any error.
![image](https://github.com/user-attachments/assets/d8bd9061-389a-478e-bdea-4b2e8bf92d3e)
But the VM isn't listed on the deployment page anymore, and I have reported it in a new [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3603).
![image](https://github.com/user-attachments/assets/afcafb75-756d-44c6-9126-f2775723aee0)

**Comment by A-Harby** [comment]
Add a new test case on Dashboard Suite: [TC2927 - List deployment from different clients](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4412605)

Update validation in CLI: [TC1492 - Deploy VM](https://app.testlodge.com/a/26076/projects/40893/suites/224178?expand_section=389033#case_3901167)
