### ISSUE TITLE
Show all deployments toggle isn't working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2365]
### Description

A clear description of the bug is:

What is the use of this toggle?
From the tooltip, it shows that if it is turned off, only deployments from the dashboard will be listed, but as you can see below, it lists all the deployments even from outside the dashboard when the toggle is off.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4a922c16-706c-405b-9e3e-60133f0b7071)

If it is to show the deployment with no metadata, then the tooltip should be corrected and shouldn't be placed on all the solutions (Micro VM only would be enough for that).

Must include any relevant identifiers, like:

- **Network**: Devnet

- **Version**: ea66380

**Comment by samaradel** [comment]
[Screencast from 07-03-24 14:36:58.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/be09b5b5-bab3-4367-9c8a-382ab30845b8)

it works!!

**Comment by AhmedHanafy725** [comment]
@samaradel the tool-tip message is confusing and it needs to be updated.

**Comment by samaradel** [comment]
> @samaradel the tool-tip message is confusing and it needs to be updated.

any suggestions?

**Comment by samaradel** [comment]
### Work Completed:
Update ```show all deployments``` info tooltip message

**Comment by A-Harby** [comment]
Verified, Devnet e7fe24d.

The toggle message was updated to `Didn't find your deployments in the list? Enable to show all deployments.`, and now the toggle is only shown on 2 deployments pages: MicroVM and Kubernetes. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/98ca7b6f-bb6f-49f5-8940-eac8310f4d80)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- c98400f

![Screenshot from 2024-03-13 18-45-26](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/4d665316-70a1-4444-bca7-3ca30de9271b)
