### ISSUE TITLE
Deployment listing stuck loading forever when there's an error

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2366]
### Description

A clear description of the bug is:

deployment listing is stuck on loading when there is an error while getting the deployment details.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7201c142-50e1-4ae6-a5c7-31c6bfd9c7e0)

Must include any relevant identifiers, like:

- **Network**: Devnet

- **Version**: ea66380

### Logs/Alerts

Must include, if available:

- Logs/Alerts.

[dashboard (3).log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/14515102/dashboard.3.log)

**Comment by A-Harby** [comment]
Still happening, Qanet 2.4.0-rc1.
 
[screen-capture (32).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/01b1521f-028d-4258-9cdd-f3a9793ea747)

**Comment by Mahmoud-Emad** [comment]
What is the status here?

**Comment by maayarosama** [comment]
Work in Progress (WIP):

Issue is hard to reproduce, but the error being thrown is from ```listContractsByTwinId``` function. I'm assuming there's a missing error handling part in the dashboard, Tried handling it in multiple methods that retrieve contracts and deployments but still isn't working

**Comment by A-Harby** [comment]
Unfortunately I was able to reproduce the error again, It's hard and not very common error to occur but it's reproducible.

[screen-capture (18).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/839670de-3210-4b47-a1e5-45a56bceb3b0)

**Comment by A-Harby** [comment]
Verified, Devnet.

The delete all contacts script splits the contracts into batches of 400 contracts each to delete all of them.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/333b7e41-d8a0-4b95-8ad4-8c91f7f7dd98)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6e4ba36d-175b-4943-98f2-05a85dc2b6bb)

[TC2721 - Delete large number of contracts](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4295754)

**Comment by A-Harby** [comment]
Verified, Devnet c14b41f.

The case is unreproducible now and if it happens, this error is shown to notify the user with a clear error message.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ad91fb5a-1dd4-4fdb-8222-0990fb52aab5)
