### ISSUE TITLE
Prevent reserving a dedicated nodes with balance less than 2 TFT

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2369]
### Description

A clear description of the bug is:

I can't deploy a VM or any solution when my TFT is less than 2, so reserving a dedicated node with the same amount should also be cancelled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1102fbf5-b28e-403a-b7f2-9bc562421725)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a5c22b2b-df83-48df-9ec9-cd7a994a2cf2)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by zaelgohary** [comment]
Work completed:

disabled reserve button if the free balance is less than 2 TFTs. added a hint that clarifies that the user has to have a minimum balance to be able to reserve a node.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : d8050a1

no nodes can be rent under 2 tft

the button is disabled and the color of the button looks bale untill you fund more than 2 tft

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a507c475-5c23-44d9-95f2-8c02b66de825)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b5561875-c099-4f59-aebb-ddecb7abd08d)

@zaelgohary  can we change the behaviour of the button when it is disabled? 
(node finder when you click on the reserve, it opens up the node health)
(dedicated node expands the node details.)


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2b165864-59bf-4727-8b1e-14bf37014045)

**Comment by zaelgohary** [comment]
> @zaelgohary can we change the behaviour of the button when it is disabled? (node finder when you click on the reserve, it opens up the node health) (dedicated node expands the node details.)
> 

@khaledyoussef24 The button behaves identically on both pages (Dedicated & Node Finder). When clicked, if the button is disabled, it opens node details.

[reserve-btn.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/5ce17da8-a22e-433b-8a5f-aaf84670de02)

**Comment by khaledyoussef24** [comment]
I think it should do nothing when disabled.
Or shows an error message notification that you should have 2 tft minimum to rent a node

**Comment by zaelgohary** [comment]
> I think it should do nothing when disabled. Or shows an error message notification that you should have 2 tft minimum to rent a node

A tooltip is already provided next to the button, explaining that the user needs a minimum of 2 TFTs to make a reservation.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/33417a4f-5aee-46c4-81b9-5466570db961)
