### ISSUE TITLE
Expiration value is 0 on contract JSON

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2370]
### Description

A clear description of the bug is:

Why is the expiration value is 0 on the contract JSON, but it shows a date on the contract list?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/46ac5aad-20f4-4cef-bb2f-810b2d189b09)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/08419fa0-7cdc-42c8-bd39-781cba21a7db)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

- **Twin ID**: 579

- **Contract ID**: e.g. 31111, 31118, 31120

**Comment by ramezsaeed** [comment]
this is not contract JSON its a deployment JSON, the correct value you will find it in the contract JSON
