### ISSUE TITLE
Prevent deploying solution without ssh key

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2371]
### Description

A clear description of the bug is:

I can deploy all the applications without having a ssh key. It should prevent deploying things like VMs and orchestrators.

[screen-capture (16).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c6dda9c1-e951-4111-81e9-cb06b780a92a)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by ramezsaeed** [comment]
its made by design, its not required ssh for solution as they already have gateway.
