### ISSUE TITLE
Add a SSH key validation

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2372]
### Description

A clear description of the bug is:

There's no SSH key format validation.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f8f54f5-58d9-4333-9bc4-a8153008e40b)

Must include any relevant identifiers, like:

- **Network**: Testnet

- **Version**: 2.3.0-rc3

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

added a function to validate if the entered ssh-key is valid to not in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2419

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/6b2ceea6-1caa-4a68-8506-2041a5be0289)

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

verified a ssh key validation is now added


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a8b08f63-32ca-4a23-9547-ca56fe77ef69)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/10d25d9e-faa4-448c-972a-f164c76557f1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7068b217-57aa-4919-9183-027a0d44a671)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4247837
