### ISSUE TITLE
Error in Spelling the Validation error message

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#2374]
**Description**

- There is an Error in Spelling the most of the Validation error messages, the word is written (then) instead of (than).

![erroSpell](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/4ed26612-5aa5-489c-948b-9be477a7538e)

![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/68d766ac-f720-488f-b18e-a3c1886d74b9)

Must include any relevant identifiers, like:

- Network : testnet
- version : 2.3.0-rc3

**Comment by A-Harby** [comment]
Verified, Devnet 17fffef.

All the larger than are corrected.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a1a9ca3a-889f-46bf-b975-e97234c77f37)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- c98400f

![Screenshot from 2024-03-13 19-03-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/6a31440a-6626-4ff5-8b22-ff291a4d0e50)
