### ISSUE TITLE
🐞 [Bug]: dashboard disclaimer mentions playground

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/264f9ef3-9587-4a4b-a0f8-b4957813cc39)

I find this on the dashboard, it mentions a playground, while that's not a thing anymore

### Steps To Reproduce

go to the dashboard dashboard.grid.tf
go to virtual machines
go to full vm 
you will find the disclaimer 

### which network/s did you face the problem on?

Main

### version

3.13

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/a65ead6d-1ba5-4f0c-9fcc-96028879c566)

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- c98400f

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/c35860ac-d854-411b-80c4-e942ba0b48a5)
