### ISSUE TITLE
🐞 [Bug]: I can't deploy a vm on development 314 with error `Cannot read properties of null (reading 'state')`

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2394]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

on local, using yarn dev and tried to deploy full vm and many other solutions, but it kept failing 

### Steps To Reproduce

1. on branch development_314
2. yarn lerna build
3. yarn dev
4. then log in and try to deploy any solution 

### which network/s did you face the problem on?

Dev

### version

development_314

### Twin ID/s

1525

### Node ID/s

125 and many others

### Relevant screenshots/screen records

[Screencast from 11 مار, 2024 EET 11:13:05 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/e44e6261-6886-43e7-aa01-5a6a274ca1dd)

### Relevant log output

```console
nothing unusual in logs
```

**Comment by A-Harby** [comment]
Verified, I can't reproduce it again.

On devnet, bd6c7c5.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e01b6a4-305d-4f0d-a7a7-9fdb933756af)
On local run, dev branch (314 is megred).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/21d76685-4290-4425-a3f2-06f26cafc753)
