### ISSUE TITLE
🐞 [Bug]: Adding IP range doesn't count the IPs with 0

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When adding the range of IPs to a farm, you are only allowed to add 16 IPs, but when the range starts at 0, it doesn't count it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/05af8f10-c003-4e44-89b8-50f0b49a942f)

### which network/s did you face the problem on?

Dev

### version

333317a

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a1d5213e-7774-45d1-92d3-661bbb3414be)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8df7ad5a-287d-4c29-93bf-22aa20297e9e)

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
should resolve this #2401 first

**Comment by A-Harby** [comment]
Verified, Devnet ff9d79e.

The count now takes the zero into consideration.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/35a6b9f6-9503-40ba-9fde-bdd925fb849b)

[TC2208 - Add Multiple IPs to a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150417)
