### ISSUE TITLE
🐞 [Bug]: Mainnet manual links are not working

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

All the manual links on the mainnet are given a 404 error.

### which network/s did you face the problem on?

Main

### version

2.3.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f9c28a9-a054-4e69-aac1-af04593f0772)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified on mainent
version : 2.3.4

all of [manual](https://manual.grid.tf/) links are working fine now
![Screenshot 2024-03-24 at 12 34 36 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b8443808-a183-4a68-94b7-124f6c127075)
![Screenshot 2024-03-24 at 12 34 32 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5e511278-3ac0-40c3-a261-03f886440319)
![Screenshot 2024-03-24 at 12 34 28 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4d1ed772-a312-422a-bef8-0b37564ff87b)
