### ISSUE TITLE
🐞 [Bug]: Deployed a caprover and deleted it but still have some contracts not deleted

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I Deployed a caprover with 2 workers and deleted it and it was deleted successfully. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0ef87582-76a3-4a2f-8bb6-85274ae0ea45)

But when I was checking your contracts page, I found that not all the contracts were deleted.

### which network/s did you face the problem on?

Main

### version

2.3.0

### Twin ID/s

7885

### Contract ID/s

291188

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c8ac05b6-3dd4-4694-95fb-b0dc1aeb619d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a03227f0-b60a-42f7-90bc-8ef05ce2aab0)

[dashboard (4).log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/14574337/dashboard.4.log)

### Relevant log output

```console
.
```

**Comment by AhmedHanafy725** [comment]
did you remove the instance after the deployment directly or there was some time between the deployment and deletion?

**Comment by A-Harby** [comment]
> did you remove the instance after the deployment directly or there was some time between the deployment and deletion?


There was some time, not a lot but I used it to verify other issue so it wasn't instant.

**Comment by A-Harby** [comment]
Mainnet, 2.3.0.
The same happened again with Caprover.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cf266a6a-0648-4242-bb36-f4915df2971c)

More surprising, it also happened to the Kubernetes.

**Comment by 0oM4R** [comment]
i tried to deploy many times on different farms but i keep getting the ip error 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/2a7f3b08-f2e3-476e-aab7-95fafe97123e)

**Comment by 0oM4R** [comment]
I tried deploy k8s with 2 workers, and delete them, the contracts existed at the beginning, but after reloading contracts table, there is no contracts left

#### please make sure to wait for few seconds and reload the table;

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 5c12959
made a caprover deployment 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/38bd136d-7ca6-46da-bb7e-758d5ccd02a7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f02af3aa-1d76-4eaf-bac5-ef4c4a8b366a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1afe5f00-693a-468c-ab76-af8d7c31f4d6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/73113205-fcec-4e2e-bc4c-569860b0f782)

and then deleted the contract and went to check my contracts and all the contracts related to the caprover were removed.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6ce70017-ce19-4cfe-b71a-5cce6c865891)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/aefd7f93-1c69-4416-9129-aeacfda4c7f7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/039cdc06-9471-4310-b06d-9ad4a59c6aad)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4150340
