### ISSUE TITLE
Add playground

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#241]
Move Playground to the mono repo

**Comment by zaelgohary** [comment]
The Playground was added. Also added build, clean dependencies workflows, and fixed linting. 

Currently working on adding version, creating docker file & docker workflow.

**Comment by A-Harby** [comment]
Verified.
Package was added https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/playground.
And was able to build and deploy successfully.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c0413b3-d47d-4288-9e13-1f01c8c715ed)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/939a3a44-5f2c-484a-9677-787a1f3975ae)
