### ISSUE TITLE
🐞 [Bug]: Threefold logo in playground is too small (unreadable) at small screen sizes

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, UI

### What happened?

I reduced device screen size, and the threefold logo became unreadable 

### Steps To Reproduce

1. run yarn dev in playground
2. login/ sign up 
3. reduce screen size to 900x 845 or smaller
4. watch the logo on the left hand side in the toolbar become unreadable mambo jumbo 

### which network/s did you face the problem on?

Dev

### version

3.14

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/61db4e0f-6267-4287-88da-3ca46a77b8cd)

### Relevant log output

```console
no logs, UI issue
```

**Comment by ehab-hassan** [comment]
Work complete

fixed at medium size and small size 
![image](https://github.com/user-attachments/assets/c561603b-a7d5-40a1-86f0-b67b581f3258)
![image](https://github.com/user-attachments/assets/e59f0cf8-3369-4f67-9440-16c966d12c1a)

**Comment by ehab-hassan** [comment]
Work Completed

**Comment by khaledyoussef24** [comment]
verified on devnet 
Version c2d6060

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/06f86f2f-830b-497c-a3cd-a2c9850e99fe" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/97bc678b-a959-4628-8915-dbe9e3722c08" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/b0fe9100-e574-4d19-8c0f-db73f6ac7407" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/db9ade2f-9433-4ff8-ba25-5b6bfc72d214" />

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4431572)
