### ISSUE TITLE
🐞 [Bug]: Error message when user tries to add same ip to farm is not user friendly

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2411]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I get an alert with a very long message of the error from the client that might not be understood by the user. 

### Steps To Reproduce

1. go to your farms page
2. expand a farm in the table
3. click add ip button
4. place a valid ip and a gateway in the form
5. click add
6. once ip is successfully added to farm
7. re click on add ip button
8. re enter exactly same ip and gateway
9. click add
10. watch the alert with the not user friendly message appear in the top right corner of the screen 

### which network/s did you face the problem on?

Dev

### version

3.14

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/c1663c13-02c3-4043-bdbd-d6afbc7b2288)

### Relevant log output

```console
logs are irrelevant
```

**Comment by 0oM4R** [comment]
we should use [types package](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/types/src/errors#tfchain-errors) to handle this error based on error class

**Comment by AlaaElattar** [comment]
### Work In Progress:
- the issue almost done, but i'm just confused about if  i should use the error package in grid client or in playground.

**Comment by AlaaElattar** [comment]
### Work Completed:
- checked on error with types package and showed user defined error msg.

**Comment by A-Harby** [comment]
Verified, Devnet ff9d79e.

Validation was added to the Add IP when the same IP was entered to show a more user-friendly error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2b31294e-561e-4af3-b79e-a6c2392016de)

[TC2678 - Add IP to Farm validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4264485)
