### ISSUE TITLE
Add warning as before when transferring TFT on dashboard

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2413]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Nelson on the Telegram chat proposes to bring back a warning to add a twin id as the memo when sending TFT from Stellar to TFChain on the dashboard.

### Describe the solution you'd like

- Add a warning as stated above.

### Where

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/d772ae5d-85b6-4094-be40-0708c64e8969)

**Comment by 0oM4R** [comment]
looks like the screenshot is not related, please ignore it.

**Comment by xmonader** [comment]
@amiraabouhadid ain't hte merged? why still in pending review?

**Comment by A-Harby** [comment]
Verified, Devnet 935d56a.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/45da67ed-64dc-4646-a4bc-f8d98a0e05b0)

[TC2202 - Bridge TFT (Deposit)](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150411)
