### ISSUE TITLE
🐞 [Bug]: Loading icon on stats page is too big

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The loading icons on the stats page is too big and it take so much time loading.

### which network/s did you face the problem on?

Main

### version

2.3.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8abeb7cd-02eb-4b21-bdaf-5562c7705928)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
Already fixed

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/c28ebb31-856b-427f-8525-9428d6d58ec3)

**Comment by khaledyoussef24** [comment]
fixed and verified now 
version : 385928e
network : devnet
![Screenshot 2024-03-25 at 8 56 03 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6b9aa018-b1be-4c30-81e1-917b1483e72b)
