### ISSUE TITLE
(Mainnet Verification) 🐞 [Bug]: enhance UI in Minting Details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The Minting Details tab UI could be better; the name is aligned to the left with no padding, and the content feels unorganized.

### which network/s did you face the problem on?

Main

### version

2.3.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8354e204-d286-45d4-9655-5b275c0cf425)

### Relevant log output

```console
.
```

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
figuring out the best way to show the minting details.

**Comment by ehab-hassan** [comment]
Work Completed
enhanced the UI
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/1d380010-cff3-480c-867b-e74dcd44f022)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/65987c83-345f-4d3a-8bb8-44a87d0d06ff)

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
show minting details like a table with a border.

**Comment by ehab-hassan** [comment]
Work Completed

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b09de9b9-2e39-4583-aabd-fc675d2fdd6f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/028d4094-0731-45b3-9105-67a81e107a4f)

**Comment by khaledyoussef24** [comment]
verified on mainnet
version : 2.5.2

Minting page from the farm side enhanced 
<img width="1358" alt="Screenshot 2024-07-16 at 11 33 20 AM" src="https://github.com/user-attachments/assets/6505418d-9967-4eda-b9f7-14e840907186">
<img width="1368" alt="Screenshot 2024-07-16 at 11 33 28 AM" src="https://github.com/user-attachments/assets/489add9b-7391-4e7f-a372-2f8dad865ebd">
