### ISSUE TITLE
(Mainnet Verification) 🐞 [Bug]: Farm finder preparing to load farms?

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The message `preparing to load farms` is always displayed, even after the farms are loaded. Why is it even shown there?

### which network/s did you face the problem on?

Main

### version

2.3.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a641cfb2-549f-45fa-81ef-a986a8655b10)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
It also appears on the node finder.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/81862de4-3e90-4b6d-9413-f81c62dd398c)

**Comment by samaradel** [comment]
### Investigation and Solution:
the ```farmsTask.initialized``` returns ``` false that's why the hint is persistent.
will check with grid-client devs.

**Comment by samaradel** [comment]
### Investigation and Solution:
Still investigating.

**Comment by samaradel** [comment]
### Investigation and Solution:
I see it's gridproxy issue, confirming..

**Comment by samaradel** [comment]
### Investigation and Solution:
when pagination is disabled it works fine, still debugging

**Comment by zaelgohary** [comment]
Issue is not reproducible.


Farm Finder:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4c95f201-8851-4573-8bb8-922698fa5c7e)


Node Finder:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/07c0f4ba-eddd-44d3-b037-8427ede77b9a)

**Comment by khaledyoussef24** [comment]
the issue still exists , the message is still there even though the farms are loaded.
will investigate more into this.


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/74c669bb-3c0f-4f0e-a8c9-00c8dd0ddba9)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f4923f07-85cd-4948-b87e-c971b25370ae)

**Comment by khaledyoussef24** [comment]
verified on QaNet
version : 2.5

working fine now
farm finder
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a734f0cd-fcbd-47d9-b2d0-a412da201581


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d094cda0-fe77-4b53-91ad-0071269222eb)
node finder
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2d562194-d5f0-46e6-85cc-02b52707b774)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ae04475b-d484-4c31-be95-5a5d2b594d6f)
