### ISSUE TITLE
Dashboard simulator, calculator enhancements

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2420]
### which package/s did you face the problem with?

Dashboard

### What happened?

Set the value of `HDD` disk to `0` by default

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/80aeda22-c7b8-44be-a263-3ac55e7aefe6)

a warning message in the simulator that contains `IMPORTANT: Farming stops once 1 Billion TFT reached (new TFT)`

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done

- Added an alert message in the SimulatorView component, 
- updated the initial value of the HDD disk to be 0 instead of 100.

**Comment by A-Harby** [comment]
The alert has been added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ae863f9-53ac-4239-94a1-56aab1112809)
But the HDD initial value do you mean this one, because it's still 1000?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3a26cce6-4c94-49f8-a344-4adbce310f3b)

**Comment by A-Harby** [comment]
Verified, Devnet c98400f.

It was on the calculator side, not the simulator.
And now it accepts zero as its initial value.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/916f8d07-cdb7-44cb-840d-74c392c8681c)

[TC2604 - Pricing calculator input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4213523)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- c98400f


![Screenshot from 2024-03-13 19-10-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/540c5ac2-0080-4d8a-aeff-4283a0c79586)
