### ISSUE TITLE
🐞 [Bug]: unused node can't be rented as dedicated node

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

As per a farmer/user:

node 4436 and 4438 : Both are unused, but 4436 is rentable and 4438 is not

### Steps To Reproduce

Try to rent nodes above

### which network/s did you face the problem on?

Main

### version

Current

### Relevant screenshots/screen records

None

### Relevant log output

```console
None
```

**Comment by xmonader** [comment]
please add to the issue the contracts on each node

**Comment by Mik-TF** [comment]
I asked the farmer for the info. Will let you know.

**Comment by Mik-TF** [comment]
The farmer said there is no contract on the nodes. Basically, no contract on the node, so both should be able to be rented as dedicated node, but only one of the two is possible.

**Comment by AhmedHanafy725** [comment]
could rent both of them 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/eb1c549b-5d35-4ed4-8238-a8c20a075e0c)

**Comment by Mik-TF** [comment]
Thanks.

Then what about this. Node ID 865, no contract, status as shared, can't rent as dedicated

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/f4ae456a-b6a0-4768-be53-ba9ddeb28e77)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/ee69eef1-94a6-451e-8be6-637f1778ed8e)


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/1e51869b-20f9-4cf2-87ae-8540dd2d843d)

Any idea?

**Comment by Omarabdul3ziz** [comment]
Hi Mik, i was trying to debug this node but i found it already has contracts, the created timestamp of the contracts says it is after your comment, but i have no other way to debug. do you know another node that has the same state?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32527347/da00ed2a-9913-456c-9242-27d98d740c0f)

**Comment by Mik-TF** [comment]
The user is deploying hundreds of presearch node on the grid, and he said the issue with 865 did not happen lately. This could be closed. It might be just a temporary issue where a new contract isn't shown temporarily so the node is not rentable as dedicated but seems to have no contract.
