### ISSUE TITLE
🐞 [Bug]: Balance input validation message on pricing calculator

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Why are the decimal points with zero not positive integers?

And also, why is my balance of 0.096 TFT approximated to 0.1? It shouldn't be to make the calculation more accurate.

### which network/s did you face the problem on?

Dev, Main

### version

2.3.0

### Relevant screenshots/screen records

[screen-capture (23).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d15d9a12-7adf-47c4-b142-364f33bb4e21)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
The balance is passed with no approximation, given a more accurate calculation.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e373e0dd-1f0f-4f2b-83ff-8492a9c55125)

But I still can't understand why the decimal point is considered not a positive number; either the validation should be changed or the error message should be changed to something like 'Balance should be a positive integer and more than 1 TFT' maybe.

**Comment by khaledyoussef24** [comment]
verified on devnet version : bef3f8f


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5bd11995-ecd7-4538-aec0-5ccc01242421)



https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4150497
