### ISSUE TITLE
integrate cpu and ram details in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2427]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

integrate cpu and ram details in the dashboard so I can choose the best node fitting my requirements

### Describe the solution you'd like

maybe to be shown up in the node finder and while selecting a node for deployment and maybe searchable text filter

**Comment by 0oM4R** [comment]
@Omarabdul3ziz  is this supported on gridproxy?

**Comment by Omarabdul3ziz** [comment]
it is implemented in this PR https://github.com/threefoldtech/tfgrid-sdk-go/pull/726 info about ram/motherboard/cpu can be found under `dmi` section on the `/nodes` endpoint response

**Comment by Omarabdul3ziz** [comment]
it is released with version 0.15.0 and deployed now on devnet

**Comment by zaelgohary** [comment]
WIP:

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2057#issuecomment-2021510752

**Comment by zaelgohary** [comment]
Work completed: 

Added processor version and memory type chips in node card. I also added a tooltip for each chip.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4ba3ce30-0783-46fc-89f3-c57d22da2fba)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f530d72
cpu and ram details are now integrated in node finder


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b757e77f-5f4d-491d-becb-2c72b0b2b44e)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459
