### ISSUE TITLE
update the simulator warning on minting to mention stellar

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2428]
### Is your feature request related to a problem? Please describe

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ce7491bc-3b93-4906-8bdd-299d9230b680)

Farming stops at 1 Billion TFT on Stellar network

### Describe the solution you'd like

Change the warning to be `Farming stops at 1 Billion TFT on Stellar network`

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

The message has been updated

**Comment by A-Harby** [comment]
Verified, Devnet a9928b8.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7cf0f32e-751a-4512-a346-d4fdd5959c4f)
