### ISSUE TITLE
Show the gold discount to the user in the pricing calculator 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2429]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Right now we allow the user to check against their own wallet or enter the number of tokens manually (but most likely they won't try it out) and it seems we are bit more expensive compared to hetzner, so to stay lucrative to the user we should show them the gold discount always and tell them how many tokens are needed to unlock it 

### Describe the solution you'd like

Adjust the calculator to reflect the FR

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
Still, investigate the best way to display the discount in the calculator

**Comment by ehab-hassan** [comment]
Note: Text not final
option 1
![pop1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/ce3bc583-7bbb-4677-b8f4-c09d983a96ef)


option 2
![pop2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/86faae61-aae3-424a-b181-64c99b899ef1)

option 3
<img width="1903" alt="Resources Pricing Calculator (1)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/7aafbe5c-b679-4abc-92f4-d7745fbe2117">

option 4
<img width="1903" alt="Resources Pricing Calculator (2)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/bb31fd0d-925f-4a2b-9a8b-716045dfa33a">

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
according to the meeting with Thabet and Hanafy working on another option.

**Comment by ehab-hassan** [comment]
@xmonader @AhmedHanafy725 what do u think?
option1
<img width="1903" alt="Resources Pricing Calculator (2)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/92c25129-487a-4031-abad-fc1070625c80">

option2
<img width="1903" alt="Resources Pricing Calculator (1)" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d50633ce-84c3-4716-9c07-eb87c91cea41">

**Comment by ehab-hassan** [comment]
Work in Progress (WIP)
Still waiting for feedback.

**Comment by samaradel** [comment]
### Work in Progress (WIP):
Card UI implemented.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/6d9f17cb-600e-44c9-afbe-3403b02cc08d)

**Comment by ehab-hassan** [comment]
Let's check tomorrow better color

**Comment by samaradel** [comment]
### Work Completed:
- Calculate the upgrade to the gold price
- Hide info card in the gold package

**Comment by samaradel** [comment]
### Work Completed:
- Add tooltip for each package card

**Comment by khaledyoussef24** [comment]
verified and added to devnet
version : ad30945



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6ce4b9e2-151b-42c9-823e-af54f825ec67)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06529ee2-1a03-4513-b746-f9901651572e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/48b67f3d-1d61-498b-89c7-53329f16ec44)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4295003
