### ISSUE TITLE
remove anything related to ROI 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2432]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/6c7ec271-2177-4c5d-aac8-96875e7450a4)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ae9bb89b-4f3d-470e-99a9-b488b9fe022a)

Remove the return of investment textbox, keep the monthly rewards

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1c317612-0cdf-454c-834d-ed018dc7b465)

hide the toggle and keep it only in the net profit mode

### Describe the solution you'd like

as above

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959
ROI toggle was removed
the ROI text box was also removed


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/457ef611-5207-47bd-bbbe-738e491c56b0)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d837e8fc-dd14-468b-a930-e1aa117c02bf)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/01199b10-9486-4d43-953e-bc27d2965178)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cbae6e5c-0427-4fe8-99b3-64e241aecb83)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 5c12959
