### ISSUE TITLE
Reduce deployments listing time

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2438]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

It took about 3 mins to list the following deployments. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/42ccae71-6ae3-4f70-92b6-bb3c33c1169d)

### Describe the solution you'd like

Reduce listing time by saving time taken in the third chunk.

**Comment by khaledyoussef24** [comment]
verified on mainnet
version : 2.3.4


deployments now have an acceptable listing time
even gpus listing have an acceptable listing time

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c0e434b6-c39a-4949-8757-5e5435c3aa15
tried many times did not exceed 20 seconds
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330
