### ISSUE TITLE
🐞 [Bug]: Worker aren't added to the Kubernetes master

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After deploying a Kubernetes master with workers, the worker isn't listed.
I also tried to add a worker after the deployment, but it didn't show up either.

### Steps To Reproduce

1. Deploy a Kubernetes master with a worker.
2. Add a worker.
3. SSH into the master and run `kubectl get nodes`.

### which network/s did you face the problem on?

Dev, Main

### version

2.3.3

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c79e0ce0-af54-427c-9d91-a28c36327fca)

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Investigation:

I tried deploying a VM with a worker and found both the master and the worker.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/de979b12-8d1f-4eb0-955a-f4a076ac5a72)


I also tried adding a new worker to it and it worked as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e6e10189-b121-464a-997f-fbfa94309678)

**Comment by khaledyoussef24** [comment]
version : 385928e
network : devnet

deployed a k8s woth a worker and worked fine
![Screenshot 2024-03-25 at 10 07 58 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b2570781-003f-4e75-8496-534c716c73e6)
and then added worker and worked fine
![Screenshot 2024-03-25 at 10 08 17 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c7d7eafa-c8d4-4f77-bf54-29304a56ac1d)
![Screenshot 2024-03-25 at 10 09 14 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1c0bc577-bb91-4960-9580-a91564891aeb)
![Screenshot 2024-03-25 at 10 09 28 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/97f414f6-3569-4d29-91c1-65567630597f)
