### ISSUE TITLE
Older VM disappeared when deploying a VM on the new dashboard.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-ts#2445]
### What happened?

Farmer says: "I just created a VM on the new dashboard. Where did all my old VMs disappear to? The overview only displays the new one."

![image](https://github.com/threefoldtech/test_feedback/assets/95933607/4471c455-e808-428f-b871-efc000f1c5af)
![image](https://github.com/threefoldtech/test_feedback/assets/95933607/66252dda-45a9-465f-9e39-af7f17c48744)

And on the contracts page it shows all the contracts created.
![image](https://github.com/threefoldtech/test_feedback/assets/95933607/c4a495e3-95bb-4fb5-b046-27880a22b619)

### What did you expect?

All deployments are expected to appear.

### What browsers are you seeing the problem on?

Chrome

**Comment by 0oM4R** [comment]
@shng4you can you provide some old contract ids ?

**Comment by shng4you** [comment]
The user confirms that the old contract has been rolled back.

Here is what farmer says: "Hey, you can forget about my last problem. The VMs are now separated into full and micro, and I didn't notice the micro ones before. It seems like they weren't deleted like I thought, they came back online. So now I'm getting rid of them."
Hence I will close this ticket.
