### ISSUE TITLE
Add computecapacity module unit tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2448]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

Add tests for [computecapacity.ts](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/zos/computecapacity.ts)

**Comment by zaelgohary** [comment]
Work completed:

Added some tests for the module and encountered some issues regarding its validation. Opened an issue [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2821).

**Comment by A-Harby** [comment]
Verified test have been added here: https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/tests/modules/compute_capacity.test.ts and they are working and passing here: https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27433452415#r0s3.

![image](https://github.com/user-attachments/assets/6b1f52d7-9db4-48d0-9915-b0fa37557b4e)
