### ISSUE TITLE
include public ipv4 cost in the resources calculator

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#245]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/7586e75a-df1a-42b2-9383-412fbcba3c00)

This is what I'm seeing, no input for ipv4

**Comment by Mahmoud-Emad** [comment]
Should implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/403
