### ISSUE TITLE
Add zdb unit tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2456]
### Which package/s are you suggesting this feature for?

grid_client

### Describe the solution you'd like

Add unit tests for [zdb.ts](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/zos/zdb.ts)

**Comment by zaelgohary** [comment]
Already done [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/9c50584f9f059de734ea83b1546d769fbc15928b/packages/grid_client/tests/modules/zdb.test.ts)

**Comment by khaledyoussef24** [comment]
verified the tests is providing the following
Deploy ZDBs
Generate Test Data/ZDB Config.
        - Select Nodes To Deploy the ZDBs on.
        - Deploy the ZDBs.
        - Assert that the generated data matches
          the deployment details.
        - Establish connection to the zdbs through
          redis client
        - Verify that the connection was established
          successfully.
        - Verify that the namespace was added and 
          that the disk size matches the generated 
          size.
        - Verify the ability to switch to your namespace
          and accessing it with the generated password.
        - Verify the ability of setting and getting
          data.


and the test is passing and working fine.


![Image](https://github.com/user-attachments/assets/f84effcb-6a55-4c81-93a1-1622e7969284)

**Comment by khaledyoussef24** [comment]
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=366955#case_4329586)
