### ISSUE TITLE
Add zmachine unit tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2458]
### Which package/s are you suggesting this feature for?

grid_client

### Describe the solution you'd like

Add tests for [zmachine.ts](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/zos/zmachine.ts)

**Comment by zaelgohary** [comment]
WIP:

Working on adding tests on all Zmachine fields.

**Comment by zaelgohary** [comment]
WIP:

Working on adding tests on all Zmachine fields.

**Comment by zaelgohary** [comment]
Work completed:

Added tests.

**Comment by khaledyoussef24** [comment]
the test is failing is there something missing shall i add ?

![Image](https://github.com/user-attachments/assets/1dd7225e-6342-4f74-8dad-bbf5f0598395)
![Image](https://github.com/user-attachments/assets/cdfd616d-ae39-4d01-914f-748ab6fa8263)

**Comment by khaledyoussef24** [comment]
verified and tested and working fine 


![Image](https://github.com/user-attachments/assets/7429bcfb-f674-477b-8ac4-3f166ba1d853)
