### ISSUE TITLE
Add zmount unit tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2459]
### Which package/s are you suggesting this feature for?

grid_client

### Describe the solution you'd like

Add tests for [zmount.ts](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/zos/zmount.ts)

**Comment by zaelgohary** [comment]
Work completed:

Added zmount tests.

**Comment by A-Harby** [comment]
The tests workflow is failing daily because of this test.
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/9932122876/job/27432996148
https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27433452415#r0s19, https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27415463877#r0s19.

![image](https://github.com/user-attachments/assets/60e24b3c-2438-4ceb-9b2f-a3b2f0a7d2e0)

Could you check it again?

**Comment by zaelgohary** [comment]
> The tests workflow is failing daily because of this test. https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/9932122876/job/27432996148 https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27433452415#r0s19, https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27415463877#r0s19.
> 
> Could you check it again?

This has nothing to do with the tests but with the workload validation itself. All tests should be working fine once https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3038 is done.

**Comment by A-Harby** [comment]
> > The tests workflow is failing daily because of this test. https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/9932122876/job/27432996148 https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27433452415#r0s19, https://github.com/threefoldtech/tfgrid-sdk-ts/runs/27415463877#r0s19.
> > Could you check it again?
> 
> This has nothing to do with the tests but with the workload validation itself. All tests should be working fine once #3038 is done.



https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2459#issuecomment-2228364969
Then this issue can be closed as the tests are doing there job, failing if something is working, and the other issue should be verified once its done and made sure the tests are passed too.
