### ISSUE TITLE
Extra Fee is not reflecting in the price shown for Dedicated Node: 6400

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#2464]
- Node ID 6400
- This is a dedicated node with "num_gpu":1
- Farmer has set "extraFee":$99"
- However in the dedicated Nodes page the extra fee doesn't appear to be reflecting:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/c41bd242-b945-4b4d-b955-d170ec1fed47)

**Comment by 0oM4R** [comment]
should be applied on node finder page

**Comment by zaelgohary** [comment]
Work completed:

Added extra fee to the total price shown to the user in node finder.

**Comment by A-Harby** [comment]
Verified, Devnet f3e199e.

The value is changed on the node finder page whenever the node extra fee is changed.
 
The extra fee when it's 10 USD.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f76edd28-8af3-4fd5-96ba-3f4f0a2bd249)
After changing it to 5000.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/38c219cc-e455-401f-b28d-462c77c4e742)

[TC2443 - Set Fee](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4164651)
