### ISSUE TITLE
🐞 [Bug]: Fix loading spinner size in k8s 

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Spinner size is way too big.

### Steps To Reproduce

- login to Dashboard
- Navigate to orchestrators/k8s
- change values so you can check the loading spinner size

Issue may exist in other VMs too.

### which network/s did you face the problem on?

Dev

### version

Locally

### Relevant screenshots/screen records

[spinner.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/dbd5bd48-0f6f-4056-aae2-d2bdbb369197)

### Relevant log output

```console
-
```

**Comment by samaradel** [comment]
### Work completed:
Decrease dynamic tabs loading size

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 5c12959

spinner size is fixed


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f73eb014-5d53-4e0a-8795-6e114db258bd)
