### ISSUE TITLE
Add monitoring url for the hosting node

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#247]
for every listing make sure that we add the metrics url for the hosting node running the vm

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/418

**Comment by Mahmoud-Emad** [comment]
Returned back to in progress because it needs to be implemented in the playground

**Comment by Mahmoud-Emad** [comment]
For the Playground Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/435

**Comment by xmonader** [comment]
Verified
