### ISSUE TITLE
Show number of workers on top of weblet

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2471]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

adding workers is not clear, how many workers i just added.
![Screenshot from 2024-03-19 11-25-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/28e49249-5cb4-4388-ad41-44e603103795)
in this picture i added about 2 workers but if want to make sure, i have to scroll down to count them

### Describe the solution you'd like

show number of workers beside `Worker` tab title or beside add button

**Comment by zaelgohary** [comment]
Work completed:

Added workers optional prop in tabs & applied change in k8s & caprover.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : e1cdba0
now no. of workers is shown in the top of the dashboard

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/04eaf51c-f8c3-4daa-9a6c-c13af38dba04)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d67ff84f-9283-4532-bf72-9fe8dd2ac22b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/25cdb149-382e-408e-8f61-bf2a1197a68b)

user can easily know the no. of added workers
tried also to delete workers after addition to make sure it decrease as well
