### ISSUE TITLE
Filter option on up & standby both

### ISSUE THREAD

**Issue by jvermond** [threefoldtech/tfgrid-sdk-ts#2476]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

If a user wants to have a quick insight of available capacity, regardless of whether online or asleep, current options are only up, only standby, or all (which included hundreds of nonexisting down nodes)

### Describe the solution you'd like

An extra option 'up + standby' would be convenient

**Comment by ramezsaeed** [comment]
Requires a ticket in grid-proxy

**Comment by Mahmoud-Emad** [comment]
It's blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/911

**Comment by zaelgohary** [comment]
WIP:

I tried adding the filter but I'm currently facing an error. Still working on it.

**Comment by zaelgohary** [comment]
Work completed:

Added the new status filter to grid proxy & playground. Also updated the status value while validating in grid proxy.

**Comment by A-Harby** [comment]
Verified, Devnet ccab3f0.

A new filter is added to the node status `Up & Standby`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0d6f2059-f01e-43f7-afec-c9b989085700)

[TC2255 - Filter Online/Offline/Standby nodes](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150464)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ad30945

![Screenshot from 2024-06-06 18-07-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/6c0c1929-4231-4ef0-8c9c-88546fcdd8bd)
