### ISSUE TITLE
Allow to create contract to unlock grace period

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2489]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

When you are in grace period, and fill it your account, it takes some time until you can access your deployment. Maybe this isn't well suited for someone who has a very important workload: they would want to fill the wallet and get the workload back on track as soon as possible.

### Describe the solution you'd like

Allow the user to query the grid/tfchain to recheck the status of the workload and re-activate the contract and then the workload is accessible quickly.

### Note

We could charge a fee for this, not just the contract price. It's the "price" to pay for the user's mistake of not funding the wallet. But we allow the possibility to have the workload up and running quickly, given a reasonable fee.

**Comment by ramezsaeed** [comment]
@sameh-farouk 
can you please check if we can add a trigger for this.

**Comment by sameh-farouk** [comment]
Easy peasy, can be fully implemented from the front end.

By showing a button to bill the due amount and restore workload when the dashboard detects that the user has some contracts in the grace period and a reasonable TFT amount in his wallet.

The button would just call ʼ bill_contract_for_blockʼ externsic with the contract ID.
it's a signed transaction and basically user will have to pay only the the transaction fee and have his contact billed immediately and consequently revive his workload.

**Comment by 0oM4R** [comment]
### issue update 

##### work completed: 
added the required functions to tfchain client and grid client

##### WIP 
use  the functions in dashboard 

##### investigation
 not sure what is the best ux in this scenario, will check with Ehab after create the required logic on dashboard

**Comment by 0oM4R** [comment]
### Work completed 
add unlock button to the ` Contract lock Details` dialog that appears only if the user has the required balance
![Screenshot from 2024-04-21 17-13-04](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/fe141751-ea66-4796-81a6-dc3d77667c1c)

### Work in progress 

adding a button to the table to allow multiple contracts unlock

**Comment by 0oM4R** [comment]
@ehab-hassan  please suggest a flow for this issue, and please check https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2582#pullrequestreview-2016824310

**Comment by sameh-farouk** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2582#pullrequestreview-2016824310
@ehab-hassan @0oM4R IMO, KISS (keep it simple, stupid), and Let the user decide to use this feature instead of handling it automatically.
Because going to automate this you will have more than one scenario to cover.
Besides what Omar has already implemented, we could add an option/button to unlock all contracts on the grace period if the user's balance is sufficient.
When the user visits the dashboard, it is his call to decide whether to pay fees to bill all contracts in the grace period, focus on important contracts, or wait.

**Comment by 0oM4R** [comment]
### Issue Update:
as discussed with Hanafy, Ehab and Emad, we are going to support three flows: the first one is already completed which is click on grace period chip to show details and unlock the contract.
2- Select contracts from contract table and unlock them
3 -  unlock all contracts 


work completed: 
change get total grace period cost to return object of contracts and its costs, to use each type in its table 
example
````
{
    "nameContracts": {},
    "nodeContracts": {
        "107218": {
            "amountLocked": 48.6378944,
            "extraAmountLocked": 0,
            "lockUpdated": 1714564608,
            "cycles": 189
        },
        "107220": {
            "amountLocked": 48.6378944,
            "extraAmountLocked": 0,
            "lockUpdated": 1714564620,
            "cycles": 189
        }
    },
    "rentContracts": {}
}
````
will move the calculation of the total cost to playground. the idea of this step is to generate a generic data that can be used in the two other scenarios

**Comment by 0oM4R** [comment]
### Issue update
Work completed:
- Implemented the required logic in clients.
- add unlock all flow to playground

WIP : 
Implement unlock selected contracts flow in playground abd will discuss the UI with Ehab next week inshallah

**Comment by 0oM4R** [comment]
### Estimated time:
will be ready for review today

**Comment by 0oM4R** [comment]
### Issue update: 
all 3 flows are done, and the pr is ready for review

**Comment by 0oM4R** [comment]
issue update: 
work completed: 
applied some comments that i got on the pr.

Investigation: 
I'm trying to handle rent contract and the node contracts related to it. i faced some issues related to the billing process but i couldn't reproduce it  


work left : 
handle the related contracts unlock, name contracts and its node contracts, and as i mentioned the rent contracts
time estimated: i had to reach to the suitable scenario for unlocking related contracts, then it's logic  and testing should be take less than working day, so i hope this will be done by end of next Sunday

**Comment by sameh-farouk** [comment]
> I'm trying to handle rent contract and the node contracts related to it. i faced some issues related to the billing process but i couldn't reproduce it

Please comment on this [issue](https://github.com/threefoldtech/tfchain/issues/969) with your details if you're experiencing any of the mentioned side effects.

**Comment by 0oM4R** [comment]
Issue update: 
- fixed some bugs related to loading the contacts locked amount, by adding loading and reset the selected contracts. 
- WIP: if the user select node contract that on rented node to unlock it, the rentContract will be added to the selected contracts automatically
  - this point need some enhancements in UI and need to be tested

**Comment by 0oM4R** [comment]
- issue update: all the logic and changes of the UI have been done
- need to investigate on rent contract billing process, i have commented on https://github.com/threefoldtech/tfchain/issues/969#issuecomment-2108160229
- also need to enhance the response of unlock method in tfchain client

**Comment by A-Harby** [comment]
Verified, Devnet 9d671ca.



[screen-capture (17).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/facbd90d-ec20-4d5a-985a-bf1205c22379)

[TC2719 - Unlock Grace period Contract](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4295189)
