### ISSUE TITLE
🐞 [Bug]: Node set with additional fee can only be used as dedicated but deploy section shows they are sharable

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- when a farmer set additional fees on a node
  - then it can only be rented as dedicated
  - but it still can be found on the dashboard deploy section and we can try to deploy on it but it never works
- solution
  - make sure node set with additional fees is not shown in the dashboard section as being deployable as a shared node

### which network/s did you face the problem on?

Main

### version

latest

### Relevant screenshots/screen records

none

### Relevant log output

```console
none
```

**Comment by xmonader** [comment]
Whilst this should be protected and enforced by the tfchain, we can filter it out from the client side

**Comment by maayarosama** [comment]
This issue will be fixed once https://github.com/threefoldtech/tfgrid-sdk-go/issues/1023 is deployed

**Comment by A-Harby** [comment]
I can't add any additional fee anymore to an offline or even online node.

[screen-capture (15).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8595b1a4-4163-4b05-82dc-1d115a8c2ac0)

Note that the values are saved on the form, but if I refresh, it goes away; it doesn't save on the gridproxy or the tfchain.

[dashboard (6).log](https://github.com/user-attachments/files/15753107/dashboard.6.log)

**Comment by AhmedHanafy725** [comment]
that happens as your node has node contracts, @A-Harby please open an issue to make the error message more clear.

**Comment by A-Harby** [comment]
Verified, Devnet 9d671ca.

I opened a separate issue for the error message: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2937.

For the node I had a fake node 72, which was shared and after adding the addition fee the status of the node changed to dedicated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4747d21d-2086-4628-a426-181f17123a92)

[screen-capture (16).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/878a4652-56ab-47e9-80e3-069ccf3f61ff)

[TC2443 - Set Fee](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4164651)
