### ISSUE TITLE
🐞 [Bug]: add stats update api to workflow and docs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Stats

### What happened?

Add `https://stats.dev.grid.tf/api/stats-update` to any workflow to trigger the update to the stats.

And also the endpoints `https://stats.dev.grid.tf/api/stats-summary` and `https://stats.dev.grid.tf/api/stats-update` aren't mentioned in the stats packages or anywhere.

### which network/s did you face the problem on?

Dev

### version

2.3.3

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
### issue update 
Investigation
will add cron job to fetch the update endpoint, we will need to monitor cron with zinit also

**Comment by A-Harby** [comment]
Verified, Cron jobs have been added to run every 6 hours daily.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/ca2ed41dba4cb69e8b11f8101c2f6f817f077398/packages/stats/Dockerfile#L19
