### ISSUE TITLE
🐞 [Bug]: some gpus details does not load [Mainnet]

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

some gpu details does not load in dedicated machines

### Steps To Reproduce

go to dashboard 
go to dedicated machines in deploy
apply filter for gpu
check any node of these nodes
![Screenshot 2024-03-24 at 1 12 25 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/10181950-7424-4d9f-91e1-1dd877247f65)
the gpu data does not load even though the node status is up

### which network/s did you face the problem on?

Main

### version

2.3.4

### Relevant screenshots/screen records

![Screenshot 2024-03-24 at 1 05 55 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/16938f93-d4a6-4487-b97d-1a32dedefde4)
![Screenshot 2024-03-24 at 1 12 25 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0437e87f-8afa-4642-ae83-7bff1c0c6fab)
![Screenshot 2024-03-24 at 1 14 21 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a355087-9cff-438d-a39e-42008f19ba24)

### Relevant log output

```console
NA
```

**Comment by ramezsaeed** [comment]
@sabrinasadik 
can we check this nodes why are not responding to RMB

**Comment by zaelgohary** [comment]
Investigation:

All mentioned nodes seem to be down as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/13891d0f-b979-4c47-9164-1ac380651f6e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/1263e807-f759-47c5-a158-212e99934f3d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/df2f663e-6442-4518-8ef9-6f16747225ca)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f1c2b8dd-43f5-4798-bb2d-4855b2ff9db8)


The error displayed in the GPU details card indicates that GPU details cannot be retrieved if the node is offline.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f77e76df-4a89-4e65-bb00-b9b3fa3d0805)


As for node 1106, it's up but it doesn't have a GPU

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/fefe3b2b-fe2b-44ba-8f02-8d4989c4b528)

**Comment by zaelgohary** [comment]
@A-Harby There's a difference between node status and node health. A node might be up but not healthy at the same time. That's why it's been clarified in the alert below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/1b8843c0-d987-4117-98a0-baea725beb87)

**Comment by A-Harby** [comment]
> @A-Harby There's a difference between node status and node health. A node might be up but not healthy as it takes up to 90 mins for the status to be updated on the chain. That's why it's been clarified in the alert below.
> 
> 

Okk, and correct me if I'm wrong but shouldn't the node status be changed after 90 minutes to offline too?

It's still up for 3 weeks now.

**Comment by zaelgohary** [comment]
Moved to 2.5 as it needs more investigation.

**Comment by zaelgohary** [comment]
> > @A-Harby There's a difference between node status and node health. A node might be up but not healthy as it takes up to 90 mins for the status to be updated on the chain. That's why it's been clarified in the alert below.
> 
> Okk, and correct me if I'm wrong but shouldn't the node status be changed after 90 minutes to offline too?
> 
> It's still up for 3 weeks now.

The node is up as it sends uptime reports to the chain. The last update report was 17 mins ago as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/8ae88e6d-cfa8-4ab7-9435-bbc0d237b5fe)


However, we cannot perform an RMB call to the node due to its unhealthy status (for some internal issues related to the node itself), and deployment is not possible on this node because it has a read-only disk.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/efc16d08-b35b-409d-9437-86fa2b59db94)


![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e5e12d47-cb0a-47f6-9de0-5d5a61003564)

**Comment by khaledyoussef24** [comment]
nodes now seemed to have status down so it is reasonable that the gpu info will not load.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5ebbca3a-b2d7-4613-85c6-4d74ab038be9)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b2de3d7-b5a8-4118-aa4c-e8fa1a39b681)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/04b2f8ef-4c23-4095-be9e-dea37214e1fb)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cb2f6c44-e045-4529-8404-9b061dc1ecf6)

will close this for now.
