### ISSUE TITLE
Enhance dedicated nodes filtering

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2496]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Filtering for dedicated nodes initially results in too many requests. When using the node finder to search for dedicated nodes, we ask for information on all nodes' farms, which could be problematic on the mainnet.

[dedicated_filter.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c98c4d84-4457-47fc-9cc3-34c5bc4aa77b)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/47ae98bb-37ec-44fd-a717-d9f355be3d9e)

### Describe the solution you'd like

Requests should be limited to nodes only.

**Comment by Mahmoud-Emad** [comment]
The whole page will be deleted after solving [this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2575).
