### ISSUE TITLE
simplify the profile manager usage

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#250]
Removing the word profile manager all together, let's use `Connect your TFChain Wallet`, add a question to ask to if you have an SSH Key or want to generate one for you, similar to this UI flow

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/4ca6d60e-54f0-4a54-bc6e-db18302b1792)

* let's introduce a password to just encrypt/decrypt the mnemonic on the local storage, but we can still keep using mnemonic to encrypt the data as a store secret

**Comment by MohamedElmdary** [comment]
TODO: Move `profile manager` to navbar

**Comment by A-Harby** [comment]
Verified 
Login changed to `Connect your TFChain Wallet`
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/772b01da-d236-4819-aae2-618a0fe17ac2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/caa3f691-810f-4758-be7f-fa8bd5efbba2)
