### ISSUE TITLE
🐞 [Bug]: Mismatch in farm location.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-ts#2500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The farm is located in Greece but on the dashboard shows in the United States.

### which network/s did you face the problem on?

Main

### version

2.3.4

### Node ID/s

635

### Farm ID/s

3617

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/f20dc845-a8ec-4fe0-b15f-2cc4b8f658f6)

### Relevant log output

```console
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/f20dc845-a8ec-4fe0-b15f-2cc4b8f658f6)
```

**Comment by khaledyoussef24** [comment]
all of the nodes in this [link](https://dashboard.grid.tf/#/deploy/node-finder/?farm-id=3617) are USA

**Comment by shng4you** [comment]
The same ticket is already open [here](https://github.com/threefoldtech/tf_operations/issues/2435), so I will close this ticket.
