### ISSUE TITLE
🐞 [Bug]: Node resources circle is loading!

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The node resources circle is loading on both my node table on your farm and on node finder.

### which network/s did you face the problem on?

Dev

### version

bd6c7c5

### Relevant screenshots/screen records

[screen-capture (20).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ace380e7-8bb2-4224-99a8-ab5dc9cf2d42)

They are loading.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4addc092-d59f-4295-a8ff-4d0b1e63e38a)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
Verified, devnet 6720234.

Resource graph circles are not loading anymore.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e5b25f73-da21-4bfa-af92-0d2af3f508ef)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0c80d41e-1035-4622-9df6-eeb0a3fc26b4)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
