### ISSUE TITLE
integrate ubuntu 23.04 in dashbaord

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2504]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

blocked on 
- https://github.com/threefoldtech/tf-images/issues/195

### Describe the solution you'd like

integrate the mentioned image in dashbaord

**Comment by zaelgohary** [comment]
Work completed:

Added the flist to Micro & Full VM.

**Comment by khaledyoussef24** [comment]
not found on devnet fullvm
version : 85a6fa4



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4b7987e7-8cb9-4da3-9064-11c63ea92c9d)

**Comment by zaelgohary** [comment]
It was integrated only in Micro VM as the image is a cloud init so it can't be mounted on "/". (Full VM has a default disk that mounts on "/"). I forgot to edit the comment above.

**Comment by zaelgohary** [comment]
@maxux Can you promote this too?

**Comment by zaelgohary** [comment]
> Which file is it as well ?

https://hub.grid.tf/petep.3bot/ubuntu23.10_mycelium.flist.md

**Comment by maxux** [comment]
It get promoted Monday to: https://hub.grid.tf/tf-official-vms/ubuntu-23.10-mycelium.flist.md

**Comment by khaledyoussef24** [comment]
verified and tested on devnet
version : b72ee05

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ef6bfa4-befa-4a67-8de7-050772dcc8a7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cdd79409-bea9-4945-86e9-4a3c586e5373)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4293787

**Comment by ramezsaeed** [comment]
Verified:
- devnet
- 4b03114

on'y available for microVM not for FullVM
