### ISSUE TITLE
Integrate Arch image in dashboard

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2505]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

blocked on 
 - https://github.com/threefoldtech/tf-images/issues/195

### Describe the solution you'd like

integrate the image within playground

**Comment by zaelgohary** [comment]
Work completed:

Added the flist to Micro & Full VM.

**Comment by maxux** [comment]
Which file is it ?

**Comment by zaelgohary** [comment]
> Which file is it ?

https://hub.grid.tf/petep.3bot/arch_mycelium.flist.md

**Comment by maxux** [comment]
It get promoted Monday to: https://hub.grid.tf/tf-official-vms/arch-mycelium.flist.md

**Comment by khaledyoussef24** [comment]
could not deploy on devnet
version : b72ee05
tried with multiple vms and faced this error


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c7a52aa4-55fe-44e5-9641-ed2043ca504c)

then tried with one ssh and faced this error

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/daa81ecc-d192-496d-8c06-d3e328546f7c)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fa981776-3f0e-4651-bd2c-16feabcf2f9e)

**Comment by zaelgohary** [comment]
> deployed a multiple vms and worked fine but when i tried to deploy with multiple ssh keys i can not ssh on the machine

All images need to be updated to support multiple SSH keys. You can comment [here](https://github.com/threefoldtech/tf-images/issues/231) and we're currently restricting the feature till all flists are updated as seen [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2892).

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945
deployed an arch image using the new integrated image for micro vm


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e7acace7-33de-472d-902b-8a778a0952d7)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4293789

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- efad68b

![Screenshot from 2024-06-09 17-01-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/8416f849-24d4-48ea-bbb3-efed96e23172)
