### ISSUE TITLE
🐞 [Bug]: Unable to see the capacity of nodes from the farmers' perspective on the Dashboard.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/tfgrid-sdk-ts#2508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

A farmer reported that he is unable to view his Node capacity on the dashboard

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/d8ea92e2-f911-4104-a9bb-a233772d885a)

### Steps To Reproduce

When I attempted to replicate the problem using Node Finder, it functioned correctly.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/eb3da048-b3e2-4a0d-a61f-bc6d4aa5b205)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/db2404dd-23ea-4171-8783-77ed776009cf)

### which network/s did you face the problem on?

Main

### version

2.3.4

### Twin ID/s

12119

### Node ID/s

6630

### Farm ID/s

5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/6025b403-e231-43db-9b10-62a1bff007a5)

### Relevant log output

```console
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/95933607/6025b403-e231-43db-9b10-62a1bff007a5)
```

**Comment by Mahmoud-Emad** [comment]
It needs to be the same design in both components.
