### ISSUE TITLE
🐞 [Bug]: Mycelium IP on K8s is not printed

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#2510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Deploying a K8s cluster with Mycelium IP does not show the IP on the cluster but appears when viewing cluster details.

### which network/s did you face the problem on?

Dev

### version

2.3.4

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/639b191f-4637-46b8-82a1-2db538e8dba9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/3b45634d-2204-454d-83e0-a526c124a79b)

### Relevant log output

```console
none
```

**Comment by zaelgohary** [comment]
Work completed:

Fixed by getting master's mycelium.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e1cdba0

mycelium ip is now printed

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b463f5a9-5618-4b4b-9d83-09dba890e2e7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f7a2cb09-b45e-417e-ac79-74bb99d850fd)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f9439a77-9552-4a4c-b30e-1e33f998dfbb)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8c402fa7-7075-4916-ab26-8957e31417ee)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4263884

**Comment by ramezsaeed** [comment]
Verified:
- Devenet
- e7030e6
