### ISSUE TITLE
🐞 [Bug]: Please fix typo in PR template 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The PR template has a typo in the Documentation PR section. It says Plaese instead of Please. Just look at screenshot below 

### Steps To Reproduce

1. Open a PR
2. Look at the Documentation PR section in the issue template 

### which network/s did you face the problem on?

Dev

### version

NA

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/5d484f68-a0f4-4f49-ac4c-5b7ab39214fd)

### Relevant log output

```console
no logs
```

**Comment by xmonader** [comment]
done ya setty https://github.com/threefoldtech/tfgrid-sdk-ts/commit/d91366d5a0cbe87f7eb59d1bfc207b77fa4920ab
