### ISSUE TITLE
🐞 [Bug]: Incorrect manual link

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The manual get started link gives 404

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/1f8e62ee-c347-4e2e-883b-af42c79f81f0)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a44fa1a2-e67d-435c-8bfb-dbd5e49e9d7a)

### Steps To Reproduce

- Go to Dashboard
- Click the manual link in the connect Dialogue

### which network/s did you face the problem on?

Dev

### version

f530d72

### Relevant screenshots/screen records

Attached above.

### Relevant log output

```console
-
```

**Comment by A-Harby** [comment]
Verified, Devnet d8050a1.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/28f4d046-4d5f-4fac-8351-0cd133f64ed7)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0e6b0f7c-07e2-4c3f-8d22-6cfbe31d5847)
