### ISSUE TITLE
[Feature] Move filters to side instead of top

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2515]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Move filters to side instead of top

### Describe the solution you'd like

Move filters to side instead of top

**Comment by A-Harby** [comment]
Verified, Devnet 6720234.

The filter is moved to the left side; it's responsive and can be collapsed on small screens.

[screen-capture (22).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/268d2b20-ef81-42ff-a5bb-5582799c2fec)

and the same applied to the filter on the farm finder page.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a0a46bf2-6247-43b9-ae17-2df970780f14)


[TC2659 - Node Finder filters](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4253053)

**Comment by A-Harby** [comment]
But for the dedicated node, the filter inputs are too large, and they take up the whole page without giving the dedicated node table any space.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/10bca8b2-4acc-4ef7-aa5d-fcdfbfd823bb)
And they are not responsive or collapsible.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b1a51fc5-469b-4d1c-9314-a8bc3480f95e)

**Comment by A-Harby** [comment]
Also table height is not the same as the filters.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7349ec2f-a333-4cf4-8854-e0a8bd5fd48f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5a0c849c-0c63-47ec-8da0-719e6cb21482)

**Comment by MohamedElmdary** [comment]
> But for the dedicated node, the filter inputs are too large, and they take up the whole page without giving the dedicated node table any space. ![image](https://private-user-images.githubusercontent.com/109473873/319338600-10bca8b2-4acc-4ef7-aa5d-fcdfbfd823bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjIzNDQsIm5iZiI6MTcxMjIyMjA0NCwicGF0aCI6Ii8xMDk0NzM4NzMvMzE5MzM4NjAwLTEwYmNhOGIyLTRhY2MtNGVmNy1hYTVkLWZjZGZiZmQ4MjNiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwOTE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTBlNTFkYWJlZTQ3ZDJkOGJjZjg2MmJlNDNhYTA5ZjIzNjRkMTBlZjVhYzJiOTYxODY0ZmEzZWYwMGFiODg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bVKNLKsNkPEsQ_k8qh-ksOsUgpG-I9rqG3Aoc_caW0) And they are not responsive or collapsible. ![image](https://private-user-images.githubusercontent.com/109473873/319338500-b1a51fc5-469b-4d1c-9314-a8bc3480f95e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMjIzNDQsIm5iZiI6MTcxMjIyMjA0NCwicGF0aCI6Ii8xMDk0NzM4NzMvMzE5MzM4NTAwLWIxYTUxZmM1LTQ2OWItNGQxYy05MzE0LWE4YmMzNDgwZjk1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNFQwOTE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDNhNWU1MmZjYzY3YTA4N2ZmNTI4N2U1M2E4OTQxZTczNWVmMGEzNWYwYjU5ZTA2OTdiODY2NjZlNGYyOWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eg__hkYWo8VZVaLsZ3V59JlRdfI7OJaqJw-T023Ihks)

dedicated nodes should be removed soon so we didn't update it

**Comment by khaledyoussef24** [comment]
verified on devnet 
filters now moved to side of the node finder 
and height issue fixed

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d0ba3a0e-d12c-424f-8729-256286800d13)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/18706fd3-e24c-4253-b219-70d9c64fed71)

the filters are also responsive and working fine

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/54ac9b9a-5d12-422e-9f6f-0e00fc7c6dab)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4dc8f8ae-efc9-44cf-9797-90d26eca519a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1390f751-e68d-405e-9b02-e73f079cf34d)

**Comment by ramezsaeed** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/ed9952a0-feb5-4131-af01-d75df1703074)
