### ISSUE TITLE
show tft price in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#252]
can use https://www.coingecko.com/en/coins/threefold

**Comment by xmonader** [comment]
moving back in progress 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c23cc6e9-924f-4bce-8656-7be4f076d9dc)


It gets hidden when the sidebar is expanded

**Comment by Mahmoud-Emad** [comment]
> It gets hidden when the sidebar is expanded

updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/399

**Comment by xmonader** [comment]
verified
