### ISSUE TITLE
🐞 [Bug]: Reserve button issues in Node Finder

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- If the user is logged in & clicks 'Reserve', the login dialogue will be shown and it'll hang there after login until I change the page or refresh.

- If the user was logged in and then logged out, he'll be able to reserve.
- After reserving the node, the node card should be updated

### Steps To Reproduce

- Go to Dashboard & login
- Navigate to Node Finder
- Try to reserve a node

OR
- Go to Dashboard & login then logout
- Navigate to Node Finder
- Try to reserve a node

### which network/s did you face the problem on?

Dev

### version

5c12959

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
WIP:

Currently working on fixing the reserve button if the user is logged in or not.

**Comment by zaelgohary** [comment]
WIP:

The user couldn't reserve/unreserve because the profile value was not a ref, fixed by converting the profile to a computed value. Also fixed the update table and now the button is being updated accordingly, however, the rented/rentable chip is not being updated as the node is sent as a prop. I'm still trying to find a better solution than sending the prop again just to change a label. Maybe I'll remove the emit of the reload table completely and change it within the node details card itself.

**Comment by zaelgohary** [comment]
Work completed:

Used reactive key (node.rentedByTwinId) to update the node card upon reserving/unreserving a node.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : f1e3728
user can now reserve nodes from the node finder


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/083a0ed8-dc2b-4cd0-a1bf-07d1c3ffd012)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7f1d45df-13a7-4d66-8e31-cb3187f37912)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/65991e1f-765c-4807-8cd8-6ace2b226746)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4246386

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- f3e199e
