### ISSUE TITLE
Enable the SMTP option on the solutions if the solution has a public ip

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2522]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The SMTP ports are blocked on the private network. so to have it working, the solution should have a public IP.

### Describe the solution you'd like

- Disable the SMTP option if the solution doesn't have a public ip
- Add a hint to SMTP tab to inform the user that he has to add a public IP to the solution to enable it

**Comment by khaledyoussef24** [comment]
verified on devnet
version : a542a73

while activating public ip 
smtp will be activated automatically


![Image](https://github.com/user-attachments/assets/fbe08135-1c24-4681-a158-c3df6514d31b)
![Image](https://github.com/user-attachments/assets/782f67c3-6186-425d-bfe2-edf05251457c)
![Image](https://github.com/user-attachments/assets/dc1dc8bc-a189-4433-a590-5947fb39bc75)
![Image](https://github.com/user-attachments/assets/5b8e6a48-9df7-45b8-ab05-a3454b8cc5b0)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4346827)
