### ISSUE TITLE
Add filter for free "Rentable" dedicated node in node finder

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#2523]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

when use the node finder and enable the dedicated node button; after that i need to be able also to filter only the rentable nodes so i can rent one.

### Describe the solution you'd like

Add drop down menu like the Up/Down one.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e1cdba0



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99d06a07-0608-4fae-95ee-e41fc614737d)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/111adc7d-6f89-4656-8326-60716292578e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d122c897-91fc-4dbc-ba72-7270222bbc62)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4263741

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- e7030e6
