### ISSUE TITLE
🐞 [Bug]: public ip column is missing in some application's deployment list

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

some solutions can be deployed with public ip but the deployment list does not have field for the ipv4 ( not all the solutions so it is in consistent )
<img width="1680" alt="Screenshot 2024-04-03 at 10 28 10 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3fc99127-83aa-4e78-80bf-81b9baa771e2">
<img width="281" alt="Screenshot 2024-04-03 at 10 28 18 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/508cbc4f-a4f5-41d6-bbf0-428a1e7acbe8">

solutions which missing the column 

1. funkwhale
2. next cloud
3. presearch
4. casperlabs

### which network/s did you face the problem on?

Dev

### version

d2a2d6b

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed:
Add ```Funkwhale``` and ```Casperlabs``` to IPV4 solutions

**Comment by A-Harby** [comment]
It's still messing in some applications that have public IPv4 in the network option, but it doesn't have IPV4 in the deployment list table.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0b7a8504-3239-4ee3-94dc-741f91b3bd92)

1. Peertube.
2. Mattermost.
3. Discourse.
4. Taiga.
5. Static Website.
6. Wordpress.

**Comment by samaradel** [comment]
@A-Harby I see ```Peertube```  doesn't have  ```IPv4``` toggle

**Comment by samaradel** [comment]
### Work Completed:
Add missed IPV4 column for applications:

- Mattermost
- Discourse
- Taiga
- Static websites
- Wordpress
