### ISSUE TITLE
🐞 [Bug]: I get This twin id doesn't exist when trying to transfer funds

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#2528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When I'm trying to transfer funds by twin id I get ``` This twin id doesn't exist``` Even though when I try to transfer funds by address and use its address it passes validation.

### Steps To Reproduce

1.  Connect your wallet
2. Navigate to TFChain section then to TF token transfer
3. choose transfer by twin id
4. Input a valid twin id, I used ```89```

### which network/s did you face the problem on?

QA

### version

2.3.5

### Relevant screenshots/screen records

![Screenshot from 2024-04-03 14-55-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/2b74a582-3e29-4c01-99c7-b9f982296473)

### Relevant log output

```console
N/A
```

**Comment by zaelgohary** [comment]
Twin exists in the mentioned network.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/9e44383c-9a9f-4f08-8389-e8ba36d60c01)

**Comment by 0oM4R** [comment]
@maayarosama  can you please provide the mentioned account address?

**Comment by 0oM4R** [comment]
the mentioned account address `5GNU4aqL9JPj79hUDyPrPPTCpaMcd3LRAmyXvvWUZYtNcLZb` on QA has twin id  32, 
![Screenshot from 2024-05-08 10-29-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/42d795d1-dd34-4243-a4b9-b0468dbcc90c)
and the twin id 89 doesn't exist on Qa 
![Screenshot from 2024-05-08 09-59-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/bb19b4df-fac1-45a2-8a0e-b57fac6c9c50)
will move the issue to verification

**Comment by A-Harby** [comment]
Verified, QA.

The twin 89 was deleted from Qanet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c8f4990f-a0aa-45e6-b322-6e9e95a09a27)
So the validation is working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d0071940-9b4c-4693-ba46-2623833eb5f1)
