### ISSUE TITLE
Block user until he sets a valid email

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2529]
**TBD**

### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The user is not required to provide their email.

### Describe the solution you'd like

If email is defined in the twin details page, user flow should be as normal. If not, the user should be redirected to the twin details page to update his email.

**Comment by amiraabouhadid** [comment]
Added redirection to twin details for email update

**Comment by A-Harby** [comment]
Verified, Devnet cddbd85.

The email is now auto-written if the mnemonic has already entered the email value before.

![image](https://github.com/user-attachments/assets/334c11d4-ef5d-4a9e-907c-d6af8208f390)

[TC2113 - Connect Wallet](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)
