### ISSUE TITLE
Improve visibility for network traffic billing

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2530]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Currently billing for network traffic isn't in the foreground when using the deployment pricing calculator and the solution/contract views. Adding some info and insights into network billing can help avoid surprises for users.

### Describe the solution you'd like

For the deployment pricing calculator, we can consider some combination of:

1. Alerting the user that network traffic billing is not included in the calculations
2. Add a box where the user can enter a GB per month traffic estimate to include in the calculation

Likewise, for the contracts view:

1. Add a column to the contracts table showing network consumption (the table is already crowded though)
2. In the billing overview at the top, give a breakdown of how network traffic is contributing to the total hourly cost
    * This is a bit complex, because traffic billing is discounted at the same rate as the contract
    * So it would require querying the nru reports for each contract, calculating the per contract billed amount for traffic based on the contract discount rate, and finally summing a total

**Comment by ramezsaeed** [comment]
bandwidth already updated in the pricing calculator.

![image](https://github.com/user-attachments/assets/2c9acfa8-7ac8-4d35-bea5-233eacd4c39f)

**Comment by ramezsaeed** [comment]
![image](https://github.com/user-attachments/assets/72c8e5e3-6ce3-40ca-99e3-6016381f5d6a)

https://www.manual.grid.tf/knowledge_base/cloud/pricing/pricing.html

**Comment by khaledyoussef24** [comment]
verified on devnet
Version c2d6060
go to the pricing calculator and enable the ipv4 and verify the cost of using the bandwidth 
<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/034b6b5d-bf01-464a-88f4-f8892c30cc82" />
[pricing](https://www.manual.grid.tf/knowledge_base/cloud/pricing/pricing.html) 
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4318068)
