### ISSUE TITLE
Update rmb-peer with the latest envelope data

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#2539]
## Description

rmb-relay v1.3.0 added a new optional `relays` field that is part of the Envelope to avoid chain updates delay: https://github.com/threefoldtech/rmb-rs/blob/v1.3.0/proto/types.proto#L75
This new field should have the current relays for the twin sending a request to a relay. It should be a list of relays in the format `<hostname>`, for example: `relay.dev.grid.tf` and `relay.dev.02.grid.tf`. neither protocol or port should be added (`wss` or `:443`).

Reference [PR](https://github.com/threefoldtech/rmb-rs/pull/194) and [Issue](https://github.com/threefoldtech/rmb-rs/issues/189)

**Comment by zaelgohary** [comment]
Investigation:

Still checking the required changes that need to be made.

**Comment by AbdelrahmanElawady** [comment]
I should probably mention that sending relays as the part of the message will not work on networks other than devnet as peers aren't updated on other networks (mainly zos nodes).

**Comment by zaelgohary** [comment]
WIP:

Updated the types.proto and generated the new types. Currently working on editing the challenge with the new relays.

**Comment by zaelgohary** [comment]
Work completed:

Added relays to the envelope and set it whenever user sends the envelope. I also added it to the challenge the same way it's implemented in rmb-rs. However, whenever I try to run the example script from the direct client, I get failed signature error as shown below. 

P.S. the old challenge works just fine.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/802bda5b-b4f2-4c1b-9ecf-fa7a8af26b31)

@AbdelrahmanElawady Can you please check if I'm missing something?
