### ISSUE TITLE
New Ssh-Keys page enhancements

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2543]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

It's not a problem

### Describe the solution you'd like

1. There Should be only one table containing both keys active and inactive 
2. The 'Manage Ssh Keys' button in the deployment needs some enhancement
3. Update the activation `Checkbox` to only active/inactive the keys and `don't open the details dialogue`
4. The SSH-Keys IDs should start from 1
5. Generate a name for the old key if there is no name

**Comment by Mahmoud-Emad** [comment]
this needs to happen directly after login

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b7631a98-3ef2-4fad-97ea-9131620a197b)

**Comment by Mahmoud-Emad** [comment]
this looks very odd

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/45754df9-a4f7-44c7-beaa-2a4336ad5ebd)

**Comment by Mahmoud-Emad** [comment]
Should be just one table contains all keys
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/55226ec4-87e7-4305-8758-a38f0ebb3a25)

**Comment by zaelgohary** [comment]
Section titles are bigger than the ones on other pages. Maybe we can use the same font size used in them.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ac0071b2-22ac-4f44-a531-40173c981d8e)

**Comment by zaelgohary** [comment]
The ID in tables starts with 2.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/2e021c56-61dc-4d30-b029-2a00563a48e1)

**Comment by samaradel** [comment]
@ehab-hassan can you provide better enhancement suggestions for ```2. The 'Manage Ssh Keys' button in the deployment needs some enhancement``` please

it looks 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/0a42b01f-433c-4da3-a41a-10768ec612f5)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/4ff404ac-ac43-43ab-a87b-0d2b04182995)

**Comment by ehab-hassan** [comment]
@samaradel I liked it like that, just I think we need to force the user to add a name to the key

**Comment by samaradel** [comment]
### Work Completed:
- Remove Active keys table
- Add all keys into one table
- generate a name for keys that haven't a name
- Reduce the size of titles
- prevent opening the dialog of ssh key details by clicking on the active checkbox

**Comment by samaradel** [comment]
### Work in Progress (WIP):
- All SSH key migration functions moved to ```utils``` folder
- Migration is running in the background when the user logs in or connect

**Comment by khaledyoussef24** [comment]
can we make warning messages be more precise (different message for each button)?
for importing, can we make the message `Importing SSH key will cost you up to 0.01 TFT`
<img width="591" alt="Screenshot 2024-04-16 at 11 44 22 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ee88f914-8a06-4f28-9cc5-baafbbe5c4f2">


for generating, can we make the message `generating SSH key will cost you up to 0.01 TFT`
<img width="613" alt="Screenshot 2024-04-16 at 11 47 34 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/52125177-45e6-4d0a-b160-f64704281c3e">

can we also change the title of the generating from `Add new SSH Key` to `Generating new SSH Key` or `Generate new SSH Key`
<img width="140" alt="Screenshot 2024-04-16 at 11 48 44 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e8889864-9f12-486f-8b67-9ab28d117aa9">

**Comment by samaradel** [comment]
### Work in Progress (WIP):

- Generate a name when the key is imported without name

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work in Progress (WIP):

- **Validation Rule Enhancement**: Modified the validation rule to accept SSH keys without names.

- **Key Name Handling**: When importing an SSH key, the system now takes the key name if it exists or generates a new one if not.

- **Migration of Old SSH Keys**: Implemented a mechanism to migrate old SSH keys after activating the profile manager. This migration process ensures that old SSH keys are transformed into the new `SSHKeyData` format.

- **Refactoring with `SSHKeysManagement` Class**: Introduced a new class named `SSHKeysManagement` to centralize all SSH functionality. This class helps avoid code duplication by encapsulating functions that are used across multiple places.

- **Button State Management**: Disabled the Import, Generate, and Export buttons while Deleting, Creating, and Updating SSH keys. This prevents errors and ensures data integrity during key manipulation operations.

- **Wait for Chain Completion**: Implemented a mechanism to wait for the chain to finish its task before updating the table of SSH keys. This ensures that the table reflects the most up-to-date information after any operations on the SSH keys.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work done

- Rename the tab of 'SSH Key' to 'SSH Keys' to match the new feature
- Generate a unique name/key and check if any of them exists on the profile keys
- Check the user balance if enough or not before updating the chain and notify the user 
- Rename the text area and input fields
- Migrate and take the old key in deployment if the balance isn't enough to avoid errors
- Removed unused loggers.
- Update the header font size.
- Fixed the issue of exporting some keys by looping over the selected keys and filtering all user keys based on the ID and then passing them.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : dd92950
User now can have more than key
he can activate which keys are active for deployments , manage keys before deploying


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e9fbbd0e-19c7-41d3-95d1-63a1ce9806b8)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/53f09e48-d5d4-4596-9772-60a8f8a53113)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db7ba150-64d1-4464-b277-434182f4d83d)

provided tests covering it
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#suite_section_430164
