### ISSUE TITLE
(Mainnet Verification) 🐞 [Bug]: node 6673 has a GPU, confirmed with deployment, but not shown in dedicated node list (GPU toggle on)

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

From Nelson on TG: https://t.me/threefoldtesting/14710

- "node 6673, has a GPU, confirmed with deployment, but does not show in the dedicated node list with the GPU toggle on"
- also: additional fees are set but not showing up
### Steps To Reproduce

- go to dashboard dedicated machines
- set GPU toggle on
- 6673 is not visible
- GPU is set to 0 on the dashboard

### which network/s did you face the problem on?

Main

### version

latest

### Node ID/s

6673

### Relevant screenshots/screen records

grid proxy does see it:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/beaa752a-6e97-43ad-92d4-9252eca41a31)

gpu set to 0 on dashboard: 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/e77061a9-f594-4673-b4ed-be339be58746)

### Relevant log output

```console
[{"node_twin_id":12187,"id":"0000:01:00.0/10de/2684","vendor":"NVIDIA Corporation","device":"AD102 [GeForce RTX 4090]","contract":0}]
```

**Comment by Nelson361** [comment]
Note: this is now node 6765.  Bug seems to persist.

**Comment by Nelson361** [comment]
Node now shows in GPU list, but additional fee does not.

**Comment by Omarabdul3ziz** [comment]
- appears that node 6765 is not rented https://gridproxy.grid.tf/nodes/6765. also, it is listed as available for rent on the `dedicated machines` page on the dashboard
- noticing that in order to find the node in the deployer on the dashboard, gridproxy will be requested with filters `has_gpu=true&rented_by=3309`. 
 that is because the node must be rented by you in order to be accessible in the deployer.

please, try reserve the node first from `dedicated machines` page on the dashboard

**Comment by Nelson361** [comment]
The node works fine and can be rented. The issue is my additional fee is not being displayed on the dashboard.

**Comment by Omarabdul3ziz** [comment]
regarding this part, `extra_fee` is recently added to the total price of the node [feature ticket](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2464) but it is still on dev didn't reach main net

**Comment by khaledyoussef24** [comment]
the node now seems to be down and has 0 GPUS attached


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d2b6ec03-b4de-4580-873c-b68859d15ea8)

I think issue has to be up to check fpr the additional fees and if the gpu is still connected

**Comment by Nelson361** [comment]
Yes, I had to take it elsewhere to rent it out until the gpu marketplace
here was fully built out.
