### ISSUE TITLE
🐞 [Bug]: Decimal values not allowed for RAM in pricing calculator

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2547]
The pricing calculator does not allow me to enter decimals into the RAM value:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/d407e230-1514-4d6d-bfc6-e68587fe894d)

**Comment by zaelgohary** [comment]
Work completed:

Changed rules to accept decimals & edited min value to .5.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4
ram is the only field which user can use decimals and working fine

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9d4579ad-4b81-4330-8aee-8c5976e8827f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/30263354-9645-468a-97b9-240e7d92ccdb)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4213523)
