### ISSUE TITLE
[Mainnet]Show cost per hour when GPU only is toggled

### ISSUE THREAD

**Issue by Nelson361** [threefoldtech/tfgrid-sdk-ts#2548]
### Is your feature request related to a problem? Please describe

GPU's rates are normally calculated per hour, not per month.

### Describe the solution you'd like

When the GPU search is toggled in the dedicated server explorer, add a column for per hour pricing, or swap the per month pricing to per hour.

**Comment by Mahmoud-Emad** [comment]
@samaradel 
This should be done in the `Node Finder` page, since the dedicated nodes page will be deleted.

**Comment by samaradel** [comment]
### Work Completed:
Display node price in ```USD/Hour``` in node finder page

**Comment by khaledyoussef24** [comment]
verified on mainnet
version 2.4.2
when the node has gpu attached to it the rate converts to be hourly.
but when the node is without gpus the rate is monthly


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b303bbcd-5842-4593-8ab6-8c98562f67f6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3e8388db-6ac1-452a-af78-6c9c7464db17)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4288616
