### ISSUE TITLE
🐞 [Bug]: Accepting the terms button does not work

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried to create a new user on devnet but the button of accepting the terms does not work.
while the go back button is working

### Steps To Reproduce

go to the dashboard try to create new account

### which network/s did you face the problem on?

Dev

### version

f1e3728

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1a7f8a83-a80c-4a08-a032-a76b42bd3246
<img width="1680" alt="Screenshot 2024-04-14 at 9 50 47 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39480b85-f5f6-457c-b770-63cc0e11a056">

### Relevant log output

```console
NA
```

**Comment by khaledyoussef24** [comment]
the issue that the button is not responsive I tried again with a zoom out and worked fine

**Comment by Mahmoud-Emad** [comment]
I believe the issue occurred because we are currently checking if the user reaches the end of the screen by comparing the screen height with the element height. To address this, I suggest first checking if there is any overflow.

**Comment by zaelgohary** [comment]
@khaledyoussef24 I tried to reproduce the issue but even when the screen is zoomed in to 175%, the button remains enabled.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e1da7597-4573-4ec9-bac8-a936cf6dadbc)

**Comment by khaledyoussef24** [comment]
issue is only reproducible under certain circumstances.

**Comment by khaledyoussef24** [comment]
opening the page with a 150% zoom or more and the button is stuck but if opened regularly and zoomed in it works fine you return the zoom

**Comment by zaelgohary** [comment]
@khaledyoussef24 I tried reporducing the issue as explained but the button worked just fine.

[ATC.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4ed8aaa5-ce20-4f9e-a888-929411357f55)

**Comment by khaledyoussef24** [comment]
I reproduced the issue again in mac as opening for the first time.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/93288479-3d96-4f0b-b0d3-d46a5205a3ff
we may check if it exists again on another mac device.
if it occurs for the user in the first page in our dashboard it may be an issue.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ff9d79e
working fine now

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/29aa3f35-ebc5-44e6-9504-2b8c35d05c9a

**Comment by khaledyoussef24** [comment]
worked fine with normal page zoom (100%)


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/39dc34c6-7d05-4080-8ded-062583cf82cf

still if the user from the beginning of the session is on 90% may face it

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/28638065-fd8c-4772-b07d-f28932d10204

**Comment by khaledyoussef24** [comment]
i think it may be closed if the case is not for all mac devices

**Comment by zaelgohary** [comment]
Work completed:

Changed the behavior of the onScroll function to enable the accept T&C button whenever it appears in the viewport.

**Comment by khaledyoussef24** [comment]
issue solved perfectly 
verified on devnet
tested from 75% to 200 % and worked fine

<img width="1680" alt="Screenshot 2024-04-28 at 2 17 52 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/44662aa9-1047-4c37-91f1-348b816efc21">
<img width="1680" alt="Screenshot 2024-04-28 at 2 18 03 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3ef6ea8c-5658-4fb3-af2d-bf724aabb9bf">
<img width="1680" alt="Screenshot 2024-04-28 at 2 18 29 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/00976a7d-0551-43dd-943d-73418db76de7">
<img width="1680" alt="Screenshot 2024-04-28 at 2 18 46 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a5578a7c-3beb-4afc-8e47-067387b1a160">
<img width="1680" alt="Screenshot 2024-04-28 at 2 19 04 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a7317847-53cc-4b38-b8f4-9867b8f7731b">
