### ISSUE TITLE
Incorrect resource packages for multiple solutions

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#255]
### Description

The resource packages for multiple solutions are incorrectly configured.

### Caprover

according to the [docs](https://manual.grid.tf/weblets/weblets_caprover.html#usage) the packages should be:

```
Minimum: {cpu: 1, memory: 1024, diskSize: 50 }
Standard: {cpu: 2, memory: 1024 * 2, diskSize: 100 }
Recommended: {cpu: 4, memory: 1024 * 4, diskSize: 250 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/c63a40bd-9a51-4b80-9241-98eb17f2fb32)

### Funkwhale

according to the [docs](https://manual.grid.tf/weblets/weblets_funkwhale.html#funkwhale) the packages should be:

```
Minimum: {cpu: 2, memory: 1024, diskSize: 50 }
Standard: {cpu: 2, memory: 1024 * 2, diskSize: 100 }
Recommended: {cpu: 4, memory: 1024 * 4, diskSize: 250 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/f02acf2d-745e-46dd-9f2e-038e55f527b0)

### Mattermost

according to the [docs](https://manual.grid.tf/weblets/weblets_mattermost.html#mattermost) the packages should be:

```
Minimum: {cpu: 1, memory: 1024 * 2, diskSize: 10 }
Standard: {cpu: 2, memory: 1024 * 4, diskSize: 50 }
Recommended: {cpu: 4, memory: 1024 * 4, diskSize: 100 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/81530523-ac1b-47c5-b925-cebb905c6388)

### Discourse

according to the [docs](https://manual.grid.tf/weblets/weblets_discourse.html#discourse) the packages should be:

```
Minimum: {cpu: 1, memory: 1024 * 2, diskSize: 10 }
Standard: {cpu: 2, memory: 1024 * 2, diskSize: 50 }
Recommended: {cpu: 4, memory: 1024 * 4, diskSize: 100 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/a8d84fe2-ccc3-42a4-b0af-c202335ea380)

### Taiga

according to the [docs](https://manual.grid.tf/weblets/weblets_taiga.html#taiga) the packages should be:

```
Minimum: { cpu: 2, memory: 1024 * 2, diskSize: 100 }
Standard: { cpu: 2, memory: 1024 * 4, diskSize: 150 }
Recommended: { cpu: 4, memory: 1024 * 4, diskSize: 250 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/7a0797cb-4d5e-46f6-a41b-71e0fa64fe72)

### ownCloud

according to the [docs](https://manual.grid.tf/weblets/weblets_owncloud.html#owncloud) the packages should be:

```
Minimum: { cpu: 2, memory: 1024 * 16, diskSize: 250 }
Standard: { cpu: 2, memory: 1024 * 16, diskSize: 500 }
Recommended: { cpu: 4, memory: 1024 * 16, diskSize: 1000 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/595599be-3fcf-476f-8ef9-a57ab0b54668)

### Subsquid

according to the [docs](https://manual.grid.tf/weblets/weblets_subsquid.html#process) the packages should be:

```
Minimum: { cpu: 1, memory: 1024 , diskSize: 50 }
Standard: { cpu: 2, memory: 1024 * 2, diskSize: 100 }
Recommended: { cpu: 4, memory: 1024 * 4, diskSize: 250 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/e6782696-5f18-4b9b-992f-6011b81b71ff)

### Casperlabs

according to the [docs](https://manual.grid.tf/weblets/weblets_casper.html#casperlabs) the packages should be:

```
Minimum: {cpu: 1, memory: 1024 * 4, diskSize: 100 }
Standard: {cpu: 2, memory: 1024 * 16, diskSize: 500 }
Recommended: {cpu: 4, memory: 1024 * 32, diskSize: 1000 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/8552b40e-02b4-4302-8beb-012df4df91c1)

### Wordpress

according to the [docs](https://manual.grid.tf/weblets/weblets_wordpress.html#wordpress) the packages should be:

```
Minimum: { cpu: 1, memory: 2048 , diskSize: 10 }
Standard: { cpu: 2, memory: 2048 , diskSize: 50 }
Recommended: { cpu: 4, memory: 4096 , diskSize: 100 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/7b7ceb6a-c56f-42af-ba19-f08ae4b12d76)

### Umbrel

according to the [docs](https://manual.grid.tf/weblets/weblets_umbrel.html#umbrel) the packages should be:

```
Minimum: { cpu: 2, memory: 2048 , diskSize: 10 }
Standard: { cpu: 2, memory: 4096 , diskSize: 50 }
Recommended: { cpu: 4, memory: 4096 , diskSize: 100 }
```
and currently they are

![image](https://github.com/threefoldtech/playground/assets/101194226/b85332fb-8446-435e-a0f5-d1af84cce848)

**Comment by 0oM4R** [comment]
Status: pr #351 ready for review
