### ISSUE TITLE
🐞 [Bug]: the email field takes time to load

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The email field takes long time to load and shows the old email when entering the twin page.

The only way is to refresh the page.

### Steps To Reproduce

1. Navigate to the dashboard.
2. Connect your wallet.
3. After logging in, check your email on the twin page.
4. Logout.
5. Connect your wallet again, but with a different email.
6. Check your email again; you will see the same old email, not the new one (you have to refresh to reload).

### which network/s did you face the problem on?

Dev

### version

f3e199e

### Relevant screenshots/screen records

[screen-capture (25).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/abf436e9-99b9-441c-8dc6-82fbcccc3d62)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work in Progress (WIP):

It's about when the user logout and login again on ``` your profile``` page with changes in data (email) it doesn't update the UI, trying some fixes

**Comment by samaradel** [comment]
### Work Completed:
Fix the email view in the profile page
