### ISSUE TITLE
🐞 [Bug]: validating gateway in adding ip range is not functional

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

we should not add the same ip as a gateway ip, in ip range; the validation happens on start ip and end ip only 
but if we add the gateway ip as one of the ips in the entered range (but not start or end ips) no validation error, but the request will fail 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/6b4ff066-d729-4070-8221-53d410409673)

### Steps To Reproduce

- go to your farms page on dashboard
- select one of your farms and add click on `add ip` button 
- select range mode and enter `125.25.25.1\16` as start ip 
- enter `125.25.25.3\16` as end ip 
- gateway `125.25.25.2`

### which network/s did you face the problem on?

Dev

### version

2.3.5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d19a9915-d9d2-4015-87c3-59abfb559d21)
![Screenshot from 2024-04-15 12-10-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4e030cf7-80c6-4d09-a779-f47e7051492a)

### Relevant log output

```console
Error: InvalidPublicIP: Failed to apply {"args":{"calls":[{"args":{"farm_id":"4,405","ip":"125.25.25.1/16","gw":"125.25.25.2"},"method":"addFarmIp","section":"tfgridModule"},{"args":{"farm_id":"4,405","ip":"125.25.25.2/16","gw":"125.25.25.2"},"method":"addFarmIp","section":"tfgridModule"},{"args":{"farm_id":"4,405","ip":"125.25.25.3/16","gw":"125.25.25.2"},"method":"addFarmIp","section":"tfgridModule"}]},"method":"batchAll","section":"utility"}
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### work done

#### Changes

- Removed unnecessary watcher
- Added a condition to check if the gateway IP is included in the range or not
- Added a watcher that watches the value of the ip-type selection and removes the values when on-change

#### Screenshots/Video 

[Screencast from 05-07-2024 03:54:45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a23d2af8-5f5c-49c4-829f-470bbff28ddd)

**Comment by A-Harby** [comment]
Verified, Devnet 0d1e63f.

The gateway input now has a validation that verifies that the gateway can't be the same as from IP to IP or the range between them.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b8797660-09fa-4dc3-a07c-ae9dc4066b13)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c5392539-d9f2-43e7-bcd9-0fa8fe7ee021)

[TC2208 - Add Multiple IPs to a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150417)
