### ISSUE TITLE
Wordpress: Broken instance and admin panel links

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#256]
### Description

In the deployment list for wordpress both of the buttons that redirect to the instance and the admin panel redirect to incorrect links.

There's an extra `http//` in both links.

![image](https://github.com/threefoldtech/playground/assets/101194226/f020cb9f-c0ee-41db-a3cd-4ab79b2e73fb)

![image](https://github.com/threefoldtech/playground/assets/101194226/58cbcc8f-6fb8-4c4e-be42-5212d02df0d8)

![image](https://github.com/threefoldtech/playground/assets/101194226/538b2341-539b-41bf-9b03-da3eeb30f232)

**Comment by 0oM4R** [comment]
investigating, also the vm is not accessible via ssh

**Comment by mohamedamer453** [comment]
> investigating, also the vm is not accessible via ssh

Just to clarify this issue was related to redirecting to the incorrect url as seen in the pics.

but when the extra `http/` was removed from the url the instance worked fine

**Comment by 0oM4R** [comment]
now the extra http/ is removed but the response is bad gw 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4135e9b7-1bb1-4bc5-a497-26d407a3bb80)

**Comment by 0oM4R** [comment]
that was due invalid entry point, will open an issue to check all solution entrypoints

**Comment by 0oM4R** [comment]
should be fixed in #359

**Comment by A-Harby** [comment]
Verified, playground Devnet, 861c5f8.
extra http was removed and redirect is correct.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a4ef844c-0bc7-49d7-acd7-fa67da0c4eb2)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8881d7bf-3bd4-4967-853b-cc21743cb991)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5f78e53a-9bf1-461c-bafc-add30aa9a825)
