### ISSUE TITLE
🐞 [Bug]: validation message says ip range must not exceed 16 but allow to add up to 17

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#2560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

validation message says ip range must not exceed 16 but actual validation allows you to add up to 17

### which network/s did you face the problem on?

Dev

### version

2.3.4

### Relevant screenshots/screen records

![Screenshot_20240415_154926](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/42457449/8f634915-dca7-4ac0-baf4-7a969b21bb7f)

### Relevant log output

```console
NA
```

**Comment by Mahmoud-Emad** [comment]
This issue reported in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2400
