### ISSUE TITLE
Easy way to delete range/set of IPs

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#2561]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Dashboard allows you to add a range of IPs. Would it be possible to allow the selection of a set of IPs for deletion instead of going through them one by one?
I understand that this task may not be an everyday one, but making it easier will help users appreciate the flawlessness when it comes time to use it.

### Describe the solution you'd like

I think adding a standard checkbox for every IP and allowing one to select/deselect all checkboxes would be a nice UX  improvement. 
![Screenshot_20240415_155418](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/42457449/e0f71288-6b15-437e-a74c-578d5d98f2d8)

**Comment by samaradel** [comment]
### Work Completed:
Remove the delete button and add delete all action

**Comment by samaradel** [comment]
### Work Completed:
Some code enhancement as per pull request comments

**Comment by samaradel** [comment]
Work Completed:
Create ```removeFarmIps``` function to delete all ips in one action

**Comment by samaradel** [comment]
### Work in Progress (WIP):
Working on [PR comment](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2593/files#r1582859973)

**Comment by samaradel** [comment]
### Work in Progress (WIP):
faced some issues while build , still investigating ..

**Comment by samaradel** [comment]
### Work Completed:
Add ```removeFarmIps``` function in tf grid

**Comment by samaradel** [comment]
### Work Completed:
- Document ```removeFarmIps``` methods.

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2610#issuecomment-2111933541

**Comment by samaradel** [comment]
### Work in Progress (WIP):
investigating..

**Comment by samaradel** [comment]
### Work Completed:
Fix farms public IPs table selection by removing the current ```data-table``` and passing props to ```list-table``` component.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 85a6fa4
a standard check box is now added to the ip table to make deleting a contract or multiple contracts easier


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b0725e82-9674-416c-8a9c-2ef3fbf44ce9)
