### ISSUE TITLE
🐞 [Bug]: Normalize the virtual machine subdomain

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The subdomain is too long

### Steps To Reproduce

1. Go to the [Dashboard](https://dashboard.dev.grid.tf/)
2. [Deploy a virtual machine](https://dashboard.dev.grid.tf/#/deploy/virtual-machines/full-virtual-machine/)
3. Try to attach a subdomain to it

### which network/s did you face the problem on?

Dev

### version

2.3.4

### Twin ID/s

143

### Node ID/s

NA

### Farm ID/s

NA

### Contract ID/s

NA

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/d07747b1-d656-4f49-b24a-3295c3ad1706)

### Relevant log output

```console
NA
```

**Comment by sameh-farouk** [comment]
Can users choose a subdomain without a prefix, if the name is not reserved? If not feasible, we can start with the user's chosen name and add a suffix afterward.

**Comment by ramezsaeed** [comment]
@sameh-farouk 
I think the prefix is important even for the user himself; so he can relate this domain to his solution.
in case the user has multiples VMs with multiple domains; it will be easier to know which domain related to which VM with the prefix.

**Comment by zaelgohary** [comment]
Work completed:

Removed twinId & solution name and edited subdomain char limit to 5 instead.

**Comment by zaelgohary** [comment]
WIP:

Reverted previous changes and currently working on combining both the prefix and the subdomain as a name and allow the user to edit both. However, a validation would be triggered to check if a name contract exists with the same name or not to avoid post-deployment errors.

**Comment by zaelgohary** [comment]
Work completed:

Created a validation rule to check if a name contract with the same name exists on the chain or not. Edited the subdomain to include the prefix by default and changed the max limit to 15 instead of 35. Also, edited the subdomain tooltip and the name in the table accordingly.

**Comment by A-Harby** [comment]
After creating a domain, the same name validation isn't working.

Maybe you should randomize naming every time dialogue is reopened. 
[screen-capture (3).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6164f257-fc36-48ed-a3fb-7e2d7b39cb55)

**Comment by zaelgohary** [comment]
Work Completed:

Validate subdomain if tab is changed, change tab condition to v-if instead of v-show so the validation condition to work.

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.
The domain name is now validated with a minimum of 4 characters and a maximum of 30 characters, as well as validation for the same domain.
And the name given to the domain is a combination of solution type, twin ID, solution name, and a random character. 
For the domain input size, I reported it separately here: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2842.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/480175b5-9bed-4020-b580-b5b0fd040f50)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0283f015-3df2-4fdb-a1a1-2e55a9c662f8)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d20b0dde-2fd5-40b6-8fd7-974f3d178d0a)

[TC2124 - Add gateway to a vm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150333)
