### ISSUE TITLE
Review the solutions domain, it needs to be shorter

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2571]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

it's a part of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2564

### Describe the solution you'd like

The solutions domain needs a review to check the generated domain name, it should be only the solution prefix + the solution name.

**Comment by zaelgohary** [comment]
Should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2573)

**Comment by A-Harby** [comment]
Verified, in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2564#issuecomment-2145285755.
The name given to the domain is a combination of solution type, twin ID, solution name, and a random character.
