### ISSUE TITLE
🐞 [Bug]: RAM utilization of node shown as greater than 100%

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

RAM utilization for node 6400 is shown as greater than 100%, which shouldn't be possible.

### which network/s did you face the problem on?

Main

### version

 2.3.4

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/04735179-0ac1-485f-acb6-bdff1163d685)

### Relevant log output

```console
NA
```

**Comment by Mahmoud-Emad** [comment]
Closed as reported in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2591
