### ISSUE TITLE
Delete the dedicated nodes page

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2575]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

As now we support the most of dedicated node features in the node finder page we should delete the whole page after ensuring that nothing is missed

### Describe the solution you'd like

Delete the page

**Comment by Mahmoud-Emad** [comment]
Should solve [this](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2576) first

**Comment by Mahmoud-Emad** [comment]
We have to ensure that nothing is missed, also we want to delete everything related `functions`, `components`...etc

**Comment by zaelgohary** [comment]
Work completed:

Remove the dedicated page & route.

**Comment by khaledyoussef24** [comment]
page removed and no longer found on devnet enviroment
version : dd92950

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/06aabf4d-a129-4800-b6a6-8f8e6b55e5b3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/90d6500e-6f21-471f-bc3d-23b4cc3a7bd2)

**Comment by khaledyoussef24** [comment]
redirection from dedicated nodes page to node finder is not working

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/881233c8-dcfd-401b-b3df-014c5941a577)

**Comment by zaelgohary** [comment]
Changed the checked route to be any route includes 'deploy/dedicated-nodes' as the browser might autocomplete the URL .

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : e1cdba0
page deleted and now redirects to node finder

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/65a03a4b-7016-45b5-96d9-a16cef247ef2

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- e7030e6
