### ISSUE TITLE
Include the discount price info in node finder

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2576]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The discount price info should be included in the node finder page as in the dedicated page.

### Describe the solution you'd like

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/7c8a948f-0de0-4665-a096-4f11d8c4a299)

**Comment by zaelgohary** [comment]
WIP:

Added the tooltip with dynamic text to show whether it's rented by the user or someone else. Currently working on adding user staking discount.

**Comment by zaelgohary** [comment]
Work completed:

Added staking discount,

**Comment by khaledyoussef24** [comment]
verified on devnet
version : e1cdba0

tooltip showing the discount info is now shown


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/83c9448e-3695-4344-8642-2b03a5f32fb3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1b194bca-4490-4ece-a4ff-f8e701036a01)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4264048
