### ISSUE TITLE
🐞 [Bug]: Search on your farm page only search on the first page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2578]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Search on your farm page; only search for the farm name or ID on the first page.

### Steps To Reproduce

1. Create more than 10 farms.
2. Search for a farm name or ID from the second page table.

### which network/s did you face the problem on?

Dev

### version

b895f6e

### Relevant screenshots/screen records

[screen-capture (27).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6a170f1c-5878-4ebe-a2f2-ca29cd990f73)

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Work completed:

Added nameContains query to queries list before getting farms & removed old filter function.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3d3d5646-1f99-4b74-8f0d-c92b94b9cd08)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d69dde72-ab83-4f9c-9fcf-046a620d279d)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150415)
