### ISSUE TITLE
Dashboard Incorporate view of bootstrap page

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2584]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

When we are on the Dashboard and click the bootstrap button, it opens a new page on the browser. We could have a view of the bootstrap page within the Dashboard.

### Describe the solution you'd like

Incorporate the bootstrap page within the Dashboard.

**Comment by Mahmoud-Emad** [comment]
The IFrame isn't provide the best UX and no need to load the page in IFrame, please if you have another reason to implement this feature comment.

**Comment by Mik-TF** [comment]
I just think it's good to have as much features of the dashboard within the dashboard, without needing to leave. As I tested it was fully functional (could download bootstrap images).

If you don't think it's useful, we don't have to add this.

**Comment by Mahmoud-Emad** [comment]
It's important to acknowledge that iframes may not fully replicate the functionality of browser tabs.

**Comment by xmonader** [comment]
> It's important to acknowledge that iframes may not fully replicate the functionality of browser tabs.

I agree, I don't think we should have it, it's also very inconsistent too in the style. Thanks @Mik-TF
