### ISSUE TITLE
🐞 [Bug]: Farm name creation validation isn't working correclty

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

You can't create a farm name that already exists, and the validation is working correctly.
But when the farm isn't listed on the table, like in the video, or is listed on another page, the validation will not work.

### which network/s did you face the problem on?

Dev

### version

1272141

### Relevant screenshots/screen records

[screen-capture (28).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/340da192-3d86-4ab1-94b5-c82aaeaddb97)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified and working fine now
tried to search for a farm which is existed already but which is not on my table
version : 2b7ab4e

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7201b6e3-ad3e-4ff8-afa3-c6716f46c87f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dabdbed5-183e-4f64-979a-24ebf369270d)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4289466
