### ISSUE TITLE
🐞 [Bug]: Check the equation of calculating the resources of the node

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Node [131](https://gridproxy.dev.grid.tf/nodes/131) ram unit is 145% which is not a valid result

Here is the equation 

```ts
const sys = 2147483648
const total = 3138523136
const used = 2415919104
const res = (sys + used) / total
res * 100 
```

### Steps To Reproduce

1. Go to [dashboard](https://dashboard.dev.grid.tf/#/)
2. Go to [Node Finder](https://dashboard.dev.grid.tf/#/deploy/node-finder/?node-id=131) page and search for node 131
3. Check it's ram unit

### which network/s did you face the problem on?

Dev

### version

1.3.4

### Twin ID/s

143

### Node ID/s

131

### Relevant screenshots/screen records

-![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/cdc44628-d4f7-4387-9678-9e7fc86e25d4)

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/bb8179a2-41eb-4c65-9e71-be84c3ee43a9)

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/fe2629af-3f75-4ecc-9a41-f91aca9dcd9c)

### Relevant log output

```console
N/A
```

**Comment by A-Harby** [comment]
Verified, Devnet 0139c63.

The resource calculations are unified both on node cards and on node details.

Node 131.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e4f9141-2d70-4cfc-814e-27041eae07b5)
Other nodes behave similarly, whether they have full resources or are empty.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8f777148-d6b8-4d70-b6f8-b2e7e3a39734)

[TC2250 - Nodes Cards Table Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459)
[TC2251 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460)
