### ISSUE TITLE
Node_Pilot Add Capacity Custom Level

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#2597]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

When running a Node Pilot instance, a farmer reported the following error:

![Low disk space_Node Pilot](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/a70d5d0c-a9cf-4afc-a100-47445d095ea0)

Farmer is intending to run a BTC node and requires at least a 2tb disk.

### Describe the solution you'd like

Upon further research it appears the Node Pilot instance does not currently have the feature to set up the SSD capacity (custom capacity level) or adding a disk.

Can this be added similar to the Algorand solution?

**Comment by zaelgohary** [comment]
Work completed:

Added custom capacity flavors as per the [Hardware Recommended](https://docs.decentralizedauthority.com/master/hardware-recommendations). Also, user can customize his own capacity resources if he wishes.

**Comment by khaledyoussef24** [comment]
Will this also be added to algorand as 2tera storage ?

**Comment by zaelgohary** [comment]
> Will this also be added to algorand as 2tera storage ? As requested?

Regarding Algorand, I opened an issue for updating its resources [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2915)
