### ISSUE TITLE
clean key-val store script does not work properly

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/tfgrid-sdk-ts#26]
running the clean key-val store script keeps logging unuseful information if the store has too many pairs.
![Screenshot from 2022-03-20 12-43-24](https://user-images.githubusercontent.com/32527347/159158805-fdc94aa2-a540-4b36-9287-c7499c23e32c.png)

However, it deletes all the pairs at the end if you were patient enough to keep it running.
![Screenshot from 2022-03-20 12-53-15](https://user-images.githubusercontent.com/32527347/159158881-decf2088-65c0-43eb-8695-7e200db4fee9.png)

**Comment by AhmedHanafy725** [comment]
grid client now supports deleting keys using batch call

**Comment by AhmedHanafy725** [comment]
> This is normal, the client deletes them one by one, then list the deleted keys at the end. But the real problem is why this leak happens?! deleting the contracts or deployments should remove all related keys.

the key-value store is not used anymore for listing the deployment. so no more leaks
