### ISSUE TITLE
Remove minting alert

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2600]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Remove minting stops at 1 billion alert

### Describe the solution you'd like

-

**Comment by zaelgohary** [comment]
Work completed:

Removed alert from minting page.

**Comment by A-Harby** [comment]
Verified, Devnet e7030e6.

The Minting alert is removed from the simulator page.
Old alert.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d4264ae1-fc1a-49ba-b4bc-d05532493a0c)
After removing it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d70b75e2-b31b-4c63-acc9-4f33e5ab5530)
