### ISSUE TITLE
🐞 [Bug]: Delete IPs should be reflected on the farm IPs table

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Deleting the IPs from a farm isn't applied to the table until a refresh, not like adding, which is applied instantly.

### Steps To Reproduce

1. Navigate to the Dashboard.
2. Connect your account.
3. Navigate to your farm page.
4. Create a farm.
5. Add IP to it.
6. Delete that IP (it will not be gone without a refresh).
7. You could delete it again, and it will give an error.

### which network/s did you face the problem on?

Dev

### version

e7030e6

### Relevant screenshots/screen records

[screen-capture (30).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/38fb7961-4910-4de8-ac2b-8a89f2e99133)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2561 should solve this one

**Comment by Mahmoud-Emad** [comment]
What is the status here?

**Comment by samaradel** [comment]
resolved with [#2593](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2593)

**Comment by A-Harby** [comment]
Devnet, 71a3b1a.

The selection isn't working correctly, it select/unselect all.
and the deletion is failing.

[screen-capture (2).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4b384494-2428-4d7d-a9dc-b64a5f89319b)

**Comment by samaradel** [comment]
related to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2561

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.

The IP deletion is now working fine with selection one or more IP, and it's reflected instantly on the table.

[screen-capture (8).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b8d0a695-7768-45c8-a958-52323fa18f63)

[TC2209 - Delete IP](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150418)
