### ISSUE TITLE
🐞 [Bug]: SSH Key disappeared when I selected them with light mode on

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

In the manage the ssh key dialogue, when I select an ssh key, it disappears in light mode.

### which network/s did you face the problem on?

Dev, QA

### version

2.4.0-rc1

### Relevant screenshots/screen records

[screen-capture (31).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/994856a0-d4a3-4fd6-9468-5e8820edde1e)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done

- Used the AppThemeSelection to get the current theme and use the colors that fit the theme instead of making it with hard value for both themes

**Comment by khaledyoussef24** [comment]
verified on devnet
version : d2e641f


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2f298f0f-afd6-4ac3-9e33-86150ae1c0de)




https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4270412
