### ISSUE TITLE
🐞 [Bug]: email is not auto-filled in solutions 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

While creating a new user the email address is needed to be filled.
While using the dashboard and trying to implement a solution which needs an email or email server it is not used.

### which network/s did you face the problem on?

Dev, QA

### version

2.4.0

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-04-28 at 10 02 06 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7f271775-627c-42cd-8830-35f1b0104dcf">

### Relevant log output

```console
na
```

**Comment by xmonader** [comment]
shouldn't be a blocker and probably should still be filled manually by the user

**Comment by Mahmoud-Emad** [comment]
Could be an optional field with `Switch-Component` `Use my wallet email` to give the user the ability to use the wallet email or enter another email

PS

When the user select the wallet email the email field should be disabled

**Comment by zaelgohary** [comment]
Already done [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/61113bbb026a3ea42d974d7dc693fd9d20408c99)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 6f39878


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d01c5a86-e41e-4188-b0b1-669b4306d89a)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0d4bb2fd-fac1-43e7-810e-cbfec98db823)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/05d95d7b-c240-4642-87cb-5b0aa596a479)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3662b8f6-c0fc-48b9-a19a-ce58a792f64b)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4310129
