### ISSUE TITLE
[Mainnet]🐞 [Bug]: Rentable filter in node finder shows all dedicated nodes

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2143

should not the rentable filter shows only nodes which allows to be rented (up and stand by only) 

### which network/s did you face the problem on?

QA

### version

2.4.0

### Relevant screenshots/screen records

<img width="1083" alt="Screenshot 2024-04-28 at 5 26 23 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99df53e8-4b3e-465c-80c8-6a7f2b517504">
<img width="181" alt="Screenshot 2024-04-28 at 5 26 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/01d44f85-cb8a-4843-baf8-08654d6069a2">

### Relevant log output

```console
na
```

**Comment by khaledyoussef24** [comment]
The rentable filter shows all nodes that are rentable and does not exclude the nodes that are down

show rentable should only show
- up or stand-by nodes.
- ready for renting nodes (not rented by another user).

**Comment by khaledyoussef24** [comment]
in that case the dedicated filter is already there.

<img width="196" alt="Screenshot 2024-05-01 at 10 41 22 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/af1556c0-55b1-4d6f-9dd7-c698eabf901f">

**Comment by A-Harby** [comment]
Testnet, 2.4.0.

I tried to search for dedicated nodes, and with the up status, I found a few nodes, all of which were rentable.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c7a6b0c7-f690-4ccb-a060-da89929524f6)
Then I switched to rentable and up status, but I only found 1 node despite having more, as you can see in the picture above.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/804c5bfe-0d68-45d7-9ce3-35056b061b78)

And the same happened on other status, so is it a bug ?
And the difference between dedicated and rentable is very confusing.

**Comment by 0oM4R** [comment]
@A-Harby resolved on #2960

> Testnet, 2.4.0.
> 
> I tried to search for dedicated nodes, and with the up status, I found a few nodes, all of which were rentable. ![image](https://private-user-images.githubusercontent.com/109473873/329843588-c7a6b0c7-f690-4ccb-a060-da89929524f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTU5NzUsIm5iZiI6MTcyMDAxNTY3NSwicGF0aCI6Ii8xMDk0NzM4NzMvMzI5ODQzNTg4LWM3YTZiMGM3LWY2OTAtNGNjYi1hMDYwLWRhODk5Mjk1MjRmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjE3YThkM2NiYmI5ZDA3ODU1ZWJjOTFlYTM4NjJlODkwM2YwNWU5NTE2NzFiOWQ1NjVmOTY1YzIxZjFkYWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.09d-yRTMdCXUBWYjH_iaqpAjj2poUwFxR8XFj_ExI_g) Then I switched to rentable and up status, but I only found 1 node despite having more, as you can see in the picture above. ![image](https://private-user-images.githubusercontent.com/109473873/329843691-804c5bfe-0d68-45d7-9ce3-35056b061b78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMTU5NzUsIm5iZiI6MTcyMDAxNTY3NSwicGF0aCI6Ii8xMDk0NzM4NzMvMzI5ODQzNjkxLTgwNGM1YmZlLTBkNjgtNDVkNy05Y2UzLTM1MDU2YjA2MWI3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QxNDA3NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDQ4MzUwODYyMGI5Zjc5NjUwMTkwYjNmMmJlNTVlYzI0Mjk4ZWIyZGY2MWQwNWFlMmYyNjA1NWJmMThiNmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gE8Ey359WBIGK_O1Eqw8RbsZKFBiZXnNaHGKRiTIj0U)
> 
> And the same happened on other status, so is it a bug ? And the difference between dedicated and rentable is very confusing.

**Comment by 0oM4R** [comment]
#### Issue update
**work completed** :
introduce new flow for this toggle:

- if the Status filter is not selected ->> the status filter will be updated to Up and Standby
- if the Status filter has any value -> nothing new happen, will keep it as it is

[Screencast from 03 يول, 2024 EEST 07:13:56 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/a89f2161-b2fd-442f-9a0b-5270a417ad53)
@ehab-hassan what do you think about this flow?

**Comment by ehab-hassan** [comment]
"As we discussed with @AhmedHanafy725 and @0oM4R, 'Rentable' means that the user needs to reserve an 'Up' or 'Standby' node. Therefore, let's freeze the 'Select Node Status' field to 'Up' and 'Standby' when the 'Rentable' toggle is active."

**Comment by khaledyoussef24** [comment]
verified on mainnet
Version 2.6.0
Rentable now when toggled is automatically shows dedicated nodes with status up and standby
![Image](https://github.com/user-attachments/assets/5b53b642-d413-4a56-a6e3-177eba6ebfeb)
![Image](https://github.com/user-attachments/assets/800bd3c4-66d6-40e2-8452-6def48974ff0)
![Image](https://github.com/user-attachments/assets/04ee5e15-dea9-466e-b561-7b8ec32a360c)
 [testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4263741)
