### ISSUE TITLE
Taiga: Deployment details improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#262]
### Description

The deployment data for Taiga needs some improvements.

-  All of these fields should be the same size as the other fields.
- The content of the Admin Password field should be hidden by default.
   
   ![image](https://github.com/threefoldtech/playground/assets/101194226/f729b674-f985-4803-a159-bd5a31cfc2d4)

- Email/SMTP Fields shouldn't appear if they're not used.
- If they include data then their size should be the same size as the other fields.
- Email Host Password field should be hidden by default.

   ![image](https://github.com/threefoldtech/playground/assets/101194226/645bf730-6054-4eb8-86f6-3e14012f79de)

**Comment by A-Harby** [comment]
Input fields sizes are normal and fits the inputs.
admin password and email host password are now hidden.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/60224cfe-b20e-43be-89e2-477955c522fe)
And stmp/email inputs fields are not shown unless toggle is enabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/820211f0-6415-4ee1-94ae-3145d53c3d0c)
