### ISSUE TITLE
🐞 [Bug]: Gateway contract isn't deleted after deleting CasperLabs instance

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After deleting a Casper Labs instance from its solution page, I found a contract of gateway type wasn't deleted.

https://github.com/threefoldtech/tf-images/issues/226#issuecomment-2081513550

### which network/s did you face the problem on?

QA

### version

2.4.0-rc1

### Twin ID/s

52

### Node ID/s

3

### Farm ID/s

1

### Contract ID/s

27305

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a273d2b8-76c4-4032-b6ec-07aa69182c55)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b2fd2fee-7cbc-4285-b01c-0224bb03edc6)

### Relevant log output

```console
{
  "version": 0,
  "twin_id": 52,
  "contract_id": 27305,
  "metadata": "",
  "description": "",
  "expiration": 0,
  "signature_requirement": {
    "requests": [
      {
        "twin_id": 52,
        "required": false,
        "weight": 1
      }
    ],
    "weight_required": 1,
    "signatures": [
      {
        "twin_id": 52,
        "signature": "80bb14dd44dbb0e0b3733fb440360c36ce2d7eade34d4dad1fda0c2f45249a6494650f4ea108e7b0de459ed425f566329e15babb0d66a027c89550b330713780",
        "signature_type": "sr25519"
      }
    ],
    "signature_style": ""
  },
  "workloads": [
    {
      "version": 0,
      "name": "cl52clv2dtc",
      "type": "gateway-name-proxy",
      "data": {
        "name": "cl52clv2dtc",
        "tls_passthrough": false,
        "backends": [
          "http://10.20.4.2:80"
        ],
        "network": "nwkcdiv"
      },
      "metadata": "",
      "description": "",
      "result": {
        "created": 1714306116,
        "state": "ok",
        "message": "",
        "data": {
          "fqdn": "cl52clv2dtc.gent02.qa.grid.tf"
        }
      }
    }
  ]
}
```

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Investigation and Solution:
Indeed, the issue persists. It appears that the project name is not being included in the `solutionHasGateway` function, causing it to return `true` if the solution has a gateway, and false if not. To resolve this, we need to ensure that the project name is properly integrated into the `solutionHasGateway` function's logic.

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done 

Fix deleting the gateway contract in the Casperlabs solution by adding the 'Casperlabs' project name in the solutionHasGateway function.

#### Changes

- added the `Casperlabs` project name in the `solutionHasGateway` function.

#### Screenshots/Video

[Screencast from 05-07-2024 02:12:16 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/4ba77ae7-0e06-4b17-b34b-e5ba480d49d9)

**Comment by A-Harby** [comment]
Verified, Devnet 1b19f4f,

I deployed a few solution instance that use a gateway then deleted them, and wasn't able to reproduce the case again.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ac347604-bb96-4ba0-9a4f-952c4b93ce20)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/87a63ecc-442f-4077-bcf3-63ef4efb3303)
