### ISSUE TITLE
🐞 [Bug]: 0% staking discount while having enough tokens to unlock the gold discount

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Got 0% staking discount while the account has enough tokens to unlock discounts

### Steps To Reproduce

1- Go to the dashboard
2- Open the node finder page
3- Filter the nodes with the rentable filter
4- Hover on the node price (0% discount as the user is not logged in)
5- Connect your wallet that has enough tokens to unlock the discounts. (noting will happen, it will remain 0%)
6- Go to any other page, then go to the node finder again and check the discount. (this time it won't be 0%)

### which network/s did you face the problem on?

Dev

### version

development

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/936a77e3-f178-440b-9493-f3bdb7826307)

### Relevant log output

```console
-
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done 

- Added a loader when loading the value of the discount
- Added a watcher that watches on the profile when connecting the wallet
- Updated the discount when connected to the wallet
- Highlighted the balance value by wrapping it with a 'strong' tag


###  Screenshots/Video

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/50404546-8d44-4eaa-a384-b6f6b13e7579)

- [Screencast from 05-07-2024 11:51:07 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a95d4760-81b9-4406-b7e9-653734263793)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 0139c63
discounts rate are verified while having enough tfts 
on the new account ) without tft)
![Screenshot from 2024-06-09 13-05-12](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/70de6a7c-69ee-4010-9ddd-c84a99b684bb)
![Screenshot from 2024-06-09 13-05-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf135826-2354-46e9-bd6d-5b6aa334fcd5)
on the account with tfts
![Screenshot from 2024-06-09 13-08-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db80812c-9061-4860-a55d-1eac302b884b)
![Screenshot from 2024-06-09 13-08-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ea16063c-e778-457a-b7d9-0d3ed063ba6d)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4264048
