### ISSUE TITLE
🐞 [Bug]: User can not edit ssh key

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

one a user created or import an ssh key he can not edit it or change any field 
- the ssh key
- the name

### which network/s did you face the problem on?

Dev, QA

### version

2.4

### Relevant screenshots/screen records

![Screenshot 2024-04-30 at 5 51 57 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5492d6aa-1e01-4ad8-8587-9031d1990d17)
<img width="1680" alt="Screenshot 2024-04-30 at 11 59 10 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8eefd6c4-4fcc-4210-97b5-6968a7d91818">

### Relevant log output

```console
NA
```

**Comment by AlaaElattar** [comment]
### Work In Progress:
- changed fields to be editable.
- added save button.
- working on error happens because i copy selectedKey from props to track changes done by user.

**Comment by khaledyoussef24** [comment]
fixed and verified on devnet
version : 2b7ab4e
field is editable and even you can not change ssh to another created one


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/78fc58a6-3850-4489-8980-0d53865bd0c4)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c82b41ee-1ef4-4774-93d9-95379625acf3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9244443b-f69c-465f-bf52-8eb947b47075)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4293756
