### ISSUE TITLE
Remove "Only" from Node Finder filters

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2629]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

It seems repetitive and unnecessary.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/1658c179-d5b4-49b7-a9e7-e17dc23361fa)

### Describe the solution you'd like

Remove "Only" from Node Finder filters

**Comment by zaelgohary** [comment]
Work completed:

Removed only from node finder filters.

**Comment by A-Harby** [comment]
Verified, Devnet.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/554c79c8-4df4-4d05-97ba-210176e3342a)
