### ISSUE TITLE
🐞 [Bug]: Mnemonics not autofilled after account creation in profile manager if there is browser autofill

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

In the profile manager, when I empty the mnemonics field and click on create account then accept terms and conditions. I am then redirected again to the profile manager but due to browser autofill it has text that overrides the insertion of the mnemonics of the newly created account.  

### Steps To Reproduce

1. save autofill in profile manager mnemonics field
2. empty autofilled mnemonics field
3. click create account
4. accept terms and conditions
5. watch the autofilled text return and the mnemonics of the newly created account get lost

### which network/s did you face the problem on?

Dev

### version

2.4

### Relevant screenshots/screen records

https://www.loom.com/share/622b414edf3d49929c5be4b0554882b0?sid=d7239941-da56-41e7-be7e-d147a90977dc

### Relevant log output

```console
n/a
```

**Comment by ramezsaeed** [comment]
we can disable the Auto Fill for that field.

**Comment by samaradel** [comment]
### Work Completed:

Fix profile manager inputs autocomplete

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4

the issue is not more producible tried it with different scenarios.



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/395404b3-00ec-4a48-a822-23e80a191e1d

**Comment by ramezsaeed** [comment]
Issue still reproducible on :
- Devnet 
- version: d44ca11


![Screenshot from 2024-07-04 11-31-43](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/31e06cce-d6a1-401b-bfc0-bb51ea81da7a)

**Comment by khaledyoussef24** [comment]
can we search if we can disable auto fill for the fields

**Comment by samaradel** [comment]
###  Work in Progress (WIP):
I can't reproduce it, still investigating...

**Comment by samaradel** [comment]
### Work in progress:
I tried several solutions, but it's still not working .. investigating...

**Comment by samaradel** [comment]
### Work Completed:
chrome behavior prevented by adding ```readonly``` attribute.

**Comment by atefnazmy** [comment]
- Verified on devnet
- Version : ac03039

- The Issue has been fixed. 



https://github.com/user-attachments/assets/6a76735c-5bae-4813-8a6c-3d58eec609cf

**Comment by khaledyoussef24** [comment]
issue fixed and verified also in #3131
