### ISSUE TITLE
Enhance delete domain dialogue style

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2632]
### Is your feature request related to a problem? Please describe

Domain chip style should have text-overflow.

### Describe the solution you'd like

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c979f239-702c-49bf-9d42-06f3dd9faa00)

**Comment by ramezsaeed** [comment]
and change the chips color too.

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.

The chips space was fixed and the color have been changed. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bda6d855-2957-4110-921b-1f0108028aac)

**Comment by ramezsaeed** [comment]
Verified:
- devnet
- 4b03114

![Screenshot from 2024-06-06 17-26-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/56acbc28-3807-4886-865f-9277ae3e2825)
