### ISSUE TITLE
[Bug 🐞]: Clearer wording for Logfiles needed & Clear indication of uptime for Standby Nodes on Dashboard

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/tfgrid-sdk-ts#2633]
### What happened?

Was looking at new dashboard and there are improvements in wording that would make Standby Nodes status clearer:

1.  For example in the logs for my Standby Node I see the following line:
getNodeAvailability: Node 6089 was down for 2215499 seconds in the last 2302923 seconds. 
This node wasn't down for 2215499 seconds, this node was in Standby for 2215499.  It hasn't been down, just in standby.

2.  In the Node Finder looking at my node, it says it has been up less than a day and is in Standby Node.  I think that is misleading since a non-technical person might see that and think the node is unreliable.  In fact  it has been available 24/hours a day for months just in Standby.  When I look at my node in the dashboard it says it has been up 3.82%.  Technically that is true, but in fact it has been available for 24/hours per day for months,  just in Standby.

Another suggestion.  When you post an article on the web, such as a description of the new dashboard, it is always useful to include a web link to the thing you are describing.  For example in your dashboard post which goes into great detail on how to use it, I could not find a link to the actual dashboard.

Just some suggestions for the future.

### What did you expect?

NA

### ZOS info

NA

### Dashboard info

https://dashboard.grid.tf/

### weblets info

NA

### Relevant log output

```shell
NA
```

**Comment by Mahmoud-Emad** [comment]
> For example in the logs for my Standby Node I see the following line:
getNodeAvailability: Node 6089 was down for 2215499 seconds in the last 2302923 seconds.
This node wasn't down for 2215499 seconds, this node was in Standby for 2215499. It hasn't been down, just in standby.

This point has been fixed by adding the node status instead of hard-coding it as "down". Will this be clear enough for the end-user, or do you have another suggestion?

> In the Node Finder looking at my node, it says it has been up less than a day and is in Standby Node. I think that is misleading since a non-technical person might see that and think the node is unreliable. In fact it has been available 24/hours a day for months just in Standby. When I look at my node in the dashboard it says it has been up 3.82%. Technically that is true, but in fact it has been available for 24/hours per day for months, just in Standby.

How can we cover this one in your opinion?

**Comment by amiraabouhadid** [comment]
Would it be more clear and intuitive to the user if instead of saying a node is up we say it is 'in use' and instead of saying a node is in standby we say that it is 'up' ? As in the node is up but is not being used. What do you think @AhmedHanafy725 ?

**Comment by amiraabouhadid** [comment]
We can create an availability percentage which is based on the amount of time the node has been available/ in standby

**Comment by Mahmoud-Emad** [comment]
Update on this issue, Case 1 will be covered

**Comment by A-Harby** [comment]
For the node status, there will be 3 different statuses: up, down,  and standby.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4cf3ee34-6742-420d-980e-ff5cbee93470)

And for the downtime and its calculation, it should be fixed here
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2900
