### ISSUE TITLE
🐞 [Bug]: Node public config validation isn't consistent with the tfchain validation 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

i tried some cases not covered leading to unclear error
<img width="1680" alt="Screenshot 2024-05-01 at 2 56 02 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/57c89ac9-8275-4e4c-bc3f-838593bf4e0a">
<img width="373" alt="Screenshot 2024-05-01 at 2 56 14 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/035fb1af-c22e-4110-a16f-54eb66ab43e4">

### which network/s did you face the problem on?

Dev, QA

### version

2.4.0

### Relevant screenshots/screen records

-

### Relevant log output

```console
NA
```

**Comment by khaledyoussef24** [comment]
can not produce the same issue again shall we close it ?

**Comment by A-Harby** [comment]
Devnet.
I found some cases, like:

- The IPv4 or IPv6 shouldn't be in a different subnet than their gateway. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/eb14f2be-341c-43ec-aa67-53ba2643bc61)
- The IPv4 or IPv6 don't have subnet mask validation.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d9fe8ee6-9414-4f86-b39b-ba9564b8d6b9)
- The IPv4 or IPv6 don't have private IP validation.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2cc0be08-8868-4c24-9d91-05627bf46792)

And there are more cases where the validation is different between the dashboard and the TFchain.

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Investigation and Solution:

The gateway must reside within the same IP range (subnet) as the node's IP address to facilitate proper routing. This ensures that the node can effectively communicate and route its traffic through the designated gateway.

### Work done
#### Changes

1. **Gateway IP Range Validation:**
   - A new validation rule has been added to ensure that the gateway IP address is within the same subnet as the node's IP address. This validation is applied based on the IP version (IPv4 or IPv6).

2. **IPv4 Address Type Validation:**
   - A new validation rule has been added to verify whether the provided IPv4 address is public or private.

3. **IPv6 Address Type Validation:**
   - A new validation rule has been added to verify whether the provided IPv6 address is public or private.

**Comment by A-Harby** [comment]
Verified, Devnet 0d964e5.

A public and private IPv4 and IPv6 validation, a subnet validation, and a gateway to be in its IP range validation have been added.

![image](https://github.com/user-attachments/assets/d13daead-0aa7-443c-af1e-bd07da2e51d6)
![image](https://github.com/user-attachments/assets/81ee0fe6-783b-4a5f-9bd3-f16295ab7732)
![image](https://github.com/user-attachments/assets/917ebbaa-ab10-4530-863b-650380e6e653)
![image](https://github.com/user-attachments/assets/d9161eef-ef6e-434b-a699-9edb997a9078)

Updated: [TC2218 - Public Config Input Validation.](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150427)
