### ISSUE TITLE
🐞 [Bug]: enhancement for "Set additional fees box" 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the box should be closed automatically after updating the fees.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c20ba065-6d4b-43e6-b4e0-8f17fddd36b7

a verification should be added to the value instead of this error 
<img width="261" alt="Screenshot 2024-05-01 at 4 01 56 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/574a61c6-aca1-4358-95e9-7ab7e9b9fc8a">

<img width="1680" alt="Screenshot 2024-05-01 at 3 00 20 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4d49d703-0674-488a-927a-50040a8c5884">
may be the verification should be added here : 

<img width="482" alt="Screenshot 2024-05-01 at 4 01 59 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/27fc567d-a4d7-42ab-985a-30f6860258b2">

### which network/s did you face the problem on?

Dev, QA

### version

2.4.0

### Relevant screenshots/screen records

-

### Relevant log output

```console
na
```

**Comment by ramezsaeed** [comment]
we can limit it to same chain value.

**Comment by atefnazmy** [comment]
verified, Dev
version: 11fa297



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/d3c76a9e-f4ae-423d-8de4-003845e3245e

**Comment by A-Harby** [comment]
Verified, Devnet 0d964e5.

The value of maximum validation is added to 1000000.
![image](https://github.com/user-attachments/assets/b9671860-8520-480e-9919-082e6a72878f)
Dialogue is closed after saving value.

[screen-capture (37).webm](https://github.com/user-attachments/assets/8d87ee3d-18b6-4f1c-a406-de24ebed8196)

[TC2443 - Set Fee](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4164651)
