### ISSUE TITLE
(Testnet Verification)🐞 [Bug]: Change standby flag color on node details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Shouldn't the standby color be yellow?
Or at least green as the red color give the feeling that the node is down.

### which network/s did you face the problem on?

QA

### version

2.4.0-rc1

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0e1be47a-749d-42d3-9087-7641c407fe52)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Updated the node status<standby> color in the node card component from red to yellow color
- Created `getNodeStatusColor` to return the color based on the node status
`Success` for `UP`
`Warning` for `StandBy`
`Error` for `Down`

#### Screenshots

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/0d615ddb-c639-44bb-8972-c7a3963c7f47)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/8ab72a5b-9723-4b9b-aa46-b7ec18c01a4d)
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/4e6bd585-87e4-47ad-b463-67364c52025d)

**Comment by khaledyoussef24** [comment]
no standby nodes on devnet will wait to testnet or mainnet to verify
