### ISSUE TITLE
🐞 [Bug]: Color Issue with Manage SSH Button

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the `manage ssh` button color is a little bit dark in the light mode 
<img width="1680" alt="Screenshot 2024-05-02 at 11 29 02 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b1006564-8654-4712-abff-40e23485b059">
I even compared it with the '`Get TFT`' button, and they do not have the same color code. Shouldn't the colors of buttons be unified?
after an investigation found out that the color codes for the buttons are a little bit different
rgb(26, 161, 143)
rgb(25, 144, 128)

### which network/s did you face the problem on?

Dev, QA

### version

2.4

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by maayarosama** [comment]
The ```manage ssh keys``` button's color has been changed 
![Screenshot from 2024-06-09 13-27-52](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/77b333c5-9caa-403f-b5ca-85c295916ca8)

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : db2daf4
manage ssh button is now replaced with the horizontal menu (slider)

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d9597fb5-68a0-458e-8bcf-6a5f282884da)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/08e23b69-9fc1-4a49-bc6d-017ff9c17b64)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d92979b6-dcff-4b00-856e-f7f29bd95057)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4270412)
