### ISSUE TITLE
🐞 [Bug]: Loading spinners in buttons are not in the same color as the buttons

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while trying to add new button with error color, the loading spinner got the primary color.
after research i found that this is not the default behavior, and we are overriding the `VProgressCircular` component on global components setting

### Steps To Reproduce

1. add any button to playground with any color rather than `primary`
2. add loading prop to be true

### which network/s did you face the problem on?

Dev

### version

development_2.5

### Relevant screenshots/screen records
![Screenshot from 2024-05-07 11-42-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/a9b0817f-b73b-4d14-b320-2c8f0500f35f)

### Relevant log output

```console
Non
```

**Comment by 0oM4R** [comment]
we should remove this line : https://github.com/threefoldtech/tfgrid-sdk-ts/blob/00c8c222d7fb0b1f0ae39db6a90aca1650db3ae9/packages/playground/src/plugins/vuetify.ts#L16

and fix its effects

**Comment by samaradel** [comment]
### Work Completed:

- Remove default ```VProgressCircular``` color.
- Add color primary to components loader.

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
version : ad30945
the spinner and the button are now in the same color


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/69edcedc-86b2-4b84-89fd-01d17b1aa8b7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1899d541-3fd1-4858-8129-3e61f95c3d0f)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/848bd4e8-a79f-4af9-b56c-a4e6f63536ac)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fb873010-765a-407b-b34f-30b78bc74af3)
