### ISSUE TITLE
Update packages section

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2655]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Packages section still contain old repos.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e756daec-611e-472f-876f-eed3c0ae3b86)

### Describe the solution you'd like

Remove old repos and rename new_stats to Stats

**Comment by khaledyoussef24** [comment]
verified and updated


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d6036ab7-9092-4c0b-9db2-47e99107e39d)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ff197308-c1de-4fc0-aa1e-08e60ade4885)
