### ISSUE TITLE
Add rmb peer client docs

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2658]
### Which package/s are you suggesting this feature for?

rmb_peer_client

### Is your feature request related to a problem? Please describe

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/bc6e8b0d-8e7b-45c2-b114-dbb087a5955b)

### Describe the solution you'd like

Add proper documentation and describe how to generate the ts types from the prototype and the main flow of the package.

**Comment by Mahmoud-Emad** [comment]
Work paused here due to currently working on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2683

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done, updated the docs

**Comment by khaledyoussef24** [comment]
verified statically 
RMB read me docs is now available [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/rmb_peer_client/README.md).
it is clear how to make a request or read a request
and also the manual was updated for this part src/documentation/developers/internals/rmb/rmb_intro.md
