### ISSUE TITLE
🐞 [Bug]: Email is not saved or updated if balance is too low

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When I connect my wallet and enter the email or update it using your profile page, it doesn't update or change.
and it only happens on low-balance accounts. 

### which network/s did you face the problem on?

Dev, Test

### version

2.4.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2cadac2b-7841-41f1-9c9a-5ad7fbcdca6e)

[dashboard (2).log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/15248011/dashboard.2.log)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
It keep loading when trying to edit it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d27ff85b-0d8a-4cf1-9d95-95bcdf7d9c99)

**Comment by samaradel** [comment]
### Work Completed: 
Check the balance before updating the email

**Comment by samaradel** [comment]
### Work Completed:
- Add a button for canceling edit

**Comment by samaradel** [comment]
### Work Completed:
Keep the old email when editing to a new email.

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.

The email wouldn't save if the balance is too low and a clear error message is shown.
A cancel button was also added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bb403d5c-050b-4842-85d4-e1f06a77eaa9)

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2842#issuecomment-2145338188

[TC2673 - Edit email](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4263111)
