### ISSUE TITLE
🐞 [Bug]: too low balance error look too bad in connect your wallet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When trying to connect to a wallet with a low balance, I got this error.

It was too long and couldn't access the email or the password input cause the error covered both of them.

### Steps To Reproduce

1. Navigate to the dashboard.
2. Connect your wallet (a wallet with a low balance).
3. Logout.
4. Open connect your wallet dialogue.

### which network/s did you face the problem on?

Test

### version

5.4.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4c7a8a08-be74-461c-ad2c-b7d5392e0462)

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
Tried reproducing the same error with a balance as low as 0.029TFT but didn't get an error. What was the balance at the time of this error?
https://www.loom.com/share/e352021790784feb9430de781def8fc6?sid=ed2be9ec-255d-4da9-9369-68a43c2ce690

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 9d671ca



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/34608729-f021-4bda-8d38-10e7a11d3190




https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=442162#case_4295011
