### ISSUE TITLE
🐞 [Bug]: UI enhancement in node public config in the node details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Why is the IPv6 the only label with copy icon?
It doesn't look the best, and what if I want to copy the other labels, like IPv4?

### which network/s did you face the problem on?

Dev

### version

2.4.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9bc3a6d1-f4c1-4a1f-b368-1930e048d47c)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e166b014-7598-45c5-876d-7270d272bf98)

copy icon now is on all labels.
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460
