### ISSUE TITLE
🐞 [Bug]: Default farm twin data displayed while there are data available to use 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Default farm twin data displayed while there are data available to use 

### Steps To Reproduce

1. Open the [dashboard](https://dashboard.dev.grid.tf/)
2. connect your wallet
3. go to the [farm finder page](https://dashboard.dev.grid.tf/#/farms/farm-finder/)
4. search on the farm with id [21](https://gridproxy.dev.grid.tf/farms?farm_id=21)
5. You'll see that the default data displayed

### which network/s did you face the problem on?

Dev

### version

2.4.0

### Twin ID/s

134

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/f8076204-c8a7-4e08-8dac-69f88864487d)

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment]
The farm has no twin data on the gridproxy so it is expected to show the default values in this case


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/38dca461-012d-4f60-b9fa-6ce0b24f79b3)

**Comment by amiraabouhadid** [comment]
twin ID 100 has no info on gridproxy, will resolve to display only twin ID in twin details card in this case

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/7630b12f-cac8-4ca9-9589-3c12a7c09546)

**Comment by A-Harby** [comment]
Verified, Devnet fa1f347.

If the twin is deleted, only the twin ID will be displayed in the twin details section.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a8592d2d-2724-42dc-a28e-cc7cbe1807e5)

[TC2270 - Show Farm Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150479)
