### ISSUE TITLE
Algorand: Deployment data improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#267]
### Description

Algorand deployment details need some adjustments.

- Network Field.
   - Should be the same size as the other fields.
   - Should be capitalized. 

   ![image](https://github.com/threefoldtech/playground/assets/101194226/c75bccc9-d906-43e2-9853-a82c54a62f88)

- Node Type
   - Should be the same size as the other fields.
   - Should be capitalized. 

   ![image](https://github.com/threefoldtech/playground/assets/101194226/509a0eb4-3e76-478b-b6cb-8faab49c1699)

**Comment by MohamedElmdary** [comment]
What is the point of Capitalizing passed environment variables? it's already lowercase and user might need the base value for some reason or what do u think?
@mohamedamer453 @AhmedHanafy725 @xmonader

**Comment by mohamedamer453** [comment]
> What is the point of Capitalizing passed environment variables? it's already lowercase and user might need the base value for some reason or what do u think? @mohamedamer453 @AhmedHanafy725 @xmonader

the main reason for this is consistency since in the deployment itself the `Network` and `Node Type` are formatted like this.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4a1ad0d3-34a7-4393-996c-c0ce8649dcff)

I didn't know that it was an env var i thought that it got the network and type from the configuration, and i still think that it would look better in the deployment details if it's the same way as displayed in the config. or if it's an env var and not that important then it could be removed entirely and could be accessed if needed from the `Json` config. but having a single word in a field written in lowercase doesn't really look appealing imo.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The size of the fields was modified and the content of the field was capitalized.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3d9b508e-d96b-4b2b-9611-b437431fbfe4)
