### ISSUE TITLE
Enhance the dashboard colors in the light mode

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2674]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

these are some examples 

watch the TFT amount here

- ![image_2024-05-09_15-02-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ce4e4435-81cd-4ce8-a436-c609fb1fa06f)

here also, notice the create button

- ![image_2024-05-09_14-54-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/64ab35f2-549b-4716-ac0d-85ccbdcc1cf3)

even the deployment details are not easy to read 

- ![image_2024-05-09_15-08-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/3a0df364-8de1-44f1-ae6c-fc7c6ec48c12)

the deploy button

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/a15a76c1-2e53-4c64-ba68-070cd72cdc5a)

### Describe the solution you'd like

N/A

**Comment by samaradel** [comment]
### Work Completed:
Enhance fields, buttons and JSON code in light theme

**Comment by samaradel** [comment]
### Work Completed: 

Enhance UI components in light theme

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.

[TC2301 - UI component](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4155453)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cf256381-8d1b-4319-92a2-d7b50c154c37)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/794e4884-fc6a-41a4-b20c-a1c27c0cc20a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/447bbd71-59c9-4d8d-a3da-8e24003eaf7e)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d806ab4


![Screenshot from 2024-06-04 17-44-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/e106cd11-5eb1-4000-98e5-800d2c03a6f6)
