### ISSUE TITLE
Update alert in node finder

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2675]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/cf4624fc-8258-4bf1-9f03-18ffb75d3aa5)

### Describe the solution you'd like

Update message to be "...click on the node card." instead of "... click on the row."

**Comment by khaledyoussef24** [comment]
verified and updated on devnet
version : e7bb580


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1dd9581-0d3a-42d8-b4c5-03494df6496a)
