### ISSUE TITLE
🐞 [Bug]:  Can't connect my wallet

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the connect your wallet was working before, but now it gives me this error in the console.
also, the dialogue and the debug logs didn't show any alert or error I just keep click it with no respond.

### which network/s did you face the problem on?

Test

### version

2.4.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/35a36a8a-9d81-4e3e-a65c-1cdefaf1f1c8)

[dashboard.log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/15264150/dashboard.log)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
i also faced this issue on Qanet
![telegram-cloud-photo-size-4-5933766953632121687-y](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4d864470-1e07-4543-baf8-b4eed2c5de68)
is it related?

**Comment by A-Harby** [comment]
The issue isn't reproducible till now, tried a few ways but still can't.

I will close the issue until it happens again.
