### ISSUE TITLE
🐞 [Bug]: UI fix to the delete button color in workers

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Change the color of the delete worker buttons; both remove and cancel text are in red, which is confusing, and the remove color background should be the one in red, not the other way around.

### which network/s did you face the problem on?

Test

### version

2.4.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7c083cb8-0b01-4515-852d-b4dce27d1b73)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
The same thing is true for deleting a domain from a VM.
Cancel shouldn't be in the green color.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8b9975e6-b9aa-4401-95c8-42a91321e9be)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/56fa7345-222e-42aa-961b-d66d226cd55b)

**Comment by A-Harby** [comment]
the buttons moved to the wrong side.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/35edeb01-d9ee-4097-a8ad-41794c5ee20a)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0139c63

the buttons are now placed in the right side


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8b19ddde-4839-444e-8284-419efcf8ef64)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf0a4b30-a9a8-4ee6-859f-0ef3229c7d82)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/faa91241-b560-45da-bcd9-05f1edba679b)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/091071dc-7a5b-4b20-af8e-f36ae886d9f3)
