### ISSUE TITLE
Hide multiple key selection in the SSH-Keys page 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2683]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

We should disable the ability to select more than one key till we fix https://github.com/threefoldtech/tf-images/issues/231

### Describe the solution you'd like

N/A

**Comment by Mahmoud-Emad** [comment]
Should be fixed in development_v2.4.0_update_sshkey

**Comment by Mahmoud-Emad** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/ad2b8bdc-8d3e-4af5-b93f-189663c75623)

[Screencast from 05-12-2024 02_33_53 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/c5fd12de-fff5-407c-a1ed-19860227d5e1)

**Comment by Mahmoud-Emad** [comment]
The issue is included in the `2.4.1 release` and should also be included in `2.5.0`

**Comment by A-Harby** [comment]
`Close` button disappears on light mode.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/06602821-d094-48ed-8b98-cd0ba47fe9d6)

**Comment by khaledyoussef24** [comment]
verified for now user can only choose one ssh key on 2.4.2 (will be changed in 2.5)
another [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2734) is already there for the close key


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b1e8c239-8cff-419c-ae45-51dc743ab00d
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/25e4da6e-8364-4b01-89ef-4fa4aff8f782)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/603b9b4c-03f2-46b1-b334-a661748362ca)
