### ISSUE TITLE
Get TFT button is not working

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2684]
> @zaelgohary After investigating in `get tft` button I found that issue related to this PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2563/files#diff-fce083955bd2accb8ca8a9c35f2f4c1915853c058393a1b14e1ae26dad9aa2c0R43-R45

**Comment by zaelgohary** [comment]
Work completed:

Reverted grid store changes in funds card.

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet and working fine now 
version : 85a6fa4



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/af5c78f2-c5e3-4a63-b00b-d9bb65646fe1
