### ISSUE TITLE
🐞 [Bug]: The dialogs' margin in the ssh key page looks inconsistent with the rest dashboard's dialogs

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the margin at the left is small

### which network/s did you face the problem on?

Dev

### version

development

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/3d327a1d-e790-490c-827a-a2cdf94f8f83)

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
I tried to compare the SSH dialogue with the node public config dialogue and found that they have the same padding as seen below.

SSH:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a0105227-27b4-40ca-b5d7-4ab77c71f770)

Public config:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/e451ce6c-c6f2-4d64-81cc-b3347e0618fd)



However, the dialogue width is different and there is an opened [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2697) for it.

**Comment by khaledyoussef24** [comment]
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a9a845b-6966-4cd1-a4e8-1935223c0f41)
