### ISSUE TITLE
🐞 (Qanet)[Bug]: node contracts on rent contracts alert doesn't appear on contract lock details

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I have rent contract on grace period, and when open the node contracts i found the locked amount 0 tfts, that is because the node contracts is on rented contract. we should handled this case before. 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/436494059d78d6e469a67676c6dde86df8180a23/packages/playground/src/components/contracts_list/contracts_table.vue#L97-L105 

### Steps To Reproduce

1. rent node 
2. deploy vm on the rented node 
3. wait for the rent contract to be in grace period 
4. in node contracts table click on grace period chip on the deployed vm 
5. you will see 0 tft as locked amount without any alerts 

### which network/s did you face the problem on?

Dev

### version

2.4.0

### Relevant screenshots/screen records

![Screenshot from 2024-05-13 11-17-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1bf4410a-f55d-422c-b4e0-7f9bb20f0b56)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
It's still showing the same thing: 0 tft with no alert.
And with new unlock button, it shows the unlock button as enabled and clickable (the click doesn't do anything, apparently but it's very confusing.)

[screen-capture (33).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/61a11be2-f1f5-46ed-95af-279f3b0f5dc0)

**Comment by 0oM4R** [comment]
I noticed that the unlock all contracts and unlock buttons are not shown in the table, even if i select only grace period contracts, 
this should be fixed in [commit](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2979/commits/a58fb6802d99af90f569a900811f4a8f8f43ac01)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/42772c66-b3fb-4a33-afe8-7d3b28cb323e)

**Comment by A-Harby** [comment]
Verified, QA 2.5.0-rc3.

The contract deployed on the grace period rented node doesn't show the unlock button anymore. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a02b2421-0d86-4f9c-a923-352c07eedd57)
And unlock all contract is now displayed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aa054cc2-9705-45b6-9f47-534cbe2ed04a)

[TC2719 - Unlock Grace period Contract](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4295189)

[TC2729 - Unlock All Grace period Contract](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4306582)
