### ISSUE TITLE
🐞 [Bug]:  Deploy button not working when deploying a micro vm

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-ts#2690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I was deploying a microvm ubuntu 22.04 using the dashboard for some reason after filling all data the deploy button still disabled tried different nodes didn't work also [devnet statging](https://staging.dashboard.dev.grid.tf) 

### Steps To Reproduce

in this env [devnet statging](https://staging.dashboard.dev.grid.tf)  try to deploy a micro vm

### which network/s did you face the problem on?

Dev

### version

4364940

### Relevant screenshots/screen records

![Screenshot from 2024-05-13 12-42-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/1689456/6f14475a-2fcc-4149-95d0-bfd67e01d72b)

### Relevant log output

```console
nothing didn't manage to even click on deploy
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

The import of the SSH-Key component was removed by mistake which cause the issue, I added it back

**Comment by A-Harby** [comment]
Verified, Devnet 0d1e63f.

[TC2126 - Deploy Micro Virtual Machine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150335)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d0984de5-92e7-45f8-b7d3-5f8b1cae8f06)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2ee16634-d3c2-4440-b7de-4d3acee16731)
