### ISSUE TITLE
Use zmount as the default disk workload

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2696]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

on the development branch, the volume workload is used as the default disk.

### Describe the solution you'd like

let's return back to use zmount as the default.

**Comment by zaelgohary** [comment]
Work completed:

Used zmount while creaing disk instead of volume.
