### ISSUE TITLE
Remove unused ipv6 column from the deployment list

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#270]
### Description

In the deployment list for presearch there's an `IPV6` field while ipv6 is not one of the options for presearch so it should be removed.

![image](https://github.com/threefoldtech/playground/assets/101194226/c16d73c0-075b-4d9c-94f4-ad007b973c79)

**Comment by A-Harby** [comment]
Verified 
All the solution Deployment List was updated to only show the available IP. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c7f6dc81-02a6-4ced-ae5d-bafecb8aed92)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0a41fdca-7e08-4c94-87fa-018005bb8b0a)
