### ISSUE TITLE
🐞 [Bug]: choosing a name for a ssh is not functional

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while i was creating a ssh key from the dashboard, i chose a name `newssh` after creating it ,it is automatic renamed.

### Steps To Reproduce

1. go to dashboard
2. go to ssh
3. choose import a ssh key
4. choose a name
5. paste your ssh
6. click on create
7. the name is changed

### which network/s did you face the problem on?

Dev, QA

### version

2.4

### Relevant screenshots/screen records

![2024-05-15_12-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1925e88d-c137-4214-a797-2f57ce8f28d6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8b3e7eee-3ff0-44e0-995a-d8a06a3bfc4b)
[Screencast from 05-15-2024 12:44:19 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/074efbe4-9a7d-4b55-a4e9-90d499f0a2c3)

### Relevant log output

```console
na
```

**Comment by AlaaElattar** [comment]
### Work Completed:
- Fixed issue, the name won't be extracted from key unless the field is empty.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 2b7ab4e


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f9c1d8bb-70e8-42bb-954f-196bd4ae21a7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bbd0ed02-661c-465b-b306-68bdc75305b8)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4259782
