### ISSUE TITLE
Presearch: Creating more than one deployment in the same farm using planetary ip only is allowed

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#271]
### Description

Creating more than one preasearch deployment in the same farm using planetary ip only is allowed.

I was able to deploy 2 presearch instances without public ips on freefarm. both of them were successfully deployed but none of them appeared in my preasearch dashboard.

![image](https://github.com/threefoldtech/playground/assets/101194226/03cead7d-b6d1-4ca9-9690-1dc48987b0d1)

![image](https://github.com/threefoldtech/playground/assets/101194226/6cc3775f-1f9d-46dc-84a5-c3d81a16f9f6)

![image](https://github.com/threefoldtech/playground/assets/101194226/8be1453b-b28a-4007-b4a9-f668f6754b73)

![image](https://github.com/threefoldtech/playground/assets/101194226/b2fc384b-4b3a-4b10-bccd-551d34ef694a)

**Comment by xmonader** [comment]
related to #294

**Comment by mohamedamer453** [comment]
Verified on devnet.

Since there's already a deployment on freefarm with planetary ip it's not possible to deploy more preasearch deployments unless a public ip is assigned for the deployment.

[TF Playground _ Presearch.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c3a67345-8672-48d1-a48d-691a5adf1397)
