### ISSUE TITLE
🐞 [Bug]: UI fix table with 1 search result 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#2711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

searched for farm ID 21 in farms finder

### Steps To Reproduce

1. go to farms finder
2. filter by farm ID 21
3. observe how table has no bottom border

### which network/s did you face the problem on?

Dev

### version

2.4

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/575cf8de-5dce-4ffe-a15a-2e62bd762466)

### Relevant log output

```console
.
```

**Comment by MohamedElmdary** [comment]
WIP:
Still need to make table headers' a little more thick

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d8d3fd41-a53f-460c-8a67-f81c36febc9d)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2095b227-67c4-4df4-9515-046b068838ac)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4295002

**Comment by ramezsaeed** [comment]
Verified:
 - devnet
 - 9d671ca

![Screenshot from 2024-06-09 17-46-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/7d5f342d-5cd6-445e-8901-1875e171d3c3)
