### ISSUE TITLE
Press enter key to apply node finder filters

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2714]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Every time I am setting filters on the node finder, I instinctively press enter to apply them but nothing happens.

### Describe the solution you'd like

Enter key should engage the "Apply" button on the node finder. Probably there are some other places in the UI where this make sense, but I didn't go looking for all of them at the moment.

**Comment by zaelgohary** [comment]
Work completed:

Added an event to apply filters on enter.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5c0107a9-9469-4b37-a99d-116d1f17048c

verified on all fields and filters

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/df0a8064-123e-427e-9b98-eb7f11e82047)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7390c78e-9f28-476f-a0ac-2178060cf13b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f7c94204-6e79-4e11-84fb-9dc193c8fc82)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- d44ca11
