### ISSUE TITLE
🐞 [Bug]: some fields is not valid in the new deployment lists for applications

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

in the new deployment lists for applications some of applications are missing the filed of public ip :
![Screenshot 2024-05-19 at 5 47 47 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8938ef4d-10d6-4448-8a26-8215d0406d3f)
![Screenshot 2024-05-19 at 5 49 05 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99e669ec-2e7f-474e-9662-877340f217e6)
![Screenshot 2024-05-19 at 5 49 11 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/494acd5a-df13-4ac1-bd33-acc6dd38ec1f)
applications which should contain public ip field : 
funkwhale
mattermost
discourse
taiga
static website
next cloud
presearch
wordpress

while in other applications it has the public ip field but the applications(algorand and subsquid) should not contain it : 
![Screenshot 2024-05-19 at 5 52 58 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2179c25a-267f-45f2-ad9c-e833e65c342c)
![Screenshot 2024-05-19 at 5 53 03 AM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/430486f9-1a23-4efd-b2e9-157bc6cf3f12)

### which network/s did you face the problem on?

Dev

### version

0d1e63f

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed:
IPv4 columns removed from:
- Subsquid
- Algorand

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945

funkwhale


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e3e1883d-cab9-46b8-b2cb-bac4b785c1a8)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/43815ef8-01c2-4a5f-9168-8e834710beb9)


mattermost


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/765b83b8-8c1c-45e1-be36-0b6b63b67b10)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/048e6ed2-1b36-437f-84eb-5fcd62cd00c0)


discourse


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6b87cb6a-e549-4a0c-b12d-3c6514d5acbc)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3c00a826-1adb-432f-80ad-c1e79f5fab6d)


taiga


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d44b714f-adf7-484f-a24b-314a118e3add)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d75a7b2c-c55f-4e42-a91f-727770095ff2)


static website


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b4b03d67-8f31-4acc-b2ef-e28645f82869)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2056aebb-ed18-495b-8868-64906cabf30f)


next cloud


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bfa57232-7fd5-4edd-81c4-9585759e2c95)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/62e61390-1691-4562-b0e4-9ff5dc38d8ab)


presearch


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1d834712-fd9b-40b6-97f9-3e13f6ca24bd)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/672b5d95-39a6-4893-9009-5e2c438126f2)


wordpress


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fd00079a-ab83-4bec-a772-7b2f83b97153)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1c13e141-0851-4ad5-8f77-dc58e5b0477e)


Algorand

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2e49a0de-34bb-4dd9-a165-7f44659e9d9e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d5a9400f-9f88-461f-a5e0-5b590ea99d57)


Subsquid


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/69089656-a4f5-4314-9064-ff33315172ac)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6617e1d0-3983-4ca6-a778-a77456771b4a)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4295005

opened another issue for node pilot #2910
