### ISSUE TITLE
🐞 [Bug]: Cannot deploy my website using the static website application

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I updated the [Github-repo](https://github.com/Mahmoud-Emad/StoryMith) then went to the [Staging Dashboard](https://staging.dashboard.dev.grid.tf/#/deploy/applications/static_website/) and deployed an instance but the instance not worked

### Steps To Reproduce

1. Go to the [Staging Dashboard](https://staging.dashboard.dev.grid.tf/#/deploy/applications/static_website/) 
2. Provide a valid Github repo
3. Deploy

### which network/s did you face the problem on?

Dev

### version

 0d1e63f

### Twin ID/s

143

### Relevant screenshots/screen records

The website link https://sw143storymith.gent02.dev.grid.tf/
The repo link https://github.com/Mahmoud-Emad/StoryMith

the deployment is not listed 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1e5ff172-2b95-4aba-b0a0-93d49d1f0b35)

### Relevant log output

```console
This is the deployment details 

[
  {
    "version": 0,
    "contractId": 110856,
    "nodeId": 171,
    "name": "storymith",
    "created": 1716100745,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/mayarosamaa.3bot/mayarosama-caddy2-v1.flist",
    "publicIP": null,
    "planetary": "300:393f:fb1e:1719:7058:9513:5a0c:19fc",
    "myceliumIP": "",
    "interfaces": [
      {
        "network": "nwcbx21",
        "ip": "10.20.4.2"
      }
    ],
    "capacity": {
      "cpu": 1,
      "memory": 2048
    },
    "mounts": [
      {
        "name": "diskela",
        "mountPoint": "/var/lib/docker",
        "size": 53687091200,
        "state": "ok",
        "message": ""
      }
    ],
    "env": {
      "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCF3JezThwSchTvkF2oPtn8X6chevNsfE58dIY3/eg5zK9tKgNYIB2saoFh12a0AJU424sAeLO0HghhNhe/Co62xkzHhk6EpXWNSFkrlzw+FVn1FKDZbbOZH47sC3n6p5a3YhM4dALssZ/aZdpaKBgXkzk91usJ+GVa+eOnpMRBlHgi9PpvowyzPSKeH9ZcVRBPnVU+nQGyV+kd6RahNBoNgNrHu/QFI92yg/y/7Szus1IS0U92cWKf/K/Sot7O10kSjmj06lMGOO8zdENk/xrtUtRHzemCj+mq0Q/3KUMCGvdb/tH0TDeNenxvibummiym4VTcnYqbm+RDXWG8HUc/RPfEVBl8p1NGZnkBt6QJl5hddHaYwx8CCmf3maSrQFcmrWYtlUDBXYkPyrv0qmy2gM1PScntF/X9zhIfnELlyAVAKXfzVwixrBh7oOIAqefydSVcwWtCXoH38F5q/zo9bQv+eHntI83mZrUUT7JGirQF64fpJKbCZPhv0kUm9bF7DVQMiyRZdk748cgVp7dEzMVlrfZ2eIvZag5zmuJTPB7bw00+Ik9jNaOIhEoCWEaYBw7KmrLonesV8rWUkEAwWPe28bXCVmUZlgZbWJi7BFWCst2Z/j2WgScHbdAv28gAcneDW4yQmt2YaYqXqmwgSVCaD/irq5FSO4upmo5u0Q== mahmmoud.hassanein@gmail.com",
      "GITHUB_URL": "https://github.com/Mahmoud-Emad/StoryMith",
      "GITHUB_BRANCH": "development",
      "HTML_DIR": "website/./index.html",
      "USER_DOMAIN": "",
      "STATICWEBSITE_DOMAIN": "sw143storymith.gent01.dev.grid.tf"
    },
    "entrypoint": "/sbin/zinit init",
    "metadata": "",
    "description": "",
    "rootfs_size": 524288000,
    "corex": false,
    "gpu": []
  }
]
```

**Comment by maayarosama** [comment]
1. Work Completed:
The issue here was the project wasn't build and and the correct html dir from the build wasn't provided. And in the static website we expected not to build the project and a correct html dir
2. Work in Progress (WIP):
- still investigating why the deployment list isn't refreshed after deploying an instance

**Comment by khaledyoussef24** [comment]
verified in both #2088 and #2817 
tried in both project a [github repo for static website](https://github.com/cloudacademy/static-website-example)
and worked fine
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4289467)
