### ISSUE TITLE
Add last deployment to node card

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2718]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

-

**Comment by khaledyoussef24** [comment]
verified on dev
version : 6f39878


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f70781ee-e1db-43fa-b4a4-61d4a6d824d7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c70b2095-15be-47a0-987d-b90f7f99d7ad)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150460

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 11fa297
