### ISSUE TITLE
Ensure IP is not already registred on other farms before adding it

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#2726]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

https://github.com/threefoldtech/tfchain_graphql/issues/157

### Describe the solution you'd like

Add a validation on add ip form to ensure IP is not already registred on other farms before adding it

**Comment by atefnazmy** [comment]
- Verified on Dev
- Version: ac03039
- The validation that checks for an existing IP has been added successfully.

![IP](https://github.com/user-attachments/assets/07a7f239-f81e-458a-b6b3-d7587233042e)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : c112478


![Image](https://github.com/user-attachments/assets/fffe737f-6b71-4d82-ae4c-59a4b41744ba)
![Image](https://github.com/user-attachments/assets/7c09b605-8678-41c3-8eb3-cf0cf824b096)





[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4329585)
