### ISSUE TITLE
Unable to deploy solutions that require a gateway

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#273]
### Description

While deploying a peertube instance i recieved the following error and it's quite unclear what the issue is.

```
Error: Failed to create name contract NaNptakvgol9em due to Failed to apply createNameContract in module smartContractModule with NaNptakvgol9em due to error: NodeNotExists
```

![image](https://github.com/threefoldtech/playground/assets/101194226/dc450620-3e97-4d92-945f-89f1a483c7ed)

Tried other deployments on different gateways `gent01` and `gent02` and all of them failed with the same error and before failing this appears in the logs.

![image](https://github.com/threefoldtech/playground/assets/101194226/680a972b-b45a-4d7d-85e2-919f038e45ec)

Then the contracts are deleted and the error mentioned above appears.

**Comment by AhmedHanafy725** [comment]
after some investigation, found that the name contract fails if it contains any uppercase characters. But the error is misleading

so all solutions should use lowercase names for the deployment name

**Comment by 0oM4R** [comment]
pr #352 ready for revie 
note : gw is still not accessable, or even ssh to the machine

**Comment by A-Harby** [comment]
Verified. devnet, 861c5f8.

deployed Peertube and funkwahle successfully.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/740d0cb2-54b9-4fd8-a257-7f929e5d6228)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/14260e6e-10ba-4e41-a240-6baccd4b3807)
