### ISSUE TITLE
🐞 [Bug]: Error loading Network Speed Test in node details in node finder

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2733]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Error loading Network Speed Test in node details in node finder giving `Failed to load IPerf details. Please try again later `

### which network/s did you face the problem on?

QA

### version

2.4

### Relevant screenshots/screen records

![Screenshot 2024-05-20 at 2 38 44 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db0f4e7d-52af-42e9-85dc-cc0135925637)
![Screenshot 2024-05-20 at 2 54 03 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/569e8343-16d1-4e8e-b71a-ed5da6ed969f)

### Relevant log output

```console
.
```

**Comment by AhmedHanafy725** [comment]
Also, it doesn't require the user to login to show the speeds as it comes from gridproxy

**Comment by khaledyoussef24** [comment]
verified on dev net 

version : 17d861b

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d3108f9e-d4a9-4f4f-8ce0-525818d591b6)


@AhmedHanafy725 it does not show up without a login ,is it okay ?
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/51ccfe02-c8ae-45f3-95ea-131e5d8c3635)

**Comment by AhmedHanafy725** [comment]
we switched back to the old implementation (show them when the user log in). if you would like to show them without login, please open a new issue for it

**Comment by khaledyoussef24** [comment]
had a discussion with @ramezsaeed and an agreement that this is the acceptable behavior.
