### ISSUE TITLE
🐞 [Bug]: UI change close button color in manage ssh keys dialogue

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Close button disappear on light mode.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d5888680-3d63-4fd8-a4f1-c157664bd7ef)

### which network/s did you face the problem on?

QA

### version

2.4.1

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed: 

Enhance UI components in light theme

**Comment by A-Harby** [comment]
Verified, Devnet.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b5fa82da-028e-4907-951b-f21480ea872a)
