### ISSUE TITLE
Show all network speeds in node's details card

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2735]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

it only shows the upload and download speeds that aren't known if it's TCP or UDP on ipv4 or ipv6

### Describe the solution you'd like

it should show all these speeds

**Comment by zaelgohary** [comment]
Work Completed:

Reverted previous changes in node details so now, IPerf test will be retrieved from zos instead of grid proxy.

**Comment by khaledyoussef24** [comment]
already verified that changes are reverted in #2733 
network speeds are shown right in node details
