### ISSUE TITLE
🐞 [Bug]: Revert Descending sort in Node Finder

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Up nodes should be shown first in Node Finder. Hence, sort by "asc".

### Steps To Reproduce

-

### which network/s did you face the problem on?

Dev

### version

3c8f13a

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b6122bcf-6af0-4411-9661-f1a1604bb05f)

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
Work completed:

Changed sort order to asc.

**Comment by AhmedHanafy725** [comment]
the changes to adjust the node sorting will be done in #2354
