### ISSUE TITLE
🐞 [Bug]: No error appeared when writing characters in calculator

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- I typed characters at the balance field in calculator, and the field accepted them.

### Steps To Reproduce

Calculator page in dashboard

### which network/s did you face the problem on?

Dev

### version

-

### Twin ID/s

-

### Node ID/s

-

### Farm ID/s

-

### Contract ID/s

-

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/86aa71db-2891-41dc-b296-7c329f1a45ac)

### Relevant log output

```console
-
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done 

Fixed entering characters value in the balance field

#### Changes

- Added the 'isInt' validation rule to check the entered value and display an error in case the entered value wasn't an integer.

#### Screenshots/Video

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/5886b8bc-536b-46bc-b9ce-6f24c22d61c9)

**Comment by khaledyoussef24** [comment]
version : 2b7ab4e
verified user now can not insert a character in the fields without errors



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6bd74e84-e3ae-4225-a120-5c007e33b2c7)


https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4292394
