### ISSUE TITLE
🐞 [Bug]: Items per page in all tables should be consistent

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- Items per page for farm finder page, not consistent with rest of tables

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/f71ff8ce-1d8d-4fbc-a23e-7d3e301e4cfb)

### Steps To Reproduce

1- Open Dashboard
2- Navigate to farm finder

### which network/s did you face the problem on?

Dev

### version

-

### Twin ID/s

-

### Node ID/s

-

### Farm ID/s

-

### Contract ID/s

-

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by samaradel** [comment]
### Work Completed: 
Fix farm finder table pagination

**Comment by khaledyoussef24** [comment]
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fc18887a-9991-42d2-b59c-7b4722cd6e7b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2d2722ed-265c-4b0c-b96c-a11b283c2f60)

still the same issue is found how is set as a default 20 while 20 is not an option to choose

**Comment by khaledyoussef24** [comment]
same for your farms page


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f558a322-254c-4652-aca8-c6d868a005ff)

**Comment by samaradel** [comment]
### Work Completed:
Rest all data-tables paginations to the default value.

**Comment by samaradel** [comment]
### Work Completed:
Remove ```All``` option from pagination as it's not supported yet.

**Comment by khaledyoussef24** [comment]
verified and options in the farm finder and the node finder are consistent for now

![Image](https://github.com/user-attachments/assets/985809d8-fb56-4a85-898f-bdbecb72000d)
![Image](https://github.com/user-attachments/assets/f2d7dc5b-2241-4ae3-bae5-df001b34058e)
![Image](https://github.com/user-attachments/assets/73971a3d-d8b7-41a4-a611-1a3b03d4f982)
![Image](https://github.com/user-attachments/assets/7f45b757-25e9-4e75-b206-d430bd0f2abb)

**Comment by khaledyoussef24** [comment]
@samaradel is there is another issue for this or this will be removed ?

**Comment by samaradel** [comment]
@khaledyoussef24 idk, maybe it was updated recently

**Comment by khaledyoussef24** [comment]
Ite,s on deployment list are still different than others : 


![Image](https://github.com/user-attachments/assets/31010a2d-04c5-465b-aace-d11c670e16e3)

**Comment by samaradel** [comment]
### Work completed:
Make all deployment tables consistent

**Comment by khaledyoussef24** [comment]
verifed on devnet
version : a542a73

all items per page are now consistent 



![Image](https://github.com/user-attachments/assets/3341015e-f868-4c00-807d-14a047d06be1)


![Image](https://github.com/user-attachments/assets/41d023ac-a4c6-4435-8ce8-147360415da6)



[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4347048)
