### ISSUE TITLE
Enable Mycelium by default in all solutions

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2747]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

-

**Comment by zaelgohary** [comment]
Work Completed:

Enable mycelium in all solutions.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 85a6fa4
mycelium is enabled by default in all apps.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/412f7c83-ccbf-44a7-a5ef-6c00985f5d0c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/11eae2c7-4386-4159-8305-28677cfd2eb2)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a04bae3-5edc-43d5-9697-d1fe1b77d8a3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bdaa5abb-e3ab-4ac4-ad1d-5735bdbf67b3)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ef5da1ff-605a-4014-9621-4506ee4f74b1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e4a0796-d371-4fbe-a3f5-d615b53a5830)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e3037a53-f0ec-43a5-ae1e-879cc5f6b51e)
