### ISSUE TITLE
Locked TFTs are not appearing

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#275]
### Description

Locked TFTs are not displayed. currently i have multiple contracts that have been active for hours and their billing rate appeared in the contracts list \. however my locked tftsTFTs are still at 0.

[Screencast from 21-05-23 17:16:43.webm](https://github.com/threefoldtech/playground/assets/101194226/1980ce61-f1bc-460c-8e43-e2f2919ba3f0)

and from the dashboard it can be seen that i have ~7 TFTs locked.

![image](https://github.com/threefoldtech/playground/assets/101194226/9e471f42-0bbb-45a7-9cfd-9a633d1eded2)

**Comment by MohamedElmdary** [comment]
Should use feeFrozen instead of reserved

**Comment by A-Harby** [comment]
Verified, Devnet b6c6d97.
Locked TFTs are now reflect correctly.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5d195869-f5c9-41a5-9f68-8a97cb9fb356)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2e9d9baf-7381-4182-a422-3ccbe86e3c7f)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e417df7b-0217-4579-9921-d167578d389e)
