### ISSUE TITLE
🐞 [Bug]: filter node result in nodes that don't have enough resource

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

I have been getting this error a lot lately, more than it's supposed. I use a filter node to find a node with a specific resource, and when deploying on one of these nodes, it gave an error that the node doesn't have enough resources, which doesn't make much sense. 

filter node result in nodes that don't have enough resource

It has been happening in most of the scripts and also in workflows, and it's usually node 11.

### which network/s did you face the problem on?

Dev

### version

5856083

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/06f0af28-9b18-4758-a467-5c60437d6bad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8fe1fcdb-8b92-4240-a9db-67cdb03b8667)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/520ecc2f-15ac-4c38-90c6-1d9c1c0d84e3)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work in progress

Could be related to https://github.com/threefoldtech/tfgrid-sdk-go/issues/1052

**Comment by Omarabdul3ziz** [comment]
check the updates on the linked issues please

**Comment by Mahmoud-Emad** [comment]
Based on @AhmedHanafy725 

> it requires that the scripts to use the filters correctly.
for example: if I require a vm with a disk, I should consider that ssd required for this deployment to be the added disk + rootfs
what I can see is we only consider the disk in the filters, but the client before executing the deployment, it double checks that and I believe that's why it fails

@A-Harby Please update the scripts

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2874
