### ISSUE TITLE
UI Enhancement : Can we change the date and time format in deployment lists ?

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2751]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

![Screenshot 2024-05-21 at 12 20 18 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/74e0aaee-203e-4454-a9dd-5a5cadc58881)

### Describe the solution you'd like

can we change the date to be in the `DD/MM/YYYY` format instead of `MM/DD/YYYY` ?
and also can we change the time format to write the 0 in time for example `12:01` instead of `12:1`

**Comment by amiraabouhadid** [comment]
will not show year as YYYY but as YY as it takes up space and isn't necessary, what do you think @ehab-hassan

**Comment by ehab-hassan** [comment]
> will not show year as YYYY but as YY as it takes up space and isn't necessary, what do you think @ehab-hassan

agree no need to YYYY

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4
the new format is now view in the contracts of devnet with the format DD MM YYYY


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1e7f3f9-ee24-4f8d-bfe7-3a08681c9630)

month is written in words
