### ISSUE TITLE
UI Enhancement : loading in contracts page giving no contracts before loading

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2752]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

loading in contracts page giving no contracts before loading contracts
![Screenshot 2024-05-21 at 12 43 16 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1765c95e-9dda-4ce8-a60a-046c13447c0b)

### Describe the solution you'd like

Can we add a loading message for a better user experience? 
Can we also decrease the loading time while changing how many contracts per page ?
( i have 40 contracts it takes too much time to load)
![Screenshot 2024-05-21 at 12 52 09 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b38fd1a-34b1-4dbb-b6b5-a4d40023b3e0)

**Comment by khaledyoussef24** [comment]
fixed and verified on devnet
version : 2b7ab4e
now when user go to contracts the message changed to loading contracts

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/917fcbc7-bebd-4d8b-ab61-8eef3c3a111e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/79c3ad43-89ce-4bae-acc1-1fdc2b287895)

will verify the rent table message when i have a rented farm

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ad30945
