### ISSUE TITLE
UI Enhancement : Can we add a info message in Your Farms and Farm Finder for farm details

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2753]
### Is your feature request related to a problem? Please describe

Can we add a info message in `Your Farms` and `Farm Finder` so user know he can get more farm details by clicking on the farm.
![Screenshot 2024-05-21 at 1 58 15 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/50108f1d-4e33-4adb-b242-457aed5639d0)

![Screenshot 2024-05-21 at 2 04 17 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/08f261d0-4016-4557-b801-62fa2c26069c)
![Screenshot 2024-05-21 at 2 04 20 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0bd6b5c6-5ef3-4e47-a654-3b4d3ed9743e)

### Describe the solution you'd like

**we can add a alert or info message like this:**
![Screenshot 2024-05-21 at 1 54 41 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/137e3047-3b82-49a9-a79f-2f22bfeaf4a8)

**Comment by zaelgohary** [comment]
Work completed:

Added the alert to both pages.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4
alert added to both pages


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ace67ebe-e08a-490d-81d9-dd03c6d9c7d9)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/59cf01ef-39ce-4a15-a934-47e7ef312614)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/64d09781-8064-496d-a21c-42a9d008a733)
