### ISSUE TITLE
🐞 [Bug]: console error while disabling all the network before choosing the desired network

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while choosing which network i will use a console error appeared while i was toggling some options
![Screenshot 2024-05-21 at 2 33 00 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fc3c2e6b-d0f7-4baf-9640-7ebf46fd349e)
![Screenshot 2024-05-21 at 2 33 08 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ff499251-89b3-4cd8-b9ca-4604ffeb1978)

### Steps To Reproduce

go to any deployment and open network and disable all network toggles
the error will appear in the console

### which network/s did you face the problem on?

Dev

### version

2.4

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
can't reproduce on staging 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d2d4209f-c086-4a17-9b61-254315d4c68c)

**Comment by khaledyoussef24** [comment]
issue is no longer reproducible tried to produce it by the same way but couldnot
