### ISSUE TITLE
🐞 [Bug]: Scroll in the dashboard is not working while the dashboard logs is opened

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

user can not scroll in the page if the dashboard logs is opened.

### Steps To Reproduce

1. go to the dashboard
2. go to any page
3. open the dashboard logs
4. try to scroll in the upper part 
5. it wont work (only will work in the logs part)
6. close the logs
7. scroll will work again

### which network/s did you face the problem on?

Dev

### version

2.4

### Relevant screenshots/screen records

![Screenshot 2024-05-21 at 3 23 04 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c5adfa08-eda1-441b-a4ff-b0f51b6b147b)
![Screenshot 2024-05-21 at 3 23 09 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d8b30131-f191-453b-a56d-588a321bc701)

### Relevant log output

```console
.
```

**Comment by ehab-hassan** [comment]
I think scrolling for both will be confusing for the user, also when logs are open it takes more than 75% of the screen so scrolling there will not be useless, the user needs to close the logos and normally scroll on the page.

**Comment by samaradel** [comment]
### Work Completed:
Fix the scroll of the main page when the dashboard logger is opened

**Comment by khaledyoussef24** [comment]
the issue is still producible

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/98ce8441-fd25-4601-bba2-53a3d2b7fcc4

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4

scroll now works in the 2 zones in the same time


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/63935341-8089-4076-933e-8bd2461c31c6


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4310896)

**Comment by ramezsaeed** [comment]
Verified on:
- Devnet
- d44ca11
