### ISSUE TITLE
SSH Dashboard, new version: update message

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2759]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The new SSH option in the Dashboard is great but the message isn't clear.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/4f1b3cc6-925c-493f-a35d-a5108a827ad3)

It implies we can edit/remove the SSH keys on the deployment page, but it's only possible on the SSH page: https://dashboard.test.grid.tf/#/deploy/sshkey/.

### Describe the solution you'd like

We could change the text to something like:

"The keys selected here will be forwarded to your deployment. To change keys, simply tap on the keys you wish to select."

**Comment by A-Harby** [comment]
Verified, Devnet 17d861b.
The message have been updated as requested.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a5fc279a-ccbd-4a6f-90d4-825c2ac26470)
