### ISSUE TITLE
Add alert on how to unlock contract in grace period

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2760]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The user has to hover over the grace period chip in the table for him to discover that he can unlock the contract if he has enough balance. This flow might not be intuitive to the user. The user

### Describe the solution you'd like

Add an alert to the user describing what is a grace period contract and how to unlock it.

**Comment by ramezsaeed** [comment]
its a hidden feature, which cannot be fixed right now.
