### ISSUE TITLE
🐞 [Bug]: SSH table can't hold more than 12 keys.

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#2762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- I generated and imported many keys and my total keys was 14 but only 12 appeared in table.

### Steps To Reproduce

1- Open Dashboard 
2- Navigate to `SSH Keys`
3- generate more than 12 keys.

### which network/s did you face the problem on?

Dev

### version

-

### Twin ID/s

-

### Node ID/s

-

### Farm ID/s

-

### Contract ID/s

-

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/525c82c2-6f9b-4207-a96f-88b351577280)

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
Work completed:

Issue happened because of the bottom template used in the table so I removed it. I also unified the pagination w the contracts' tables.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 17d861b
user now can use more than 12 keys

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/790daa5f-2b68-4bb3-96e5-629cb9b87172)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/22ca6a61-b221-459a-ba8f-c58d486b8c2e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0fdc191a-285f-4e70-adc8-b8070c32f6ed)
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430164#case_4289592
