### ISSUE TITLE
🐞 [Bug]: Remove node type `Participant` from algorand application

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Remove option participant from the node type list in Algorand, as the Algorand dashboard was shut down.

https://github.com/threefoldtech/tf-images/issues/256

### which network/s did you face the problem on?

Dev, Main

### version

2.4.2

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/16311211-21df-4557-9c93-7c9e70594229)

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
work done: removed participant node from UI but network error keeps showing up so debugging

**Comment by amiraabouhadid** [comment]
found cause of network error here https://github.com/threefoldtech/tfgrid-sdk-ts/blob/bdcdc46698d8ebfd6d267190265dc9983781b77e/packages/playground/src/components/networks.vue#L140

**Comment by A-Harby** [comment]
Verified, Devnet 0139c63.

The participant option was removed from dashboard and grid client script
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/131e1bd6-2ccf-43e0-8ced-4a2d47c3c1fb)

And I was able to deploy with and without mycelium.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/aacbdcd6-371a-459e-9b89-f673ff32178d)


And opened issue in info grid to update docs https://github.com/threefoldtech/info_grid/issues/567.
