### ISSUE TITLE
🐞 [Bug]: Unable to deploy VM on dashboard through "Automatic" & "Manual" mode of selection due to errors.

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/tfgrid-sdk-ts#2767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When users trying to deploy VM's through dashboard it shows "No Nodes were found" when selecting Automatic Mode.

<img width="553" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/117bf3bd-d99b-461f-a305-e5dec47c3e63">

When selecting the specific Node through Manual selection it shows "**Error getting node 26 Failed to send request to twinId 47 with command: zos.storage.pools, payload: TimeoutError: Didn't get a response after 20 seconds**"

<img width="647" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/2de47937-7f6f-4d74-9ea9-b1d586a29929">

<img width="481" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/ed67ec57-475b-4215-b0e4-72eaa5cc5877">

### which network/s did you face the problem on?

Main

### version

NA

### Node ID/s

All

### Farm ID/s

NA

### Contract ID/s

NA

### Relevant screenshots/screen records

Automatic
<img width="553" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/117bf3bd-d99b-461f-a305-e5dec47c3e63">
Manual
<img width="647" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/2de47937-7f6f-4d74-9ea9-b1d586a29929">

<img width="481" alt="image" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/89931135/ed67ec57-475b-4215-b0e4-72eaa5cc5877">

### Relevant log output

```console
NA
```

**Comment by timurgordon** [comment]
I'm having the same problem using the grid-cli (tried with tfgrid-sdk-go 0.15.3 & 0.15.4) so perhaps its not isolated to the dashboard. Server seems to be always returning an empty list of nodes for deployment requests.

**Comment by timurgordon** [comment]
All nodes are unhealthy according to gridproxy:

https://gridproxy.grid.tf/nodes?healthy=true

**Comment by mahendravarmayadala93** [comment]
It's working again.
