### ISSUE TITLE
Manage ssh key to store the last used key

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2778]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

while deploying some vms every time i have to change the ssh key to use (because it resets to the first ssh key after every deployment)

will it be improtant ? or it will be updated in 2.5.0 for the active key  method?

### Describe the solution you'd like

![Screenshot from 2024-05-26 22-36-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/69b0cd99-cf5a-4c90-a6f7-c3a57b0b39a7)

**Comment by AhmedHanafy725** [comment]
already you can do that on devnet

**Comment by khaledyoussef24** [comment]
verified on devnet and using active algorithm
version : 17d861b


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b136dfb-c686-48ce-8b9c-54e539848d7c)
