### ISSUE TITLE
Full VM: Duplicate Network Contracts

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#278]
### Description

For each Full Vm deployment that i have, there are 2 different network contracts with the same name and different contract ids.

[Screencast from 21-05-23 16:48:11.webm](https://github.com/threefoldtech/playground/assets/101194226/d773ab65-ff6d-4dfe-809a-8d5b7fd3d816)

**Comment by 0oM4R** [comment]
I discussed it with @AhmedHanafy725, as the two contracts that have the same name are not on the same node so it is not a bug.
note: this only happens when the add wireguard access is selected

**Comment by A-Harby** [comment]
Verified,Devnet 7099cbc.
Deployed different solutions with IPV4, IPv6, wireguard and planetary.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/349689a9-8cde-4404-85d0-578fbc33b686)
