### ISSUE TITLE
🐞 [Bug]: Peertube & Funkwhale deployer not consider errors

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After merging this pull request https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2742
peertube and funkwhale didn't respect clicking deploy as other applications did ... right now clicking deploy - no matter how many errors in form - will just start deploying an instance cause an error happen to user

### which network/s did you face the problem on?

Dev

### version

2.5.0-rc1

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/a7708bf6-9924-4908-a88c-f0f342d7d0d8)

### Relevant log output

```console
Nothing
```

**Comment by MohamedElmdary** [comment]
Kubernetes also have an issue
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/0f55fbab-f6ed-49da-ab5f-31d7f4af77d7)

**Comment by MohamedElmdary** [comment]
Static Website also got the same issue

**Comment by khaledyoussef24** [comment]
fixed and verified on devnet
version : ad30945
now the deploy button is working fine


and even tried to trigger the deployment button while any field is not filled and deployment failed and asked me to continue the details


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a062ef9a-d0e9-4e7d-91d8-0047e422673b)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d0bbd56b-7380-46c9-9f09-d4f7194e510c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1aa886bb-8206-4480-b33d-9f771289fccf)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d1b24369-fb3e-4f5f-b7ee-85d161089ff2)

same for peertube
could not deploy until all fields are filled right



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eeb033e0-77b0-4153-8614-b9f8cd44f897)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a3d2c2d5-c0a5-4cc2-9eb4-53a753b33ee1)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/95c03d6f-a2d3-4685-bfc5-fa963a1732ea)



deployment tried and working fine
static website
node pilot 
next cloud 
will check deploy button in others as well but working fine for now
