### ISSUE TITLE
Present apps in alphabetical order

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2787]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Currently, the apps are not organized logically.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/5598c839-65ba-4c98-87ec-50d637ebe06e)

### Describe the solution you'd like

Present the apps in alphabetical order

Algorand, Caprover, Casperlab, etc.

It's a small detail but it makes the site looks suboptimal.

**Comment by khaledyoussef24** [comment]
verified on devnet
apps are now presented in alphabetical order
version : d806ab4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e230fe0-2fb2-4f6a-a3ab-bb158fcc0a91)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4292304

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ad30945
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/960afa4b-f916-41ad-b455-7a0ccc31ab3b)
