### ISSUE TITLE
Kubernetes deletion is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#279]
### Description

Unable to delete a kubernetes cluster.

When i tried to delete a k8s cluster it loaded for only a couple of seconds and when the deployment list appeared again the cluster also appeared and nothing was deleted.

[Screencast from 21-05-23 16:38:45.webm](https://github.com/threefoldtech/playground/assets/101194226/877ddeed-1630-4882-86ae-41a48ea1a3e3)

**Comment by A-Harby** [comment]
Verified, Devnet

Deployed and delete 2 kubernetes master with/without a worker and both were succesfully deleted.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2398cd60-d897-4fa0-ad20-f5ff26cb6841)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/16dc8ec9-5651-48b5-b293-f0144985e355)
