### ISSUE TITLE
No error on network failure with node finder and no option to retry

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2790]
I noticed the following behavior on the node finder:

1. While my network connection was not super reliable, I tried filtering on a node id that I know is valid
2. The result is just "no data available"
3. The *Apply* button becomes greyed out, so I can't try again

There's two things I think can be improved about this:

1. Present an error that network communication failed when that's the reason for no data (versus no data returned on a successful backend query)
2. Allow the user to retry somehow when network comms is the cause of failure

**Comment by maayarosama** [comment]
Work completed:

Added an error variable which in case of error will display an error alert and a retry button

**Comment by A-Harby** [comment]
Verified, Devnet 0d964e5.

An alert with an error message and a retry button have been added. 
![image](https://github.com/user-attachments/assets/de78f069-143a-47ab-b35d-bfa5b6d4cb87)

[TC2735 - Retry on failed filter](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4318312)

**Comment by scottyeager** [comment]
Looks good, thanks!
