### ISSUE TITLE
Add network usage to pricing calculator

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#2791]
Let's add another input to the pricing calculator that's labeled "Estimated bandwidth usage per month in GB" or something similar. Then the user can also understand how the cost of bandwidth will affect the total monthly cost of their deployment.

**Comment by khaledyoussef24** [comment]
added and verified and it in the calc.
version : b91fde4




![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/381af7a4-605a-4299-8e0c-254ecf731e7c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b8c51409-a781-43fc-95f3-e82869fdc14e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a003d1c-e5b4-4eb7-9ee2-cd46c77313e0)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31982aa6-1b31-46a8-b5b3-e1fc27959398)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4292349

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ad30945

![Screenshot from 2024-06-06 18-19-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/18ac3c16-e2bb-48cc-8e82-8a7e8e83725f)
