### ISSUE TITLE
🐞 [Bug]: unclear error while deploying full vm

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while deploying a full vm deployment failed and got unclear error message

### which network/s did you face the problem on?

Main

### version

2.4.2

### Twin ID/s

3680

### Node ID/s

2150

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0be6ff5c-4a1f-4cc4-b319-bfd68230511d)

**Comment by AhmedHanafy725** [comment]
The node won't send an uptime report (become offline) if the disk is read-only https://github.com/threefoldtech/zos/issues/2134

**Comment by AhmedHanafy725** [comment]
and this issue for better error messages #2841

**Comment by khaledyoussef24** [comment]
could not produce the same error again will open again if i could reproduce it
