### ISSUE TITLE
🐞 [Bug]: listing requests got triggered twice on mount contracts page

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

after opening contracts page, tables are reloading twice, This happens because `Update:options` is triggering while mounting the table with init values, and loadContracts are also triggering in onmount function.

### Steps To Reproduce

1. open https://staging.dashboard.dev.grid.tf/#/deploy/your-contracts/
2. each table will be in loading state twice

### which network/s did you face the problem on?

Dev

### version

2.5.0-rc1

### Relevant screenshots/screen records

I set network throttling to slow 3g, to make it easy to catch
[Screencast from 28 ماي, 2024 EEST 05:24:42 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/b9667332-c066-4ed1-b197-94f736d2ae21)

### Relevant log output

```console
N/A
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 
### Work done

Enhance the contracts list by removing the duplicate requests, and reduce the time limit when loading the contracts by removing the `onMounted` lifecycle

#### Changes

- Removed the 'onMount' from the 'onMounted' life cycle since it is not needed because we call the 'loadContracts' function on each change that happens on the table.
- Fix the contracts table takes too much time to load.

#### Screenshots/Video

 [Screencast from 06-04-2024 06:46:01 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1ae65b10-66d1-4666-860a-b3d662092af4)

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done

Enhance the contract list view:
- Replaced the static values with `ref` concept to change the value when needed.
- Cached the nodes to use it when re-request to avoid duplicated requests.
- Enhanced the list time by using the `Promise.all()` and displaying what gets finished.
- Introduced a new hint alert to inform the user that the table will be reloaded in a bit.
- Replaced the `update-options` event with the `update-page` and `update-size` events to avoid requesting each change that happens on the table and only request when changing the `page/size`.
- Created only one function to request to list the contracts based on it's type.
- Returned the `onMounted` life cycle and called the 'loadContracts' inside it.
- Remove the duplicate requests.
- Updated the `getNodeInfo` function to request only the nodes that are not cached.

**Comment by khaledyoussef24** [comment]
verified and working fine on devnet
version : ad30945

- the duplicate requests are now removed 
- Introduced a new hint alert to inform the user that the table will be reloaded in a 8-10 seconds.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c2517586-7798-45ee-836f-7894607ffaae
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/34e44efb-c0ea-446e-93b4-af889126a313
