### ISSUE TITLE
Unable to delete kubernetes workers 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#280]
### Description

Deleting workers from a kubernetes cluster is not working.

After selecting a worker and clicking on delete, it takes a couple of seconds then both workers disappear and they also disappear from the deployment details and the number of workers is changed to 0. however when you navigate to the contracts list you will find that the contracts were not deleted and when you navigate back to the kubernetes tab you will find both workers available and none of them was actually deleted.

[Screencast from 21-05-23 16:32:27.webm](https://github.com/threefoldtech/playground/assets/101194226/d0ab233e-0619-4541-af4e-2212bf454eaf)

**Comment by MohamedElmdary** [comment]
@AhmedHanafy725 Please check this error
```
Error while deleting worker TypeError: Cannot read properties of null (reading 'deleteReservedIp')
    at KubernetesHL.<anonymous> (base.js?t=1685009158497:200:29)
    at Generator.next (<anonymous>)
    at fulfilled (base.js?t=1685009158497:4:58)
```

**Comment by A-Harby** [comment]
Verified, b6c6d97.
Deployed many instance of a kubernetes worker and were all delete successfully.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/857e5757-35cc-44db-8073-55c75dae01e7)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3adcedb0-d4a8-45a4-9093-95b9af224c76)
