### ISSUE TITLE
(Mainnet Verification) 🐞 [Bug]: Some shared GPU nodes have discount icon

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Some shared GPU nodes have discount icon and when hover on it, nothing happens.

### Steps To Reproduce

- Change network to main locally
- Filter with GPU in Node Finder

### which network/s did you face the problem on?

Main

### version

v2.5.0-rc1

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/8f956b0a-3c85-4b9b-81bc-6a4a2a56e11a)

### Relevant log output

```console
-
```

**Comment by khaledyoussef24** [comment]
verified on mainnet
verson : 2.5.2
now only nodes which are able to be rented have discount rates


![Image](https://github.com/user-attachments/assets/ee4808f2-a0a3-48cf-8b5c-db80f5900e04)
![Image](https://github.com/user-attachments/assets/4bd5b8fe-116b-48d7-a78c-a3e1f37211dd)
![Image](https://github.com/user-attachments/assets/f667d005-3f7b-4ec8-b46e-239779df455d)
![Image](https://github.com/user-attachments/assets/e6864a17-c792-4185-98f8-198c84615eac)
![Image](https://github.com/user-attachments/assets/63510311-1b4f-4fe8-bcdf-d43befcd92f3)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4264048)
