### ISSUE TITLE
🐞 [Bug]: Fix node card style

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- Node ID and farm details position is not right.
- Reserve text is not shown

### Steps To Reproduce

- Go to staging
- Navigate to Node Finder
- Filter by dedicated, rentable & up nodes

### which network/s did you face the problem on?

Dev

### version

fa1f347

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/663fbd90-cffc-4b51-b34c-e56f13f7604e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/efebfeef-5719-475c-93a5-e021e21b5dcb)

### Relevant log output

```console
-
```

**Comment by amiraabouhadid** [comment]
@zaelgohary please specify screen dimensions at which this issue occurs

**Comment by zaelgohary** [comment]
> @zaelgohary please specify screen dimensions at which this issue occurs

Button color and background color should be the same in all dimensions.

**Comment by amiraabouhadid** [comment]
issue seems to be from new vuetify version because node ID title has no styling implemented

**Comment by A-Harby** [comment]
Verified, Devnet ccab3f0.

[TC2250 - Nodes Cards Table Information](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150459)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8a977bf3-4db4-4cd6-b995-edd523f3defc)

**Comment by ramezsaeed** [comment]
![Screenshot from 2024-06-06 18-16-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/af065440-dc4f-407e-8cef-27731036e449)
![Screenshot from 2024-06-06 18-16-10](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5c6dc3b9-4d42-47e1-9dd1-22394c559e4d)
