### ISSUE TITLE
New design for showing the node's price and discount

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#2805]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

the current view lacks some info like the price before and after the discount,...

### Describe the solution you'd like

it should be shown in a tool-tip only for the dedicated nodes when the user hovers over the price or the reserve button and should include
- the discount
- The price before the discount.
- The price after the discount.
- Price/month
- Price/hour
- How many TFTs are required to unlock more discounts (better to show them in packages(bronze, silver, and gold))

**Comment by ehab-hassan** [comment]
WIP
Investigate the best way to show all details

**Comment by ehab-hassan** [comment]
WIP
still investigating the best way

**Comment by AhmedHanafy725** [comment]
let's go with option 1

**Comment by amiraabouhadid** [comment]
Work done: added table of packages

**Comment by amiraabouhadid** [comment]
Debugging vuetify hide sort in v-data-table

**Comment by khaledyoussef24** [comment]
verified on devnet
version : cddbd85



![Image](https://github.com/user-attachments/assets/e035934b-2120-4c3a-8bee-c5cff24fd53a)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4264048)
