### ISSUE TITLE
🐞 [Bug]: fqdn gateway not working with vm manage domains

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

can't deploy fqdn with manage domains in fvm and micro vm

### which network/s did you face the problem on?

Dev

### version

latest

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by A-Harby** [comment]
Verified, Devnet ccab3f0.

FullVM
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c0b602b6-c054-43b4-9ca5-7ff6e078af91)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b53dad39-bd0a-4236-b4f2-bbb5a1d9436c)
MicroVM
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/116bbb64-f6e3-4145-bd52-1f16b1c3d18d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d08505e9-e08c-4bbd-9ace-fcee687478bc)
