### ISSUE TITLE
🐞 [Bug]: Peertube instance: loading circle always on screen

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#2809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- Deploying a peertube instance
- uploading a video
- the video always has the circle loading screen

### Steps To Reproduce

- to see the bug go to this website and check the video: https://seninsayfan.site/videos/watch/8aa7ac7d-03f4-4d17-a4f4-1a3d6fa962c5

### which network/s did you face the problem on?

Main

### version

latest

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/b807b51f-8d99-4a6c-aeac-028a05afccae)

### Relevant log output

- json output

```console
{  "version": 0,
  "contractId": 461138,  "nodeId": 159,
  "name": "pthttdl",  "created": 1716826989,
  "status": "ok",  "message": "",
  "flist": "https://hub.grid.tf/tf-official-apps/peertube-v3.1.1.flist",  "publicIP": null,
  "planetary": "301:4b18:eda3:6a68:3631:54fd:e7ca:93b8",  "myceliumIP": "52d:7837:b555:fac8:ff0f:0:400:2",
  "interfaces": [
    {      "network": "nwj93x0",
      "ip": "10.20.4.2"    }
  ],  "capacity": {
    "cpu": 2,    "memory": 6000
  },  "mounts": [
    {      "name": "diskxni",
      "mountPoint": "/data",      "size": 53687091200,
      "state": "ok",      "message": ""
    }  ],
  "env": {    "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC59pzj902ur6MzxmtIIdbpte4PEBVoRQwtFnMIpiKC2aO8PEgoVE3BtjI6I5P70v41Bu0Ki85fMATcrsXeF4l//UPQf2ZpMpZsmUOFVI8aWP7+QDVLtfGDZK1b4jZop3SgZpel8z9ZrfRnCHzONZ0CsX0DUwmmkzT5IVOXBujIuxZA+R0o/xiy75Ja7qw4phAv/j7G6YUiLUTlD+lAmf5dOuTEbQI8orSEc8m0D45eGqCZF7+6saI3xkS6A+e9Y7ysNqGd+KE09xZaJL5EM0AAJOKNbCHyJKkJXoA72TstSXFFokuP//5BrEqz+M7y8I2x7pmDBNVQndVyA1832sVD+U4F5CXbiLw1nH/RJHUaGDNkQjUOvPvXQdi6zdO4vFgPSWznVUJNRFDiVDmC7oT85faym5P4XPP0tyAFLHjVO9FQIBpIVMuSnqqXoTIMHG3Pvc+1X/EJ4anQmrfDOMNI6wMUFN1/0jIAhpUcbeS8pkIJjRm3pChjoQ4jTnbTEP0yvWFPrKnOHNByzpXMlGsz7UsR0bFroxizre8EfybSYUZAjkiCmD2ED+7n6BW4xGPP8oVxQzUz3nkxZT5FT7XKgoevuffBch8YdSFXPcX9bdnUQ3oKiLSRl4fUQRj2KqPqU0cp8ThawBaMjULlihvqMwsQ+gUWhMpOb2YzcFEivw== Threefold",
    "PEERTUBE_ADMIN_EMAIL": "bayramak1989@gmail.com",    "PT_INITIAL_ROOT_PASSWORD": "4XCE8nyzx5xH",
    "PEERTUBE_WEBSERVER_HOSTNAME": "seninsayfan.site"  },
  "entrypoint": "/sbin/zinit init",  "metadata": "",
  "description": "",  "rootfs_size": 2147483648,
  "corex": false,  "gpu": [],
  "deploymentName": "pthttdl",
  "projectName": "peertube/pthttdl",  "billing": "0.797 TFT/hour",
  "wireguard": "[Interface]\nAddress = 100.64.20.3/32\nPrivateKey = 4Amvie00sE7XsPDuJdBgI7SCrNFwWrdmUFHgqFAepxM=\n\n[Peer]\nPublicKey = RSj+BbsfbGdBOkSFtJzi6jL0Wb4ptqjGq8f+QEUxHRA=\nAllowedIPs = 10.20.0.0/16, 100.64.20.0/32\nPersistentKeepalive = 25\nEndpoint = 83.231.240.119:4626"}
```

# Node Stats

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/77026219/9bad3467-0e78-4b51-9d28-563c98ff51c9)

**Comment by AhmedHanafy725** [comment]
I can confirm that happened with me too, there is an issue with updating peertube image https://github.com/threefoldtech/tf-images/issues/268, so let's recheck it after

**Comment by ghost** [comment]
I used the newly upgraded flist mentioned in https://github.com/threefoldtech/tf-images/issues/268#issuecomment-2199711243 and seems like the issue is persisting

[Screencast from 08-25-2024 04:21:30 PM.webm](https://github.com/user-attachments/assets/28ff1f85-9b16-4eda-9a64-039408ad9587)


![image](https://github.com/user-attachments/assets/e8c30413-cd6f-4899-aa04-d0ecb30aa931)


**PS:** Worked after refreshing the page

**Comment by ghost** [comment]
The flist updated and promoted
https://github.com/threefoldtech/tf-images/issues/268#issuecomment-2308916300

**Comment by A-Harby** [comment]
Devnet, 448a213.

its still showing the loading circle even when the video is fully loaded.
![image](https://github.com/user-attachments/assets/7fc312ae-b208-4450-8e76-c753692c8541)

I'm using the default peertube flist `https://hub.grid.tf/tf-official-apps/peertube-v3.1.1.flist`

**Comment by Mahmoud-Emad** [comment]
it'll work normally after refreshing the page, based on @AhmedHanafy725 it's okay

**Comment by ramezsaeed** [comment]
It regarding peertube, not our side.
for now refreshing the page solve the issue.
