### ISSUE TITLE
integrate security audit for commits and before releasing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2810]
integrate security audit for commits and before releasing to avoid security vulnerabilities, maybe can be in the precommit to run npm audit or as part of the PR checks or any other reasonable option

**Comment by zaelgohary** [comment]
Work completed:

Add audit-fix script & workflow to run on push & PR.

**Comment by khaledyoussef24** [comment]
the work flow is added and running.
even duplicate issue creation is added to avoid duplication of issues
issue #2978 is created to solve the missing Security Vulnerability


![Image](https://github.com/user-attachments/assets/8f805aef-5b9e-4235-b89c-5404d21fa120)
![Image](https://github.com/user-attachments/assets/276a60f4-3725-40b5-a238-0a4f7defe791)
![Image](https://github.com/user-attachments/assets/098eeb6b-0618-4042-b0ac-fc7c1e6448f0)
![Image](https://github.com/user-attachments/assets/b383c9ec-f008-4cba-8b25-29b9e4952a11)
![Image](https://github.com/user-attachments/assets/dfc67a22-f790-4223-91fd-0503f846798a)
