### ISSUE TITLE
🐞 [Bug]: Error getting last deployment date

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/c308c104-86e0-4161-9821-8573148c9cc9)

### Steps To Reproduce

- Go to Dashobard
- Navigate to Node Finder
- Open the console

### which network/s did you face the problem on?

Dev

### version

bdcdc46

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b451e1e7-25e8-487a-bbd5-05713b90b2ae)

### Relevant log output

```console
-
```

**Comment by samaradel** [comment]
blocked on https://github.com/threefoldtech/tf_operations/issues/2587

**Comment by samaradel** [comment]
### Work Completed: 

Fix nodes ```last deployment timestamp``` in the node finder

**Comment by khaledyoussef24** [comment]
verifed on devnet 
version : 0d964e5
 getting last deployment date working fine and no errors on console


![Image](https://github.com/user-attachments/assets/05b18549-671f-46ee-901f-f3546a8e36f4)
