### ISSUE TITLE
[Qanet] Add a way to see the node I rented

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After I reserve a dedicated node, it is hard to find it again, especially on the mainnet, where there are a lot of dedicated nodes. There isn't a way to show it in the node finder; I have to find the node ID from your contract page and then filter it in the node finder.
 
The mine tab was a lot better and easier, or maybe add a filter for nodes rented by me or at least sort the node in node finder by rented for me first.

### which network/s did you face the problem on?

Dev, Main

### version

2.4.2

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
can we implement a Mine filter showing the nodes rented by me in the node finder .

**Comment by khaledyoussef24** [comment]
the mine filter is added but will wait to qanet to verify it

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e11eb32d-f314-4a7d-aff6-f1611ca4085c)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f6b7fefc-c5be-4415-841f-20d913f80d86)

**Comment by A-Harby** [comment]
Verified, Devnet cddbd85.

The mine filter is added, and the nodes I rented are listed successfully.

![image](https://github.com/user-attachments/assets/376e8b09-aa43-4af9-a0e1-b2b54f19903c)

New test case: [TC2747 - Filter Nodes by Mine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4335955).

**Comment by ramezsaeed** [comment]
I think better name can be used "My Nodes"

**Comment by khaledyoussef24** [comment]
verified now there is a filter called my nodes![Image](https://github.com/user-attachments/assets/378f9269-d5ca-4e3d-822b-a871c9ec930e)
![Image](https://github.com/user-attachments/assets/aea29625-29d8-46ec-9ebb-b0ef19a29d99)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4364094)
