### ISSUE TITLE
Upgrading the static website flist to the official one

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#2817]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Currently the flist used for the static website application isn't an official one

### Describe the solution you'd like

Use the official flist instead.

**Comment by maayarosama** [comment]
Blocked on
 - #https://github.com/threefoldtech/tf-images/issues/259

**Comment by khaledyoussef24** [comment]
already verified on #2088 and tried deployment and flist is working fine on machine


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dc4dfac0-2586-4569-94ba-b3095efbeecd)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/81cf8365-f2bc-466d-9985-877cb86c3449)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4289467
