### ISSUE TITLE
Kubernetes: Deployment details improvement 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#282]
### Description

The kubernetes deployment details include some fields that are not necessary and should only be available in the json tab.

all of these fields are not really important and not needed to be displayed in the details and if they're needed at anytime the user can get them from the json tab. (This applies for both the master and worker tabs)

![image](https://github.com/threefoldtech/playground/assets/101194226/66091321-6bb9-41d5-95e8-4752a355b755)

And at the top of the list, a space should be added between these buttons.

![image](https://github.com/threefoldtech/playground/assets/101194226/9005ab29-c393-49b2-bc75-d417ffc10e83)

And the Name tab in the deployment name should display the cluster name not the name of the master.

![image](https://github.com/threefoldtech/playground/assets/101194226/aa48fd39-28eb-43dc-b500-5a223e2a4396)

**Comment by A-Harby** [comment]
Verified on Devnet, 9227221.

Unnecessary items were removed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cf0cc6c4-a314-4f62-96a5-34a7b752ff7e)
Space was added between deployments name.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7b58eb51-617a-4a48-b42c-21ada897fa65)
Name was updated to display actual name.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/24ba44fb-bf81-487a-824f-14ccefc21ac0)
