### ISSUE TITLE
🐞 [Bug]: Add validation to compute capacity module

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

No errors were thrown when testing with invalid min, max, empty values, and decimal values. 

### Steps To Reproduce

Run the following test: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/2820/files

### which network/s did you face the problem on?

Dev

### version

Locally

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by MohamedElmdary** [comment]
We can add a `MethodDecorator` which should validate object before trigger the targeted function

```ts
function TriggerValidate(): MethodDecorator {
  return <T>(
    target: object,
    propertyKey: string | symbol,
    descriptor: TypedPropertyDescriptor<T>,
  ): void | TypedPropertyDescriptor<T> => {
    function value(...args: any[]): any {
      const errors = validateSync(target);

      if (errors.length > 0) {
        console.log({ errors });
        throw new Error("Something went wrong");
      }

      return target[propertyKey]?.(...args);
    }

    return {
      ...descriptor,
      value: value as T,
    };
  };
}
```

which can be used like
```ts
class Zmount extends WorkloadData {
  @TriggerValidate()
  challenge(): string {
    return ''
  }
}
```

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/03319d0a-3f3a-41a1-b787-2818a31c6a1e)

**Comment by zaelgohary** [comment]
Work completed:

Implemented a way to validate class prop/methods when set/call.

- feat: Add a class decorator with options to validate any needed prop/method
- feat: Use Validate class decorator in ComputeCapacity class to throw errors when needed
- chore: Remove skip from tests and run them using SKIP_PROPS_VALIDATION=true env var
- feat: Included SKIP_PROPS_VALIDATION to grid client workflow so tests won't fail

**Comment by khaledyoussef24** [comment]
verified compute capacity is now added to the gridclient tests module and ran the test and it is working fine


![Image](https://github.com/user-attachments/assets/97495c3d-d764-44d3-aefa-61b76812bf64)
![Image](https://github.com/user-attachments/assets/2f8e33a0-39f9-463c-9c72-71c8e32fe211)
![Image](https://github.com/user-attachments/assets/8df25da6-257d-4759-9cf2-7068cb2a322f)
