### ISSUE TITLE
🐞 [Bug]: Twin Not Authorized to cancel contract; Can't batch delete my contracts

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried deleting a lot of my contracts, and I keep getting that error multiple times.

### which network/s did you face the problem on?

Dev

### version

bdcdc46

### Twin ID/s

1174

### Relevant screenshots/screen records

[screen-capture (5).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5e7907b1-893a-40df-8556-e772473b3890)

[dashboard (5).log](https://github.com/threefoldtech/tfgrid-sdk-ts/files/15502146/dashboard.5.log)

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
couldn't reproduce this issue on staging i tried to delete 50 contracts 
[Screencast from 04 يون, 2024 EEST 03:48:06 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7afb9469-4ef3-4694-b451-67fb569fd19f)

i think the issue got resolved here [#2485](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2485)

**Comment by A-Harby** [comment]
Verified, Devnet.

I was able to delete all the contracts after @0oM4R, tried and deleted some of them.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c2ea46e8-00b7-4559-9036-8c52ae485948)


I don't know what the error was or the cause of it, but I will close the issue and reopen it if it recurs again.
