### ISSUE TITLE
🐞 [Bug]: pricing calculator is broken

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#2826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

pricing calculator is disabled 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/29899572-87fa-4c0d-a13c-59f1f5db4218)

even when enabled ipv4 and entering bandwidth data
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/8b1c0c74-c2c9-4238-a97a-97337200d129)

It works only when I toggle the use my balance couple times
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0db02cff-3c36-46d1-b396-22ae23460680)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c5beb78e-501c-4b6c-8650-cbc498729572)

### Steps To Reproduce

- go to staging.dashboard.dev.grid.tf
- then go to pricing calculator

### which network/s did you face the problem on?

Dev

### version

bdcdc46

### Relevant screenshots/screen records

All added to the body

### Relevant log output

```console
All added to the body
```

**Comment by zaelgohary** [comment]
Work completed:

Issue happened because of type mismatch in balance field when balance is being updated. Edited _applyRules function to stringify the value before running any validations. Also, changed balance rule to isNumeric instead of isInt.

**Comment by khaledyoussef24** [comment]
tested and verified on both qanet and testnet
v2.4.3
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/02b3d8f0-b531-464e-9f40-1f8b9b3e65b4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ebbfcb95-86aa-4068-a940-cb562c97c273)

**Comment by ramezsaeed** [comment]
Verified:
- Testnet
- version: 3.4.3


Tested with:
 - new account (0 tokens) w
 - existing account (with and without toggling my balance) 
 - for each do logout


![Screenshot from 2024-06-02 17-07-39](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/86c9753e-199e-475f-be5d-ca588ba28b1d)
![Screenshot from 2024-06-02 17-02-28](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/888e26d9-c7c5-4458-83e3-031d764c0fd8)
![Screenshot from 2024-06-02 16-55-08](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/5052a196-08e4-4db6-8bed-35a9debde23a)
