### ISSUE TITLE
🐞 [Bug]:  loading nodes on mainnet stuck

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-ts#2830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I was trying to deploy a micro vm on mainnet the loading is stuck in loading node while saying press `load nodes` and no button with this label exist

### Steps To Reproduce

in mainnet try to deploy a  microvm 

### which network/s did you face the problem on?

Main

### version

2.4.2

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/1689456/53c418b6-971e-43db-a35a-53833eb1b59b)

### Relevant log output

```console
no logs
```

**Comment by AhmedHanafy725** [comment]
can we try it on a slow network?

**Comment by zaelgohary** [comment]
@ashraffouda I tried multiple times on slow 3G network and couldn't reproduce the issue. Can you try again? and if faced the issue again, can you attach the logs from the Dashboard logs?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f2596601-4e24-4681-89b7-3256fee762c8)

**Comment by ashraffouda** [comment]
didn't happen with me again u can close until we see it again
