### ISSUE TITLE
🐞 [Bug]: subsquid instance fail if I provided a websocket entrypoint

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried deploying multiple instances of subsquid with different websocket entry points, which I tried before and was working fine, but now it all fails, and only the instance will work if the websocket entrypoint is left empty!.

### Steps To Reproduce

1. Connect your wallet.
2. Navigate to applications under the deploy section in the sidebar.
3. Navigate to the Subsquid page by choosing the Subsquid card.
4. Type in a valid websocket entrypoint (eg. `wss://polkadex-mainnet-rpc.dwellir.com`) and choose a domain.
5. Deploy (it will not work).
6. Now try the same steps without typing any websocket entrypoint. 

### which network/s did you face the problem on?

Dev

### version

2.4.3

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
I successfully deployed a Subsquid instance using the same endpoint provided in the issue and was able to access the domain.

![image](https://github.com/user-attachments/assets/2319d0bc-4c86-4806-a291-8e20aa16b298)


![image](https://github.com/user-attachments/assets/60151f71-e9eb-470e-beaf-cce96de61a81)


When trying to deploy with an empty endpoint, validation blocks the deployment.

![image](https://github.com/user-attachments/assets/65b1e2a8-edde-47fb-96ee-2046555217e3)

@A-Harby Can you verify?

**Comment by A-Harby** [comment]
Verified, Devnet a66e759.

Yes, it doesn't show the error anymore.
![image](https://github.com/user-attachments/assets/48b59282-2cdf-4290-a805-0e924007b95b)
![image](https://github.com/user-attachments/assets/20321947-e3c0-49e4-ba3a-73ffeba3f511)
