### ISSUE TITLE
🐞 [Bug]: Double requested disk size while filtering nodes

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Double requested disk size while filtering nodes
```ts
{
  sru:
      (filters.ssdDisks || []).reduce(
        (t, s) => t + s,
        (filters.solutionDisk ?? 0) + (filters.rootFilesystemSize ?? 0),
      ) || undefined,
}
```

`sru = disks + solutionDiskSize + rootFsSize`

### which network/s did you face the problem on?

Dev

### version

latest

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/0fa5bf2e-02da-41dd-8e68-fc69ece54415)

### Relevant log output

```console
None
```

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0139c63
the sru of the results = the required sru + root file size

![Screenshot from 2024-06-09 14-20-27](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/75eff639-d95e-403d-b6eb-b1a57dd5389c)
![Screenshot from 2024-06-09 14-20-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e61c3981-fc8a-47ea-a771-6d16ccdb1aeb)

not double the size as before
