### ISSUE TITLE
🐞 [Bug]: Admin Email text box in the mail server tab has no validation when deploying Discourse instance.

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#2838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

when I tried to deploy Discourse instance, I observed that the Admin Email text box under mail server tab has no validation,   I just clicked space at this box then the deploy button being active and the deployment was successfully done. 

### which network/s did you face the problem on?

Main

### version

2.4.3

### Relevant screenshots/screen records

![Screenshot from 2024-06-03 11-29-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/7ac066c7-02f8-490f-b63d-8a88f634dc43)

![nosmtp](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/034bb717-94b2-4433-8c0b-41147ca9893f)

### Relevant log output

```console
-
```

**Comment by maayarosama** [comment]
Work completed:

Added validation to admin email

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0d964e5

can not deploy with out an email and email has it's own validations 


https://github.com/user-attachments/assets/22d4aa12-77ac-4343-9ba6-caa288b0c533
![Image](https://github.com/user-attachments/assets/b1a47369-8902-44b9-aea6-ed6f809c1511)
![Image](https://github.com/user-attachments/assets/3cd2837a-4102-49a9-b81c-3635d15e5dc2)
![Image](https://github.com/user-attachments/assets/76526c98-11ec-4656-b1ff-1359b44b1ca4)
