### ISSUE TITLE
🐞 [Bug]: UI fix domain name input in manage domains 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Fix the input size of the gateway name when adding domain to a vm.

### which network/s did you face the problem on?

Dev

### version

17d861b

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/07b67fba-7b04-473f-8125-4cc2a3e45bd4)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
The same issue is happening with the email input.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/97b49aac-c9c2-4cb8-9c30-10d919d663a9)

**Comment by samaradel** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/6fd59166-5de0-49dd-bceb-f28871a47dd7)

**Comment by khaledyoussef24** [comment]
verified and fixed on devnet
version : 2b7ab4e




![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8159aaf2-a3b9-4b65-bb01-db094ee88d13)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3b05cd97-71f4-4702-b855-125dff917da2)

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/51cb9fa7-05db-464d-9ca5-10056d6e3563)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8172e0d4-f264-4b52-8858-c50e6ff132ee)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8090c041-3e02-4235-818d-208d2ca89e18)
