### ISSUE TITLE
🐞 [Bug]: Farm IPs table pagination is removed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The farm IP table pagination has been removed from the farm table, and I can only see the first 5 IPs.

And there was a sorting feature on the table, and now it only sorts the deployed contract ID column.

### Steps To Reproduce

Just create a farm and add more than 5 IPs.

### which network/s did you face the problem on?

Dev

### version

17d861b

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4803ed62-75d3-4157-b561-b9875f1b6cfe)

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
will list all ips for now, and there are some issues for the pagination 
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2886

https://github.com/threefoldtech/tfgrid-sdk-go/issues/1067
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2884

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945

pagination removed and now ips are just listed.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c927150d-3ce0-4184-853d-bbc6e47bed68)
