### ISSUE TITLE
🐞 [Bug]: TF Robot(dashboard applications) docs redirecting to tf robot sdk guide

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

TF robot docs from the dashboard redirects to the sdk (how to install and configuration )

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![Screenshot 2024-06-04 at 11 19 42 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/dd20f2cb-6586-402e-a106-e6a003c4691f)
![Screenshot 2024-06-04 at 11 19 53 AM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f9d87175-eea4-4656-9c49-641d54ef8356)
it should redirect to another docs for using the machine or the deployment in the dashboard section not the developers section

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
may this docs also containt tfcmd , tf-grid-cli ,tf robot which are also installed on the vm

**Comment by ramezsaeed** [comment]
@khaledyoussef24 please open an issue in info_grid too

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/info_grid/issues/563

**Comment by Mik-TF** [comment]
@zaelgohary 
Good to go on the manual side.

Amazing addition to the Dashboard guys! Will clearly explore that one.

**Comment by zaelgohary** [comment]
> @zaelgohary Good to go on the manual side.

Will update the URL once the PR is merged.

**Comment by khaledyoussef24** [comment]
@zaelgohary it is not updated yet 


![Image](https://github.com/user-attachments/assets/edb81a77-a4ea-4c13-b902-ebe2771754dc)
![Image](https://github.com/user-attachments/assets/6c8dfeb9-1c5d-4df8-937b-98c09aa2d775)

**Comment by zaelgohary** [comment]
> @zaelgohary it is not updated yet

Done.

**Comment by khaledyoussef24** [comment]
version : 184fa12
verified on devnet
tf robot has it's own docs now


![Image](https://github.com/user-attachments/assets/4663f6c8-a3cf-4370-8ece-b27b0e0a1994)
![Image](https://github.com/user-attachments/assets/a4475ac7-a352-41c5-ab68-d5e99a640302)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4347172)
