### ISSUE TITLE
🐞 [Bug]: No message to handle K8s deployment errors

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I'm trying to deploy K8s and I got nothing

### which network/s did you face the problem on?

Dev

### version

c30c991bca4f18b5eea14afd0d4962093850a527

### Relevant screenshots/screen records

[Screencast from 04-06-24 11:46:21.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/4f453875-cdb2-4898-b80e-476934d222b2)

### Relevant log output

```console
N/A
```

**Comment by MohamedElmdary** [comment]
can't reproduce this issue on development branch

**Comment by A-Harby** [comment]
Verified, Devnet, ccab3f0.

Kubernetes is now working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5a166e54-44b3-4f06-9fb3-6eefcd675515)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7d82777c-761c-4829-8da9-2c8352ee5cc9)
