### ISSUE TITLE
🐞 [Bug]: Nodes country chip looks weird 

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#2852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

some of nodes have an empty/weird country chips

### which network/s did you face the problem on?

Dev

### version

c30c991bca4f18b5eea14afd0d4962093850a527

### Node ID/s

87, 172

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/56d0a5ad-b122-4e57-b51e-d16ab3ae2137)

### Relevant log output

```console
N/A
```

**Comment by zaelgohary** [comment]
Work completed: 

Location string had spaces in it. Checked for the length after trimming the string.

**Comment by khaledyoussef24** [comment]
the issue still exist:


![Image](https://github.com/user-attachments/assets/a6b4fd3c-8921-4300-8a64-4b47a8d8fb36)
![Image](https://github.com/user-attachments/assets/96ee305e-ef75-4ce3-a3bd-6d9b09ed43de)
![Image](https://github.com/user-attachments/assets/5c569c46-63ba-44fe-a7d0-b8c1482473e6)
![Image](https://github.com/user-attachments/assets/bf1312c2-21dc-435b-95b6-01b2f314baaf)
![Image](https://github.com/user-attachments/assets/4eced827-26f0-4d03-903b-bb718d533603)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : c112478
the nodes with this weird empty chips is fixed and no longer exists
<img width="1112" alt="Screenshot 2024-08-05 at 9 52 11 AM" src="https://github.com/user-attachments/assets/d072958c-7259-4376-a99a-d701792509db">
