### ISSUE TITLE
navigating to the any solution tab gives invalid message

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#286]
### Description

after navigating to any solution tab gives invalid before clicking on any field or filling any field invalid message appears
the message should be appear once the user interact or start to fill the fields
[Screencast from 05-21-2023 12:16:33 PM.webm](https://github.com/threefoldtech/playground/assets/110984055/a020ac56-46b6-4753-b543-75b6005dbae5)

**Comment by Mahmoud-Emad** [comment]
@MohamedElmdary 
Please provide API to allow the rest of the input.
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/488#issuecomment-1587103565

**Comment by khaledyoussef24** [comment]
verified now invalid only appears after interacting with it
[Screencast from 06-25-2023 10:48:16 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/71e05684-fb88-4823-9fbf-105e99380902)
