### ISSUE TITLE
Create a type for getting result of VM and gateway object

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2869]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

Create a type object to be used for VM and gateway (and if there is another) like the one used in the script `gridClient.machines.getObj`.

### Describe the solution you'd like

eg.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2d8352dd-5cf2-44a2-831f-89ed47e11196)

**Comment by A-Harby** [comment]
@Mahmoud-Emad, I can't see the type in the PR closed or explained anywhere.

**Comment by Mahmoud-Emad** [comment]
@A-Harby Please check this one https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3014/files#diff-e98a290bab2065d3ac312a240683c4be0cdfd916a95e5549c1c9f2ad6f7fb2ebR48-R91

**Comment by A-Harby** [comment]
Verified Devnet,

A type was added and called `ZmachineData`.
And the test scripts are identifying the values now (if . 
![image](https://github.com/user-attachments/assets/dffff430-ab70-4ace-b00f-590384565198)
