### ISSUE TITLE
Unclear error message after a failed deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#287]
### Description

Full VM deployment failed with the following error message.

```
Error: Failed to deploy on node 17 due to Error: Failed to send request to twinId 25 with command: zos.deployment.deploy, payload: {"version":0,"metadata":"{\"type\":\"network\",\"name\":\"NWWmgVIBRdSd\",\"projectName\":\"fullvm\"}","description":"","twin_id":60,"expiration":0,"workloads":[{"version":0,"name":"NWWmgVIBRdSd","type":"network","data":{"subnet":"10.20.4.0/24","ip_range":"10.20.0.0/16","wireguard_private_key":"8X4hGri7UkLzR7vB7K0Z7gkcEcf62Htc+jq7CjtDQnc=","wireguard_listen_port":3802,"node_id":17,"peers":[{"subnet":"10.20.2.0/24","wireguard_public_key":"JP4lvhkpk/rRyr09lWzD8Sk1Id7UTETduUhnSbNoVnI=","allowed_ips":["10.20.2.0/24","100.64.20.2/32","10.20.3.0/24","100.64.20.3/32"],"endpoint":"185.206.122.32:2110"}]},"metadata":"{\"type\":\"network\",\"name\":\"NWWmgVIBRdSd\",\"projectName\":\"fullvm\"}","description":""}],"signature_requirement":{"requests":[{"twin_id":60,"weight":1,"required":false}],"signatures":[{"twin_id":60,"signature":"2601a2bfd769e6e12ea57a4549b42f4abb8b16e37d121330e6b8e335c35e931baeea2093547f314d86043770aaafe9c3f3d2ca826722be5852d3517715a28487","signature_type":"sr25519"}],"weight_required":1},"contract_id":26826} due to 255 write /var/cache/modules/provisiond/workloads.bolt: disk quota exceeded
```

![image](https://github.com/threefoldtech/playground/assets/101194226/e5de3c28-ed78-4e96-be04-ff2e23e433be)

at the end of the error it appears to be a storage issue `disk quota exceeded`. i'm not sure if it is actually a storage issue or something else but the error message needs to be much shorter and clearer.

**Comment by zaelgohary** [comment]
Should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/195cb558ce28c84bfb9a83441c6cd2f1cb54e9dc/packages/playground/src/weblets/full_vm.vue#L90).

**Comment by khaledyoussef24** [comment]
fixed and verified and deployed different solutions 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9c87d205-6d5f-43fe-b1ab-610babb05fd8)

**Comment by khaledyoussef24** [comment]
deployed and verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4b487324-22c3-44bc-9b6b-72c53203d682)
