### ISSUE TITLE
🐞 [Bug]: sorting contracts is not functional

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2871]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

tried to use sorting in contract lists but it is not functional at all in all fields .(created at and id and node)
even though it should sort all contracts not only contracts in the current loaded page
![Screenshot 2024-06-04 at 3 57 39 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a9c891c5-88f2-4cde-9aa1-5d5cb0ab08fb)
![Screenshot 2024-06-04 at 3 57 56 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/72c5159a-1ae8-4a97-8755-da8bed500c8d)
![Screenshot 2024-06-04 at 3 59 54 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2ca6ad6e-1c37-4e47-a5f5-5e26c2f46087)

### which network/s did you face the problem on?

Dev

### version

d806ab4

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Enhance the contracts list page and support sorting

#### Changes

- The column key was changed from 'farmId' to 'farm_id' to match the field name returned from the grid proxy and to support sorting by it.
- A new event emitter was created to sort the contracts based on the 'key' and the 'order'.
- A new function called 'sortContracts' was created to sort the contracts of type <Type> based on the specified requirements.

#### Screenshots/Video 

[Screencast from 06-11-2024 10:00:17 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/07bfefe4-abd9-4737-97e8-62f019e0cf31)

**Comment by khaledyoussef24** [comment]
sorting is working fine for 5 contracts but it does not sort all of the 40 contracts 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/47f37af3-a527-48db-8e9a-685f9daad811)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/37991c3a-d696-43de-893f-327c00f7a658)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2c1fca88-d57c-4f73-aefb-0c1a8937ed45)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cde65d51-21b9-4e05-8a40-eebf9a7b46e7)

**Comment by Mahmoud-Emad** [comment]
The functionality for sorting should be handled on the server side rather than on the client side.

SortBy/SortOrder fields 
https://gridproxy.dev.grid.tf/swagger/index.html#/GridProxy/get_contracts

**Comment by Mahmoud-Emad** [comment]
## Issue Update 


### Work done

Support sorting from GridProxy on the Contracts List page

#### Changes

- Updated the GridProxy client to include `SortBy` and `SortOrder` fields
- Created a new enum to store the values accepted by the proxy
- Validated the incoming value before sending it to the proxy
- Updated table fields to support only accepted sortable fields.
- Removed outdated sort function and integrated Grid Proxy client for sorting.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac03039
the first click sorting ascending 
<img width="1680" alt="Screenshot 2024-07-30 at 12 20 21 PM" src="https://github.com/user-attachments/assets/a9cd106f-fb6d-4bae-93ea-f0089d9dd127">

the second click sorting descending
<img width="1680" alt="Screenshot 2024-07-30 at 12 20 25 PM" src="https://github.com/user-attachments/assets/9773aec9-4ed1-484a-b7e6-b73c93736604">

the third click returning to the default 
<img width="1680" alt="Screenshot 2024-07-30 at 12 20 30 PM" src="https://github.com/user-attachments/assets/5198db5b-f3c6-47b2-a9ab-872b6621b5ae">
