### ISSUE TITLE
🐞 [Bug]: Contract table should be reloaded after deleting the contracts

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After deleting some contracts from any of the contracts table in your contracts page, the table show that there is no contract available on this account while I still do.

Also the contracts number, page and everything else aren't updated

### Steps To Reproduce

1. Create more than 5 contracts.
2. delete the first 5 contracts in your contract page (there should be more contracts remaining, but you will see that the table isn't showing them instead it will show no contract available and also the number of the contract isn't updated.)

### which network/s did you face the problem on?

Dev

### version

b91fde4

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/abac5a68-ce47-46d9-a9a9-e1959375aceb)

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
Duplicate #2800
