### ISSUE TITLE
🐞 [Bug]: calculator enhancement for "Too expensive? " dialogue 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while using the calculator every time I insert an input the `Too expensive? ` dialogue pops up then disappears which feels annoying can not this behavior be improved? 

### which network/s did you face the problem on?

Dev

### version

89f8a0c

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e66d06a4-1184-48df-884d-3470439da73f

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed:
Fix too expensive box flashing.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : db2daf4
behaviour enhanced and much better than the first one.
while loading the message also changed until the user finishes not the flashing behaviour.

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8e09a310-b707-40b3-bdb7-14b089b981ce)
