### ISSUE TITLE
Remove Public IP switch from the deployment details in case the deployment doesn't have one

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#288]
### Description

The public IP switch should be removed entirely from the deployment details if the deployment doesn't have one.

![image](https://github.com/threefoldtech/playground/assets/101194226/111326c1-8f19-480f-8a6e-17efe414dd68)

The current implementation may give the user a wrong idea that a public ip could be added after the deployment is complete.

If removing the field entirely will not work then it should be replaced with a field that contains `-` or `N/A` or `Option was not selected` but hiding it would be a better option.

**Comment by A-Harby** [comment]
Deployed a VM without any ip and still shown as the issue screen not updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2575ecd8-a832-4f66-9919-48b1d369d6e2)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The toggle button was removed from the deployment details.

- Deployment without a public ip

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/25776dbe-13a9-4523-8e82-d2d2610785e5)

- Deployment with a public ip

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/debd8380-ccc4-4850-8239-de41c3a56f14)
