### ISSUE TITLE
🐞 [Bug]: dashboard error while deploying

### ISSUE THREAD

**Issue by MarioBassem** [threefoldtech/tfgrid-sdk-ts#2887]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

dashboard was slow in finding nodes. same single node was returned each time (node 127), and deployments failed (either deployment did not succeed or succeeded but node health tag said `Error`
ps: staging env https://staging.dashboard.dev.grid.tf was working fine for me

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26723944/959d0493-438e-4087-8244-ae3f7aae633d)
![Screenshot from 2024-06-05 18-15-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26723944/d3fe246c-a5f1-4fa7-9834-a728a848f273)

### which network/s did you face the problem on?

Dev

### version

devnet

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26723944/959d0493-438e-4087-8244-ae3f7aae633d)
![Screenshot from 2024-06-05 18-15-01](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/26723944/d3fe246c-a5f1-4fa7-9834-a728a848f273)

### Relevant log output

```console
WorkloadDeployError
```

**Comment by AhmedHanafy725** [comment]
this error comes for the node, I have opened an issue for it https://github.com/threefoldtech/zos/issues/2355

**Comment by A-Harby** [comment]
Verified, devnet 08a275d.

I deployed VMs on multiple nodes, and it worked fine with no delay.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85cc1b80-ff7f-4498-bd1a-7ba3b7d09ea9)
