### ISSUE TITLE
🐞 [Bug]: InvalidResourcesError while deploying k8s cluster 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while deploying k8s cluster with about 5 workers,
some of workers have the same node for all of them auto selected, then i got this error 
![Screenshot from 2024-06-05 19-51-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/3706504d-84ec-4b76-a34f-5224d054d3ea)

after some investigation, i found that the node resorces is not enough for all of the workers but only one or two of them, here i tried to reproduce the error by selecting the same node on each of them with total memory needed 32 GB , 8 for each and the available on the node was about 10 GB

### Steps To Reproduce

1. go to K8s page 
2. select a node to continue with 
3. make the memory field of each worker and the master fit in the pre selected node 
4. select the preselected node on each of them
 the idea is
 if we have node x that have 10 GB memory available, and have 4 workers with required memory 8 GB for each
 the node will be listed on all of them and you can select it while the total required memor;y is 32GB 
and you will have this error 

![Screenshot from 2024-06-05 19-49-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/3d3ebe45-fa1d-4ade-a16b-4f03683bd4c2)

### which network/s did you face the problem on?

Dev

### version

10b2b62

### Twin ID/s

1525

### Node ID/s

166 for this test

### Relevant screenshots/screen records

[Screencast from 05 يون, 2024 EEST 07:50:57 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7d1ae7bb-e7df-47db-849b-a3c0b05d1104)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0d964e5


![Image](https://github.com/user-attachments/assets/b86e3d71-e629-4afc-9432-70241b12dba4)
![Image](https://github.com/user-attachments/assets/8295bfa8-5216-48de-9bac-e179bee0262d)
![Image](https://github.com/user-attachments/assets/63b416bb-d1d3-40cf-b122-60d011ea96fa)
![Image](https://github.com/user-attachments/assets/d02a954c-8cb5-4263-b3a2-f51a8cbb8704)
![Image](https://github.com/user-attachments/assets/2035477f-b0a1-4f64-aae2-4362078ea6bb)
