### ISSUE TITLE
🐞 [Bug]: Deleting some contracts listed in the current page showing no contracts available while there are many other pages 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

if you are on the first page of contracts table with page size 5
the you select all the 5 contracts and delete them you will  `No node contracts found on your account.`

### Steps To Reproduce

1, create more than 5 node contracts 
2. go to contracts table and make the page size 5 
3. select all of the 5 listed contracts 
4. delete the selected contracts 
5. you will see there is no contracts msg while you have another page 

### which network/s did you face the problem on?

Dev

### version

10b2b62

### Twin ID/s

1525

### Relevant screenshots/screen records

[Screencast from 05 يون, 2024 EEST 08:03:28 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/9b6c757f-999e-45cc-a036-d282013d468a)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done

Enhance the contract list view:
- Replaced the static values with `ref` concept to change the value when needed.
- Cached the nodes to use it when re-request to avoid duplicated requests.
- Enhanced the list time by using the `Promise.all()` and displaying what gets finished.
- Introduced a new hint alert to inform the user that the table will be reloaded in a bit.
- Replaced the `update-options` event with the `update-page` and `update-size` events to avoid requesting each change that happens on the table and only request when changing the `page/size`.
- Created only one function to request to list the contracts based on it's type.
- Returned the `onMounted` life cycle and called the 'loadContracts' inside it.
- Remove the duplicate requests.
- Updated the `getNodeInfo` function to request only the nodes that are not cached.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945
contracts now reloads the page after 8 to 10 seconds 
a message and notifications are now popping up to the user to enhance user experience

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e5219c46-04ae-42d3-97d7-0bc5ec09129e)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6daf9718-248d-480f-871e-3452d4d16506)
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fb9ee784-5a45-480e-8b24-10a2c73333dc
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4294999
