### ISSUE TITLE
Wireguard Config is not returned in the deployment details

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#289]
### Description

Wireguard config is missing from the deployment details after enabling the wireguard access during the deployment.

![image](https://github.com/threefoldtech/playground/assets/101194226/f4a569c4-adc9-4a11-9605-8ecba742e02b)

![image](https://github.com/threefoldtech/playground/assets/101194226/bd8ae5c6-068a-4193-8123-1dd324e6840c)

I tried enabling the option for full vm and micro vm but it didn't appear in both.

**Comment by 0oM4R** [comment]
Status: PR #409 ready for review

**Comment by mohamedamer453** [comment]
Verified on devnet.

Wireguard config was added to the deployment list when the option is selected while configuring the deployment.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fdcc5ebb-25f8-4c50-ab87-8b17d6514996)
