### ISSUE TITLE
Change the ability to select multiple `SSHKeys` to selecting only one key. 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2892]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Change the ability to select multiple `SSHKeys` to selecting only one key till the [issue of the images](https://github.com/threefoldtech/tf-images/issues/231) is finished.

### Describe the solution you'd like

Change the ability to select multiple `SSHKeys` to selecting only one key till the [issue of the images](https://github.com/threefoldtech/tf-images/issues/231) is finished.

**Comment by Mahmoud-Emad** [comment]
## Issue update 
### Work done
The requested changes should be done in the mentioned PR

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ad30945
user now can not use multiple ssh key  only one.
and active column removed from the ssh tab
![Screenshot from 2024-06-09 05-54-51](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/89f906c4-c7c2-41f3-beea-56e56e905ba5)
[Screencast from 06-09-2024 05:54:30 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/20362802-978d-4112-a90e-f4f52aa6bf26)
