### ISSUE TITLE
🐞 [Bug]: UI improvement to the stats page.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The UI isn't the best responsive; it needs some improvement, like the map looking weird; I don't think the dimension is correct and the map isn't centered (lots of whitespace under); and the last card should be taking up all the space, which would be better.

### which network/s did you face the problem on?

Dev

### version

b72ee05

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f9e81d74-0c5e-4d3e-97f1-f346b6812398)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed:
- Center all items vertically
- Remove vertical divider

**Comment by samaradel** [comment]
@A-Harby when I made the last card take the full width it became ugly because it contains little data so I skipped the last part.

**Comment by samaradel** [comment]
### Work Completed:
- Let the last card take the full-width 
- Make all cards height equal on small screens 
- Adjust the statistics page grid

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 0d964e5
 the last card take the full-width
 all cards height equal on small screens



![Image](https://github.com/user-attachments/assets/dae966b3-def5-4b92-b15a-cc732716659f)
