### ISSUE TITLE
🐞 [Bug]: unclear error while deploy with multiple ssh keys

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

wile deploying a vm with multiple ssh keys i face this error.(9 ssh keys )
may be there is an accepted number of ssh keys to make the deployment

### which network/s did you face the problem on?

Dev

### version

b72ee05

### Relevant screenshots/screen records

<img width="1373" alt="Screenshot 2024-06-06 at 3 00 41 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4e9b7aeb-2494-446f-9691-064a039d7cf8">
<img width="1680" alt="Screenshot 2024-06-06 at 3 17 45 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f0d68bc5-e02e-4e9a-b776-241cafd20f72">

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
@khaledyoussef24 which node ?

**Comment by AhmedHanafy725** [comment]
this error comes for the node, I have opened an issue for it https://github.com/threefoldtech/zos/issues/2355

**Comment by A-Harby** [comment]
Verified, 08a275d.

It took a while, but the deployment was successful on node 127.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b63d1704-113a-4552-a688-7b268e529221)
