### ISSUE TITLE
Remove Disk path from Full VM deployment details

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#290]
### Description

In the Full Vm deployment details there's a path next to the added disk, even though the disk is not mounted yet and the user is responsible for mounting it at any desired location.

![image](https://github.com/threefoldtech/playground/assets/101194226/619b33ec-6055-4990-973d-2c0bef935183)

**Comment by zaelgohary** [comment]
@mohamedamer453 What should the text be changed to?

**Comment by mohamedamer453** [comment]
Verified on devnet.

The disk path was removed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/23181664-94df-47a5-8aa0-1d69833ef57b)
