### ISSUE TITLE
🐞 [Bug]: Orchestrators page cards are not responsive

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

k8s and caprover cars are not responsive

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c1d92576-7d06-461e-9d32-62b7eb213047)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/64c33785-7d4d-48ad-9eec-6bc3c72b13b8)

### Relevant log output

```console
.
```

**Comment by atefnazmy** [comment]
Verified, Dev
version: 6f39878



https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/1cd06b67-b4c7-4586-91ae-2502c8f8395b

**Comment by khaledyoussef24** [comment]
verified on devnet
version: db2daf4

orchestros cards are now responsive and the text is displayed fine.
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d56383c7-c170-4f8e-b93c-6b78eacbb5ae)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/35f39aa1-5818-46cb-9565-033047f37449)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ace805a8-181b-4e3b-8194-f41a265a81e9)
