### ISSUE TITLE
🐞 [Bug]:  no title in solution pages

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

can we add a title to the solution pages in case of the collapsing the side bar will be needed

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/69f8ce9a-4bdd-4eff-80c1-cfb6bed5c891)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0128516b-0e28-4239-9531-b9611aba236c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94200f3e-879a-4f84-94eb-e9e51b850b3a)

### Relevant log output

```console
.
```

**Comment by ehab-hassan** [comment]
Work Done

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/0e5d4a05-d910-4cba-bd43-65996ac97cfd)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d65fac49-3ef3-4383-a948-a4e229a681d6)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/60afc19b-b3a7-4244-9a27-e33e0b454631)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4

titles are now visible and clear

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8a70e05e-9b34-429c-896f-9e06e930faeb)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7bb52c15-0afe-4cb5-9893-93fa4bbd5ab7)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/031549f5-1543-4614-a965-50679811f4f8)
