### ISSUE TITLE
🐞 [Bug]: Node pilot deployments does not have Domain name

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

made a node pilot deployment but no domain name was provided 
i could only reach the deployment through public ip and not secured
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b9af81f7-432f-4441-a8f0-491bc55ec135)
[Screencast from 06-09-2024 06:18:33 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/748a94f9-3e0e-4f3e-82fe-c36b908215cc)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4dff2df9-d3dd-4c8f-8cc2-970d74d17f05)

there is no domain name in deployment details like other solutions also
![Screenshot from 2024-06-09 06-20-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/71678206-9619-4c5c-9392-beaa6d642414)
 

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Work completed:

Added domain to node pilot.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : db2daf4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9b0f7740-5a1d-4798-ab10-a179948ac8d5)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/6e6c591e-161e-4fde-bf4b-a9700bae11e6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4a1f0884-5a18-4bb4-911a-ff6c7ede4887)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8aa93216-5396-4340-aea2-ab55fe04bb87)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a1527805-b847-4d70-bd51-4a933ec7299e)

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150351
