### ISSUE TITLE
🐞 [Bug]: Node pilot table fields emhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

node pilot table has planetary ip and mycelium ip columns, while the deployment has no network settings for this only deploying using public ip.
and deployment list need a column for public ip

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0567a67f-6c62-4720-81c0-2c2bc997daed)

### Relevant log output

```console
.
```

**Comment by AhmedHanafy725** [comment]
Add the network tab in the solutions so the user can select the network he needs in each solution. Also, the IPs in the table would be usable.

**Comment by maayarosama** [comment]
Work completed:

Adding the network component to node pilot application

**Comment by khaledyoussef24** [comment]
we shall add ipv6 as well 
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2930

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac03039


![Image](https://github.com/user-attachments/assets/137e7076-af76-4e71-ad43-b3bcb146bf76)
