### ISSUE TITLE
🐞 [Bug]: clicking sorting in contracts page does not trigger requests

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

trying to use sorting in contracts but tables stay the same and no requests are even trigger 
different than  #2871 
sorting was at least making triggers but did not make the required changes

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

[Screencast from 06-09-2024 06:45:08 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cc98265e-7a42-42a8-bd31-23dfe92e1af0)
[Screencast from 06-09-2024 06:48:25 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e69fd1e3-2142-45d9-b4d3-d9d0a8bd00ab)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

Enhance the contracts list page and support sorting

#### Changes

- The column key was changed from 'farmId' to 'farm_id' to match the field name returned from the grid proxy and to support sorting by it.
- A new event emitter was created to sort the contracts based on the 'key' and the 'order'.
- A new function called 'sortContracts' was created to sort the contracts of type <Type> based on the specified requirements.

#### Screenshots/Video 

[Screencast from 06-11-2024 10:00:17 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/07bfefe4-abd9-4737-97e8-62f019e0cf31)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c27924c
- The sorting functionality is working as expected and successfully triggering the requests. 


https://github.com/user-attachments/assets/2bc8681a-b695-439b-ab0e-13bf255c9dcd


#### Related Link
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4156493
