### ISSUE TITLE
🐞 [Bug]: node finder is not responsive

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

zoomed out at node finder page to see more nodes but it is not filling up the whole page
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/db85c7a3-9690-46c4-98ab-ac01da97bf16)
should it fill the whole page as i zoom out ?

### Steps To Reproduce

1. go to the node finder
2. zoom out to see more than 3 nodes (it should be 20 per page
3. it wont fill the whole page

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![Screenshot from 2024-06-09 07-02-50](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/deba0711-3866-439b-9d5d-9927cce18886)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/709ef09c-be43-48a1-9b54-f267b5f87e22)

### Relevant log output

```console
.
```

**Comment by MohamedElmdary** [comment]
@khaledyoussef24 it should look fine even in very big screens but zooming out won't be that great

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 2.6
I think this may be enough as long as it is working fine on normal screens
