### ISSUE TITLE
🐞 [Bug]: error behavior enhancement while adding an in correct ip

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

tried to add an ip to public ip table in myfarms

- got unclear error 
- the fields were cleared instead of telling me that a field need to be validated

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![Screenshot from 2024-06-09 10-23-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5e08de9b-94fb-40aa-b661-02c22f9969cd)
![Screenshot from 2024-06-09 10-22-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/762574da-3fb5-4c65-9bb4-9dc2c26b44a8)
![Screenshot from 2024-06-09 10-21-24](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8c916115-243c-4c27-b44f-82d79e89ec6b)

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
could not reproduce, @khaledyoussef24  can you?

**Comment by khaledyoussef24** [comment]
could not reproduce the issue,will open again if i could.
