### ISSUE TITLE
Update Algorand node resources

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2915]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Resouces is not updated.

### Describe the solution you'd like

Algorand required resources need to be updated as per the [docs](https://developer.algorand.org/docs/run-a-node/setup/install/#hardware-requirements)

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

- Increased minimum memory size to 16GB to meet the system requirements.
- Updated CPU requirements to a minimum of 8 cores as per the latest specifications.
- Added a hint message for users selecting the 'custom' option, advising them to review hardware requirements before deploying a new Algorand instance.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : db2daf4


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/54a64bb6-060c-4592-9098-8777c459ace6)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0b5b13bc-e6c9-47ee-890d-9cbfd2b0e67a)



![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ed3f756a-b106-4053-871d-998ee8621be0)
