### ISSUE TITLE
🐞 [Bug]: Node finder should sync with the profile manager

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I rented a node 205 with twin 143 then I pressed the unreserve button connected to another wallet and pressed the reverse button and guess what? I was able to reserve it with the old wallet, not the newly connected wallet

### Steps To Reproduce

1. Open the [staging dashboard](https://staging.dashboard.dev.grid.tf/)
2. Go to the [Node Finder Page](https://staging.dashboard.dev.grid.tf/#/deploy/node-finder/)
3. Reserve a node
4. Un-reserve it
5. Connect another wallet without refreshing the page
6. Reserve the node again
7. After the transaction is a success and before re-loading the table try to go to your contracts page
8. Return back to the node finder page and search about the node and see if it reversed to you, you'll not see the un-reverse button
9. Connect the old wallet search about the same node and try to un-reverse the node, you'll face an error.

### which network/s did you face the problem on?

Dev

### version

c94d09d

### Twin ID/s

143 and 39

### Node ID/s

205

### Farm ID/s

1

### Relevant screenshots/screen records

[Screencast from 06-09-2024 11_23_49 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/024c3e64-d98e-49f8-981e-aefdb1256cb8)

### Relevant log output

```console
TypeError: Cannot read properties of null (reading 'clientOptions')
    at updateGrid (index-e86b182e.js:285:12304)
    at ve (index-e86b182e.js:378:26118)
    at index-e86b182e.js:6:103167
    at callWithErrorHandling (index-e86b182e.js:6:44051)
    at callWithAsyncErrorHandling (index-e86b182e.js:6:44173)
    at callWithAsyncErrorHandling (index-e86b182e.js:6:44310)
    at HTMLButtonElement.d (index-e86b182e.js:6:102862)
```

**Comment by A-Harby** [comment]
Verified, Devnet 9d671ca.

The resync is working fine, and I was able to reserve and unreserve with different accounts without needing to refresh.

[screen-capture (12).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d4269015-a046-453a-89a9-23affcad3df7)

[TC2715 - Reserve same node with 2 different account after each other](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4295009)
