### ISSUE TITLE
Complete project docs

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#292]
### Description

Project documentation needs to be added and the readme needs to be updated.

### Readme

- Remove unnecessary stuff added by the template.
- Add introduction about the playground.
- Add installation Steps.
- Getting Started Guide.
- Running tests commands.

### Docs

- Same docs that are available in the [weblets](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/weblets/docs) should be modified and added here (if it still needed).
- These docs include:
   - build.
   - config.
   - contributing.
   - getting started.
   - testing.

**Comment by zaelgohary** [comment]
All done except for tests.

**Comment by mohamedamer453** [comment]
Verified.

- [`Readme.md`](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/playground#readme) was updated.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4b8946a2-a9b7-4caa-b49d-a24b5a8ad6b2)

- [docs](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/playground/docs) directory was added with all of the mentioned files.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0874cc60-6a75-4826-b1dc-47a28bac17a3)

- As for testing docs, it should be included when selenium/cypress or any other test framework is used.
