### ISSUE TITLE
🐞 [Bug]: Deployments number are not correct

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The node 29 on Qanet shows that no workload or deployment is Zero, while the graphql shows the 2 contracts are deployed there!

### which network/s did you face the problem on?

QA

### version

2.4.3

### Node ID/s

29

### Farm ID/s

180

### Contract ID/s

29280, 29282

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ee02c267-7d68-420b-955d-67e7fc1c343c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5e3edf83-8a18-4500-b4ca-7fe7c75ef88c)

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
@A-Harby I tried running the same query on graphql but couldn't find any active deployments on the node.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/adcf14f8-599b-4a0d-a1a1-d69f16d7295d)

Can you verify if the issue still exists?

**Comment by A-Harby** [comment]
It doesn't show the contract anymore for some reason; it will close and reopen if it reoccur.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/de62d27e-8fd2-406c-80dc-9ee2a4660b26)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8171bf16-7e3c-41fa-961d-45d76a54557a)
