### ISSUE TITLE
Error Message improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#293]
### Description

Error Messages for min and max length could be improved.

`Name minLength is 2 chars.` -> `Name Must be at least 2 characters.`

`Name maxLength is 15 chars.` -> `Name can't exceed 15 characters.`

these are a couple of suggestion but any other format/wording would be better than `minLength` & `maxLength`

this issue applies for all `Name` `Username`, `password` fields.

**Comment by A-Harby** [comment]
Name was fixed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/857cc720-d6b9-4541-a7d4-a345a8b694eb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bc756c1a-1e2c-4e5c-a316-a274b1dea618)

But password isn't fixed yet.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4a4220c8-5a10-48cf-ac12-b7d0fddf9e99)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d92806d6-c013-4f17-94e2-5c7dc031e78f)

**Comment by A-Harby** [comment]
Password input in STMP server in Discourse, But it happens in all password inputs in any stmp or mail server tabs.

**Comment by A-Harby** [comment]
Verified 537d01e.
Password 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e3d03f41-0f93-4355-94d6-70be3a1ed33a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f8799563-35c9-4729-aa8e-4dcb1f779a2f)
In STMP server.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fbec6701-9bfc-4444-974e-319aa7379017)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/76bc8d2c-1308-4056-86a5-020c191d59a6)
in mail server
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/041b394f-826d-4937-b86f-1b832b2b3f3c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/55123df5-9c9c-48bb-beaf-4bf56bc53a25)
