### ISSUE TITLE
🐞 [Bug]: IPV6 isn't showing as a network option in the applications

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

IPV6 isn't showing as a network option in all of the applications, missing the consistency between them.
And I think as long as the IPV4 is an option, so should the IPV6.

### which network/s did you face the problem on?

Dev

### version

44f15ae

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fa563797-e64d-47cd-8214-1ab6a4b79b99)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : d863879
IPV6 is now added to all applications 
can we add a column as well to it in all deployment lists ?

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: ac03039
- The IPV6 Network option and Its column are added to all deployments.

**Comment by khaledyoussef24** [comment]
verifiedn on devnet 
version : ac03039


![Image](https://github.com/user-attachments/assets/26ce760f-b9b3-4502-be6d-1ab99e3c7fb5)
![Image](https://github.com/user-attachments/assets/264b2931-acc9-41f7-8079-93803bc7f6d3)
![Image](https://github.com/user-attachments/assets/5ef9ce7b-0d3c-419f-a868-79a4e41d1354)
![Image](https://github.com/user-attachments/assets/d8b5d6a0-7de8-4324-a10e-39727bc4731a)
