### ISSUE TITLE
🐞 [Bug]: The Reserve/Unreserve does not work as expected

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I visited the dashboard and was trying to reserve a node. I searched for a node to rent and clicked the "Reserve" button. After the loading finished and all the necessary actions were completed, I noticed that the button text still displayed "Reserve" and the color did not change.

### Steps To Reproduce

1. Go to the dashboard
2. Go to node finder
3. Rent a node
4. watch the button

### which network/s did you face the problem on?

Dev

### version

localhost

### Twin ID/s

143

### Node ID/s

205

### Relevant screenshots/screen records

NA

### Relevant log output

```console
NA
```

**Comment by A-Harby** [comment]
[screen-capture (12).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/15078591-ed9f-4ca8-adf8-18d38550f5b2)

**Comment by maayarosama** [comment]
## Issue Update

### Investigation and Solution:

on unreserve the nodes doesn't update after the unreserving method is done, so it sees the node as still rented

**Comment by maayarosama** [comment]
## Issue Update

### Investigation and Solution:

I used ```props.node``` directly to reflect any changes that happens to the node, instead of saving a snapshot of the node to a ref value which doesn't reflect the changes in the node

**Comment by A-Harby** [comment]
Verified, Devnet c14b41f.

The button now change back between reserve and unreserve.

[screen-capture (19).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b77622fe-d782-46f6-939e-c70882c57043)
