### ISSUE TITLE
🐞 [Bug]: Enhance the addition fee error message

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#2937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The current error message in the addition fee is just `failed to add addition fee` for all of the error kinds.

### which network/s did you face the problem on?

Dev

### version

17d861b

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2490

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2490#issuecomment-2156657464

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Work completed:

Edit err msg if node has active contract.

**Comment by A-Harby** [comment]
Staging, d52b72f.

Still only showing the default error message for online nodes 155 and 156. 

![image](https://github.com/user-attachments/assets/9d248f43-eae6-4f5f-80bc-ce5352c29ece)

**Comment by zaelgohary** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3304

**Comment by A-Harby** [comment]
Verified, Devnet 815d729.

The addition of the fee is working fine.
![image](https://github.com/user-attachments/assets/d3b18eec-a680-441d-ad9c-1dfb109969bc)
and the error message is clear and states the reason.
![image](https://github.com/user-attachments/assets/d31fc657-ff00-41c5-895c-175ba6013217)

[TC2443 - Set Fee](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4164651)
