### ISSUE TITLE
Update the `Delete IPs`, `Manage Ssh Keys` dialogs with `Chip-Group` component

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2939]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Vuetify offers a component called "chip-group," which is useful for including multiple chips in the same card and managing padding/margin. Please refer to the screenshot below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b4adee94-5c33-49a4-b2d3-9a17f18ab392)

### Describe the solution you'd like

https://vuetifyjs.com/en/components/chip-groups/#usage

Also, we can remove the logic of selecting keys and use the vuetify one

[Screencast from 06-10-2024 09:20:25 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/38b964ee-7e09-4426-8e79-635a63b3e6c7)

**Comment by zaelgohary** [comment]
Work completed:

Use chip group in delete public IP. Not usable in SSH page as multiple SSH keys feature is not active as of now.

Note: chip group doesn't pick up the chip color and this seems to be a problem from Vuetify which has been reported https://github.com/vuetifyjs/vuetify/issues/19678

**Comment by zaelgohary** [comment]
Used chip group in Manage SSH key section in solutions. I also used a margin for the chips in the delete dialogue.

**Comment by khaledyoussef24** [comment]
verified now the selecting of the ssh changed and the behaviour is better now when changing a ssh the other is automatically de activated

https://github.com/user-attachments/assets/f228b865-1b90-4e11-98b6-53bf1f0b61a7
![Image](https://github.com/user-attachments/assets/41aee829-89b5-4138-a18a-930ea81cfd17)

but the deleting ips still have the same behaviour


![Image](https://github.com/user-attachments/assets/61248e82-f450-4c4d-ad6e-b3a0e835a892)
but i think this is acceptable, shall i verify like this or there is more enhancements ?
@zaelgohary @Mahmoud-Emad

**Comment by zaelgohary** [comment]
> verified now the selecting of the ssh changed and the behaviour is better now when changing a ssh the other is automatically de activated
> 
> https://github.com/user-attachments/assets/f228b865-1b90-4e11-98b6-53bf1f0b61a7
> ![Image](https://github.com/user-attachments/assets/41aee829-89b5-4138-a18a-930ea81cfd17)
> 
> but the deleting ips still have the same behaviour
> 
> 
> ![Image](https://github.com/user-attachments/assets/61248e82-f450-4c4d-ad6e-b3a0e835a892)
> but i think this is acceptable, shall i verify like this or there is more enhancements ?
> @zaelgohary @Mahmoud-Emad 

For the IP chips, it was fixed by adding a margin. Please, verify as it is.

**Comment by Mahmoud-Emad** [comment]
@khaledyoussef24
Also, you can open an issue to change the style of the delete ips dialog the same of the ssh keys dialog to be consistent

**Comment by khaledyoussef24** [comment]
will close this for now another issue is opened for the delete ips
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3221
and already closed to continue with the current  flow.
