### ISSUE TITLE
🐞 [Bug]: Deploying and Listing gateways for multiple vms deployment

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#2940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When deploying multiple vms in a single deployment we show them as a single vm deployment in listing table which leading to unexpected behaviour while deploying/listing gateways(aka. manage domains)

while listing gateways(domains) we check projectname as path and retrieve back all gateways there which will lead to loading all gateways no matter which vm is it

### which network/s did you face the problem on?

Dev, QA, Test, Main

### version

latest

### Relevant screenshots/screen records

None

### Relevant log output

```console
None
```

**Comment by A-Harby** [comment]
Verified, Devnet 408184e.

The gateway is now separated from each VM, and I can deploy on each successfully.

[screen-capture (20).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b47253db-8c7e-4670-983f-aacea8956338)
