### ISSUE TITLE
(QA verification) 🐞 [Bug]: Rentable filter is not working fine

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Used rentable filter to rent a node on quanet with dediacted filter 
got this
<img width="1448" alt="Screenshot 2024-06-11 at 4 38 54 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/03327cbb-00cf-4f92-ad67-155fd6a86915">

used dedicated node only got these
<img width="1446" alt="Screenshot 2024-06-11 at 4 36 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/91394ebf-d520-47db-8516-44b34b9f6bdf">
used dedicated node and status up got these
<img width="1452" alt="Screenshot 2024-06-11 at 4 39 09 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4c70a8e0-ef72-4b53-9367-f1406ec39445">

i think rentable filter supposed to show any node ready for rent status up or standby

### which network/s did you face the problem on?

QA

### version

2.5

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Investigation and Solution

I think there are no issues, when 
**Requests**
1. [Dedicated filter](https://gridproxy.qa.grid.tf/nodes?page=1&size=20&ret_count=true&status=up&dedicated=true&sort_by=status&sort_order=asc)

2. [Rentable filter](https://gridproxy.qa.grid.tf/nodes?page=1&size=20&ret_count=true&status=up&sort_by=status&sort_order=asc&rentable=true&available_for=33)

3. [Dedicated && Rentable](https://gridproxy.qa.grid.tf/nodes?page=1&size=20&ret_count=true&status=up&dedicated=true&sort_by=status&sort_order=asc&rentable=true&available_for=33)


Based on @Omarabdul3ziz 

> two nodes in the second url are on freefarm2 which is a dedicated farm.
means that only its nodes can be rented to be available for use. query looks fine it is dedicated=true and also rentable=true
 
the first URL has the extra query available_for which excludes the freefarm2 nodes cause they are neither rented by this twin id NOR not in un dedicated farm.

**Comment by Mahmoud-Emad** [comment]
@A-Harby 

You are right that the "available for" shouldn't be there in that case.
Additionally, for the second point, it's not a problem at all, since users can choose their filters. We have a drop-down that contains all the types of statuses, so if you want to see the online nodes only, you can select "up" from the drop-down, and so on. I also want to let you know that even if the user forgets to select the "up" status, we order the nodes based on their status, which means the "up" nodes come first, and then any other status.

**Comment by A-Harby** [comment]
Verified, QA 2.5.0-rc3.

Now the dedicated node flag show all the dedicated now (rented and free).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7dc11eea-4eb4-45ea-84f7-3af82829f3d5)
But the rentable only shows the free ones.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/431d3ec1-ddcb-4153-962c-1331f50c01ce)
