### ISSUE TITLE
🐞 [Bug]: Minting reports page enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

While i was verifying what a user without wallet do the minting reports page opened and did not ask me to connect my wallet.
<img width="1680" alt="Screenshot 2024-06-11 at 5 28 45 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8fd50ff1-3487-48dd-b746-4b829063c2d4">
and the input field needs to be enhanced
<img width="305" alt="Screenshot 2024-06-11 at 5 34 42 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d3fb1d4d-eaae-4f6e-87d5-18fa00f42461">
<img width="253" alt="Screenshot 2024-06-11 at 5 34 48 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fcc2f4f6-11f5-4949-b80d-ab1e8d418c7d">

### which network/s did you face the problem on?

QA

### version

2.5

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by zaelgohary** [comment]
Issue was already fixed and verified [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2842#issuecomment-2149770976). Dev & QA doesn't have the correct version. Should be done once the version is updated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/4cec6f86-b5e3-44a0-8f24-c8380d533e2a)

**Comment by A-Harby** [comment]
Verified, Qanet 2.5.0-rc2.

The version is correct and the 


 is back to
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ccc4852-beab-43c4-b6a8-8087879ec651)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f42d11bf-d505-4653-bb84-183713088a9c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e3f352ac-aad5-41dc-9681-2d0c7bd6485e)
