### ISSUE TITLE
🐞 [Bug]: Add no data available to IP table

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#2966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

```No available data``` isn't shown.

### Steps To Reproduce

1. Go to https://staging.dashboard.dev.grid.tf/
2. login and navigate to your farms
3. choose a farm with no IPs added
4. check IP table

### which network/s did you face the problem on?

Dev

### version

408184e

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b4b05496-78bc-4a88-910a-e3dc811ab7c4)

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
Work completed:

Added no data msg in public IP table.

**Comment by A-Harby** [comment]
Verified, Devnet 0d964e5.

`No IPs added on this farm.` added the farms with no IPs in them.
![image](https://github.com/user-attachments/assets/28eae4c6-f352-4894-a158-d7339cee2371)
