### ISSUE TITLE
🐞 [Bug]: User Experience Enhancement : Logging out from the wallet closes the dialogue of the wallet

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#2981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

every time I log out from a user to log in to another user the dialogue of the wallet. 

### which network/s did you face the problem on?

Dev, QA

### version

2.5

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9fa47650-3237-4822-a7fd-0c533421b870

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
Removed the event emitter from closing the dialog after logout.

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : d863879


https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/feaae8bc-5791-4f9f-9291-07bcabf08433
