### ISSUE TITLE
🐞 [Bug]: Enhance the load domains behavior

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#2982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

While testing the dashboard, I noticed that 2 requests are invoked when the reload icon is pressed. Both of them have the same response/result. Are they both needed?

 the `ret_count` query is set to one of them, it can be done by removing the first one and send only one request with the `ret_count` if needed

### Steps To Reproduce

1. Go to the [dashboard](https://staging.dashboard.dev.grid.tf/)
2. Connect your wallet
3. Deploy a micro VM
4. Go to attach a domain to it
5. Inspect the page and Go to the network tab
6. Press on the reload button beside the domains select
7. Watch the network tab and you'll see that two requests are sent to the server and only the difference is that the `ret_count` query is set to one of them 

### which network/s did you face the problem on?

Dev

### version

b4861f5

### Twin ID/s

143

### Relevant screenshots/screen records

[Screencast from 06-13-2024 08:46:01 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/fae17381-9c84-46f3-b185-87078710879a)

### Relevant log output

```console
N/A
```

**Comment by MohamedElmdary** [comment]
This is not possible for our implementation as we don't lose 1st page as request so we need to get count then load a random page so we might load 3rd page before 1st one

**Comment by khaledyoussef24** [comment]
there are now 2 requests also


![Image](https://github.com/user-attachments/assets/6e7ab515-26d5-4770-8661-caea1f1c7e3d)


https://gridproxy.dev.grid.tf/nodes?ipv4=true&ipv6=true&available_for=201&status=up&page=1&size=0&ret_count=true&sort_by=free_cru&sort_order=desc&domain=true

https://gridproxy.dev.grid.tf/nodes?ipv4=true&ipv6=true&available_for=201&status=up&page=1&size=20&sort_by=free_cru&sort_order=desc&domain=true

**Comment by 0oM4R** [comment]
its impossible to make it only one request. We enhanced the load domains by reducing the size of the request and set it to zero 
you can validate it by checking the size flag here 
https://gridproxy.dev.grid.tf/nodes?ipv4=true&ipv6=true&available_for=201&status=up&page=1&size=0&ret_count=true&sort_by=free_cru&sort_order=desc&domain=true

**Comment by khaledyoussef24** [comment]
verified on devnet
version : a542a73


![Image](https://github.com/user-attachments/assets/5999e4e9-9973-4833-87a8-c7255b6c47b5)
![Image](https://github.com/user-attachments/assets/e22ea78f-9861-4f92-85e8-f97bdcfd9076)

the request size is 0 now
