### ISSUE TITLE
🐞 [Bug]: Unlock Dialog buttons appears on right 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#2985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the buttons should be on the left side of the dialog but it appear on the right side 

### which network/s did you face the problem on?

Dev

### version

b4861f5

### Relevant screenshots/screen records

![Screenshot from 2024-06-13 12-13-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/8fab8c01-8e82-4827-8720-cd73d8a278fa)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
Verified, 08a275d.

The close and unlock buttons are moved to the left side.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b4cb0a38-bd44-439b-b6ca-6d53a724b5b2)
