### ISSUE TITLE
🐞 [Bug]: The (Yes) Button has no label to vote on proposals

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#2996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- when trying to vote on proposals I observed that the (Yes) button has no label.

![Screenshot from 2024-06-20 09-13-33](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/487834c2-5e21-4993-8da3-f6cec04a3ae3)

### Steps To Reproduce

- Navigate to https://dashboard.test.grid.tf/
- Connect your wallet.
- From the sidebar, select TFChain then click on TF DAO.

### which network/s did you face the problem on?

Test

### version

2.5.0-rc2

### Relevant screenshots/screen records

- 

### Relevant log output

```console
-
```

**Comment by A-Harby** [comment]
Verified, Devnet 08a275d.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/549346bb-eac0-410b-8683-09dce2b53a95)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4dc22e0c-7261-4235-82fc-ab3967a0d3b4)
