### ISSUE TITLE
🐞 [Bug]: Cannot Deploy Kubernetes workers

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- After Deploying Kubernetes and trying to deploy workers through the manage workers button, the Deploy button was still inactive, although all configurations for this worker were done.

### Steps To Reproduce

- After successfully deploying a K8s cluster.
- Navigate to the deployment list and click on Manage Workers
- Fill the info for the new worker and click on Deploy

### which network/s did you face the problem on?

Test

### version

2.5.0-rc2

### Relevant screenshots/screen records

![worker](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/44ee5478-abaf-43d6-846b-fb46cbbc7648)

### Relevant log output

```console
-
```

**Comment by khaledyoussef24** [comment]
same for caprover
<img width="1680" alt="Screenshot 2024-06-23 at 12 36 26 PM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/abc49c10-f2f4-4ca7-8fd0-0aa66a47ebc8">

**Comment by khaledyoussef24** [comment]
verifed on devnet
version : 08a275d

k8s
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94f583bd-995a-4e68-b1df-c9fe859ddef6)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f7da42f5-3420-4b8b-9b1f-1065808164a7)

caprover


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ab50ce66-c936-47bb-a0d8-3cfb081f1982)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d19edbf1-02bb-4e7b-86cc-fc3b1e1c136d)
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a171dc3b-f0e5-48c1-92eb-7c1f8361d53b)




https://app.testlodge.com/a/26076/projects/40893/runs/746337?tab=2#executed_case_32672081
https://app.testlodge.com/a/26076/projects/40893/runs/746337?tab=2#executed_case_32672089
