### ISSUE TITLE
🐞 [Bug]: A lot of errors in the dashboard console 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3007]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The dashboard is showing a lot of errors when entered for no reason.

### which network/s did you face the problem on?

Test

### version

2.5.0-rc2

### Relevant screenshots/screen records

[screen-capture (35).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d6a0234e-e200-4f5f-ad32-e85d05cc8923)

[dashboard (8).log](https://github.com/user-attachments/files/15944256/dashboard.8.log)

### Relevant log output

```console
6/23/2024, 1:54:56 PM
 | 
[Uncaught Error]
- Message: Cannot read properties of undefined (reading 'value')
- Stack: TypeError: Cannot read properties of undefined (reading 'value')
   at https://dashboard.test.grid.tf/assets/index-e68c104c.js:10:36223
   at Proxy.find (<anonymous>)
   at https://dashboard.test.grid.tf/assets/index-e68c104c.js:10:36199
   at Array.forEach (<anonymous>)
   at getIds (https://dashboard.test.grid.tf/assets/index-e68c104c.js:10:36177)
   at https://dashboard.test.grid.tf/assets/index-e68c104c.js:10:34434
   at ReactiveEffect.get [as fn] (https://dashboard.test.grid.tf/assets/index-e68c104c.js:7:8689)
   at ReactiveEffect.run (https://dashboard.test.grid.tf/assets/index-e68c104c.js:6:31974)
   at get value (https://dashboard.test.grid.tf/assets/index-e68c104c.js:6:43789)
   at Object.isSelected (https://dashboard.test.grid.tf/assets/index-e68c104c.js:10:35899)
- Constructor: TypeError
```

**Comment by zaelgohary** [comment]
I tried multiple times but couldn't reproduce the issue.

[profile_logs.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/2bdd199a-ac90-429a-8769-fe55d9493094)


@A-Harby Can you verify if the issue is still happening?

**Comment by khaledyoussef24** [comment]
still facing the same issue is it normal ?

![Image](https://github.com/user-attachments/assets/c67c90aa-3b3b-4de9-808a-77a24196186c)

**Comment by zaelgohary** [comment]
> still facing the same issue is it normal ?

Definitely not normal but I just tried again on staging and the console didn't have any errors. Can you tell me how to reproduce the issue?

![image](https://github.com/user-attachments/assets/be3c42b8-ed0b-4a27-9e1c-013a2acc6e25)

**Comment by khaledyoussef24** [comment]
Verified the issue is no longer reproduicable.
verified on multiple accounts
network devnet
version : 33bf0c8



![Image](https://github.com/user-attachments/assets/069a5523-da6b-434f-916b-e36995809153)
![Image](https://github.com/user-attachments/assets/7ab0f8fe-f156-44e5-8b68-0be185f218e1)



will open another issue for duplication of errors if an contract has a problem in reading it


![Image](https://github.com/user-attachments/assets/56d860a5-e5ec-4d50-bc93-a1faab8af8c6)
![Image](https://github.com/user-attachments/assets/d3c1d5ee-2325-4af3-858d-9762e88d5fc1)
