### ISSUE TITLE
Comprehensive type checking in GridClient Models/Methods

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3013]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

it's a feature request

### Describe the solution you'd like

Enhance the Grid Client by ensuring all models and methods have complete type definitions.

**Comment by Mahmoud-Emad** [comment]
I have made the necessary updates to the `getObj` as requested in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2869.

However, some of the models and functions need to infer their types as well.

**Comment by Mahmoud-Emad** [comment]
Whoever is going to work on this, please make sure to update the types in the GridClient scripts.

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3014#discussion_r1652120131

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work in progress:

- [Documented the machines module.](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3024/commits/fc3fb2e7323755dcbd319e606d3856f3610fb5fd)
- [Documented the client loader:](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3024/commits/534ff31dbc1d00950de376fe41ead97b92a73c58)
- [Documented the GridClient module.](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3024/commits/d4d1f4d14a6ea54ea4ecec2a4ccfb731f836a784)
- [Documented the networks module.](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3024/commits/3e98ca0540557097d51cdebf73b0943d76ef9fe3)

**Comment by khaledyoussef24** [comment]
verified some of the docs 
clarifying data types used and some docstring improvement to make the codes more clear and usable as the codes are open source and some comments for the code
machine class : 


![Image](https://github.com/user-attachments/assets/103e86ad-7ce5-491f-8a6c-ef345b84f354)

retrieving data by the machine name

![Image](https://github.com/user-attachments/assets/1bb86ace-c860-40c6-86dd-d9380f742520)

conf loading : 


![Image](https://github.com/user-attachments/assets/b3804176-5677-49ec-82d9-a95b323dd2f4)

client connection : 


![Image](https://github.com/user-attachments/assets/050e0786-5f9a-4d47-a9db-339becd8e1d4)


network module: 
![Image](https://github.com/user-attachments/assets/eace828a-8386-4d99-8225-370c7fc3288b)

algorand module :
  

![Image](https://github.com/user-attachments/assets/6f48fa88-f8fe-4f55-874a-cbaaf09a364b)

block chain module

![Image](https://github.com/user-attachments/assets/20b479b8-df10-46ee-88ee-d117fdd4c1d3)

calc module : 


![Image](https://github.com/user-attachments/assets/42cb59eb-2de7-4ebe-aad8-11ac6c3793bc)

zos module : 


![Image](https://github.com/user-attachments/assets/d76e25a2-58d8-4621-8e23-af6e2c527082)

tfchain module : 


![Image](https://github.com/user-attachments/assets/98e50ea9-7dce-4a31-ba06-a989fc4c7c3a)


contracts module : 


![Image](https://github.com/user-attachments/assets/b54a80cc-16aa-4885-96bd-cc69d2eda883)

**Comment by khaledyoussef24** [comment]
base modules : 

![Image](https://github.com/user-attachments/assets/dd5af63b-f0a4-4d2b-853f-65e515532508)

balance modules : 



![Image](https://github.com/user-attachments/assets/cf5fd719-ea84-43af-8852-cb939f175f74)

capacity module : 


![Image](https://github.com/user-attachments/assets/debcac67-5355-4164-bdef-858a96d70203)

currency class : 


![Image](https://github.com/user-attachments/assets/841f93e9-220f-4d2d-9610-c5d53f7886a3)

farmer bot class : 


![Image](https://github.com/user-attachments/assets/31eabaf3-f4cf-4845-b42e-6bb9f4934435)


DAO class : 


![Image](https://github.com/user-attachments/assets/f6acd18c-8b4f-4e18-91f3-ffa34707c095)

gateway class : 


![Image](https://github.com/user-attachments/assets/b814a9dc-2658-405e-9db2-0487a2da8c06)

k8s class : 


![Image](https://github.com/user-attachments/assets/d33d5c7b-9aff-44a8-a4d2-9616ac2fec8b)

nodes class : 


![Image](https://github.com/user-attachments/assets/a1896e24-a3f3-4e51-bc0d-560508efc80a)
