### ISSUE TITLE
🐞 [Bug]:  Show/Hide icon in password field shouldn't be selectable

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#3016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Click `tab` while focusing on any password input will select the hide/show icon which badly impact UX because as a user I would expect to focus next input to continue entering data

Solution:
We need to remove icon from tab index by setting `tabindex="-1"`

### which network/s did you face the problem on?

Dev

### version

latest

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/3dbab8e9-9606-495b-a6ac-19e0e544c13c)

### Relevant log output

```console
None
```

**Comment by samaradel** [comment]
### Work in progress:
investigating..

**Comment by samaradel** [comment]
### Work Completed:
- Remove password input wrapper
- Create a prepend inner icon for inputs with type password
- Fix show/hide icon selection when pressing tab
- Fix the order of dialog actions tabindex

**Comment by samaradel** [comment]
### Work in Progress (WIP):
trying another solution without deleting password-wrapper component

**Comment by samaradel** [comment]
### Work Completed:
- Fix show/hide icon selection when pressing tab
- Fix the order of dialog actions ```tabindex```

**Comment by khaledyoussef24** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d7ee288c-1345-4470-86b4-497f2d1817d7

verified on devnet version : d863879
