### ISSUE TITLE
[Bug 🐞]:  Bandwidth Cost

### ISSUE THREAD

**Issue by luthic** [threefoldtech/tfgrid-sdk-ts#3018]
### What happened?

Before I deploy a node, there is a preview of the costs. This is completely omitting the fact that additional costs for bandwidth will appear and automatically deducted from my wallet.

### What did you expect?

Costs that are displayed should be correct. Costs for bandwidth should be presented in an understandable way that allows to control and foresee costs.

### What browsers are you seeing the problem on?

Chrome

**Comment by maayarosama** [comment]
### Work Completed:
Checking if ipv4 is true to display the bandwidth note and adding the cost of bandwidth per hour

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 0d964e5

 the bandwidth note is added and the cost of bandwidth per hour

![Image](https://github.com/user-attachments/assets/4ff1c41f-a689-4487-805c-b7139b3e42bc)
