### ISSUE TITLE
🐞 [Bug]: When the account doesn't have ssh in the metadata key, it crashes while loading the micro vm component (Maximum call stack size exceeded)

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When the account doesn't have ssh in the metadata key or (doesn't have the metadata key at all), it crashes while loading the micro vm component (Maximum call stack size exceeded)

### Steps To Reproduce

- Remove the metadata key using client or polkadot 
- Login into the dashboard
- Go to micro VM page 

### which network/s did you face the problem on?

Dev

### version

76de2278f0c335891d5a08626f4b5427270665a2

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/354a6c17-0d59-4dd5-85f0-528d0b12397a)

[dashboard.log](https://github.com/user-attachments/files/15968755/dashboard.2.log)

### Relevant log output

```console
-
```

**Comment by Mahmoud-Emad** [comment]
That issue might be related to the reading of the SSH keys, but I believe it can be resolved at https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2666.
