### ISSUE TITLE
🐞 [Bug]: GridClient: `NetworkModule.list()` doesn't work as expected

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3032]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

When call the `NetworkModule.list()` I expect to see all of my networks, but what happened is that I received an empty array instead while I have a networks contract in my account.

### which network/s did you face the problem on?

Dev

### version

 f0ac1e1

### Twin ID/s

143

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/55b17c20-06ec-4255-b395-3ce09e5859ed)

### Relevant log output

```console
NA
```

**Comment by A-Harby** [comment]
If I get this correct, the function should print all the network contracts available on the account.

And my account has 27 network contracts.
![image](https://github.com/user-attachments/assets/0783bb1a-7e64-4593-b6bd-49bcd3cc3e34)

But it's only showing 14 out of them.
![image](https://github.com/user-attachments/assets/d7ef7b13-eaf8-49cf-9142-1eaabfae3dae)

**Comment by zaelgohary** [comment]
@A-Harby, I noticed that the networks are being repeated. The same network could be used on different nodes (1 node per contract). However, the list works normally as it lists unique network contracts. 

I created a PR to refactor the previous fix, but the current listing should work just fine.

**Comment by A-Harby** [comment]
Verified, Devnet 4829e02.

The contracts were actually repeating, and the script showed the correct networks.

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3032#issuecomment-2324688859
