### ISSUE TITLE
🐞 [Bug]: Review node pilot network options

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Node pilot has a newly added network component, but the filters are not updated with those changes.
Currently, node pilot filters have ipv4 =true but the deployed instance doesn't have any
this effects some features like custom domain name

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/68fe8b88b99d4f01af705dfd805b97a34ea300ea/packages/playground/src/weblets/tf_node_pilot.vue#L54-L56

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/68fe8b88b99d4f01af705dfd805b97a34ea300ea/packages/playground/src/weblets/tf_node_pilot.vue#L95

### which network/s did you face the problem on?

Dev

### version

development_2.6

### Relevant screenshots/screen records

![Screenshot from 2024-06-27 13-59-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0042aa5b-38f4-4a6e-b297-e23c6ea18e3a)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
verified on devnet 
version : 0d964e5

deployed and worked fine

![Image](https://github.com/user-attachments/assets/f0dc4ca6-b6ac-450c-9e5f-570393ad7b66)
![Image](https://github.com/user-attachments/assets/b33f7d96-85f9-4d58-9c9a-ac06c429450a)
![Image](https://github.com/user-attachments/assets/7c345fc3-844c-49ed-a92a-ce6f1c45b859)

should we add a column for public ipv4 and ipv6 in the deployment list or shall we open another issue for this

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ac03039


![Image](https://github.com/user-attachments/assets/472e8e8d-08b6-40e5-a45b-966b9ea74295)

network columns for ipv4 and ipv6 are now added to deployment list
