### ISSUE TITLE
🐞 [Bug]: Solutions docs are removed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Docs are removed from solutions.

### Steps To Reproduce

- login and choose any solution
- try to navigate its docs

### which network/s did you face the problem on?

Dev

### version

2.5.0-rc3

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/80fd0c33-2954-4ae6-b0d5-1f3e4d2e0b61)

### Relevant log output

```console
-
```

**Comment by ehab-hassan** [comment]
WIP
Return docs at App but try to figure a better way for docs at contract and Minting Pages

**Comment by ehab-hassan** [comment]
Work completed 
PR pending in review

**Comment by khaledyoussef24** [comment]
verified on stagging 
version : ac03039
docs are now add in application info


![Image](https://github.com/user-attachments/assets/2f600374-b44d-4af5-8cf1-7ab35dc03b2b)
![Image](https://github.com/user-attachments/assets/cd7daa08-60cd-4fdd-ab9e-ee1e3a477576)
![Image](https://github.com/user-attachments/assets/be6fc1ae-6db6-44df-866b-2ef3e50198af)
