### ISSUE TITLE
Add delete all contracts button to contracts list 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3056]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Use delete all contracts in contracts list 

### Describe the solution you'd like

.

**Comment by 0oM4R** [comment]
[Screencast from 2024-08-04 18-22-17.webm](https://github.com/user-attachments/assets/4cd6c6c4-3d97-468b-98c6-b025171c34ac)

work completed:
Added a delete all button.

> just need to test two scenarios:
>  ~1- when have node contracts on on rented node~
> 2- grace period

**Comment by 0oM4R** [comment]
should the use be able to delete grace period contracts ?

**Comment by AhmedHanafy725** [comment]
it should delete all the contracts (created or grace period)

**Comment by A-Harby** [comment]
Verified, Devnet 07280a7.

The delete all was added to your contract page, and it successfully deletes every contracts.

![image](https://github.com/user-attachments/assets/8a225ca5-f476-4b39-8a4f-ddf81dfdc678)

![image](https://github.com/user-attachments/assets/e62637c2-93af-4ade-ab3e-2618331c6d90)

[screen-capture (3).webm](https://github.com/user-attachments/assets/f1fbd7f5-1cc1-4506-b152-216ad713d6e4)

[TC2746 - Delete All](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4333774)
