### ISSUE TITLE
lerna: remove caret `^` from dependencies version range  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3060]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

If we use older version of grid client for example `2.4.0`, its dependencies that contain `^` will have newer version.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/c9ff1cd9-267e-4e00-9016-deeb2eebf59d)
 

### Describe the solution you'd like

on `lerna version` we should update the dependencies with the exact new version, without any version range `comparator`

**Comment by A-Harby** [comment]
Verified, Devnet [v2.5.0](https://github.com/threefoldtech/tfgrid-sdk-ts/releases/tag/v2.5.0).

The lerna: remove caret `^` is removed from all installed version.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e747c09b-13b1-4786-9754-17d1fcd2894a)
