### ISSUE TITLE
🐞 [Bug]: `gridproxy_client` is used in gridclient but not included in its dependencies 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

while using `grid_client: 2.5.0-rc3` in outer package, the build fails due to`Error: Cannot find module '@threefold/gridproxy_client'`

### which network/s did you face the problem on?

Dev

### version

2.5.0-rc3

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/845d4cf8-198e-4e33-801d-558bf6d2cf7c)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
Verified, Devnet 2.5.0-rc3.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4633a763-eeaf-482e-8b4f-a70edb1e2a38)
