### ISSUE TITLE
🐞 [Bug]: Incorrect 'Contracts in Grace Period' Notification Displayed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I'm not sure if this happens all the time but I had contracts in grace period and the toast kept showing even after I got enough TFTs.

### Steps To Reproduce

- login with account that has grace period contracts
- get more TFTs
- logout and login

### which network/s did you face the problem on?

Dev

### version

11fa297

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b45b807a-9885-45df-87a8-5276a6104d4e

All my contracts are in created state as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/262144f6-ca50-48e3-a49b-f3f753b0160b)

### Relevant log output

```console
-
```

**Comment by AhmedHanafy725** [comment]
the warning was on the offline node not the grace period
