### ISSUE TITLE
Refactor error types or introduce new class 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3071]
### Which package/s are you suggesting this feature for?

types

### Is your feature request related to a problem? Please describe

For TFChain not all errors are handled, we can't sync the changes of the chain errors.
many tfchain errors got thrown as generic tfchain error  

### Describe the solution you'd like

we should have an error class that have module name and error name props, and can be passed the contractor

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

- Created a new Error wrapper to throw errors based on their type.
- Determined the type of error and threw it accordingly.
- Updated the error interface to differentiate between Module, Token, and other error types.
- Remove the TFChain error from the types package.
