### ISSUE TITLE
Refactor tfchain `_applyExtrinsic` error handling to include other dispatch errors 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3072]
### Which package/s are you suggesting this feature for?

tfchain_client

### Is your feature request related to a problem? Please describe

dispatch error have other types than module e.g token. this is not handled, and it got thrown as generic tfchain error
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/db2daf4712060aa6b098fdb0cbcce07fa3512b63/packages/tfchain_client/src/client.ts#L378-L389

### Describe the solution you'd like

add new method to pars the error and throw the proper error type,
 #3071

**Comment by Mahmoud-Emad** [comment]
## Issue update

### Work done

- Created a new Error wrapper to throw errors based on their type.
- Determined the type of error and threw it accordingly.
- Updated the error interface to differentiate between Module, Token, and other error types.
- Remove the TFChain error from the types package.
