### ISSUE TITLE
🐞 [Bug]: Can not find docs in applications in the dashboard

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

can not find docs for applications 

### which network/s did you face the problem on?

Dev

### version

2.6

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-07-03 at 10 09 40 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ecda44f3-4d91-44cf-a27f-c08875600861">

### Relevant log output

```console
NA
```

**Comment by ramezsaeed** [comment]
Dublicate: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3049
