### ISSUE TITLE
🐞 [Bug]: Can't login into my twin `Mnemonic doesn't seem to be valid` after the 14 days of expiration date

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, tfchain_client

### What happened?

I can't login to my twin. `Mnemonic doesn't seem to be valid`, I made sure that mnemonic was correct and tried a few times but still got the same error.

I think it was probably caused by this: https://github.com/threefoldtech/tfchain/issues/979.

### which network/s did you face the problem on?

Dev

### version

db2daf4

### Twin ID/s

1174

### Relevant screenshots/screen records

This is the error I get.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/98b6ee68-8e5f-42be-9ffd-40d32ebbf878)

And I sure twin is not deleted or something.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/009b62da-cf5c-4ffc-9b28-4bc99bb190e8)

The contract is still on grace period, which is not correct.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e245246d-7a39-41ba-b7f0-b7b7b75aca2b)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
not produced as the mnemonic that was used had a mistake, the account works fine now
![image](https://github.com/user-attachments/assets/e872f980-a7a9-4702-84da-95bbbf4d84a9)

**Comment by A-Harby** [comment]
My mistake must have been that I added a letter to the mnemonics by mistake.
