### ISSUE TITLE
`sdk-ts` : Support multiple stacks per network 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3078]
https://github.com/threefoldtech/home/issues/1550

**Comment by 0oM4R** [comment]
Issue update :
started to implement the logic but can't use the monitor package 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/11b58ac6-38ef-422f-a723-6e023478ab13)

**Comment by 0oM4R** [comment]
also current mentor services logs the aliveness of the services but do not return any values,i think it need some refactor adding new methods

**Comment by 0oM4R** [comment]
WIP: creating the logic to pick the first available stack per service add this init class to the `alivenessCheck` in monitoring 
```ts
export class serviceStackPicker {
  private result: ServicesUrls = {};
  constructor(public options: StackPickerOptions) {}

  private async pingService(service: ILivenessChecker) {
    const status = await service.isAlive();
    if ("disconnect" in service) {
      await (service as IDisconnectHandler).disconnect();
    }
    return status;
  }
  async GetAvailableServices(): Promise<ServicesUrls> {
    if ("tfChain" in this.options)
      this.result.tfChain = await this.getAvailableServiceStack(
        this.options.tfChain.slice(1),
        new TFChainMonitor(this.options.tfChain[0]),
      );
    if ("gridProxy" in this.options)
      this.result.GirdProxy = await this.getAvailableServiceStack(
        this.options.GirdProxy.slice(1),
        new GridProxyMonitor(this.options.GirdProxy[0]),
      );


    return this.result;
  }
  async getAvailableServiceStack(urls: string[], service: ILivenessChecker) {
    let index = 0;
    do {
      const status = await this.pingService(service);
      if (status.alive) return service.serviceUrl();
      console.log(`${service.serviceName()}: failed to ping ${service.serviceUrl()}, due to ${status.error}`);
      service.setServiceURl(urls[index++]);
    } while (index < urls.length);
  }
}
```
and should be called anywhere with
```ts 
 const test = new serviceStackPicker({
    tfChain: ["faf", "wss://tfchain.dev.grid.tf/ws", "wsss://tfchain.dev.grid.tf/ws"],
    GirdProxy: ["hahah", "https://gridproxy.dev.grid.tf"],
  });
  console.log(await test.GetAvailableServices());
```

this snips is the initial phase of coding, feel free to suggest any refactors

**Comment by 0oM4R** [comment]
Issue Update: 
monitoring part is almost ready, will support accessing the pick function directly and make the #3105 ready for review.

**Comment by 0oM4R** [comment]
Issue update: 
was investigating how to read and pars array form user, but i can't reach anything;

WIP: creating a script to read from user the stacks for each service and then will convert it to string and export it 
current behavior 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/ef772fd8-6ffb-45ae-908d-7cc708c01a1d)

**Comment by AhmedHanafy725** [comment]
it shouldn't be interactive. you can export them with comma-separate then split them in the script

**Comment by 0oM4R** [comment]
> it shouldn't be interactive. you can export them with comma-separate then split them in the script

done export target stacks separated with comma will work fine
![image](https://github.com/user-attachments/assets/e7c3174d-b0a7-42b6-9437-41ddabbc1015)

**Comment by 0oM4R** [comment]
Issue update: 
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3105 got some changes: 
- add stats and activation services
- fix build for browser 
- replace fetch with axios
- refactor sendRequest to adapt graphQl requests
- add options to allow validating tfchain while validating rmb, or take the provided tfchain url as it is

**Comment by 0oM4R** [comment]
Issue update: 
#3105 had some refactors 
WIP: finding a way to integrate this logic with playground

**Comment by 0oM4R** [comment]
Issue update:  applied pr comments and introduce new features

**Comment by 0oM4R** [comment]
New monitoring pr is ready : https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3134

**Comment by 0oM4R** [comment]
All review comments applied on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3134

**Comment by 0oM4R** [comment]
Issue update: 
fixed some issues in monitroring while integrating it in UI, 

**Blocker**: 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/0a5568e40f31ebe8399e59ef31eedc6d75eefe02/packages/playground/src/clients/index.ts#L1-L10

those clients got loaded before initializing the envs and got undifined urls, suggest moving those clients to grid store

**Comment by 0oM4R** [comment]
Issue Update:
Monitoring integrated in playground
Blocker: Not sure yet should we provide fake mnemonic for RMB monitor or what

![Screenshot from 2024-07-24 19-14-39](https://github.com/user-attachments/assets/104726d9-8a90-44ca-9692-8f5feafc6b46)

**Comment by 0oM4R** [comment]
all requested changes applied, and ui is ready as well.

**Comment by 0oM4R** [comment]
As we discussed with @sameh-farouk, we can use chain `/health` endpoint to verify node rpc status, 
if it responds with 200 OK, then it is alive and we can rely on it

**Comment by 0oM4R** [comment]
Issue update 
 - now all services are monitored via fetch requests 
 - applied some review comments 
 

Blocker 
while pinging all urls in parallel, by passing url to the alive method, all urls give an error even if one of them is reachable
work on testing [branch](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development_monitoring__stacks_test_isalive)

**Comment by 0oM4R** [comment]
Issue update: 
I added the required fallback mechanism, but I'm facing a very wired issue, when we have more than one invalid url in the stack, the whole requested urls for all services got effected and gives Timeout error
![Screenshot from 2024-07-30 18-43-53](https://github.com/user-attachments/assets/0c90be15-dfd2-4b6e-ad8d-8104e286b85a) 

but if we remove one of the invalid/unreachable urls from the array it works fine. 
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/889190d255a1b5a762ca47a6c880e10f30e824a7/packages/monitoring/example/serviceURLManager.ts#L10

details of the new applied mechanism:
- isAlive method now takes an optional url param, and the default value is `service.url`.
- store the promise result of `isAliveWithretires` for all stacks  in promise array 
    https://github.com/threefoldtech/tfgrid-sdk-ts/blob/889190d255a1b5a762ca47a6c880e10f30e824a7/packages/monitoring/src/serviceMonitor/serviceURLManager.ts#L128
-  resovle using `Promise.allSattled` and return the first fullfiled url in the promise array "first based the order of promises array" 
  https://github.com/threefoldtech/tfgrid-sdk-ts/blob/889190d255a1b5a762ca47a6c880e10f30e824a7/packages/monitoring/src/serviceMonitor/serviceURLManager.ts#L130-L131
  
  
**Concerns**:
this approach takes a lot of time, as `Promise.allSattled` waits for all stacks to resolve
so if i have 2 urls first one has a response on the first try, and the second is unreachable 
i have to wait for the second one to exhausts all its retries, for our case, with base timeout 2 it will take about 12 seconds to response with the first url that already replied within the first 2 seconds 
![image](https://github.com/user-attachments/assets/d4ba256f-db0b-4ea1-86b0-7c87b5c759a2)

**Comment by 0oM4R** [comment]
Issue update :
resolved the issue of fetch by providing valid or existing urls
work completed: 
support url monitor in gridclient, code needs some cleanup and test then the pr will be ready

**Comment by 0oM4R** [comment]
I faced an issue while testing playground integration:  `getDefaultUrls` had braking changes as it used in playground and tests so will create new function that contain the new added logic

**Comment by 0oM4R** [comment]
work completed: 
- monitoring : https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3134
- dashboard: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3162
- grid client: https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3200

**Comment by A-Harby** [comment]
Verified, Devnet.

The stack is working fine, checking all the URLs at once with 3 retries and picking the working one in the same order as they were written.

For one failing but the other working.
![image](https://github.com/user-attachments/assets/6bf1258b-fa99-4971-acc5-f563c321c92d)

For all of them to fail.
![image](https://github.com/user-attachments/assets/87124753-ada1-4c14-b668-41e9c44db5e1)

For Grid client.
![image](https://github.com/user-attachments/assets/3cff9ae7-ee5e-40b5-b85e-b21d78f8a8e5)

Created an issue for the Grid Client to work as config in playground: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3399.

New test Case: [TC2825 - Run locally with multiple stack](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422337#case_4363617)

**Comment by khaledyoussef24** [comment]
verified 
used [Harby's test case and it is working fine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422337#case_4363617)

changed the stacks in the file of tfgrid-sdk-ts/packages/playground/public/config.js
<img width="955" alt="Screenshot 2024-09-30 at 3 13 18 PM" src="https://github.com/user-attachments/assets/8be5e764-66ef-4d6d-84ce-43f85dc93ca4">

and also tried to implement wrong urls in the file to check the behaviour
<img width="1680" alt="Screenshot 2024-09-30 at 3 18 21 PM" src="https://github.com/user-attachments/assets/68c5a552-edb4-499d-bbf3-c0ca6d190ceb">
if many stalk are there it would switch automatically to another one
as here : (left the same wrong urls  but added also the valid ones)
and the dashboard worked (but left some errors for the wrong urls

<img width="1680" alt="Screenshot 2024-09-30 at 3 20 27 PM" src="https://github.com/user-attachments/assets/dda42fbb-5bbe-4173-99e6-9544fe57b1e4">
