### ISSUE TITLE
add docs of node prices & discounts

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3080]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Need docs explaining how discounts, packages etc are used in calculations in node finder and pricing calculator 

### Describe the solution you'd like

Just a readme file with a clear explanation of all the calculations used

**Comment by ramezsaeed** [comment]
https://manual.grid.tf//knowledge_base/cloud/pricing/pricing.html
