### ISSUE TITLE
🐞 [Bug]: Grace period Error message enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I had many vms rented and my tfts was drained i got tfts but to unlock contracts i got to the contracts page but got an unclear error.

### Steps To Reproduce

1- Rent contracts
2- Let them go to grace period
3- go to the contracts page

### which network/s did you face the problem on?

QA

### version

2.5

### Relevant screenshots/screen records

![Screenshot 2024-07-04 at 4 04 57 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c18be515-811b-4b56-9871-c46b762f3606)
![Screenshot 2024-07-04 at 4 08 38 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0bf020ce-9eb6-4e19-b312-7a2955b89b11)
![Screenshot 2024-07-04 at 4 09 27 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/193c774c-3156-472b-97a3-72d3fa7c8ebe)

### Relevant log output

```console
NA
```

**Comment by 0oM4R** [comment]
this is not related to unlock process related to : #3083

**Comment by 0oM4R** [comment]
![Screenshot from 2024-07-10 11-18-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/6ff195b5-0bf9-4006-881e-32297928840a)
![Screenshot from 2024-07-10 11-18-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/89cb4872-145a-4c81-ac18-345a1b7bb5a0)

i got the same error and i found that the issue was in this contract meta

**Comment by samaradel** [comment]
I got an error here also 
![image](https://github.com/user-attachments/assets/c4743331-c422-4512-b849-915e83336165)

**Comment by 0oM4R** [comment]
I can't find a contract with the same issue, please if anyone has one let me know, 
for now, we will add error handling to normalize contract to avoid missing all contracts and freeze the page.

**Comment by 0oM4R** [comment]
Work completed: I added logic to collect the failed to normalize contract IDs, and after loading all contracts, it will show an error with those contract IDs.

**Blocker** : I can't access `contractID` as this ontract is of type contract in Gridproxy client and the proxy actually returns the contract id as `contract_id`, i opened an issue #3236  with that and already prepared the two prs

**Comment by khaledyoussef24** [comment]
I couldn't produce the same issue and even the account which i created the issue from is not showing it now 

![Image](https://github.com/user-attachments/assets/cfae184c-e071-420d-920d-a1a4b03ca252)
