### ISSUE TITLE
🐞 [Bug]: Unlocking grace period dialog  enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I had a grace period contracts and then i tried to unlock them can we add the total locked amount of tft in the confirmation message before unlocking

### Steps To Reproduce

1- make contracts go to grace period
2-try to unlock them
user should know how much he will pay in this step

### which network/s did you face the problem on?

Dev

### version

2.5

### Relevant screenshots/screen records

![Screenshot 2024-07-04 at 4 04 18 PM (2)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0f542500-d51f-4141-8d41-f92d9c1b7d36)

### Relevant log output

```console
Na
```

**Comment by Mahmoud-Emad** [comment]
I encountered a strange amount when trying to unlock my contracts. Additionally, the rent contract looks unusual compared to the others, which typically have an amount of around 6 TFT.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/b154833f-5d06-4fac-9074-ae8e430b2e6c)

This is the rent contract 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/778ed266-87fe-4d22-8c15-a4c441acc696)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 2.5.2

enhanced and looks better now
![Image](https://github.com/user-attachments/assets/fc1d42c2-2da2-41f7-8d58-4950adf17b2b)
![Image](https://github.com/user-attachments/assets/ad3d6fcb-6768-4229-a889-12de0e8b2762)
![Image](https://github.com/user-attachments/assets/1de0301b-d9fa-4648-a324-f11e77f9dae5)
![Image](https://github.com/user-attachments/assets/5d1f2760-8ebd-44c3-abf0-b5f3d674cfa0)
