### ISSUE TITLE
🐞 [Bug]: After unlocking grace period contracts can not find my contracts

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

unlocked my contracts after they were in grace period but then can not find them in contract lists but found them in the full vm deployment list

### which network/s did you face the problem on?

QA

### version

2.5

### Relevant screenshots/screen records

![Screenshot 2024-07-04 at 4 08 30 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c4bf5c01-1a7f-47fa-90b6-1c77dbd5650f)
![Screenshot 2024-07-04 at 4 15 34 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b04fa9c3-5c51-4983-88db-f2039bc966b9)
![Screenshot 2024-07-04 at 4 15 36 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/275c5abe-0c03-4d9a-87f2-d60a17b5e750)
![Screenshot 2024-07-04 at 4 18 28 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b82f5fae-3276-424f-a994-eb21e2689688)

![Screenshot 2024-07-04 at 4 16 10 PM](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/89503903-30a5-456e-938d-e724aa661dff)

### Relevant log output

```console
NA
```

**Comment by 0oM4R** [comment]
can't reproduce on ubmrel and full vm

[Screencast from 07 يول, 2024 EEST 10:37:57 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7c008b64-6a83-453c-bc46-ae826343b69f)
 
[Screencast from 07 يول, 2024 EEST 10:30:00 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0371e01b-ba25-4033-af77-2f6c448b32a2)
