### ISSUE TITLE
Deployment Tables Summary: Summary of all individual solution tables in one place

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#3092]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

As of now, all deployment types, e.g. micro VM, generates a deployment table with the deployment info.

It's very useful and working well. But what if you have 4 deployments, e.g. wordpress, micro vm, full vm and nextcloud.

To connect/find info, you need to remember you have those exact 4 deployments, go to those page individually and check the table info (or open each deployment page individually of all deployments, go to the bottom and see if you have a deployment of this solution type, to find the 4 you deployed).

This is not ideal and can take time for users with lots of deployments.

### Describe the solution you'd like

A solution would be to have somewhere on the dashboard where you can see all the deployment tables of all the deployments you have. It wouldn't show any empty tables of deployments you don't have (e.g. you have micro VM deployment, and it shows all the other table as empty).

UX with basic example:

- I deploy 3 deployments, wordpress, nextcloud, peertube
- I can go to the individual deployment page to see the individual table; OR
- I can go to the Deployments Summary Table and see the 3 deployment tables of wordpress, nextcloud and peertube.

### References

Just like we have a page to see all contracts, we could have a page to see all deployment tables.

**Comment by AhmedHanafy725** [comment]
related to #1602

**Comment by ramezsaeed** [comment]
duplicated to: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1602
