### ISSUE TITLE
Add Ubuntu 24.04 to the micro vm & fullvm flists in the dashboard

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3096]
make sure to use it as the default flist in both the micro vm and full vm

**Comment by maayarosama** [comment]
Blocked on https://github.com/threefoldtech/tf-images/issues/228

**Comment by khaledyoussef24** [comment]
verified on 2.5.2
network devnet
deployed on both Full vm and micro vm

![Image](https://github.com/user-attachments/assets/38ba8a5f-90b3-42f3-9be5-bb4a24c64e32)
![Image](https://github.com/user-attachments/assets/022371d7-84df-48f9-b1b2-d47faab5226c)
![Image](https://github.com/user-attachments/assets/a72f1c30-cba6-4be8-8bd7-438be777fb42)
![Image](https://github.com/user-attachments/assets/3db77546-2c61-40bb-9e9e-2d6bba9b08d0)
![Image](https://github.com/user-attachments/assets/1fabc82e-5c42-45ea-b2d4-edfaa0cf2ace)
![Image](https://github.com/user-attachments/assets/034cd004-7f3f-49bd-8d13-277d0d6186b3)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330)

**Comment by khaledyoussef24** [comment]
verified on 2.5.2
network devnet
deployed on both Full vm and micro vm

![Image](https://github.com/user-attachments/assets/38ba8a5f-90b3-42f3-9be5-bb4a24c64e32)
![Image](https://github.com/user-attachments/assets/022371d7-84df-48f9-b1b2-d47faab5226c)
![Image](https://github.com/user-attachments/assets/a72f1c30-cba6-4be8-8bd7-438be777fb42)
![Image](https://github.com/user-attachments/assets/3db77546-2c61-40bb-9e9e-2d6bba9b08d0)
![Image](https://github.com/user-attachments/assets/1fabc82e-5c42-45ea-b2d4-edfaa0cf2ace)
![Image](https://github.com/user-attachments/assets/034cd004-7f3f-49bd-8d13-277d0d6186b3)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330)
