### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3101]
parent: https://github.com/threefoldtech/home/issues/1554

**Comment by amiraabouhadid** [comment]
Added sentry to playground vue, reading docs on how to proceed

**Comment by amiraabouhadid** [comment]
Might cause problems in chatbot 
![image](https://github.com/user-attachments/assets/5efd8217-a5a8-46c2-8271-48ab5cd9acb5)

**Comment by amiraabouhadid** [comment]
Added sourcemaps and debugging. Looking into adding source code and running sourcemaps in CI

**Comment by amiraabouhadid** [comment]
was able to link sentry on dev.sentry to playground repo, able to view click generated error
added release number to error details

**Comment by amiraabouhadid** [comment]
waiting on [ops issue](https://github.com/threefoldtech/tf_operations/issues/2641#issuecomment-2245030601) to be resolved

**Comment by khaledyoussef24** [comment]
verified sentry is now integrated with dashboard
giving warning to vulnerabilities
detecting errors ![Image](https://github.com/user-attachments/assets/aba7f7b7-c62b-4507-ade2-1971468a921e)
[test suite](https://app.testlodge.com/a/26076/projects/40893/suites)
