### ISSUE TITLE
🐞 [Bug]: `Monitoring ` Retry logic in failed on RMB

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Monitoring

### What happened?

tried to run example of monitoring with invalid relay url and got an error after first try

### which network/s did you face the problem on?

Dev

### version

2.5.0

### Relevant screenshots/screen records

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d5fa5f96-f8ac-47ff-a524-7d21b61abb90)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
Verified, Devnet.

It worked with all the URL correct and with 2 invalid URLs.

![image](https://github.com/user-attachments/assets/d7b033ae-380b-460a-acbe-07d378409179)
