### ISSUE TITLE
🐞 [Bug]: IPV4 network option not showing with some applications

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

when trying to deploy both PeerTube and Subsquid applications,  I cannot see IPV4 network option.

### Steps To Reproduce

1- Navigate to the Dashboard
2- Connect your account.
3- Navigate to Deploy from the sidebar then click on Applications.
4- Navigate to the Peertube or Subsquid.
5- Expand network option.

### which network/s did you face the problem on?

Dev

### version

5ea3c0a

### Relevant screenshots/screen records

![peertube](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/b021e500-786a-4d1d-8a15-1e37925ffeac)

![subsquid](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/becaefaf-845e-429a-bcec-3eeeec1367c3)

### Relevant log output

```console
n/a
```

**Comment by khaledyoussef24** [comment]
verified ipv4 and ipv6 is now added to all applications 


![Image](https://github.com/user-attachments/assets/62ce86cd-a9c3-4ae6-8ed6-4d01f058e222)


![Image](https://github.com/user-attachments/assets/010b34a6-4504-47e8-9b04-2a766eec289f)
![Image](https://github.com/user-attachments/assets/4a1540a1-9f50-415f-ac00-01a684d28dd1)
![Image](https://github.com/user-attachments/assets/329742ff-fec1-444a-af1e-f1539f59ba26)
![Image](https://github.com/user-attachments/assets/0017e5d9-738d-4aec-9ec2-d75816d322bd)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4329590)
