### ISSUE TITLE
Make the buttons in unlock dialog consistent with other dialogs

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3109]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/d67d79fa-0be9-4754-944a-942dcaebf671)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/11662805/5eb56d91-986c-414f-bdbd-8507f76a9016)

please make sure that the action buttons are consistent with the rest of dialoges

_Originally posted by @samaradel in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3091#issuecomment-2212413753_

**Comment by samaradel** [comment]
### Work Completed:
Adjust contract dialog card dimensions.

**Comment by khaledyoussef24** [comment]
the dialogue of unlock all and selecting to unlock one contract is different and different in dimensions 
should they be in the same dimensions ?

![Image](https://github.com/user-attachments/assets/43d5f16c-83a5-4ab2-8970-b26e0370b870)
![Image](https://github.com/user-attachments/assets/01813800-4830-446b-9a2b-d41f983d11cd)

**Comment by samaradel** [comment]
### Work Completed:
Fix unlock all contracts dialog style

**Comment by khaledyoussef24** [comment]
verified on devnet
version : c112478
the dialog styles are now consistent
the unlock all : 


![Image](https://github.com/user-attachments/assets/fb58722d-b4d2-45ed-a8d8-c765e080d0f3)


unlocking one contract : 
![Image](https://github.com/user-attachments/assets/dbc52844-09d2-4f8e-9fb5-551ddaa5a5f0)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4295189)
