### ISSUE TITLE
🐞 [Bug]: Discourse Mail Server is enabled despite the solution having no public IP

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- While deploying Discourse application without a public IP, I observed that the Mail Server option is enabled and I could configure it and deploy the instance.

### Steps To Reproduce

- Navigate to the Dashboard
- Navigate to Deploy from the sidebar then click on Applications.
- Navigate to the Discourse deployment page by clicking on the Discourse card option
- Expand the network option and turn off the public IPV4 toggle
- Switch to the SMTP tab and add your smtp configuration and click the Deploy button

### which network/s did you face the problem on?

Dev

### version

cd929e2

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/32517137/9e500630-6077-4684-81d9-b9b8aab41fce

 ### Related Issue:
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2522

### Relevant log output

```console
n/a
```

**Comment by samaradel** [comment]
### Work in Progress (WIP):
found an issue coming from ```zos``` working on it

**Comment by samaradel** [comment]
Work in Progress (WIP):
The value of the switch is transformed somehow, debugging..

**Comment by samaradel** [comment]
### Work Completed:
Fix discourse TLS switch on transform data

**Comment by atefnazmy** [comment]
- The Issue is still producible as the SMTP option isn't disabled despite the solution having no public IP.

https://github.com/user-attachments/assets/d6deeca3-0da9-46a0-b22e-17be7663164f

**Comment by khaledyoussef24** [comment]
the issue is still producable 
<img width="1680" alt="Screenshot 2024-07-30 at 9 06 12 PM" src="https://github.com/user-attachments/assets/66d2b989-8f01-4229-93c6-fd8503e22b88">
<img width="1680" alt="Screenshot 2024-07-30 at 9 07 39 PM" src="https://github.com/user-attachments/assets/f42362dd-b3da-4a41-9bbe-701b03691acc">

**Comment by khaledyoussef24** [comment]
verified now public ip and mail server are related
version : 184fa12
in Discourse ipv4 is enabled and can not be disables so no problem with mail server




![Image](https://github.com/user-attachments/assets/f7c01c65-570f-4c4c-a91e-5f6db3cf90cd)



[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4150344)
