### ISSUE TITLE
Hide the node's price if the node is down

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3112]
Show the node's price if the node is rentable or rented by the logged-in user

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/ba4ebe48-5fda-4d80-b5e0-7769c3a9fe7b)

**Comment by samaradel** [comment]
### Work in progress:
Condition added in all node cards

**Comment by samaradel** [comment]
### Work Completed:
Show the node price if the node is rentable or rented by the logged-in user.

**Comment by khaledyoussef24** [comment]
verified on stagging 
network : devnet
version : ac03039
dedicated nodes which are down are without prices


![Image](https://github.com/user-attachments/assets/60c5ac74-4f9b-457b-a57d-3e70c8cecf95)
