### ISSUE TITLE
🐞 [Bug]: Offline & stand-by nodes which can be rented do not give gpu details

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

user shall be able to rent a gpu node even if the status of the node standby but i can not know any details of the gpu in that case

### Steps To Reproduce

1. go to node finder
2. search for a gpu node and status standby
3. click on the node to see the details
4. info of the gpu is not available

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-07-16 at 10 17 34 AM" src="https://github.com/user-attachments/assets/274ce59d-61a9-4995-bc60-005a4d1ba0bb">
<img width="624" alt="Screenshot 2024-07-16 at 12 41 58 PM" src="https://github.com/user-attachments/assets/ccf67f2a-538e-4b37-b89b-23b12b6da4eb">
<img width="378" alt="Screenshot 2024-07-16 at 12 42 03 PM" src="https://github.com/user-attachments/assets/bd49b676-c796-4bd4-a7df-2326e0d3aaa1">

### Relevant log output

```console
na
```

**Comment by Omarabdul3ziz** [comment]
proxy issue https://github.com/threefoldtech/tfgrid-sdk-go/issues/1144

**Comment by zaelgohary** [comment]
Work completed:

- Updated GridNode type in proxy
- Replaced cards arr with GPU arr from grid proxy
- Applied changes in Playground
- Removed repeated type & unnecessary code

**Comment by khaledyoussef24** [comment]
verified on devnet
Version fccc6af
![Image](https://github.com/user-attachments/assets/56eb7530-42f5-4952-ac2c-0741bfadd5e5)
![Image](https://github.com/user-attachments/assets/3c7c9bab-2b94-4a47-8f5c-82f0364bb63b)
![Image](https://github.com/user-attachments/assets/d8c64d98-2c03-4b92-a317-17f6df1a7724)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4401808)
