### ISSUE TITLE
🐞 [Bug]: The password field accepts spaces as a valid password

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- when creating a new twin account, the password field accepted the 6 spaces as a valid password and the new account has been successfully created. 

### Steps To Reproduce

- Navigate to The Dashboard.
- Click on Connect Your Wallet.
- Click on Create Account.
- Insert an Email.
- Enter a password.

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

https://github.com/user-attachments/assets/0f8ee3cb-7619-4a62-a95b-0233e5822092

### Relevant log output

```console
n/a
```

**Comment by 0oM4R** [comment]
We think that there is nothing wrong with a password that has spaces, and this change will also affect already-stored passwords
