### ISSUE TITLE
Adding validation to solution name

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#313]
### Description

There should be some validation on Solution Name input to prevent the special char.

Error message 
`Validation failed. errors: An instance of MachinesModel has failed the validation: - property name has failed the following constraints: isAlphanumeric ,An instance of MachinesModel has failed the validation: - property machines[0].name has failed the following constraints: isAlphanumeric`.

### Logs/Alerts

![image](https://github.com/threefoldtech/playground/assets/109473873/ee916777-730c-4568-87af-6c7c82e35f41)

![image](https://github.com/threefoldtech/playground/assets/109473873/80a56575-9f60-4670-98bb-62a26079fdca)

**Comment by xmonader** [comment]
should be enforced everywhere

**Comment by mohamedamer453** [comment]
Verified on devnet.

Name validation was added for all solutions. and now it only accepts alphanumeric values and can only start with a alphabetical value. and the `Deploy` button is disabled when there's a validation error

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e5ac5574-28c7-4989-be8d-802bb31d6981)
