### ISSUE TITLE
🐞 [Bug]: Unify SSH error message for new users

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Users with no ssh gets different warnings messages for creating a new ssh.
I think they shall be unified

### which network/s did you face the problem on?

Dev, QA, Test, Main

### version

2.5.2

### Relevant screenshots/screen records

messages for the vms and k8s 
<img width="1680" alt="Screenshot 2024-07-17 at 2 58 53 PM" src="https://github.com/user-attachments/assets/1f7542e8-e057-48dd-a172-f34f55ffa9c0">
<img width="1680" alt="Screenshot 2024-07-17 at 2 58 59 PM" src="https://github.com/user-attachments/assets/c9ee4682-c88f-4f81-983c-7cdbf602d2d8">
<img width="1680" alt="Screenshot 2024-07-17 at 2 59 03 PM" src="https://github.com/user-attachments/assets/5300f54e-d5fb-4678-8b3c-09a4c781ca74">
<img width="1680" alt="Screenshot 2024-07-17 at 2 59 08 PM" src="https://github.com/user-attachments/assets/f5d1de7b-f42b-4f39-832a-d9ae4b29d9fe">

in applications and solutions :
<img width="1417" alt="Screenshot 2024-07-17 at 3 00 16 PM" src="https://github.com/user-attachments/assets/f7c36df9-2528-4dc0-a831-c146a3bd4917">

i think this one is much better

### Relevant log output

```console
NA
```

**Comment by ramezsaeed** [comment]
That's because in these yellow waning means ssh its not a must to use the application as you already have the domain deployed.
