### ISSUE TITLE
🐞 [Bug]: Mnemonic field content is replaced with wrong data after providing a pre-existing Email in case the browser autofills 

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while creating a new twin and pressing on Create Account button it generates a new Mnemonic, then after providing a pre-existing Email, the Mnemonic field content is replaced with my previous account's Password.

### Steps To Reproduce

- Navigate to The Dashboard.
- Click on Connect Your Wallet.
- Empty the autofilled mnemonics field
- Click on Create Account.
- Accept terms and conditions
- Insert a Pre-exist Email.

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

https://github.com/user-attachments/assets/17f1f72d-d400-4aca-b431-95fff0a4c034

### Relevant log output

```console
n/a
```

**Comment by khaledyoussef24** [comment]
could not produce the same issue will also check on different browser

**Comment by khaledyoussef24** [comment]
still not producible will check with atef

**Comment by atefnazmy** [comment]
- Verified on devnet
- Version: ac03039
- The Issue has been fixed and is not producible anymore.

https://github.com/user-attachments/assets/3e325023-aac4-43f9-956a-bf0394dbb577


### Related Issue:
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2630
