### ISSUE TITLE
🐞 [Bug]: adding worker on k8s is not functional

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while adding worker to k8s after adding it the worker is not shown in the master

### Steps To Reproduce

1. deploy k8s with one worker
2. add a worker to the same cluster
3. go to the master ssh on it and use `kubectl get nodes`
4. the other worker is not shown

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-07-17 at 10 19 48 PM" src="https://github.com/user-attachments/assets/a2e9df89-02e8-4cd7-a81a-3f55753f2428">

### Relevant log output

```console
na
```

**Comment by khaledyoussef24** [comment]
tried on different deployment and faced this
<img width="1680" alt="Screenshot 2024-07-17 at 10 40 12 PM" src="https://github.com/user-attachments/assets/57496e96-25ab-46b1-9618-7d3f95fbca8a">

**Comment by atefnazmy** [comment]
- The issue isn't Reproducible anymore.

![Screenshot from 2024-07-23 10-13-17](https://github.com/user-attachments/assets/cf84434a-fb2a-421c-b2d3-327a829182ac)
