### ISSUE TITLE
🐞 [Bug]: Many Dashboard Functions Cannot be seen when the Logs tab is opened

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- The most dashboard Functions cannot be seen when opening the Logs tab and trying to do another action.

### Steps To Reproduce

- Navigate to the Dashboard.
- At the bottom of the screen, click on Dashboard Logs.
- From the sidebar select `Deploy` for an example and try different options.

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

https://github.com/user-attachments/assets/4dbefd20-b95a-4b05-8a70-dd3e9bed542b

### Relevant log output

```console
m/a
```

**Comment by 0oM4R** [comment]
**Suggestion**: collapse on click outside the logs tab

**Comment by samaradel** [comment]
### Work Completed:
Close logger tab when clicking anywhere except the logger component and its children

**Comment by khaledyoussef24** [comment]
verifed on devnet
version : 967b554


https://github.com/user-attachments/assets/b4b51730-0a4a-43ed-852a-9e5dee7c94d6

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4331140)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- cc9b035
