### ISSUE TITLE
Root File System (GB) in Micro VM shouldn't be validating when resource changes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#314]
### Description

The Root File System (GB) input in Micro VM is validating whenever any of the resource changes.

### Logs/Alerts

[Untitled_ May 14, 2023 6_32 PM.webm](https://github.com/threefoldtech/playground/assets/109473873/fd83ff9e-52e8-4c94-8d7a-d4e57c637a52)

**Comment by xmonader** [comment]
The min allowed root fs depends on the cpu and ram

https://github.com/threefoldtech/zos/blob/f620733482d75f14972491096d162ea91bddf069/pkg/gridtypes/zos/zmachine.go#L129
