### ISSUE TITLE
reduce the number of columns in deployment list (remove the need to scroll)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3146]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

![image](https://github.com/user-attachments/assets/a47d87bb-7227-47c9-9444-0919c8b846e4)

It seems to be that there're so many columns right now,

### Describe the solution you'd like

suggestion is we start hiding public ipv6 and ygg column or maybe move to a card based design instead of a table?

**Comment by 0oM4R** [comment]
**Suggestion**: remove some network values and reduce flist length

**Comment by zaelgohary** [comment]
Work completed:

Removed some networks from vm & k8s. Renamed flist in vm table.

**Comment by khaledyoussef24** [comment]
verifed on staging
Full vms : 


![Image](https://github.com/user-attachments/assets/27e0d89c-64e6-4fc9-bfd2-2ecbcbd83a13)

micro : 



![Image](https://github.com/user-attachments/assets/066689f2-25bc-4d47-b9a9-76db9186b4cc)



k8s : 


![Image](https://github.com/user-attachments/assets/3f37a950-1b31-4805-83e0-7aa1ca553854)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 28e17de
![Screenshot from 2024-08-19 13-23-28](https://github.com/user-attachments/assets/bff8e17a-feba-4789-8486-1542059c1ac8)
