### ISSUE TITLE
🐞 [Bug]: email should be retrieved if the mnemonic are ok during login and its validation needs fixing

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

1- I expect the dashboard to fetch the email for me and fill the form if the mnemonic were okay
2- if i try to submit the form without the email filled in (and it's mandatory, i should see a validation error)

### Steps To Reproduce

I already entered my email before, now in a new browser i try to login. I paste my mnemonic and and encryption password and I don't remember the email.

### which network/s did you face the problem on?

Main

### version

3.14

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/98ba3f96-391c-44c4-8b50-ffda83ba5726)
no validation on email and yet the button is disabled 

### Relevant log output

```console
N/A
```

**Comment by samaradel** [comment]
### Work Completed:
Load Email when mnemonic is entered if exists.

**Comment by A-Harby** [comment]
Verified, Devnet cddbd85.

The email is now auto-written if the mnemonic has already entered the email value before.

![image](https://github.com/user-attachments/assets/334c11d4-ef5d-4a9e-907c-d6af8208f390)
![image](https://github.com/user-attachments/assets/b6067802-6986-442d-bd5e-7ac0120aa823)

[TC2113 - Connect Wallet](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322)

**Comment by A-Harby** [comment]
The input is stuck loading. 

![image](https://github.com/user-attachments/assets/91cd818b-9016-4fc9-9e08-a9717a5fb83b)


`Error: TwinNotExistError: Couldn't find a user for the provided mnemonic on dev network.`

**Comment by samaradel** [comment]
### Work in Progress (WIP):
Investigating in checking if the mnemonic if it already has an account or not

**Comment by samaradel** [comment]
### Work Completed:
Fix Email loading when the profile doesn't have ```twinId```

**Comment by A-Harby** [comment]
Verified, Devnet 4829e02.

IF the twin is not registered on this network or doesn't have an email attached to it, it won't show an error anymore.
![image](https://github.com/user-attachments/assets/2082a34b-2106-4301-a05a-638b7980b097)
