### ISSUE TITLE
Support selecting the network while adding domain to vm

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3148]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

currently, the user can't select the network to deploy the gateway workload.

### Describe the solution you'd like

allow the user to select the network (yggdrasil, mycelium, public ipv4, and public ipv6) based on the supported networks on the vm.

**Comment by Mahmoud-Emad** [comment]
## Issue Update

### Work done

- Check if the IP is V6 and format it to match '[IP]:PORT' pattern
- Pass the IP if it's V4
- Created a new v-select that lists all supported VM networks
- Bind the selected network on mounting the page
- Refactor the vue component

**Comment by Mahmoud-Emad** [comment]
As @AhmedHanafy725 reported, there was an issue when selecting another network other than the WireGuard IP

```log
WorkloadDeployError: Failed to deploy gateway-name-proxy with name vm26vmf1d6qf on node 11 due to: failed to setup name proxy: failed to get user network: couldn't load network with id (pL1JFSUwD5VFC): open /var/run/cache/networkd/networks/pL1JFSUwD5VFC: no such file or directory.
```
So, to avoid this error, we must send the network option field only if the WireGuard IP selected

**Comment by A-Harby** [comment]
I deployed a FullVM with all the networks and git cloned a sample site, then hosted that site on port 8000.
And deployed a gateway using all the interfaces. 
![image](https://github.com/user-attachments/assets/0e422864-5965-4816-bd31-43fc1d3da760)
The server was shown on Wireguard and IPv4 only and failed on all of the other interfaces (Planetary, Mycelium, and IPv6).
![image](https://github.com/user-attachments/assets/7f739c63-fb65-42f1-a045-593d82ff94af)
![image](https://github.com/user-attachments/assets/77981234-650b-4f92-bb03-b45e0b440a23)

**Comment by Mahmoud-Emad** [comment]
Are you sure your server bind IPv6?

**Comment by A-Harby** [comment]
@Mahmoud-Emad mentioned to add IPv6 bind to server to accept IPv6, like `python3 -m http.server --bind ::` and it worked on all the interfaces.

Verified, Devnet 28e17de.
![image](https://github.com/user-attachments/assets/2604a977-b2eb-4a05-a819-00ebc4c709e7)

Created a test will all the steps needed: [TC2785 - Domain works on all Interfaces](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4344247)
