### ISSUE TITLE
Support managing domain on kubernetes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3149]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The user might have some solutions on the cluster that require an ingress with a domain.

### Describe the solution you'd like

It would be good if he could create domains pointing to the cluster's master.

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Work done

#### Changes

- Optimized the `ManageGatewy` component to work on both types of machines normal `VM` and `K8S` machine
- Generate the name based on the master
- takes the master networks as the domain-supported networks
- Change the dialog title to be dynamic
- Working on refactoring the component
- Load the WireGuard network name dynamic based on the machine type

#### Screenshots/Video

 [Screencast from 08-18-2024 03:10:58 PM.webm](https://github.com/user-attachments/assets/89de2baf-c59c-4849-9241-1e612823da9a)

**Comment by Mahmoud-Emad** [comment]
After some investgation we found that our K3S image binds on IPv4 and won't work on IPv6 e.g. Mycelium or Planetary networks, we need to search if there a way to bind on both IPs v4 or v6 without break the current behavior

**Comment by Mahmoud-Emad** [comment]
Due to https://github.com/threefoldtech/tf-images/issues/291 we have 2 options now

1. - [x] Support only IPv4 and Wireguard networks
2. - [ ] Wait until the operations update the K3S image

**Comment by Mahmoud-Emad** [comment]
During the implementation, we discovered and agreed on:

- -[x] Set the default port to 443
- -[x] Define a new selector that lists all node's master/workers
- -[x] Let the user select the target node and load its interfaces based on the selected node
- -[x] Remove any V6 from the networks, let the user only choose Public IPv4 or Wireguard 

We'll go with the first option

> Due to [threefoldtech/tf-images#291](https://github.com/threefoldtech/tf-images/issues/291) we have 2 options now
> 
> 1. * [x]  Support only IPv4 and Wireguard networks
> 2. * [ ]  Wait until the operations update the K3S image

**Comment by Mahmoud-Emad** [comment]
During the implementation i faced this bug https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3321

**Comment by A-Harby** [comment]
Can we change one of the logo of the manage workers or domain? Both having the same logo is kind of confusing.
![image](https://github.com/user-attachments/assets/c918521c-e533-48f6-9aaf-661f83744b5d)

And maybe we add a new column to identify to whom this domain is attached to (master or which worker).
![image](https://github.com/user-attachments/assets/67eb5ff3-04c5-4374-b23b-3b4819a1aa45)

**Comment by A-Harby** [comment]
Not all the domain interfaces are shown.

I deployed worker with all the networks.
![image](https://github.com/user-attachments/assets/fd7a7dbb-5609-4881-8c17-61a59d9377d5)

But it only shows me Wireguard and IPv4.
![image](https://github.com/user-attachments/assets/58283d31-3391-4b9c-9ed3-4d4077ce8d70)

And master with deployed with planetary and mycelium, but also it only shows wireguard.

**Comment by Mahmoud-Emad** [comment]
> Can we change one of the logo of the manage workers or domain? Both having the same logo is kind of confusing. ![image](https://private-user-images.githubusercontent.com/109473873/362387216-c918521c-e533-48f6-9aaf-661f83744b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzg3MjE2LWM5MTg1MjFjLWU1MzMtNDhmNi05YWFmLTY2MWY4Mzc0NGI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzZkMzkxMTc0ODBlYWYzNzUyN2U5ZWRkMWQ3ZWQyN2M0ZDgxYzgxMDY4YjhkZDljMWQyNTc1NmIzMzRhOTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mmU846kFhsXa5Go3UJ4UtM5dFEobEsem5af4DlpgliM)
> 
> And maybe we add a new column to identify to whom this domain is attached to (master or which worker). ![image](https://private-user-images.githubusercontent.com/109473873/362390882-67eb5ff3-04c5-4374-b23b-3b4819a1aa45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzkwODgyLTY3ZWI1ZmYzLTA0YzUtNDM3NC1iMjNiLTNiNDgxOWExYWE0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTQzYjUyNDE3MDMxOGQ2ZDYwMjJkYzJkOTQ5OTAwNjNkOGIzYzZjNGY3YzRiNmY5YzUwZGI4MmJjNDBkMDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fzh8wls6IT1XGHv9t0GUr3696IwbC2kx7JI0Fduvwf4)

@ehab-hassan , please give it a look

**Comment by Mahmoud-Emad** [comment]
> Not all the domain interfaces are shown.
> 
> I deployed worker with all the networks. ![image](https://private-user-images.githubusercontent.com/109473873/362393491-fd7a7dbb-5609-4881-8c17-61a59d9377d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzkzNDkxLWZkN2E3ZGJiLTU2MDktNDg4MS04YzE3LTYxYTU5ZDkzNzdkNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDRlMDg1ZTM2MjJkMTQ5OWRmNWNiMzgyZDFkYmQzOWYyM2YxODUxODk4NGE5NTdjODhkNzU4YzhlZmViMjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.afUwUAciyqlqRI1y8N7LjjLNyYsYQqa9-DjqT7GEvpE)
> 
> But it only shows me Wireguard and IPv4. ![image](https://private-user-images.githubusercontent.com/109473873/362393273-58283d31-3391-4b9c-9ed3-4d4077ce8d70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzkzMjczLTU4MjgzZDMxLTMzOTEtNGI5Yy05ZWQzLTRkNDA3N2NlOGQ3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzQ5NmIyODcwYTMxNjJmNDIwZWRhZDcwNzJjNDIyZDY5NWQwNjU4Nzk0YjQxYWJjMzY4YmMyOTA4YjcyNWYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1EHlag7WHYb6hP8fauArJJ-L-vnFb1R7XnaKpfo8Pw8)
> 
> And master with deployed with planetary and mycelium, but also it only shows wireguard.


@A-Harby , Please see the above comment

> Due to https://github.com/threefoldtech/tf-images/issues/291 we have 2 options now

> 1. - [x] Support only IPv4 and Wireguard networks
> 2. - [ ] Wait until the operations update the K3S image

**Comment by ehab-hassan** [comment]
> > Can we change one of the logo of the manage workers or domain? Both having the same logo is kind of confusing. ![image](https://private-user-images.githubusercontent.com/109473873/362387216-c918521c-e533-48f6-9aaf-661f83744b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzg3MjE2LWM5MTg1MjFjLWU1MzMtNDhmNi05YWFmLTY2MWY4Mzc0NGI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzZkMzkxMTc0ODBlYWYzNzUyN2U5ZWRkMWQ3ZWQyN2M0ZDgxYzgxMDY4YjhkZDljMWQyNTc1NmIzMzRhOTM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mmU846kFhsXa5Go3UJ4UtM5dFEobEsem5af4DlpgliM)
> > And maybe we add a new column to identify to whom this domain is attached to (master or which worker). ![image](https://private-user-images.githubusercontent.com/109473873/362390882-67eb5ff3-04c5-4374-b23b-3b4819a1aa45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTIxNDYsIm5iZiI6MTcyNDkxMTg0NiwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzkwODgyLTY3ZWI1ZmYzLTA0YzUtNDM3NC1iMjNiLTNiNDgxOWExYWE0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwNjEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTQzYjUyNDE3MDMxOGQ2ZDYwMjJkYzJkOTQ5OTAwNjNkOGIzYzZjNGY3YzRiNmY5YzUwZGI4MmJjNDBkMDhjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fzh8wls6IT1XGHv9t0GUr3696IwbC2kx7JI0Fduvwf4)
> 
> @ehab-hassan , please give it a look

use this  for Workers
https://pictogrammers.com/library/mdi/icon/cube-outline/

and Globe for domain

also, we had a tooltip here to be cleared to the user

**Comment by Mahmoud-Emad** [comment]
@ehab-hassan 
We can't use the Globe icon for the domain for two reasons

1. The manage domains icon in the VMs view is the `settings` icon, so we have to be consistent.
2. The Globe icon used in the `Manage Domains` modal and point to redirecting the user to the domain

IMO. setting it as the settings icon and only changing the `Manage workers` icon might be good, what do you think?

**Comment by Mahmoud-Emad** [comment]
> Can we change one of the logo of the manage workers or domain? Both having the same logo is kind of confusing. ![image](https://private-user-images.githubusercontent.com/109473873/362387216-c918521c-e533-48f6-9aaf-661f83744b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMwNzAsIm5iZiI6MTcyNTM2Mjc3MCwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzg3MjE2LWM5MTg1MjFjLWU1MzMtNDhmNi05YWFmLTY2MWY4Mzc0NGI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTI2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjE2MmI4MDZmNWY0MDc4MDcxNjY4ZDkyZTJiZDI4NjdiOGQ0YzdkOGQ5YzRmZDZmOTRlNWRkMTQwNWYwMzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bgr9AoYO5j3-CRct_yYwAM8whJJgNseJQG6C8Nvp4rQ)
> 
> And maybe we add a new column to identify to whom this domain is attached to (master or which worker). ![image](https://private-user-images.githubusercontent.com/109473873/362390882-67eb5ff3-04c5-4374-b23b-3b4819a1aa45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjMwNzAsIm5iZiI6MTcyNTM2Mjc3MCwicGF0aCI6Ii8xMDk0NzM4NzMvMzYyMzkwODgyLTY3ZWI1ZmYzLTA0YzUtNDM3NC1iMjNiLTNiNDgxOWExYWE0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTI2MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Y2YxNzlkOGY2ZGQ3ZWZlY2QwNGI0ZWFlOWVjYWJlOGFjYjBjNDY3MGM5MDZlNTkxYzdkNjM0ZDRhZGYxOTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ovx-z-p650wV1BUz0YyEBWZubWWtAy92-HNueYivLi8)

@A-Harby 
Please check

**Comment by A-Harby** [comment]
Verified, Devnet 4829e02.

Icons of manage worker was changed.
![image](https://github.com/user-attachments/assets/3ec02a3c-27b6-4ef5-8f6b-1d42fe51ed89)

And a new column was added to identify which master or worker the domain is attached to. 
![image](https://github.com/user-attachments/assets/b37671d3-a1f2-4b30-ba74-183735f2ae2e)

And the domains are working correctly on master and workers (for wireguard and IPv4 only).
![image](https://github.com/user-attachments/assets/c0cb5886-b70a-4ccf-873a-0a94019806e1)

New test case: [TC2815 - Add domain to a Kubernetes master and worker](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4359725)

**Comment by A-Harby** [comment]
Unfortunately, I found a bug when the TLs is turned on; the domain won't work, and the attached file disappears!.

![image](https://github.com/user-attachments/assets/31b17b98-1e9c-4f1e-9c57-fea990cbc54d)
![image](https://github.com/user-attachments/assets/1a49cd70-97b6-450b-bec6-9af9cb37ecc7)

**Comment by Mahmoud-Emad** [comment]
> Unfortunately, I found a bug when the TLs is turned on; the domain won't work, and the attached file disappears!.
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/364027259-31b17b98-1e9c-4f1e-9c57-fea990cbc54d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDcwMDMsIm5iZiI6MTcyNTQ0NjcwMywicGF0aCI6Ii8xMDk0NzM4NzMvMzY0MDI3MjU5LTMxYjE3Yjk4LTFlOWMtNGYxZS05YzU3LWZlYTk5MGNiYzU0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDQ1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjk0NzBiNTc2Yzg3ZDU1MGU3NWEwOWNhZDc2NTg0MmMwYmJjODQ0ZTc4OTNhOTdjZjdhMzI0Mjk4M2U0ODMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rgzoQ1l7hTfOw_F6oWjirQ52qc_bPDgpX90bkGEiczs) ![image](https://private-user-images.githubusercontent.com/109473873/364029260-1a49cd70-97b6-450b-bec6-9af9cb37ecc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDcwMDMsIm5iZiI6MTcyNTQ0NjcwMywicGF0aCI6Ii8xMDk0NzM4NzMvMzY0MDI5MjYwLTFhNDljZDcwLTk3YjYtNDUwYi1iZWM2LTlhZjljYjM3ZWNjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMDQ1MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOWYyZWRjYjU1MGEwNDQ3NmI1ODdlZDFmYjQ4MDMyOTE0MTI0NDg2NzIyMDQ4ODgxOTg0OTc0NDQ3MmVmZDM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d7SEay_sH7Voxui6ZK2NIiFSBmugLTeUOuBB3NrMAMA)

@A-Harby 
Yeah, there is an issue with loading the attached machine name in case the machine is enabled with the TLS option, However, how do you run the server inside the machine?

**Comment by A-Harby** [comment]
Verified Devnet, ebe226c.

The loading attachment bug was solved, and the name now appears on TLs on or off.
![image](https://github.com/user-attachments/assets/4f8d0e57-011b-49bc-b538-7a5b716c6fb3)

And also, the domain is working.
![image](https://github.com/user-attachments/assets/f517f72a-c3f8-49ca-8dcf-036d9ecfb6d7)

Updated the test case with ingress steps: [TC2815 - Add domain to a Kubernetes master and worker](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4359725)
