### ISSUE TITLE
Add compare locked balance script

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3152]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

Add a script where you compare user's frozen balance & the contracts locked balance. The script should return any mismatched accounts.

### Describe the solution you'd like

-

**Comment by khaledyoussef24** [comment]
verified the script is now in the grid client scripts and working fine giving details for all contracts and locked tfts


![Image](https://github.com/user-attachments/assets/6b27c20c-425b-4207-8528-d7b0b5513013)
![Image](https://github.com/user-attachments/assets/ecaa9eaa-4cf4-49b3-bf17-69fcfb41e84e)
![Image](https://github.com/user-attachments/assets/6edc0f11-103a-4a35-a76d-3ddd951f2cf6)
![Image](https://github.com/user-attachments/assets/2d82bcbb-34ea-42b5-9c34-ab372d27df36)
![Image](https://github.com/user-attachments/assets/3abdd2d0-63bc-4416-986c-04f8b808fc25)
![Image](https://github.com/user-attachments/assets/83e62e32-e5d2-4f48-bba3-3b56770ee81a)
![Image](https://github.com/user-attachments/assets/b0f2fe3a-6d77-42dc-8532-d70580afdd2c)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_4326497)
