### ISSUE TITLE
Add more info and tool tips for fields and option that aren't very clear for the user

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#316]
### Description

Tool-tips should be added for multiple fields in order to clarify the options for the user. for each of the fields that i'm going to mention only a brief description should be added and the full description should be available in the quick start docs. this issue will mainly include options and fields that are not clear for the average user that doesn't have a technical background or stuff that are related to the grid only and not used in other cases or solution specific options.

 Some of these fields are:

- Network Selectors in every deployment (specially the `Planetary Network` & `Wireguard Access` since these options are not clear for the average user) 

   ![image](https://github.com/threefoldtech/playground/assets/101194226/98434800-904a-4793-8faa-b929dad355e7)

- `Flist` & `Entry Point` fields (Micro & Full VM)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/f7d63467-cf44-42db-b3c0-f9220b866aa0)

- `Environment Variables` (Micro VM)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/f468d919-2d08-4a21-8047-289d29d1f640)

- `Cluster Token` (Kubernetes)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/52fbe196-f111-4eff-8369-48fdf8239f88)

- `Gateway Node` (All solutions that require a gateway node)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/4e3bbb39-bd59-4012-b393-cc1ba1350046)

- `Presearch Registration Code`, `Public, Private Restore Keys`

   ![image](https://github.com/threefoldtech/playground/assets/101194226/88df23d7-2a22-44db-92d1-1cef0a980de6)

   For the restore key it should be treated like the smtp option in other deployments since it's not required. (With a toggle button to activate it if needed) and the info should be above both fields mentioning that this option is not required and should only be used in case of restoring old instances.

   ![image](https://github.com/threefoldtech/playground/assets/101194226/6652ae28-962a-4c07-9042-6eb5c6091034)

- `Websocket Endpoint` (Subsquid)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/40cda9a4-61b8-49d3-b6a7-b047a8966823)

- `Network` , `Node Type` (Algorand)

   ![image](https://github.com/threefoldtech/playground/assets/101194226/519fdf3c-7f13-44fc-afff-925af60fd6c1)

**Comment by mohamedamer453** [comment]
Tooltips were added but it still needs some improvement.

### Network options
  
It's not clear that there are info available for these fields since you have to hover over the toggle button for it to appear, same thing for the root fs field. i think it would look better if these fields had the same `i` icon next to them to make it very clear for the user.

[Screencast from 15-06-23 13:17:55.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6c2a2d4b-b838-488e-90a8-7fe48a96e4c7)

### Field sizes

After adding the info icon, the fields became uneven in size and it looks weird.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9a46bfd1-d447-431f-97c5-4cb663c1b150)

### VM image, Flist. entrypoint fields

Nothing was added to these fields.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/57c45dca-a64f-4f3e-b7b4-22fa43560b0e)

### Environment Variables

When you hover over the tooltip next to the `SSH_Key` field it doesn't show anything since it's disabled with the field.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ebc93b12-0642-4f1c-a389-f36b24b798e8)

More info needs to be added here since the description doesn't clarify anything.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5b0d097d-c113-4229-8cb8-ca5a908d8f31)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4799b211-559e-4d25-bcd9-38b02fa0de84)

### Gateway Node

Nothing was added to this field.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/43740baf-a2c8-4b42-8b43-88cc3096af16)

### Presearch

The added info is the same thing written in the placeholder text.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7c9104a9-4b95-403f-90b4-2200dc3a25d8)

> For the restore key it should be treated like the smtp option in other deployments since it's not required. (With a toggle button to activate it if needed) and the info should be above both fields mentioning that this option is not required and should only be used in case of restoring old instances.

The mentioned option to toggle these fields wasn't added and more info about restoring instances needs to be added.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a39060ff-11e1-41a3-98da-3253c359868d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cfc9fb5e-7264-4ef3-9f7a-8aa729b67f58)

### Subsquid

Same  as the placeholder text. needs more info
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/940ab3fd-d3c2-4d74-a39a-e5726c3ebb35)


### Algorand

Nothing was added to the mentioned fields.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1729bcef-f8ae-41a7-903e-5ccdec42807d)

**Comment by Mahmoud-Emad** [comment]
For the issue of unclear messages, I kindly request that you provide me with specific examples of messages that you find clear and easy to understand.

**Comment by khaledyoussef24** [comment]
verified on devnet:
network:
wireguard:
![Screenshot from 2023-06-20 15-21-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c83ea204-df66-4690-b4cd-763551281a6b)
planetary:
![Screenshot from 2023-06-20 15-21-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9001ab13-de9e-4fce-989b-7a1a49e89c98)
ipv6:
![Screenshot from 2023-06-20 15-21-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2aca2a11-7680-4229-81ab-ba1ce1723bf0)
ipv4:
![Screenshot from 2023-06-20 15-20-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/84366f12-63c0-4ec6-8f8b-ea0b436531a2)

flist:
![Screenshot from 2023-06-20 15-24-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/139faa14-2880-4da4-8bf8-98876e44a9db)
k8s cluster:
![Screenshot from 2023-06-20 15-25-10](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9d2df983-a69b-434c-9b82-ecfbcc9bc6e7)
environment variables:
![Screenshot from 2023-06-20 15-23-42](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/2ac4210f-fd95-41ed-8593-6e7efe67b92c)

**Comment by khaledyoussef24** [comment]
verified on devnet
