### ISSUE TITLE
Configure the timeout in the dashboard

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3169]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

In case the dashboard fails to load deployments as the network is slow, there is no way to change the timeout

### Describe the solution you'd like

The user should be able to configure the timeout he wants. This timeout should be stored in the user's metadata. and if it's not found fall back to the timeout configured in the config file.

**Comment by 0oM4R** [comment]
**Suggestion**: introduce a new `Setting` page that contains a timeout field, change password, dark/light mode.

**Comment by amiraabouhadid** [comment]
@ehab-hassan can we please have a design for the settings page?

**Comment by ehab-hassan** [comment]
@amiraabouhadid check this

https://www.figma.com/proto/7f7OANwfyTHQxtoP80D4rp/Untitled?node-id=1-16&t=eh8DWQe0dYbd8oMq-0&scaling=scale-down&content-scaling=fixed&page-id=0%3A1

**Comment by ehab-hassan** [comment]
updated
![Frame 386](https://github.com/user-attachments/assets/1699dd79-73a1-45e6-859c-9f96f8af5d02)
https://www.figma.com/proto/7f7OANwfyTHQxtoP80D4rp/Untitled?node-id=9-228&t=eh8DWQe0dYbd8oMq-0&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1

**Comment by amiraabouhadid** [comment]
added update theme card and settings page

**Comment by amiraabouhadid** [comment]
blocked on #3341

**Comment by khaledyoussef24** [comment]
verfied on devnet
Version fccc6af

settings page is now available 
![Image](https://github.com/user-attachments/assets/3cc861c5-6b61-4324-9cf4-1d431b6b0fa4)
![Image](https://github.com/user-attachments/assets/9745d230-9b90-4572-9ea9-0c6fe3d1d9d7)


[testsuite](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=454504#suite_section_454504)

**Comment by xmonader** [comment]
The behaviour of the timeout should be verified

**Comment by khaledyoussef24** [comment]
Tried with a throttled connection and increased time out and it works.

Do you recommend a specific test that could be more reliable?
@xmonader

**Comment by xmonader** [comment]
> Tried with a throttled connection and increased time out and it works.
> 
> Do you recommend a specific test that could be more reliable? @xmonader

I didn't see that in your verification steps

**Comment by khaledyoussef24** [comment]
> > Tried with a throttled connection and increased time out and it works.
> > Do you recommend a specific test that could be more reliable? [@xmonader](https://github.com/xmonader)
> 
> I didn't see that in your verification steps

okay will add steps and searching for a scenario doing the opposite to watch it fail due to time out

**Comment by khaledyoussef24** [comment]
okay I tried to produce a Pessimistic Scenario but still did not work out 
made the time out to 3 seconds and made the connection to 3g but still everything is working fine which is weird.
![Image](https://github.com/user-attachments/assets/9351413e-f90d-455c-8120-ba7d116bb858)
![Image](https://github.com/user-attachments/assets/d5a3ecb5-6974-45f8-898a-f420f2c36828)


can we also write in the validation the max amount which is 180 and 1800 instead of the max limit exceeded
as we wrote the minimum is 3 
![Image](https://github.com/user-attachments/assets/62d33294-00b8-4e33-9fdf-cf0a9762870e)
![Image](https://github.com/user-attachments/assets/fdf1f7f8-6f7d-48ca-9b62-62048f4c4d50)


and can we also add a button for default values reset

**Comment by amiraabouhadid** [comment]
@khaledyoussef24 will not be adding reset button at the moment, please open feature request 
updated validation error messages to include the max timeout in seconds

**Comment by khaledyoussef24** [comment]
verified on devnet
Version ffbb750

max time out validation is now added
![Image](https://github.com/user-attachments/assets/99be1a8e-9d32-4a95-bb42-e02709a234e0)

after setting the time out ti 3 seconds and tried to verify deploying in this time worked fine and functional
![Image](https://github.com/user-attachments/assets/3b74f457-0696-4cab-b5fb-8d12e2441c14)
![Image](https://github.com/user-attachments/assets/561c8c93-572b-4f0f-bdac-f12812c65e5d)
![Image](https://github.com/user-attachments/assets/3cc866d1-f69f-4d80-986f-eae51370346f)
after resetting it it deployed fine
![Image](https://github.com/user-attachments/assets/e2ac94a2-9b05-4012-a425-6ca79168d934)


testcase coveing validation
[test1](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=454504#case_4410309)
[test2](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=454504#case_4410317)

timeout function 
[test1](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=454504#case_4410321)
[test2](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=454504#case_4410322)
