### ISSUE TITLE
Add a clearer error message if the mnemonic doesn't belong to a registered twin on the grid

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#317]
### Description

A clearer error message should be added when the mnemonic is not registered to a twin on a certain network. for example i added the mnemonic of my mainnet twin and it's not registered on devnet and it returned the following error message.

```
Failed to load grid for this user.
```
which doesn't clarify anything for the user or what the error might be.

![image](https://github.com/threefoldtech/playground/assets/101194226/0fc4e805-adc5-41ee-b794-2d0b6c68fa0d)

**Comment by Mahmoud-Emad** [comment]
It appears that this was a duplicate issue of [this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/321), and the fix implemented in [this pull request](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/368) has resolved it.

**Comment by A-Harby** [comment]
Close the issue as duplicate
