### ISSUE TITLE
Expose solution

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3178]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

a user might have a server running on a local machine or vm on the grid and this machine has Mycelium IP or Yggdrasil and would like to expose this server to the public network.

### Describe the solution you'd like

The user can use the grid gateways to expose his server on a domain by using his machine IP or the vm IP (can be Mycelium IP, Yggdrasil IP, or public IP (v4 or v6))

The solution should ask for the gateway node, a subdomain, the IP, and the port.

**Comment by maayarosama** [comment]
@ehab-hassan Please provide an icon for this solution

**Comment by maayarosama** [comment]
Issue Update Format

1. Work Completed:
Added the expose solution to the dashboard
2. Work in Progress (WIP):
- waiting on expose icon
- adding docs to the manual
- adding validation to the ip field

**Comment by ehab-hassan** [comment]
> @ehab-hassan Please provide an icon for this solution

![expose1](https://github.com/user-attachments/assets/fae7c7c0-51f7-40a9-a74b-815461a908ac)
![expose2](https://github.com/user-attachments/assets/f33cca66-a888-4545-9416-905a02cbcfa6)

I like option2

**Comment by maayarosama** [comment]
1. Work Completed:

- added expose icon
- added docs to the manual
- added validation to the ip field

**Comment by maayarosama** [comment]
Issue Update Format

- Work Completed:
Removed deploying vm
-  Investigation and Solution:
I get an error while deploying , still investigating

![Screenshot from 2024-08-12 22-06-07](https://github.com/user-attachments/assets/02df2a1f-5d11-44ca-810e-10442986c24a)

**Comment by AhmedHanafy725** [comment]
> ![Screenshot from 2024-08-12 22-06-07](https://private-user-images.githubusercontent.com/66883096/357171443-02df2a1f-5d11-44ca-810e-10442986c24a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTAwOTcsIm5iZiI6MTcyMzQ4OTc5NywicGF0aCI6Ii82Njg4MzA5Ni8zNTcxNzE0NDMtMDJkZjJhMWYtNWQxMS00NGNhLTgxMGUtMTA0NDI5ODZjMjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE5MDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NTE5MDU5ZWIxOTEwOTFiN2Y3ZjczOTNhNTg1ZTQwOThmNjJkZDc5MmZhY2YwNDY4NjY3YWI1NmU1ZWE2YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IBIuBL5ba8Ibpr-9Vz8dwwe_N6ThUnGdwzMAqPOCzHE)

This means that you are trying to deploy a gateway workload and using a network's name doesn't exist (you didn't deploy it and you don't need it). This network field on the gateway workload is only used for  wireguard network

**Comment by maayarosama** [comment]
- Work Completed:
Fixed dialoge feature with domain
- Investigation and Solution:
Deployment list doesn't work probably as there's no projectNae added to the gateway contract

**Comment by maayarosama** [comment]
### Work Completed:
- Fixed dialogue feature on row-click
- Fixed rollbackGateway
- Fixed deleting domain instances

**Comment by A-Harby** [comment]
Devnet, 99b5130.

It worked on all networks except for IPv6, it gives me an error not found.

![image](https://github.com/user-attachments/assets/17aa33a8-83df-433c-b3df-2e9d1d7d7d12)

![image](https://github.com/user-attachments/assets/32eb5fa6-151d-4b98-8968-08fb34d47fd2)

its missing the `http://`, could be the error.

**Comment by A-Harby** [comment]
Also, using wireguard is not supported; its deployment is different than the other networks.

![image](https://github.com/user-attachments/assets/be0747eb-4298-4be3-ba94-32355d2a63f5)

**Comment by A-Harby** [comment]
Last thing what does the health mean?
![image](https://github.com/user-attachments/assets/c3c50087-90b2-4fd5-8f75-2136d93fb138)

Because it shows ok in either way the domain is up or down.

**Comment by maayarosama** [comment]
> Also, using wireguard is not supported; its deployment is different than the other networks.
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/363727808-be0747eb-4298-4be3-ba94-32355d2a63f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAxOTgsIm5iZiI6MTcyNTM1OTg5OCwicGF0aCI6Ii8xMDk0NzM4NzMvMzYzNzI3ODA4LWJlMDc0N2ViLTQyOTgtNGJlMy1iYTk0LTMyMzU1ZDJhNjNmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMDM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yN2E3ZTlhZTU5MGVkM2Y4NjdiZjgyMDJhYWI0NmM5Y2ZjMmYzY2Q1MGZlMWNmZjY1YmQ5NjUxZDlmMDQ4MjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ltEgWvOT2Pe59bfUlsTxnG55G98PMH48fzeq6CASow0)

Wiregaurd is indeed not supported

**Comment by maayarosama** [comment]
> Devnet, [99b5130](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/99b5130e1c1f3a502f9de6160545b8a82a4c43c5).
> 
> It worked on all networks except for IPv6, it gives me an error not found.
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/363724908-17aa33a8-83df-433c-b3df-2e9d1d7d7d12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAxOTgsIm5iZiI6MTcyNTM1OTg5OCwicGF0aCI6Ii8xMDk0NzM4NzMvMzYzNzI0OTA4LTE3YWEzM2E4LTgzZGYtNDMzYy1iM2RmLTJlOWQxZDdkN2QxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMDM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzYyMzk1ZmM4YjU0N2E2YTc4MTU2OTk2MDJmOTdhNWQ0NjdlZjc1ZmU0ZTllNmYzN2Y0Zjk1ZmUxYjgxOGMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KMj3mDAqpeXH7gmL7-dGJqtMt_8hDJyCt233MsErRkk)
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/363725385-32eb5fa6-151d-4b98-8968-08fb34d47fd2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjAxOTgsIm5iZiI6MTcyNTM1OTg5OCwicGF0aCI6Ii8xMDk0NzM4NzMvMzYzNzI1Mzg1LTMyZWI1ZmE2LTE1MWQtNGI5OC04OTY4LTA4ZmIzNGQ0N2ZkMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMDM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzBmMzc4NGIzOWJiZTUzMjlkNTBmOTU3YTllNjIzN2RlZmZkYjA1YTNjMDA2ODJiYWU3YThlZDE0OWQ0ZTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jl1AtUEH5vKuYh82s-Wmj5Zcphw4Q1KOgmpUi99ibJI)
> 
> its missing the `http://`, could be the error.

I think the ipv6 you provided isn't a valid ip, Please try it again because I tried and ipv6 works just fine
![Screenshot from 2024-09-03 14-02-31](https://github.com/user-attachments/assets/7e7ca075-98d2-4bac-97e1-2bc8ee83d406)
![Screenshot from 2024-09-03 14-03-05](https://github.com/user-attachments/assets/dc7488e0-3089-4057-8441-9ee0374d5e4d)

**Comment by A-Harby** [comment]
> I think the ipv6 you provided isn't a valid ip, Please try it again because I tried and ipv6 works just fine ![Screenshot from 2024-09-03 14-02-31](https://private-user-images.githubusercontent.com/66883096/363956555-7e7ca075-98d2-4bac-97e1-2bc8ee83d406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjE3MzQsIm5iZiI6MTcyNTM2MTQzNCwicGF0aCI6Ii82Njg4MzA5Ni8zNjM5NTY1NTUtN2U3Y2EwNzUtOThkMi00YmFjLTk3ZTEtMmJjOGVlODNkNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNjFlYmI5NjM2ZDBmZjc4ZTYwNDRlNzhlYTQyZThlZTNlOThhMzI4NDNiMTJkMGQ1ODM4OTA3MjU5ZDVhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfEnz82svUxBXnpIsCAG9ASaSfPL-lh3iFdqqGUJAac) ![Screenshot from 2024-09-03 14-03-05](https://private-user-images.githubusercontent.com/66883096/363956559-dc7488e0-3089-4057-8441-9ee0374d5e4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjE3MzQsIm5iZiI6MTcyNTM2MTQzNCwicGF0aCI6Ii82Njg4MzA5Ni8zNjM5NTY1NTktZGM3NDg4ZTAtMzA4OS00MDU3LTg0NDEtOWVlMDM3NGQ1ZTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjY5Y2NkYzFlNGE4ODVhY2NiN2E4ZDkxNTc4NTAwMWZlYTg1NDgzMmM2MmZmMzg2YTIzNzE3YjcyMjQxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqc4M04PNkVQmrhD51WwPBNL9altLxTvqTYIpJyfsbE)



True, it wasn't with the IPv6 but rather with the tls passthrough option; if you turn it on, the domain will not work.

![image](https://github.com/user-attachments/assets/9081dedb-10b6-4608-91ed-fe98efc7dd47)

Also chip should be green and red, and in some deployment table is called status.
![image](https://github.com/user-attachments/assets/88e3424e-573e-4402-9f70-137e9c06147c)

**Comment by maayarosama** [comment]
> > I think the ipv6 you provided isn't a valid ip, Please try it again because I tried and ipv6 works just fine ![Screenshot from 2024-09-03 14-02-31](https://private-user-images.githubusercontent.com/66883096/363956555-7e7ca075-98d2-4bac-97e1-2bc8ee83d406.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjE3MzQsIm5iZiI6MTcyNTM2MTQzNCwicGF0aCI6Ii82Njg4MzA5Ni8zNjM5NTY1NTUtN2U3Y2EwNzUtOThkMi00YmFjLTk3ZTEtMmJjOGVlODNkNDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNjFlYmI5NjM2ZDBmZjc4ZTYwNDRlNzhlYTQyZThlZTNlOThhMzI4NDNiMTJkMGQ1ODM4OTA3MjU5ZDVhYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WfEnz82svUxBXnpIsCAG9ASaSfPL-lh3iFdqqGUJAac) ![Screenshot from 2024-09-03 14-03-05](https://private-user-images.githubusercontent.com/66883096/363956559-dc7488e0-3089-4057-8441-9ee0374d5e4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjE3MzQsIm5iZiI6MTcyNTM2MTQzNCwicGF0aCI6Ii82Njg4MzA5Ni8zNjM5NTY1NTktZGM3NDg4ZTAtMzA4OS00MDU3LTg0NDEtOWVlMDM3NGQ1ZTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDExMDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZjY5Y2NkYzFlNGE4ODVhY2NiN2E4ZDkxNTc4NTAwMWZlYTg1NDgzMmM2MmZmMzg2YTIzNzE3YjcyMjQxNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qqc4M04PNkVQmrhD51WwPBNL9altLxTvqTYIpJyfsbE)
> 
> 
> 
> 
> 
> 
> 
> True, it wasn't with the IPv6 but rather with the tls passthrough option; if you turn it on, the domain will not work.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/9081dedb-10b6-4608-91ed-fe98efc7dd47)
> 
> 
> 
> Also chip should be green and red, and in some deployment table is called status.
> 
> ![image](https://github.com/user-attachments/assets/88e3424e-573e-4402-9f70-137e9c06147c)
> 
> 

If the server doesn't have a certificate and you enable the tls passthrough it will never work

**Comment by A-Harby** [comment]
Verified, Devnet a948bfa.

The domain is now working fine with all network interfaces except for Wiregurad and with the TLS option on/off.

![image](https://github.com/user-attachments/assets/a731c34b-2d86-4c63-af00-00e22c1e60dc)
![image](https://github.com/user-attachments/assets/02884b77-4006-4b54-82b2-00090726ffc3)

And health chip is fixed.
![image](https://github.com/user-attachments/assets/f5ea130e-e685-447d-abea-9307d0e11501)

Test case: [TC2827 - Deploy Domain](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4364216)

**Comment by amiraabouhadid** [comment]
test scenarios:
- write better test case descriptions
- details details details pwease @khaledyoussef24 
- test on local deployment (mentioned above) 

issues:
- update subdomain tooltip to include an example, clearer text 
- tooltips typos
- TLS switch looks clickable in deployment details dialog <- move to deployment details dialog
