### ISSUE TITLE
Add animation for what's new in version

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3179]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

For example, we have a lot of solutions but nothing to say that there is a new solution or any other features added we would like to show it to the user.

### Describe the solution you'd like

Adding animation to guide the user to the newly added main features on the release would be nice

**Comment by 0oM4R** [comment]
**Suggestion**: hide after click on the new solution 
hit for search : CSS : sudo class dirty

**Comment by samaradel** [comment]
### Work in Progress (WIP):
chips are added and working on the logic of displaying it

**Comment by samaradel** [comment]
### Work in Progress (WIP):
investigating how to save solutions appearance in kvstore

**Comment by samaradel** [comment]
### Work Completed:
Add chip with New for new applications and will expire after 1 month.

P.S. PR is drafted till we get the animated image from @ehab-hassan

**Comment by ehab-hassan** [comment]
I added like this @samaradel I need ur help to apply at just the new App not all

![new_APP](https://github.com/user-attachments/assets/472edf6a-c6c9-42f9-a8eb-02db04bed23b)

**Comment by samaradel** [comment]
@ehab-hassan updated only for the new app/version, thanks

![Image](https://github.com/user-attachments/assets/fac91cb0-195a-4812-bf72-23a41b9e99bc)

**Comment by A-Harby** [comment]
Waiting for https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3448 to verify.

**Comment by 0oM4R** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3493#issuecomment-2388500470
looks like there is an issue with responsive will move it to accepted

**Comment by samaradel** [comment]
> [#3493 (comment)](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3493#issuecomment-2388500470) looks like there is an issue with responsive will move it to accepted

@ehab-hassan please check

**Comment by ehab-hassan** [comment]
fixed @ #3511

**Comment by A-Harby** [comment]
Verified, https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3448#issuecomment-2413166331.
