### ISSUE TITLE
No clear instructions what to do with id_rsa

### ISSUE THREAD

**Issue by amr-yassir** [threefoldtech/tfgrid-sdk-ts#3180]
### What happened?

While deploying the VM it wasn't clear as a user what to do with the id_rsa key.

Steps I followed to solve the issue:
   moved the id_rsa to ~/.ssh
   run `chmod 0600 ~/.ssh/id_rsa`

### What did you expect?

Expected a clear usage of how to deploy and access the VM

**Comment by 0oM4R** [comment]
**Suggestion**: After generating a ssh key from dashboard, open dialog and show how to use the downloaded file
