### ISSUE TITLE
[Mainnet] [Bug 🐞]: Nodes for the Netherlands on the Dashboard world map display a count of zero.

### ISSUE THREAD

**Issue by mahendravarmayadala93** [threefoldtech/tfgrid-sdk-ts#3181]
### What happened?

Robert, one of our clients, noticed that the Nodes for the Netherlands on the world map in the Dashboard's Node Statistics tab displayed zero.

<img width="928" alt="image" src="https://github.com/user-attachments/assets/772f8766-96d8-4ba4-8ee6-185fd98c4dae">

The Data in Grid Proxy at https://gridproxy.grid.tf/stats?status=up lists the name as **The Netherlands** with over 270 nodes. However, when filtering nodes by the name **Netherlands** on the Dashboard, nearly all nodes appear as down. 

_Scott suspects that this discrepancy may be due to differences in naming, causing the node count not to properly map to the country._

### What did you expect?

To see the exact number of Nodes with the correct name.

### What browsers are you seeing the problem on?

Chrome

### ZOS info

NA

### Dashboard info

https://dashboard.grid.tf/#/tf-grid/node-statistics/

### weblets info

NA

### Relevant log output

```shell
NA
```

**Comment by 0oM4R** [comment]
**Hint**: check the country name on the response

**Comment by maayarosama** [comment]
### Work in Progress (WIP):
No updates as I got distracted with work in test-tracker with the interns

Investigation and Solution:
- Checking the countries names in the response match the  countries names in the map

**Comment by maayarosama** [comment]
Work Completed:
- Fixed the mismatch between country names

**Comment by RoberL72** [comment]
![afbeelding](https://github.com/user-attachments/assets/4239ecb2-c9f5-4f01-a6e0-e0c97f4ffa26)

The country also does not show up anymore in the list with locations when deploying...

**Comment by AhmedHanafy725** [comment]
#3021

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3021
