### ISSUE TITLE
🐞 [Bug]: The Most Applications don't have a Wireguard Network option

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

-  The most applications don't have a Wireguard Network option.

### which network/s did you face the problem on?

Dev

### version

ac03039

### Relevant screenshots/screen records

![no_wireguard](https://github.com/user-attachments/assets/fd36e383-077a-4a1d-9603-1341066fec50)

![with_wireguard](https://github.com/user-attachments/assets/90b37974-d349-4b0d-b669-2aac43b6fb3b)

### Relevant log output

```console
n/a
```

**Comment by Mahmoud-Emad** [comment]
## Issue update 

### Changes

- Enabled the Public IPv4 and displayed it as a 'read-only' field
- Send the value of the 'Wireguard' option to the deployment
- Updated the return of the 'createWorker' function to be ready to accept all networks
- Updated the worker interface to accept all networks

- Infrared the type of the name in the validator to avoid typescript errors
- Send the value of the 'Wireguard' to the deployment
- Enable Mycelium option by default
- Added the Wireguard option to the K8S deployment

- Added a watcher into all solutions that require a domain to be deployed to watch on the custom domain value then updated the Wireguard option
- Added a new attr 'read-only' in the 'Networks' component to set the 'Wireguard' option as 'read-only'
- Update the opacity of the 'Wireguard Switch' in the 'Networks' component
- Updated all applications with the new requirement and tested the full workflow

#### Proposal

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3294

**Comment by Mahmoud-Emad** [comment]
- Established a new constant by computing the options for IPv4 and custom domains to decide whether the Wireguard option should be read-only or not.
- Monitored the 'isWireguardReadonly' constant to determine the value of the Wireguard feature based on it.

**Comment by A-Harby** [comment]
Verified, Devnet 99b5130.

The wiregurad option is added to all of the solutions: VMs, Orchestrators and Applcations.
 
![image](https://github.com/user-attachments/assets/dc72f5b0-609f-496a-ace0-2bf378d8bdbb)
![image](https://github.com/user-attachments/assets/94362395-fe1e-4002-9e4c-e4f0975c2816)
![image](https://github.com/user-attachments/assets/228fd978-fed4-4b9c-b2c7-8f38f29c25f2)
![image](https://github.com/user-attachments/assets/83019057-9943-482c-ac55-c6dc8e29279b)
