### ISSUE TITLE
Public SSH Key Validation is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#320]
### Description

Public SSH Key Validation is not working and it can be updated with any value.

### Adding a new ssh key with an invalid value

[Untitled_ May 14, 2023 3_45 PM.webm](https://github.com/threefoldtech/playground/assets/101194226/7d72d7e3-9af7-41a5-bbaf-c572c0e106e9)

### Updating and already existing key with an invalid value.

[Untitled_ May 14, 2023 3_40 PM.webm](https://github.com/threefoldtech/playground/assets/101194226/06f5cbb4-67e2-4385-a672-fd78d3da8a3a)

**Comment by 0oM4R** [comment]
PR #455 ready for review

**Comment by 0oM4R** [comment]
after some discussions, will make sure the user provides a ssh key, if no the user will not be able to complete the deployment.
whoever the pr now is ready for  review :D
