### ISSUE TITLE
(Mainnet verification) Error when voting on DAO🐞 [Bug]: 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#3202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Got error 'vote failed' when trying to vote on a DAO proposal. The vote did went through tho. Multiple farmers have shared that the same thing happened to them. 

My nodes on the farm are active so that's not the problem

### Steps To Reproduce

1. dashboard.grid.tf (mainnet)
2. TFChain
3. DAO
4. Vote
5. Error: 'Vote Failed!' but did go through after checking tfchain

### which network/s did you face the problem on?

Main

### version

3.14

### Twin ID/s

785

### Node ID/s

6344, 4245, 6357

### Farm ID/s

452

### Relevant screenshots/screen records

![photo_2024-08-02 10 25 57](https://github.com/user-attachments/assets/82963683-40c5-4b09-bd48-9a0872f7810d)

### Relevant log output

```console
-
```

**Comment by 0oM4R** [comment]
Issue status: It is not clear what is the error here, will give it **2 hours** to investigate.

**Comment by 0oM4R** [comment]
Issue Status: the same happens to me if i vote on the same dao twice, 


solution: will handle this error and show new error msg, also if the eror not related to the duplicate vote, we will log the error,
will take about **1 hour**

**Comment by 0oM4R** [comment]
Issue status: 
work completed
- add log line in side the error handling to make it clear what exactly happens.
- handle the duplicate vote error, and clarify the toast message with it

**Comment by A-Harby** [comment]
It's working fine on Devnet, 448a213.
![image](https://github.com/user-attachments/assets/fa22b082-a9b5-4245-a01f-ca7045ab4ed5)
