### ISSUE TITLE
Support node in graphql/gridproxy client

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#3209]
### Which package/s are you suggesting this feature for?

graphql_client

### Is your feature request related to a problem? Please describe

yes when importing graphql_client in node (commonjs module) it throws an error

```
/...path/@threefold/graphql_client/dist/index.js:1
export * from "./types";
^^^^^^

SyntaxError: Unexpected token 'export'
```

### Describe the solution you'd like

Support node in graphql client

**Comment by AhmedHanafy725** [comment]
should be tested after the release

**Comment by A-Harby** [comment]
@AhmedHanafy725 Is that deployed yet?

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 Is that deployed yet?

yes

**Comment by A-Harby** [comment]
I tried and still got the same error!

![image](https://github.com/user-attachments/assets/d4465099-2cf0-44f2-98ec-5ca8642b0c30)

`"dependencies": {
    "@threefold/graphql_client": "^2.5.2",`

**Comment by AhmedHanafy725** [comment]
can you try the edge version? `2.6.0-rc3`

**Comment by A-Harby** [comment]
> can you try the edge version? `2.6.0-rc3`

For graphql or grid_client package?

**Comment by AhmedHanafy725** [comment]
> > can you try the edge version? `2.6.0-rc3`
> 
> For graphql or grid_client package?

both should work

**Comment by A-Harby** [comment]
> > > can you try the edge version? `2.6.0-rc3`
> > 
> > 
> > For graphql or grid_client package?
> 
> both should work

Verified.

I had client on grid client on version `2.6.0-rc3`, but used old for graphql, but after updating it and running the script again, it worked fine.

![image](https://github.com/user-attachments/assets/66d9a23d-3d40-4b12-b505-891b0f1a975f)

[Grid Client NPM Package](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=455924#suite_section_455924)
