### ISSUE TITLE
Error reporting should be improved for mnemonic validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#321]
### Description

Error reporting should be improved for mnemonic validation. I got the following error when i added the mnemonic of one of my twins on devnet that wasn't updated to use the relay yet and when i added its mnemonic i got the following error.

```
Failed to load grid for this user.
```

```
RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low

DRR: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance 

RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
```

![image](https://github.com/threefoldtech/playground/assets/101194226/fa69227f-99bd-419d-82ca-c310e29f841c)

The error message is unclear and it doesn't describe where the issue is or what is the reason for not being to load this twin. i tried the same mnemonic in the old weblets and it returned a clearer error message.

```
Unable to establish a connection with the RMB server. Please check your internet connection and try again. If the problem persists, please contact our support.
```

![image](https://github.com/threefoldtech/playground/assets/101194226/d22e0cab-e6f3-4aa7-b181-4d9bea08ea62)

However it still didn't mention that the twin should be updated with the relay.

**Comment by A-Harby** [comment]
Error message is still the same

Mnemonics of other chain.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/70ee54d0-26c4-493a-b061-d6932a2e586b)
Newly created twin on devnet but havn't updated the relay yet. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9ef884df-0024-433f-871a-d58a2f454129)

**Comment by A-Harby** [comment]
Error is removed and only shown in the console
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cb7d275b-fafe-47ad-b3d4-82fb62e78bb8)

**Comment by A-Harby** [comment]
Verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8dca23bb-241f-4b6a-abf1-75a38b6ca66d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d4d5b1a4-f401-45f7-8a85-029963bc0423)
