### ISSUE TITLE
Add volume unit tests

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3219]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

-

**Comment by A-Harby** [comment]
Verified Devnet,
Tests are added here: https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/tests/modules/volume.test.ts.

And they are passing on the last run today: https://github.com/threefoldtech/tfgrid-sdk-ts/runs/28630019958
![image](https://github.com/user-attachments/assets/75ba5088-b797-459f-9937-10425874758b)
