### ISSUE TITLE
🐞 [Bug]: Dashboard Deployment Table Shows Incorrect time format

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Dashboard Deployment Table Shows Incorrect time format

### Steps To Reproduce

1. Deploy a node
2. if it's a 1 digit minute (e.g. 0 to 9) it shows the format e.g. 1:1, instead of 1:01, etc.

### which network/s did you face the problem on?

Main

### version

latest

### Node ID/s

6071

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/2020df8a-313c-46cd-bd2b-3650960a963e)

### Relevant log output

```console
8/5/24, 9:1 PM
```

**Comment by Mahmoud-Emad** [comment]
Hello @Mik-TF 

I tried the mentioned scenario and seems working as expected on the [staging server](https://staging.dashboard.dev.grid.tf/), please note, the staging server running against Devnet

![image](https://github.com/user-attachments/assets/3ca66a28-5535-4e99-9e8a-b8e024ead92b)

**Comment by mik-tf** [comment]
I wonder if it's something that happens only with e.g. 10:01 --> 10:1

If it worked on your side, all's good. Thanks.

**Comment by A-Harby** [comment]
> I wonder if it's something that happens only with e.g. 10:01 --> 10:1
> 
> If it worked on your side, all's good. Thanks.

It was an UI issue, and it was reported and fixed here: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2751.

But its on 3.15, so its not released yet.
