### ISSUE TITLE
🐞 [Bug]: Manage domains dialog validation error 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When opened the Manage Domains dialog to attach a domain name to my machine I got `Subdomain should consist of lowercase letters only.` without touching anything.

### Steps To Reproduce

1. Go to the [Staging Dashboard](https://staging.dashboard.dev.grid.tf/)
2. Go to [Deploy Micro Virtual Machine](https://staging.dashboard.dev.grid.tf/deploy/virtual-machines/micro-virtual-machine/) page
3. Deploy a new machine
4. open the Manage Domains dialog

### which network/s did you face the problem on?

Dev

### version

967b554

### Twin ID/s

143

### Relevant screenshots/screen records

[Screencast from 08-06-2024 11:34:07 AM.webm](https://github.com/user-attachments/assets/56f5a74a-667a-47bd-b960-c6420d4f9818)

### Relevant log output

```console
N/A
```

**Comment by A-Harby** [comment]
Verified, Devnet e00cb4c.

The validation are now corrected and working fine.
![image](https://github.com/user-attachments/assets/6db44133-667d-43e6-ba10-0238a65bf09e)
![image](https://github.com/user-attachments/assets/ac14bb62-4988-4fdd-9de9-e0d95dde6d27)
![image](https://github.com/user-attachments/assets/a2e62181-3f93-4e64-accd-c63c6738ef18)
![image](https://github.com/user-attachments/assets/f8a3dfb3-8e07-4a83-b913-5722bc962654)
![image](https://github.com/user-attachments/assets/ae2a9e1e-1fc1-4899-bbb3-49b3beefa22b)
![image](https://github.com/user-attachments/assets/1e0c6a12-d0d0-40a4-9ee4-c7f9f5d9768f)

[TC2124 - Add gateway to a vm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150333)
