### ISSUE TITLE
🐞 [Bug]: Mail Server is enabled without IPv4 in Gitea

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Try to deploy a Gitea instance with a mail server and don't enable IPv4. It would work.

### which network/s did you face the problem on?

Dev

### version

beafeda

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
Work completed:

Watched the smtp value to enable the IPv4 if it is true and vice versa. I also, added smtp env vars to machines while deploying. However, the image needs to be updated to link mailer configs correctly. Opened an [issue](https://github.com/threefoldtech/tf-images/issues/283) for it.

**Comment by khaledyoussef24** [comment]
verified on devnet
version : a542a73

after enabling smtp server the public ip is enabled automatic


![Image](https://github.com/user-attachments/assets/4936b3ae-8f90-4b6f-aef6-030e5ac2414b)
![Image](https://github.com/user-attachments/assets/76f6e2d8-bf10-4f6d-a9ee-57c0fe360569)
![Image](https://github.com/user-attachments/assets/cb5b2bd9-4158-448b-913c-a9d745758e2c)
![Image](https://github.com/user-attachments/assets/63f7bca9-3f89-4a1c-85a7-a574a05aed04)

[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4346827)
