### ISSUE TITLE
🐞 [Bug]: DAO vote isn't applied after voting

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After voting on the DAO page, the vote is cast and added to the chain, but it's reflected on the page even after waiting for a few minutes.

You have to reload the page to view the new vote parentage.

### which network/s did you face the problem on?

Dev

### version

c609551

### Relevant screenshots/screen records

[screen-capture.webm](https://github.com/user-attachments/assets/fd317e23-0c97-4301-97ae-09374982608c)

[screen-capture (1).webm](https://github.com/user-attachments/assets/65321cf7-19e3-4525-a4ae-8622e89abdb1)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Investigation and Solution:
investigation about Dao's page

**Comment by samaradel** [comment]
### Work in Progress (WIP):
it takes 20sec to reflect on the page .. working on making it take less time

**Comment by samaradel** [comment]
### Work in Progress (WIP):
missunderstanding some concepts in ```tf-chain``` working on it

**Comment by samaradel** [comment]
### Work Completed:
Update only the voted DAO proposal as it took a long time to update the page and the vote appeared after refresh.

**Comment by A-Harby** [comment]
Verified, Devnet 8fda273.

The vote is now reflected instantly after voting.

[screen-capture (8).webm](https://github.com/user-attachments/assets/dc772d6e-3c5b-4f11-9a17-27da9c63e61e)
