### ISSUE TITLE
Sorting is broken in multiple tables

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#324]
### Description

Sorting is broken in multiple tables.

### Deployment List

The sorting is completely broken in this table. and sorting should be removed from the `Actions` column.

[TF Playground _ Full Virtual Machine.webm](https://github.com/threefoldtech/playground/assets/101194226/dd99828d-cc45-4e86-9d10-0813daf13d7b)

### Deployments Tab

Same thing in the deployments tab. and sorting should be removed from the `Actions` column.

[TF Playground _ Deployment List.webm](https://github.com/threefoldtech/playground/assets/101194226/452691f7-b299-413a-b8e9-fdcb30941134)

### Contracts List

Only the the number/`#` sorting is broken and i'm not sure about the `State` and `Expiration` since i didn't have contracts in grace period.

[TF Playground _ Contracts List.webm](https://github.com/threefoldtech/playground/assets/101194226/28ab1d2a-bab3-4f05-a790-e3228b7b52a8)

**Comment by 0oM4R** [comment]
__Update__: can't fix it yet, will check with Rabie

**Comment by MohamedElmdary** [comment]
This issue might be caused because vuetify looking at passed data as [IDs] not [Objects] so we might need to pass a custom sorting function

More info here
https://vuetifyjs.com/en/components/data-tables/sorting/#basic-sorting

**Comment by mohamedamer453** [comment]
Work Completed:

- The contracts table is now working fine so nothing needed to be done with it.
- For the deployment list i was able to disable the sorting for the actions column and i'm still trying different solutions for the broken sorting itself.

Work in Progress (WIP):
- Still trying to find the appropriate solution for fixing the broken sorting, tried to follow the same method that was provided by vuetify for their [example](https://play.vuetifyjs.com/#eNqtll1v2jAUhv/KUaSKViqfAVoihrTRfXTdxW6n0guTHKhVE0e2YWOI/75jEgIEjEbU3MQ+x695zuuP8LzytArrH5OktpijF3h9g7NEMIODUQzQX1QjZljVsLFAGwBYVGcyQhFoqUx1vPww8mzr03LkpfngFVmESlMia+UZTnPbeIRaozJ5IhRM2zgKXDDDZVxtpqlBv74PsEUKCSAXzUy1PfI2KUomCgerFaRIsF736zay0dFUVkidfn2vSOrqUPHEbEbhn4SkEOGEzYWBVTqtRbi+2fYAFJq5ind9yH4wgOcVvCG9KyETUnHUlVuQilygENNhBdYvtztVZhDJdjHYn9Y+hhuBJH9IXYPrZqMxBWoueDy9qexNZx8m+DSm0dowZYpJS2mNDGDChMZCNgWP2QwPdeuD3ioHGu5KLNTslHxhxG+hM8WEGffgIVNjfTA8tBG34KeSBnl8IEnSmFv0qCQprnYKToHD4ftLtt2759fMmmjLVfIvxvBLTufHi7F1K4BWo1HIkS8BdGvF8KZ+Gt8uxLMiA2gfSWw1RNK8OrumJ+kfQzplCtkMNIuj3zx8vbiEnqsE/85dgv9+JXymW4IrN7Z/Grvptr4Il3MfSzLuuxLcw3kSsrfCOfwPcL9W9DXj7l7u930J7q90JaEa06aJ3OztS01v91zwfq2Y2m6Wbgn67yjEEsbI4ovhGy72nvOsHksy9kYJ9B9SCJ7IpAR4ywF+7wQ/jd0qgf1NxrgM5Wx8Mbfv4r537vRurXOavN0pgf4g4/mZO71zGrvVcW2UTtN9Qh2bvFXG8idunuirezG483R2i67m4MWVyLDPHc3dp3adNtIkdfr1/G+at771/BrddV76bvneyz9ZOKTi) but unfortunately it didn't work.
- Tried other solutions that i found online but still no luck with the sorting.

Investigation and Solution:

- Since the solutions found online didn't work the next step is looking into this: 


> This issue might be caused because vuetify looking at passed data as [IDs] not [Objects] so we might need to pass a custom sorting function
> 
> More info here https://vuetifyjs.com/en/components/data-tables/sorting/#basic-sorting

**Comment by mohamedamer453** [comment]
Update:

Work Completed:

- The sorting was fixed for the Vm and K8s tables.
- The sorting for the networks and actions columns was disabled.

Work in Progress (WIP):

- After the sorting was fixed i found out that opening the K8s deployment details and opening the worker dialog broke.
- No luck yet with both dialogs still debugging and trying to fix them.

**Comment by mohamedamer453** [comment]
Update:

Work Completed:

- Fixed the broken deployment details and worker dialogs in the K8s deployment table.
- Fixed broken gateway dialog in the vm deployment table.

Status:
 
Pr is ready for review #1348

**Comment by scottyeager** [comment]
Do the changes here fix the issue with sorting `Created At` dates, as seen below?

Note that the contracts created today (11/6) never appear at the top of the list:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/b8c8b903-3897-471b-86ee-5e06e601ab55)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/17682591/754a949e-ee9d-423b-a29e-462fe841ed10)

**Comment by zaelgohary** [comment]
I don't think we need to enable sorting by date as it'll always be the same as sorting by ID. Maybe we should disable it instead?

**Comment by scottyeager** [comment]
> I don't think we need to enable sorting by date as it'll always be the same as sorting by ID. Maybe we should disable it instead?

Hmm, that's true, but it's not intuitive. I probably would not have thought to sort on ID if sorting on created date were disabled. I'm for keeping it.

**Comment by khaledyoussef24** [comment]
fixed and unnecessarily  fields disabled in both deployment lists and contract lists 
[Screencast from 11-23-2023 04:42:32 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/07e900aa-1d08-4f2f-9e66-c2f801754a33)
[Screencast from 11-23-2023 04:42:03 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cd611197-2959-4299-ac8c-f64ca322560e)
[Screencast from 11-23-2023 04:35:53 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4e8d1206-aca8-4017-bd0c-bae5f1a045ee)

i think the state sorting should be disabled
