### ISSUE TITLE
🐞 [Bug]: some nodes have broken flag images

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

some nodes have broken flag images
#2852 

### which network/s did you face the problem on?

Dev

### version

2.6

### Relevant screenshots/screen records

<img width="74" alt="Screenshot 2024-08-07 at 11 39 23 AM" src="https://github.com/user-attachments/assets/1ce147b1-28dc-42b4-afcd-aaedf18362d8">
<img width="1680" alt="Screenshot 2024-08-07 at 11 39 24 AM" src="https://github.com/user-attachments/assets/53d7c166-cd8b-455b-8355-f12ecf7cfeef">

### Relevant log output

```console
na
```

**Comment by A-Harby** [comment]
Verified, Devnet db4d515.

The broken flag was changed to NA for country with no flag (wrong countries from fake nodes).

![image](https://github.com/user-attachments/assets/b631811d-48b9-4cd8-a9cb-62ab029fda28)
![image](https://github.com/user-attachments/assets/3e2041d6-a60e-4d6e-b860-5a7d3f31c89d)
