### ISSUE TITLE
Live node check with Farm Filtering

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#325]
### Description

How will the live node check work since the node selection is now changed to farm selection?

Currently the nodes on devnet are offline and when i configured my vm i was allowed to deploy but after that i got this error message mentioning that the node was not accessible.

![image](https://github.com/threefoldtech/playground/assets/101194226/8531ad16-71ee-46ce-b4fd-11bbbe7cf191)

And there's no check being done now and the deployment is allowed once the resource validation is passed.

![image](https://github.com/threefoldtech/playground/assets/101194226/0d583f68-e440-4f7a-ba3e-c960e26678a2)

**Comment by xmonader** [comment]
@alichaddad please check if anything is needed for the gridproxy

**Comment by mohamedamer453** [comment]
Verified on devnet.

Live node check was added and each node is checked when it's selected from the nodes list to verify that it's online.

[TF Playground _ Full Virtual Machine (4).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cd195b7b-665b-4b66-9b4f-1cb8072cf83a)
