### ISSUE TITLE
🐞 [Bug]: The IPV4 Network option button is disabled on the staging dashboard

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Cannot On/Off The IPV4 Network option Toggle as the button is inactive.

### which network/s did you face the problem on?

Dev

### version

f7fffc5

### Relevant screenshots/screen records

![ipv4_button](https://github.com/user-attachments/assets/8ab3fc75-b718-45e0-ad74-dce45f133373)

### Relevant log output

```console
n/a
```

**Comment by samaradel** [comment]
### Work Completed:
Fix apps IPV4 switch button from being disabled by default

**Comment by khaledyoussef24** [comment]
verified on devnet
version : cddbd85


![Image](https://github.com/user-attachments/assets/928d241c-4fad-4412-87a4-2e0ccfb91505)
![Image](https://github.com/user-attachments/assets/83875f44-f6a7-4bb4-b6a3-b84b6ff035a9)
![Image](https://github.com/user-attachments/assets/68b1cb76-014a-422e-a073-712fbaeacfa0)



![Image](https://github.com/user-attachments/assets/50ed3287-92bf-4b42-83c3-44a6f33ccb87)
![Image](https://github.com/user-attachments/assets/2dc1493d-9a68-46ae-b1d3-4e6460b98e20)
![Image](https://github.com/user-attachments/assets/79c77e44-8dec-4a7b-b8eb-fa62aa03843e)
