### ISSUE TITLE
Error while deleting contracts

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#327]
![image](https://github.com/threefoldtech/playground/assets/40770501/6ca28a1c-274c-4392-9249-074074a172f7)

**Comment by mohamedamer453** [comment]
Verified on qanet playground `2.0.0-rc14`

I tried to delete a couple of my contracts that were in grace period while i had 0 tft in my account and i wasn't able to, and i got a clear error message mentioning that my balance is not enough. and i can check exactly the amount needed to delete/unlock my contract by clicking on `GracePeriod` from the contracts list.

[Screencast from 21-06-23 11:41:31.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1209a8d7-d9e7-4b28-bd0e-6a4b33d75cb5)
