### ISSUE TITLE
Change the background color for the disabled buttons based on the button's state

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3270]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

The ipv4 is disabled but its value is true. It looks like it's false
![Screenshot from 2024-08-08 12-45-05](https://github.com/user-attachments/assets/a92da546-3e0b-478f-843d-a5fe9d455f1c)

### Describe the solution you'd like

Add a background color for the button to indicate having the value true or false while it's disabled

**Comment by samaradel** [comment]
### Work Completed:
Fix Ipv4 switch button when it disabled

**Comment by A-Harby** [comment]
Verified, Devnet cddbd85.

The toggle is now in a gray-green color; its visible that its activated.

![image](https://github.com/user-attachments/assets/f7735df2-bfdc-4a32-8f32-ce8f98d20729)
