### ISSUE TITLE
Refactor Grid Nightly workflow

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3273]
### Which package/s are you suggesting this feature for?

grid_client

### Is your feature request related to a problem? Please describe

Duplicate issues for the same failures.

### Describe the solution you'd like

Avoid creating issues if an issue with the same title exist.

**Comment by zaelgohary** [comment]
Work completed:

Removed unnecessary steps. Also, added a step to check for issue title before creating new one.

**Comment by khaledyoussef24** [comment]
workflow improved and working fine
runs daily and detects if any test fails and opens a new issue.
and check if any existing issues are found so it does not open duplicate issues


![Image](https://github.com/user-attachments/assets/ab5aecbc-ed62-4e33-bf79-ed3410bd8950)
![Image](https://github.com/user-attachments/assets/825a87f1-fbb9-478d-ab4b-7816bc34ffc6)
