### ISSUE TITLE
🐞 [Bug]: Weird error message when trying to deploy on a rented node `RMBError: 0 function is not found`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I got an error saying `Couldn't get free Wireguard ports for node 227 Failed to send request to twinId 8582 with command: zos.network.list_wg_ports, payload: RMBError: 0 function is not found` when I try to deploy on a rented node.

### which network/s did you face the problem on?

Dev

### version

07280a7

### Relevant screenshots/screen records

[screen-capture (4).webm](https://github.com/user-attachments/assets/3179b508-2cd1-44a8-96af-e9709b53100b)

![image](https://github.com/user-attachments/assets/8c416c44-d846-4409-87d5-e0c4b33ba562)

### Relevant log output

```console
.
```

**Comment by Mahmoud-Emad** [comment]
We need to check if that happen on a different node

**Comment by 0oM4R** [comment]
I was able to deploy micro vm on different nodes on different farms with no error at all:
![image](https://github.com/user-attachments/assets/d3b16a60-28ad-40ec-a9f0-75f9768958e0)

**Comment by A-Harby** [comment]
It could be an issue with the node itself, but its not up anymore and can't reproduce the issue.
![image](https://github.com/user-attachments/assets/444fbfe7-9f27-4e5a-bfd2-5229190f51b0)
And the deployment is working fine, so I'm closing the issue.
![image](https://github.com/user-attachments/assets/90bbe76e-84e3-4ea8-abb2-5d55bbf7de5e)
![image](https://github.com/user-attachments/assets/df06a3e3-b2bd-4805-b90b-7c49c716f87d)
