### ISSUE TITLE
escape button for dialogs

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#328]
dialogs should close on escape

**Comment by MohamedElmdary** [comment]
This issue should be fixed by https://github.com/threefoldtech/playground/pull/77

**Comment by mohamedamer453** [comment]
Verified on devnet.

Dialogs can now be closed with escape.

[Screencast from 11-06-23 18:19:10.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6fd4ad47-84ef-4402-8b1e-6944eab8418c)
