### ISSUE TITLE
CapRover Dashboard instance table could show IPv4 address

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3280]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

- Caprover on the dashboard uses by default ipv4, but it isn't shown on the instance deployment table

### Describe the solution you'd like

- We could add ipv4 on the table (even replace planetary by the ipv4, as the focus is on mycelium)

![image](https://github.com/user-attachments/assets/26f50619-6823-43a4-aa9e-85bb3eec050b)

**Comment by Mahmoud-Emad** [comment]
We should add those networks on all of the solutions

**Comment by samaradel** [comment]
### Work Completed:
Add ```ipv4``` column to ```CapRover```

**Comment by A-Harby** [comment]
Verified, Devnet 99b5130.

IPv4 was added to the CapRover deployment table. 
![image](https://github.com/user-attachments/assets/93e0c66a-c03c-43ee-a0ea-40b378131126)
and also added it into the CapRover worker table, but Mycelium is not.
![image](https://github.com/user-attachments/assets/d1ba6c38-a9af-434b-9313-7cc3cbde3916)

I will mark this as done, but im not sure if two tables should be consistent or not necessary.

**Comment by xmonader** [comment]
@ramezsaeed

**Comment by ramezsaeed** [comment]
I think Mycelium must be added into the CapRover worker table.

**Comment by samaradel** [comment]
@ramezsaeed @A-Harby can you create an issue for this please, and feel free to assign me.

**Comment by A-Harby** [comment]
> @ramezsaeed @A-Harby can you create an issue for this please, and feel free to assign me.

Done, https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3446.

Issue verified on https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3280#issuecomment-2324744411.
