### ISSUE TITLE
🐞 [Bug]: Small Mycelium network typo

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- Mycelium should be written with upper case: Mycelium, not mycelium

### Steps To Reproduce

1. Check any app on the dashboard
2. go to network and check mycelium

### which network/s did you face the problem on?

Main

### version

latest

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/05f8c66d-5caa-4587-b573-bc45fa36bf47)

### Relevant log output

```console
- No output
```

**Comment by 0oM4R** [comment]
should be fixed in #3287  
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3287/files#diff-be42196b7e6e7db3698453b1b1cf1e9d7a1cb3ef8881a8cbb8f7cb06add18ec9R71

**Comment by A-Harby** [comment]
Verified, Devnet a66e759.

Mycelium is now capitalized.
![image](https://github.com/user-attachments/assets/e444e230-c2fa-4846-b718-985d2e6562b3)
