### ISSUE TITLE
All Apps on dashboard should have mycelium by default and present mycelium in deployment table

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3283]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

- We want to put Mycelium at the forefront of the TF ecosystem
   - We are currently revising the Manual in this regard
- We should make sure Mycelium is enabled by default and shown to the users in the Dashboard
- Might be a duplicate or outdated. Writing the issue to be sure.
### Describe the solution you'd like

- Every dashboard apps should have mycelium enabled by default in the Network menu
- Mycelium address should always be shown in the deployment table
- Should we remove planetary address in the deployment table? IMO yes so the focus is on Mycelium.
- Here below we see mycelium but the planetary network is shown "first".
![image](https://github.com/user-attachments/assets/e110ec07-6799-40e8-b5ce-b7a8b3d5e93a)

**Comment by mik-tf** [comment]
- data point
   - the mainnet dashboard node pilot provides only ipv4 and ipv6, not mycelium

![image](https://github.com/user-attachments/assets/d7a1648e-23b0-4280-aa20-8ee8c91e7dd3)

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3287

**Comment by A-Harby** [comment]
Verified, Devnet 99b5130.

The Mycelium option is added to all of the solutions: VMs, Orchestrators, and Applications; and is enabled by default in all of them.
 
![image](https://github.com/user-attachments/assets/dc72f5b0-609f-496a-ace0-2bf378d8bdbb)
![image](https://github.com/user-attachments/assets/94362395-fe1e-4002-9e4c-e4f0975c2816)
![image](https://github.com/user-attachments/assets/228fd978-fed4-4b9c-b2c7-8f38f29c25f2)
![image](https://github.com/user-attachments/assets/83019057-9943-482c-ac55-c6dc8e29279b)
