### ISSUE TITLE
Add Docker file

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#331]

**Comment by zaelgohary** [comment]
Added [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/37280f7fc925c5617fe5c2b1dd59d7e27e35cd31)

**Comment by mohamedamer453** [comment]
Verified,

Docker file was added and available in https://github.com/threefoldtech/tfgrid-sdk-ts/commit/37280f7fc925c5617fe5c2b1dd59d7e27e35cd31
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/Dockerfile
