### ISSUE TITLE
🐞 [Bug]: Update `DeleteMachineModel.DeploymentData` validation

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I can't delete a deployment with name `Ofe_tea09`

### which network/s did you face the problem on?

Dev

### version

2.5.2

### Relevant screenshots/screen records

![Screenshot from 2024-08-19 12-29-55](https://github.com/user-attachments/assets/929eb4a1-3a76-40fc-ac00-808ccd33bfc8)

### Relevant log output

```console
Error while deleting deployment ValidationError: Validation failed. errors: An instance of DeleteMachineModel has failed the validation:
 - property deployment_name has failed the following constraints: isAlphanumeric 
.
```

**Comment by AhmedHanafy725** [comment]
related to #2364

**Comment by A-Harby** [comment]
Devnet, 99b5130.

I am still getting the same error!

[screen-capture (5).webm](https://github.com/user-attachments/assets/405a3685-d4f6-4552-ac85-3667c9396be0)

![image](https://github.com/user-attachments/assets/f0a6e4e6-9f13-4297-ab76-e63e1abef624)

```
Validation failed. errors: Array(1) [Object(5) {"target": Object(2) {"name": test_omar, "deployment_name": test_omar}, "value": test_omar, "property": deployment_name, "children": Array(0) [], "constraints": Object(1) {"isAlphanumeric": deployment_name must contain only letters and numbers}}]

Error while deleting deployment ValidationError: Validation failed. errors: An instance of DeleteMachineModel has failed the validation:
- property deployment_name has failed the following constraints: isAlphanumeric 
.

error while getting value of key(VM89c30eb6) GridClientError: Couldn't decrypt key: dev/162/machines/fullvm/VM89c30eb6/contracts.json.
```

**Comment by 0oM4R** [comment]
> Devnet, [99b5130](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/99b5130e1c1f3a502f9de6160545b8a82a4c43c5).
> 
> I am still getting the same error!
> 
>  screen-capture.5.webm 
> ![image](https://github.com/user-attachments/assets/f0a6e4e6-9f13-4297-ab76-e63e1abef624)
> 
> ```
> Validation failed. errors: Array(1) [Object(5) {"target": Object(2) {"name": test_omar, "deployment_name": test_omar}, "value": test_omar, "property": deployment_name, "children": Array(0) [], "constraints": Object(1) {"isAlphanumeric": deployment_name must contain only letters and numbers}}]
> 
> Error while deleting deployment ValidationError: Validation failed. errors: An instance of DeleteMachineModel has failed the validation:
> - property deployment_name has failed the following constraints: isAlphanumeric 
> .
> 
> error while getting value of key(VM89c30eb6) GridClientError: Couldn't decrypt key: dev/162/machines/fullvm/VM89c30eb6/contracts.json.
> ```

the mentioned version is earlier commit 
please validate it on newer version [95f7469](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/95f7469f4daa462fc410f8ebb466e8cc80216783)

**Comment by A-Harby** [comment]
Verified, Devnet 4829e02.

The deletion worked fine.
![image](https://github.com/user-attachments/assets/965b8482-9597-48c5-8c7f-a7faeed0f8ec)
