### ISSUE TITLE
How to deploy k8s workers on different nodes if we filter only on farms not nodes?

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#332]
While deploying, we filter only on countries and farms. What if the user wants to deploy k8s workers, each on different node to reduce risk ?
How that will be handled ?

**Comment by mohamedamer453** [comment]
Verified on devnet.

I deployed a cluster with a master and a worker and both were deployed in different nodes as seen in the deployment details.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/51548543-7b5e-4844-81ff-0c669cc9b056)

and after that i added a worker to the cluster and it was deployed on a third node different from the other 2.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cc02a38e-2f8f-4d23-89a6-41131c651b2a)
