### ISSUE TITLE
Use the same master's filst when adding a new worker to kubernetes cluster

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3320]
https://github.com/threefoldtech/tf-images/issues/292

**Comment by maayarosama** [comment]
Investigation and Solution:
Right now the Flist is hardcoded, still need to test what happens if I change it and add a new worker to an already existing cluster. Should be fixable by passing the master's flist to the worker as a parameter instead of a hard coded variable

**Comment by maayarosama** [comment]
### Work Completed
Added a masterFlist var so when adding a worker the flist would be the same on the master

### WIP
testing the solution

**Comment by khaledyoussef24** [comment]
verified Flist of master and worker are the same
Version fccc6af


![Image](https://github.com/user-attachments/assets/500b86a6-e227-4fb0-8f19-f03784c78c2e)
![Image](https://github.com/user-attachments/assets/75522eba-a188-4743-9ae7-27bf0b912d24)
![Image](https://github.com/user-attachments/assets/59e9a99e-ea29-4fd2-9d2d-1655980c2e91)
![Image](https://github.com/user-attachments/assets/3863a330-dc9c-47db-bf16-840853a34087)
![Image](https://github.com/user-attachments/assets/1f454bad-0310-4e34-9670-2293bd2a268a)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4150337)
