### ISSUE TITLE
🐞 [Bug]: Lock K8S resources during the deployment process

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I selected the master node with public IP, then selected 2 workers also both with public IP, then pressed deploy and got this error.

### Steps To Reproduce

1. Go to [Dashboard](https://staging.dashboard.dev.grid.tf/)
2. Connect your wallet
3. Go to [Deploy Kubernetes application](https://staging.dashboard.dev.grid.tf/#/deploy/orchestrators/kubernetes/)
4. make sure that the selected farm only has 2 public IPs, if the farm has more please address to deploy nodes + 1 
5. Prepare master node with public IP
6. Prepare 3 workers nodes with public IP
7. Press Deploy

### which network/s did you face the problem on?

Dev

### version

28e17de

### Twin ID/s

143

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/fe8b1496-bb85-4a8b-892f-dd1d28fa9206)

### Relevant log output

```console
N /A
```

**Comment by A-Harby** [comment]
Verified, QA 2.6.0.

I tested it with the farm ID 204 (Freefarm2), and it has a free public IP of 5.
![image](https://github.com/user-attachments/assets/6fcd2fbd-1142-4393-9683-ab1e16b1d7f4)
I created a master with a public IP, then started to add a worker with a public IP each.
When I reached the 4 workers (1 master and 3 workers is the max), it gave me no more nodes available.
![image](https://github.com/user-attachments/assets/8dbbe081-971b-4ac2-bc00-1023b9a75a05)
![image](https://github.com/user-attachments/assets/a7304684-1c3e-4b9b-b3fa-f51b4744f146)

Test case created: [TC2941 - Deploy workers with more public IPs than available](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4414371)
