### ISSUE TITLE
🐞 [Bug]: automatic node selection fails to load location

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while deploying a vm `Failed to load locations. Please try again!` error shows up

### which network/s did you face the problem on?

Dev

### version

a542a73

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-08-20 at 5 54 26 PM" src="https://github.com/user-attachments/assets/c1c0aa7f-a0ab-4b7d-bbad-fbf32bb2afec">

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
might be caused by accessing an undefined URL, lazy loading issue

**Comment by khaledyoussef24** [comment]
the issue is still reproducible and can not deploy
![Screenshot 2024-09-29 at 12 37 27 PM (2)](https://github.com/user-attachments/assets/16b33a2e-2fb5-4410-ade5-a078e5d283fe)

**Comment by khaledyoussef24** [comment]
the issue is no longer reproducible  
tried to deploy vms and deployed different appliactions
![Image](https://github.com/user-attachments/assets/5d468698-df64-417a-b23d-acdaead5220b)
