### ISSUE TITLE
🐞 [Bug]: `Error while listing contracts: Unexpected end of JSON input` is keep happening randomly in my contracts page 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

This issue happened to too many times and to multiple people, but the reason of reproducing is unknown. 

I added screenshots from 2 different devices and logs, if it can help identify the reason.

### which network/s did you face the problem on?

Dev

### version

184fa12

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/d9585755-ba7a-4579-9f5b-6327d66d6129)

![image](https://github.com/user-attachments/assets/6b365ad1-327d-4080-b797-52d71dbc3c81)

[dashboard.log](https://github.com/user-attachments/files/16694269/dashboard.log)

### Relevant log output

```console
`Error while listing contracts: Unexpected end of JSON input`
```

**Comment by amiraabouhadid** [comment]
duplicate issue of [#3322](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3322)
