### ISSUE TITLE
🐞 [Bug]: unclear error appears in the dashboard logs while using the deployment lists of vms

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

some deployments produce an unclear error in the dashboard logs when using deployment lists of vms 
all other unclear errors are fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3220

### which network/s did you face the problem on?

Dev

### version

815d729

### Relevant screenshots/screen records

<img width="568" alt="Screenshot 2024-08-25 at 2 09 29 PM" src="https://github.com/user-attachments/assets/b48f83ba-0a9d-41eb-9ea3-d08e8ff9af4e">

### Relevant log output

```console
-
```

**Comment by amiraabouhadid** [comment]
reproduce by making an error in deployment data on the contract using Polkadot add Invalid Deployment Data. Follow the steps to reproduce in in PR in #3220.

**Comment by 0oM4R** [comment]
i can't reproduce with the mentioned steps, contract deployment data is changed and the deployment list lists all other deployments. 
![Image](https://github.com/user-attachments/assets/584d7589-82c8-46d8-8ac9-1ad4000d25bb)


please provide more steps or confirm that it is not happening, also we have error handling to avoid freeze on error and list other deployments

**Comment by khaledyoussef24** [comment]
@0oM4R https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3220#issuecomment-2408877336
is this the same issue ?

**Comment by khaledyoussef24** [comment]
once I delted this contract the issue did not reproduce anymore and can not deploy the same contract again
will close this for now
![Image](https://github.com/user-attachments/assets/0aa32edc-db0f-430f-9604-8dfcc1eb661d)
