### ISSUE TITLE
🐞 [Bug]: Reset function in Input and Form Validator not working

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried resetting a form using a const initialized with the useFormRef and then calling reset() on the const but the form was not reset back to Init status.

### Steps To Reproduce

1. create a form with form validator and input validator components
2. disable submit btn until input is validated
3. make input fields clear after form is submitted (i.e if string input set to "" after submit)
4. use formRef.reset() and inputRef.reset().
5. submit form
6. watch validation get triggered after form is submitted

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/c610cfca-63dd-4d24-aa5d-62abd31b97a1)

### Relevant log output

```console
n/a
```

**Comment by MohamedElmdary** [comment]
Already working but added a tiny feature allowing user to add default value when reseting form/input here https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3297

**Comment by A-Harby** [comment]
Verified, Devnet 96e183a.

Tested couple of forms with submit options, as password form, farm name, add ip and others all still works fine.

[screen-capture (12).webm](https://github.com/user-attachments/assets/cf7540b6-f30b-4d9f-bdeb-ed83b4027839)
