### ISSUE TITLE
🐞 [Bug]: Change mail config validator on taiga

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The same [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2152) is happing to the [taiga](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2152#issuecomment-2314834580), and also check all of the other application stmp.

### which network/s did you face the problem on?

Dev

### version

448a213

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/2152#issuecomment-2314834580

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
Use validation used in discourse solution. Remove the condition applying validation to just discourse.  
Check after the validation change that the solution won't crash because other solution might inherently have different email requirements. 
Check if you can still send emails with SMTP

**Comment by samaradel** [comment]
### Work in Progress (WIP):
utils created to validate SMTP (email, apiKey, username), faced an error .. investigating..

**Comment by samaradel** [comment]
### Work Completed:
- Remove ```isDiscourse``` check and apply adding email or username for all apps with SMTP.
- Create a function to validate applications with SMTP.
- All solutions with SMTP are tested except ```Taiga``` which is blocked on https://github.com/threefoldtech/tf-images/issues/293

**Comment by samaradel** [comment]
### Work Completed:
- Doc string added to explain the new ```IsAlphaExpectDashAndUnderscore``` validator function.
- Unit test added too.

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a78daae

now user names are allowed so user can use api keys or user name normally
![Image](https://github.com/user-attachments/assets/ef31e170-5439-4bda-84f4-5e56162ca3db)
![Image](https://github.com/user-attachments/assets/36435ba0-69b9-4d89-a1f0-e2ad6a7618b6)

passwords is allowed more than 50 characters
validation is also added (in this case i used space in the user name to test validation ):
![Image](https://github.com/user-attachments/assets/597aca31-ead5-43ac-8e06-e71f46480373)
here to check that passwords can be more than 50 characters :
![Image](https://github.com/user-attachments/assets/0af14ced-0aea-4cb0-a465-11dac318027f)
here to check the validation of passwords when inserting space :
![Image](https://github.com/user-attachments/assets/cc2db2c2-d8c2-4712-8869-49f66dc64e5c)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4408753)

**Comment by khaledyoussef24** [comment]
after deploying 2 taigas did not recieve any mails on the mail I used in the setup is this related ?

**Comment by samaradel** [comment]
we mentioned [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3343#issuecomment-2340935784) that taiga part is blocked on https://github.com/threefoldtech/tf-images/issues/293

**Comment by khaledyoussef24** [comment]
Okay, thanks for clarifying.
