### ISSUE TITLE
🐞 [Bug]: Fix typo in Domains solution

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/user-attachments/assets/6a20441b-2fa4-4cd6-9725-f57b9504ddc4)

- Fix: `Deploy Domains Instance`
- Move domains out of the applications and into the deploy section
- Remove the ssh dialogue from the deployment list

### which network/s did you face the problem on?

Dev

### version

37ba5b4

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by A-Harby** [comment]
> Fix: Deploy Domains Instance

Is the typo here Domain, not domains, `Deploy Domain Instance`?

> Remove the ssh dialogue from the deployment list

Shouldn't the SSH section be removed?

![image](https://github.com/user-attachments/assets/c6555a80-a799-446f-aaf6-617fdf186579)

**Comment by maayarosama** [comment]
> > Fix: Deploy Domains Instance
> 
> Is the typo here Domain, not domains, `Deploy Domain Instance`?
> 
> > Remove the ssh dialogue from the deployment list
> 
> Shouldn't the SSH section be removed?
> 
> ![image](https://private-user-images.githubusercontent.com/109473873/365694830-c6555a80-a799-446f-aaf6-617fdf186579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjY1MzYsIm5iZiI6MTcyNjU2NjIzNiwicGF0aCI6Ii8xMDk0NzM4NzMvMzY1Njk0ODMwLWM2NTU1YTgwLWE3OTktNDQ2Zi1hYWY2LTYxN2ZkZjE4NjU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwOTQzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjhlMTBiNGVhMzNjNTg1ODJjNWExNDE2NGQ2YjVkNDhhMzIxZGRkYWJjZDk1MjdlZGE3NTNmNmRlZjM1Mzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ysBHlgmEVjX_T0UXhYncZ2xHj1YmVM60BgvoFSsw6B8)

The typo was the ```a``` in ```Deploy a domains instance```

**Comment by A-Harby** [comment]
Verified, Devnet cc0b65f.

Typo was fixed.
![image](https://github.com/user-attachments/assets/dc15fdc4-d67a-40ae-a825-239cb2a88404)
And ssh tips were removed.
![image](https://github.com/user-attachments/assets/45ba3c9c-e091-466a-b526-fe50d7983463)
