### ISSUE TITLE
🐞 [Bug]: Use default Caprover flist

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When I created a Caprover cluster to test the fix of [this issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3281) I found, I created/attached a new worker after creating the deployment, then I found that the flist of the newly created worker is different then the one that used when creating the full cluster.

### Steps To Reproduce

1. Go to the Dashboard
2. Go to the Caprover application
3. Update the leader and create a worker
4. Deploy them
5. After listing the newly deployed instance click on `Manage Workers` and then `Deploy`
6. After deploying the new worker open the full deployment details hit the newly created worker tab and check all of the flists and you'll see that all of them are not the same

### which network/s did you face the problem on?

Dev

### version

Development

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/bb4cc307-92df-4289-a7e7-94dc994c25a4)

![image](https://github.com/user-attachments/assets/bcfc188f-c72a-4aad-80c5-64ea44073ecc)

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment]
Two flists with two tags: main and latest. Need to unify flists. 
When you deploy two instances, one takes on leader and worker (leader2 and worker2 both get same flist) any later instances get a different flist (worker 3).

**Comment by zaelgohary** [comment]
Unified both flists to be caprover latest.

**Comment by khaledyoussef24** [comment]
verified flists updated
Version fccc6af


and now swarm mode for each deployment is set right 
worker : 
![Image](https://github.com/user-attachments/assets/6cb511c1-d95a-4225-9b59-58485dd07134)
![Image](https://github.com/user-attachments/assets/cc7ac4b1-fa92-4777-9a21-d0a52ed4ca3f)
master : 
![Image](https://github.com/user-attachments/assets/5965c0c7-0879-42e0-ba76-88c2d04cbd69)
![Image](https://github.com/user-attachments/assets/1773d8dc-9239-4322-9610-a690989c4b41)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4401809)
