### ISSUE TITLE
🐞[QAnet] [Bug]: Grace period contracts are showing zero locked tfts with no billing rate because its on a dedicated machine while it was never on a dedicated node

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Grace period contracts are showing `This contract is in a grace period because it's on a dedicated machine also in a grace period. That's why this node is locked with zero TFTS and no billing rate.` while I never rented a node or deployed any of my contracts on a dedicated machine!

### which network/s did you face the problem on?

Dev

### version

4829e02

### Twin ID/s

8823

### Node ID/s

1, 4416

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/aa144849-eb99-466d-b730-d04a1e8b7ba9)
![image](https://github.com/user-attachments/assets/6f1b48a3-4e57-44e7-8097-634b363ea53f)

[node_contracts.json](https://github.com/user-attachments/files/16850799/node_contracts.json)
[name_contracts.json](https://github.com/user-attachments/files/16850801/name_contracts.json)

### Relevant log output

```console
This contract is in a grace period because it's on a dedicated machine also in a grace period. That's why this node is locked with zero TFTS and no billing rate.
```

**Comment by amiraabouhadid** [comment]
related to tfchain locked amount calculation being broken #3340 .

**Comment by A-Harby** [comment]
Verified, Qanet 2.6.0-rc3.

The message now is more clearer and correct.
![image](https://github.com/user-attachments/assets/2525e454-28c2-4db0-bce0-fbf6764bf060)
![image](https://github.com/user-attachments/assets/fb144e55-4ee9-4082-bde3-f70206ca1c7b)

[TC2618 - Grace period locked TFT amount](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430129#case_4214522)
