### ISSUE TITLE
🐞 [Bug]: Use the same validation for secret seed everywhere

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the validation for hex seed is different between client and the input field

### Steps To Reproduce

- use hex seed in the mnemonic or hex seed field in the dashboard without `0x` at the beginning.

### which network/s did you face the problem on?

Dev

### version

development

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/3b6cb3fe-28d0-4782-a362-4860b928679e)

### Relevant log output

```console
-
```

**Comment by samaradel** [comment]
Works for me 
[Screencast from 11-09-24 17:21:19.webm](https://github.com/user-attachments/assets/7ab3e7d4-b3bf-4267-98fd-63aa0abd71cd)
[Screencast from 12-09-24 15:16:23.webm](https://github.com/user-attachments/assets/255acc37-1233-4b2b-849d-66cc990a388e)

**Comment by xmonader** [comment]
@AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
@samaradel please try with a new seed and try to activate the account.

**Comment by samaradel** [comment]
### Work in Progress (WIP):
Added function to force the input to include ```0x``` but with final test it converts the inserted mnemonic into a hex seed.

**Comment by samaradel** [comment]
### Work in Progress (WIP):
faced an error from ```tf-chain``` while activating hex seed without ```0x``` investigating...
![Image](https://github.com/user-attachments/assets/11aea216-2933-43c8-8c04-82aec4761ce7)

**Comment by samaradel** [comment]
### Work Completed:
- Validate the hex seed that passed to activate and create an account function.
- Fix the hex seed label in the profile dialog.

**Comment by samaradel** [comment]
### Work in Progress (WIP):
while refactoring ```checkinput``` function in ```tfchain``` the function stopped working.. investigating...

**Comment by samaradel** [comment]
### Work Completed:
Double check of mnemonic and hex seed that passed to validation function.

**Comment by khaledyoussef24** [comment]
verified on devnet
Version d757d29

user can now login with the seed 0x

![Image](https://github.com/user-attachments/assets/782fe65b-db31-42f8-aa0e-9115062dc1c1)
![Image](https://github.com/user-attachments/assets/b59ccd7d-4c52-41a7-808e-5b6bf49cb2e5)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4208196)
