### ISSUE TITLE
🐞 [Bug]: Delete the gateway workload while deleting the machine/cluster

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I'm encountering an issue with managing Kubernetes domains. After deploying a cluster with one master and one worker node, I named the deployment cluster, the master node master, and the worker node worker. Then, I deployed two domains: domain.gent01.dev.grid.tf and domain2.gent01.dev.grid.tf.

When I deleted the entire cluster, it appears that the domains weren't removed as expected. Later, I re-deployed another cluster using the same names. However, when I accessed the manage domains dialog, the old domains were still listed. These domains aren't associated with the newly deployed cluster, as the backend IPs differ.

I suspect this might be happening because, during the cluster deletion process, the attached gateways aren't being properly removed.

### Steps To Reproduce

1. Go to the dashboard
2. Deploy Kubernetes cluster with one master, one worker
3. Deploy domains both points to the master/worker
4. Delete the deployed cluster
5. Deploy the same cluster again with the same name
6. Open the `Manage Domains` dialog and you'll see the old domains are fetched

### which network/s did you face the problem on?

Dev

### version

4829e02

### Twin ID/s

143

### Relevant screenshots/screen records

N/A

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment]
need when deleting vm and cluster, delete all its gateways

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a78daae

Steps made to verify : 

1. Deployed A K8s cluster with master and worker
2. Added domain to the worker
3. Delete the cluster
4. Make a cluster with the same name
5. Check the domain list
6. The domain shall not be visible 

![Image](https://github.com/user-attachments/assets/24321095-5973-435a-9427-e20ce6857c7e)
![Image](https://github.com/user-attachments/assets/e0e419d4-21e5-4c06-95c6-76d178be5009)
![Image](https://github.com/user-attachments/assets/c8da8ebe-4706-4b51-b6db-cd66633b46c4)
![Image](https://github.com/user-attachments/assets/6920276c-8624-43c5-8d02-4df244ee0498)
![Image](https://github.com/user-attachments/assets/b2353b70-2d9a-453b-a65d-36103f5b121d)
![Image](https://github.com/user-attachments/assets/1b452786-cdbd-4c15-968d-422e8c4e250b)
![Image](https://github.com/user-attachments/assets/3b70e374-1d0d-47f5-a5d0-2d785865c56f)
![Image](https://github.com/user-attachments/assets/7bbef338-b30d-4c02-82ca-5a1d7a2e1650)
![Image](https://github.com/user-attachments/assets/afcedc2d-2ddb-4cc7-a4f5-f9b6cdd647ad)
![Image](https://github.com/user-attachments/assets/b39f6396-c9de-4203-acc8-21a05f61d267)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4408688)
