### ISSUE TITLE
🐞 [Bug]: Gateway contracts and Network contracts both are listed in the Node contracts table

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The contracts list table lists incorrect contracts with incorrect types `Gateway` and `Network` while it should list `Node` contracts only.

I think it might be a proxy issue since they are the same in the response that was returned from the grid proxy

### Steps To Reproduce

1. Go to the Dashboard
2. Deploy a micro VM
3. Deploy a domain for this VM
4. Go to the contracts list and watch the node contracts table

### which network/s did you face the problem on?

Dev

### version

4829e02

### Twin ID/s

143

### Relevant screenshots/screen records

- ![image](https://github.com/user-attachments/assets/c81bb869-a5d5-4fce-9962-a2c1fe26bb6c)
- ![image](https://github.com/user-attachments/assets/002dd3f3-41fc-465c-bc99-b4f12f2ddc1e)

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment]
node contract is for solutions, gateway or network so this isn't an issue
