### ISSUE TITLE
🐞 [Bug]: `lazy load` Dashboard doesn't behave well with refreshing the site

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Dashboard doesn't behave well with refreshing the site.

It happens a lot after using the site for a while, and it breaks everything.

### Steps To Reproduce

1. Navigate to the dashboard.
2. Connect your wallet.
3. Navigate through some pages.
4. Press the refresh button.

### which network/s did you face the problem on?

Dev

### version

4829e02

### Relevant screenshots/screen records

[screen-capture (6).webm](https://github.com/user-attachments/assets/80e291fd-7f07-4e6f-a06c-aeedc4e4cf59)

![image](https://github.com/user-attachments/assets/31c82d33-e709-4b93-8605-3c85f221ae5b)

[dashboard (1).log](https://github.com/user-attachments/files/16871185/dashboard.1.log)

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
same lazy loading issue #3359 and #3322

**Comment by 0oM4R** [comment]
should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3475

**Comment by khaledyoussef24** [comment]
lazy loading issue is solved
already verified 

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3322
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3359
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3480
