### ISSUE TITLE
🐞 [Bug]: Remove unused billing interfaces in gridproxy_client/contracts

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

gridproxy_client

### What happened?

We no longer user gridproxy for retrieving contract consumption billing and discount, so billing interfaces present in gridproxy contract module are useless 

### Steps To Reproduce

1. Just go to gridproxy_client/modules/contracts/ts
2. search for ContractBilling interface used in any of the contracts returned
3. remove interface

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

n/a

### Relevant log output

```console
n/a
```

**Comment by amiraabouhadid** [comment]
don't forget to update interface returned from updated gridproxy

**Comment by amiraabouhadid** [comment]
removed unused billing interfaces, running tests to make sure nothing got broken

**Comment by khaledyoussef24** [comment]
shall be verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3406
and verified that the interfaces were removed from `gridproxy_client/modules/contracts/ts`
![Image](https://github.com/user-attachments/assets/1f6f2d45-2608-4d61-8463-8bc2a603de8c)
