### ISSUE TITLE
🐞 [Bug]: Error message is wrong when account doesn't have enough TFTs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When the account doesn't have enough TFT to do a transaction, the error message should specify that.
But the current behavior is that it give a wrong validation error message.

### which network/s did you face the problem on?

Dev

### version

4829e02

### Relevant screenshots/screen records

[screen-capture (7).webm](https://github.com/user-attachments/assets/3236b915-e1b1-40bc-b67b-e4e892e54929)

### Relevant log output

```console
.
```

**Comment by amiraabouhadid** [comment]
show original error for the failed transaction (insufficient funds) in catch block.

**Comment by zaelgohary** [comment]
Work completed:

Added a condition for insufficient err in public config & additional fee.

**Comment by A-Harby** [comment]
Verified, Devnet b95bde8.

The error message is now updated to reflect the correct error message that the user doesn't have enough money for a transaction.

![image](https://github.com/user-attachments/assets/93f81f68-3cdd-467b-85b8-7854811a4545)
![image](https://github.com/user-attachments/assets/8218dd88-e790-4aef-8a6a-8cc1369612d3)
![image](https://github.com/user-attachments/assets/e070398f-6ed2-46c9-8bc6-4589ab2232d9)
