### ISSUE TITLE
🐞 [Bug]: Empty planetary network IP in K8s

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I was listing k8s workers and I found this:

![image](https://github.com/user-attachments/assets/f4ede9a6-b5a7-4bdc-b358-0340b2218c7e)

### Steps To Reproduce

- Deploy k8s with a worker
- List workers from the deployment lists

### which network/s did you face the problem on?

Dev

### version

dfb8cd3

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by amiraabouhadid** [comment]
Investigate first, If the field is empty, place "-".

**Comment by zaelgohary** [comment]
Work completed:

Set value of planetary to "-" if empty.

**Comment by A-Harby** [comment]
Verified, Devnet a948bfa.

The `-` was added to all the empty fields in the master and workers deployment tables.

![image](https://github.com/user-attachments/assets/3e43b431-ce4d-4bdc-9d5f-3b3600ea134f)

![image](https://github.com/user-attachments/assets/fcda5e67-5acb-41d0-b1cf-c6349cd58011)
