### ISSUE TITLE
🐞 [Bug]: The contract type on the contract page not always correct

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the node contracts that contain `network` or `gateway` have wrong type `vm`

### Steps To Reproduce

- deploy micro vm
- add gateway to this vm
- check the contracts created in the contracts page

### which network/s did you face the problem on?

Dev

### version

development

### Relevant screenshots/screen records

these contracts are shown as vms while they are gateways
![image](https://github.com/user-attachments/assets/c9505904-168f-44ab-9026-e2e599a1919d)

### Relevant log output

```console
-
```

**Comment by 0oM4R** [comment]
we are using grid proxy to list the contracts, and using the type in the "details/deployment_date" 
in dev net all contracts have the type vm, while from their names they are starting with nw-- should be network

![image](https://github.com/user-attachments/assets/a6e01760-42f0-4568-a1f6-09df9f5174f7)


while on main net: 
![image](https://github.com/user-attachments/assets/1b4881ba-1e41-487b-a4dd-4e7897f0410f)

**Comment by 0oM4R** [comment]
@Omarabdul3ziz  can you confirm that gridproxy works fine with that point please?

**Comment by 0oM4R** [comment]
Issue update: the network contracts got updated to be vm  in deployment list, will continue investigating what is the reason of that call

**Comment by 0oM4R** [comment]
Issue update : 
in this pr we have some changes that effect the migrations, the networks contracts got listed and updated later in the migration, need to understand the migration and listing flow then will start to resolve the issue
will keep the estimated time as 3 hours of investigation

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a78daae

![Image](https://github.com/user-attachments/assets/054ea6be-b9ab-4108-900d-e1a1407696e4)
![Image](https://github.com/user-attachments/assets/007be5bb-d95d-47aa-99c4-2775e995001a)
![Image](https://github.com/user-attachments/assets/637894db-c056-42b5-b6a0-028c0ea188d4)
![Image](https://github.com/user-attachments/assets/b06a88d7-b723-48b8-bfea-2a24132a4d2a)
![Image](https://github.com/user-attachments/assets/600f3339-0bff-4bf4-89a7-ed26f4fd7efb)





[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=455301#case_4408432)
