### ISSUE TITLE
Set mycelium as true in applications grid_client scripts

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3379]
### Is your feature request related to a problem? Please describe

# Situation

- We want to put forward Mycelium in all TF deployments
  - see info_grid issue by @xmonader: https://github.com/threefoldtech/info_grid/issues/617
- The scripts of applications have mycelium set as false 

### Describe the solution you'd like

# TODO

- Set Mycelium as true in applications: https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/grid_client/scripts/applications

## References

- Example for casperlabs: https://github.com/threefoldtech/tfgrid-sdk-ts/blob/ae4d8762729aaec21366a9b18ff9e6f811d6632f/packages/grid_client/scripts/applications/casberlabs.ts#L89

**Comment by A-Harby** [comment]
Verified, Devnet.

I tried VM and a few solutions, and Mycelium was enabled and I was able to SSH successfully.

![image](https://github.com/user-attachments/assets/aefd947e-4a31-4e21-827b-4d5d2aa67e5c)
![image](https://github.com/user-attachments/assets/d46ff063-a4e2-4eae-9bd5-9eafd06eb7fb)
![image](https://github.com/user-attachments/assets/c78b316a-d8fb-4880-beb0-56e9f26c51bc)

Checked the scripts, and mycelium flag was enabled on all of them.
