### ISSUE TITLE
🐞 [Bug]: Fix CasperLabs typo

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, grid_client

### What happened?

Mik found a typo in the grid_client using CasberLab instead of CasperLabs

### Steps To Reproduce

1. Search for CasperLabs misspelled in ts-sdk

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

N/A

### Relevant log output

```console
N/A
```

**Comment by A-Harby** [comment]
Verified, Development branch.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/fca22f01925b41c13df23aa8f6b2af9730076d64/packages/grid_client/scripts/applications/casperlabs.ts#L102
