### ISSUE TITLE
🐞 [Bug]: Gateway network contract not deleted after failing to deploy

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried to deploy a domain for my VM using a custom domain and it failed during deployment. However, I noticed that no rollback happened to the created network contract.

![image](https://github.com/user-attachments/assets/5fb4f067-cf15-443c-97c5-a77f3cec817b)

![image](https://github.com/user-attachments/assets/1dd4fbc4-f948-4886-8012-d92505aa4165)

Now, when I try to deploy another domain, it shows this error:

![image](https://github.com/user-attachments/assets/15c2bc62-2b52-4f40-9f1d-736b1abfa8c3)

### Steps To Reproduce

- Deploy vm
- Check your node contracts, you'll find a network contract for the gateway exists
- Now try to add a domain. It should fail with the error below.

### which network/s did you face the problem on?

Dev

### version

ea80744

### Relevant screenshots/screen records

attached above

### Relevant log output

```console
`Failed to deploy the deployment on node 11. Failed to send request to twinId 21 with command: zos.deployment.deploy, payload: {"version":0,"metadata":"{\"version\":3,\"type\":\"network\",\"name\":\"nws1rxs\",\"projectName\":\"vm/vmyq8e8\"}","description":"","twin_id":89,"expiration":0,"workloads":[{"version":0,"name":"nws1rxs","type":"network","data":{"subnet":"10.20.2.0/24","ip_range":"10.20.0.0/16","wireguard_private_key":"lBIlM8lP9I46ImN7f939X9lvpuma0wtBkSITA85UmMo=","wireguard_listen_port":20712,"node_id":11,"peers":[]},"metadata":"{\"version\":3,\"user_accesses\":[]}","description":""}],"signature_requirement":{"requests":[{"twin_id":89,"weight":1,"required":false}],"signatures":[{"twin_id":89,"signature":"02f7139c31f886e46d5e474d2c87397d268ed81e55efd90ce812fd5c8be7284b2161bed35ed8ee10dc42a60f79bf7f27f0895e6d2f98f89a96d921f348f9aa81","signature_type":"sr25519"}],"weight_required":1},"contract_id":149941} RMBError: 0 global workload with the same name 'nws1rxs' exists: conflict`
```

**Comment by zaelgohary** [comment]
Needs to investigate why network type is inconsistent. Related to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3378.

**Comment by zaelgohary** [comment]
Investigate what happens while rolling back.

**Comment by khaledyoussef24** [comment]
could not produce the same issue
deployed vms with domain 
![Image](https://github.com/user-attachments/assets/28a31f7f-daac-4e02-9545-3b1819e404d3)
![Image](https://github.com/user-attachments/assets/6b3b97c8-ff94-4317-bbab-ecf18298aa38)
![Image](https://github.com/user-attachments/assets/dd5ad0f4-b431-492e-8752-008a3de3c2a3)

**Comment by khaledyoussef24** [comment]
could not produce the same issue 
tried to deploy and produce the issue in various way
even this validation prevents creating duplicate gateway even if any contract is not deleted after failing
![Image](https://github.com/user-attachments/assets/e8533900-5625-4b49-9400-91d943b5dd2a)

**Comment by khaledyoussef24** [comment]
is this enough to verify it ?

**Comment by khaledyoussef24** [comment]
network : devnet
** Version a004c81**
tried also to stop the connection in the creation process 
 ![Image](https://github.com/user-attachments/assets/bc0674b3-f598-41b5-b957-176128c195c8)
![Image](https://github.com/user-attachments/assets/926263ad-3ae7-4745-ad59-8f1b79e79052)
the domain would be named `khal`
after the restoring of network the domain was not created and tried to deploy another with the same name to check that if the roll back worked fine and could be able to deploy the same name without any issues
![Image](https://github.com/user-attachments/assets/ebfe33d7-c989-4d4b-957d-9bd77bb390e9)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150370)

**Comment by ramezsaeed** [comment]
The main issue here couldn't be reproduced, which means no fixes done from Dev side.
we tried this latest scenario https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3390#issuecomment-2456372636 and will close it for now.
