### ISSUE TITLE
🐞 [Bug]: Testlodge TestSuites & Cases Updates

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Some of the testlodge test cases are outdated. 

Outdated TestSuites:
- Terraform: 
    - TC219: The instructions in the first link do not work. Just include the second link. 
    - TC220: the given link gives 404. Please update it to https://library.threefold.me/info/manual/#/manual3_iac/grid3_terraform/manual__terraform_readme
    - 
-  Dedicated Nodes: Entire suite needs to update test steps to get to dedicated nodes:
    - TC585: We no longer have a dedicated machines page. Instead, it is now just  a filter on the nodes in the Node Finder page.
    - TC586: There is no longer a portal or an explorer, just dashboard (aka playground)

- Grid3_Client_TS:
    - TC390: links do not direct to where we can create an account or a twin, they just redirect to the test suites page. 
    - TC243: node version requirements are not consistent with README.md in link provided
    - TC1201: The link provided to the generated docs returns a 404.
- New Dashboard:
    - TC2435: custom network is mentioned for the first time in the last bullet point. No instructions are given on how to set up a custom network. Also, please change in the second to last bullet point to "by changing ```export MODE=dev``` or ```export MODE=test``` etc ". 
    - TC2305: change last step to "check if you can access the following: 
         - grid status
         - node statistics
         -  node monitoring
         - pricing calculator
         - node finder
         - images
         - farm finder
         - node installer
         - simulator
         - manual "
    - TC2118: Please remove the add TFTs to your twin and the enter SSH key steps as they are not necessary to creating a twin on the chain. You can move them to a separate test case. 
    - TC2458: Add expected result: "Verify that the stats cards correspond to correct stats". 
    Change second to last expected result to "verify there are 7 cards:
       - Your profile
       - deploy virtual machines
       - deploy applications
       - deploy orchestrators
       - explore grid capacity 
       - explore grid nodes
       -  The layer zero for a decentralized world etc. "
    - TC2319: update screenshots. 
    - TC2197: add domains under deploy in sidebar and update screenshot
    - TC2647: attach a screenshot so tester knows what to expect
    - TC2278: which explore website?
    - TC2682: attach screenshot of logs
    - TC2463: fix typo "to check nodes" in expected results
    - TC2247: consider referring to it as statistics instead of explorer
    - TC2621: I think the last expected result point has a typo; it doesn't make sense.  
    - TC2434: should verify email is there too. Add verify of the qr code and the playstore buttons. 
    - TC2200: mention that user might have to click on the burger menu icon in case balance is collapsed in small screen sizes.
    - TC2201: the get tft button that adds 100 tokens is no longer applicable on dev and qa net.
    - TC2202: should be "Verify the destination and twin ID are correct. Verify **there** is a warning to add twin ID as memo text under twin ID field"  . Last expected result is incomplete and doesn't make sense. 
    - TC2203: there is only 1 bridge 
    - TC2293: check transfer fees in expected results as it may have changed 
    - TC2455: title and description is misleading. Suggestion for title: "Transfer form inputs get cleared after successful transfer", description suggestion: "The transfer twin ID / or address and the transfer amount input fields should be reset after successful transfer"
    - TC2205: mention that two toasts that should should up on successful farm creation
    - TC2241: I think this test case would make more sense if it was split into smaller test cases. A test case for each of the following:  
       - farm creation farm name input validation
       - farm payout address input validation 
       - farm add public IP form input validation 
    - TC2211: remove "Portal"
    - TC2243: add link to creating a twin test case in the description . Farms is not in the twin Details page. Minting reports are no longer in the Your Farm Nodes table. Please update instructions to point to TF minting reports page. 
    - TC2212:add go to 'Your farms" after "Farms" in the sidebar
    - TC2215: there are many more filters added to node finder other than node id and farming policy id, please include them here as well. Also there is no more farming policy id filter
    - TC2214: add node uptime query on gridproxy used to check uptime 
    - TC2279: not enough details , which page ? what is being tested? It is not clear.
    - TC2280: add details on where zero-os and bootstrap can be found in the sidebar, remove playground
    - TC2213: your nodes table is no longer sortable
    - TC2272: outdated, no more 'explorer'
    -  TC2281: outdated, status column in your nodes table is no longer sortable 
    -  TC2275: outdated description
    - TC2285: add max validators values 
### Relevant log output

```console
N/A
```

**Comment by samaradel** [comment]
Test suite: [Virtual Machine Deployment](https://app.testlodge.com/a/26076/projects/40893/runs/757865?run_suite_id=1252038&tab=2)
- [x]  Test case: [TC290](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289561) [outdated
](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3689443)
- [x] Test case: [TC1161](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289) [outdated](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3389184)
- [x] Test case: [TC323](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289568) [outdated](https://github.com/threefoldtech/grid3_client_ts#grid3_client_ts) , [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/config.json) , [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/single_vm.ts)
- [x] Test case: [TC1172](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289571) [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/multiple_vms.ts)
- [x] Test case: [TC298](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289572) [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/vm_with_qsfs.ts) 
- [x] Test case: [TC367](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289574) [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/test_node_filters.ts) , [outdated](https://dashboard.qa.grid.tf/explorer/nodes)
- [x] Test case: [TC1178](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289575) [outdated](https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/name_gateway.ts)
- [x] Test case: [TC1173](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289586) [outdated](https://dashboard.qa.grid.tf/explorer/nodes) 
- [x] Test case: TC314 outdated
- [x] Test case: TC419 outdated
- [x] Test case: TC315 skipped case
- [x] Test case: TC302 skipped case
- [x] Test case: TC294 skipped case
- [x] Test case: TC304 skipped case
- [x] Test case: TC305 skipped case
- [x] Test case: TC306 skipped case
- [x] Test case: TC307 skipped case
- [x] Test case: TC308 skipped case
- [x] Test case: TC309 skipped case
- [x] Test case: TC310 skipped case
- [x] Test case: TC311 skipped case
- [x] Test case: TC312 skipped case
- [x] Test case: TC313 skipped case
- [x] Test case: TC320 skipped case
- [x] Test case: TC321 skipped case
 =====================================
Test suite: [Terraform](https://app.testlodge.com/a/26076/projects/40893/suites/193850)
- [x] Test case: TC220 outdated
- [x] Test case: TC604 wrong info
- [x] Test case: TC185 outdated 
=====================================
Test suite: [TF Grid Stats](https://app.testlodge.com/a/26076/projects/40893/suites/211395)
- [x] Test case: TC1644 outdated 
=====================================
Test suite: [New Dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/234374)
- [x] Test case: [TC2646](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395437) outdated
- [x] Test case: [TC2201](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395454) outdated
- [x] Test case: [TC2246](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395477) outdated
- [x] Test case: [TC2212](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395487) update text
- [x] Test case: [TC2269](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395496) outdated info
- [x] Test case: [TC2270](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395497) outdated info
- [x] Test case: [TC2291](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395525) outdated/wrong info
- [x] Test case: [TC2255](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395539) wrong info
- [x] Test case: [TC2628](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395549) wrong info
- [x] Test case: [TC2229](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395558) wrong/outdated steps
- [x] Test case: [TC2283](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395564) wrong info
- [x] Test case: [TC2440](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395565) wrong info
- [x] Test case: [TC2448](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395566) wrong info
- [x] Test case: [TC2642](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395567) wrong info
- [x] Test case: [TC2484](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395577) need to update the steps
- [x] Test case: [TC2163](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395592) outdated info
- [x] Test case: [TC2164](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395593) outdated info
- [x] Test case: [TC2121](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395614) outdated
- [x] Test case: [TC2785](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395620) update the case
- [x] Test case: [TC2147](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395631) wrong info
- [x]  Test case: [TC2146](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395633) wrong info
- [x] Test case: [TC2126](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395640) outdated info
- [x] Test case: [TC2167](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395652) wrong info
- [x] Test case: [TC2168](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395653) wrong info
- [x] Test case: [TC2170](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395668) wrong info
- [x] Test case: [TC2171](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395675) wrong info
- [x] Test case: [TC2172](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395681) wrong info
- [x] Test case: [TC2173](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395683) wrong info
- [x] Test case: [TC2174](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395685) wrong info
- [x] Test case: [TC2175](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395687) wrong info
- [x] Test case: [TC2176](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395691) wrong info
- [x] Test case: [TC2178](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395693) wrong info
- [x] Test case: [TC2139](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395694) outdated
- [x] Test case: [TC2179](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395695) wrong info
- [x] Test case: [TC2180](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395697) wrong/outdated info
- [x] Test case: [TC2181](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395699) wrong/outdated info
- [x] Test case: [TC2183](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395701) wrong/outdated info
- [x] Test case: [TC2182](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395703) wrong/outdated info
- [x] Test case: [TC2184](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395705) wrong info
- [x] Test case: [TC2738](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395714) wrong/outdated info
- [x] Test case: [TC2740](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395716) wrong/outdated info
- [x] Test case: [TC2804](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395718) outdated
- [x] Test case: [TC2805](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395719) outdated
- [x] Test case: [TC2806](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395720) outdated
- [x] Test case: [TC2808](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256640&selected=33395722) wrong info

**Comment by 0oM4R** [comment]
Test suite: [New Dashboard](https://app.testlodge.com/a/26076/projects/40893/suites/234374)
- [x]  Test case: [TC1577](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254883) update `click on activate` to be login
- [x]  Test case: [TC2435](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254400) we no longer support custom network, it is updated in docs please remove the last step.
- [x] Test case: [TC2305](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254403) update the test case we change the side bar structure 
- [x] Test case: [TC2118](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254405) should be updated we don't ask for the ssh key now.
- [x] Test case: [TC2117](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254410) SSH key is not exists on the profile manager 

- [x] [test case](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254426) outdated
- [x] [test case TC2247](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254439) how to calculate, should be clarified 
- [x] [Test case: TC2652](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254458)
- [x] [No.620 - Test case: TC2235](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254462)
- [x] [Test case: TC2295](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254464)
- [x]  [Test case: TC2235](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254462)
- [x] [Test case: TC2206](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254468) will be fixed on #3472, should remove the last line imo
- [x] [Test case: TC2241](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254467) we should separate the validation fields to other test cases, payout address is already have test case Test case: TC2649 
- [x] [TC2211] (https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254477) `There should be a Zero-OS bootstrap website link in the farm's details.` is not clea, what dose that mean?
- [x] [Test case: TC2212](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254479) steps to be click on farms-> your farms
- [x] [Test case](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254486) clarify the steps
- [x] [Test case](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254495) clarify the test case 
- [x] [Test case](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254496) outdated 
- [x]  [test case 2270](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254489) edit the description, update the steps and define what is the farm page  
- [x] [test case 2279](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254495) clarify, missing steps 
- [x] [Test case: TC2604](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254512) add bandwidth to expected results 
- [x] [Test case: TC2291](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254517) rephrase the test result, to be more clarified and the golden color may not appear if the balance is to low, 
- [x] [Test case: TC2119](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254523) clarify, add more steps to locate the link, screenshot 
- [x] [Test case: TC2249](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254524) 
  `You should see the node is listed by the sorting of CPU status in the Node Finder page.
  You should see the nodes in node selection while deploying are sorted be less CPU provisioned.` that is not clear for me, it should be sorted by the node status, and we should remove the last line as it not related to the test case 
- [x] [Test case: TC2250](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254525) outdated should be changed to new node card
- [x] [Test case: TC2256](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254532) clarify 
- [x] [ Test case: TC2282](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?selected=33254544) duplicated, and please check the tests after it if they are duplicated as well
- [ ] [Test case: TC2747 ](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?=1250709)
- [ ] [ Test case: TC2229](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254550) Outdated, please update steps also i can't find the filter 
- [ ] [ Test case: TC2486 ](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254552) outdated there is no dedicated nodes 
- [ ] [testcase](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254559)  it is not clear for me can we explain more,?

**Comment by khaledyoussef24** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### which package/s did you face the problem with?
> Dashboard
> 
> ### What happened?
> Some of the testlodge test cases are outdated.
> 
> Outdated TestSuites:
> 
> * Dedicated Nodes: Entire suite needs to update test steps to get to dedicated nodes:
>   
>   * TC585: We no longer have a dedicated machines page. Instead, it is now just  a filter on the nodes in the Node Finder page.
>   * TC586: There is no longer a portal or an explorer, just dashboard (aka playground)
> * Grid3_Client_TS:
>   
>   * TC390: links do not direct to where we can create an account or a twin, they just redirect to the test suites page.
>   * TC243: node version requirements are not consistent with README.md in link provided
>   * TC1201: The link provided to the generated docs returns a 404.
> * New Dashboard:
>   
>   * TC2435: custom network is mentioned for the first time in the last bullet point. No instructions are given on how to set up a custom network. Also, please change in the second to last bullet point to "by changing `export MODE=dev` or `export MODE=test` etc ".
>   * TC2305: change last step to "check if you can access the following:
>     
>     * grid status
>     * node statistics
>     * node monitoring
>     * pricing calculator
>     * node finder
>     * images
>     * farm finder
>     * node installer
>     * simulator
>     * manual "
>   * TC2118: Please remove the add TFTs to your twin and the enter SSH key steps as they are not necessary to creating a twin on the chain. You can move them to a separate test case.
>   * TC2458: Add expected result: "Verify that the stats cards correspond to correct stats".
>     Change second to last expected result to "verify there are 7 cards:
>     
>     * Your profile
>     * deploy virtual machines
>     * deploy applications
>     * deploy orchestrators
>     * explore grid capacity
>     * explore grid nodes
>     * The layer zero for a decentralized world etc. "
>   * TC2319: update screenshots.
>   * TC2197: add domains under deploy in sidebar and update screenshot
>   * TC2647: attach a screenshot so tester knows what to expect
>   * TC2278: which explore website?
>   * TC2682: attach screenshot of logs
>   * TC2463: fix typo "to check nodes" in expected results
>   * TC2247: consider referring to it as statistics instead of explorer
>   * TC2621: I think the last expected result point has a typo; it doesn't make sense.
>   * TC2434: should verify email is there too. Add verify of the qr code and the playstore buttons.
>   * TC2200: mention that user might have to click on the burger menu icon in case balance is collapsed in small screen sizes.
>   * TC2201: the get tft button that adds 100 tokens is no longer applicable on dev and qa net.
>   * TC2202: should be "Verify the destination and twin ID are correct. Verify **there** is a warning to add twin ID as memo text under twin ID field"  . Last expected result is incomplete and doesn't make sense.
>   * TC2203: there is only 1 bridge
>   * TC2293: check transfer fees in expected results as it may have changed
> 
> ### Relevant log output
> ```
> N/A
> ```
### **Test cases fixing  progress :**
### Outdated TestSuites:
- [x] Dedicated Nodes: Entire suite needs to update test steps to get to dedicated nodes:
- [x] TC585: We no longer have a dedicated machines page. Instead, it is now just a filter on the nodes in the Node Finder page.
- [x] TC586: There is no longer a portal or an explorer, just dashboard (aka playground)
- [x] Grid3_Client_TS:
- [x] TC390: links do not direct to where we can create an account or a twin, they just redirect to the test suites page.
- [x] TC243: node version requirements are not consistent with README.md in link provided
- [x] TC1201: The link provided to the generated docs returns a 404.

### New Dashboard:


- [x] TC2435: custom network is mentioned for the first time in the last bullet point. No instructions are given on how to set up a custom network. Also, please change in the second to last bullet point to "by changing export MODE=dev or export MODE=test etc ".
- [x] TC2305: change last step to "check if you can access the following:

- grid status
- node statistics
- node monitoring
- pricing calculator
- node finder
- images
- farm finder
- node installer
- simulator
- manual "

- [x] TC2118: Please remove the add TFTs to your twin and the enter SSH key steps as they are not necessary to creating a twin on the chain. You can move them to a separate test case.
- [x] TC2458: Add expected result: "Verify that the stats cards correspond to correct stats".
- [x] Change second to last expected result to "verify there are 7 cards:

- Your profile
- deploy virtual machines
- deploy applications
- deploy orchestrators
- explore grid capacity
- explore grid nodes
-  The layer zero for a decentralized world etc. "


- [x] TC2319: update screenshots.
- [x] TC2197: add domains under deploy in sidebar and update screenshot
- [x] TC2647: attach a screenshot so tester knows what to expect
- [x] TC2278: which explore website?
- [x] TC2682: attach screenshot of logs
- [x] TC2463: fix typo "to check nodes" in expected results
- [x] TC2247: consider referring to it as statistics instead of explorer
- [x] TC2621: I think the last expected result point has a typo; it doesn't make sense.
- [x] TC2434: should verify email is there too. Add verify of the qr code and the playstore buttons.
- [x] TC2200: mention that user might have to click on the burger menu icon in case balance is collapsed in small screen sizes.
- [x] TC2201: the get tft button that adds 100 tokens is no longer applicable on dev and qa net.
- [x] TC2202: should be "Verify the destination and twin ID are correct. Verify there is a warning to add twin ID as memo text under twin ID field" . Last expected result is incomplete and doesn't make sense.
- [x] TC2203: there is only 1 bridge
- [x] TC2293: check transfer fees in expected results as it may have changed

**Comment by zaelgohary** [comment]
- [x] TC249: the case passed, however, link for vm.env in test steps not working.
- [x] TC251: 
script path not found. Kubernetes tests have been moved to
- scripts/orchestrators/kubernetes_leader.ts
- scripts/orchestrators/kubernetes_worker.ts
- scripts/orchestrators/kubernetes_mycelium.ts
- scripts/orchestrators/kubernetes_with_qsfs.ts

- [x] TC254: script path should be updated
- [x] TC770: Cluster tab not found
- [x] TC2522: Expected results need to be changed
![image](https://github.com/user-attachments/assets/e0ecd816-75b8-4c19-9f85-218b5c4af651)

- [x] TC2741: Only unmatched balance contracts are printed.
![image](https://github.com/user-attachments/assets/4e586342-ec6b-468a-8ddb-f0faf78177ef)

- [x] TC772: Test case needs to be updated
- [x] TC1426: Already fails with valid inputs
- [x] TC1252: Skipped from test file itself
- [x] TC1253: Skipped from test file itself
- [x] TC2690: Skipped from test file itself
- [x] TC2701: Skipped from test file itself
- [x] TC2433: outdated
- [x] TC2117: SSH key is no longer in connect tab nor profile manager

**Comment by maayarosama** [comment]
TC2620 : outdated
