### ISSUE TITLE
🐞 [Bug]: Gateway contract in Gitea & Jenkins exist after deployment deletion

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

solutionHasGateway should include Jenkins & Gitea

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/delete_deployment.ts#L75-L89

### Steps To Reproduce

- Deploy Jenkins or Gitea
- Delete the deployment from the deployment list
- Check name contracts, you'll find the gateway contract still exist

### which network/s did you face the problem on?

Dev

### version

ebe226c

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by khaledyoussef24** [comment]
still found on devnet
version : 1f123d2
gateway and vm ccontracts created  but all of the contracts does not get deleted in gittea
(it is also weird 4 contracts are created) 
![Image](https://github.com/user-attachments/assets/4f366b75-bb07-46d0-b2d1-57f7f7efe036)
![Image](https://github.com/user-attachments/assets/af578dfc-b34d-4a2c-982b-ef474ab593a4)
![Image](https://github.com/user-attachments/assets/b4e9fd05-b241-4561-bf84-da176d837d1c)
![Image](https://github.com/user-attachments/assets/a2902c2b-4f4a-4d7c-a2a9-1e11e5f12d4f)
![Image](https://github.com/user-attachments/assets/b1f2a9bc-93f8-4f05-b400-94da9689d7bd)
![Image](https://github.com/user-attachments/assets/72ca41c7-a312-421e-a7e1-c920977836b4)

**Comment by zaelgohary** [comment]
> gateway and vm ccontracts created but all of the contracts does not get deleted in gittea (it is also weird 4 contracts are created) 

4 contracts are normal for all application solutions. 
- deployment contract
- deployment network contract
- gateway contract
- gateway network contract

Regarding the existence of the contracts after deletion, this is because deletion hasn't been reflected on tfchain yet. It takes about 30 seconds or so. Can you double-check if contracts still exist? @khaledyoussef24 

I tested the deletion and found that sometimes, network contracts aren't being deleted. Opened an issue for it [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3425)

**Comment by A-Harby** [comment]
I deployed Jenkis and Gitea.
![image](https://github.com/user-attachments/assets/82c77b18-6afc-490a-a521-d40a39519c65)
![image](https://github.com/user-attachments/assets/73c952cd-09e8-4136-9e64-784e0f5ba2ac)
And after deletion and waiting up to 10 minutes, some of the contracts weren't deleted (network, gateway and name).
![image](https://github.com/user-attachments/assets/6e95e6e1-2699-4fb8-bb7e-1b2713f0d860)
![image](https://github.com/user-attachments/assets/bb2ef9ca-ee4d-45de-a0cb-eb18492e5478)

**Comment by zaelgohary** [comment]
> And after deletion and waiting up to 10 minutes, some of the contracts weren't deleted (network, gateway and name).

Network contracts should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3456)

Will check gateway & name.

**Comment by zaelgohary** [comment]
@A-Harby  All is fixed in the PR mentioned above. Please verify again.

**Comment by khaledyoussef24** [comment]
verified
stagging version : b760b10

<img width="1680" alt="Screenshot 2024-09-30 at 9 22 46 AM" src="https://github.com/user-attachments/assets/9e96f431-281f-4156-8d5d-8efe4b6a08ee">
<img width="1680" alt="Screenshot 2024-09-30 at 9 22 55 AM" src="https://github.com/user-attachments/assets/f579072a-7a78-468b-92b3-e3b339261fba">
<img width="1387" alt="Screenshot 2024-09-30 at 9 23 25 AM" src="https://github.com/user-attachments/assets/74d63558-fc44-4ad3-b773-9c65fddd903a">
<img width="1413" alt="Screenshot 2024-09-30 at 9 24 30 AM" src="https://github.com/user-attachments/assets/d7628965-0bef-4c6f-bd81-b7d326ebcdd5">
<img width="1680" alt="Screenshot 2024-09-30 at 9 24 50 AM" src="https://github.com/user-attachments/assets/2f5e940c-ad4f-4fb2-9a34-8f098e1ba5e7">

https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4379960

**Comment by ramezsaeed** [comment]
verified:
- Devnet
- b760b10
