### ISSUE TITLE
Update tfchain client types

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3401]
### Is your feature request related to a problem? Please describe

#3340 have some new methods and errors

### Describe the solution you'd like

update the auto generated types

**Comment by khaledyoussef24** [comment]
verified 
auto complete is now working with tf chain client types

![Image](https://github.com/user-attachments/assets/9c3c34d5-7096-4483-8597-50d7cc42cdfb)
![Image](https://github.com/user-attachments/assets/bca12e87-995e-4581-a692-c6988e52c6a6)
![Image](https://github.com/user-attachments/assets/2559035c-6d82-42bc-a12e-67f05fac86a4)
![Image](https://github.com/user-attachments/assets/1bf34616-cf77-406f-b6c0-4af5ba908268)

**Comment by ramezsaeed** [comment]
@khaledyoussef24 
regarding to the TFchain issue mention here https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3340
I think you may need to do more test to verify this.
