### ISSUE TITLE
🐞 [Bug]: load logs is taking forever 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

i deployed a micro vm, opened the logs, there were none. pressed load logs and it is still spinning. it has been more than 10 minutes since I've pressed on it 

### Steps To Reproduce

1. run playground
2. open up logs
3. press load logs
4. wait forever

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![Uploading image.png…]()

### Relevant log output

```console
no logs
```

**Comment by amiraabouhadid** [comment]
Investigating why logs are not updated after mount

**Comment by amiraabouhadid** [comment]
Found two unhandled cases, added handling. Will test next.

**Comment by amiraabouhadid** [comment]
Load logs still keeps loading on application mount in some cases, debugging

**Comment by amiraabouhadid** [comment]
fix load logs on application mount. However, logs still sometimes do not load even after deploying a VM so investigating why.

**Comment by amiraabouhadid** [comment]
this console error is now handled and removed as well 
![image](https://github.com/user-attachments/assets/66318c78-d518-46f0-93de-10abd31fb923)

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

The load logs are working fine now.

[screen-capture (9).webm](https://github.com/user-attachments/assets/1e7bec11-1c06-476c-85f4-a2116299f5b1)

[TC2621 - Debug Logs Tab](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4216871)
