### ISSUE TITLE
🐞 [Bug]: Transfer amount validation

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

check what the minimum transfer amount is taking into mind the transfer fees. test lodge test case says transfer fees is 0.01 so shouldn't the minimum transfer amount be more than 0.01 to account for the transfer fees? 

### Steps To Reproduce

1. go to transfer page
2. enter 0.01 in transfer amount field
3. watch validation pass

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/426f9303-2fba-42b9-8e8b-e5e6c3fe9e07)

### Relevant log output

```console
n/a
```

**Comment by maayarosama** [comment]
check that the amount to transfer + 0.01 transfer fees is covered by the balance

**Comment by maayarosama** [comment]
Amount to transfer + transfer fees is always validated against the balance
![Screenshot from 2024-09-23 14-29-41](https://github.com/user-attachments/assets/372f6022-fe8c-4dd3-a3a0-8c0104005987)
![Screenshot from 2024-09-23 14-32-06](https://github.com/user-attachments/assets/e7ec27cc-6fa5-420f-8e51-2c7b509f8ab9)
![Screenshot from 2024-09-23 14-36-56](https://github.com/user-attachments/assets/aad48fb1-8127-4a6a-81a2-44c611a29661)
![Screenshot from 2024-09-23 14-38-41](https://github.com/user-attachments/assets/5129afca-426f-464b-9d10-29d67ac1effb)

**Comment by A-Harby** [comment]
The transfer amount validation is the balance + maximum fee (which is 0.01).
 
[Screencast from 2024-09-25 13-46-15.webm](https://github.com/user-attachments/assets/eec99021-f92e-42bf-a4be-72fe5ae10c02)

[TC2293 - Transfer TFT By Twin Address](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4152312)
