### ISSUE TITLE
🐞 [Bug]: Failed to excute 'add'

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

a sentry error appears in the console once you login 

![image](https://github.com/user-attachments/assets/5470d2f0-e72d-4ed5-97fb-45c065d2cdba)

### Steps To Reproduce

- Go to [Dashboard](https://staging.dashboard.dev.grid.tf/#/)
- login

P.S. You should trigger the toast to be displayed once login by having a contract in grace period for instance.

### which network/s did you face the problem on?

Dev

### version

5941a62

### Relevant screenshots/screen records

-

### Relevant log output

```console
@sentry_vue.js?v=c45f874f:7606 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('mosha__icon__System Mode__warning') contains HTML space characters, which are not valid in tokens.
    at http://localhost:5173/src/utils/custom_toast.ts:49:27
    at sentryWrapped (http://localhost:5173/node_modules/.vite/deps/@sentry_vue.js?v=c45f874f:7589:17)
```

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a78daae

made a contracts and let them go to grace period
tried to login and checking the console if the same add error is produced


![Image](https://github.com/user-attachments/assets/f2a2566a-1a0b-4cd9-b5e4-5c468b167d55)
![Image](https://github.com/user-attachments/assets/b0de78b1-b454-4f97-8334-9bfac181524e)
![Image](https://github.com/user-attachments/assets/2348c146-bd00-4450-acfb-311052561316)
