### ISSUE TITLE
🐞 [Bug]: Stats cards numbers is not corresponded with stats.dev.grid.tf

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, Stats

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254415

### which network/s did you face the problem on?

Dev

### version

2.5.2

### Relevant screenshots/screen records

![Screenshot from 2024-09-18 19-09-19](https://github.com/user-attachments/assets/f46ae34d-b620-4152-8735-22d9288006fd)
![Screenshot from 2024-09-18 19-09-48](https://github.com/user-attachments/assets/2917ef88-4a53-40f3-a41d-ea103e8d72db)

### Relevant log output

```console
.
```

**Comment by maayarosama** [comment]
investigate the result returned from https://stats.grid.tf/api/stats-summary, we use different endpoints

**Comment by A-Harby** [comment]
Its mainnet not devent correct?

And did you assert the value from the stats card in the dashboard to the stats site?
Also, did you check both numbers with stats up and standby?

**Comment by xmonader** [comment]
@0oM4R

**Comment by 0oM4R** [comment]
on dev net
![image](https://github.com/user-attachments/assets/eb02963f-dac5-4105-b255-b6a9dc4645d5)
![image](https://github.com/user-attachments/assets/b2246571-40de-4f25-9871-79da2e41c389)
check nodes, cpu, no need to check for node stats as the stats webside already do this

**Comment by samaradel** [comment]
it works fine on the dashboard 
![Image](https://github.com/user-attachments/assets/00a7d6d0-7236-4b2c-9c38-ea64d66d4794)
with status up
![Image](https://github.com/user-attachments/assets/dd7d187e-92df-477a-8c5b-2c54ced33dd3)
with status standby
![Image](https://github.com/user-attachments/assets/019377b8-0ef1-4115-86e7-ff7c2031450d)

**Comment by samaradel** [comment]
and on stats too 
![image](https://github.com/user-attachments/assets/6e8b7f09-5211-4d5b-a82a-2b6e6f263bea)
![image](https://github.com/user-attachments/assets/f864df4e-a141-4a7f-9263-e89dfd848a5e)
![image](https://github.com/user-attachments/assets/83c82ad3-d62f-4ea0-8a20-97a937cb37ff)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: 4e2fc0b
- the Stats Cards are now aligned with stats.dev.grid.tf

![dashboard_stats](https://github.com/user-attachments/assets/77ca5844-ab2a-41ab-8966-843ffeca62f1)
![sats_dev](https://github.com/user-attachments/assets/590208a7-64c0-459c-af6b-23095ec10f27)

#### Related Link:
https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254415
