### ISSUE TITLE
🐞 [Bug]: Gitea solutions shows as "vm" in the solution type in contracts

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

after deploying gitea and checking contracts 
the solution type is showed as vm

### which network/s did you face the problem on?

Dev

### version

1f123d2

### Relevant screenshots/screen records

<img width="1338" alt="Screenshot 2024-09-19 at 10 27 48 AM" src="https://github.com/user-attachments/assets/06f7b641-c429-442a-9af4-d5cb2eefb873">
<img width="1680" alt="Screenshot 2024-09-19 at 10 31 12 AM" src="https://github.com/user-attachments/assets/e8f41eb9-23bc-4c9d-9537-ca16cae25b42">
<img width="1680" alt="Screenshot 2024-09-19 at 10 31 14 AM" src="https://github.com/user-attachments/assets/ad919544-2f69-43a9-bb50-f43439a0d39a">
<img width="1680" alt="Screenshot 2024-09-19 at 10 31 29 AM" src="https://github.com/user-attachments/assets/3ceb6797-7c54-44c2-a385-90433a4cacd3">

### Relevant log output

```console
na
```

**Comment by khaledyoussef24** [comment]
as mentioned in [#3397](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3397)
4 contracts were created

**Comment by maayarosama** [comment]
Investigation and Solution:
Still investigating from the grid client side, no actual progress

**Comment by maayarosama** [comment]
It might be fixed when #3378 is fixed, I'll have to test it again

**Comment by maayarosama** [comment]
### Work Completed
@0oM4R figured out that the issue was [here](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/types/index.ts#L132)

**Comment by khaledyoussef24** [comment]
verified on devnet
version : ** b760b10**

deployed a gittea and contracts type is now showing right![Image](https://github.com/user-attachments/assets/be06dca8-f1e2-4861-be9b-4535e789163e)
![Image](https://github.com/user-attachments/assets/d0d2f952-047d-4f78-983a-c27e669dff1b)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4311200)
