### ISSUE TITLE
🐞 [Bug]: Network contract exist after deployment deletion

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Jenkins network contracts exist after I deleted the deployment

### Steps To Reproduce

1. Go to dashboard
2. Deploy Jenkins
3. Delete deployment
4. Check network contracts

### which network/s did you face the problem on?

Dev

### version

1f123d2

### Relevant screenshots/screen records

[jenkins_deletion.webm](https://github.com/user-attachments/assets/7e67bb6a-dc07-437a-a655-d9b62f33fe93)

### Relevant log output

```console
-
```

**Comment by maayarosama** [comment]
Might be related to contract type

**Comment by ramezsaeed** [comment]
Failed to load all contracts after delete the jenkins instance !!
Devnet
version: 8529bf1

[Screencast from 09-29-2024 11:49:35 AM.webm](https://github.com/user-attachments/assets/25f4ab58-80b9-4836-b75b-d701d3cacde0)


![Screenshot from 2024-09-29 11-55-25](https://github.com/user-attachments/assets/acaae002-610a-4b3c-ba5a-5ec9f5e3b2d5)
![Screenshot from 2024-09-29 11-53-55](https://github.com/user-attachments/assets/4503d735-f050-436e-a3b8-18940e4ab980)
![Screenshot from 2024-09-29 11-51-21](https://github.com/user-attachments/assets/bbc0fe68-2d50-45b4-86ad-43324fcd72ea)

**Comment by zaelgohary** [comment]
> Failed to load all contracts after delete the jenkins instance !! Devnet version: [8529bf1]

This issue is regarding the lazy loading and should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3322)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- b760b10
