### ISSUE TITLE
🐞 [Bug]: Unable to add caprover worker from deployment list

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I deployed a caprover instance with worker and tried to add another worker from the deployments list but it failed.

I think the issue happens because we use the worker name instead of the leader name.

### Steps To Reproduce

1. Go to dashobard
2. deploy caprover
3. wait till the deployment finishes and add a worker from deployed list

### which network/s did you face the problem on?

Dev

### version

1f123d2

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/27775cc8-fc58-4d11-89b7-8a2f3a6c53ae)

### Relevant log output

```console
-
```

**Comment by amiraabouhadid** [comment]
tried same flow, got this error 
![image](https://github.com/user-attachments/assets/05467a21-79fb-49ca-8789-7e3d7eef0e47)
was able to add worker on second trial though
![image](https://github.com/user-attachments/assets/4aaf89df-f2ce-4f3a-b39c-177cf599f423)

**Comment by Mahmoud-Emad** [comment]
Fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3363

**Comment by atefnazmy** [comment]
- Verified, Dev, e87174a
- successfully added a worker from the deployed list.

![worker](https://github.com/user-attachments/assets/4b0e3930-59fe-4a7e-86b6-d636e736a9bd)


![add_worker](https://github.com/user-attachments/assets/2fd81d80-5e06-4117-8f6e-d63ac415d7b4)


- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4208504
