### ISSUE TITLE
🐞 [Bug]: Failed to load resource: server responded with 503 envelope

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

whenever i run yarn dev from development branch i get the following console err 
appears to be from the RMB as that is where we use envelope 

### Steps To Reproduce

1. open up playground development branch
2. look at console

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/bee26acd-3080-4834-a139-4a78ae6c2e5c)

### Relevant log output

```console
n/a
```

**Comment by wardahub-design** [comment]
This might help:This file might fix it
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by amiraabouhadid** [comment]
console err is no longer there, tested on development branch with slow network
![Image](https://github.com/user-attachments/assets/e8a19b8b-7358-4346-a4b9-f2b24ddb6379)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: f0f91d9
-  The issue is no longer reproducible, and the dashboard handled the resource loading as expected without encountering the 503 error.

![consol](https://github.com/user-attachments/assets/a74cc294-a7ca-4478-a194-030edd100e2a)
