### ISSUE TITLE
🐞 [Bug]: Wrong conversion function `bytesToGB` in tests

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

maybe the naming only misleading but anyways we have to change that  
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/903d36e4be04a14f381e531734a2fab84b5592fd/packages/grid_client/tests/utils.ts#L33-L35

### which network/s did you face the problem on?

Dev

### version

903d36e

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
WIP:
The wrong was in the naming only; I checked the test using it and made sure from that.
And updated the function name to `GBToBytes` and updated all of the tests using it.

**Comment by A-Harby** [comment]
Verified, merged https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3444.
