### ISSUE TITLE
🐞 [Bug]: Comment cancel deployment from multiple_vms script

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

Deployments are being canceled becasue of this line:

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/0c16bcb97cfb3543c9846d6bc6cb491368a39848/packages/grid_client/scripts/multiple_vms.ts#L111

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242430&user_id=170529

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3431

### which network/s did you face the problem on?

Dev

**Comment by samaradel** [comment]
### Work Completed:
Comment cancel deployment function

**Comment by A-Harby** [comment]
Verified, Development branch.

The cancel function was commented as the rest of the scripts.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/1ef744b41010c1353d7fdd012e270118812428ee/packages/grid_client/scripts/multiple_vms.ts#L111
