### ISSUE TITLE
🐞 [Bug]: Deploy a CapRover Leader script failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

vmQueryOptions needs to be updated to include availableFor option and URL is not working. Also, script link is outdated.

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242440&user_id=170529

### which network/s did you face the problem on?

Dev

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/7de2c1de-b137-4465-ba37-cbde194ae44a)

![image](https://github.com/user-attachments/assets/1fa5c16b-85d0-4a86-8cbd-6c7de26b0017)

**Comment by samaradel** [comment]
### Work Completed:
Add ```availableFor``` filter in ```caprover_leader``` script

**Comment by khaledyoussef24** [comment]
verified working now fine
![Image](https://github.com/user-attachments/assets/9b1aa3b2-8bfd-4775-8db4-34e1f4881bdd)
![Image](https://github.com/user-attachments/assets/0d2f6186-cb86-46ed-bfd6-6096456817a7)
![Image](https://github.com/user-attachments/assets/66ab7962-71b4-4dad-ad32-306c26acb439)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=306578#case_3585046)
