### ISSUE TITLE
🐞 [Bug]: Monitoring script failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

This test case shouldn't be in this test suite. Also, the test failed.

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242449&user_id=170529

### which network/s did you face the problem on?

Dev

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/05d318eb-c7be-4d8d-b688-9e73fa801831)

**Comment by maayarosama** [comment]
There's no index.ts file. Monitoring scripts are here https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development/packages/monitoring/example

The testcase is outdated, should be added to the outdated  testcases issue
