### ISSUE TITLE
🐞 [Bug]: Deploy a mycelium K8S script failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

- The test failed as seen in the screenshot below. Also, the test path needs to be changed to scripts/orchestrators/kubernetes_mycelium.ts.

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242451&user_id=170529

### which network/s did you face the problem on?

Dev

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/dc575ec3-3c23-4e6c-82ce-64838041dff7)

**Comment by maayarosama** [comment]
If master and worker deployed on same node we need to add both resources and adjust the filter. but it's better to choose different nodes for them
use excludeNodes filter

**Comment by samaradel** [comment]
@zaelgohary it works with me. ![Image](https://github.com/user-attachments/assets/1d66fe33-91d4-471f-a6a2-04dbd8ccc184)

**Comment by A-Harby** [comment]
Verified, Dev branch.

The Kubernetes scripts is working fine with me too.
![image](https://github.com/user-attachments/assets/23559e32-6cbf-4f73-90d9-8b8a2ceea077)
