### ISSUE TITLE
🐞 [Bug]: Deploy a VM With a Disk Jest test failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242476&user_id=170529

P.S. I had no contracts before running the script.

### which network/s did you face the problem on?

Dev

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/c2c4a5ab-7b42-4244-aed5-d370b4a1fc62)

**Comment by zaelgohary** [comment]
I had no deployments with the same name at the time of running the script.

**Comment by samaradel** [comment]
### Work  Completed:
After fixing some issues locally on my machine with authentication, That works great for me.

![Image](https://github.com/user-attachments/assets/e31eee25-a74c-4e5e-91ba-4efa431a7e4d)

**Comment by A-Harby** [comment]
Verified, Development branch.

I just tried it, and it worked fine with no issue locally or in the workflow. 
![image](https://github.com/user-attachments/assets/4be67f39-0b35-4b47-a285-3a7265bbee95)

And it has been passing for the past few days.
