### ISSUE TITLE
🐞 [Bug]: Failed to add worker to K8s Cluster

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242479&user_id=170529

![image](https://github.com/user-attachments/assets/64df2d4b-c5d0-4c98-a639-87a9020255ea)

P.S. I didn't have any contracts at the time of running the script

### which network/s did you face the problem on?

Dev

### version

-

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
I had no deployments with the same name at the time of running the script.

**Comment by khaledyoussef24** [comment]
still failing am i missing anything ?
![Image](https://github.com/user-attachments/assets/bfe050c9-7562-4fdb-ab2f-abc6b423d2cf)

**Comment by samaradel** [comment]
All cases passed except the ```Add Worker``` case because of https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3509, which was skipped until it get fixed.

![image](https://github.com/user-attachments/assets/14d86178-7da9-4908-8cac-854173f716e7)

**Comment by A-Harby** [comment]
Verified, Devnet branch.

I tried the Kubernetes tests, and it worked fine. 
![image](https://github.com/user-attachments/assets/0082dda8-8099-4b4c-91ed-62d31823b6d6)

For the skipped test case, you could follow up on it [here](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3509#event-14848631443).
