### ISSUE TITLE
🐞 [Bug]: Expose a VM over gateway failed

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242484&user_id=170529

![image](https://github.com/user-attachments/assets/9dac03ac-6051-4df9-b1c9-da64bfa8df9d)

### which network/s did you face the problem on?

Dev

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by zaelgohary** [comment]
It's a timeout issue. Maybe an async operation wasn't completed within the time limit.

**Comment by khaledyoussef24** [comment]
verified fixed and worked fine now

![Image](https://github.com/user-attachments/assets/b9219613-4cb0-4c13-a4db-11635d19f663)
![Image](https://github.com/user-attachments/assets/a45f80b7-ce65-45da-9358-2ca93ea17221)
![Image](https://github.com/user-attachments/assets/c0aa1447-4f31-4977-8aad-fe44fbfb47fc)
![Image](https://github.com/user-attachments/assets/303a3724-553f-4e99-93b5-85d0dbbd7c22)
![Image](https://github.com/user-attachments/assets/16cb58aa-c6b6-4393-b84e-91ee93166956)
