### ISSUE TITLE
🐞 [Bug]: Fix Public Ip Pagination in Your Farms

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

on staging there are 10 ips shown in hamada farm while on dashboard.dev there are 19 public ips 

### Steps To Reproduce

1. create 10 public ips on a farm on devnet 
2. observe how many public ips show up on dashboard.dev
3. observe how many public ips show up on staging.dashboard

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/d2eca275-0cc9-4382-a4d3-4da8a834a098)

### Relevant log output

```console
n/a
```

**Comment by amiraabouhadid** [comment]
After adding ip range, ips are not shown in list 
![Screenshot from 2024-09-29 09-18-09](https://github.com/user-attachments/assets/17e004d4-6a64-4f7b-a95a-eed66f6eb1b7)
![Screenshot from 2024-09-29 09-20-02](https://github.com/user-attachments/assets/c490ed9f-7ac1-43e7-a3b0-3d64b32f6688)

**Comment by khaledyoussef24** [comment]
verified on devnet
Version d757d29

![Image](https://github.com/user-attachments/assets/1b52c81f-d006-4545-9f86-99fc3779f2e4)
![Image](https://github.com/user-attachments/assets/2b109186-c548-44f4-8f75-9b036290dc7f)
![Image](https://github.com/user-attachments/assets/d23f540c-18c5-4b5f-90e3-e6897022b841)
![Image](https://github.com/user-attachments/assets/9f330123-e28d-4124-abfa-cac137069f89)
![Image](https://github.com/user-attachments/assets/19dc1f20-fb18-4bb5-84ee-76cb1d290590)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4402266)
