### ISSUE TITLE
🐞 [Bug]: Consistency between Caprover master and worker table's column.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Consistence between Caprover master and worker table's column. 

More info on: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3280.

### which network/s did you face the problem on?

Dev

### version

4829e02

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/52cdccc5-1315-4c50-86ff-29f96290ef54)
![image](https://github.com/user-attachments/assets/dc3b29c3-852f-4baf-a826-b450b3c4dd54)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
Blocked as there are no available nodes with ```mycelium``` atm

**Comment by samaradel** [comment]
### Work Completed:
- Add the MyCelium IP column in workers table.
- Include myCelium in worker deployment object.

**Comment by samaradel** [comment]
### Work Completed:
Add `Created At` and `Health` columns.

**Comment by samaradel** [comment]
review blocked on https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3565

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: f0f91d9
- Currently there is a consistency between CapRover Master and Worker Table's Columns
- **Created At** , **Health columns** and **MyCelium IP** columns have been added.

![Screenshot From 2024-12-29 21-15-29](https://github.com/user-attachments/assets/f758fc4f-c2d0-4cd3-b4b5-9c168ed0c4ee)

![Screenshot From 2024-12-29 21-11-34](https://github.com/user-attachments/assets/2b6ef8cc-270b-404a-afae-f155c7739e5c)
