### ISSUE TITLE
🐞 [Bug]: Add `NEW` for the newly added application

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The newly added application doesn't have the `NEW` animation added to it.
I think (Gitea, Jenkins, Jitsi, Nostr, static website and TFrobot) should have it.
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3179

### which network/s did you face the problem on?

Dev

### version

ca89db4

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/00be7be7-e47f-47ac-9543-7283697d56a1)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work Completed:
- Add release date for the applications for Gitea, Jenkins, Jitsi, Nostr, static website, and TFrobot.
- Remove importing ```nextTick``` as it's not used anymore.

**Comment by samaradel** [comment]
### Work Completed:
- Add ```new``` label for ```Domains``` too.

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

The `new` tag has been added to the new applications.
(Gitea, Jenkins, Jitsi, Nostr, static website and TFrobot)
![image](https://github.com/user-attachments/assets/4a14f4ee-a2a6-4b9d-893d-1e07fd94dc10)

[TC2866 - New tag for newly added application](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422332#case_4398143)
