### ISSUE TITLE
🐞 [Bug]: solutions gives bad gateway 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

many solutions that require gateway name, gives bad gataway  

### Steps To Reproduce

1. navigate to staging dashbaord
2. find any solution with gateway, wordpress gitea
3. deploy instance
4. navigate to the instance url
5. you will find bad gateway 

### which network/s did you face the problem on?

Dev

### version

ca89db4

### Relevant screenshots/screen records

`

### Relevant log output

```console
`
```

**Comment by xmonader** [comment]
which network? which gateway, .. etc?

**Comment by 0oM4R** [comment]
> which network? which gateway, .. etc?

dev net, I got assigned to confirm the issue and provide more issue, will make sure to mention the gateways

**Comment by 0oM4R** [comment]
![image](https://github.com/user-attachments/assets/8263028c-61e1-407d-a42e-9316de906d79)
Gateway: gent01
while testing #3398

**Comment by 0oM4R** [comment]
![image](https://github.com/user-attachments/assets/b4e514a9-969c-4fa4-a6d5-46d6b614f5e8)
works fine on gent02

**Comment by A-Harby** [comment]
Devnet,038404b.

The domain gent01.dev is working fine with the applications.
![image](https://github.com/user-attachments/assets/7a2a6403-6e6b-45a3-96c2-9c81863e3091)
