### ISSUE TITLE
🐞 [Bug]: Failed to get stats data after 3 attempts

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#3450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

when try to open statistics page in dashboard; got this error:
Failed to get stats data after 3 attempts, Feel free to contact the support team or try again later.

### which network/s did you face the problem on?

Dev

### version

ca89db4

### Relevant screenshots/screen records

![Screenshot from 2024-09-24 15-50-10](https://github.com/user-attachments/assets/bc8deab3-66f2-40bf-a249-1a82999c653e)

[Screencast from 09-24-2024 04:06:13 PM.webm](https://github.com/user-attachments/assets/af2a4ad0-d760-493f-8318-f31c42ceb1be)

### Relevant log output

```console
Failed to get stats data after 3 attempts, Feel free to contact the support team or try again later.
```

**Comment by khaledyoussef24** [comment]
failed to reproduce the same issue 
![Image](https://github.com/user-attachments/assets/bbce5924-7a17-4377-b055-7a1145f1ee1a)
