### ISSUE TITLE
update Kubernetes solution flist

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfgrid-sdk-ts#3465]
### Which package/s are you suggesting this feature for?

Kubernetes

### Is your feature request related to a problem? Please describe

- according to this issue https://github.com/threefoldtech/tf-images/issues/292 a new image for k3s was requested with the new tag not using latest tag.

### Describe the solution you'd like

- update your used Kubernetes flist to be using this one : https://hub.grid.tf/tf-official-apps/threefolddev-k3s-v1.31.0.flist.md

**Comment by AhmedHanafy725** [comment]
Requires: #3320

**Comment by 0oM4R** [comment]
update the flist link in k8s in gridclient

**Comment by khaledyoussef24** [comment]
verified on devnet

Version fccc6af
for both worker and master

![Image](https://github.com/user-attachments/assets/dff95302-9c33-425c-a261-32394a47152f)
![Image](https://github.com/user-attachments/assets/803e6d48-f494-4043-b3a4-e9e471720796)
![Image](https://github.com/user-attachments/assets/a9cd235a-e70a-4233-9869-578a22bf2614)
![Image](https://github.com/user-attachments/assets/7ef0fbf3-e59f-4831-8307-f13d10fec927)
![Image](https://github.com/user-attachments/assets/b0258ee3-0555-4f47-a3d6-0c3be88a9c33)

**Comment by khaledyoussef24** [comment]
I faced this but can not produce it again
![Image](https://github.com/user-attachments/assets/fccfa4d9-30b7-4a75-bfb5-d9357cbe0b74)
