### ISSUE TITLE
🐞 [Bug]: Transfer TFT By Twin ID Input validation accepts decimal value without error

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

i tried to enter 1525.32 and it transferred to twin 1525 

Test case: TC2240 : https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254452

### which network/s did you face the problem on?

Dev

### version

2.5.0

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/248d753c-5a11-4006-b554-1a38a1cf0329)

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
add validation to the twin id field to accept integer only.

**Comment by samaradel** [comment]
### Work Completed:
Add validation on twin ID input as it should accept only integers.

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

The Twin ID validation is showing an error for any incorrect twin ID. 

![image](https://github.com/user-attachments/assets/380e1ad3-653e-4626-a520-6725f428b3db)

[TC2240 - Transfer TFT By Twin ID Input validation](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150449)
