### ISSUE TITLE
🐞 [Bug]: Create farm dialog not cleared after creating the farm

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

i craeted a farm name testlodge, the dialog got closed an toasts appeared then i tried to create another one but i found the old name in the input field with validation error name already exists 

test case: https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254467

### Steps To Reproduce

1. create a farm
2. wait until the dialog got closed,
3. click on create farm button, you will see the old farm name

### which network/s did you face the problem on?

Dev

### version

2.5.2

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
on dialog close make sure to unmount the dialog to reset the fields

**Comment by samaradel** [comment]
### Work Completed:
Reset the farm name value in the create farm dialog on submit and on close.

**Comment by samaradel** [comment]
### Work Completed:
Remove props of the child as it's not usable in the parent (farm page) and refactor code.

**Comment by khaledyoussef24** [comment]
verified on devnet
Version d757d29
![Image](https://github.com/user-attachments/assets/0247a152-c929-4848-b045-80f02b779707)
![Image](https://github.com/user-attachments/assets/5c1cea31-3037-4a04-a51b-1fa0a6f0694c)


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150414)
