### ISSUE TITLE
Reload you farms table after create new farm

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3471]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

as in contracts page, any operation on the contracts will reload the contract after a while, 30 seconds
but in create farm you need to reload the page manually 

### Describe the solution you'd like

add timer to reload the farmss after a while

**Comment by 0oM4R** [comment]
make the table reload after 30 sec as in contracts table

**Comment by amiraabouhadid** [comment]
Added emit from create user to update userFarms table.

**Comment by khaledyoussef24** [comment]
Version fccc6af

verified on devnet

![Image](https://github.com/user-attachments/assets/0b43c3d6-0ca3-4424-90ca-4b0b97d0ffc0)
![Image](https://github.com/user-attachments/assets/a24e46c5-e6fc-47eb-b15b-85a1e0e807b6)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150414)

**Comment by khaledyoussef24** [comment]
it reloads after the first farm creation but after the second farm creation it does not reload
![Screenshot 2024-10-20 at 11 22 29 AM (2)](https://github.com/user-attachments/assets/f2264084-c09a-446e-b58d-c76a696150d9)
![Screenshot 2024-10-20 at 11 22 40 AM](https://github.com/user-attachments/assets/9e4124e4-863c-415c-bc08-2cfd8809e269)
![Screenshot 2024-10-20 at 11 22 56 AM (2)](https://github.com/user-attachments/assets/efe3bb50-cc75-44c7-a97a-2546d30aca30)

**Comment by A-Harby** [comment]
Verified, Devnet c0d9939.

The farm table reloads every time a new farm is created, even after 3rd one now.
![image](https://github.com/user-attachments/assets/036171ee-06f7-4416-bfeb-be984a381558)
![image](https://github.com/user-attachments/assets/99ac417e-4779-4cf8-9b98-ea747160139e)

Update test case: [TC2205 - Create a Farm](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150414)
