### ISSUE TITLE
🐞 [Bug]: Deployment timeout issue via UI

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When deploying using the dashboard UI it gives a timeout issue while deploying and loading nodes although it deployed via grid-client script on the same node using the same connection.

### Steps To Reproduce
Micro VM
https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289561
Full VM
https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33289564

### which network/s did you face the problem on?

Dev

### Twin ID/s
- 1837
- 9166

### Relevant screenshots/screen records

with dashboard
![image](https://github.com/user-attachments/assets/7f6c2983-da6e-4806-9400-46a7bf3fe805)
![image](https://github.com/user-attachments/assets/1812cc7f-b969-46dc-a3d2-6b34ad78f81b)

with grid-client script

![image](https://github.com/user-attachments/assets/36f53a2c-d523-4cb4-9d01-d21b3851cd54)

![image](https://github.com/user-attachments/assets/add3fc04-471d-4257-8aa6-34a2ce47dcdf)

### Relevant log output

```console
Failed to load deployment with name testvm:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name vm:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name wedtestwithip:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name nwpj0fr:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name nwjpat5:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name testvm:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name nwjpat5:
Cannot read properties of undefined (reading 'workloads')
Failed to load deployment with name vm:
Cannot read properties of undefined (reading 'workloads')
```

**Comment by 0oM4R** [comment]
need some investigation

**Comment by 0oM4R** [comment]
this happens with some twins but if you create new twin will work fine, this also happens on dashboard only.

**Comment by samaradel** [comment]
happened when deploying with grid-client script with twinId ```9166```

![Image](https://github.com/user-attachments/assets/8ceaa415-0e3c-4b15-b3ac-a0983399a0de)

**Comment by maayarosama** [comment]
- #3508

**Comment by AhmedHanafy725** [comment]
related to https://github.com/threefoldtech/rmb-rs/issues/200#issuecomment-2435549736

should be working fine after the restart

**Comment by khaledyoussef24** [comment]
verified and working fine after the restart with twins which had the issue 
Version c0d9939

![Image](https://github.com/user-attachments/assets/c858522d-4c54-4499-bcc7-f8ca946ae166)
