### ISSUE TITLE
🐞 [Bug]: `lazy load` TFT rate convertor is not working

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while using the dashboard the tft convertor is not working
![Screenshot 2024-09-29 at 1 03 42 PM](https://github.com/user-attachments/assets/799e45f7-625f-434b-b823-ff71c6d55423)

![Screenshot 2024-09-29 at 1 03 49 PM (2)](https://github.com/user-attachments/assets/841bf99a-1bc3-4561-a4df-54e0efd1fd25)

### which network/s did you face the problem on?

Dev

### version

b760b10

### Relevant screenshots/screen records

.

### Relevant log output

```console
na
```

**Comment by khaledyoussef24** [comment]
lazy loading related
https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3475

**Comment by 0oM4R** [comment]
should be fixed in #3475

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 205fd89 

the issue is no longer reproducible
![Image](https://github.com/user-attachments/assets/68d97d70-1980-4b4b-a9f1-2094e688dc46)
