### ISSUE TITLE
🐞 [Bug]: `lazy load` Node finder " Can not load nodes "

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

while i was using the node finder i faced this issue :
![Screenshot 2024-09-29 at 1 42 30 PM (2)](https://github.com/user-attachments/assets/86900cc2-5dc1-42b2-afac-c4667b7e5d90)

### which network/s did you face the problem on?

Dev

### version

b760b10

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
this is related to lazy load should be fixed in #3475

**Comment by khaledyoussef24** [comment]
verified on devnet
version : 205fd89
node finder is now working fine and the issue is no longer reproducable
![Image](https://github.com/user-attachments/assets/17a45117-a4f9-4860-887d-bfa58faa67b5)
