### ISSUE TITLE
🐞 [Bug]: Deleting a VM with IPv4 interface linked to a domain will not remove the associated name and gateway contracts

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#3485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, grid_client

### What happened?

When I click the actions button next to a VM and link a domain with an IP reserved by the VM, then proceed to delete the VM, the client leaves the name contract and gateway workload that were supposedly routing traffic to the now-removed VM.

### Steps To Reproduce

1. go to https://staging.dashboard.dev.grid.tf/#/deploy/virtual-machines/full-virtual-machine/
2. Deploy a VM with IPv4 address
3. Add a new domain. Make sure to pick the IPv4 interface
4. Verify that the name contract and the gateway contract were successfully created.
5. Select the VM, from the full-virtual-machine page, and delete it.
4. revisit the contracts page and verify that the name contract and gateway's node contract are left behind.

### which network/s did you face the problem on?

Dev

### version

NA

### Relevant screenshots/screen records

![Screenshot_20240930_164118](https://github.com/user-attachments/assets/a2182cf8-5d2b-40ea-a5b1-4192ca2febb2)

I tried that twice, and here is the result

![Screenshot_20240930_164735](https://github.com/user-attachments/assets/07c40372-9195-4f5a-bd30-5e6ce227315f)

### Relevant log output

```console
NA
```

**Comment by maayarosama** [comment]
This might happen because we check if the backends in  the gateway is wiregaurd ip connected to the vm. In this case the solution need to check on all network interfaces https://github.com/threefoldtech/tfgrid-sdk-ts/blob/205fd89574b83e7651aeac91d69592a130c5cf8a/packages/playground/src/utils/delete_deployment.ts#L122

**Comment by 0oM4R** [comment]
work completed :
add a function that pass all ips to the delete function and edit the filtration prop

WIP: some gws on interfaces like ipv4 didn't got listed checking..

**Comment by A-Harby** [comment]
Verified, Devnet ffbb750.

I deployed a VM and add a domain to it and made sure everything is correct.
then deleted it as mention and verified that all the contracts are deleted from contracts page, including vm, name and gateway.
 
![image](https://github.com/user-attachments/assets/20e1d1ba-a232-4728-ab65-447467bfa444)
![image](https://github.com/user-attachments/assets/00bd3402-5e74-44fe-ae33-38955c6f60b2)
![image](https://github.com/user-attachments/assets/1e3b8ff0-96e5-418e-aea3-89b6422e6a62)

Newly created test case: [TC2903 - Deleting VM with domain](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4410144)
