### ISSUE TITLE
Broken Link > Info Button > Dedicated Toggle

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#3487]
- Broken Link > Info Button next to Dedicated Toggle under VMs & Applications.
![image](https://github.com/user-attachments/assets/1188c8c4-eb2c-429a-ab01-58cf415d82e8)

- Broken Link: https://manual.grid.tf//documentation/dashboard/deploy/dedicated_machines.html

- Networks:
https://dashboard.grid.tf/
https://dashboard.dev.grid.tf/
https://dashboard.qa.grid.tf/

**Comment by samaradel** [comment]
### Work Completed:
Fix dedicated node links across all pages.

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

the link is updated to https://www.manual.grid.tf/documentation/dashboard/deploy/node_finder.html#dedicated-nodes.
![image](https://github.com/user-attachments/assets/9347ed3d-4de3-45f4-b9bc-00e3d9107f72)
