### ISSUE TITLE
🐞 [Bug]: Domains icon doesn't appear on light mode 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/user-attachments/assets/815f8888-f4be-477c-b73d-51222e23e6e7)

### which network/s did you face the problem on?

Dev

### version

205fd89 

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by xmonader** [comment]
@ehab-hassan is it feasible to fix it in 3.15?

**Comment by ehab-hassan** [comment]
Checking...

**Comment by ehab-hassan** [comment]
![image](https://github.com/user-attachments/assets/382f39e0-facb-4fcf-9de7-dcbb7d52e8f7)

I suggest using a material design icon rather than the image to match with other icons at hover & click

**Comment by ehab-hassan** [comment]
fixed

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

The domain icon is now appearing in both light and dark mode.
![image](https://github.com/user-attachments/assets/45804473-de9b-480a-9d91-17e84da0479b)
