### ISSUE TITLE
🐞 [Bug]: Profile manager tabs is not working correctly 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

if i exit the profile manager on connect your wallet tab and reopen it will open on the connect your wallet tab but with login field

### Steps To Reproduce

1. open profile manager to connect a wallet, while you have logged in with another before
2. click on connect your wallet
3. close the dialog
4. reopen it

### which network/s did you face the problem on?

Dev

### version

535487c

### Relevant screenshots/screen records

[Screencast from 2024-10-02 12-53-22.webm](https://github.com/user-attachments/assets/91b3ee1a-9a4d-4a3b-9991-b5c3a6ecc7f7)

### Relevant log output

```console
.
```

**Comment by samaradel** [comment]
### Work in Progress (WIP):
tried several solutions but it still not working, I am investigating...

**Comment by samaradel** [comment]
### Work in Progress (WIP):
trying to fix it via DOM

**Comment by samaradel** [comment]
### Work Completed:
Fix active tab content.

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a516b1b
https://github.com/user-attachments/assets/07119998-45cd-4651-b887-1db17908ac9c
