### ISSUE TITLE
🐞 [Bug]: Switch theme is not working correctly 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I set the them to dark, after refresh, it got switched to light 

### Steps To Reproduce

1. click on switch to dark mode
2. refresh the page 

### which network/s did you face the problem on?

Dev

### version

535487c

### Relevant screenshots/screen records

![Screenshot from 2024-10-02 15-28-26](https://github.com/user-attachments/assets/f6407d6e-9a03-47f8-b52d-677ada9020ea)

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
Devnet, 038404b.

You can still they that if you change it from settings page.
![image](https://github.com/user-attachments/assets/b77482e4-a415-46c7-89a6-76a14a0a9ee2)

**Comment by samaradel** [comment]
### Work Completed:
- Fix the theme switch in the app bar and setting page.
- Fix switching theme on refresh

**Comment by A-Harby** [comment]
verified, Devnet c0d9939.

The switching is now synced with settings and button on the top.
![image](https://github.com/user-attachments/assets/3015a2ae-5196-461d-bc27-97c23d72c1f0)


Updated test case: [TC2199 - Enable/Disable Dark mode](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150408).
