### ISSUE TITLE
🐞 [Bug]: Could get a free wireguard port on node 150 (devnet)

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

was trying to create a machine without wireguard and disabled the option still getting an error that i can not create on the node because no wireguard port is empty

### which network/s did you face the problem on?

Dev

### version

205fd89

### Node ID/s

129 156 160 165

### Relevant screenshots/screen records

<img width="1680" alt="Screenshot 2024-10-07 at 2 52 31 PM" src="https://github.com/user-attachments/assets/61afae78-d0fb-4d29-90ea-78e17af723c0">
<img width="1680" alt="Screenshot 2024-10-07 at 2 52 38 PM" src="https://github.com/user-attachments/assets/5861d9b5-726c-495b-aded-73cde542e514">
<img width="273" alt="Screenshot 2024-10-07 at 2 52 41 PM" src="https://github.com/user-attachments/assets/20f180aa-350d-4609-aafc-b385dafd68f0">
<img width="1680" alt="Screenshot 2024-10-07 at 2 56 10 PM" src="https://github.com/user-attachments/assets/3b4e4d57-d31d-4bee-a760-afaecfee6c88">
<img width="1036" alt="Screenshot 2024-10-07 at 3 00 19 PM" src="https://github.com/user-attachments/assets/60e520c7-2456-4ab1-9554-16c0f9f68a76">

### Relevant log output

```console
na
```

<img width="1680" alt="Screenshot 2024-10-07 at 3 00 20 PM" src="https://github.com/user-attachments/assets/1943e054-0645-4221-b9b5-9b924ab8b649">

**Comment by maayarosama** [comment]
Try using one relay in the stack and leave it one hour in case of cache and try again

**Comment by xmonader** [comment]
@khaledyoussef24 I appreciate that you include the problem in the title, because "can't deploy a VM" sounds like the whole grid is broken.

**Comment by khaledyoussef24** [comment]
@xmonader it seems broke to me i still can not deploy any vm

the issue after inspections it was related to few twin ids and one of them is my twin id

**Comment by khaledyoussef24** [comment]
it seemed broken to me because i could not deploy any vm on any node ,the issues is reproducible on my twin with all nodes.

the issue after inspections was related to a few twins; one is mine.

even when wireguard it turned off.

@xmonader what do you recommend.

**Comment by AhmedHanafy725** [comment]
related to https://github.com/threefoldtech/rmb-rs/issues/200#issuecomment-2435549736

should be working fine after the restart

**Comment by khaledyoussef24** [comment]
verified 
Version c0d9939

now i could use the old twin again and deployed a vm using it successfully 
![Image](https://github.com/user-attachments/assets/d5ed6475-2820-4c05-a8bf-b89184de2415)
