### ISSUE TITLE
🐞 [Bug]: can not create new account

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

every time I try to create a new account, it fails, and I get error code 500
![Screenshot 2024-10-08 at 1 02 14 PM](https://github.com/user-attachments/assets/2d5b979d-c6ae-467d-bd6e-fe419d5b276c)
![Screenshot 2024-10-08 at 1 04 12 PM (2)](https://github.com/user-attachments/assets/48e500f5-932d-4301-ac27-a4fb005c0301)

### which network/s did you face the problem on?

Dev

### version

205fd89

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by maayarosama** [comment]
Activation service might have no tokens

**Comment by xmonader** [comment]
this should be in verification now

**Comment by A-Harby** [comment]
Verified, Devnet 038404b.

The creation is now working again fine.
![image](https://github.com/user-attachments/assets/89689780-a7a3-4296-a004-65bf845a1707)
![image](https://github.com/user-attachments/assets/dffeccd2-0fed-4900-a0fa-fd4eb15df432)

[TC2118 - Create a new twin](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=442285#case_4150327)
