### ISSUE TITLE
🐞 [Bug]: version chip UI enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the version chip is getting over the texts  
![Screenshot 2024-10-08 at 1 16 36 PM](https://github.com/user-attachments/assets/20a6cfe1-7e41-4160-980a-63a233fd41f5)
![Screenshot 2024-10-08 at 1 16 37 PM (2)](https://github.com/user-attachments/assets/f5c1ad86-f5c5-443c-8167-5acc50d75ec1)

### which network/s did you face the problem on?

Dev

### version

205fd89

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by ehab-hassan** [comment]
![image](https://github.com/user-attachments/assets/0ab943de-77b8-4eba-9097-be4dc97effd6)

it's above the text but while it's tonal(transparent) it shows like that I think the best way is to move it to the footer

**Comment by ehab-hassan** [comment]
I moved this issue to accepted becaus there are code modifications needed here so @AhmedHanafy725 ll need some help from deveoper here 🙏

**Comment by ehab-hassan** [comment]
Amira did it and waiting for the review

**Comment by khaledyoussef24** [comment]
verified on devnet
Version fccc6af

![Image](https://github.com/user-attachments/assets/dcc4b3d9-6ba0-413d-817c-bfbff0f24a6e)
![Image](https://github.com/user-attachments/assets/9768bca0-8f5b-48d3-9427-c5711a0327ed)
[test case](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4400706)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 56ca263
