### ISSUE TITLE
introduce KYC in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3519]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

Child of https://github.com/threefoldtech/home/issues/1572

### Describe the solution you'd like

Enforcing every user wanting to deploy on the grid to go through the KYC process

**Comment by samaradel** [comment]
- in twin details, add KYC status
- in the client twin deployment handler, check the KYC status
- on the dashboard login/refresh, check the KYC status
- on logout, remove the KYC status
- KYC verification setup should be in an iframe on a separate component that should appear on the button click
- Add documentation in manual repo

**Comment by 0oM4R** [comment]
work completed: 
- init the kyc componet in UI
- add kyc to profile manager store 
- block the deployments if kyc is not verified 
- add kyc client to grid client #3531

**Comment by 0oM4R** [comment]
nothing new waiting for the service domain to continue implementation and testing

**Comment by 0oM4R** [comment]
WIP: integrate kyc in dashboard

add some error handling to the client, modified some method return types, now get token and status are ready will try to test the full idenfy flow tmw

**Comment by 0oM4R** [comment]
issue update: almost done need to define error types and handle them in dashboard

**Comment by khaledyoussef24** [comment]
### **KYC verified on devnet**
Version ffbb750

### Steps made to verify : 
-Made multiple of new accounts
-Verified that the minimum amounts of tft to verify your account is 100 tft
![Image](https://github.com/user-attachments/assets/cc20377b-dc6e-46e1-99d0-1a2968deef61)
- User can not deploy unless he verifies his account
![Image](https://github.com/user-attachments/assets/a1fb21af-3f44-4f7b-add3-d0a75aa29d9d)
- Steps to verify are clear wether click on `verify now` in the warning 
![Image](https://github.com/user-attachments/assets/5d0d3a3a-bf58-4ba1-abf5-f505a2566498)
- or to go to Tfchain profile
![Image](https://github.com/user-attachments/assets/5f146634-1105-454d-a109-e9494a9cbbb5)
- IDenfy page will open and offer you the choice wether to go and verify from the mobile or user can click on verify from the
![Image](https://github.com/user-attachments/assets/041c027e-c5ff-4bb8-9b08-cad2e1c7b314)
- user will have the options to verify using a various methods
![Image](https://github.com/user-attachments/assets/dfd41da6-06b5-4f64-b807-fd99a8ed1316)
- If the user provided a working info account will be verified
![Image](https://github.com/user-attachments/assets/f60ce80c-f636-4fc8-9081-3520ba9c1337)
![Image](https://github.com/user-attachments/assets/21e1301c-c880-42b0-b9c9-6bc2f47d7df9)
![Image](https://github.com/user-attachments/assets/920a46aa-d7e1-4d38-b991-8879a83bba08)
- if the user provided an Expired document or blur photos
![Image](https://github.com/user-attachments/assets/6863d8f0-266d-43e4-a983-5e612121d03f)
![Image](https://github.com/user-attachments/assets/a75ffb2d-37f0-478a-ab49-c5f07ea5a120)

[test section covering all of these](https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#suite_section_455595)

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.6.0-rc3

only noticed this manual verification and its working fine.

![Screenshot from 2024-11-04 14-54-10](https://github.com/user-attachments/assets/5fa065a1-0c26-4167-9fe5-f707f3dda4b1)
