### ISSUE TITLE
🐞 [Bug]: Domains page is broken when the profile isn't active

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The domains page works when the profile is not active. Does the domains page require login??

### Steps To Reproduce

- Navigate to the Dashboard.
- Close the profile manager without logging in.
- The sidebar is disabled for the pages that require login and the user shouldn't be able to access any deployment page without logging in.

### which network/s did you face the problem on?

Dev

### version

77e194

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/f71fdd17-3bb1-43a3-a9a9-1f057ea8eaa6)

**Comment by xmonader** [comment]
It should have the same behavior as the other pages e.g Virtual Machines and Orchestrators  

![image](https://github.com/user-attachments/assets/9774792a-0331-43ae-bc2c-1b17cfc6ef79)

**Comment by samaradel** [comment]
### Work Completed:
- Fix the Domains page view on the before-login view
- Check if there client in gridstore

**Comment by khaledyoussef24** [comment]
verified on devent
Version d757d29

![Image](https://github.com/user-attachments/assets/0eb98faf-4b2a-4d51-ad71-258a0058cb04)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=442285#case_4150325)
