### ISSUE TITLE
🐞 [Bug]: Farm finder clear button doesn't work if any of the filters are not valid

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Farm finder clear button doesn't work if any of the filters are not valid

### Steps To Reproduce

- Click on Farm Finder.
- Enter any invalid input and try to use clear button

### which network/s did you face the problem on?

Dev

### version

77e194

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/4d3ff0cb-3227-4d72-af81-e357fca77fdf)

**Comment by 0oM4R** [comment]
in node finder and farm finder should clear the fields, what ever the data is

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: 4e2fc0b
- Clear button still doesn't work when entering an invalid filter argument.

https://github.com/user-attachments/assets/acf4e1ca-2236-4cde-ba51-9398d431779d

**Comment by ramezsaeed** [comment]
![image](https://github.com/user-attachments/assets/38855089-65ea-4f0e-be53-7faf35933b98)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- The Clear btn works even if any filter input has an invalid value.

https://github.com/user-attachments/assets/6443a037-a326-470e-b99f-5455ed8de104

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4155450
