### ISSUE TITLE
🐞 [Bug]: The Governance link in the dashboard footer doesn't work properly

### ISSUE THREAD

**Issue by atefnazmy** [threefoldtech/tfgrid-sdk-ts#3522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- When I try to click on the Governance link in the dashboard footer, It redirects me to a broken link.

https://github.com/user-attachments/assets/4748be20-181c-4aef-898e-ef2b1c9e4421

### which network/s did you face the problem on?

Dev

### version

038404b

### Relevant screenshots/screen records

n/a

### Relevant log output

```console
n/a
```

**Comment by samaradel** [comment]
Blocked on: https://github.com/threefoldtech/info_grid/issues/660

**Comment by samaradel** [comment]
### Work Completed: 
Fix broken governance link

**Comment by atefnazmy** [comment]
- Verified on Dev, 
- Version: 56ca263
- The Governance Link has been fixed.

https://github.com/user-attachments/assets/da7c83b2-e299-4866-90c3-400327f1716a


- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4246720
