### ISSUE TITLE
🐞 [Bug]: zmount tests are failing on the grid tests workflow

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The zmount tests are keep failing.

### which network/s did you face the problem on?

Dev

### version

dev branch

### Relevant screenshots/screen records

https://github.com/threefoldtech/tfgrid-sdk-ts/runs/31240774792#r0s30

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
@ramezsaeed please check if this test related issue or not.

**Comment by A-Harby** [comment]
> @ramezsaeed please check if this test related issue or not.

I checked the tests, and all its doing is just calling the zmount module function and asserting the result, so the changes are coming from the module, not the tests.

**Comment by samaradel** [comment]
### Work in Progress (WIP):
checking jest return values

**Comment by samaradel** [comment]
### Work Completed:
Fix ```zmount``` test cases expected errors.

**Comment by samaradel** [comment]
### Work Completed:
Refactor test cases

**Comment by samaradel** [comment]
### Work Completed:

Add function to get random number to validate z-mount size

**Comment by samaradel** [comment]
### Work Completed:
Add random ranges to check the min, max, and valid sizes.

**Comment by khaledyoussef24** [comment]
verified and tests are now passing and working  fine
<img width="740" alt="Image" src="https://github.com/user-attachments/assets/cf54b1a6-ac24-4b71-b8bb-088843341ef0" />
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/194096?expand_section=366955#case_4431580)
