### ISSUE TITLE
🐞 [Bug]: Couldn't login with hex seed generated from dart-sdk

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3524]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I created a hex seed usig dart sdk but couldn't login to Dashboard with it.

### Steps To Reproduce

- Create hex seed using stellar package in dart-sdk
- Try to login with seed in the Dashboard

### which network/s did you face the problem on?

Dev

### version

038404b

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/f5f41cc8-4a05-47ba-96b4-44effec84a42)

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
You need to use the TFchain secret here not stellar one
