### ISSUE TITLE
🐞 [Bug]: Set additional fees save button disabled  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/user-attachments/assets/23f23946-ef89-4c2b-989b-eef9b3b34849)
the default value is not acceptable, the save button is disabled, and other value is acceptable but the init one is not even if you rewrite it 

### Steps To Reproduce

1. go to farms 
2. go to your farms
3. in your nodes table 
4. click on any node then set additional fees

### which network/s did you face the problem on?

Dev

### version

2.5.2

### Node ID/s

89

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
save button is disabled in case the value doesn't changed, you may try to change the value and check again.
