### ISSUE TITLE
🐞 [Bug]: pricing page: balance doesn't have max validator

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3529]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254508
![Screenshot from 2024-10-15 21-51-28](https://github.com/user-attachments/assets/18aaf314-5168-452c-84da-8ae5ab46c6d6)

also the error message should have unit

### which network/s did you face the problem on?

Dev

### version

038404b

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
we should set the max balance to 10^15

**Comment by samaradel** [comment]
### Work Completed:
Add the max value for the balance calculation to 1000000000000000.

**Comment by atefnazmy** [comment]
-Verified on Dev,
-Version: 4e2fc0b
-The balance field currently has a maximum validator.

![Image](https://github.com/user-attachments/assets/67dd3a9b-0906-495f-a809-be79e337ea7c)

#### Related Link:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=430165#case_4150494
