### ISSUE TITLE
Invalid shh key in solutions deployment data

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#353]
### Description
![Screenshot from 2023-05-25 11-16-22](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4d943468-40ae-478f-92e2-4adbbdc4c6cd)
this because of  `{ key: "SSH_KEY", value: domain },` in `weblets/tf_wordpress"

### Steps to reproduce

deploy a wordpress instance
check the json data

**Comment by 0oM4R** [comment]
found that on casperlaps to

**Comment by A-Harby** [comment]
Verified, Devnet 861c5f8.

Deployed MicroVm, Subsquid and Wordpress and was pointing to the correct SSH key.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f7f016fb-a7b9-4707-80c8-3ca32d139681)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/be0b2f96-4dd4-428f-8673-cf1c2afeda72)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f1e52cf-7c33-42e2-a128-fe4b7cc80c10)
