### ISSUE TITLE
🐞 [Bug]: pricing calculator: balance less than 1 TFT is acceptable  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254510

### which network/s did you face the problem on?

Dev

### version

038404b

### Relevant screenshots/screen records

![Screenshot from 2024-10-15 21-55-11](https://github.com/user-attachments/assets/816684e8-32c2-4a0e-8c2c-413dec06c662)

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
will fix the test case to accept zero.
