### ISSUE TITLE
🐞 [Bug]: Theme selection Enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

when I go to settings to select the themes the auto fill is turned on in the field 
![Screenshot 2024-10-20 at 10 11 36 AM (2)](https://github.com/user-attachments/assets/c9796e6b-f94b-46b9-99d3-a51334e0a102)
![Screenshot 2024-10-20 at 10 11 45 AM](https://github.com/user-attachments/assets/f8fd9c2a-946a-47e9-bb15-caadcfd2dedb)
can we turn it off  or can we make it like a toggle or selection like this ?
![Screenshot 2024-10-20 at 10 17 35 AM](https://github.com/user-attachments/assets/aa8140af-e45c-4a04-abd5-87b313e3a487)

### which network/s did you face the problem on?

Dev

### version

Version fccc6af

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by 0oM4R** [comment]
@ehab-hassan

**Comment by samaradel** [comment]
I couldn't reproduce it, please verify
https://github.com/user-attachments/assets/323bf8f7-a945-40da-8f9e-b3b37e3363e0

**Comment by ehab-hassan** [comment]
@khaledyoussef24 I don't think we need a toggle here we just have 2 options

**Comment by atefnazmy** [comment]
-Verified on Dev,
-Version: 4e2fc0b
-The Theme selection works as expected.


https://github.com/user-attachments/assets/15e21ed6-62f7-4452-b416-d1b448cc695f
