### ISSUE TITLE
🐞 [Bug]: VM, Full can't list any deployment  

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I can't list any deployment on full vm or vm.
on the commits before this https://github.com/threefoldtech/tfgrid-sdk-ts/commit/d1f7304034abc2b8c47bdebb8bbfd3071767429d it works fine 

### which network/s did you face the problem on?

Dev

### version

d757d29

### Relevant screenshots/screen records

![Screenshot from 2024-10-21 12-50-51](https://github.com/user-attachments/assets/12690dbd-3434-45a8-af88-e5cf80d5d01d)

### Relevant log output

```console
.
```

**Comment by khaledyoussef24** [comment]
the same issue is reproducible  on micro VMs and all apps also
![Screenshot 2024-10-24 at 3 54 33 PM](https://github.com/user-attachments/assets/9ade4fe6-8a00-45ae-ac68-ee8ce12c8429)
![Screenshot 2024-10-24 at 3 59 39 PM](https://github.com/user-attachments/assets/35bebb8b-e45c-4f96-8516-590ba681f6af)

**Comment by khaledyoussef24** [comment]
also the refresh button disappeared
![Screenshot 2024-10-24 at 3 23 47 PM](https://github.com/user-attachments/assets/038b8c6a-3037-45d6-85d5-4bf54152c449)
 
![Screenshot 2024-10-24 at 3 59 39 PM](https://github.com/user-attachments/assets/d6878de6-d444-46b2-a900-c7f0db639957)

**Comment by Mahmoud-Emad** [comment]
> also the refresh button disappeared ![Screenshot 2024-10-24 at 3 23 47 PM](https://private-user-images.githubusercontent.com/110984055/379762310-038b8c6a-3037-45d6-85d5-4bf54152c449.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTA4MzYsIm5iZiI6MTczMDAxMDUzNiwicGF0aCI6Ii8xMTA5ODQwNTUvMzc5NzYyMzEwLTAzOGI4YzZhLTMwMzctNDVkNi04NWQ1LTRiZjU0MTUyYzQ0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmZlYjBkY2QwMDhhYjQ5Yjc4MDE4ODU2Y2UxODIzZjVlN2Y2MGE1YjQxMDYwZjYyYjNkOWQzNWYwYTU5Y2QzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.o0aJ5g3FBlyb1Q0tgxi_B6oxZGHL4V-2mV5bChBicTU)
> 
> ![Screenshot 2024-10-24 at 3 59 39 PM](https://private-user-images.githubusercontent.com/110984055/379762366-d6878de6-d444-46b2-a900-c7f0db639957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwMTA4MzYsIm5iZiI6MTczMDAxMDUzNiwicGF0aCI6Ii8xMTA5ODQwNTUvMzc5NzYyMzY2LWQ2ODc4ZGU2LWQ0NDQtNDZiMi1hOTAwLWM3ZjBkYjYzOTk1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwNjI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTI4YjQ2YmJiYTlhNTU0ZTE4NTA1NjRmNDFmOWQyMmEyOGQxZWMxOTg0YTgyYzU5Y2NkNjc4MWUxYzE0OTA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4uY-PAPXR3HyWnw5-63rhxOkL61AKTlGAL_wHGOrDeg)

I believe the refresh button wasn't there, would you like to add it?

Check my changes [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3363/files)

**Comment by Mahmoud-Emad** [comment]
### Investigation and Solution:

This issue might be due to how `Promise.all` handles errors versus the sequential `for` loop. With `Promise.all`, all `deleteDeployment` calls are executed concurrently, meaning the `delete_machine` method might check for the deployment existence before another instance of it finishes deleting. In contrast, a regular `for` loop executes sequentially, so each `deleteDeployment` call completes before the next starts, avoiding potential race conditions.


### Work Completed:

**Prevent a race condition in deployment deletion by switching to sequential execution**

- Replaced `Promise.all` with a `.reduce()` approach to sequentially await each `deleteDeployment` and `deleteGatewayDeployment` call.

**Comment by A-Harby** [comment]
Verified, Devnet ffbb750.

I deployed a FullVm and it was listed without any error.
![image](https://github.com/user-attachments/assets/dc7abae1-353d-47e4-8be2-81343eec7403)
![image](https://github.com/user-attachments/assets/07e95120-d0a3-4d0d-b52f-e2f385601c26)

[TC2121 - Deploy Full Virtual Machine](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330)
