### ISSUE TITLE
🐞 [Bug]: Validation Error on Deployment Name for CapRover Cluster Worker Attachment

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#3545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I successfully deployed a CapRover cluster with the leader node named `leader_2`. After this, I attempted to attach a worker node to the leader using the `Manage Worker` dialog. 

During the deployment process for the worker, an issue occurred due to the deployment name of the leader, which is `leader_2`. The problem stems from a validation rule in the `AddMachineModel` model, which enforces that the `deployment_name` field must contain only alphanumeric characters, disallowing any underscores or special characters.

Although `leader_2` contains a non-alphanumeric character (`_`), it was allowed for the leader node. However, when attempting to deploy the worker, the same validation rule was triggered, causing the deployment to fail.

This seems inconsistent, as deployment names such as `dep_num21`, which include numbers and valid non-alphabetic characters, should be permitted. It’s crucial that the validation rules align across both leader and worker nodes to prevent deployment failures.

The fix could be the same as https://github.com/threefoldtech/tfgrid-sdk-ts/pull/3353/files

### Steps To Reproduce

1. Go to dashboard
2. Deploy a Caprover leader with name `leader_2`
3. Attach a worker to that leader

### which network/s did you face the problem on?

Dev

### version

..

### Twin ID/s

143

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/94c4418d-423c-4cda-b568-ab1193764312)

### Relevant log output

```console
N/A
```

**Comment by 0oM4R** [comment]
`IsAlphanumericExpectUnderscore` should be added to  
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/95f7469f4daa462fc410f8ebb466e8cc80216783/packages/grid_client/src/modules/models.ts#L155

and add to k8s models like AddWorkerModel

**Comment by khaledyoussef24** [comment]
verified issue is no longer reproducible 
Version a78daae



![Image](https://github.com/user-attachments/assets/676d695a-7ceb-4cc7-913b-d37c6880d4f3)
![Image](https://github.com/user-attachments/assets/2f9a87f9-60d9-4613-b6ed-ae5131ce47f2)
![Image](https://github.com/user-attachments/assets/dcba8544-1166-4648-950a-d810a2f81dc1)
![Image](https://github.com/user-attachments/assets/159606d9-91fa-4538-9488-347d9f8ddc18)
![Image](https://github.com/user-attachments/assets/dabb9fe5-497b-4f8f-b203-125b552ed64a)

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4408430)
