### ISSUE TITLE
🐞 [Bug]: Mainnet config in ts client isn't correct for stellar network

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard, grid_client

### What happened?

I thought by changing the mode to main all the variables in the config file would change to the mainnet, but I could see the stellar network is still on test, not main, probably the same happens to the issuer, not sure.

### Steps To Reproduce

1. cd packages/playground/public
2. export MODE=main
3. bash ../scripts/build-env.sh

### which network/s did you face the problem on?

Dev, Main

### version

dev branch

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/d8f57548-e735-40d2-b2dc-86ca2aa7c038)

### Relevant log output

```console
window.env = {
  NETWORK: 'main',
  GRAPHQL_STACKS: ['https://graphql.grid.tf/graphql','https://graphql.02.grid.tf/graphql'],
  GRIDPROXY_STACKS: ['https://gridproxy.grid.tf','https://gridproxy.02.grid.tf'],
  SUBSTRATE_STACKS: ['wss://tfchain.grid.tf/ws','wss://tfchain.02.grid.tf/ws'],
  ACTIVATION_SERVICE_STACKS:  ['https://activation.grid.tf/activation/activate','https://activation.02.grid.tf/activation/activate'],
  RELAY_STACKS:  ['wss://relay.grid.tf','wss://relay.02.grid.tf'],
  BRIDGE_TFT_ADDRESS: 'GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC',
  STELLAR_NETWORK: 'test',
  STELLAR_HORIZON_URL: 'https://horizon-testnet.stellar.org',
  TFT_ASSET_ISSUER: 'GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3',
  MINTING_URL: 'https://alpha.minting.tfchain.grid.tf',
  STATS_STACKS: ['https://stats.grid.tf','https://stats.02.grid.tf'],
  TIMEOUT: +'10000',
  PAGE_SIZE: +'20',
  MANUAL_URL: 'https://www.manual.grid.tf',
  SENTRY_DSN: 'https://598bcc658bd99042ab429166035f8278@sentry.grid.tf/2',
  ENABLE_TELEMETRY: 'false'
};
```

**Comment by AhmedHanafy725** [comment]
you have to set stellar network https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/docs/build.md#run-the-script

**Comment by A-Harby** [comment]
Okay mb, so both have to be exported I thought the mode would be enough
