### ISSUE TITLE
🐞 [Bug]: Multiple stack is not switching when one of them goes down

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#3548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I created my own stack and it worked fine, then I followed the steps to deploy a dashboard with multiple stacks. The first provided was my own stack, and the second was the main stack I processed with the deployment, and it worked fine. Then I shut down my own stack, excepting the dashboard, to switch to the working main stack, but it didn't; it just broke, only showing errors.

### Steps To Reproduce

[TC2825 - Run locally with multiple stack](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422337#case_4363617)

### which network/s did you face the problem on?

Dev, Main

### version

Dev branch

### Relevant screenshots/screen records

[screen-capture (10).webm](https://github.com/user-attachments/assets/fc947d0e-a07e-4b98-b00d-3be880c6b1cd)

[dashboard (3).log](https://github.com/user-attachments/files/17473780/dashboard.3.log)

### Relevant log output

```console
window.env = { NETWORK: 'main', GRAPHQL_STACKS: ['https://graphql.harby.gridtesting.xyz/graphql','https://graphql.02.grid.tf/graphql'], GRIDPROXY_STACKS: ['https://gridproxy.harby.gridtesting.xyz','https://gridproxy.02.grid.tf'], SUBSTRATE_STACKS: ['wss://tfchain.harby.gridtesting.xyz/ws','wss://tfchain.02.grid.tf/ws'], ACTIVATION_SERVICE_STACKS: ['https://activation.harby.gridtesting.xyz/activation/activate','https://activation.02.grid.tf/activation/activate'], RELAY_STACKS: ['wss://relay.harby.gridtesting.xyz','wss://relay.02.grid.tf'], BRIDGE_TFT_ADDRESS: 'GBNOTAYUMXVO5QDYWYO2SOCOYIJ3XFIP65GKOQN7H65ZZSO6BK4SLWSC', STELLAR_NETWORK: 'main', STELLAR_HORIZON_URL: 'https://horizon-testnet.stellar.org', TFT_ASSET_ISSUER: 'GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3', MINTING_URL: 'https://alpha.minting.tfchain.grid.tf', STATS_STACKS: ['https://stats.harby.gridtesting.xyz','https://stats.02.grid.tf'], TIMEOUT: +'10000', PAGE_SIZE: +'20', MANUAL_URL: 'https://www.manual.grid.tf', SENTRY_DSN: 'https://598bcc658bd99042ab429166035f8278@sentry.grid.tf/2', ENABLE_TELEMETRY: 'false' };
```

**Comment by ramezsaeed** [comment]
It will not switch without refresh; you need to refresh the page and try again

**Comment by A-Harby** [comment]
It did work, but after refreshing, which wasn't mentioned anywhere.

![image](https://github.com/user-attachments/assets/54208728-1e07-48ea-9e40-5e6d7b84aefd)
