### ISSUE TITLE
🐞 [Bug]: logger can't read properties of value

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

console error from logger accessing undefined.value

### Steps To Reproduce

1. pull development branch
2. yarn lerna run build
3. make run project=playground
4. look for error in console

### which network/s did you face the problem on?

Dev

### version

current

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/de130547-d316-412b-9b56-1d10b3be795a)

### Relevant log output

```console
[Vue warn]: Error in setup function: "TypeError: Cannot read properties of undefined (reading 'value')"

found in

---> <VBtn>... (16 recursive calls)
       <App> at /home/amira/tfgrid-sdk-ts/packages/playground/src/App.vue
         <AsyncComponentWrapper>
```

**Comment by ramezsaeed** [comment]
cannot reproduce.
please re-verify

**Comment by amiraabouhadid** [comment]
was not able to reproduce on development_2.7 nor on development branches. nevertheless added conditional to check if logs.value is defined before pushing item to it

**Comment by khaledyoussef24** [comment]
issue is no longer reproduicable; tried to produce the same issue many times but with different contracts but didn't pop out.
