### ISSUE TITLE
invalid entrypoint in many solutions

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#356]
while investigating in #256 I found the VM is not accessible for ssh.
the ` entryPoint: "/init.sh",` is not the same to the [docs](https://github.com/threefoldtech/tf-images/tree/development/tfgrid3/wordpress#entrypoint)
some other solutions like subsquid and casperlabs have the same issue

**Comment by A-Harby** [comment]
Verified, devnet 861c5f8.

Entry point was updated to `/sbin/zinit init`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c13b4d16-6669-4eea-af35-bc65e0efc447)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/62c1c08c-03d1-4b50-9cd9-5c6f7d0d14d9)
