### ISSUE TITLE
🐞 [Bug]: SSH warning and KYC warning

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

when creating a new one that is not verified and has no SSH keys, only one warning is shown on the deployment page.
<img width="1680" alt="Screenshot 2024-11-04 at 7 10 02 AM" src="https://github.com/user-attachments/assets/8618c3e7-a39e-429a-b5d3-44f045c26f21">

<img width="1680" alt="Screenshot 2024-11-04 at 7 05 09 AM" src="https://github.com/user-attachments/assets/31550b08-ac33-44a8-af60-39a23a39e6d6">
<img width="1680" alt="Screenshot 2024-11-04 at 7 05 16 AM" src="https://github.com/user-attachments/assets/c9b4eb72-93fd-46d1-ae60-d1ca4ad7378e">

### which network/s did you face the problem on?

Dev

### version

3.15

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
Duplicate: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3573
