### ISSUE TITLE
Live Chat button overlaps with multiple UI elements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#358]
### Description

The live chat button overlaps with the delete deployment button and other elements according to its position on the screen.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/92450a55-bd8e-42bf-9409-3223c37a5b1d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8b3ec1fc-11f1-4040-822d-faee7a33238a)

**Comment by xmonader** [comment]
is that at 100% zoom or not?

**Comment by MohamedElmdary** [comment]
@xmonader depends on the screen size
I have added a bottom padding in the main layout so it won't overlap if u scroll down

**Comment by A-Harby** [comment]
Verified 
A padding was adding to the bottom, giving the live chat icon a good space whatever was the zooming or screen size is.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d242c2ab-382d-432b-892e-2af167c3e2e4)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f394e03f-1100-4b23-8aff-3ad08b7f14c1)
