### ISSUE TITLE
🐞 [Bug]: Idenfy session timeout 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Idenfy session give 30 minutes to the user but after the session time out i tried to refresh and faced this
<img width="1680" alt="Screenshot 2024-11-04 at 7 24 23 AM" src="https://github.com/user-attachments/assets/79b10eaf-215a-4ce9-97c5-04c1c90237ec">

### which network/s did you face the problem on?

Dev

### version

3.15

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by A-Harby** [comment]
This is the intended scenario for the 30-minute duration to verify.
