### ISSUE TITLE
🐞 [Bug]: Kubernetes Manage Workers's button not working

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3594]
### which package/s did you face the problem with?

Dashboard

### What happened?

Kubernetes Manage Worker's button open Manage domains dialog

### Steps To Reproduce

- Go to Kubernetes
- Deploy K8s
- Click on manage workers

### which network/s did you face the problem on?

Dev

### version

a004c8

### Relevant screenshots/screen records

[Screencast from 05-11-24 13:20:26.webm](https://github.com/user-attachments/assets/b5b7b098-1a3e-4c1b-994d-878e5d0f2e6a)

**Comment by samaradel** [comment]
### Work Completed:
Prevent opening manage workers and manage domains from triggering together.

**Comment by A-Harby** [comment]
Verified, Devnet 96e183a.

The manage worker button is working fine again.
![image](https://github.com/user-attachments/assets/06497a9c-e408-4c61-9c79-cfd5d9372b65)

[TC2129 - Add Kubernetes Worker](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4150338)
