### ISSUE TITLE
🐞 [Bug]: MetaMask extension Conflicts with KYC Iframe Render 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#3596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

3 of us tried going through the KYC verification process on both devnet & qanet dashboard. 
It worked for Maxime (Chromium & adblocker)
Didn't work for me (Chrome & both with enabled and disabled adblocker)
Didn't work for Lee (Firefox & both with enabled and disabled adblocker)

All 3 of us are at the office.

### Steps To Reproduce

1. Devnet & qanet
2. Enough TFT balance 
3. Deploy - VM - Verify now

### which network/s did you face the problem on?

QA, DEV

### version

Current  (2.6.0-rc3)

### Twin ID/s

Sabrina qa: 594 dev: 9791 Maxime qa: 595 dev: 7737 Lee qa: 580 dev: 9142

### Relevant screenshots/screen records

![Scherm­afbeelding 2024-11-05 om 14 18 04](https://github.com/user-attachments/assets/e39b6146-f65e-4bff-9d76-c9931a745c40)

https://github.com/user-attachments/assets/1bf8914a-5aea-46ac-a962-cca8dacae74c

### Relevant log output

```console
See screenshot
```

**Comment by sabrinasadik** [comment]
### Sabrina

- Devnet:5HfzhyBMvFEkWTEjhSvGL5gfMdhV2btFrNX6toTRSVUhsJ1H
- QAnet: 5Dtj4gR1qydkoCx4kLbgbEa9RBexAhx6dydARgFJg4eTiSo5

### Maxime 

- Devnet: 5Fn9NhaEZ1ptiDeRfeuBzNSZ5D7ritJXDWcqMwxRwLnpfgPp
- QAnet: 5GnejG345DYmgMsJC5UuTrajnTfWFDznvKtRWzWQGv7WC8nJ

### Lee

- Devnet: 5EACfbtWrDBkJw7uRAd4wpEoaF7vNkTxxZhPziJsKFusDDbn
- QAnet: 5C7a5g8fR5uDnAnsE4qeA8BXoeyx2h6GSzygH8dpt2bokgfv

**Comment by ramezsaeed** [comment]
Just tried now with a new account on devnet & qanet
chrome working fine.

**Comment by sabrinasadik** [comment]
Still not for me

**Comment by ramezsaeed** [comment]
I have this chrome Version 130.0.6723.91 (Official Build) (64-bit)

**Comment by maximevanhees** [comment]
For reference, working for me on:

- Chromium Version 130.0.6723.69 (Official Build) Arch Linux (64-bit)
- Mozilla Firefox 131.0.3

Also working on a Windows machine:
- Google Chrome Versie 130.0.6723.92 (Officiële build) (64-bits)

**Comment by sabrinasadik** [comment]
Works in incognito mode. Question is why?

**Comment by sabrinasadik** [comment]
Blocked by metamask extension

**Comment by sameh-farouk** [comment]
> Blocked by metamask extension

Nice catch! I renamed the issue to reflect the problem better.

**Comment by sameh-farouk** [comment]
@0oM4R Can you check if using `sandbox="allow-scripts"` attribute can help contain MetaMask’s influence within the iframe?
See [here](https://www.w3schools.com/tags/att_iframe_sandbox.asp) also for other sandbox options that could be useful.

**Comment by 0oM4R** [comment]
Issue update: The issue wasn't about  MetaMask alone; any extension that triggers `message` event will have the same issue.
so we add more restriction to the event check to include the status field, if not the event will be ignored.

**Comment by 0oM4R** [comment]
> @0oM4R Can you check if using `sandbox="allow-scripts"` attribute can help contain MetaMask’s influence within the iframe? See [here](https://www.w3schools.com/tags/att_iframe_sandbox.asp) also for other sandbox options that could be useful.

thank you @sameh-farouk I tried you suggestion it worked with metamask only and have some side effects that will lead to bad UI/UX, and many other errors in the console, and the issue still exists with other extensions, so we manged to have more generic solution, to handle any other sources  
![Screenshot from 2024-11-06 13-21-53](https://github.com/user-attachments/assets/47d9e88d-820b-4b97-bbd1-106933242e3d)

**Comment by A-Harby** [comment]
Verified, Devnet 96e183a.

The KYC wasn't working on my device too, except for the incognito option, and now it is working fine after the fix. 
![image](https://github.com/user-attachments/assets/8c9d17b0-3c41-452e-949f-bbb938cef926)

[TC2899 - KYC dashboard integration](https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4410140)

**Comment by ramezsaeed** [comment]
Verified:
- QAnet
- 2.6.0-rc4
