### ISSUE TITLE
Add security link for the user to check before starting the verification

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3599]
https://www.idenfy.com/security/

**Comment by 0oM4R** [comment]
Issue update: 
initialized the dialog, will check the UI with Ehab

**Comment by 0oM4R** [comment]
Issue update: the dialog is ready, changed the flow as well, but I can't test due the KYC dev net [issue](https://github.com/threefoldtech/tf_operations/issues/2902)

**Comment by A-Harby** [comment]
Verified, Devnet 96e183a.

The acceptance term and condition daily were added with the security link in it.
![image](https://github.com/user-attachments/assets/172ddb5a-2a91-4f9f-9b80-fd9b22f2932b)
![image](https://github.com/user-attachments/assets/e1e9e05b-685e-49b5-bd42-af572d71cca3)

A new test case created in KYC: [TC2935 - Accept terms and conditions](https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4413352)

**Comment by A-Harby** [comment]
But this fix introduces a new error where the KYC doesn't open anywhere now except in your profile page only.

Any other page as FullVM gives this error.
![image](https://github.com/user-attachments/assets/5f01f2db-5edf-4ae9-8020-b6715027ed91)

**Comment by khaledyoussef24** [comment]
verified on devnet
Version a9a62b8

![Image](https://github.com/user-attachments/assets/7d77dede-ce5f-4f64-8c98-515a122d5a21)
![Image](https://github.com/user-attachments/assets/de756708-b9af-494b-905e-0e8c71884a61)
![Image](https://github.com/user-attachments/assets/e66f987d-3332-4abd-af75-e2f1cc07cf35)
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4413372)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 96e183a

![Screenshot from 2024-11-11 23-44-03](https://github.com/user-attachments/assets/d30c0c99-be77-4c10-ab39-b027489debb1)

**Comment by ramezsaeed** [comment]
The verify button enter infinite loop when cancel the terms and condition from the deploy page.

- Devnet
- 96e183a

### Test steps
- Create a new account
- Fund it with 100 TFT
- Go to deploy page --> deploy micro VM
- press verify button
- in the dialog for terms and conditions check the checkbox.
- press the cancel button
- NOW: you will notice that the verify button keep rotating and get into infinite loop.


### logs
[dashboard.log](https://github.com/user-attachments/files/17708484/dashboard.log)

### Screenshots
![Screenshot from 2024-11-11 23-51-23](https://github.com/user-attachments/assets/f57ecee7-ef96-45c7-a7be-4c6cde477810)
![Screenshot from 2024-11-11 23-54-49](https://github.com/user-attachments/assets/506fee27-9f87-4932-9ac2-0060391f63ab)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 7f9c4df
