### ISSUE TITLE
🐞 [Bug]: Grid3_Client_TS Test Suite issues

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3609]
### Test Cases:

- [x] [TC1159](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33387741)
- [x] [TC1160](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?selected=33387742)
- [x] [TC769](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387749)
- [x] [TC770](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387750)
- [x] [TC776](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387752)
- [x] [TC777](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387753)
- [x] [TC2620](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248)
- [x] [TC2626](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387760)
- [x] [TC2741](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387761)
- [x] [TC772](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387762)
- [x] [TC773](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387763)
- [x] [TC774](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387764)
- [x] [TC775](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387765)
- [x] [TC1420](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387766)
- [x] [TC1421](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387767)
- [x] [TC1422](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387768)
- [x] [TC1423](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387769)
- [x] [TC1424](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387770)
- [x] [TC1425](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387771)
- [x] [TC898](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387772)
- [x] [TC899](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387773)
- [x] [TC900](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387774)
- [x] [TC901](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387775)
- [x] [TC902](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387776)
- [x] [TC903](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387777)
- [x] [TC923](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387778)
- [x] [TC1426](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387780)
- [x] [TC1427](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387781)
- [x] [TC1428](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387782)
- [x] [TC1227](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387783)

### Which network/s did you face the problem on?

Dev

### version

a004c8

**Comment by atefnazmy** [comment]
- All links are currently up to date.
