### ISSUE TITLE
🐞 [Bug]: Cannot delete domains

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3613]
### which package/s did you face the problem with?

Dashboard

### What happened?

When trying to delete domains I got `Cannot read properties of undefined (reading 'toLowerCase')`

### which network/s did you face the problem on?

Dev

### version

a004c8

### Relevant screenshots/screen records

[Screencast from 10-11-24 18:59:43.webm](https://github.com/user-attachments/assets/9fa33b71-3ecc-4dc8-aab5-02e4d82d475f)

### Relevant log output

```console
N/A
```

**Comment by ramezsaeed** [comment]
Can't reproduce it, please re-open if u got it again.

**Comment by atefnazmy** [comment]
- Verified on Testnet
- Version 2.6.0
- The Domain has been Deleted without any error message.


https://github.com/user-attachments/assets/7db555cd-b9e6-43d9-be35-94e77385b10a

[Testcase](https://app.testlodge.com/a/26076/projects/40893/runs/726768?tab=2#executed_case_31541584)
