### ISSUE TITLE
🐞 [Bug]: Deposit TFT not working properly

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

I tried to deposit a TFT from my tf connect app via the QR code. Although the amount got deducted, the balance was not reflected in the Dashboard.

### which network/s did you face the problem on?

Main

### version

2.5.2

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/8a2d517f-c8ba-453f-8f32-eb5fbf64c0a9)

### Relevant log output

```console
-
```

**Comment by 0oM4R** [comment]
![Image](https://github.com/user-attachments/assets/4f3c192e-c4cf-41f8-80bb-64479edc5154)
works fine with me on test and main net

**Comment by atefnazmy** [comment]
- Verified on Mainnet
- version: 2.5.2
- The transaction has been done successfully

![trans](https://github.com/user-attachments/assets/d4c611fd-46e1-464c-a1c9-09f18f07e1fe)

[Testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150411)
