### ISSUE TITLE
🐞 [Bug]: Node details empty network speed box

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

checking node 11 network speed the dialog frozen after few seconds of loading 
https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254561

### Steps To Reproduce

1. go to dashboard, node finder
2. node 11

### which network/s did you face the problem on?

Dev

### version

2.6.0-rc4

### Twin ID/s

800

### Node ID/s

11

### Relevant screenshots/screen records

![Screenshot from 2024-11-11 19-23-49](https://github.com/user-attachments/assets/dca41c6b-f43b-48e6-8918-08303055c079)

### Relevant log output

```console
all logs about sentry
```

**Comment by 0oM4R** [comment]
handled errors in network speed box by showing errror alert

**Comment by atefnazmy** [comment]
- Verified on Dev
- Version: 4e2fc0b
- The Network speed box for (Node 11) is not empty and it is showing error alert

![Image](https://github.com/user-attachments/assets/8ba1b289-412f-4ec3-b1b7-0a1840419aa9)
