### ISSUE TITLE
🐞 [Bug]: VM: Deploy a VM With Mycelium test case fails

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

all VM Deployment test cases are passed except ```Deploy a VM With Mycelium ```.

### Steps To Reproduce

1. Go to Grid Client repo
2. run `yarn test tests/modules/vm.test.ts`
- [Test case: TC2847](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387785)

### which network/s did you face the problem on?

Dev

### version

a004c8

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/22c0e6a8-63d6-4852-8d53-04085ad1d9e1)

### Relevant log output

```console
N/A
```

**Comment by ramezsaeed** [comment]
@A-Harby fix the test steps please

**Comment by A-Harby** [comment]
Fixed, updated the test case, and tested.
Also, the readme had that note.
![image](https://github.com/user-attachments/assets/2cdd49fb-8f15-4644-8fbe-71ffcbe7a176)
but case was updated.
https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256248&selected=33387785
