### ISSUE TITLE
🐞 [Bug]: Copy btn active on details tab deployment dialog

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the copy btn is active on the details tab of the deployment dialog 
copy btn should not be active in details tab 

### Steps To Reproduce

1. deploy any solution
2. go to details tab of deployment dialog that opens up after solution is deployed 
3. click copy
4. observe json copied to clipboard

### which network/s did you face the problem on?

Dev

### version

96e183a17f9ad9e662e8ba89dfa2da89d00b7a9e

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/9f902cbb-b669-459b-bd03-3831439425d3)

### Relevant log output

```console
n/a
```

**Comment by ramezsaeed** [comment]
Hide the copy button in details tab, and make it work only in Json tab.

**Comment by atefnazmy** [comment]
Verified on Dev
version: 4e2fc0b
- The Copy btn is still active on details tab.

![Image](https://github.com/user-attachments/assets/8538c0db-e501-4e2b-ba49-acd2933558fe)

**Comment by ramezsaeed** [comment]
- DEvnet
- 4e2fc0b
- copy button still there

![Screenshot from 2024-11-28 16-41-16](https://github.com/user-attachments/assets/b4a96f92-be66-49b0-843a-be121f9e9850)

**Comment by amiraabouhadid** [comment]
@ramezsaeed @atefnazmy this is because prs in 3.16 are merged onto development_2.7 branch which has not been merged into development yet. Please verify on development_2.7 branch .

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- The Copy button has been removed from Details Tab and only active on JSON Tab.

![Screenshot From 2024-12-18 11-39-07](https://github.com/user-attachments/assets/8049580c-934d-4e0b-9654-0595a9e87ceb)
![Screenshot From 2024-12-18 11-40-14](https://github.com/user-attachments/assets/df4e826d-50aa-4b09-93c5-89805256ed27)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422333#case_4150330
