### ISSUE TITLE
🐞 [Bug]: Backends column should not be sortable in deployment table 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

the backends  column should not be sortable in deployment table 

### Steps To Reproduce

1. deploy a domains solution or attach a domain to a vm
2. try to click sortable arrow on backends column in table
3. observe order of entries in table not changing 

### which network/s did you face the problem on?

Dev

### version

96e183a17f9ad9e662e8ba89dfa2da89d00b7a9e

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/4ea26211-3754-4ab1-8270-a7a6f0604cec)

### Relevant log output

```console
n/a
```

**Comment by atefnazmy** [comment]
- The issue is still reproducible as the Backends column can be sortable.

https://github.com/user-attachments/assets/67ff92b8-0096-4b5c-969e-a8251f62a5e8

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- Currently Domains' Backends column is not sortable.


https://github.com/user-attachments/assets/3463d90f-5c23-4a7d-bf42-749269e9d2e9


#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=455301#case_4413834
