### ISSUE TITLE
🐞 [Bug]: Save button not disabled after setting extra fee

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Save button not disabled after setting extra fee.

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242679&user_id=170529

### Steps To Reproduce

- Click on Your Farms from the sidebar then Your Farms
- In your nodes table, click on the set extra fee icon
- Enter your fee and Save
- Close the dialogue & open it again

### which network/s did you face the problem on?

Dev

### version

96e183a

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/028fc113-e3d3-4f2d-887c-63a68538058b)

### Relevant log output

```console
-
```

**Comment by atefnazmy** [comment]
-Verified on Dev,
-Version: 4e2fc0b
-The "Save" button is now properly disabled after the modifications are successfully executed.


https://github.com/user-attachments/assets/4e4027c2-b16f-4b72-a431-61cc07c5d87a

#### Related Link:
https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242679&user_id=170529
