### ISSUE TITLE
🐞 [Bug]: Domain in public config accepts wrong formats

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Domain field accepts wrong formats.

https://app.testlodge.com/a/26076/projects/40893/runs/757631/run?selected=33242682&user_id=170529

### Steps To Reproduce

- From the sidebar, click on Your Farms then Your Farms.
- In the Your Nodes table Click on the Add Public Config Icon for any of the nodes.
- Try entering the following formats in domain field:
    - mydomain.unknown
    - my@domain.com

### which network/s did you face the problem on?

Dev

### version

96e183a

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
need to add the same domain validator used in caprover.

**Comment by atefnazmy** [comment]
- Devnet
- 4e2fc0b
- The  public config field for domain has no validation yet.


https://github.com/user-attachments/assets/c7c74e2d-0f17-48df-8127-4ae569c04149

**Comment by maayarosama** [comment]
> * mydomain.unknown

mydomain.unknown is an acceptable case

**Comment by atefnazmy** [comment]
- The domain field is currently behaving as a required field, even though it is supposed to be optional.

![Screenshot From 2024-12-18 15-24-16](https://github.com/user-attachments/assets/a52cdb7c-4494-45e9-970a-cc2cee7001e7)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: f0f91d9
- The domain field currently doesn't accept the wrong format,  which is defined as optional, and there is no validation error if it is missing.

![Screenshot From 2024-12-30 07-48-09](https://github.com/user-attachments/assets/33c1d42d-5262-4de3-861d-c602045c3111)

https://github.com/user-attachments/assets/48fb9e82-2de8-43f9-8485-7723d4555af2

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426668#case_4150427
