### ISSUE TITLE
🐞 [Bug]: Node Finder: change `Up and Standby` filter to `Up or Standby` 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The filter naming is incorrect because you can't have a node as up and as standby in the same time

### Steps To Reproduce

- Go to Dashboard
- Deploy
- Node finder
- Check node status filter you should see `Up and Standby` while it should be `Up or Standby`

### which network/s did you face the problem on?

Main

### version

2.5

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by atefnazmy** [comment]
- Verified on QA,
- Version: 2.6.2
- The (Up and Standby) Node status filter has been changed to (Up or Standby)

![Image](https://github.com/user-attachments/assets/7fecc764-2544-4e82-89a9-00c86a72c2b1)

#### Related link:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150464

**Comment by ramezsaeed** [comment]
verified:
- Testnet
- 2.6.2

![image](https://github.com/user-attachments/assets/75d1566c-61b5-4ca7-81e9-98b3569e3519)
