### ISSUE TITLE
🐞 [Bug]: Domains page: the order of the IP and Port

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3641]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The form shows the port then the IP while it typically should be ip then port

### Steps To Reproduce

Open the dashboard and then go to the domains page

### which network/s did you face the problem on?

Main

### version

2.6.0

### Twin ID/s

6

### Node ID/s

-

### Farm ID/s

-

### Contract ID/s

-

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/b00bae79-d982-49a3-addb-281b02119887)

### Relevant log output

```console
-
```

**Comment by khaledyoussef24** [comment]
verified on devnet
Version bf66d67

order is now changed
![Image](https://github.com/user-attachments/assets/9af87d01-ca4c-457c-94d7-3dda0313b602)
