### ISSUE TITLE
🐞 [Bug]: Fix profile card spacing

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The phrase "Scan the QR code using [ThreeFold Connect ](https://manual.grid.tf//documentation/threefold_token/storing_tft/tf_connect_app.html)to fund your account" has no space after it. 

### Steps To Reproduce

1. Login to the dashboard
2. Go to profile

### which network/s did you face the problem on?

Dev

### version

2.6.0

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/b43ba34f-9129-472c-af37-b8cf41c1fdc5)

### Relevant log output

```console
-
```

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: 4e2fc0b
- The profile card spacing has been fixed.

![Image](https://github.com/user-attachments/assets/d752086e-081d-47d8-9747-18352eba476f)

**Comment by ramezsaeed** [comment]
Verified:
 - Devnet
 - 4e2fc0b

![Screenshot from 2024-11-28 16-33-57](https://github.com/user-attachments/assets/2f00a11e-58c3-4a03-a99b-4d9c4c9dd4ba)
