### ISSUE TITLE
🐞 [Bug]: Dashboard manual link redirects to connect docs

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Wrong URL.

### Steps To Reproduce

1. Go to Dashboard
2. Open manual link in connect tab

### which network/s did you face the problem on?

Dev

### version

2.6.0

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/7484630a-7570-4ba8-b689-ec7cf80d0559)

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
the correct link: https://www.manual.grid.tf/documentation/dashboard/wallet_connector.html

**Comment by ramezsaeed** [comment]
Also there is an extra slash in the manual link for All  Network other than staging:

Mainnet
![image](https://github.com/user-attachments/assets/5b493d24-13d7-41b7-9fd0-b3e1d77909bd)

Testnet
![image](https://github.com/user-attachments/assets/716c203d-c665-4b14-9403-dd9372e0fc15)

QAnet
![image](https://github.com/user-attachments/assets/3c07164a-26b4-415e-8966-77572f0f20db)


Staging
![Screenshot from 2024-11-19 17-50-16](https://github.com/user-attachments/assets/6a713330-e06e-4c33-9608-8de9b29cc58d)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: 4e2fc0b
-  The manual link works as expected and redirects to https://www.manual.grid.tf/documentation/dashboard/wallet_connector.html

![Image](https://github.com/user-attachments/assets/c8e55abb-41b5-4bfe-9d5f-92a003da060c)
