### ISSUE TITLE
Change Dashboard title from ThreeFold to ThreeFold Cloud

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/tfgrid-sdk-ts#3645]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

- With v4 on its way, we want to state clearly that threefold v3 is a threefold cloud platform
- ETA: as soon as possible to align with V4 communication plans

### Describe the solution you'd like

- Update ThreeFold to ThreeFold Cloud on the Dashboard
- e.g. 
![image](https://github.com/user-attachments/assets/b7e3c24f-55a0-45be-bbde-d9e96f67a5e9)
- change this to THREEFOLD CLOUD
- e.g.
![image](https://github.com/user-attachments/assets/4e914633-90f2-42ad-8b09-f02c5d5ae933)
- change this to THREEFOLD CLOUD
- e.g.
![image](https://github.com/user-attachments/assets/1549cb70-d119-4d21-ab4c-1fe035f3ef5c)

- Change to:
"Anything that runs on Linux can run on the ThreeFold Cloud – with more security, more sustainably, and in true decentralization. The ThreeFold Cloud can support workloads from Blockchain to Web2 to Web3 to IoT and Metaverse and more."
- Learn About the ThreeFold Cloud (instead of Grid)

# Notes

Also, is it possible to have the dashboard accessible to cloud.threefold.io? @xmonader what do you think? See here for the reasoning behind this: https://git.ourworld.tf/tfgrid/circle_promotion/issues/318

**Comment by mik-tf** [comment]
# Update

- We will have this also for the manual (ThreeFold Cloud Manual, instead of ThreeFold Manual): https://github.com/threefoldtech/info_grid/pull/680

**Comment by xmonader** [comment]
This goes to blocked until there's a ticket with stakeholders approvals for UX changes.

**Comment by mik-tf** [comment]
Let's close this and see if stakeholders agree later. I think it is not a priority after discussion with Thabet.
