### ISSUE TITLE
🐞 [Bug]: Google Play Button Style in Deposit Dialog is Distorted

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

![image](https://github.com/user-attachments/assets/a7d14062-07e8-4c3f-aa9d-111f9d29ca9f)

### Steps To Reproduce

1. Login
2. Go to Bridge then open deposit dialogue

### which network/s did you face the problem on?

Dev

### version

bf66d67

### Relevant screenshots/screen records

-

### Relevant log output

```console
-
```

**Comment by ramezsaeed** [comment]
Need to be fixed in light ode too.

![Screenshot from 2024-11-19 11-18-31](https://github.com/user-attachments/assets/50b60b26-a4ac-4e7b-9cc4-44770f1c8604)



check if we can unify the qr code and buttons in one place.

**Comment by amiraabouhadid** [comment]
fixed google play btn in dark mode, added btns in light mode, extracted qr and btns into a separate component. will investigate why qr code shrinks in light mode

**Comment by amiraabouhadid** [comment]
qr code was fine, it was a margin from light mode btn which has been removed now. No adequate google play store light btn was found so reverted back to using dark mode btns for both themes

**Comment by amiraabouhadid** [comment]
used slot instead of passed msg prop to QRPlayStore component. integrated component in twin view

**Comment by khaledyoussef24** [comment]
verified on devnet
Version c2d6060

<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/1ca8930b-90a5-472c-b0f4-05c65579badd" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/2f7e2f52-f2e0-4f0a-9e2d-049d934dd6f3" />

[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4150411)
