### ISSUE TITLE
🐞 [Bug]: Dashboard Test Suite

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#3649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

- [No.456 - Test case: TC2631](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245810)
- [No.478 - Test case: TC2316](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245832)
- [No.476 - Test case: TC2312](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245830)
- [No.474 - Test case: TC2314](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245828)
- [No.458 - Test case: TC2686](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245812)
- [No.456 - Test case: TC2631](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245810)

### which network/s did you face the problem on?

Dev

### version

bf66d67

### Relevant screenshots/screen records

N/A

### Relevant log output

```console
N/A
```

**Comment by maayarosama** [comment]
- [No.519 - Test case: TC2126](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245873)
- [No.530 - Test case: TC2461](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245884)
- [No.531 - Test case: TC2167](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245885)
- [No.532 - Test case: TC2168](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245886)
- [No.535 - Test case: TC2674](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245889)

**Comment by maayarosama** [comment]
- [No.541 - Test case: TC2734](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245895)
- [No.546 - Test case: TC2169](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245900)
- [No.554 - Test case: TC2171](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245908)

**Comment by maayarosama** [comment]
- [No.599 - Test case: TC2808](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245953)
- [No.601 - Test case: TC2663](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245955)
- [No.607 - Test case: TC2667](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1250259&selected=33245961)

**Comment by 0oM4R** [comment]
- [No.739 - Test case: TC2162](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254581)
- [No.740 - Test case: TC2459](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254582)
- [No.742 - Test case: TC2163](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254584)
- [No.743 - Test case: TC2164](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254585)
- [No.745 - Test case: TC2314](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254587)
- [No.746 - Test case: TC2311](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254588)
- [No.747 - Test case: TC2312](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254589)
- [No.749 - Test case: TC2316](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254591)
- [No.750 - Test case: TC2449](https://app.testlodge.com/a/26076/projects/40893/runs/757884/run?run_suite_id=1250709&selected=33254592)

**Comment by khaledyoussef24** [comment]
Done All tests are edited and fixed

**Comment by khaledyoussef24** [comment]
@ramezsaeed shall we close or leave it if anyone may add more testcases?

**Comment by ramezsaeed** [comment]
will close and if anyone have issue in the same testsuite will open a new one.
