### ISSUE TITLE
🐞 [Bug]: TF Grid Proxy test suite issues

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3660]
### which package/s did you face the problem with?

gridproxy_client

### What happened?

- [ ] No.1432 - [Test case: TC881](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256636&selected=33395279)
- [ ] No.1446 - [Test case: TC879](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256636&selected=33395293)
- [ ] No.1450 - [Test case: TC872](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256636&selected=33395297)
- [ ] No.1461 - [Test case: TC1285](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256636&selected=33395308)
- [ ] No.1469 - [Test case: TC2330](https://app.testlodge.com/a/26076/projects/40893/runs/757865/run?run_suite_id=1256636&selected=33395316)

**Comment by khaledyoussef24** [comment]
Done and fixed
