### ISSUE TITLE
🐞 [Bug]: misleading message while withdraw from the bridge page "Blocked Address"

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#3667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When try to withdraw TFTs from the bridge page, 
I used by mistake the bridge stellar address; and I got validation message declares that the address is blocked without saying anything more which was very confusing for me and had to ask why this address is Blocked.
so what should be done here:
    - add info button about which exact address the user should use and maybe add how to get it from the connect app.
    - when use this wrong bridge address; the message should be more clears that this is a theefold bridge only.

### Steps To Reproduce

- open dashboard
- login
- go to bridge page under Tfchain
- select Deposit button
- copy stellar address shown the close.
- select withdraw button
- paste the stellar address you copied in the address field

-- now the message is there "Blocked Address" without declaring why this is blocked.

### which network/s did you face the problem on?

Dev, QA, Test, Main

### version

2.6.0

### Relevant screenshots/screen records

![Screenshot from 2024-11-21 17-04-54](https://github.com/user-attachments/assets/b6133ef4-eccc-4b7a-90a2-20bba42619c3)

![Screenshot from 2024-11-21 15-11-22](https://github.com/user-attachments/assets/501a1a7f-af27-4e7b-88dc-b48e7398d3c3)

![Screenshot from 2024-11-21 15-02-52](https://github.com/user-attachments/assets/d39291da-5ed7-4c70-b4f8-73e3a372a4a0)
![Screenshot from 2024-11-21 15-02-19](https://github.com/user-attachments/assets/724b4358-bb82-4d29-8111-d38ae1e75ae7)
![Screenshot from 2024-11-21 14-58-00](https://github.com/user-attachments/assets/4c8b6ae6-a52f-4300-be60-44083bc2d0ca)

### Relevant log output

```console
--
```

**Comment by amiraabouhadid** [comment]
static blocked addresses were found which are not the correct bridge address, input address is now checked against env var for bridge tft address instead. Verification err msg is updated to explain why address is blocked.

**Comment by khaledyoussef24** [comment]
verify on devnet
Version c2d6060

the message is more clear now
<img width="393" alt="Image" src="https://github.com/user-attachments/assets/ee54c24c-24ed-46a2-897b-f53322718511" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/6b9a6767-b7b0-47ac-8315-46a299592daf" />
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4431579)
