### ISSUE TITLE
🐞 [Bug]: Failed to load Deployments while listing domains

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

When the page is loaded it fails to load domains with alert `Failed to load Deployments: TypeError: Cannot read properties of undefined (reading 'workloads')`

### Steps To Reproduce

- Go to Domains page
- Try to list domains

### which network/s did you face the problem on?

Dev

### version

2eb9e8703c1aff520418902f0bb6c134e02035db

### Relevant screenshots/screen records

[Screencast from 24-11-24 11:38:51.webm](https://github.com/user-attachments/assets/26ca52a1-3052-43c0-812a-88924fee251b)

### Relevant log output

```console
N/A
```

**Comment by amiraabouhadid** [comment]
works right after deployment 
![Image](https://github.com/user-attachments/assets/3aba9eb9-f61a-4271-bb79-2cf9e8741536)

**Comment by amiraabouhadid** [comment]
works after navigating to another page then back to domains page
![Image](https://github.com/user-attachments/assets/3a565a05-15a3-4e4c-8b9c-6ca19e531203)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- All deployments are listed as expected.

![domain_list](https://github.com/user-attachments/assets/93f6879a-f4b5-4e34-9473-2a9dd7b94481)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=455301#case_4413834
