### ISSUE TITLE
Apply KYC on farmers

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3678]
### Is your feature request related to a problem? Please describe

Farmers should go through KYC process if they want to interact with any farming features

### Describe the solution you'd like

Farmers should go through KYC process if they want to interact with any farming features

**Comment by ehab-hassan** [comment]
option 1

![Frame 301](https://github.com/user-attachments/assets/3fd1fe55-fecd-4298-92d4-2ca2ba46e721)
![Frame 302](https://github.com/user-attachments/assets/9c738bcd-9d43-42c1-91ba-4d61382fbf8a)

option 2
![Frame 303](https://github.com/user-attachments/assets/13f04429-2c2e-4790-941b-47fbd707a1a3)
![Frame 304](https://github.com/user-attachments/assets/8b4935d7-3f80-4b81-9a42-46e9a252a21c)

**Comment by ehab-hassan** [comment]
WIP
Waiting for verification at the design

**Comment by ehab-hassan** [comment]
Ok We agreed on the red color 

To preview light and dark modes click on an image at Figma
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?node-id=1494-2832&t=cDL2ZXkzDQjEFLxH-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=124%3A196

![kyc3](https://github.com/user-attachments/assets/2827e9ae-2ba1-4f6c-898c-15333b6ecdd5)

message alert 
"To start farming, KYC verification is required. Please complete the process to proceed"

**Comment by maayarosama** [comment]
### Work Completed:
- Added Kyc Verifier component in your farms page
- Added an alert and blocked interacting with farms in case kyc wasn't verified

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: f0f91d9
- KYC is currently applied on farmers.

![Screenshot From 2024-12-30 06-58-28](https://github.com/user-attachments/assets/eb51d7e6-d1ff-48a2-8c5b-f30acce0eb6f)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435042

**Comment by ramezsaeed** [comment]
feature coverage on testlodge:
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435692
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435693
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435694
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435695
- https://app.testlodge.com/a/26076/projects/40893/suites/246368?expand_section=455595#case_4435696
