### ISSUE TITLE
🐞 [Bug]: Auto node selection failed to satisfy required capacity

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Was deploying K8s with the default resources and it doesn't select/scroll to the selected VM
![image](https://github.com/user-attachments/assets/90626b87-547e-489f-b106-9bb4738be9cd)
and when deployed node `153` was the selected one and it gives
![image](https://github.com/user-attachments/assets/da6780bd-de20-4bd7-add6-e28dc32ac45c)
 

### Steps To Reproduce

- Go to K8s solution
- Deploy an instance

### which network/s did you face the problem on?

Dev

### version

288faa0dd74fa0b7bb63fa30bd9b52284e3e1302

### Node ID/s

153

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/d4848ac6-6bfb-4db9-91e7-4937e80fdf93)

### Relevant log output

```console
WorkloadDeployError: Failed to deploy zmachine with name mrm7gb3 on node 153 due to: failed to satisfy required capacity: cannot fulfil required memory size 4294967296 bytes out of usable 3951718400 bytes.
```

**Comment by maayarosama** [comment]
Happened with me on node 179 
![Screenshot from 2024-11-21 16-23-48](https://github.com/user-attachments/assets/dd594da6-a5ce-4ae8-948b-433ce4040aff)

**Comment by 0oM4R** [comment]
![image](https://github.com/user-attachments/assets/efef79f4-b24b-4c8a-b955-54adc2d088c6)
while deploying master without workers

**Comment by maayarosama** [comment]
Can't reproduce.
- I tried deploying on more than 5 random nodes and all passed
- Node 179 wasn't a valid node to deploy on
-  I tried to deploy on node 153:
    - Master without workers and it passed
    - Adding workers and it passed
    - Master and worker at the same time and it passed

**Comment by khaledyoussef24** [comment]
deployed more than 8 times and could not produce the same issue again.
will open again if i could produce it.
