### ISSUE TITLE
🐞 [Bug]: Caprover cost column has an empty value

### ISSUE THREAD

**Issue by samaradel** [threefoldtech/tfgrid-sdk-ts#3682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

After deploying `Caprover` instance while reproducing [#3614](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3614) issue the cost column had an empty value.
🐞 [Bug]: Caprover cost column has an empty value

### which network/s did you face the problem on?

Dev

### version

6b81cd4b5fa2e78fe3b0e35bf18a33ab8207ca02

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/f92ded58-a91a-4a27-8bfb-0408d47f379d)

### Relevant log output

```console
N/A
```

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- The cost column is not empty and display a valid value.

![cost](https://github.com/user-attachments/assets/a91ad74f-720a-42f4-96f7-1947e57c2ed6)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=429347#case_4164911
