### ISSUE TITLE
🐞 [Bug]: Down nodes shouldn't have `rentable` chip

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#3692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Down nodes have the rentable chip while the user can't rent the node.

### Steps To Reproduce

1- Go to node finder
2- Check the down nodes

### which network/s did you face the problem on?

Main

### version

2.6.0

### Twin ID/s

1061

### Node ID/s

865

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/928a4c9d-7f0e-4e86-98ba-865cb554649c)

### Relevant log output

```console
-
```

**Comment by atefnazmy** [comment]
- Still reproducible on Dev.
- Version: c27924c
![Screenshot From 2024-12-15 12-28-47](https://github.com/user-attachments/assets/1907faf7-06d6-4374-90a5-cdb246c62da6)

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c3bfded
- Currently the Down nodes have no rentable chip.

![Screenshot From 2024-12-18 14-09-01](https://github.com/user-attachments/assets/029e0cde-3eaa-4d70-bd32-00b2c8e48ab8)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4429582
