### ISSUE TITLE
🐞 [Bug]: TFT Minting Process URL gives 404

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#3699]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

Check TFT minting Process URL.

### which network/s did you face the problem on?

Main

### version

2.6.0

### Relevant screenshots/screen records

![image](https://github.com/user-attachments/assets/62dfb2a5-7e29-48c8-af26-7f7d66e1e337)

![image](https://github.com/user-attachments/assets/f4d4336b-9fcf-4660-b0b0-05e5a1d9fc5a)

### Relevant log output

```console
-
```

**Comment by xmonader** [comment]
@Mik-TF  please create a PR for the changes happened to the links https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/manual.ts

**Comment by mik-tf** [comment]
@xmonader 

Done. As written, we need to make sure the info_grid PR is merged before: https://github.com/threefoldtech/info_grid/pull/699

I hope all's good. Lmk if I need to adjust anything. Thanks.

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: c27924c
- The TFT minting process URL works fine. 

https://github.com/user-attachments/assets/2a707a3e-bf1e-4903-8ab3-f47daf6548d8


#### Related Link
- https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4153425
