### ISSUE TITLE
Make error messages more clear 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#37]
Error messages needs to be more clear 
![Screenshot from 2023-04-03 12-06-25](https://user-images.githubusercontent.com/56790126/229482471-21069257-7ff1-4fb5-92e0-f562a8db3b34.png)

**Comment by 0oM4R** [comment]
@amiraabouhadid  any steps to reproduce this error ?

**Comment by Mahmoud-Emad** [comment]
Should be improved in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/198

**Comment by A-Harby** [comment]
Verified, Changes in the error message 
![image](https://user-images.githubusercontent.com/109473873/235351177-32303b01-0704-48fc-8df4-8e5754df7589.png)
Screen will be added once error reproduce.

**Comment by A-Harby** [comment]
Weblets Devnet, version 49a9c82 .
Same message error was displayed.
![image](https://user-images.githubusercontent.com/109473873/235618254-01cb8cbc-51b7-4dd6-b730-a7a97598b70f.png)

**Comment by Mahmoud-Emad** [comment]
This wants a release, once the playground get released it'll work.
