### ISSUE TITLE
Node finder: add refresh button 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3700]
### Which package/s are you suggesting this feature for?

Dashboard

### Is your feature request related to a problem? Please describe

While filtering nodes, I need to refresh the current page with the same filters, as we may have delay to reflect some extrinsics like delete rent contract 

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/6660fa97-c065-48da-98f2-79201b26cf16)

add referesh button to the side of clear and apply or replace the apply with refresh if it is disabled

**Comment by ramezsaeed** [comment]
we can replace the apply button with refresh button when the apply button is disabled.

**Comment by samaradel** [comment]
### Work Completed:
Check if the filter forms are valid or changed to apply the refresh button.

**Comment by khaledyoussef24** [comment]
verified on devnet
Version c2d6060

refresh is now added to the node finder
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/7b47bf37-ce60-4046-a685-7246469a1570" />
<img width="122" alt="Image" src="https://github.com/user-attachments/assets/cce9709a-a0ce-401e-82a6-a7f3806f6a9d" />
<img width="1680" alt="Image" src="https://github.com/user-attachments/assets/3b59413c-e147-4407-ac7e-3a85bd2c8d3c" />
[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4431578)

**Comment by khaledyoussef24** [comment]
[testcase 2
](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4434548)
[test case 3
](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4434549)
[testcase 4
](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4434550)

[testcase 5](https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4434551)
