### ISSUE TITLE
Remove HDD reporting in the stats views

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#3709]
### Is your feature request related to a problem? Please describe

Remove HDD reporting in the stats views

### Describe the solution you'd like

Remove HDD reporting in the stats views

**Comment by atefnazmy** [comment]
- Verified on QA,
- Version: 2.6.2
- HDD reporting has been removed in the stats view

![Image](https://github.com/user-attachments/assets/8c38a1ad-d3cc-4949-b7dc-13bc350e5abe)


#### Related Link:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4150456

**Comment by 0oM4R** [comment]
we did small update to show the ssd capacity to be like "18,000,333 GB"

**Comment by atefnazmy** [comment]
- Verified on Mainnet.
- version: 2.6.3

- Currently SSD capacity format is changed to be like "7,376,570 GB"

![Screenshot From 2024-12-11 13-51-59](https://github.com/user-attachments/assets/d376889f-c83a-4ca5-a8cb-e82c8f51655e)

#### Related Link:
https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426660#case_4150456
