### ISSUE TITLE
Mismatch in K8S deployment name

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#371]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/3dd50c1a-4d83-4584-9826-7aaab3207728)

**Comment by A-Harby** [comment]
Verified playground Devnet, 861c5f8.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b67bf6f2-1bd6-4aa3-89d5-3873fa82ec58)
