### ISSUE TITLE
🐞 [Bug]: Test suite: TF Grid Proxy

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/tfgrid-sdk-ts#3712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

gridproxy_client

### Outdated Tests:
- [No.702 - Test case: TC877](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654141)

### which network/s did you face the problem on?

Test

### version

N/A

### Relevant screenshots/screen records

N/A

### Relevant log output

```console
N/A
```

**Comment by maayarosama** [comment]
- [No.703 - Test case: TC884](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654142)
- [No.704 - Test case: TC878](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654143)
- [No.705 - Test case: TC882](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654144)
- [No.711 - Test case: TC883](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654150)
- [No.714 - Test case: TC892](https://app.testlodge.com/a/26076/projects/40893/runs/757665/run?run_suite_id=1267179&selected=33654153)

**Comment by atefnazmy** [comment]
all Test-Cases were updated.
