### ISSUE TITLE
🐞 [Bug]: Grid client tests are failing

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#3716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

automated grid clients tests are failing
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/12217621944/job/34082114516
Test Suites: 7 failed, 2 skipped, 22 passed, 29 of 31 total
Tests:       11 failed, 5 skipped, 97 passed, 113 total
 FAIL  tests/modules/zmount.test.ts
 FAIL  tests/modules/currency.test.ts 
 FAIL  tests/modules/vm.test.ts
 FAIL  tests/modules/qsfs.test.ts 

### which network/s did you face the problem on?

Dev

### version

2.6.1

### Relevant screenshots/screen records

.

### Relevant log output

```console
.
```

**Comment by ramezsaeed** [comment]
Duplicate: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/3711
