### ISSUE TITLE
🐞 [Bug]: Do we still need to run gridclient 2.5.2 like manual say for mainnet

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#3720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

grid_client

### What happened?

In grid client readme file still indicating to use version 2.5.2 for qa, test, and mainnet

### Steps To Reproduce

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/README.md

### which network/s did you face the problem on?

QA, Test, Main

### version

2.6.0

### Relevant screenshots/screen records

![Screenshot from 2024-12-08 15-44-48](https://github.com/user-attachments/assets/26f08a32-224b-4816-b649-0ed2e31bf306)

### Relevant log output

```console
--
```

**Comment by ramezsaeed** [comment]
Please also update the version in grid nightly workflow.

**Comment by khaledyoussef24** [comment]
verified 
Version c2d6060

the grid clients tests now runs on <img width="381" alt="Image" src="https://github.com/user-attachments/assets/5365ad51-5474-44da-a27f-9670556c8bb2" />
<img width="516" alt="Image" src="https://github.com/user-attachments/assets/429a3f97-ea34-4ccd-b3d7-1bcfaa7f6c36" />
