### ISSUE TITLE
🐞 [Bug]: Stats url always pointing to the main net stats

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#3722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

on initializing the dashboard, the `window.env.STATS_URL` is not defined, so we fall back to the hardcoded value of main net stats 
this behavior was working fine before supporting stats monitoring.
now before pinging or setting the url, the store initializes the stats url with main net stats `https://stats.grid.tf/`

we should have url initialization in the store, we can pass the url in the function of useStatsStore or have initialize function that handle that 

also we need to unify the stats url to be called from env whatever the case is 

### Steps To Reproduce

1. open dashboard and check logs 
2. you will find the provided stats pinged.
3.  one of the stats calls will call main net url

### which network/s did you face the problem on?

Dev

### version

2.6.2

### Relevant screenshots/screen records

<img width="832" alt="image" src="https://github.com/user-attachments/assets/167424ef-92f7-4edb-a8b7-3915a1bbe637">

### Relevant log output

```console
.
```

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: 6fb2ab7
- The stats URL points to the correct endpoint for testnet, devnet, or mainnet.

![stat](https://github.com/user-attachments/assets/f64be1e8-b477-4dd2-a89c-e0bd1c183fff)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/suites/211680?expand_section=354530#case_3676886
