### ISSUE TITLE
🐞 [Bug]: colors are not visible in live and operational section in landing page light mode

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtech/tfgrid-sdk-ts#3726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

The live and operational section in the dashboard landing page are not visible in light mode; however it works fine in dark mode.

### which network/s did you face the problem on?

Dev, QA, Test, Main

### version

2.6.2

### Relevant screenshots/screen records

![Screenshot from 2024-12-09 14-26-04](https://github.com/user-attachments/assets/0021fb29-4995-4fa3-9db4-78716c9c3d3c)
![Screenshot from 2024-12-09 14-25-59](https://github.com/user-attachments/assets/fd5ba909-1656-48b7-b614-206a55e4556b)

### Relevant log output

```console
--
```

**Comment by ehab-hassan** [comment]
Work done waiting for review

**Comment by atefnazmy** [comment]
- Verified on Dev,
- Version: f0f91d9
- The map image has been updated to be clear in light mode

![Image](https://github.com/user-attachments/assets/9b4a641c-850a-4d37-823f-efe7714be882)

#### Related Link:
- https://app.testlodge.com/a/26076/projects/40893/runs/763032?tab=2#executed_case_33539733
