### ISSUE TITLE
Provide text to add in case the use didn't connect his tfchain wallet

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#373]

**Comment by xmonader** [comment]
Section 1

A Co-Owned Global Sovereign Internet
ThreeFold is a peer-to-peer open-source Internet platform that connects users directly with local Internet capacity (storage, compute, and network) provided by farmers. A decentralized sovereign alternative to today’s centralized Internet model.


Section 2

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/238797b5-9d89-44b9-a2a4-2321137a33d0)


Section 3

The Layer Zero for a Decentralized World
Anything that runs on Linux can run on ThreeFold – with more security, more sustainably, and in true decentralization. The ThreeFold Grid can support workloads from Blockchain to Web2 to Web3 to IoT and Metaverse and more.
