### ISSUE TITLE
🐞 [Bug]: solutions not shown even when logged in 

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#3731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### which package/s did you face the problem with?

Dashboard

### What happened?

logged in and when to a solutions page , solution page didnot see that wallet is connected

### Steps To Reproduce

1. log in on home page
2. navigate to a solution
3. might be slow network issue
4. observe that balance is loaded but solution page does not see that your wallet is connected

### which network/s did you face the problem on?

Dev

### version

4dc450876efd0c07de46d88c6db3f64a98f351b1 

### Relevant screenshots/screen records

![Screenshot from 2024-12-10 10-17-33](https://github.com/user-attachments/assets/ed0b3b2a-c019-4713-b7a2-fcb8fa9d5c1e)

### Relevant log output

```console
logs are in screenshot
```

**Comment by amiraabouhadid** [comment]
issue is not reproducible even with slow network.

**Comment by khaledyoussef24** [comment]
could not produce the same issue will reopen if reproduced
