### ISSUE TITLE
profile manager updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#377]
##  Add a hint for password

password: used to encrypt your mnemonic on your local system, and is used to login from the same device.

register -> change to `Connect 

## Remove the don't have account, create one from the login tab

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/0d687d87-103e-4278-b07f-e7977fb5fdb6)

this is what happens when i click on that create button without providing a password in the login

## Register
next to the mnemonic input, put the generate an account button

**Comment by mohamedamer453** [comment]
Verified on devnet.

- Tooltip was added in the password field.
- Register was changed to connect.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/edace93b-3d4c-4d3e-8419-938f17f07e47)

- `Don't have account, create one` button was removed and replaced with `Generate Mnemonic` button.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e4f4f6a9-4416-4110-96b0-620e24883aec)
