### ISSUE TITLE
Solutions always deploy with Planetary Network IP

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#391]
### Description

Solutions always deploy with Planetary Network IP, despite if its was chosen or not.

### Steps to reproduce

1. Choose a solution.
2. Fill out all the inputs.
3. Disable Planetary Network IP input.
4. Deploy

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6d53021b-d4d0-49b4-8bb4-d7fc9a900a78)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fb803dd8-35d2-414f-ad42-0fcb372594ab)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6ca46449-de7f-4c42-a5a3-2ce916b2a641)

**Comment by mohamedamer453** [comment]
Verified on devnet.

When all network are disabled, a warning message appears mentioning that at least one network option should be enabled and the deploy button is disabled in this case.

- Full VM

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/da75bbdb-712d-4b9e-8202-aa9fde59a06b)

- Micro VM

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/90dea304-1de9-4712-bd18-94b98351ce62)
