### ISSUE TITLE
Update explorer links to direct to the correct network.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#393]
### Description

`Explore ThreeFold Grid Capacity` button directs to the mainnet explorer not to the devnet. 
Also, it should reflect the chosen network.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/905bf354-23e2-4827-912e-dd7bb762de63)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e01a4302-df51-4729-9513-0476639e81f9)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The explorer link now redirects to the correct network.

[Screencast from 12-06-23 12:50:42.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f578fe07-a53c-45d5-bb9f-3ab5d11627b8)
