### ISSUE TITLE
playground randomly stuck at solution page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#395]
### Description

87c8714

After some navigation or deploying a solution, playground stuck at a page and don't allow me to navigate to any other solution with the shown error in the console every time I press on any solution, and it only solved by refreshing the site.
its happens randomly with no steps to reproduce but occurred more then once for me.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/12345926-cfb0-4466-acb7-08b11003c941)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f633cdbb-7ca1-48e0-b9c1-0f4cab2afae6)

**Comment by maayarosama** [comment]
too old
