### ISSUE TITLE
Update username label to be email in STMP and Mail server tabs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#397]
### Description

Update username to be email, as it's unclear cause its the same as the format of the emails `@expamle.com`.
Input are in STMP and Mail server tabs.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e4ee1817-9811-4265-940f-71557c53882a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/63564b6c-88a5-41cd-9909-82e4ddb69939)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The field was modified for all of the solutions that have smtp config.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c9124fe8-eec6-48c3-a061-2ef878245a32)
