### ISSUE TITLE
Viewing contract details of contracts deployed from terraform is not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#405]
### Description

Viewing the contract details of a contract deployed from terraform is not working.

```
Failed to send request to twinId 24 with command: zos.deployment.get, payload: {"contract_id":28677} due to 255 unexpected end of JSON input
```
[Screencast from 30-05-23 14:26:20.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a5cea8e7-836f-4c52-8004-2190a04aa4a3)

**Comment by MohamedElmdary** [comment]
Can't reproduce this issue tried to `show details` of contract created from terrraform and it worked just fine

**Comment by khaledyoussef24** [comment]
it worked fine with me now,I made a deployment from terraform and i can see the contract details from play ground.
![Screenshot from 2023-06-20 11-38-18](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9834b3fe-0f79-4b78-a909-d2f21088bd41)
![Screenshot from 2023-06-20 11-36-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0aa1ef20-f6cb-424b-be45-904ac400206a)

I used the single node example from terrafrom.
