### ISSUE TITLE
The node details section in the explorer is not displayed on devnet dashboard

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#41]
### Description

The node details section in the explorer is not displayed on devnet dashboard and the following errors appears in the console once you expand the details of any node.

![image](https://user-images.githubusercontent.com/101194226/231730693-45e81c79-3dd3-4d91-bea9-58414e4e58ae.png)

```
Access to fetch at 'https://gridproxy.dev.grid.tf/nodes/14/statistics' from origin 'https://dashboard.dev.grid.tf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
```
GET https://gridproxy.dev.grid.tf/nodes/14/statistics net::ERR_FAILED 502
```
```
TypeError: Cannot read properties of undefined (reading 'users')
    at s.S (NodeDetails.vue?5007:1:2519)
    at Sn.e._render (vue.runtime.esm.js:3569:22)
    at s.r (vue.runtime.esm.js:4081:21)
    at or.get (vue.runtime.esm.js:4495:25)
    at new or (vue.runtime.esm.js:4484:12)
    at Rn (vue.runtime.esm.js:4088:3)
    at Tr.$mount (vue.runtime.esm.js:8459:10)
    at init (vue.runtime.esm.js:3137:13)
    at p (vue.runtime.esm.js:6022:9)
    at f (vue.runtime.esm.js:5969:9)
```

[Screencast from 13-04-23 12:17:40.webm](https://user-images.githubusercontent.com/101194226/231729968-a1e1b3ef-c456-4133-b655-370d4780f950.webm)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/explorer/nodes
- Click on any node from the nodes table.

### Environment 

- Network: `Devnet`
- Dashboard Version: `v1.5.0-rc3`
- Gridproxy Version `v1.8.0-rc2`

**Comment by A-Harby** [comment]
Verified on Devnet, v1.5.0-rc3.
![image](https://user-images.githubusercontent.com/109473873/234849268-3b387eec-e051-4c23-a03c-d4f310c6f753.png)
