### ISSUE TITLE
Valid password message need to be improved

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#411]
### Description

Not sure if it's supposed to be shown to the user like that, but the message could be improved and it is duplicate.  

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/58c650d1-05ae-433e-bfb4-34026d3e62c0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5584aab7-a9d1-4aa8-b061-e6f883e68526)

**Comment by mohamedamer453** [comment]
Fixed and verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/377
