### ISSUE TITLE
filtering with pricing policy for null

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#42]
### Description

searching for nodes with pricing policy returns results for 0 while there is only pricing policies of 1
works fine with the other numbers
![image](https://user-images.githubusercontent.com/110984055/230900195-2361568b-a4a6-4ea3-8fea-19ef431a2a89.png)

### Steps to reproduce

1. go to dashboard
2. go to explorer 
3. click on farms
4. add pricing policy filter
5. search for 0
[Screencast from 04-10-2023 02:16:57 PM.webm](https://user-images.githubusercontent.com/110984055/230900074-08c22cea-83d7-4422-84a8-ee4057bfb37e.webm)

**Comment by 0oM4R** [comment]
should we make a number validator to be larger than 0?
@AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
yes, numbers should start from 1 for the pricing policies

**Comment by 0oM4R** [comment]
Status: Ready on PR #246

**Comment by 0oM4R** [comment]
Status: waiting for dashboard release

**Comment by mohamedamer453** [comment]
Verified on devnet.

A validation  message now appears in when 0 is entered in the `Pricing Policy` field.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3c4cadda-7ba3-424c-b91f-c424e6bced72)
