### ISSUE TITLE
Deployment list not working as expected

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#423]
### Search first

Maybe this is a part of this issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/412 

### Description

After logging in I noticed that there are no full VMs listed, while when I go to the deployment list tab my VM was there!

### Steps to reproduce

- Go to playground.dev.grid.tf
- insert your memo/password
- close the profile manager then watch the listing tab, make sure that you have deployments

### Logs/Alerts
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/bf36315e-6006-4401-b40c-4d712b44e9c6)

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/412#issuecomment-1569956395
