### ISSUE TITLE
Dashboard : values file need to be improved 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfgrid-sdk-ts#437]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/v2.0.0-rc11/packages/dashboard/charts/tfgrid-dashboard/values.yaml#L107 , this line is not needed anymore as it's already be passed in env variables .

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/dashboard/charts/tfgrid-dashboard/values.yaml

The mentioned value was removed.
