### ISSUE TITLE
Playground : env varialbles need to improved and documented

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/tfgrid-sdk-ts#439]
https://github.com/threefoldtech/tfgrid-sdk-ts/blob/d591f8b54d74e9ae552eb0353e522d4cc7c3b71c/packages/playground/playground-charts/values.yaml#L13
- why need to pass version as env variable as it passed in image tag .
- network env variable is processed as MODE in scripts of build-env.sh here https://github.com/threefoldtech/tfgrid-sdk-ts/blob/v2.0.0-rc11/packages/playground/scripts/build-env.sh#L22

**Comment by mohamedamer453** [comment]
Verified from https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/playground-charts/values.yaml#L13&L29

The mentioned section was modified.
