### ISSUE TITLE
add prefix to portal path 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#44]
### Description

the portal prefix is only `/` while other components have a meaningful prefix like `/explorer`
this leads to weird path if you navigate from explorer or calculator to portal like `https://dashboard.dev.grid.tf/calculator/account-transfer`
### Implementation

add prefix to protal like in explorer

**Comment by AlaaElattar** [comment]
- I've tried this but portal is not the root.
- I think we should close it as it's already handled in both new and old dashboard
