### ISSUE TITLE
UI: change the balance and locked TFT color and size

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#452]
![nav1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/e60ef357-d346-4858-af0c-7f4df338a5af)
please change the balance and locked TFT to be like this
![nav2](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/62f74499-ef88-41f3-ab22-5696429bcab6)
green color #76e2c8

**Comment by khaledyoussef24** [comment]
verified on devnet balance now is more clear.
![Screenshot from 2023-06-25 10-50-09](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0d761002-00f6-4195-a25a-0caa714ac653)
