### ISSUE TITLE
Newly created twin causes some errors in the console 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#456]
### Description

QA 2.0.0-rc12

Some errors appeared in the console when you create new twin and open it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ae304c74-44a5-4134-8185-d0b448c9c09f)

**Comment by xmonader** [comment]
I don't believe that's relevant, probably misconfigured analytics
