### ISSUE TITLE
Inconsistency between the explorer and the dedicated nodes tables

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#46]
### Description

Inconsistency between the explorer and the dedicated nodes tables.

![image](https://user-images.githubusercontent.com/101194226/228827559-fbb046d2-c55b-4c2a-a07d-51ef0faea736.png)

As it can be seen above the data is inconsistent between the two tables for the same nodes.

Both tables are technically correct and there is no problem with the data itself, however the way of displaying the data should be unified. this should include the units, approximations etc.. and if the same data is displayed anywhere else in the dashboard or in some other place throughout the grid then it also should use the same convention.

Also the location of the columns should be consistent. for example in the explorer the columns are sorted like this: `HRU` -> `SRU` -> `MRU` -> `CRU` and in the dedicated nodes page its: `CRU` -> `HRU` -> `MRU` -> `SRU` this section should be consistent in both tables. 

and lastly the location of the unit. in the explorer its next to each value.

![image](https://user-images.githubusercontent.com/101194226/228830572-7b0a05f6-8087-4057-a8d8-b784d68c80e6.png)

While in the dedicated nodes table it's next to the header.

![image](https://user-images.githubusercontent.com/101194226/228830689-63b2f123-0a9d-45d5-9d7e-6422d763774e.png)

The `HRU` in the explorer is in `TB` while it's in `GB` in the dedicated nodes table.

**Comment by 0oM4R** [comment]
Should I change the dedicated nodes table to be like the explorer, or vice versa? @mohamedamer453  @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
the dedicated nodes table to be like the explorer one

**Comment by 0oM4R** [comment]
status: PR #503  ready to review

**Comment by mohamedamer453** [comment]
Verified on qanet dashboard `2.0.0-rc14`

The data is now consistent between the two tables. the order is now `CRU` -> `MRU` -> `SRU` -> `HRU` for both tables.

Units are now next to the value in each column and the approximations are consistent in both tables.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8f2f3e80-85a2-4f86-9c08-156a54d29b17)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ee7c861f-7c88-47e2-aad6-f367c00f216a)
