### ISSUE TITLE
UI Planetary network IP toggle should be removed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#461]
### Description

Planetary network IP toggle should be removed since it wasn't already selected because the user could be misled into that it could be enabled after the deploying is done 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0d6fa9b4-53fc-431a-be63-6e56bc73d961)

**Comment by khaledyoussef24** [comment]
verified toggle is not visible if there is no network ip
