### ISSUE TITLE
Login button will stuck loading if account balance is not enough

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#462]
### Description

If account balance is not enough (less than 2 TFT), Login button will get stuck loading forever.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ddd7c629-f0c5-44d5-aa9f-9cc0c0b006bb)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/04bfed59-9c3d-476b-9716-26cda4a6d6ec)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2578cc7f-6441-4dde-9987-232363304f16)

**Comment by khaledyoussef24** [comment]
verified 
[Screencast from 06-25-2023 01:04:54 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cd79422d-a210-4750-961e-f4d3023efd6f)
![Screenshot from 2023-06-25 13-02-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/7c000f1c-7d62-4376-bcfa-64bc7ce22eac)
![Screenshot from 2023-06-25 13-00-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9a448da2-4989-44b0-8d29-2dc6d6341674)
