### ISSUE TITLE
GPU support in the client

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#464]
https://github.com/threefoldtech/home/issues/1392 

https://github.com/threefoldtech/zos/pull/1973

**Comment by AhmedHanafy725** [comment]
- [ ] a new field in [zmachine](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/zos/zmachine.ts#L41) should be added and propagated to the [machine module](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/src/modules/models.ts#L85) for GPU check [here](https://github.com/threefoldtech/zos/pull/1973/files#diff-3f3d95e016b8d0b2e9784c44053c1393d3c6124cf28cef3c2d9d7ee567edb136R151)
- [ ] the zos module on the grid client should have a new call over RMB to get the node GPU details
- [ ] a check should be added in case the requested deployment has GPU to make sure that the node has GPU or not
- [ ] Add a new filter option to filter the nodes with GPU (require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/201)

**Comment by AhmedHanafy725** [comment]
all done and waiting for a node for testing

**Comment by A-Harby** [comment]
Verified,

New option have been added to the gridproxy `HasGPU`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/90478647-c213-411c-b622-8d7e53ea93c6)
Deployment was successful.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a632b586-73f1-436b-9f17-0c62ba01a3bf)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/637aeb1e-23b1-4585-8d88-4b257f038c64)
