### ISSUE TITLE
GPU support in explorer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#465]
https://github.com/threefoldtech/home/issues/1392 

https://github.com/threefoldtech/zos/pull/1973

suggestions:

## nodes table
- a new toggle for gpu, like online and gateways 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3f26ee27-8e66-440e-a813-4cebd7f65dd9)

- column has gpu with a checkbox readonly?

## node detail
once you click on the node you can see the information of the available gpus (it requires sending ListGPUs rmb call), maybe with a card rendering a list of gpus

Note: if we index the GPUs on the explorer, we could also add a filter for specific GPUs and show the names in the nodes explorer

require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/201

**Comment by AhmedHanafy725** [comment]
each gpu in the list should look like 
```
  {
    id: '0000:0e:00.0/1002/744c',
    vendor: 'Advanced Micro Devices, Inc. [AMD/ATI]',
    device: 'Navi 31 [Radeon RX 7900 XT/7900 XTX]',
    contract: 31540
  }

```

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/a8531e82-e83c-4199-b903-e035a5312ca1)
 
what do you think?
@xmonader @AhmedHanafy725

**Comment by 0oM4R** [comment]
merged waiting for release

**Comment by mohamedamer453** [comment]
Verified on devnet.

GPU toggle was added to filter only nodes with GPU.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/43d75690-a585-48e8-8f00-a6d987385ac2)

And a new column was added to display the number of gpus available for each node.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5e67c079-fc2a-4c86-b67e-73277a7fac68)

and gpu information was added in the in the node details.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ab45e5c8-69b7-4f0e-9efd-ea92c73ed87c)
