### ISSUE TITLE
migrate statistics website to vue3

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#467]

**Comment by 0oM4R** [comment]
@ehab-hassan should we keep the old design ?
https://stats.dev.grid.tf/

**Comment by ehab-hassan** [comment]
@0oM4R 
use new color ar playground 
dark green #1aa18f
light green #74DDC3

icons at titles not values
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/fe725b36-58b2-4b37-b8b5-9fd368c2f3c9)

make this like a Disclaimer background at playground,gray with white text
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d8a28f45-a9dc-4c1b-b4a4-e54670ac72d6)

**Comment by 0oM4R** [comment]
we need to add feature to select the network something like check box or drop down 
so the user will be able to select specific networks to show it's stats 

@ehab-hassan  **can you please provide you thought about it ?**

**Comment by 0oM4R** [comment]
status: just walked throw the old website and setup the new project, and working on replacing the fetch utils to use gridproxy_client instead of axios

**Comment by 0oM4R** [comment]
Status: worked on UI; will add filter feature tmw.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/c4063e35-c445-4b52-bdd0-2603bb53ac37)

**Comment by ehab-hassan** [comment]
Figma for statistics
https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=1123-2815&t=pQNKrdRbXNSfHXsb-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196

**Comment by 0oM4R** [comment]
There have been no updates to this issue. I had to work on CrystalLib issues last week and will return to this issue as soon as they are resolved.

**Comment by 0oM4R** [comment]
worked on bind stats data from store to the stats table based on selected network by network filter,
todos:
- fix responsiveness issue 
- implement refresh logic 
- error handling 
- cleanup the code

**Comment by ehab-hassan** [comment]
@0oM4R can we change the Refresh button to be outlined with light green #74DDC3

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6a254247-bce8-48c9-a5fd-bf78ab89a5bf)

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/50e9edba-63de-458d-8335-6c1156337b46)

WIP:
- updated the filte and refresh logic
- applied some UI changes and fixed some responsive issues
- changed the store to pinia and having some issues with it will check them with Rabie

**Comment by 0oM4R** [comment]
![Screenshot from 2023-10-23 17-40-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/77cabc0e-410c-48fa-a47d-9f7fdb1daea5)
![Screenshot from 2023-10-23 17-40-15](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/5c19a7b5-e808-4884-bf71-9cbf17abd19c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0640af95-306b-4372-b63e-24bd0c8666ba)

## Status
- updated ui to support small screens 
- fixed store issue 
- add error component
## todos
- handle error msg in small screens
- clean up the code and prepare the pr

**Comment by xmonader** [comment]
Let's wrap this today

**Comment by 0oM4R** [comment]
####Status
 pr https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1234 ready for review

**Comment by 0oM4R** [comment]
__Status__:
resolved some comments on the pr

**Comment by 0oM4R** [comment]
__Ready for review__
resolve #1275 to include standby nodes and change merge data logic

**Comment by khaledyoussef24** [comment]
verified added to the new playground
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ab7774f-3aa0-4b08-8f79-f07c20080304)
