### ISSUE TITLE
Migrate Dashboard to vue3

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#468]
- [x] Layout: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1013
 - [x] Portal 
     - [x] Twin: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1014
     - [x] Bridge: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1015
     - [x] Transfer: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1016
     - [x] Farms: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1017
     - [x] Dedicated Nodes: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1018
     - [x] DAO: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1019
     - [x] Get TFT button: #1070 
     - [x] TFT-USD Exchange Rate: #1072
- [x] Explorer
     - [x] Statistics: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1022
     - [x] Nodes: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1020
     - [x] Farms: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1021
- [x] Calculators
     - [x] Resource Pricing: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1024
     - [x] Simulator: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1135

P.S.  Each template/HTML element should have an identifier or class attached to it for testing purposes and it should be based on [BEM Naming Convention](https://getbem.com/naming/)

**Comment by amiraabouhadid** [comment]
need to add this issue as well #1070

**Comment by A-Harby** [comment]
Verified,
On Devnet 13a87cf, through both https://dashboard.dev.grid.tf/ and https://playground.dev.grid.tf/.
All the pages have been migrated, and their functionality is working fine.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/14ea462f-c28c-44e1-b9d2-6449d5c7f083)
Both test cases and separate reported issues are being worked on.
New test suite: https://app.testlodge.com/a/26076/projects/40893/suites/234374

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- ec2ed3d
