### ISSUE TITLE
dashboard to use the profile manager 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#470]

**Comment by A-Harby** [comment]
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/852

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc3.

Connecting your wallet is working fine with any mnemonics, same as creating new twin.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b815baef-9c90-4249-b778-f0e9c6bfb919)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/85bdf82f-a3ad-4c87-8a60-da2103d682c5)

And password is being saved and relogging with no issue.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/955cf55d-d5ca-4b14-b154-fdbe89d02fed)
 
All other related issues are created separately and will be verified once it's fixed.
