### ISSUE TITLE
Weird characters randomly appear instead of icons in the playground

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#471]
### Description

Sometimes all of the icons in the playground change to weird characters, i'm currently not sure what's the cause of this and how to reproduce but it happened multiple times randomly. the only thing that i can think of that might have caused this is the window size since it happened a couple of times when the window was minimized (50% of the screen or less) but i lowered the size of the window and i wasn't able to reproduce it.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8b5121bd-ac0f-4acb-aea8-31dfd99c20a5)

Will try to add steps on how to reproduce it once i figure it out.

### Environment

- Network: `qanet`
- playground version: `2.0.0-rc12`
- Screen resolution `2560*1440`

**Comment by zaelgohary** [comment]
I tried multiple times but couldn't reproduce the issue. 
Note: The issue happened before after building the project from the docker image and was fixed once [nginx config](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/6a05c01635552e88db2c10c2f8147c69ea98f487/packages/playground/nginx.conf) was added.

**Comment by mohamedamer453** [comment]
As i mentioned originally in the issue it was random and unfortunately i wasn't able to reproduce it and it hasn't occurred with me since. so i'll close this issue and in the future if i was able to reproduce it then i'll reopen the issue with more details
