### ISSUE TITLE
GrafanaStatistics not working correctly in playground

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#478]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/1b81df45-2847-4da8-a7e5-9c89820eaa5d)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in #480

**Comment by A-Harby** [comment]
Verified,
Error removed from console and grafana stats page is working now.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f329faf1-f4df-4eee-82ee-89906b8c3ba1)
