### ISSUE TITLE
The serial number of some newly booted nodes on testnet is displayed as `Default string`

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#48]
### Description

The serial number of some newly booted nodes on testnet is displayed as `Default string`.

![image](https://user-images.githubusercontent.com/101194226/228820016-f3cb712a-f543-4dc4-9d52-d6555f7efde5.png)

### Environment

- Network: `testnet`.
- Dashboard Version: `v1.4.0-rc10`

**Comment by xmonader** [comment]
Let's add a note on the Nodeslist component with the explanation for Default string in the serial number column

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/ca3efbb6-ef4e-4369-9e54-89f5c832979e)
![Screenshot from 2023-05-24 13-43-53](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/8aacae32-365d-407f-b1e5-eee0027c4879)
Is that what we need ? the icon and its note will appear only if the serial number is Default string

@xmonader

**Comment by xmonader** [comment]
> ![image](https://user-images.githubusercontent.com/62248851/240578511-ca3efbb6-ef4e-4369-9e54-89f5c832979e.png) ![Screenshot from 2023-05-24 13-43-53](https://user-images.githubusercontent.com/62248851/240578640-8aacae32-365d-407f-b1e5-eee0027c4879.png) Is that what we need ? the icon and its note will appear only if the serial number is Default string
> 
> @xmonader @AhmedHanafy725

You shouldn't mention silver boxes, just make it 

`While parsing the hardware information, the manufacturer didn't provide a proper serial number, and made its value "Default string"`

**Comment by 0oM4R** [comment]
Status: Merged, waiting for release
