### ISSUE TITLE
Dashboard and weblets are not rendering correctly on all networks

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#486]
### Description

Icons are not being rendered on both the dashboard and the weblets (on all networks).

### Dashboard 

- dev

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c1be47d5-f21c-44a9-8c2e-952f4669b79f)

- test 
 
   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a73a9148-71c8-4e4e-94fb-8e75feed14c9)

same issue also happened on qa and main

and this error appears in the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/267e50a8-5017-43bb-a60f-3972ed6d1336)

### Playground

- dev

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9fc83019-61ae-464c-9be2-99216d83acec)

- test

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2ac22f7f-3f6c-4bf4-88b9-e540800b8041)

same issue also happened on qa and main

and this error appears in the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4b6753e8-a5bf-4e48-a49a-127fd09d4d6b)

**Comment by khaledyoussef24** [comment]
and the dark mode icon also
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f46efeba-8332-49ce-9c88-4ece593e8049)

**Comment by ramezsaeed** [comment]
#592
