### ISSUE TITLE
change the default view for the login manager

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#488]
Yesterday in the demo when sam was trying the playground for the first time he was blocked by the fact the first tab was login and he was asked for a password, I checked the flow in foldit.tf, what they do is if there's a local storage item they show the login option

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/24d0efa4-9f1f-4cb1-9d86-987209eafefc)

and if not (indication it's the first time to use on that device they show the create account form)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/62e486c2-a981-45b3-929f-54c1dd00ecda)

**Comment by A-Harby** [comment]
Verified Devnet 5e5c622,
First time using the playground will only display the connect your wallet tab
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d831bbc6-0f8e-4396-b6a5-2abd5c946951)
After that both login and connect tabs will be shown.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b61e1373-41ce-4e3a-bb09-64397b42abb3)

**Comment by A-Harby** [comment]
Just missing a small fix is needed,
First time connecting your wallet, the password field will give an error once its open.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7282e0fd-8b0d-4c6b-9a38-d7617c40ae2d)
