### ISSUE TITLE
Request calls are repeated when navigating from Explorer node to statistics 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#49]
### Description

Network requests calls are repeated when you navigated from Explorer node page to statistics page

[Untitled_ Mar 23, 2023 4_08 PM.webm](https://user-images.githubusercontent.com/109473873/227230569-afca62dd-323a-4f10-98d7-de30b9b563b1.webm)

**Comment by 0oM4R** [comment]
ready on pr #220

**Comment by 0oM4R** [comment]
mentioned wrong pr, will create a new pr tmw

**Comment by A-Harby** [comment]
Devnet, 2.0.0-rc12.

Fix seems not to be working, requests is still repeated when I navigate from Explorer node page to statistics page like video.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e4b8d5ab-8ebc-43c1-a81b-ec7dd374e967)

**Comment by 0oM4R** [comment]
__status__:  waiting for release

**Comment by A-Harby** [comment]
Verified on QA, 2.0.0-rc14.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/34b823e5-9911-4554-b839-35429dd75982)
