### ISSUE TITLE
Add filtering farms based on it's node

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#491]
## Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-go/issues/41

**Comment by MohamedElmdary** [comment]
@xmonader currently we're using the `nodeFilters` so we might no need to update it right now

**Comment by zaelgohary** [comment]
Blocked on [this](https://github.com/threefoldtech/tfgrid-sdk-go/issues/263).

**Comment by mohamedamer453** [comment]
Verified on devnet.

The filtering is now done with the `/farms` endpoint according to its nodes. using the new queries from https://github.com/threefoldtech/tfgrid-sdk-go/issues/263#issuecomment-1681878077

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2bfaa1f0-6c9f-499f-829d-d7b5efc73fd3)
