### ISSUE TITLE
gpu support in statistics website

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#492]

**Comment by AhmedHanafy725** [comment]
total number of the gpu cards added to the gridproxy on the stats endpoint so we can add a card with it

**Comment by A-Harby** [comment]
Verified on Devnet

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/48be7eb3-c4dc-4548-a8cb-21047049d2bc)
