### ISSUE TITLE
GPU: Allow a farmer to set a custom "extra" price on a node in the dashboard

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgrid-sdk-ts#499]
To complete https://github.com/threefoldtech/home/issues/1392 we need on chain a way to set an extra price. But we also need a flow in the dashboard for a farmer to set a custom price.

I would suggest adding the new "button" on the farmer's node overview page where a modal opens so he can view/set an extra price. 

A call to tfchain `smartContractModule.setDedicatedNodeExtraFee` must be mode with (node_id: u32, extra_fee: u64).

The `extra_fee` is expressed in mUSD (milli usd => USD * 1000)

Errors will be thrown when:

- the node has active deployments
- the node is rented already

**Comment by AhmedHanafy725** [comment]
for these errors, does it mean that the farmer can't set the extra fee if the node has node/rent contracts?

**Comment by DylanVerstraete** [comment]
> he farmer can't set the extra fee if the node has node/rent contracts

Yes indeed

**Comment by renauter** [comment]
See some specs from TFChain side here:
https://github.com/threefoldtech/tfchain/issues/725

**Comment by A-Harby** [comment]
Verified.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/323fc4df-7eb4-4a1e-89ea-5fb0d145b0df)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3a77e7ff-51f0-459e-9d46-d76c5470f116)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/72367b64-427d-44c3-a5b9-df8103fbb45f)
