### ISSUE TITLE
Stellar Payout Address edit btn messed up ui

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#50]
### In portal if the farm has Stellar Payout Address the edit btn missed its original position 
![Screenshot from 2023-03-23 15-14-25](https://user-images.githubusercontent.com/62248851/227216455-8bfd168c-360c-4efa-83a8-743ade199770.png)
 if no Stellar payout address 
![image](https://user-images.githubusercontent.com/62248851/227216800-9613e13f-6f94-4174-b2c5-8766c776cf0f.png)

**Comment by A-Harby** [comment]
Verified, Devnet 2.0.0-rc12.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a78e2bdf-e786-4896-b61e-259652a9b6d4)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1c43091e-57b9-477e-87ba-8de19abcc2cd)
