### ISSUE TITLE
Adding a warning in case that something failed to load

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#504]
### Description

There should be a warning for the user that the icons on the site isn't loaded successfully and to check internet, retry again later or contact support if the problem is persist.
like the [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/486) happened with dashboard, weblets ,stats and other sites.

**Comment by ramezsaeed** [comment]
#592
