### ISSUE TITLE
Dashboard node details no longer show interface details

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfgrid-sdk-ts#508]
### Description

Opening the detailed view of a node on the dashboard does not show the interface details (mac and ip of the zos bridge)

**Comment by 0oM4R** [comment]
__status__ :  merged, waiting for release

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.

Node details is displaying now with no error.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/658dc1d9-95c8-4fee-ae92-7e14842180ba)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5500812c-81ab-4e5c-898f-847b258a18ef)
