### ISSUE TITLE
Fetch balance when depositing TFT via stellar

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgrid-sdk-ts#51]
### Description

When depositing TFT from Stellar to Tfchain, I have no indication wether or not the bridge transaction was completed. I have to reload the page to see my updated balance after like 10-20 seconds. It would be better to have some kind of loading spinner and when it notices the bridge transaction is completed i would get a notification.

### Implementation

When you are on the swap page and you click deposit we can start fetching events from tfchain and watch for `mintCompleted` with the destination account being my twin account. If it notices such an event, we close the modal and we give the user a notification and we update the balance. If the user closes the modal, we also stop watching events.

**Comment by 0oM4R** [comment]
Update: Now i have a good idea about the events and the chain, I already created a function to listen on that event but no I'm trying to make it more generic

**Comment by 0oM4R** [comment]
Update: done, and tested.. will make the pr by Sunday

**Comment by 0oM4R** [comment]
**Status**:
 Pr ready for review

**Comment by 0oM4R** [comment]
> If the user closes the modal, we also stop watching events.
the watch method on the chain already has a timeout, I think it will be better if we keep the watch method even if the user closes the modal

**Comment by 0oM4R** [comment]
Update: implement the method in the dashboard, will move Deposit Dialog to a separate component to avoid some buggy scenarios

**Comment by 0oM4R** [comment]
Status : merged, waiting for release

**Comment by mohamedamer453** [comment]
Verified.

From testnet dashboard `v2.0.0-rc12` i was able to see the balance update after depositing TFTs and a message also appears at the bottom right of the screen mentioning that a certain amount of tfts was added to my balance.

[Screencast from 13-06-23 12:17:08.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2d6156fc-bf64-44e3-8364-141a4de0c60b)
