### ISSUE TITLE
Clear profile manager fields when the user switches between `Login` and  `Connect`

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#510]
### Description

The password field should be cleared when switching from the `Login` to the `Connect` tab and vice versa. and it also should be cleared if the profile manager was closed. and the same issue is present in the mnemonic field when the user switches between tabs or closes the profile manager.

[Screencast from 11-06-23 12:03:35.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9f384993-e9a1-4d5f-875c-873196c6f7ac)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/525

**Comment by A-Harby** [comment]
Verified,
Field are cleared when navigate between login and connect
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4fcc284a-1099-4e95-883b-4f72d16cc51f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5ccf53b8-f9f4-4005-9758-be4941455023)
