### ISSUE TITLE
Listing deployments with a slow connection takes too much time and sometimes fails to list the deployments

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#513]
### Description

Listing deployments with a slow connection takes too much time. as seen in the video below i tried to list my full vm deployments while throttling my connection to `Slow 3G` from the devtools. i took around 1 minute to list my deployments.

[Screencast from 11-06-23 15:27:16.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b27a4a0a-4c03-4914-b76d-e1584914cf47)
 
Another scenario that sometimes happens is that it takes more time than the mentioned above and fails with the following error in the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cd6bcbd4-908c-4e55-81c2-b8605e6f4c42)

```
Error] failed to load deployment with name FarmerbotVM336:Failed to get deployment due to Error: Failed to send request to twinId 11 with command: zos.deployment.get, payload: {"contract_id":20973} due to Didn't get a response after 60 seconds

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.

[Error] failed to load deployment with name vmmwia79mv:Failed to get deployment due to Error: Failed to send request to twinId 25 with command: zos.deployment.get, payload: {"contract_id":29203} due to ,Unable to send due to ,Failed to open connection after try for 5 times.

[Error] failed to load deployment with name vmkywm8gog:Failed to get deployment due to Error: Failed to send request to twinId 21 with command: zos.deployment.get, payload: {"contract_id":30949} due to ,Unable to send due to ,Failed to open connection after try for 5 times.
```

### Environment

- Network: `devnet`
- Playground Version: `9955b45`
- Internet Connection: Throttled to `Slow 3G`

**Comment by ramezsaeed** [comment]
#592
