### ISSUE TITLE
failed to load N deployments

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#516]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/4c69e83d-4a28-44c7-b6a3-c828caeba21a)

Add an explanation on the meaning of this

**Comment by 0oM4R** [comment]
describing the error? if not can you suggest a phrasing ?

**Comment by mohamedamer453** [comment]
Verified on devnet.

More explanation was added to this message.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f21d3ae9-017d-4e39-8aff-6e676a212fc7)
