### ISSUE TITLE
profile manager get started link redirects to old weblets profile manager

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#517]
blocked on https://github.com/threefoldtech/info_grid/issues/120

**Comment by mohamedamer453** [comment]
Issue is still present and the link redirects to https://manual.grid.tf/weblets/weblets_profile_manager.html

**Comment by A-Harby** [comment]
Verified on Devnet, 2.1.0-rc6.
Buttons UI were improved and help button was removed
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/79036198-3635-48e5-a31b-fb1d063b0b24)

**Comment by khaledyoussef24** [comment]
the profile manager still redirects me to 
https://manual.grid.tf/weblets/weblets_profile_manager.html
instead of 
https://www2.manual.grid.tf/playground/home.html

**Comment by khaledyoussef24** [comment]
verified on devnet 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/99fbeb72-61dc-46c2-ba43-d069f371cb94)
