### ISSUE TITLE
Store And Login action button

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#519]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/2372d53e-c180-4835-a141-4b4aa67f78d4)

Please replace with `Connect` or maybe something else

**Comment by Mahmoud-Emad** [comment]
Should be updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/509
