### ISSUE TITLE
Submit button validation on adding node public config without IPV6

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#52]
### Description

When adding node public config, all the input must be filled in for the submit button to be enabled.
But when you fill in all of them and the button is enabled you can now then removed IPV6 or the IPV6 gateway and the button will still be enabled 

### Steps to reproduce

When you fill in all the inputs
![image](https://user-images.githubusercontent.com/109473873/226591573-6252b53c-1a48-483c-9e40-34d914dc47f7.png)

When you remove one of them
![image](https://user-images.githubusercontent.com/109473873/226591467-90ad3a8c-2d02-46d8-b5f2-d66450fa7425.png)
![image](https://user-images.githubusercontent.com/109473873/226591354-97fc660e-14d3-4ba5-a196-8fe5bf4da7b4.png)

Will give this error in the console when submit without only one of them.
![image](https://user-images.githubusercontent.com/109473873/226591092-aaf998fe-1b7e-4ae2-8ac4-acfe02f29ed1.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now when the user enters anything in the `IPV6` the `GW6` field becomes mandatory and vice versa. and it's only optional when both fields are empty.

[Screencast from 11-06-23 18:09:48.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/452f5147-3959-448c-bcd0-b91434eef31b)
