### ISSUE TITLE
switching to light mode doesn't reflect on sidebar

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#521]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/7c285f1f-6af6-4229-a5e8-b2fe10728853)

**Comment by MohamedElmdary** [comment]
Mr @ehab-hassan said it should be like that for user experience reason

**Comment by ehab-hassan** [comment]
we working now at threefold.io new themes so no  purple anymore ll send the new color soon just need to make sure that is the final color with the marketing team

**Comment by amiraabouhadid** [comment]
resolved in new playground 

![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/56790126/f7e65355-cfbb-4ea0-a850-a023e501ee9f)

**Comment by khaledyoussef24** [comment]
fixed and verified 
enviroment used : devnet

<img width="1440" alt="Screenshot 2023-12-20 at 1 16 39 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0961bd03-61b5-4a54-9333-64a4195126c1">
<img width="1440" alt="Screenshot 2023-12-20 at 1 16 42 AM" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/adba37ef-1dfb-4d03-919f-7e4817774092">

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422339#case_4157426

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 000eea2
