### ISSUE TITLE
Add more tooltips on the network options 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#522]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/99b73806-39f4-4adb-8aab-e3a1c99909d6)

add a tooltip for planetary and wireguard access

**Comment by Mahmoud-Emad** [comment]
Should be added in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/522

**Comment by mohamedamer453** [comment]
Verified on devnet.

Tooltips were added to all network options.

[Screencast from 18-06-23 15:49:34.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b64b18e1-156c-4d04-9bbf-d39226f04452)
