### ISSUE TITLE
Number of locked TFTs doesn't appear if it's 0

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#524]
### Description

Number of locked tfts doesn't appear if it's 0.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/edb7853e-e8f8-4a20-9300-cc7354b030a7)

### Expected result

It should display `0 TFT`.

**Comment by A-Harby** [comment]
Verified, Devnet c765569.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fabd4d43-fdd3-41cd-b206-2ffc4589047a)
