### ISSUE TITLE
update ownCloud instance name

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#526]
### Description

ownCloud instance name should start with `ow` not `mm`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/19e87cd6-4e3b-4ed2-b047-699928408c85)

**Comment by zaelgohary** [comment]
I renamed the deployment initials to "oc"

**Comment by mohamedamer453** [comment]
Verified on devnet.

ownCloud instance name now starts with `oc`.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/97f9baad-7961-4caa-8a61-eee4f4dc6da0)
