### ISSUE TITLE
deployment cost colors fixes

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#528]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/8a977595-fc5b-4cad-ae15-b3035a0b5646)

the purple seems bit weird in the context

**Comment by ehab-hassan** [comment]
we'll get rid of Purple at all and use green and blush colors 
and yallow for warning

Dark mode
primary: #7de3c8
secondary: #14A1B8
info: #7de3c8
warning: #FFCC00
link: #5695ff

Light mode
primary: #1AA18F
secondary: #14A1B8
info: #1AA18F

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94372af2-1b51-4653-aff4-664e7b1815af)
verified on devnet cost colors are now more clear
