### ISSUE TITLE
add a filler description for the disks page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#530]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/28bc8cbc-04d9-4a29-82f0-dea4d355e2b8)

**Comment by 0oM4R** [comment]
__Status__: #549 ready for review

**Comment by khaledyoussef24** [comment]
verified on devent.
change style of add btn
add a description to disks page
add a tooltop for name and disk size
![Screenshot from 2023-06-26 11-15-13](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/eca4475e-eab4-40c2-ba07-ae9501598a93)
![Screenshot from 2023-06-26 11-14-58](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/11caa32d-9039-4d2c-bbb1-a51ccff7ddf5)
![Screenshot from 2023-06-26 11-14-43](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9a3b89b4-613d-4155-b277-ef5a90bbb823)
