### ISSUE TITLE
deploy button is too small compared to add disk

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#531]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/5729d504-3e14-4474-a550-d7583a1f0e90)

**Comment by 0oM4R** [comment]
__Status__: #549 ready for review

**Comment by mohamedamer453** [comment]
Verified on devnet.

The add button was adjusted. and now its size is normal in comparison to the  `Deploy` button

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1892f935-3889-438f-a434-8389d4d430be)
