### ISSUE TITLE
change deployment list title per solution page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#532]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/344d8636-5ce1-4af3-ae28-ad5bcf1e4794)

Should be 

Virtual Machines, Clusters, ..... etc

**Comment by 0oM4R** [comment]
@xmonader  this may lead to wired names for some solutions 
Taigas, woredpresses, and discourses... etc 
imo, we can set it to `Your Taiga deployments`

**Comment by mohamedamer453** [comment]
Verified on devnet.

Titles were updated.

Full, Micro vms -> `Virtual Machines`, `Micro Virtual Machines`
K8s, CapRover -> `Clusters`
all of the other solutions `<solution_name> Instances`

[Screencast from 18-06-23 15:52:32.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4b9b7dd5-3906-4ac5-bf07-d1b5d0e3322e)
