### ISSUE TITLE
Allow tooltip or hint option on all of the fields used in the playground

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#538]

**Comment by MohamedElmdary** [comment]
@xmonader We shouldn't wrap inputs with `v-tooltip` as it has tons of options
if we did that we will start adding option by option from time to time and it won't scale that well
we should just stick with `<v-tooltip>`

**Comment by khaledyoussef24** [comment]
verified on devnet.
tool tip is now available on all options on the playground.
![Screenshot from 2023-06-26 11-25-45](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/edeabc39-6aaa-46ec-bce1-92980aee4906)
![Screenshot from 2023-06-26 11-25-35](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/482e9965-ac2e-49e5-83ac-22c488ddd15a)
![Screenshot from 2023-06-26 11-25-23](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9349a284-9073-415b-91f6-434398e3049d)
![Screenshot from 2023-06-26 11-25-14](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e78218ed-d061-4bb5-9fa4-79a6f7df2753)
