### ISSUE TITLE
add info for the root disk

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#539]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c06d8a8f-702c-4db2-8de2-524ffeffa915)

as a user i have no idea what is happening

**Comment by zaelgohary** [comment]
Already done [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/cc922858032e61609526eee503e27aa484dece04#diff-5de8e8967563e9dbb2e0d2676373b261516fa8521f33004a9c2e674e91ff0b07R21)
