### ISSUE TITLE
Console error from stellar address page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#54]
### Description

Error is shown once I open the stellar address pop up.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/225589050-fc22f49a-d95b-4f93-be7c-5d08e3c6119a.png)

**Comment by 0oM4R** [comment]
the issue is the text field has an asynchronous function `swapAddressCheck` in its validation rules.

**Comment by 0oM4R** [comment]
Update: waiting for dashboard release

**Comment by mohamedamer453** [comment]
Verified on devnet.

The mentioned error no longer appears in the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/563a7f9d-b56f-4095-a71a-6303c24ee1dc)
