### ISSUE TITLE
change picking a node to `finding a suitable node to deploy on`

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#540]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d7d8b3bb-c4a2-466d-92e9-d8c0f7b3e205)

**Comment by A-Harby** [comment]
Verified, 0faca50.
Messaged was changed to `finding a suitable node to deploy on`.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/29d4a53e-08f9-40fb-8b40-11aabb9ceab7)
