### ISSUE TITLE
Cannot read properties of undefined (reading 'wireguard')

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#542]
### Description

Whenever I try to open Kubernetes deployment details, it doesn't open & I get this error in the console.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/34bd7a27-48e3-48ab-a477-40a967d09019)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Kubernetes deployment details and cluster management pages are fully functioning without any issues.

[Screencast from 13-06-23 12:51:45.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fea9ae56-0236-4ef8-b53d-7b61f738f6b9)
