### ISSUE TITLE
Weird behavior with the cursor in the rootfs field 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#544]
### Description

Weird behavior in the rootfs field where the cursor returns to the start of the line when a decimal value is entered.

mentioned before in #310 

> ### Root FS

> - The this field sometimes shows weird behavior where it returns the cursor to the first line and sometimes it changes the numbers to 0 

> [TF Playground _ Micro Virtual Machine.webm](https://github.com/threefoldtech/playground/assets/101194226/46844f1f-b99d-4b1a-9145-40c25f75cb1e)

**Comment by MohamedElmdary** [comment]
This issue can be caused due to different reason but I think it's cause due to disabling rootfs field while validating

**Comment by MohamedElmdary** [comment]
This issue is no longer exists in new playground
