### ISSUE TITLE
Update deployment titles

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#545]
### Description

Remove `a` & `an` & `instance` from the title of each deployment

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a297dafc-9afe-4faf-a178-fa1c9b7830fb)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ae68f010-c278-42dc-b59a-e13003c931e0)

The only solution that doesn't have it in the title is `Caprover` and imo it looks much better.

or to simplify it even further i think it would look better if the title is the name of the deployment only.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/10ce4d20-59fc-445f-b9c9-4e9d0dd881df)

**Comment by xmonader** [comment]
will be fixed in #566
