### ISSUE TITLE
Algorand: Update capacity when selecting a different node type

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#546]
### Description

Capacity for algorand nodes should be updated according to the node type. as seen in the video below the values doesn't change when you switch between node types and in comparison is the same flow from the old weblets where the capacity used to change with each node type.

[Screencast from 12-06-23 13:21:39.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/43aeb2a1-df24-407c-9f15-d60ed3d1f1f0)

**Comment by MohamedElmdary** [comment]
@mohamedamer453 What if the use wrote his own values and then he switched the network or type? why should we update the values in case the user decided he is going to set his custom ones?

**Comment by mohamedamer453** [comment]
I think mainly because the flow is firstly selecting the Network/Node type and based on that the user will add the needed resources, and i think it's a better flow to add the minimum acceptable resources instead of showing an error message while changing the node type.

**Comment by A-Harby** [comment]
Verified on Devnet, 9227221.

Values were updated.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3116b81f-3e94-4c72-b58d-c61d568dee60)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/edd14489-c8b6-47a6-8d99-4d6bd6d3778d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2ff601c6-6ef3-4522-b29e-c2212c1ad63f)
