### ISSUE TITLE
Contract list stuck loading in a failed connection

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#548]
### Description

When there's a connection error or slow internet connection, Contract list is stuck at loading like this and this error is shown in the console. 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fb756063-7740-452e-ade0-eaabf224dbcb)

**Comment by xmonader** [comment]
Should we flag this as a known issue in the release notes?

**Comment by AlaaElattar** [comment]
- I've tried multiple situations and they were handled 

![Screenshot from 2023-08-16 17-03-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/16b2eca6-ee32-4cbc-b1fe-2755cf41736a)

![Screenshot from 2023-08-16 17-06-19](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/54944491/c1251afc-5aea-4afa-b8c0-5a8ab6dbfd5f)

**Comment by A-Harby** [comment]
Still happening, steps to reproduce:
1. Login and go to Contracts.
2. Change network to Slow 3G. 
3. Press Refresh button.
4. Repeat step 3 until it happens.

[Untitled_ Aug 17 2023 9_47 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e8b68541-27dd-485a-8183-577dfb0b8f3e)

It's not a common bug but it will happen if user has a bad network or grid proxy/graphql is having a connection error.

**Comment by khaledyoussef24** [comment]
verified 
it never gets stuck may take a long time to load but works fine
[Screencast from 12-27-2023 06:54:26 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/15030e74-be37-4bbe-8f71-ded4beb1a33b)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 842ebef

This is a random issue,
I tried multiple times did't happen with me.
so please re-open if happen again.
