### ISSUE TITLE
group network options under "networking" and make them collapsed by default

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#552]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/a54050f5-cbd3-41d3-926c-e4916b9c034f)

Also make them checked by default too

**Comment by 0oM4R** [comment]
ui ready; need to use it on weblets,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d82ccf9a-9329-4444-b646-9ad52e44d0e8)
![Screenshot from 2023-06-13 20-08-55](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0b2e719b-1105-4b8d-a781-9fa21cc55a50)
and if the user turn off all options it can't be collapsed till the error resolved 

[Screencast from 13 يون, 2023 EEST 08:11:07 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/9ba21a4c-ea15-463d-b50d-8748504f2a36)

@xmonader  any idea?

**Comment by 0oM4R** [comment]
__status__: #597 ready for review

**Comment by A-Harby** [comment]
Verified 50b986e

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c4c50f8-c64d-4176-94d3-e24423de722d)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a7b4976-7d5a-4227-970c-79c30af9dae6)
