### ISSUE TITLE
rephrase deployment cost message

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#553]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b545461c-892b-4910-a6c5-6763b5a5818f)

```
Your deployment costs 511.2 TFTs or 6.134 USD/month based on the cloud resources (CPU, RAM, SSD, Public IP) selected  [Learn more about the pricing and how to unlock discounts.](https://manual.grid.tf/cloud/cloudunits_pricing.html)
```

**Comment by khaledyoussef24** [comment]
deployment cost message rephrased 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1d443bde-5ffe-4e62-ac85-1f564266d33b)
