### ISSUE TITLE
wrong link in the contracts page description 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#555]
it links to https://manual.grid.tf/tfchain/tfchain_external_service_contract.html

**Comment by 0oM4R** [comment]
__Status__ #599 ready for review

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now it redirects to https://manual.grid.tf/tfchain/tfchain.html where it explains each type of contract (Node, Name, Rent), billing, grace period, etc...

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ff081239-8c4f-4959-8ca9-ad5bf0c5d192)
