### ISSUE TITLE
table rows should be clickable and show the details page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#556]
I expect the row items to be clickable to open the details page

**Comment by MohamedElmdary** [comment]
Will check if this feature is implemented yet in vuetify3

**Comment by xmonader** [comment]
Status?

**Comment by A-Harby** [comment]
Verified, Devnet 7f4cb37.
the table rows are now clickable too.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/75955436-9d00-4fa9-ab60-b0bf9b01b64a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2cb09eba-1fbc-407b-abc3-14c0c8bbafb2)
