### ISSUE TITLE
add custom packages for microvm and fullvm

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#557]

**Comment by MohamedElmdary** [comment]
Can you provide the required packages? @xmonader

**Comment by xmonader** [comment]
microvm

- 1cpu 1ram 25 disk
- 2cpu 4ram 50disk
- 4cpu 4ram 100disk

fullvm

- 1cpu 1ram 25 disk
- 2cpu 4ram 50disk
- 4cpu 4ram 100disk

**Comment by xmonader** [comment]
We should call it `Storage (SSD)`

**Comment by mohamedamer453** [comment]
Verified on devnet.

Packages were added with the resources mentioned above, each package was tested and the selected resources are applied correctly in the deployment details and in the vm itself.


### Full VM

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f83d3cb2-aab8-4d0c-bc28-460029f55a77)

### Micro VM

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/73d1a542-24c0-4ba5-ba37-f08277e318b0)
