### ISSUE TITLE
lowercasing all default values

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#559]
- lowercase all default values in playground
- add validation over lowercase in inputs

**Comment by mohamedamer453** [comment]
### Solution Name

The generated names now have the prefix only. i think it was better before when a random valid string was generated after the prefix, and it'll prevent errors if the user tried to deploy another instance without changing the name.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/956cb395-4e18-4602-b814-00512e2e3dbe)

### Disk Name

There's an `undefined` next to the generated string. and the error message should be `Name cannot exceed 15 characters` to be consistent with the other error messages in the playground.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/3331f9d1-d0e8-4609-8215-ff45a754e9d2)

### Cluster Token

Invalid cluster token was generated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0b7b63c9-c5fb-410b-a7c8-3b89c4223db3)

### peertube email field

This field should be empty, instead solution prefix was generated there.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f99bbb43-3850-48fc-a15a-05bdf3d1d53d)
