### ISSUE TITLE
Threefold price swapping -> TFT exchange rate

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#561]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/9d838c9c-5d5e-4201-9f34-f0030f1b0557)

**Comment by A-Harby** [comment]
Verified on QA, 2.0.0-rc14.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6b82fc5a-f608-4ea0-a449-d49d55be3e4d)
