### ISSUE TITLE
support info markdown pages

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#563]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/62793ba0-3076-4d6e-8d83-d26c48c7524a)

**Comment by khaledyoussef24** [comment]
verified and works fine for all solution.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/142710be-776e-435b-9b3e-5c14a4e3ad26)
