### ISSUE TITLE
Improve Contracts List

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#569]
- [x] Move checkbox into `#` column
- [x] Turn `Show Details` into icon button (icon: eye)

**Comment by khaledyoussef24** [comment]
icon eye changed 
![Screenshot from 2023-06-19 14-19-07](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/569eb450-a7fa-41b6-9d0d-a367f033dfec)
but the check box and the numbers still the same
![Screenshot from 2023-06-19 14-19-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f5b79850-1344-4e0e-8f69-9b402021a1b5)
