### ISSUE TITLE
Add Solution Provider page

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/tfgrid-sdk-ts#57]
A seperate tab that can:

- List active solution providers
- Let a user create a solution provider object 

## Listing active/inactive solution providers

Storage map on tfchain: `SmartContractModule`:`SolutionProviders(id)`

Clearly show which are approved and which ones are not

## Creating a solution provider

See screenshot:

![image](https://user-images.githubusercontent.com/17138347/219081383-acd278a4-c06a-4464-8ddd-640474736e1a.png)

After submitting this, the user that created this object should create a forum post about the who/what/why of the solution provider. We should clearly indicate this when the user is creating this

**Comment by xmonader** [comment]
solution provider is being deprecated
