### ISSUE TITLE
Get TFT not working for dev net from dashboard

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-ts#571]
### Description

I tried to fund my balance from dashboard  https://dashboard.dev.grid.tf/ but for some reason it is failing 

### Steps to reproduce

- go to https://dashboard.dev.grid.tf/ 
- login with your account
- click get tft button on the top
### screenshots
![Screenshot from 2023-06-13 16-26-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/1689456/2481cab2-a642-4266-b8c2-17fa92ed8b0e)

**Comment by AhmedHanafy725** [comment]
ALICE wallet was out of funds. it's funded now but a better error message would be better

**Comment by xmonader** [comment]
As this is not affecting testnet or mainnet, it can be moved to 3.12

**Comment by khaledyoussef24** [comment]
verified works fine now
[Screencast from 08-29-2023 10:40:10 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/27651ba4-0e23-44fc-8b1b-3922ebac431a)
