### ISSUE TITLE
Rename Zero-Os hub to 0-Hub

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#574]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/c0f48279-f04d-4c2a-b8f7-ac088a8b45a0)

**Comment by A-Harby** [comment]
Verified on QA, 2.0.0-rc14.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2f2ec039-75cd-4a33-82e5-f04c8baec879)
