### ISSUE TITLE
dashboard DAO: clarify the status of the proposal

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#576]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/859b31a3-45de-4e82-a5b5-26e4380e2887)

right now i'm assuming 100% blue = yes and 100% white = no?

**Comment by 0oM4R** [comment]
My suggestion is to keep the progress bar as it is and  replace the percentage with `rejected` and `accepted`
@xmonader what do you think?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/7fffbd68-2aa1-46f2-9e5d-b27a44483468)

**Comment by xmonader** [comment]
Nice!!

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now the status of the proposal is clear.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5c9d0f03-14e5-494c-bbb8-e9391a3285d9)
