### ISSUE TITLE
dashboard: your farm page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#577]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/b4fd0096-d83e-4465-b93d-08421c9dbc1a)

please add tooltips over the buttons of v2 address and view bootstrap explaining why do I need to click on these

**Comment by xmonader** [comment]
V2 Address -> change to Stellar Address, highlight `Where minting payouts get sent to`
View Bootstrap -> Download a ZOS image for your farm nodes

**Comment by A-Harby** [comment]
Verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/d61d3a7e-5126-4f84-911e-fde134d5a816)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f9ea4d5b-9c05-4338-b529-1ad0c9e2ad4f)
