### ISSUE TITLE
dashboard balance summary touch ups 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#579]
![image](https://github.com/threefoldtech/tfgrid-sdk-go/assets/64129/ec4a9f8c-945f-486a-ba21-cb7d519cbc4a)

It looks very dull and also info needs to be linked for reserved/locked tokens too

**Comment by ehab-hassan** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/377e5074-ef56-4309-b756-fa12aba448e0)

Figma file 
https://www.figma.com/file/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=49-73&t=7SFfbpu65SPXYaN1-4

Icon is here but white:
![balance](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/26dbd514-f050-4029-865d-78da06c075ad)

**Comment by ehab-hassan** [comment]
@Mahmoud-Emad modified 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/3c8816c6-40d9-4381-9b96-4a834250e2e1)

**Comment by Mahmoud-Emad** [comment]
working on it in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/621

**Comment by Mahmoud-Emad** [comment]
Should be improved in #621

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.

Balance summary updated with new icon and style.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f8ecf4a7-7584-489f-a32a-d7d018682922)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e916905d-6caa-4b85-9419-1e6eaee2f753)
With a pointer to the locked TFT info https://manual.grid.tf/tfchain/tfchain.html?highlight=locked#contract-locking.
