### ISSUE TITLE
explorer: add a note on the online filter that standby nodes are shown with the offline nodes 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#583]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/022f1517-f65a-46d5-bcea-c6444877cd3b)

apparently it's shown with the offline nodes

**Comment by ramezsaeed** [comment]
will use a tool tap on the switch

**Comment by mohamedamer453** [comment]
Verified on qanet dashboard `2.0.0-rc14`

Now a tooltip appears on hover mentioning that standby nodes are not included when the online only filter is active.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4a9f4877-49f3-4d7b-86da-009f493671cd)
