### ISSUE TITLE
node status flair isn't correct

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#584]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/20d8dbc8-cdd5-4805-be58-1c23434e4b59)

afaik the reporting happens every 40mins, there was a point where we reported the node as down if it missed 2 cycles = 80 mins? please update to the latest accurate info

**Comment by AhmedHanafy725** [comment]
require https://github.com/threefoldtech/tfgrid-sdk-go/issues/198

**Comment by xmonader** [comment]
https://github.com/threefoldtech/tfgrid-sdk-go/issues/198 is now in verification and can now proceed with the issue

**Comment by xmonader** [comment]
The updated text should say every 90 mins

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc3.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4764b343-b372-49e6-906b-4f80475535d1)
