### ISSUE TITLE
Relay case in node twin details

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#587]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f4f6de79-6d95-457c-95f5-7992b72f45db)

Not sure why this is in all caps, while the rest are normally capitalized

**Comment by mohamedamer453** [comment]
Verified on devnet.

The case of the `Relay` in node details was updated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e1447466-5222-4352-9501-ddd50dbc5214)
