### ISSUE TITLE
node details review

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#588]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/387c61e0-ee61-4a53-b6d0-af52aad0ed2a)

CPU Resources Units, .. etc seem to be weird
Please use (CPU: X cores, Disk (SSD): .. , Disk (HDD): .., RAM: ... )

**Comment by A-Harby** [comment]
Verified on QA, 2.0.0-rc14.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/47e879d1-f9bf-4c58-a2d2-3eab5a568a3d)
