### ISSUE TITLE
node id filter doesn't show any data

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#589]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/b43958c6-c3ee-4154-8399-b2efd2af1a6f)

compared to when clicking on the choosing the filters list I can see a drop down
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/8e86442e-fb9b-42f4-8d66-b777e4507346)

**Comment by 0oM4R** [comment]
what is the expected behavior here? 
if the user click on the expand should list all available values to select from?
for example, if the user selects node id and then expands the filter field should list all available node ids to pick one?

**Comment by AhmedHanafy725** [comment]
It needs to be an input field instead of being dropdown.

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.
Input updated
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7a03876e-2c64-4f55-b68b-17cea105dd3e)
with a validation to only numbers.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a2ad80f3-59cb-4e0f-8c7c-13b9392c649b)
