### ISSUE TITLE
High CPU usage on DAO page

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#59]
### Description

I noticed a very high CPU usage (+- 75%) whenever I open the dashboard and looks to be when I open DAO page. 
CPU usage goes down once I close the page. 

<img width="318" alt="Screenshot 2023-02-14 at 09 40 12" src="https://user-images.githubusercontent.com/31733464/218683269-7d3c65fa-e69d-4e05-9f89-7ee48baaace9.png">

**Comment by scottyeager** [comment]
I checked this on devnet and the change looks good. According to the browser task manager, the CPU load for the tab drops to 0 after loading is complete.

Can we get https://github.com/threefoldtech/tfgrid_dashboard/pull/631 pushed to test and mainnet now as a patch ahead of the next release?

**Comment by mohamedamer453** [comment]
I'm closing this issue since it was already verified before and no further input was added.

> Can we get [threefoldtech/tfgrid_dashboard#631](https://github.com/threefoldtech/tfgrid_dashboard/pull/631) pushed to test and mainnet now as a patch ahead of the next release?

I think it's planned to be released in 3.10
