### ISSUE TITLE
update resources calculator with more friendly names

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#590]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/fdcc83d3-983e-4dd4-aa48-00ddf0869bf2)

CPU, Disk SSD, Disk HDD, RAM

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.
calculator resources were update with more friendly names.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f03a1bd0-8b9e-4b74-b330-d8d72b5ed58a)

But info weren't added, which would be a good hint to the user about the inputs.

**Comment by A-Harby** [comment]
Closing the issue as main comment was done.
And seperating amer suggestions to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/681.
