### ISSUE TITLE
zero-os bootstrap isn't loading

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#591]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/73157ded-67a8-4bd7-b1ee-94784fe80071)

also Please make the menu item exactly like this `[Zero-OS Bootstrap](https://bootstrap.grid.tf/)`

**Comment by xmonader** [comment]
could be caused by https://github.com/threefoldtech/tf_operations/issues/1738

**Comment by ramezsaeed** [comment]
Fix text only, and the functionality of bootstrap will be handled in the other issue in operations.

**Comment by xmonader** [comment]
Been resolved by serving the files directy in the hub and bootstrap without the need for the CDN
