### ISSUE TITLE
Add a loading page

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#592]
### Description

A loading page should be added to the playground/playground while it's loading to give an indication that something is happening in case of slow connection. as mentioned originally in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/489#issuecomment-1586095666

> ### Opening the playground
> This was calculated from the moment that the url was entered to the moment that the website loads and the loading spinner stops.
> 
> > This was done in an incognito tab to simulate opening the playground for the first time. without having anything cached.
> 
> Using a normal connection it was very fast and it took around ~3 seconds however with a throttled connection it was extremely slow compared to the normal connection and it took around ~160 seconds.
> 
> ![image](https://user-images.githubusercontent.com/101194226/244927590-941fcadf-468f-4a6e-a966-309d0e59f617.png)

so having a loading page instead of just a while page for this duration will give the user a clear indication that something is loading and maybe if it took more than a minute then a message should popup mentioning that this is taking longer than expected due to slow internet connection.

### Implementation

- I'm not quite sure about the implementation but here are a few suggestions on what it could look like:
   - A page with threefold logo and a progress bar showing the loading progress.
   - An animated version of the threfold logo could be a nice touch and would improve the experience.
   - A message mentioning that the website is loading. not sure what the correct phrasing for this message is.
   - A message that appears if the loading took more than one minute mentioning that "this is taking longer than excepted due to slow internet connection", again the phrasing could be improved.
   - It would be great if it could be done as separate component that could be used for all of threefold's websites(playground, dashboard, stats, getmastodon, etc...).
   - This website has a good variety of loading screens/patterns/logos and the ability to adjust/animate according to the desired design. could be helpful. https://loading.io

**Comment by mohamedamer453** [comment]
Update:

Still researching, trying to figure out the logic behind the page and how will it be implemented.

An option would be creating a loading component and checking the ready state of the page in the `mounted` hook. and i'm currently investigating this option.

**Comment by mohamedamer453** [comment]
Update:

The loading page was implemented in #1321 and the pr is ready for review

**Comment by khaledyoussef24** [comment]
verified using a slow connection the loading page works fine
before :
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d5323deb-b712-44eb-aaf2-5ca1ea210015)
after:
[Screencast from 11-22-2023 07:15:31 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0d90d12a-4290-4060-a38c-c3e3626b2957)
