### ISSUE TITLE
Add a link to tft price/info page from CoinGecko or any other trading website next to tft price

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#593]
### Description

Add a link to tft price/info page from CoinGecko or any other trading website. Inspired from [foldit.tf](https://foldit.tf/#/dashboard)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fa70e647-83f9-48ab-a8f5-94e1578e808e)

### Implementation

An icon could be added next to `TFT`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/929fd0e4-35a4-4577-bfe1-5c761a39f1b0)

This icon will redirect to any trading website that has full info/history/live price of tft.

https://www.coingecko.com/en/coins/threefold?__cf_chl_tk=Anz5VJMTrLAYi1WiVmZtV96KscSlZ7dkOScHhDXQBcI-1686732252-0-gaNycGzNDWU

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/85aaddab-f60c-4093-be1d-6119c6ac403d)

**Comment by xmonader** [comment]
Current information is coming from tfchain pricing module, Should be linked against the new manual information

**Comment by xmonader** [comment]
update in the more info link please use this link https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?asset[]=TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1&filter=markets&market=USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN-1

**Comment by Mahmoud-Emad** [comment]
Should be added in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/665

**Comment by A-Harby** [comment]
Verified on Devnet, 2.1.0-rc1.

Link was added pointing to https://stellar.expert/explorer/public/asset/TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1?asset[]=TFT-GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47-1&filter=markets&market=USDC-GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN-1
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4025b876-a68d-4911-83be-41bb2aaecb9b)
