### ISSUE TITLE
Provide a design for 404 page

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#595]
Please provide a design for 404 page follows the layout of new playground as it's currently showing `not_yet_implemeted`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/7ce9700f-32c6-4382-aa3c-77b4b7ff6902)

**Comment by ehab-hassan** [comment]
<img width="1920" alt="Frame 1" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/ae99ebd1-2c23-415e-b29b-8737377613a2">
<img width="1920" alt="Frame 2" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/7c1943c8-8afc-49a6-8885-c45a8035c8b5">

https://www.figma.com/file/da9QInhria3pF8wqIM0rcY/404-Page?type=design&node-id=1-2&t=g6H1y94m8lazxsQj-0
![404_img](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/57cce4fa-a405-4c4d-a5a0-2e2d169c0e38)
