### ISSUE TITLE
Build workflow failed sometimes 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#611]
### Description
Also after rerunning it it works fine; 
I think the issue is with Lerna version,
if you check the passed one:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/d3009184-9c8f-4e3e-958a-edb571903e36)

- example : https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5276161122/jobs/9542507182

### Logs/Alerts

````
Run lerna run build --no-private
  lerna run build --no-private
  shell: /usr/bin/bash -e {0}
lerna notice cli v7.0.0
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.
Error: Process completed with exit code 1.
````

**Comment by A-Harby** [comment]
Verified and the last few workflows were ran sucessfully .
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/623
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/playground_build.yml
