### ISSUE TITLE
update Home page 

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/tfgrid-sdk-ts#612]
please change the home page playground size and the images need to be at container and use the image attached it ll work better with white and dark mode.
no need to add Threefold logo it is already at the nav

![photo_2023-06-15_10-49-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/8d6c81a0-ce53-452c-b5fb-41ba9d973f8b)

![capacity](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/a818bd30-79ec-4631-8b73-4bf2deedef97)
![cores](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/f97e79d2-aa8c-4972-9785-f4c62bc06b8a)
![countries](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/b0b494e9-7941-4f1c-97ff-93e768205cd5)
![Nodes](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6633ab0c-61e8-4c39-b4ab-eed320673e3b)
![grid_map](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/6e2799c5-b0a3-4b26-a0a7-6a6c1029b150)

need to be like this
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/07fa3954-d364-4a3d-a705-49b9e4759803)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/f958459d-b9eb-4bf4-964b-491e8da61b21)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The landing page was updated with the provided images. and the text, map now don't exceed the mentioned boundaries.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/734d7fda-1a21-4a3f-9fd8-45198a88c84f)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/144d6a89-2c63-4aac-b121-6ac0abef733c)

And the extra threefold logo was removed.

**Comment by ehab-hassan** [comment]
@MohamedElmdary Perfect Thanks Rabie :)
