### ISSUE TITLE
Building workflows failing

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#623]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/58c51953-248c-4a80-b708-7a424f405084)

This issue appeared after merging this PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/619

**Comment by zaelgohary** [comment]
@MohamedElmdary I checked all workflows that ran after #619 and they all succeeded as per the screenshot below. Can you provide the link for the failing workflow?

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/90b1041a-d57b-4f11-8a4e-50771f79cc94)

**Comment by zaelgohary** [comment]
I commented [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/617#issuecomment-1593055027). Should be fixed now.

**Comment by A-Harby** [comment]
Verified and the last few workflows were ran sucessfully . https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/playground_build.yml
