### ISSUE TITLE
Add link to manual in navbar and sidebar in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#626]
Add link to manual in navbar and sidebar in the dashboard 

Note: in the navbar maybe with `?`/alt text "Help" item

**Comment by A-Harby** [comment]
Verified, on QA 2.0.0-rc14.
Button with text 'Help' was added to the navbar, navigating to https://manual.grid.tf/dashboard/dashboard.html
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/804f73d6-8306-4e09-8b50-8f80cf452408)
