### ISSUE TITLE
Huge amount of requests is being made in the playground

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#627]
### Description

A huge number of requests is being made to graphql and it increases the cpu usage significantly.

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1e987ea0-d706-4884-9e4d-fe2dcc46b609

### Logs

The 2 requests are:

- graphql

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/91e20f92-6e78-4420-bf0e-844d5bc1283d)

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1bb8ffd9-ea59-4bc1-93d4-bd2c6d42de38)

```
{"query":"query { __typename }","variables":{}}
```

- gridproxy

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a194f380-e59c-44d6-b2e2-0f58902fcec5)

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/acced63c-5be2-4f0e-a6b4-ead5d2be18a1)

**Comment by xmonader** [comment]
Add the graphql payload please

**Comment by mohamedamer453** [comment]
>   ![image](https://user-images.githubusercontent.com/101194226/246652094-1bb8ffd9-ea59-4bc1-93d4-bd2c6d42de38.png)

@xmonader  Is this this the required payload or is it something else?

**Comment by AhmedHanafy725** [comment]
these 2 calls (graphql + gridproxy) to check if they are up and this happens once when trying to connect with the client. not sure why the connect method is called too much

**Comment by xmonader** [comment]
Should be fixed now with the 2.1.0-rc1 release on devnet
