### ISSUE TITLE
Config file is not updating

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#629]
Even after changing TFCHAIN_NETWORK to qa, config file is not updating
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ffcb0327-b92e-4ae1-a5ef-df2e9193a566)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/cc6108e9-ff91-4b65-935c-8dff7d5c7799)

**Comment by mohamedamer453** [comment]
Verified.

After exporting the version and network, and executing the env file using `source scripts/build-env.sh` the new config was generated and the changes were reflected in the `config.js` file.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2f69d663-7b7c-4b25-babc-23ae56394395)

and after executing `yarn serve` i was able to verify that the correct version and network were applied.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fdfab625-2538-474f-8d69-a6490400215b)

**Comment by khaledyoussef24** [comment]
verified 
![Screenshot from 2023-06-21 11-28-31](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/fab442ee-7283-4f5d-adbc-8117c64f39f8)
![Screenshot from 2023-06-21 11-08-32](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d91b6da3-267d-4237-90fc-e7b792a390dc)

**Comment by mohamedamer453** [comment]
Verified.

I followed the same steps mentioned in the comment above but this time the `config.js` file was added to the same directory that i executed the command in.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/15382418-2f18-468b-aade-341aa95f004a)
