### ISSUE TITLE
Textbox showing error without using them

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#630]
First time accessing the site I am getting errors for Password textbox I didn't interact with:

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/60783742/1b46d1ee-cade-42e7-8b17-3e7a097b9656)

I think it would be better if it should show an error when I interact with it and leave it empty.

**Comment by A-Harby** [comment]
Verified, Devnet 9227221.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/7eeec843-e7ff-4f75-a4d6-5208a25805dd)
