### ISSUE TITLE
Revisit UI/UX of playground

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/tfgrid-sdk-ts#632]
The idea here is to create a better experience for our users

**Comment by ehab-hassan** [comment]
According to our meeting 

- [ ] We'll add the deployment costs calculated to the right so the user can see the price updated without att details without scrolling.
- [ ] Remove the balance from the nav and add it at the top of the deployment costs calculated (the new).
- [ ] change the size of Connect your TFChain Wallet and Connect your TFchain Wallet pop-up (It is too wide)
- [ ] add license checkbox at Connect your TFchain Wallet.
- [ ] Change Pinck color to blue to match with new branding.
- [ ] Show the contracts page in a better way.  

@rkhamis @AhmedHanafy725 If there is something missing please update the issue

**Comment by ehab-hassan** [comment]
first edition 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/fab61429-933a-46ab-b591-04ea6e0986ec)
https://www.figma.com/file/A16wcW2xqLCWWxkj9NduRt/Playground-UI%2FUX?type=design&node-id=0-1&t=Zszk7gHTmjjeQOvA-0

**Comment by ehab-hassan** [comment]
what do you think if we add the deploy button to price details, it'll be clearer?

![playground](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/51597d61-7b7f-4297-b78f-dd297f182139)

Also, this pop-up connects TF chain wallet
![ConnectTF1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/ea46b9c7-1b17-4cbf-bec8-8889a08e7b26)
<img width="1920" alt="ConnectTF2" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/d7901cc3-9a90-4003-bf4f-470001605fa8">
