### ISSUE TITLE
Failed to create any deployment on playground

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#634]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/a877044c-a397-4feb-a5cc-48e70b42da8e)

This happens because the name field in all deployments is the solution name.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Solution names were fixed and now a name is generated after the prefix instead of the prefix only.

[Screencast from 18-06-23 18:08:33.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1f577f98-143a-40da-bcd9-6f2a167c564e)
