### ISSUE TITLE
Add the extra fee while calculating the node renting price

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#637]
require: https://github.com/threefoldtech/tfgrid-sdk-go/issues/201

**Comment by A-Harby** [comment]
There's a wrong calculation on the dedicate nodes table.
Price of node 93 is 60.73
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/57b7b515-1913-4be5-8ee1-947a5dbf8f49)
but this this for a Twin with no TFTs (no staking or packages).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f9c19f29-79cc-4cfb-a9e2-00514a94db37)
It should be 48.58 ( Default Package ).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/77d0b139-1c12-4f77-a46a-20d444d440fa)

**Comment by A-Harby** [comment]
Verified. 
Calculation here is done correctly but there's an issue and will be open separately. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/362a3858-445e-4624-ad59-7340e87603aa)

  https://github.com/threefoldtech/tfgrid-sdk-ts/issues/796
