### ISSUE TITLE
Add new option for deploying a fullvm with GPU in playground

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#638]
require: https://github.com/threefoldtech/tfgrid-sdk-ts/issues/464

**Comment by xmonader** [comment]
dashboard or playground?

**Comment by AhmedHanafy725** [comment]
> dashboard or playground?

issue title is updated

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/711

**Comment by A-Harby** [comment]
Verified on Devnet, 0ab73db.
GPU option, List of the available rented node and GPUs available on it were added to the FullVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/48168b45-70e2-4081-a87b-01cfb4d02ac9)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f952b5c-6add-4417-ad5c-8df1c199463f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4fada73e-edb4-4010-8ed5-6334e4b55cf8)
