### ISSUE TITLE
Login/Signup flow improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#643]
### Description

Login/Signup flow adjustments.

### Login

A clarification message should be added above the field mentioning that this password is the same one that was created while signing up/visiting the playground for the first time.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b3bada09-5deb-43aa-941c-64a1dc1d5e20)

Password validation message shouldn't appear before entering anything in the field.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d9858799-42b1-4554-9f64-fe6427149fde)

Tooltip message should start with a capital letter.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cd784a17-4fc3-41be-913a-8bdca608afe8)

### Signup

A clarification message should be added mentioning that this page is for "creating an account" not sure what the correct phrasing should be.
A message should be displayed above each field mentioning the function of each field, this message could be the same one as the tooltip message.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f24982f6-74e2-4366-982d-97c8b3e053d7)

Mnemonic validation message shouldn't appear before entering anything in the field.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6000d3d6-de1c-4568-824f-0bb27029416c)

Tooltip message should start with a capital letter.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/74528aed-ad30-4357-a183-53c1dc801bdf)

lastly if the user already has an account then a warning message should be displayed in the signup page mentioning that in the case of creating another account with a different password then it will overwrite the current one.

**Comment by mohamedamer453** [comment]
Another good indicator would be adding a third field `Confirm Password` just to be a clear indication that this flow is for creating a new account.

**Comment by khaledyoussef24** [comment]
verified 
clarification message for clarifying that You will need to provide the password used while connecting your wallet.
![Screenshot from 2023-06-20 15-14-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f634d1ee-e3db-4963-8b94-70bb4a1fef6c)
the tooltip message starting with capital
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/77c1aee8-643f-458f-b9ff-4ae7cc2e21d4)
while inserting wrong password
![Screenshot from 2023-06-20 15-14-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/79ce6ab3-16d9-4c04-afee-264a941489ed)
the sign up tab
Mnemonic validation working fine
added confirm password too
![Screenshot from 2023-06-20 15-14-00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/316409a6-54b7-47c3-a747-29d3a88f9335)
