### ISSUE TITLE
Workflow failing due to node version

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#644]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/cd9836d1-4294-4698-8fad-b42ea0c9d7b5)

**Comment by A-Harby** [comment]
Verified,
All the workflows with node version were updated to 18.x and were succesfully run with no issue in the last build https://github.com/threefoldtech/tfgrid-sdk-ts/actions.

The remaining test workflows should be updated in [here](https://github.com/threefoldtech/tfgrid-sdk-ts/pull/653).
