### ISSUE TITLE
Update docs, lerna and dashboard

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#645]
### Description

- in [readme](https://github.com/threefoldtech/tfgrid-sdk-ts#readme)  we need to mention the required versions of node and lerna.
- and for the [dashboard](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/dashboard/docs/getting_started.md) need to edit `Adjust your config.js file as per your environment` section as it currently should run the script in the dashboard not in public

**Comment by 0oM4R** [comment]
@AhmedHanafy725  can you confirm the required versions please?

**Comment by 0oM4R** [comment]
> @AhmedHanafy725 can you confirm the required versions, please?
As we discussed, node 18 and Lerna 7.1.1

**Comment by mohamedamer453** [comment]
Verified.

Versions were added in the [requirements](https://github.com/threefoldtech/tfgrid-sdk-ts#requirements) section.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4556d1a2-0810-4814-b3ea-cac3648366d2)

and the paths were updated in the dashboard docs.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fa6b0ffc-4bf2-4ac0-b251-24c31a1c3b42)
