### ISSUE TITLE
Wrong disclaimer text on https://playground.test.grid.tf/

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/tfgrid-sdk-ts#648]
### Description

The text starts with `This is a environment.` instead of `This is a test environment.` or `This is a testing environment.` as it is on https://play.test.grid.tf/

**Comment by Mahmoud-Emad** [comment]
should be improved in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/655

**Comment by mohamedamer453** [comment]
Verified locally.

I changed the network to testnet and served the playground locally. and the disclaimer text was updated as seen below.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2726e6b0-239c-4c52-8668-1fda11fb2cd2)

and for qanet it was also updated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c21172df-2641-4781-bb01-d097fec5852f)

**Comment by robvanmieghem** [comment]
@mohamedamer453 while at it, can you correct "intetrnal" to "internal" for qanet

**Comment by mohamedamer453** [comment]
> @mohamedamer453 while at it, can you correct "intetrnal" to "internal" for qanet?

will be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/687
