### ISSUE TITLE
(Mainnet verification) Node download receipts pdf formatting

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/tfgrid-sdk-ts#65]
as of now the pdf only shows the first 8 receipts of a node, need to make it show all receipts of a node in the farm nodes receipts summary

**Comment by Omarabdul3ziz** [comment]
update: wip in this pr #814

**Comment by Omarabdul3ziz** [comment]
update: fixed in this pr #814

**Comment by khaledyoussef24** [comment]
Verified on mainnet
Downloading minting pdf files for the receipts working fine
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8121e0ad-4f94-49ad-ace6-e856c02ec37a)
