### ISSUE TITLE
Outdated manual link in the dedicated nodes page

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#658]
### Description

Old docs link in the discount levels description. https://library.threefold.me/info/threefold/#/tfgrid/grid/pricing?id=discount-levels

Should redirect to https://manual.grid.tf/cloud/cloudunits_pricing.html#discount-levels

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2f118cbe-e888-45a3-a87c-af3cdc35b2cb)

**Comment by 0oM4R** [comment]
__Status__: waiting for release

**Comment by khaledyoussef24** [comment]
works fine now :
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/90b2eb17-3cf0-4d72-b097-1334b678bb03)
