### ISSUE TITLE
login button is disabled in the login page

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#660]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f4790878-6612-4cbe-89d9-13f6eca42c17)

on playground.dev.grid.tf

there're also no errors in the console

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/d3182cdc-0147-4a47-b131-427d7a36ac6f)

**Comment by Mahmoud-Emad** [comment]
should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/661

**Comment by khaledyoussef24** [comment]
fixed and verified 
![Screenshot from 2023-06-20 15-03-57](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/112d6c01-c719-4fa6-baec-570187f20446)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/93a1bb19-3c48-45e9-a234-e2f341f36333)
