### ISSUE TITLE
Return special chars in password while generating

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#664]
Reverse PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/662
and fix validation to accept special chars

**Comment by A-Harby** [comment]
Verified on Devnet, 9227221.

Cluster token validation was updated to accept also the special char.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f7fc6db4-1686-44d8-ba55-74426b8a4024)
