### ISSUE TITLE
grid_nightly workflow randomly fails in the installation step with an error related to lerna

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#669]
### Description

The [`Install`](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/.github/workflows/grid_client_nightly.yml#L49&L52) step in the grid_client_nightly workflow sometimes fails with the following error.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5320494202/jobs/9634342286#step:8:43

```
lerna ERR! ECONFIGWORKSPACES The "useWorkspaces" option has been removed. By default lerna will resolve your packages using your package manager's workspaces configuration. Alternatively, you can manually provide a list of package globs to be used instead via the "packages" option in lerna.json.
```

In [this](https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5320494202) run the workflow failed this step in qa, test, main but passed in dev.

and in other previous runs it can also be seen randomly failing with the same error.

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5263690897/jobs/9514102991#step:8:46

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5275426586/jobs/9540894038#step:8:43

https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5286834638/jobs/9566649157#step:8:43

**Comment by A-Harby** [comment]
Verified
Workflow have been running sucessfully.
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/grid_client_nightly.yml
And I also run it manually and it did successed.
https://github.com/threefoldtech/tfgrid-sdk-ts/actions/runs/5505869137
