### ISSUE TITLE
contract list doesn't have more info icon

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#672]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/3ac385db-0442-46a8-b81c-527047508ef0)

**Comment by khaledyoussef24** [comment]
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/53dcba7d-8ecf-46a1-bb0f-068fb61ff695)
info icon is now found in contract list
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/caa622dc-c8a0-431d-85c2-ea03831cbf8d)
