### ISSUE TITLE
how do i logout of the playground?

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#673]
when i reopen it automatically logs me in

**Comment by AhmedHanafy725** [comment]
using this button, but I think it will be easier if this button is on the navbar beside the balance (no one will expect that it's inside)
 ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/5530a3af-1e55-4048-a5fd-51787bd4db5c)

**Comment by xmonader** [comment]
Definitely, needs to be in the navbar

**Comment by A-Harby** [comment]
Verified on Devnet, 9227221.

New logout button was add beside the balance in the navbar 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e53a9fea-50f5-41f3-b271-f68631ff35bb)
