### ISSUE TITLE
Dashboard stuck on routing when adding new router

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#68]
https://user-images.githubusercontent.com/31689104/187872830-27e9d739-8f3a-464d-a696-3aaaf942d5ba.mp4

**Comment by MohamedElmdary** [comment]
I don't this issue is still valid
tried to use dashboard but it's no longer appears

**Comment by mohamedamer453** [comment]
Issue is still present on devnet dashboard `2.0.0-rc12`

[Screencast from 11-06-23 17:06:26.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/85ca1a6e-d922-4826-98b1-8a943855cadf)

**Comment by MohamedElmdary** [comment]
@amiraabouhadid do you have idea why this is happen?

**Comment by MohamedElmdary** [comment]
@amiraabouhadid Any updates?
