### ISSUE TITLE
Adding more info on the calculator inputs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#681]
### Search first

https://github.com/threefoldtech/tfgrid-sdk-ts/issues/590

### Description

Another suggestion would be including an info section in the resource calculator page similar to the one available in [foldit.tf](https://foldit.tf/#/calculator)

### More

See the comment on the issue https://github.com/threefoldtech/tfgrid-sdk-ts/issues/590#issuecomment-1590802668.

**Comment by AlaaElattar** [comment]
- It's already handled in calculator page.

**Comment by khaledyoussef24** [comment]
in the calculator page you can access [Cloud Unit Pricing](https://manual.grid.tf/cloud/cloudunits_pricing.html#cloud-unit-pricing)
Info about each field and what does it represents is provided .
user can reach [utilization page](https://docs.google.com/spreadsheets/d/1E6MpGs15h1_flyT5AtyKp1TixH1ILuGo5tzHdmjeYdQ/edit#gid=2014089775)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1d16d952-e3b7-4747-a951-dc5f55cbd500)

![Screenshot from 2023-10-25 08-17-30](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/af7b3da8-3495-4265-a39e-fb0e92bfc8fb)
