### ISSUE TITLE
remove subnet mask from the public IP4 details form

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#682]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/30562b11-1e53-4d4b-a026-0cd2bab80be9)

the visible IP shouldn't show /24

**Comment by MohamedElmdary** [comment]
@xmonader Should we remove subnet mask also from ipv4 in table?

**Comment by A-Harby** [comment]
Verified, Devnet 7f4cb37.
IPV4 subnet mask was removed.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8e693bc6-7f20-42b0-94d6-4e953f3046d3)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6f5414fc-661d-4355-9e14-60a3fd3c5c03)
