### ISSUE TITLE
Update the disclaimer text for qanet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#687]
### Description

Update the disclaimer text for qanet.

should be `internal`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d756e8c8-faa2-4ce4-864f-b0f52ec4dcfb)

**Comment by xmonader** [comment]
I kinda disagree with this, there should be only two environments concerning the enduser mainnet env and testnet envs other than that -e.g devnet, qanet1, qanet2, .. etc- should be ephermal environments with no special handling, I'll close, but if you feel we need to discuss it further please reopen
