### ISSUE TITLE
review the dashboard UI elements

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#689]
please go through the dashboard for the minimal changes
- colors
- spaces
- form elements
- details 

Please keep in mind we will be migrating to #468 so the changes should have that in mind

**Comment by ehab-hassan** [comment]
@xmonader While we need to make all our products same theme I create Figma for a new theme for the dashboard to match with playground

note: just 2 links at side menu work as a guide for now.

https://www.figma.com/proto/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=113-50&t=WnXJoMIjxfcOFTkY-0&scaling=contain&page-id=0%3A1&starting-point-node-id=124%3A196
