### ISSUE TITLE
Support GPU in dedicated nodes pages

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#690]
- Update the dedicated nodes table to include a new column with a header GPU in which you list the count of GPUs
- Update node resources to include a list of GPUs which on click, shows GPU details

**Comment by 0oM4R** [comment]
@AhmedHanafy725 
should we add the extra fee to the total price?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/70064f6e-fe2d-442e-81e8-b994f0062a85)

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 should we add the extra fee to the total price? 

already done in #637

**Comment by 0oM4R** [comment]
__Status__: waiting for release

**Comment by mohamedamer453** [comment]
Verified on devnet.

The GPU column was added.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ad2115d8-b58f-4fc1-8c84-86831855794e)

and the gpu details were also added

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/744898e7-c51e-4a48-9daa-2a0df1083818)
