### ISSUE TITLE
The number column is duplicated in the Manage k8s worker tab

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#691]
### Description

The number column is duplicated in the Manage k8s worker tab.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e391f8a6-11db-4417-ba76-43abb924b283)

### Steps to reproduce

- Navigate to https://playground.qa.grid.tf/
- Navigate to the Kubernetes tab
- Configure and deploy a kubernetes cluster.
- From the deployment list click on the manage workers Icon.

**Comment by xmonader** [comment]
This looks bad indeed, should be patchd in 2.0.0 @AhmedHanafy725
