### ISSUE TITLE
Documentation link for micro vm is missing

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#693]
### Description

Documentation link for micro vm is missing in both the description and the more info section.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/188f1bb1-ebf2-4b3d-bfc1-2e969cf83232)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fe4467b6-8e59-42c0-b485-80d4fac5c41f)

**Comment by zaelgohary** [comment]
Already fixed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/f6b3cbb8-7788-41b3-8c7c-2c661a2e624e)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/ac7708af-1aaa-4666-be32-52a7ed5c4e4e)
