### ISSUE TITLE
can not create new twin

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#694]
### [dashboard](https://dashboard.qa.grid.tf/)
version : v2.0.0-rc14
network : QAnet
### Description

after creating an account and then accepting terms and condition the request gets rejected
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5f75b9c4-0f7c-40b7-8e41-0fff3d8e9d31)

[Screencast from 06-21-2023 02:50:31 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9904db04-bf3b-4702-a489-1335db3dae55)

**Comment by xmonader** [comment]
This needs investigation

**Comment by AhmedHanafy725** [comment]
After some investigation found that accepting terms & conditions fails due to the document hash being empty.

**Comment by A-Harby** [comment]
Verified on QAnet, 2.0.0-rc15.

Accept terms and condition are accepted and relay created, Twin was successfully created.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6cb61be7-3f86-4582-ba4c-5bbdc1021b66)
