### ISSUE TITLE
Another gateway deployment with the same name `pt143peertube1` already exists

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#695]
### Description

When deploying a Peertube instance with the same gateway name of the old Peertube instance, got this error

`
Another gateway deployment with the same name pt143peertube1 already exists
`

### Steps to reproduce

- Go to [Playground](https://playground.dev.grid.tf/#/)
- deploy a Peertube instance or any other solution with a gateway name
- delete it
- deploy another one with the same name 

### Logs/Alerts

- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/adcdad37-a133-4b52-9395-c0eee4dd4c59)

**Comment by xmonader** [comment]
Why does it say freeflow?

**Comment by Mahmoud-Emad** [comment]
> Why does it say freeflow?

Tried another solution called Freeflow, the screenshot from there

**Comment by 0oM4R** [comment]
For k8s, is invalidating keys necessary too?
@AhmedHanafy725

**Comment by 0oM4R** [comment]
#751 ready for review,


> For k8s, is invalidating keys necessary too? @AhmedHanafy725


will open a new issue in case it is necessary

**Comment by AhmedHanafy725** [comment]
> For k8s, is invalidating keys necessary too?

yes, but this can be done on the grid client.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The issue was fixed and now when a solution is deleted and the user tries to deploy another one with the same name it works without any issues.

[TF Playground _ Peertube.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/344875f3-bc2e-46fa-9b92-0eb881c90da4)
