### ISSUE TITLE
rent contract details

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/tfgrid-sdk-ts#696]
### Description

rent contracts can't show details

### Steps to reproduce

In contracts page click on `show details` for a rent contract

### Logs/Alerts

![Screenshot from 2023-06-21 16-17-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/47260239/f4bae3fa-38b3-4265-93c9-ae3ead010316)

**Comment by AhmedHanafy725** [comment]
rent contracts shouldn't have a details button icon. only the node contracts

**Comment by xmonader** [comment]
> rent contracts shouldn't have a details button icon. only the node contracts

Why not? It seems there're bunch of details we can use?

**Comment by 0oM4R** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/621f8a69-99d6-40dd-80c6-c86273538bf3)
should be fixed in #740

**Comment by khaledyoussef24** [comment]
verified on devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/89c95a73-27a0-4543-83db-a58c45057352)
