### ISSUE TITLE
Support Freeflow solution

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#697]
### Description

The [freeflow](demo.freeflow.life) service should be implemented as a solution in the playground

**Comment by Mahmoud-Emad** [comment]
Should be implemented in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/699

**Comment by mohamedamer453** [comment]
Verified on devnet.

The FreeFlow solution is now available in the playground and i was able to deploy an instance with my 3bot and then i was able to access it after authenticating it from the ThreeFold Connect app.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/cf95fadc-ed5d-4ca5-838d-1bf31549d99f)

[Untitled_ Jul 2, 2023 2_58 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/47f96a15-63d0-476e-a9a4-1f086d5489f5)

**Comment by xmonader** [comment]
@mohamedamer453 can you please open a follow up issue to have it with packages

**Comment by mohamedamer453** [comment]
> @mohamedamer453 can you please open a follow up issue to have it with packages

It already has packages but in the screenshot above i was deploying with `Custom` capacity.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/dde507a0-317f-42d6-8663-e58867e66459)
