### ISSUE TITLE
Can't load existing deployments or contract details

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#71]
On v1.7.0, existing deployments aren't showing up for several users, either on the relevant deployment tab or on the deployments list tab. For example, this account (twin 18 on mainnet), has two deployments. One is a micro VM and the other is a Presearch. They appear in the contract tab:

![image](https://user-images.githubusercontent.com/17682591/231291535-8fc17653-62b3-4ada-9945-7e8b5bdf9873.png)

But they don't appear in the relevant deployment lists. I see `Listing Micro Virtual Machines...` for quite some time, then finally:

![image](https://user-images.githubusercontent.com/17682591/231291809-1e1d5207-4192-4ba3-b82f-ebe9d9ae05ae.png)

Same for Presearch:

![image](https://user-images.githubusercontent.com/17682591/231292436-d6bc38dd-0ab1-48f6-88bf-af2470218322.png)

When I hit the `Show Details` button from the contract's tab, it just spins and does not bring up the details:

![image](https://user-images.githubusercontent.com/17682591/231292669-8fc1b98d-7b10-451a-980b-67b2aecec44a.png)

**Comment by scottyeager** [comment]
An update here: I'm now able to load contract details, but deployments still don't load. Possibly contract details were blocked by https://github.com/threefoldtech/zos/issues/1950, which is now resolved (I didn't try testing RMB specifically on node 2816).

**Comment by alichaddad** [comment]
An update: There was a recent change in the namespace of the deployments which we thought might have caused the issue. We did a rollback and deployed new machines under the old namespace and we found that it was still returned which means that the current implementation supports both namespaces.
We are still looking at it and will update the issue with our findings.

**Comment by 0oM4R** [comment]
this is not reproducible after the changes made in  
- https://github.com/threefoldtech/grid_weblets/pull/1391
- https://github.com/threefoldtech/grid_weblets/pull/1337
- https://github.com/threefoldtech/grid_weblets/pull/1413
Now all deployments are set to their type namespace

for some reason, the deployment may fail to load in the deployed list, the reason may be the different store secret or a different method to deploy, e.g. weblet and ts client, this is not clear for this case.
If the user has only one deployment and it fails to load, the output to the user will be `no <solutionType> found in this profile`, we improve those points in #202 to show the user if any number of deployments failed to load and print the error to console

**Comment by A-Harby** [comment]
Verified, Devnet 49a9c82.
Tried to deploy multiply instance of FullVm, MicroVM and other solutions on devnet, and deployments was successfully listed.
Solution deployment list.
![image](https://user-images.githubusercontent.com/109473873/235627004-ac4f5ff8-78e2-4887-8d49-1fa2c22ed003.png)
Contract list.
![image](https://user-images.githubusercontent.com/109473873/235626933-9ca16b2e-a12c-44a0-bfeb-9c56034ebe41.png)
Deployment list.
![image](https://user-images.githubusercontent.com/109473873/235626890-2fb28735-5433-4bf6-8732-c5e4c59ff351.png)
