### ISSUE TITLE
add playground notifications in case of graceperiod contracts

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#712]
maybe every 15mins show a notification to the user that they have contracts in graceperiod (allow the user to snooze the during the session if they want)

**Comment by A-Harby** [comment]
Verified, Devnet 73edbcd.

Notification is added and if user has a grace period contracts, he will be notified once logged in and every 15 minute.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/44bca3d4-4bd6-41cb-ae69-0e1ae327fc57)
