### ISSUE TITLE
nodes.SetNodePower is no longer working

### ISSUE THREAD

**Issue by brandonpille** [threefoldtech/tfgrid-sdk-ts#713]
I'm using the tfgrid http server and I'm doing the http post to nodes.setNodePower and I get the following error message back from the post: Cannot read properties of undefined (reading 'toJSON')

This was working before when I was using version 2.0.0-rc12

Can someone investigate? This is quite urgent as we need it for the farmerbot.

**Comment by AhmedHanafy725** [comment]
which version are you using now? and against which network?

**Comment by brandonpille** [comment]
I'm using devnet and 2.0.0-rc16

**Comment by AhmedHanafy725** [comment]
please use 2.1.0-rc1 for devnet and 2.0.0-rc16 for the rest networks

**Comment by brandonpille** [comment]
Why is that?

**Comment by AhmedHanafy725** [comment]
cause there are some changes in TFchain on the balance module on devnet. and the grid client checks the balance before doing any extrinsic

**Comment by brandonpille** [comment]
Can we use 2.1.0-rc1 for all networks?
