### ISSUE TITLE
playground is unusable in the light mode

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#715]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/44a99f68-e046-4fa8-9b7b-6d1ab9c87dea)

I can't properly recognize the icons (e.g the info icons)

**Comment by ehab-hassan** [comment]
all are good to me except the info icon we need to make it outline color for both dark and white mode but the rest are Ok!!

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/28d2d37a-9b40-4d59-bdd1-2ee2b98f2a2c)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/521770db-7304-40db-b78d-29b48b0fc52d)

**Comment by ehab-hassan** [comment]
same issue at [#1496](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1496)
