### ISSUE TITLE
explorer nodes does not work correctly and only shows first 10 nodes

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#716]
### Description
[dashboard](https://dashboard.dev.grid.tf/explorer/nodes) version : 2.0.0-rc15

explorer nodes does not work correctly and only shows first 10 nodes and can not go to other pages or see more nodes using the page navigator.

### Steps to reproduce

1. open [dashboard](https://dashboard.dev.grid.tf/explorer/nodes)
2. go to explorer
3. go to nodes
4. try to use the navigator to see more nodes
5. you will find yourself stucked in the first 10 nodes

[Screencast from 06-25-2023 01:21:26 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/890ccbf5-8400-4ed3-ae9f-1b74977a3b89)

you can only show more nodes by using rows per page:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f0a19983-a654-457c-90ba-b24dba715dc8)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in #722

**Comment by A-Harby** [comment]
Verified on QAnet, 2.0.0-rc17.

[undefined.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9808d249-b3b5-4f8f-8fa2-257ecc6b58eb)

**Comment by A-Harby** [comment]
Verified on QAnet, 2.0.0-rc17.

[undefined.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9808d249-b3b5-4f8f-8fa2-257ecc6b58eb)
