### ISSUE TITLE
searching for node in presearch does not keeps searching

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#72]
### Description

while searching for node in presearch when it does not find nodes  it does not time out

### Steps to reproduce

1. go to playground
2. go to presearch tab
3. use capacity filter to find a node
4. it will not time out
![Screenshot from 2023-04-11 10-38-12](https://user-images.githubusercontent.com/110984055/231109377-84eb6220-c8da-42b4-a1f9-6ccdbdcf5da1.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now filtering for nodes will timeout when there are no available nodes to deploy on. and it returns that there are `0` nodes found.

[Screencast from 19-04-23 14:28:58.webm](https://user-images.githubusercontent.com/101194226/233075303-65695409-63b6-4f3c-960d-d17467bbcd79.webm)

Weblets Version: `ad87c97`
