### ISSUE TITLE
explorer: blank page while loading node details 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#723]
while testing a new feature I noticed that with slow 3g throttling a blank page appears for a while till the requests are done 
- we need to add a loading indicator till the requests are done 

[Screencast from 26 يون, 2023 EEST 12:12:43 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/94e79b12-006c-4cd5-95d0-1386fa345e10)

**Comment by 0oM4R** [comment]
__Status__ : waiting for release

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/10c36d7e-8d12-4f8a-acbd-2209b7cb8566)
can no longer reproduce the issue
