### ISSUE TITLE
caprover deployment: validation failed

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#724]
### Description
Trying to deploy caprover  I get `Validation failed. errors: An instance of MachinesModel has failed the validation: - property machines[0].node_id has failed the following constraints: min`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/f5f702e7-f962-4e8e-a838-e5325ea043dd)

### Steps to reproduce
1- go to devnet playground 
2- choose caprover solution
3- click on deploy

**Comment by mohamedamer453** [comment]
Verified on devnet.

I was able to deploy a CapRover instance without any issues.

[TF Playground _ Caprover.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/1077df30-1bdb-42f8-9d52-d3885c8e279e)

And after the deployment i was able to access the machine.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6604c1c7-122a-4a1f-aeab-da4c24b4f05a)
