### ISSUE TITLE
Playground shows nodes are down when public key missing from twin

### ISSUE THREAD

**Issue by elproducto** [threefoldtech/tfgrid-sdk-ts#73]
### Description

Unable to deploy a micro VM on test playground.  Error Node is down is presented once node is selected, however node is marked as online in the test dashboard.  Brave and Chrome browser was used to deploy on grid.   

Issue only appears on test playground.  I was able to deploy a Micro VM to production playground with same browsers and seed phrase.  Production playground  is using v1.6.1 of playground, test is using v1.7.0-rc3 of playground.

### Steps to reproduce

- Navigate to test dashboard Node Section - Note an online Node ID 
- Navigate to test playground
- In Brave browser toggled Shield down, not required for Chrome
- Select Micro Virtual machine link
- Click Profile Manager link
- Input seed phrase into Profile Manager
- Inpute VM specification
- Select node or Input Node ID from above to deploy VM to (Tested against several nodes, but one can use FreeFarm Nodes,Node 12, or Node 262 to reproduce)

**Comment by AhmedHanafy725** [comment]
same as
- #88

**Comment by A-Harby** [comment]
PK issue was fixed and if pk is empty or incorrect, it will update once weblets is used.
And If relay isn't defined yet, user wouldn't be able to open until twin relay is set. 
![image](https://user-images.githubusercontent.com/109473873/234848167-7e0704d4-e305-48ac-8eac-8ca804ce979e.png)
![image](https://user-images.githubusercontent.com/109473873/234848210-b06d2a1f-a35a-43d0-b556-be2f6c2828aa.png)
