### ISSUE TITLE
dashboard.grid.tf - can't connect account - page unresponsive 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#732]
### Description

Opening dashboard.grid.tf. Don't see a possibility to connect my farm as I was trying to vote on a DAO proposal. Clicked connect, doesn't do anything. Page is not loading either. 

I noticed this happens quite often (pretty much everytime I open dashboard). 

After a hard refresh, it works but this shouldn't be like that. 

### Steps to reproduce

- Open dashboard.grid.tf
- Click on connect
- Nothing happens

### Logs/Alerts

https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31733464/92912acf-b69a-4696-b773-bce79167d41a

**Comment by 0oM4R** [comment]
This has happened to me a few times before, but I can no longer reproduce the scenario.
It works fine for me on both the development and main nets.

  [Screencast from 02 يول, 2023 EEST 12:55:11 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/1371ee12-b5fe-4c2e-8f87-7e229c50ed94)

However, there is another situation I encountered while trying to reproduce it: if the user does not have any accounts registered on the Polkadot extension, that view will remain unchanged, and there is no indicator suggesting any tips to the user.

My suggestion is:
1: Handle opening the polkadot and show a clear message to the user if the dashboard can't enable it.
2: Handle accessing the registered accounts on Polkadot and show a clear message to the user that you don't have any accounts on the Polkadot extension.

**Comment by 0oM4R** [comment]
@sabrinasadik can you please provide the logs of the console?

**Comment by 0oM4R** [comment]
__Update__: After some investigation, one more scenario requires reloading the page.
The user must reload the page if they installed or enabled the extension after they had already opened it.
We can add a message to tell the user to install the extension and reload the page, or do it within the connect button logic.

**Comment by sabrinasadik** [comment]
> @sabrinasadik can you please provide the logs of the console?

<img width="1438" alt="Screenshot 2023-07-03 at 09 27 19" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31733464/afe54596-57cf-4505-9036-54b414a72ef9">

**Comment by sabrinasadik** [comment]
> **Update**: After some investigation, one more scenario requires reloading the page. The user must reload the page if they installed or enabled the extension after they had already opened it. We can add a message to tell the user to install the extension and reload the page, or do it within the connect button logic.

I haven't installed anything new. Just tried again, and having the same issue where it's not connecting nor responding.

**Comment by 0oM4R** [comment]
> > @sabrinasadik can you please provide the logs of the console?
> 
> <img alt="Screenshot 2023-07-03 at 09 27 19" width="1438" src="https://user-images.githubusercontent.com/31733464/250487296-afe54596-57cf-4505-9036-54b414a72ef9.png">

@sabrinasadik 
I see the `Auth` warning on polkadot icon can you confirm that you allow access to this page?
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/209bebdb-dfba-4bd4-a62b-2308d2347544)

**Comment by 0oM4R** [comment]
By alerting the user that something went wrong, changes in #745 might enhance the experience.
I'm not yet able to reproduce the scenario Sabrina mentioned.

**Comment by sabrinasadik** [comment]
I did notice that it only happens when going to dashboard.grid.tf, not in https://dashboard.grid.tf

**Comment by sabrinasadik** [comment]
> > > @sabrinasadik can you please provide the logs of the console?
> > 
> > 
> > <img alt="Screenshot 2023-07-03 at 09 27 19" width="1438" src="https://user-images.githubusercontent.com/31733464/250487296-afe54596-57cf-4505-9036-54b414a72ef9.png">
> 
> @sabrinasadik I see the `Auth` warning on polkadot icon can you confirm that you allow access to this page? ![image](https://user-images.githubusercontent.com/62248851/250496675-209bebdb-dfba-4bd4-a62b-2308d2347544.png)

yes, approved. This notification had something to do with gpu forum post asking for access

**Comment by sabrinasadik** [comment]
Don't seem to have this issue anymore since latest changes. Can be closed I think.

**Comment by 0oM4R** [comment]
> I did notice that it only happens when going to dashboard.grid.tf, not in https://dashboard.grid.tf

it is reproducible now I got this error : 
`Error initializing polkadot-js: Invalid url chrome://newtab/, expected to start with http: or https: or ipfs: or ipns:' 
but I think this is not related to us, I'm not sure if we can do something to prevent this error

**Comment by 0oM4R** [comment]
> By alerting the user that something went wrong, changes in #745 might enhance the experience. I'm not yet able to reproduce the scenario Sabrina mentioned.



__Status__: waiting for release

**Comment by khaledyoussef24** [comment]
it is not reproducible anymore
[Screencast from 07-11-2023 05:24:34 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/98aa8973-c674-4772-a238-2faaf57f9666)
