### ISSUE TITLE
playground: info blocks use yellow warnings background 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#734]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/ed9c8121-1513-4283-90b2-51f950a6baf6)

Should be using a different color

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c18ddf0e-26e7-4f36-b3dc-0ddcb2f226b7)
verified warmings are now in green

**Comment by khaledyoussef24** [comment]
![Screenshot from 2023-10-12 10-29-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/625e3d5d-fabe-44d2-8514-0a32e65b6774)
![Screenshot from 2023-10-12 10-29-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bc3729d4-3fc3-44ee-bba1-36444016e035)
![Screenshot from 2023-10-12 10-29-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c81bfd2c-c9e2-4af1-b306-0a74b5005dc1)
verified all info are now in green
