### ISSUE TITLE
playground: missing help text for mnemonic

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#735]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/27891424-45b0-4298-9c53-461267543412)

a help button next to generate account or in the description above

**Comment by khaledyoussef24** [comment]
only generate account changed into create account 

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d4e6b008-74a5-4ce0-a6a3-d85c919e82d0)

but help button is still not added

**Comment by AlaaElattar** [comment]
- Me and @xmonader have agreed on that.
