### ISSUE TITLE
add deprecation warning on the old weblets website

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#737]
add deprecation warning on the old weblets website with a link to the new playground

**Comment by mohamedamer453** [comment]
Verified on devnet.

The deprecation warning was added and also a link to the new playground was added,

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c9f42008-eb19-48a7-9068-3c4fe8a64cea)
