### ISSUE TITLE
The disclaimer text in the stats website overlaps with the map at certain window sizes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#738]
### Description

The disclaimer text in the stats website for `dev`, `qa`, `test` networks is overlapping with the map when the window size is decreased.

[Threefold Capacity.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/42dcf723-e2be-459f-859d-677deba87a68)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/8aaaa9da-a7a0-42b2-9bf1-3868dbe4bdbd)

### Steps to reproduce

- Navigate to https://stats.dev.grid.tf (or qa, test)
- Decrease the size of the window.

**Comment by ramezsaeed** [comment]
we can also please add "Net" the end of the ine.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now the text is above the map and it doesn't overlap with it under any conditions.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/431a07d7-fa21-4de5-8f2e-6593e2a251b0)
