### ISSUE TITLE
Show details on rent contract results in an error.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#739]
### Description

Show details Icon on My contract page will give an error of the contract is a rent contract.

### Steps to reproduce

1. Reserve a node from dashboard.
2. Login to the playground with the same twin used in renting the node.
3. Navigate to My contract page.
4. Click on Show details Icon of the node rent contract. 

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3840a793-de75-45c1-aa02-8fab72c747fa)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/69b46f4a-8b2c-4ff8-b2f0-be0edfc115b2)

**Comment by xmonader** [comment]
possible duplicate of #696

**Comment by A-Harby** [comment]
Verified on Devnet, 0ab73db.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/470b8f52-1ce1-4e6f-b563-159d2038485a)
