### ISSUE TITLE
Allow to load details for name and rent contracts

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#741]
Currently, `grid_client` throws an error in case we try to load details about any of mentioned contracts however we can load some extra information for the user
```gql
query MyQuery {
  nameContracts {
    name
    solutionProviderID
    state
    twinID
    id
  }
}
```

```gql
query MyQuery {
  rentContracts {
    nodeID
    id
    state
    twinID
    contractID
    solutionProviderID
  }
}
```

**Comment by zaelgohary** [comment]
Added 2 new methods that get name contract & rent contract by contract id. Applied changes in Playground.

**Comment by khaledyoussef24** [comment]
verified now on devnet and apploed in playground
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/811f8c40-cb33-40b9-898f-e2a94e8ea74d)
