### ISSUE TITLE
a clear hint the user that they need to click on the user icon to fund their wallet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#743]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/131e3cc1-cb17-4ec0-8830-dce6f523ab23)

this is how it looks on gitopia 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/2befe9aa-2026-4d1d-9038-eaa83cd60ede)

**Comment by AlaaElattar** [comment]
- It seemed to be clear enough for user, so the issue is closed.
