### ISSUE TITLE
replace Nones in the tables

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#744]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/8a3bc1ec-624c-4681-8eb0-f072aa3c31b1)

I think a dash or empty is more appropriate

**Comment by ehab-hassan** [comment]
I think dash is better

**Comment by khaledyoussef24** [comment]
verified in devnet 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/8150e5d7-8a71-441f-aa8f-c6fa02710e29)
