### ISSUE TITLE
Keep getting a request to vote on Dao, but already voted

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/tfgrid-sdk-ts#746]
### Description

Have voted on the open DAO proposals, but keep getting a notification to vote anytime I open dashboard. Is there any way to check if it's already voted on and if yes, not show the notification anymore? 

### Logs/Alerts

<img width="900" alt="Screenshot 2023-07-03 at 13 25 50" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31733464/e28509a0-b098-4c24-8ebc-ce97c854409c">
<img width="928" alt="Screenshot 2023-07-03 at 13 26 02" src="https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31733464/d84bba73-d4fe-4bf5-96c8-aa8b7c0828e2">

**Comment by A-Harby** [comment]
I received the notification
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bd036f69-25dc-42d5-90c6-1f547408ffec)
And casted my vote.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1258702e-98e1-48fc-a19b-fe1e1ad7aa1e)

And for me the notification didn't show up again as much as I can wait or refresh the page.

Also tried it on different twin and same as above.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/16d83be7-b4c1-4c3f-bb76-fe548be613cd)

This is on Devnet, 2.1.0-rc2.

**Comment by 0oM4R** [comment]
@sabrinasadik can you please confirm that you have voted with all your farms that have nodes?
This can occur since you should cast your vote using another farm.

**Comment by sabrinasadik** [comment]
I have only one farm. But went on dashboard today and it didn't ask me to vote anymore so don't know what changed.

**Comment by A-Harby** [comment]
Closing issue as fixed
