### ISSUE TITLE
The twin loading color in the light mode doesn't show the text because of the white color.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#748]
[Screencast from 03-07-23 17:08:40.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/cd0c97e5-88bf-4f30-841e-3c5149b5c47c)

should be like 

[Screencast from 03-07-23 17:12:24.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/30e94bd1-ed52-4996-8e06-cf60f9d6f226)

**Comment by A-Harby** [comment]
2.1.0-rc2
![Uploading image.png…]()
