### ISSUE TITLE
Contradiction in balance

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#752]
The current balance in the profile manager is the total (free + locked). While all calculations are being done, depend on the free balance only which might be misleading.

Suggestion: include free balance in the profile manager.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/b89837a8-4e86-4d1a-8ff0-779e246e66c7)

**Comment by ehab-hassan** [comment]
agree doesn't make sense to add balance while including locked!!
@xmonader @zaelgohary what u think about adding "locked" and "unlocked"?

**Comment by zaelgohary** [comment]
I noticed that the balance in the profile is free only but for some reason, the free balance takes time to be updated unlike the locked.

https://github.com/threefoldtech/tfgrid-sdk-ts/blob/bce196e2d9b83d48732f55c6edb57673c09d5de5/packages/playground/src/weblets/profile_manager.vue#L21

**Comment by mohamedamer453** [comment]
Verified on devnet.

 The balance check is now every 2 mins instead of 5.

[Untitled_ Jul 12, 2023 2_59 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ecf8e152-6a94-4595-9cb0-3a2e69d7ddfe)
