### ISSUE TITLE
Rollback on failed GPU deployments doesn't work

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#754]
### Description

I tried to deploy a FullVM with a GPU option enabled and deployment failed due to network issue as seen in the logs, then I tried to re-deploy but failed cause there's another deployment was the same name (Failed previous deployment).
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/244e1bbe-85de-4c52-a14c-c25b7910087b)
After refreshing.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cb4b655d-c6ef-49fb-99c0-eeabd5f41929)

**Comment by Mahmoud-Emad** [comment]
This issue is duplicate according to https://github.com/threefoldtech/tfgrid-sdk-ts/issues/695

**Comment by 0oM4R** [comment]
should be fixed in #751

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/695#issuecomment-1632290538
