### ISSUE TITLE
remove unnecessary console log while setting gpu filter 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#755]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/642cff0f-64cf-4951-8449-f66c3c4ce849)
we need to just remove this line :  https://github.com/threefoldtech/tfgrid-sdk-ts/blob/42d807f3460bbc7120f655ff1fb1b297b3ffc43c/packages/dashboard/src/explorer/views/Nodes.vue#L251

**Comment by khaledyoussef24** [comment]
verified on devnet
no unnecessary console logs now appear 
[Screencast from 07-20-2023 10:44:02 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ee99cfef-74c0-4d56-9428-422be86f1910)
