### ISSUE TITLE
Improving the GPU node card UI

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#756]
### Description

The card name should have more details (Model number) like the dashboard.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/abe5373a-6585-4e0f-bb97-6887a4dffcad)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0082c42c-827f-41d4-8836-bb24999df572)

Also Node card list should load in the UI to let the user know that it is loading the info instead of just disabling it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2024b620-1b23-4e05-874b-bee260c8c6c7)

**Comment by Omarabdul3ziz** [comment]
update:
- added loader to the gpu card filed 
- added the device name for the gpu card besides the vendor

**Comment by A-Harby** [comment]
Verified, Devnet a11c9c0.
List GPU card loader was added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/dbc1ce05-45d6-4ff7-a9a7-02edf4886ffe)
And GPU card name was added beside vendor details
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/12c8780b-095b-4bc9-9a37-8626560c550d)
