### ISSUE TITLE
User didn't get balance discount

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#759]
According to [this](https://forum.threefold.io/t/do-i-have-to-do-something-extra-to-activate-the-gold-package/4005) user didn't get a discount although he was eligible.

**Comment by zaelgohary** [comment]
After some investigations, I found that:
- The user couldn't get the gold package as it's only for dedicated nodes and there is no way from the current flow in the playground to select the node he wants to deploy on directly
- The only way where a user can deploy on a dedicated node is by reserving it from the dashboard first, then selecting the farm which contains the node in the playground and it'll be chosen automatically
- I created a deployment with the same specs but with different balances to check if the discount would reflect

No discount was applied as the balance was 0

![default](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/738a706e-cd0a-487e-a05c-554d637f6d53)

with discount applied

![discounted](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/2d440f54-2df7-439c-bd5d-e8be24a75d7a)

Note that the discount applied here is about 85.72% and I'm not sure why.

According to the dashboard, I should get 40% off only as the node I deployed on is DIY and not certified.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/260362e9-c56d-4f77-a890-b73c00bf6f2a)

**Comment by zaelgohary** [comment]
@Ashishban I'm not sure there's a possibility to detect what exactly happened to the client's contract as it's been canceled but we're working on a way to enable users to deploy on a dedicated node from the playground.

**Comment by Ashishban** [comment]
Thanks for update.

**Comment by Ashishban** [comment]
Client has shared the latest contracts details on the forum here: https://forum.threefold.io/t/do-i-have-to-do-something-extra-to-activate-the-gold-package/4005/13 and he says if we can use these contracts for investigation?

**Comment by zaelgohary** [comment]
I checked the [contract](https://graphql.grid.tf/graphql) billing details and here's how the billing went.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/7614c9e6-dfee-42cc-973e-04209bf40959)

As per the screenshot above, the user was eligible to get the gold discount on a shared node and the billing rate for that would be 1.6 TFT/hour. Once the balance is lower than 52722 -give or take due to TFT price fluctuation-, the silver package discount will be applied for a rate of 2.6 TFT/hour. 

My guess is that the user transferred more TFTs to his account and the provided screenshot was taken before the gold discount get applied.

**Comment by mohamedamer453** [comment]
Verified.

According to [this comment](https://forum.threefold.io/t/do-i-have-to-do-something-extra-to-activate-the-gold-package/4005/15) the user misunderstood the packages and the difference between dedicated and shared nodes. i think it's safe to close this issue since the latest shared info seems to reflect the correct deployment price with the applied silver package discount. but feel free to reopen this issue if more info/details appear.
