### ISSUE TITLE
Filtering nodes by farm name from the capacity filter with the farmerbot returns nodes with insufficient resources

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#76]
### Description

Filtering nodes by farm name from the capacity filter with the farmerbot returns nodes with insufficient resources and wakes up nodes even though it doesn't have enough resources for the mentioned deployment.

[Screencast from 06-04-23 14:20:56.webm](https://user-images.githubusercontent.com/101194226/230378200-39b6041a-78f7-4d26-a001-fdc3f0d8a2aa.webm)

As seen in the video above i tried to deploy a full VM with `50GB` disk and selected `Amer-Farmerbot-testnetfarm` from the farm name field in the capacity filter this farm (farm `336`) has 4 nodes and none of these nodes has `50GB` of free sru.

But instead of returning that there are no nodes in this farm available with these resources it returned node `248` which only has `19GB` of free sru and as seen on the left side in the polkadot ui it changed the state of node `248` and the node started shortly after the state was changed.

And after node `248` was powered on i tried to deploy on it with the same resources but it didn't appear in the capacity filter.

![image](https://user-images.githubusercontent.com/101194226/230382624-d7dae279-1d41-42fb-aeb0-89499c01a35d.png)

And in the manual filter it returned that the node doesn't have enough resources.

![image](https://user-images.githubusercontent.com/101194226/230382826-af1c91c2-8479-4c52-8800-a03a10c3fa42.png)

### Steps to reproduce

- Find a farm ran by farmerbot and check the power target and state of its nodes.
- Navigate to the weblets and prepare any deployment with resources more than the available on any node in the mentioned farm.
- Select the capacity filter.
- Select the farm from the `Farm Name` list.
- Click on `Apply Filters & Suggest Nodes`
- Check the power state and target of the returned node.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453 
Hello Amer, 

I did the whole scenario you mentioned in test/qa net `they have the same version of the playground` and yes I faced the issue, while when did the same on the dev network I didn't find the issue, maybe because there we check on the disk input every single time the user changes the value of it and it's a new feature, so can you please try it on the dev version and update the issue if the bug still there?

Thanks

**Comment by mohamedamer453** [comment]
@Mahmoud-Emad I checked the issue on devnet and the following results were performed on Nodes `83`, `84`, `85`, `86` these nodes belong to `brandon-farm`. These are the same nodes that i had in my farm on testnet but they were booted on devnet so the same disk sizes that were originally mentioned in the issue still apply.

The case where the capacity filter returned powered off nodes when the farm didn't have any nodes with enough resources was fixed and now when there's not enough resources in any of the nodes the capacity filter doesn't return nodes.

However another issue is still present when i add valid disk size and selected the farm from the capacity filter it returned 2 nodes that were powered off by the farmerbot `83`, `84`

both cases can be seen in the video below.

[Screencast from 30-04-23 12:26:09.webm](https://user-images.githubusercontent.com/101194226/235346229-ffadb4e2-0048-4928-be5b-a03631b921d9.webm)



### Environment 

- Network: `devnet`.
-  Weblets Version: `35919fc`.

**Comment by mohamedamer453** [comment]
Closing this issue since the main issue was solved and verified above and the other issue mentioned in the comment above is a duplicate of #78
