### ISSUE TITLE
Update calculator in client

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/tfgrid-sdk-ts#767]
- Edit packages duration
- Include certified price

**Comment by mohamedamer453** [comment]
Verified on devnet

The `Certified` flag was added and it increases the cost by 25%

- Cost with `Certified` set to false.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a4566938-00fb-4cb1-97b2-18de12f3a7b8)

- Cost with `Certified` set to true

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/56675a4a-22ab-47eb-95b5-d0a301e4c048)

and the claculations seems to be correct.

```
14.625 * 1.25 = 18.28125

29.25 * 1.25 = 36.5625

```

and for the packages if we calculate it with the following resources:

```
cru: 16,
    mru: 8, // GB
    sru: 25,
    hru: 0,
    ipv4u: false,
    certified: false,
    balance: 0,

```

the cost on a shared node will be `29.25` USD/month = `29.25 * 100` = 2925 TFT/month therefore the user should be applicable for a default package if the balance is greater than or equal to 2925 * 1.5 = 4387.5

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ec105a13-8a18-4ee0-9069-750a2db634e2)
