### ISSUE TITLE
Dashboard raises an error on connecting to the Polkadot extension, also the loading credentials loading forever

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#769]
### Description

I'm having trouble accessing the explore tab in the dashboard after connecting my account and refreshing the page. The nodes section seems to be stuck in an endless loading loop.

also, I'm seeing an error message that states "Can't get any account information from Polkadot extension. Please ensure that you have registered an account on it." However, I have registered six accounts already.

### Steps to reproduce

- Go to the dashboard on the local server
- Refresh the page 

### Logs/Alerts

[Screencast from 06-07-23 11:23:08.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/7fccbc29-98df-4549-abff-27f9a0e67644)

[Screencast from 06-07-23 11:35:13.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/7312cdd4-1d17-4a95-bc00-04a4979e5760)

**Comment by Mahmoud-Emad** [comment]
is this not planned to be fixed? we will implement the profile manager based on this one?
https://github.com/threefoldtech/tfgrid-sdk-ts/issues/470

**Comment by xmonader** [comment]
We are moving to a local wallet, is it still relevant?
