### ISSUE TITLE
Explorer nodes filter doesn't work as expected 

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#770]
### Description

I noticed that when filtering the nodes table to show only online nodes, it also displays offline and standby nodes. This doesn't seem right. Additionally, the toggle for the online/offline message always displays "Does not include Standby nodes" regardless of the actual filter settings.

### Steps to reproduce

- Go to the dashboard on the local server
- Toggle the online/offline switch.

### Logs/Alerts
[Screencast from 06-07-23 11:29:44.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/58792581-5d3c-4da9-80e6-d294d47b673f)

**Comment by A-Harby** [comment]
- Add some space between gateway and gpu toggles
- Page counts needs to be reset every time a toggle is enabled/disabled.
[TF DASHBOARD (2).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/806b9017-6e15-4a87-acb2-ddbaedf195b4)

**Comment by Mahmoud-Emad** [comment]
@AhmedHanafy725 @xmonader 

I would like to propose a solution.
Upon mounting the page, it would be beneficial to initially get all nodes.

This would provide users with a clearer overview of the nodes' statuses until they manually modify the filters according to their preferences.

Additionally, when filtering a node by its specs e.g. <NodeID>, it is recommended to return the node even if its status is "Down" and the requested filter status is "UP". This would allow users to easily locate and access specific nodes, regardless of their current status.

What do you think?

**Comment by Mahmoud-Emad** [comment]
If we decide to proceed with this approach, we require [this issue](https://github.com/threefoldtech/tfgrid-sdk-go/issues/243) to be executed.

**Comment by maayarosama** [comment]
Blocked on https://github.com/threefoldtech/tfgrid-sdk-go/issues/243

**Comment by zaelgohary** [comment]
Issue fixed in Playground.

**Comment by ramezsaeed** [comment]
verified on:
- devnet
- 8c32384

![Screenshot from 2023-12-17 20-59-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/a02144bd-342b-49f8-8e76-dc8c918f1a8f)

**Comment by zaelgohary** [comment]
Issue still exists. Nodes with a down status do not appear unless filtered.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/40770501/6262c6ab-9094-4023-ae8b-39b616433502)

**Comment by zaelgohary** [comment]
WIP: 
- Reset the status filter to be undefined on mount so now all nodes will be returned on init
- Sort by status is not implemented yet in Grid Proxy so opened an [issue](https://github.com/threefoldtech/tfgrid-sdk-go/issues/566) for it. Issue is blocked.

**Comment by zaelgohary** [comment]
Work completed:
- Reset the status filter to be undefined on mount so now all nodes will be returned on init

Opened a new [issue](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/1786) to sort by status

**Comment by A-Harby** [comment]
Devnet, ec2ed3d.

The Select node status doesn't work at all, and the status chosen is not shown.

[Threefold Dashboard: Nodes (2).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/3066e762-95ab-4fe1-8abb-5b6ac339fa51)

**Comment by zaelgohary** [comment]
Work completed:

Status filter value was changed to its initial value on update. Fixed by removing this part.

**Comment by maayarosama** [comment]
Verified on devnet
![Peek 2024-01-02 12-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/66883096/8adea08f-6874-49f6-87b1-5b946ec2b2a2)

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d

![Screenshot from 2024-01-02 15-04-17](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/f03e77a8-05f0-4024-a1a5-466f757976cf)
