### ISSUE TITLE
Feature add node GPU card detail to the deployment details

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#771]
### Description

Add Node card details to the deployments details when deploying a VM with GPU if possible, it's helpful to know which card is selected if there's more the one card to select from when deploying.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ecb8b793-d8c5-42d0-b52f-6779ed63ba3a)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5d47b4bf-3992-4f65-b330-5e7c2521cbe0)

**Comment by xmonader** [comment]
the used cards should be excluded in the listing

**Comment by Omarabdul3ziz** [comment]
update: 
- added a new filed in the deployment dialog to view card info in the mentioned pr

**Comment by A-Harby** [comment]
Verified, Devnet a11c9c0.
Card name was added the deployment info.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/485049af-a2f6-4f80-9fe9-d2e2eab61346)
