### ISSUE TITLE
(Mainnet verification) add a link or iframe the minting website in the dashboard

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#775]
https://alpha.minting.tfchain.grid.tf/

**Comment by 0oM4R** [comment]
> https://alpha.minting.tfchain.grid.tf/

is this link for all networks?

**Comment by AhmedHanafy725** [comment]
> is this link for all networks?

only mainnet

**Comment by 0oM4R** [comment]
__Status__: pr #792 is ready for review 


![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/73a46312-f9e0-4af6-a1d7-73adfab96a6d)

**Comment by 0oM4R** [comment]
__Status__: merged; waiting for the release

**Comment by khaledyoussef24** [comment]
verified locally waiting to be released on mainnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ef9598a-ade7-4a12-94f6-7e6170b6aaed)

**Comment by A-Harby** [comment]
Verified, Mainnet 2.1.0.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f8e7b592-ac51-4713-a735-cdc770769d70)
