### ISSUE TITLE
Network options do not appear in MicroVM.

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#776]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/3fa4f751-442f-401f-854c-57ef9563701f)

**Comment by A-Harby** [comment]
Verified on Devnet, fbe08b3.

Networks option is back on the microVM.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/cea6a4db-bdd0-4f9f-aa6b-9c07ce997459)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/b35016dd-e4a2-4fe1-8061-1bba28f7d0db)
