### ISSUE TITLE
After deploying a vm, can't find the wireguard config in the details pop-up

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#784]
env: devnet

### Steps to reproduce

- Deploy a vm with `add wireguard access` enabled.
- Close the pop-up result and open it again

### Expected

find a wireguard config in the details pop-up

### Result 

the machine has wireguard config in the json result, but it's not on the details

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/96cdb049-060a-4c85-ab0e-66832abf3011)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/1fd41de2-6472-450d-9965-0074b29ad4bd)

**Comment by 0oM4R** [comment]
__Status_: pr #798 is ready for review

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Wireguard` config is now available and appears in the details popup after deployment. tested for both the Micro and Full vms and it's working fine in both.

[TF Playground _ Micro Virtual Machine (2).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ca6e963a-70e7-4d79-a185-6fe2f338bf41)
