### ISSUE TITLE
re-phrase the calculator cost message

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#785]
`Cost of reservation on a Dedicated Node` -> `Cost of reserving a Dedicated Node of same specification`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/41957921/c54ccb00-1a24-4683-b7d8-e76bfd962a43)

**Comment by 0oM4R** [comment]
@AhmedHanafy725 should we change the shared node message too or keep it?

**Comment by AhmedHanafy725** [comment]
keep it

**Comment by 0oM4R** [comment]
![Image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/955ea68e-e73b-480c-8e75-c58f27547b4b)
__status__:  pr #795  ready for review

**Comment by 0oM4R** [comment]
__Status__: waiting for the release

**Comment by mohamedamer453** [comment]
Verified on devnet.

The message was updated.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4525771e-7ce2-4d10-967d-04b2881305b1)
