### ISSUE TITLE
Update manual links to be pointing to the new manual

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#79]
The new manual link is https://manual.grid.tf

**Comment by mohamedamer453** [comment]
All Links were Updated with their corresponding section in https://manual.grid.tf/

Except for 3 links:

- Micro VM

   Still points to https://library.threefold.me/info/manual/#/manual__weblets_vm

   ![image](https://user-images.githubusercontent.com/101194226/232712999-15a036f6-e4e6-4a7f-bc18-5aa64fa5d0dc.png)

- Contracts

   Still points to https://library.threefold.me/info/manual/#/manual__tfchain_home

   ![image](https://user-images.githubusercontent.com/101194226/232713276-1a7c11e6-b46e-4ff3-acca-b41361674a52.png)

- Threefold Connect

   Still points to https://library.threefold.me/info/threefold#/tokens/threefold__threefold_connect

   ![image](https://user-images.githubusercontent.com/101194226/232713613-d807c803-6cfd-4f55-b212-ad7355c4fc6b.png)


### Environment

- Network: `Devnet`
- Weblets Version: `09d33c2`

**Comment by A-Harby** [comment]
Also check the Dashbaord manual links wasn't updated to the new link.
![image](https://user-images.githubusercontent.com/109473873/234863227-3fc6cd22-6896-4472-9f67-69238efe7565.png)
![image](https://user-images.githubusercontent.com/109473873/234863377-7e258cba-31e2-4f99-90c6-d4512e14e621.png)

**Comment by zaelgohary** [comment]
I updated the Dashboard links except for the following as they were missing from the new manual.
- [Pricing](https://library.threefold.me/info/threefold/#/tfgrid/pricing/threefold__pricing)
- [Discount Levels](https://library.threefold.me/info/threefold/#/tfgrid/pricing/threefold__pricing)
- [Terms & Conditions](https://library.threefold.me/info/legal/#/)

Note: current links for Javascript Client redirect to the archived repo, not the one in the mono repo.

**Comment by mohamedamer453** [comment]
Closing this issue since the it has the `weblets` tag and all links in the weblets were fixed. regarding the dashboard links, once the latest version is released and deployed i'll check the links and if the docs links still need to be updated i'll open a separate issue for it.
