### ISSUE TITLE
The first billing rate for name contracts is not accurate.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#791]
### Description

The first billing rate for name contracts is not accurate.

After deploying a solution that uses a name contract the billing rate that appeared in the contracts list is `0.007` tft/hour.

https://user-images.githubusercontent.com/101194226/252345527-17539d98-8a64-405a-b35c-e84cf924627e.png

however the value from the calcualtions is different.

From the current pricing policy on devnet, the price of the unique name is `2500` which is `2500*10^7` USD/hour.

```
Unique Name = 2500/10000000
            = 0.00025 USD/hour
```

Current USD to TFT rate is 1 USD = 100 TFT

```
Price in TFT = 0.00025 * 100
             = 0.025 TFT/hour
```

Since i have enough tft in the account for a 60% staking discount therefore the final cost should be

```
Price with 60% discount = 0.025 * 0.4
                        = 0.010000000000000002 TFT/hour
```
which is still higher than the 0.007 that's displayed in the contracts list.

and indeed after the first billing cycle the correct value was displayed.

![photo_2023-07-11_12-46-44](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/c9f617bb-2b00-435b-ac83-74e406960734)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/49717c9b-2173-4df8-8f99-91b81f28f137)

**Comment by AhmedHanafy725** [comment]
the issue was found for the first period after the contract is created, but waiting for a contract to have the same issue to make sure the fix is working
