### ISSUE TITLE
Fake nodes created from the chain can be used to vote on DAO proposals

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#794]
### Description

Since there's a **createNode** function from the polkadot UI where users could create fake/imaginary nodes from, then it would be very easy to fake dao votes. i've only tried this on devnet for now but i assume that the same flow could be reproduced on mainnet.

### Steps to reproduce

First step is creating a node from the chain

![image](https://user-images.githubusercontent.com/101194226/252638741-904db2e6-eb0f-4cd7-b107-bf8485230cb6.png)

![image](https://user-images.githubusercontent.com/101194226/252638924-b06f1c2d-23f3-4ad3-adbe-291327e85ae4.png)

then voting with the created node on any dao vote since the only limitation for voting is the user must have a farm that contains nodes. and as seen the fake node could also have very high resources which will skew the vote to the desired outcome.

[TF DASHBOARD (1).webm](https://user-images.githubusercontent.com/101194226/252645786-af93709f-1781-4c98-bcfe-1a2d5cda60b8.webm)

 the screenshot below is a comparison of a vote between a node with normal resources and another one with very high resources.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4b7da5d6-53d3-4880-988b-85f3b8e70f64)

- Resources of the node that voted `yes`

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9fde854f-2fdd-419e-8534-5ae2b2adb308)

- Resources of the node that voted `no`

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/08e20054-3022-47d9-898c-35bb35aecfde)

> both nodes that were used for voting are fake nodes that were created from the polkadot UI

### Environment 

- Network: `devnet`
- dashboard Version: `2.1.0-rc2`

**Comment by Mahmoud-Emad** [comment]
Couldn't be reproduced, please re-open it if you face the same issue
