### ISSUE TITLE
Support hex based seeds

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/tfgrid-sdk-ts#8]
For the purposes of the `farmerbot`, it would be beneficial to support the use of hex based seeds in `grid3_client_ts`.  Many farms have been created using the TF Connect App, whereby the farmer only has a hex secret to work with for their twin and farm.

Since `rmb-rs` [already](https://github.com/threefoldtech/rmb-rs/commit/00fdc4b8b6c10882a4c81f08244de1974008e964) supports this and it's possible to achieve all necessary TF Chain signing activities with a hex secret, I think it should be possible to support it for this client.

**Comment by AhmedHanafy725** [comment]
for the deployment part, it could be supported as well for signing the deployment but the issue is saving the deployment on the kvstore on tfchain. the mnemonic is used as a symmetric key to encrypt the values. so if a user has mnemonic and secret seed for the same account and used them to deploy. both accounts will see the contracts without any problem but the deployed list will be different between them as the keys encrypted by one of them won't be decrypted by the other one.

**Comment by AhmedHanafy725** [comment]
related 
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/127

**Comment by AhmedHanafy725** [comment]
maybe a suggestion:

- if a mnemonic is provided, convert it to a secret seed.
- if it's a secret seed keep it as is
- always use the seed for the encryption

but this will require migrating all the keys to be encrypted by the seed instead of the mnemonic

**Comment by MohamedElmdary** [comment]
Blocked on some appeared issues described in PR https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1380#issuecomment-1801782457

**Comment by A-Harby** [comment]
I tried using the hex secrets from the Threefold Connect app, but the activate button wasn't enabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/26656ce3-e4cc-44f6-86fc-cdeaa85b0f7f)

Also, can you link the documents for the hex seeds in the issue?

**Comment by khaledyoussef24** [comment]
am still facing the same issue
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b30359fe-eaf6-45f3-9b4d-4ab978d3eed3)

**Comment by AhmedHanafy725** [comment]
@khaledyoussef24 can you please add the steps to reproduce? how did you get the hex seed?

**Comment by khaledyoussef24** [comment]
@AhmedHanafy725 
Sure it is got the hexseed from the threefold connect app![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bf195c70-75e3-4f4e-9193-32e7131b47e2)

Then went to the dashboard and paste it as written in the login documentation

**Comment by khaledyoussef24** [comment]
verified and working fine now
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1c00fba2-a583-4c66-9880-bac1a392f8e9)
the issue that my old hex seed did not have a twin.

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4150322

**Comment by khaledyoussef24** [comment]
blocked on #1690 to verify that we can create a twin with a hex seed also

**Comment by khaledyoussef24** [comment]
env used : devnet
version used : 228c723
verified now user can log in and activate account from mnemonic and hex seed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/31b5b19f-14ff-4354-82f9-623ead179df1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bbfad00c-793d-4b73-a6f9-22143d8d10f2)

test lodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=422331#case_4161528

**Comment by ramezsaeed** [comment]
Verified:
- Devnet
- 33c308d
