### ISSUE TITLE
Lots of errors appear in the console while accepting the terms and conditions

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#806]
### Description

Lots of errors appear in the console while accepting the terms and conditions.

[Screencast from 13-07-23 13:10:21.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f1b23998-89b4-4cdf-9524-98bfa4dc73c1)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Create a new account from the polkadot extention.
- Select this account from the dashboard.
- Check the console.
- Accept the terms and conditions.
- Check the console again.

### Logs/Alerts

- Errors that appear before Accepting the terms and conditions

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/11e9eb97-057c-4592-b228-c175b65e5bed)

```
There was an error setting cookie `_pk_ref..8596`. Please check domain and path.

There was an error setting cookie `_pk_ses..8596`. Please check domain and path.
```

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0050f527-8c20-4f07-a725-bc5a6449b6ca)

```
library.threefold.me/info/legal/favicon.ico:1     GET https://library.threefold.me/info/legal/favicon.ico 404

docsify-glossary.min.js:1     GET https://library.threefold.me/info/legal/_glossary.md 404

POST https://analytics.threefold.io/matomo.php?action_name=&idsite=&rec=1&r=254465&h=13&m=19&s=39&url=https%3A%2F%2Flibrary.threefold.me%2Finfo%2Flegal%2F%23%2F&urlref=https%3A%2F%2Fdashboard.dev.grid.tf%2F&_id=9c60ea9d5d5ed648&_idn=1&send_image=0&_refts=1689243580&_ref=https%3A%2F%2Fdashboard.dev.grid.tf%2F&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=2560x1440&pv_id=6X2Snn&pf_net=642&pf_srv=209&pf_tfr=3 400
```

- Errors that appear after.

   ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/38e7e421-2564-4c61-9da9-942c8f3da554)

**Comment by maayarosama** [comment]
Caused by the manual wiki
