### ISSUE TITLE
Playground RMB server connection issue

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#809]
A user on TG tries to deploy on playground and gets an RMB issue. Link to the picture one reply above [this](https://t.me/threefoldfarmers/63405).

**Comment by Mik-TF** [comment]
The issue might be related to needing to set a relay on the tf dashboard for twin missing the relay (pre 3.xx twin) as pointed out by Drew on TG.

Will keep this issue posted as we get more info on TG.

**Comment by AhmedHanafy725** [comment]
could reproduce the issue on mainnet by throttling the network, and increasing the timeout of the rmb connections worked fine

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 So this wasn't related to the twin not having the relay set, but it was due to the connectione timeout, right?

yes exactly, and if the twin doesn't have the relay set, the playground will set it automatically

**Comment by mohamedamer453** [comment]
Verified on devnet.

Even with a throttled connection now the error message doesn't appear anymore.

and now it takes a bit longer on throttled connection but at the end it logs in without any issues.

[Untitled_ Jul 24, 2023 1_12 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/35cc17cc-6174-450d-a313-7cc423bf21e9)

**Comment by Mik-TF** [comment]
@mohamedamer453 
Thanks so much! Amazing. 

For documentation purpose, I incorporated the info you gave on the tf relay+playground in [this QnA](https://www.manual.grid.tf/faq/faq.html#how-can-i-set-the-relay-on-the-tf-dashboard)

**Comment by scottyeager** [comment]
This issue seems to still be blocking some users from using the Playground. Can we push a hotfix to mainnet?

**Comment by Mik-TF** [comment]
Since this is closed, I created a new issue to push the hotfix to mainnet. So we can keep track separately (this issue for dev net, the new one for main net).
