### ISSUE TITLE
Feature request: Add sorting to the `Contracts List`

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#81]
### Description

Add sorting functionality to the `Contracts List` table.

Adding sorting for this table would be very helpful since it allows the users to sort their contracts according to different aspects. And it would improve the experience of exploring and querying the list.

![image](https://user-images.githubusercontent.com/101194226/229345674-59126db3-8976-404d-a483-98178de604b2.png)

**Comment by Mahmoud-Emad** [comment]
Now we support sorting in the contracts list

[Screencast from 04-24-2024 08:55:30 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/13590887-f1e7-48be-a810-455a694ca158)
