### ISSUE TITLE
Listing node GPU card takes longer than it should.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#818]
### Description

I deleted the deployment that used the GPU card and waited more than an hour for the card to be listed again, but it never did.

I made sure no one was using the card and waited long enough, even though that I had previously used the same node card and this issue had never occurred to me.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/1795db31-4f9f-4f89-91e8-5c778a37e274)

**Comment by AhmedHanafy725** [comment]
the playground marks the GPU card as used based on a call to the node `zos.gpu.list` if the contract's field in the result is not 0. And the contract wasn't 0 in after deleting the contract

**Comment by xmonader** [comment]
3.8.2 has thsi fix https://github.com/threefoldtech/rmb-rs/pull/144

**Comment by khaledyoussef24** [comment]
verified now once you delete a gpu machine you can deploy another gpu machine at the same instant
[Screencast from 08-01-2023 04:21:54 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ca970f71-df1d-4bb6-a717-d8390506b974)
