### ISSUE TITLE
Dashboard node details SSD and HDD are wrong

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/tfgrid-sdk-ts#819]
### Description

On dashboard, if you open the details of individual nodes, there are "Node resources" at the top which show the percentage of utilization of resources on the node. In these graphs, it seems as if the graph labeled SSD shows HDD utilization, and the graph labeled HDD shows SSD utilization

Checked on both mainnet and devnet

**Comment by mohamedamer453** [comment]
Verified on devnet.

By checking the resources of multiple nodes from the gridproxy and comparing them to the values in the node details it appears to be fixed.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b5fb64c9-7fa7-43d7-98a8-467930906404)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/da8ba960-48af-462f-8744-3a43f2f7a8a1)
