### ISSUE TITLE
Contracts List: Minor improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#82]
## Description

Some Fields in the Contracts List need minor improvements.

### Type Column

Contract Types should be capitalized.

![image](https://user-images.githubusercontent.com/101194226/229344742-f2cfb11b-4749-470a-9f46-707f3be8f448.png)

- `name` -> `Name`
- `node` -> `Node`
- `rent` -> `Rent`

### State Column

![image](https://user-images.githubusercontent.com/101194226/229344781-85fcd65a-4fca-4c53-82f4-3a48a0931a05.png)

A space should be added between `Grace` and `Period`

### Solution Type Column

Solution names should be capitalized and should match the names available in the sidebar

![image](https://user-images.githubusercontent.com/101194226/229344927-b58138cd-03fb-4790-a1f7-ac5ed3c4247c.png)

### Actions Column

I think it would be better if this column was renamed to `Details` instead of `Actions` since currently the only action that could be done in this column is showing the contract's details.

**Comment by xmonader** [comment]
let's verify against the new playground

**Comment by mohamedamer453** [comment]
The mentioned points are still present in the new playground.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f97333b6-2181-4390-9583-99525872664d)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2cbe0e87-9a95-4923-8a6a-60f6824c8571)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/6e856ed6-c259-4e37-a064-34a76fba0748)

**Comment by 0oM4R** [comment]
discussed it with @AhmedHanafy725  and we changed the new playground only

**Comment by khaledyoussef24** [comment]
verified:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/847c39d5-275c-4b48-aec6-59c030737eeb)
action also changed
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/932f4eea-bd9c-4ef4-82b4-273eb100ca4a)
