### ISSUE TITLE
(Mainnet Verification) Load more gateway nodes in the same farm, country, and finally whole network

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#829]
### Description
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/670
- https://github.com/threefoldtech/tfgrid-sdk-ts/pull/820
after those updates; the `select_gateway_node` will return the gateway nodes in the same selected farm, if there are no gateway farms then it will as for all gw nodes in the same country of the selected farm. finally, if we ask for all gw nodes on the network 
but what if the user needs to load more nodes in the same farm, country, or even the whole network?

![Screenshot from 2023-07-19 17-30-59](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/0b9e7db0-f9ea-474b-88e9-31280fd35c5b)

### Implementation

we need to add a logic that makes load btn say `load more nodes in <<farmName>>`, `load more nodes in <<countryName>>`
and `load more nodes` idk if we should make three buttons together or change the btn content and logic progressively 

- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/670
- https://github.com/threefoldtech/tfgrid-sdk-ts/pull/820

**Comment by khaledyoussef24** [comment]
verified on https://dashboard.bknd1.ninja.tf/
[Screencast from 22 ينا, 2024 EET 08:55:12 ص.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/42892fa7-6683-48a6-995b-1ca60a6ff6b3)
![Screenshot from 2024-01-22 08-55-02](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/c9d0cd67-7949-4a47-9829-c908debd5d2b)
![Screenshot from 2024-01-22 08-55-00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3dbf2156-5119-4860-b609-f6b9e7ff2081)

`load more gateways nodes` is functional
and even when a field is changed it does not affect the loaded gateways

testlodge : https://app.testlodge.com/a/26076/projects/40893/suites/234374?expand_section=426661#case_4150357

**Comment by ramezsaeed** [comment]
Verified:
- Mainnet (Ninja)
- 2.3.0-alpha6
- https://dashboard.bknd1.ninja.tf/#/deploy/applications/peertube

![Screenshot from 2024-01-22 12-46-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/16083592/3963ce7d-32ab-4d0a-b5fa-ad8afd2bc44a)
