### ISSUE TITLE
Playground: UI - Drop-down consistency issue

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#830]
I noticed something off with the playground UI.
You can open and close the network menu by clicking on the same spot which is pretty cool and convenient.
But for some reason, the VM image, country and farm menus don't work like that. You have to click on different spots to open and close them.

That's kind of annoying.
Can we make all the drop-down menus consistent and easy to use?
I can see that these fields are searchable, not sure if we can get the best of the both worlds.

**Comment by maayarosama** [comment]
The Network menu is an expansion panel and the others are drop down
