### ISSUE TITLE
styles in deployment list should be with the same color

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#833]
network:[Devnet](https://playground.dev.grid.tf/#/peertube)

### Description

styles of action buttons in deployment list and contract should be with the same color
![image_2023-07-20_14-38-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3e001ff8-dfbb-479c-8ae2-685cd047b7b6)

in taiga same goes for admin panel:
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/920f99e9-9c1f-4d20-b4b2-8758c69c79d6)

### Steps to reproduce

1. go to playground
2. go to peertube or any solution with domain feature
3. make a deployment with domain
4. check the colors of the action buttons they should be the same

![image_2023-07-20_14-38-40](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/52bed1f2-21c0-428c-b96f-be34eac99a01)

**Comment by ramezsaeed** [comment]
@ehab-hassan

**Comment by ehab-hassan** [comment]
@zaelgohary, let's make all icons white.

**Comment by khaledyoussef24** [comment]
verified on devnet all icons are now white 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/32fc7a44-c649-4bd4-9482-9671efd98698)
