### ISSUE TITLE
Show terms and conditions when generating a new account

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#834]

**Comment by 0oM4R** [comment]
ready on playground but pending on dashboard

**Comment by mohamedamer453** [comment]
Verified on devnet.

The terms and conditions is now shown when a new account is generated either from the dashboard or the playground.

- dashboard

[Untitled_ Jul 26, 2023 3_24 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/e2980d23-467b-43b9-a8c6-47d43ed32f23)

- playground

[Untitled_ Jul 26, 2023 3_25 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a567eafa-160e-4bda-9956-89b2ea18758b)
