### ISSUE TITLE
action button in deployment list naming

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#835]
network : Devnet
### Description

naming of the action button of deployment list is not descriptive 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/0de805f2-1810-423d-a30c-86d9d6ebb64c)
should be more descriptive like :go to deployment

**Comment by ramezsaeed** [comment]
Change preview to visit

**Comment by mohamedamer453** [comment]
Verified on devnet.

The naming was changed to `Visit` instead of `Preview`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/bb299d63-17aa-4cdd-ad69-a0ababe4718a)
