### ISSUE TITLE
discourse while using domain name gives 404 not found

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#837]
discourse while using domain name gives 404 not found
![image_2023-07-20_15-19-16](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/04870855-6431-4132-a0b0-930f4f2b1aaf)

while tried to deploy without domain name worked fine and image is up
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/66f75b8b-68e4-4e7d-937f-dacf95703009)

_Originally posted by @khaledyoussef24 in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/670#issuecomment-1647425796_

**Comment by khaledyoussef24** [comment]
verified working now 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3e14d5a6-31b5-4c94-b8df-a2bb1d3b5f59)
