### ISSUE TITLE
Twins with farms but no nodes are notified to vote, although voting is only available to farms with nodes.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#839]
### Description

While voting is only available to farms containing nodes, twins with farms that have no nodes receive a notification to vote.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/880667e0-a290-4593-86a1-171b6da9824f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c7c04883-0354-4481-aede-bd2b06344698)

**Comment by ramezsaeed** [comment]
USER MUST HAVE ONLINE NODES IN HIS FARM SO HE CAN VOTE.

**Comment by zaelgohary** [comment]
Added user nodes to the store so that it would be accessible by all portal components. However, the voting dialogue shows right after the logging and before the state gets updated. I think the issue would be fixed if we created a grid proxy API that returns nodes by user twin ID.

**Comment by zaelgohary** [comment]
Added a condition to check if the user has nodes before showing the voting dialogue.

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc11 .
Now voting notification only appears to twins with nodes in it.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/eccba081-c767-4c41-bbea-079cc2ffe279)
