### ISSUE TITLE
Inconsistency in the description/more info sections

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#840]
### Description

The deployment description is inconsistent, for some deployments it only shows a brief message with no link to the docs like full,micro vms.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9da21980-c9f8-4c5b-8651-4dc3c46763a0)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/35c56224-9aeb-49ea-9c43-77871e51231d)

also for full vm it still has description below the title which was replaced a while ago with the one above it in all other solutions.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fe178686-8c3a-458e-8e8d-68b51ee2599e)

and for other solutions it's a full description with details and links for the documentation.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f67e186d-93c4-4e31-9d0a-6363b8c94c17)

and for most of the solutions the more info icon displays the same text that's already displayed in the description section.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/edcf74dc-754a-42b9-943f-16cf4115f0b6)

### Suggestions

The section above each deployment should be consistent for all solutions. 

or

For a cleaner look i would suggest removing the description from each solution and having full description + link to the documentation in the more details section instead of displaying the same data in multiple places. Suggested look:

Remove all descriptions from the UI and have the `i` icon contain all of the needed description and manual links

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/15ec1885-9866-4ed4-81ad-65b5d9c5231d)

**Comment by zaelgohary** [comment]
Removed description & included docs to each solution info except for Freeflow as it's not yet included in the manual.

**Comment by khaledyoussef24** [comment]
verified on devnet playground descriptions are now removed except for freeflow 
![Screenshot from 2023-07-31 10-25-21](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/94543831-4d1b-4f16-b766-d9e18d173d85)
![Screenshot from 2023-07-31 10-25-11](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/bd6be8be-40eb-46ec-bf8d-f72dcce9b727)
![Screenshot from 2023-07-31 10-24-25](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/a92a5da3-1b70-4497-85bf-0f2ab4475b4c)
![Screenshot from 2023-07-31 10-25-03](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/13efa089-a9bc-4e21-8b90-c301776ea5af)
![Screenshot from 2023-07-31 10-24-56](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1ad44d64-e133-4cb0-8d82-f2ec4a9df014)
![Screenshot from 2023-07-31 10-24-29](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/ded8d9a5-60de-4b9b-9a26-a4ceffec1155)
