### ISSUE TITLE
CapRover is missing the solution icon and title

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#841]
### Description

CapRover is missing the solution icon and title.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ec3e9fd7-ff1c-42d9-b837-96c93116deef)

**Comment by khaledyoussef24** [comment]
verified on devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/82410b3a-7d08-4c1a-b066-0df0ed5094c4)
