### ISSUE TITLE
caprover: use a better generated leader name

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#848]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/1f82be4f-3213-4dd2-a099-f08fc7809a7e)

**Comment by khaledyoussef24** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/e14e10e6-78af-4a56-8676-5f48620b4451)
now generated names will use cr prefix then 10 random numbers and letters
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/4fe15b5b-6874-4487-b8fa-637af77bf621)

statically : the name generation function changed
