### ISSUE TITLE
UI: Add a space between deployment messages.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#85]
### Description

Add a space between deployment messages.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/101194226/227880055-e8235c6b-cbbc-4e1f-bed9-ac44964b802d.png)

**Comment by xmonader** [comment]
let's verify if it's better in the new playground

**Comment by mohamedamer453** [comment]
Verified in the new playground.

Spaces between deployment message and other UI components were improved.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/334a6602-20f6-4700-802d-c655d5551c18)
