### ISSUE TITLE
Suggestion to new profile manager UI

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#852]
### Description

Bring back the two options of ThreeFold Grid (Manual and Explorer) instead of the empty appearance homepage.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/6e9a4c9b-648d-4cbd-879d-59b695ff6148)

Just remove first slide of polka extension and leave both other slides like below. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/80ce0cc6-0d1d-417e-814e-d5dd2dcd6ab1)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/deb083e9-24ac-48ed-9698-ad615254e33e)

**Comment by 0oM4R** [comment]
__Status__: Pr #863 is ready for review

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc6.
Slideshow was added.
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4dc8ed47-c206-4578-9272-4be51d5f7efe)
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a3d99553-310d-4210-bdb1-e066de0d0415)
