### ISSUE TITLE
Navbar improvements

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#855]
### Description

The look of the navbar after moving the balance is a bit inconsistent and uneven. Firstly there are too much colors in this area with two different shapes for the buttons.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0ea14889-2144-4832-94e8-1eb4827f129b)

Secondly the `GET TFT` button is now floating in the middle and it doesn't really make sense if it isn't next to the balance.

Lastly the spaces between everything is uneven.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9c200987-d931-496f-a29e-eb388352eb2c)

### Environment

- Network: `devnet`
- Dashboard Version: `2.1.0-rc3`

**Comment by 0oM4R** [comment]
@ehab-hassan

**Comment by ehab-hassan** [comment]
ll create Figma file and send it soon

**Comment by ehab-hassan** [comment]
@0oM4R 
![test_nav](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/5145411e-d3cb-440a-b1b2-22019d4764ed)
![Twin (1)](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/10484295/707689ba-b155-4a72-a78c-8c5d8d899770)

https://www.figma.com/file/b50GilnYwLrhwOUIhfzHNA/dashboard-Nav?type=design&node-id=0-1&mode=design&t=flgy3sIe0aXN7AMQ-0

**Comment by A-Harby** [comment]
Verified on Devnet, 2.1.0-rc6.
Buttons UI were improved and help button was removed
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/79036198-3635-48e5-a31b-fb1d063b0b24)
