### ISSUE TITLE
The validation in the profile manager fields is enabled before anything is entered

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#856]
### Description

The validation in the profile manager fields is enabled before anything is entered in these fields.

[Untitled_ Jul 26, 2023 4_23 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f81f979a-b370-4064-9399-e538b80b6c55)

The affected fields are `Password`, `Mnemonic`, `Confirm Password`

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Click outside of the password field when it asks you to enter it.
- Switch to the `Connect Your Wallet` tab.
- Click outside of the mnemonic field.

### Environment

- Network: `devnet`
- Dashboard Version: `2.1.0-rc3`

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc6.

Input are no longer enabled when entered.
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5526aa3b-778d-40fa-9a51-54f05b0477d5)
![1](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/78a62a7e-19b4-45d4-b8e2-059b0d8fd0f2)

But the Password input in the login tab is still connected to the confirm password input.
[Untitled_ Aug 7, 2023 4_26 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/0105ad01-c3a0-429e-b03f-b06f1ae9e058)

**Comment by A-Harby** [comment]
Verified, 2.1.0-rc8.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/10bd1b67-5253-4e93-ab5d-bbba8a5d8428)
