### ISSUE TITLE
Profile Manager: Capitalize the titles of the tabs instead of being all in uppercase

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#857]
### Description

The titles for the tabs in the profile manager should be capitalized not all in uppercase.

`LOGIN` -> `Login`
`CONNECT YOUR WALLET` -> `Connect Your Wallet`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/fe32cd73-33cd-4eef-b607-736e98d1cd13)

### Environment

- Network: `devnet`
- Dashboard Version: `2.1.0-rc3`

**Comment by khaledyoussef24** [comment]
verified 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/d642661e-1f23-479f-adb4-2c469d294cfd)
