### ISSUE TITLE
The manual link for the profile manager in the dashboard redirects to the one for the weblets

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#858]
### Description

The manual link for the profile manager in the dashboard redirects to the one for the weblets.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ff2695bc-de5b-4c0d-8844-213ef3cd440c)

Redirects to https://manual.grid.tf/weblets/weblets_profile_manager.html

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Click on the manual link that's under `Connect your TFChain Wallet`

### Environment

- Network: `devnet`
- Dashboard Version: `2.1.0-rc3`

**Comment by zaelgohary** [comment]
Created an [issue](https://github.com/threefoldtech/info_grid/issues/217) in the manual. URL will be updated once the issue is closed.

**Comment by zaelgohary** [comment]
Blocked on [this](https://github.com/threefoldtech/info_grid/issues/217).

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now it redirects to https://manual.grid.tf/dashboard/dashboard.html#tfchain-wallet
