### ISSUE TITLE
Close the profile manager after logging in

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#860]
### Description

The profile manager in the dashboard stays open after logging in, and there's nothing displayed in it except for the mnemonic. imo it would be a better experience if the profile manager is closed after logging in and if the user needs to open it for any reason then it can be accessed by clicking on it.

[TF DASHBOARD (2).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/65e30fb7-dc66-4481-b1e7-a7f9aeeb5e72)

**Comment by 0oM4R** [comment]
the qr code should be shown
