### ISSUE TITLE
The `How is it done?` link in the `Bridge` page is broken

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#861]
### Description

The `How is it done?` link in the `Bridge` page is broken. https://manual.grid.tf/TF_Farmer_Guide/TF_Complete_Farmer_Guide/farmer_guide.html?highlight=bridge#how-to-use-the-tfchain-stellar-bridge

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/f17abee3-9787-48ba-bb3f-35a0302b4cc5)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/66fd83fe-cfdf-420e-9be7-4b470c4d62b6)

### Steps to reproduce

- Navigate to https://dashboard.dev.grid.tf/
- Login
- Navigate to the `Bridge` page.
- Click on the `How is it done?` link

**Comment by 0oM4R** [comment]
__Status__ : pr #872  is ready for review

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc6.

Link was updated to
https://manual.grid.tf/threefold_token/tft_bridges/tfchain_stellar_bridge.html#how-to-use-the-tfchain-stellar-bridge
