### ISSUE TITLE
(Mainnet Verification) Experimental Playground - Available nodes latency display during deployment.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#862]
Experimental Playground - available nodes are taking much longer than expected to display during deployments, specifically for countries like USA where there are relatively many nodes available.

Please see video grab under [ticket ](https://github.com/threefoldtech/tf_support/issues/573)

**Comment by AhmedHanafy725** [comment]
after doing this issue #491 the filters should be faster

**Comment by zaelgohary** [comment]
Blocked on [this](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/491).

**Comment by AhmedHanafy725** [comment]
this needs to be tested against mainnet once the release reaches it

**Comment by A-Harby** [comment]
Verified, Mainnet 2.1.0.

Searching using any country is now much faster and acceptable.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4aeb9cdb-dd01-41b4-82e6-03a7be82afaf)
