### ISSUE TITLE
Improving the listing nodes inputs 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#865]
### Description

When selecting the node (GPU, Dedicate, or Certified), having four inputs load at the same time puts a lot of loads on the browser, making it slow, difficult to intercept what is going on and most of the time crashes.

It also displays a lot of info like checking if node is alive multiple times and error alerts like Invalid query, farmerbot or rmb is not responding and others.

### Logs/Alerts

[Untitled_ Jul 27, 2023 11_41 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/f1446ba1-f632-42bd-867f-eb7ec61ba220)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/634faca2-b3a2-4f8c-9ba7-35afd8692221)

Maybe it would be better to load each input concurrently.

**Comment by zaelgohary** [comment]
Should be fixed [here](https://github.com/threefoldtech/tfgrid-sdk-ts/commit/4c5ca358a10e293d607f4b9e29e31926a9d2f939).

**Comment by A-Harby** [comment]
Verified, a41641d
When the node checking is working, the country and farm name input are disabled.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/db15af2d-234b-405c-916c-c7cb67b4e7e3)
