### ISSUE TITLE
A node is listed, but the deploy button is disabled.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#867]
### Description

Deploy button is disabled despite having a node available with enough resource for the deployment.

### Steps to reproduce

1. Open https://playground.dev.grid.tf/#/
2. Login and choose FullVM.
3. Change capacity to Recommended.
4. Add a disk
5. Try to deploy

### Logs/Alerts

[Untitled_ Jul 27, 2023 12_57 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/521d52ed-95ef-47b3-9dd8-6776b949df09)

**Comment by AhmedHanafy725** [comment]
this happens after doing multiple requests for different resources before the loading of the first request is finished.
should be solved with #828

**Comment by khaledyoussef24** [comment]
can not reproduce the same issue anymore
[Screencast from 08-29-2023 10:23:36 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/20c4a433-d352-4a32-ac68-f30d4d76f6a9)
