### ISSUE TITLE
SSH connection issue with newly converted Flists

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#868]
### Description

I encountered an issue when trying to SSH into a virtual machine deployed using a newly converted Flist from a Docker image. The Docker image contains a `static Python server` and has the `ssh-server` enabled. However, attempts to SSH into the virtual machine using both the `Yggdrasil` network and the `IPV4` address resulted in a `Connection refused` error.

### Steps to reproduce

1. Build a Docker image with an `ssh-server` enabled.
2. Push the Docker image to a registry.
3. Use the [Docker Hub Converter](https://hub.grid.tf/docker-convert) to convert the pushed image to an Flist.
4. Go to the [playground](https://playground.grid.tf/#/) and deploy a Micro VM with the newly converted Flist.
5. Attempt to SSH into the deployed virtual machine using SSH client tools.

### Expected Behavior
SSH connection to the virtual machine should be established successfully, allowing access to the machine.

### Observed Behavior
SSH connection to the virtual machine using both Yggdrasil and IPV4 addresses resulted in a "Connection refused" error.

#### Yggdrasil
```console
$: ssh root@300:bda2:1631:aaf7:33bf:2882:5182:4efd
$: ssh: connect to host 300:bda2:1631:aaf7:33bf:2882:5182:4efd port 22: Connection refused
```

#### IPV4
```console
$: ssh root@185.206.122.26                      
$: ssh: connect to host 185.206.122.26 port 22: Connection refused
```
### Additional Information
Upon further investigation, I noticed an error in the network tab stating "the job id not found," while the UI indicates "Image ready!" The issue seems to be specific to the newly converted Flists, as SSH works fine with older converted Flists.
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/1d065ab5-9efe-465e-adf7-5ec67cd577b0)
- error message -> `{"message":"job id not found","status":"error"}`

### Reproduction Environment
I created a Docker image with a static Python server and enabled ssh-server. The Docker image can be found [here](https://github.com/Mahmoud-Emad/zinit-python-server) or can be pulled from Docker Hub using the following command:

```console
$: docker pull mahmoudemmad/python-server
```

**Comment by ramezsaeed** [comment]
@maxux

**Comment by khaledyoussef24** [comment]
worked fine with me on mainnet
deployed a micro vm and connected to it successfully 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/b200fb39-0647-47fe-9f83-e4c189628a05)

**Comment by mohamedamer453** [comment]
Verified.

I created a new flist with the same docker image that was provided in the issue and after the flist was created successfully i then deployed a micro vm with this flist and i was able to ssh to the vm without any issues.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d2c5b38d-8598-4e59-bfa5-6c12a5f3bcc4)
