### ISSUE TITLE
Update the list input on Transfer TFTs.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#869]
### Description

Since no other twin addresses exist, remove the list input on Transfer TFTs on the TFChain.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8dce4bc6-e6e9-41d9-9f40-c4c2ded8505f)

**Comment by amiraabouhadid** [comment]
debugging

**Comment by mohamedamer453** [comment]
Verified on devnet.

The list was removed and now it's a normal field when transferring by address.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d1523c25-340b-4642-a85b-0e45dfd7a9b4)

and a numeric field when transferring by twin id.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a40347bc-f581-4eec-bb72-4e0d6acc010e)
