### ISSUE TITLE
Update Threefold Chain button navigation after logging in

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#870]
### Description

After logging in, Pressing on `Threefold Chain` from homepage or sidebar menu will direct you back to the Please connect to your tfchain wallet page while the twin is still logged in. 

### Logs/Alerts

[Untitled_ Jul 27 2023 2_42 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/fafdde8e-2457-46f4-a717-857fd789107f)

**Comment by amiraabouhadid** [comment]
still debugging

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now it redirects the user to the homepage of the dashboard and the user stays logged in.

[TF DASHBOARD (15).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/98215584-29ee-4e85-aa04-1dc0ab79f821)
