### ISSUE TITLE
Add margin to side bar on explorer,  and calculator

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#871]
![Screenshot from 2023-07-27 14-58-38](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/4682cfcd-d505-4af1-85c8-95f8ecc03318)
![Screenshot from 2023-07-27 14-58-20](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/2cca5924-be54-442e-acff-8aa15232a51e)

**Comment by mohamedamer453** [comment]
Verified on devnet.

Margin was added to the sidebar.

[TF DASHBOARD (7).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0db24fe4-91d6-43ab-9d8f-5f772d278dc0)
