### ISSUE TITLE
Error when opening contract data modal

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#881]
### Description
When attempting to open the contract data modal in the dev playground, an error is encountered in the console.

### Steps to Reproduce
- Go to the [dev playground](https://playground.dev.grid.tf/).
- Navigate to the contract list tab.
- Click to view any contract.

### Logs/Alerts
- ![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/4a76654f-0d62-4ea3-a89a-5717de8abf96)

- [Screencast from 30-07-23 11:42:17.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/57001890/32159b6c-d532-4dd5-9961-57a29c00f205)

**Comment by khaledyoussef24** [comment]
verified and fixed on [devnet](https://playground.dev.grid.tf/#/contractslist)
[Screencast from 08-13-2023 08:49:55 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cbbd3756-15d6-426d-b9a2-7eae498fd4a8)
