### ISSUE TITLE
Deleting contracts not working

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/tfgrid-sdk-ts#884]
### Description
I deployed a gateway contract and tried to delete it, it is not working keeps loading for ever
A clear description of the bug
![Screenshot from 2023-07-30 17-30-05](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/1689456/d7bc8ab9-e23d-4976-b2cb-da7646bfd700)

**Comment by AhmedHanafy725** [comment]
related to https://github.com/threefoldtech/tfchain/issues/831

**Comment by AhmedHanafy725** [comment]
The issue is resolved but the playground shouldn't be loading forever and show the error happened instead
