### ISSUE TITLE
Change the way of calculate rootfs to be consistent in all weblet 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#890]
rootfs logic is not consist in all weblets will update this comment with some documentation how to deal with rootfs in other components like filters: 
- Full vm : has a constant variable `rootFilesystemSize` with value 2GB;
- micro VM : the value of `solution.value.disk`;
- kubernets: 
    - Master: master.rootFsSize
    - For each worker: worker.rootFsSize
- Caprover: 
    - Leader: using `rootfs`  function; `rootFs(leader.solution?.cpu ?? 0, leader.solution?.memory ?? 0)`
    - Workers: using `rootfs` function; `rootFs(worker.solution?.cpu ?? 0, worker.solution?.memory ?? 0)`
- Peertube: **Not passed**
- Funkwhale: **Not passed**
- Mattermost : using `rootFs(solution.value.cpu, solution.value.memory)`
- Discourse:  using `rootFs(solution.value.cpu, solution.value.memory)`
- Taiga: using `rootFs(solution.value.cpu, solution.value.memory)`
- Ownclound: `rootFs(solution.value.cpu, solution.value.memory)`
- Presearch: constant variable `rootFsSize = rootFs(cpu, memory)` cpu and memory also is const values
- Subsquid: **Not  passed**
- Casperlabs: **Not passed**
- Algorand: **storage.value**
- Node pilot: 2GB
- WordPress: **Not Passed**
- Umbrel: **rootFs(solution?.cpu ?? 0, solution?.memory ?? 0)**

will update this comment with the new approach

_Originally posted by @0oM4R in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/864#issuecomment-1658430002_

**Comment by 0oM4R** [comment]
- micro VM : `rootFilesystemSize` computed prop equals to solution disk

**Comment by 0oM4R** [comment]
New approach: 
- Full vm :
- micro VM : `rootFilesystemSize` computed prop equals to solution disk
- kubernets:
    - Master:
    - For each worker:
- Caprover:
    - Leader:
    - Workers:
- Peertube:
- Funkwhale:
- Mattermost :
- Discourse:
- Taiga:
- Ownclound:
- Presearch:
- Subsquid:
- Casperlabs:
- Algorand:
- Node pilot:
- WordPress:
- Umbrel:

**Comment by mohamedamer453** [comment]
Verified from #893 

The rootfs is now consistent for all of the weblets, it's assigned through `rootFilesystemSize` const for all of the weblets and its value changes according to the requirement of the weblet itself, some are directly assigned like full vm, node pilot, others are calculated from the [`rootFS`](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/playground/src/utils/root_fs.ts) function, but now the logic is consistent.
