### ISSUE TITLE
Reload user's balance after successful transfer

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#895]
- When user transfer TFT, its balance may be updated immediately without refreshing the page.

**Comment by A-Harby** [comment]
Verified Devnet, .

Balance amount is now updated after every transcation.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/2a81451c-17fb-4dfd-87f4-a5d21d4558c0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/18bfdc9b-49ae-4dde-8ff9-7a6c3ebcd83f)
