### ISSUE TITLE
devnet balance is displayed in qanet dashboard

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#898]
### Description

On qanet dashboard the twin information is correctly displayed for my qanet twin but the displayed balance is for my devnet twin

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/725fcc26-6011-480e-9e2c-5259e521c33b)

### Steps to reproduce

- Navigate to https://dashboard.qa.grid.tf/
- Login to your account.
- Check the twin info and the balance.

### Environment

- Network: `qanet`
- Dashboard Version: `2.1.0-rc5`

**Comment by khaledyoussef24** [comment]
fixed now 
qa balance is reflected in the right way
![Screenshot from 2023-08-09 10-49-06](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5700824e-8d22-4bb0-bdd2-b9b28142f34d)
![Screenshot from 2023-08-09 10-48-00](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5f3a390f-1676-4614-8c07-21c7572768e9)
