### ISSUE TITLE
Updated amount statement in Deposit TFT in bridge page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#902]
### Description

`Amount: should be larger than 0TFT (deposit fee is: 0TFT)` Statement should be updated to the correct TFT value or improve it in the case fee and limit have been removed.
 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/9b659607-842b-4032-bca8-99c3dfd2eda8)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c244b4f2-394a-4361-8387-ce8c8e36569d)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/902

**Comment by A-Harby** [comment]
Verified Devnet, 2.1.0-rc8.
Statement was updated
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/093b5b65-40f1-4784-b476-9d090a525ec0)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/83376c0b-ea81-4730-a1ea-909a63b38510)
