### ISSUE TITLE
When user transfer TFTs to himself, the transaction fee is deducted

### ISSUE THREAD

**Issue by AlaaElattar** [threefoldtech/tfgrid-sdk-ts#909]

**Comment by khaledyoussef24** [comment]
verified on devnet now you can not transfer to yourself
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/f09093cf-4ee1-4cd8-b061-44a97f9e286e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3e57b63f-3a3f-45f8-8f4f-a7fe51f97437)
