### ISSUE TITLE
Account balance doesn't get reset in some cases

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#91]
### Description

The displayed balance is not reset after changing the mnemonics with another mnemonics of an account that either doesn't have enough balance or if the account doesn't have a ssh key.

[TF Playground.webm](https://user-images.githubusercontent.com/101194226/223766125-b9995c1e-01e9-45f0-8491-5bed55a6aee2.webm)

### Steps to reproduce

- Navigate to play.dev.grid.tf/
- Enter the mnemonics of any account with valid balance.
- after loading the twin and the balance open the profile manager again and replace with mnemonics with another one that belongs to account that is not funded yet or an account that doesn't have ssh key.
- Close the profile manager.

**Comment by xmonader** [comment]
please reverify on the new playground

**Comment by mohamedamer453** [comment]
The issue is no longer present in the new playground since the flow was changed and now to change the mnemonic you'll have to logout of the current account. and the balance will disappear once you logout of the current account so there's no chance for it to appear in another account.
