### ISSUE TITLE
Increase RMB Timeout - Push to Main net

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#914]
We had to Increase the timeout for the rmb connections.

The issue discussed in issue #809 has been solved for dev net. I am doing a new issue since the dev fix is closed in both issue and PR (#822).

It would be good to have it quickly to main net, as requested per @scottyeager. (The demand comes from users of the Playground.)

See [this](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/809#issuecomment-1665088300)

I set it as major for this reason.

I assigned @AhmedHanafy725 since you worked on the merge to Dev net.

Thanks!

**Comment by A-Harby** [comment]
Closing this as [solved](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/809#issuecomment-1647629399),
And the Mainnet was just released.
