### ISSUE TITLE
Unable to create a new twin on qanet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#917]
### Description

Unable to create a new twin on qanet.

In the relay selection/twin creation page, after selecting a relay and clicking on the `Create` button it fails to create a twin.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/22688f35-0cf7-458e-9679-63d58e0f3e87)

### Steps to reproduce

- Navigate to https://dashboard.qa.grid.tf/
- Generate a new account.
- Enter a new password and confirm it.
- Accept terms and conditions.
- Select relay and click on `Create`

### Logs/Alerts

```
Current status is Finalized
Account.vue:88 Transaction included at blockHash 0x65a0cdd2d212bdae629b49380bf69de2b348cef865427bbb3c94d90fed1d6b7f
Account.vue:95 	' {"applyExtrinsic":1}: balances.Withdraw:: ["5FNBveQTvrTeRwPnFTNC3GPPemxT4dtNQmqgEX2nVyq88kEG",10126]
Account.vue:95 	' {"applyExtrinsic":1}: balances.Deposit:: ["5E1euBd4m4zG47BdZTUH6UgLLY9ry59C97ZSwh7ghHcBk9dB",10126]
Account.vue:95 	' {"applyExtrinsic":1}: transactionPayment.TransactionFeePaid:: ["5FNBveQTvrTeRwPnFTNC3GPPemxT4dtNQmqgEX2nVyq88kEG",10126,0]
Account.vue:95 	' {"applyExtrinsic":1}: system.ExtrinsicFailed:: [{"module":{"index":25,"error":"0x1c000000"}},{"weight":{"refTime":513115000,"proofSize":3700},"class":"Normal","paysFee":"Yes"}]
```

### Environment

- Network: `qanet`
- Dashboard Version: `2.1.0-rc5`

**Comment by mohamedamer453** [comment]
After testing the same flow with another twin i found that the following error happens and it prevents the dashboard from redirecting the user to the twin details page after the twin creation. and it keeps the user stuck in the relay selection page and clicking on `Create` leads to the error mentioned above, since the twin is already created.

```
nextTick.js:19 TypeError: Cannot set properties of undefined (setting 'active')
    at Account.vue:100:33
    at Array.forEach (<anonymous>)
    at Account.vue:94:20
    at decorateMethod.js:61:22
    at nextTick.js:14:7
```
[Untitled_ Aug 6, 2023 2_54 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/dcd761a3-8419-409e-9c6a-c5c86721e330)

**Comment by AhmedHanafy725** [comment]
the account is created on devnet and seems it's related to this issue #898

**Comment by xmonader** [comment]
qanet and bridge address issue is already fixed now, moving to verification

**Comment by A-Harby** [comment]
Verified, QA 2.1.0-rc7.

Generating mnemonics is working fine now,
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/bcaa7e5e-661d-432e-8e5a-2dc8c83dc30f)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/31af990b-2a5c-4a52-a791-756dac57c775)
