### ISSUE TITLE
The profile manager fields should be cleared after closing it or logging in/out

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#919]
### Description

The profile manager fields should be cleared after closing it or logging in/out.

[Untitled_ Aug 6, 2023 3_08 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/775d4f79-f3b0-4222-a75e-3be2a02bfb67)

**Comment by A-Harby** [comment]
The fields are cleared, but only for the tab that was selected before closing; the other tab isn't affected.
[Untitled_ Aug 13 2023 11_51 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/4afbdf38-5925-4f54-838c-40bf001fa461)

**Comment by mohamedamer453** [comment]
Verified on devnet.

All fields are now cleared after closing the profile manager or logging in/out.

[TF DASHBOARD (8).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/7ab8b065-4c72-4669-8690-50cb3052039d)
