### ISSUE TITLE
Add support for generating seed outside the portal

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#920]
### Description

The portal has changed the way to activate new accounts. Before, I could link the account using the polkadot browser extension, accept the terms and conditions and activate the account with a simple click. Now, it requires me to enter the mnemonics, which I did not need before. When I did that it said that the user was not found. But that is expected for new accounts that have no Existential Deposit yet, right?

The only way I could activate the account was to press generate and then see the terms and conditions. After that, it took me back to the form where I could click on the eye icon and copy the newly generated mnemonics.

IMO The form also should allow me to generate the key outside the portal (in the browser extension or a secure wallet) and then enter the mnemonics in the form to activate the account. But right now, it seems that this option is not supported and it is confusing and limiting.

**Comment by MohamedElmdary** [comment]
Block on this https://github.com/threefoldtech/tfgrid-sdk-ts/pull/936
we need to update dashboard flow into playground one

**Comment by mohamedamer453** [comment]
Verified on devnet.

Activating a seed that's generated outside of the dashboard/playground is now supported.

### Dashboard

[Untitled_ Aug 16, 2023 11_33 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0ff2c26f-e715-4ad6-80f7-dbaeb030075d)

### Playground

[Untitled_ Aug 16, 2023 11_31 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d141b24c-9bb2-410a-aed2-23a92dd50869)
