### ISSUE TITLE
Profile Manager: `Generate Account` sometimes gets stuck at loading the `Terms and conditions` page and keeps loading forever

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#922]
### Description

The `Generate Account` button sometimes gets stuck at loading the `Terms and conditions` page and keeps loading forever with no errors in the console.

[Untitled_ Aug 6, 2023 3_14 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/2f2ca368-02fb-47c9-b6db-f974d308fb2a)

### Steps to reproduce

> This issue is not always reproducible out of 4 tries it got stuck once.

- Navigate to https://dashboard.qa.grid.tf/
- In the `Connect your wallet` tab, click on `Generate Account`

> Another scenario that will always reproduce this issue is generating an account and accepting the terms and conditions then clearing the mnemonic field and clicking on `Generate Account` again.

[Untitled_ Aug 6, 2023 3_29 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/5b4fc0c7-da14-4d83-8365-5a86bda6e8f8)

### Environment

- Network: `qanet`
- Dashboard Version: `2.1.0-rc5`

**Comment by zaelgohary** [comment]
Still investigating.

**Comment by mohamedamer453** [comment]
Verified on devnet.

I've tried generating multiple accounts and it worked every time.


> Another scenario that will always reproduce this issue is generating an account and accepting the terms and conditions then clearing the mnemonic field and clicking on `Generate Account` again.

this scenario was also fixed and now the terms and conditions page appear normally.

[TF Playground _ Full Virtual Machine (9).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/64d0b9a8-5d9a-4d21-b241-dc1aadca77c1)
