### ISSUE TITLE
Add a loading spinner while deleting IPs from farms

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#923]
### Description

A loading spinner should be added while deleting a Public IP from a farm, to clarify that a process is being executed instead of it abruptly disappearing after a couple of seconds.

[TF DASHBOARD (5).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b8629f1a-163f-4b3d-938d-c272391e3512)

### Steps to reproduce

- Navigate to https://dashboard.qa.grid.tf/
- Login to your account.
- Navigate to the Farms page.
- Delete a public ip from any of your farms.

**Comment by A-Harby** [comment]
Verified Devnet, 2.1.0-rc8.
Loading spinner was added.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c7b7e277-ee3c-4776-b2ed-fa5ba3b39da9)
