### ISSUE TITLE
Adding a public config for a node failed without a clear error

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#924]
### Description

Unable to add a public config for a node even when it passed the input validation.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/bb5760a4-aa30-4049-90d1-3a50747130e0)

I've tried adding the same config directly from the chain but it also failed with `InvalidPublicConfig`

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/064f7fa7-7c76-46bd-b9fc-45e4fd0ea93a)

so it seems like a validation issue.

**Comment by 0oM4R** [comment]
__Update__: on [Branch](https://github.com/threefoldtech/tfgrid-sdk-ts/tree/development_dashboard_publicIP_validation)
added ip4 and ip6 classes; for now it just makes sure that the given ip is within the ip range, to handle the case of providing gw not in the range of the ip;
I tried to make the same logic as in the chain but need to be tested will as there is many edge cases specially for ipv6 will provide some unit test as well

**Comment by 0oM4R** [comment]
I have some concerns about this PR #966 
- should we use [ip6](https://www.npmjs.com/package/ip6) package to handle the format of the ipv6 and avoid possible edge cases?
- should we move the whole ip logic into those classes ?
 
__Will convert the pr to draft to discuss those points__

**Comment by mohamedamer453** [comment]
Verified on devnet.

I've tried the same config that was originally mentioned in the issue and it triggered the validation since the gateway ipv6 wasn't a part of the given ip.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/49b5b8f6-8b1f-4516-932b-265d9e86531a)

and when i updated the gateway ipv6 with a valid one that's a part of the ip it worked without any issues and the config was added.

[TF DASHBOARD (14).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/0e369ab7-d85e-483b-86a0-5cffc488e705)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4366aab4-b648-4353-8d8f-08cc0b3c4fee)
