### ISSUE TITLE
Rootfs is not passed to the farm and node filters

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#925]
### Search first

in some weblets rootfs not passed to the node/farm filter,
- https://github.com/threefoldtech/tfgrid-sdk-ts/pull/893
- https://github.com/threefoldtech/tfgrid-sdk-ts/pull/912
this changes will help to fix this issue

**Comment by 0oM4R** [comment]
__Status__: PR #937 is ready for review

**Comment by A-Harby** [comment]
Verified.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a38fce83-49a8-4b07-86f6-467ff64c2650)
