### ISSUE TITLE
Update the bridge address for qanet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#926]
### Description

The bridge address for qanet is the same one as devnet.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d437a153-865d-424f-8fc3-0cda4015ab7a)

requires: https://github.com/threefoldtech/tfchain/issues/845

### Steps to reproduce

- Navigate to https://dashboard.qa.grid.tf/
- Login to your account.
- Select `Bridge` from the sidebar.
- Click on `Deposit`
- Check the Bridge address.

### Environment

- Network: `qanet`
- Dashboard Version: `2.1.0-rc5`

**Comment by Mahmoud-Emad** [comment]
blocking on https://github.com/threefoldtech/tfchain/issues/845

**Comment by Mahmoud-Emad** [comment]
Should be updated in https://github.com/threefoldtech/tfgrid-sdk-ts/pull/961

**Comment by mohamedamer453** [comment]
Verified on qanet.

The bridge address for qanet was updated. https://github.com/threefoldtech/tfchain/blob/development/bridge/README.md

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/4f8f95be-3718-434b-9c4a-b1b5f162da3f)

however it still needs to be activated as mentioned in https://github.com/threefoldtech/tfchain/issues/845#issuecomment-1672767211

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/b53c2396-263b-4dae-8615-cae99cd58a3f)
