### ISSUE TITLE
Explorer: Nodes, Farms filters improvement

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/tfgrid-sdk-ts#927]
### Description

The titles of the filters in the nodes and farms pages should be capitalized not all in uppercase.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/bd83b7f1-da49-4acd-a92e-98bb860527ab)

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/d602d6fc-25a4-4d02-8420-64cd2a8b3fbf)

**Comment by khaledyoussef24** [comment]
verified in both tabs of explorer nodes and farms 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/cf0537bb-3a24-49a1-9f82-422c4979f7b7)
