### ISSUE TITLE
Adding Public Config to Node - Unable to save.

### ISSUE THREAD

**Issue by TullysInc** [threefoldtech/tfgrid-sdk-ts#928]
When adding a public config for a Node ID, the save button does not highlight until all fields have been entered:

![RJ Lamers](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/105203696/96517443-1b00-4f67-832e-79ccc50a0b96)

However, as per our current [manual](https://manual.grid.tf/farmers/3node_building/1_create_farm.html?highlight=Public%20Config#how-to-configure-public-ip-addresses-for-a-threefold-farm-or-a-3node) - the IPv6 address and the Domain are meant to be optional.

**Comment by 0oM4R** [comment]
the `domainCheck` rule is returning false if the  `domain` field is empty; 
not sure should we remove this or update the manual ? @AhmedHanafy725

**Comment by A-Harby** [comment]
Verified, Devnet 2.1.0-rc8.

Based on docs, Only IPV4 is the necessary ip to be added. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a287eef4-dc86-47ca-ba01-997c86afe234)
And it was updated to only request IPV4 to enable submit button
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/ae447e04-a170-4425-8e72-0b3362c082c5)

**Comment by Ashishban** [comment]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/91247662/ae77464c-ff4b-4916-a707-fdb8d88e8235)

Client continues to receive the same error.

**Comment by Ashishban** [comment]
Client was on mainnet. Thanks for pointing that out.
