### ISSUE TITLE
Adding error handling to the farm page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#941]
### Description

Farm page keeps loading forever when there's a failed request occured from the grid proxy, error is displayed on the console but the page keeps like that `Loading farms`.

There should something like a notification or an alert (with a reload button) to inform the user that an error occurred (from proxy or network issue) and to reload the page.

### Logs/Alerts

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/43612d46-ba45-401c-aab8-c502e05bc46e)
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c3a0fc89-c2fb-4c2f-bf5c-76a7c6c15a46)

**Comment by Mahmoud-Emad** [comment]
Should be fixed https://github.com/threefoldtech/tfgrid-sdk-ts/pull/1010

**Comment by A-Harby** [comment]
Verified Devnet,

'An error occurred during the attempt to fetch farms due to a network error' An error message is displayed with a reload button when an error happens. 
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/a47daed7-a924-401a-9266-0a9de068bf61)
