### ISSUE TITLE
Request from farms through the farm page

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#942]
### Description

While navigating to the farm page, a request is sent for each farm the twins have, even though the farm table default rows per page is only 10.

Why does it then ask for all of them?

### Logs/Alerts

[Untitled_ Aug 8 2023 5_06 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/91217718-694b-43d8-b424-c89c4c7c09e9)

**Comment by Omarabdul3ziz** [comment]
introduced in this commit https://github.com/threefoldtech/tfgrid-sdk-ts/commit/7bcb4930f71a21934044a3b962acfd5e868f8423 a request is sent to each farm to know if it has nodes or not to show or hide the `Download Miniting Receipt`
This may not be the best solution but there is no other way to get this info. a suggestion is to add a new endpoint in gridproxy API that returns aggregation of each farm and the nodes it has, opened an issue on sdk-go https://github.com/threefoldtech/tfgrid-sdk-go/issues/355

**Comment by Omarabdul3ziz** [comment]
after a discussion with hanafy, it is not a normal case for a twin to have this number of farms but it is still a better solution to have a single call to the grid proxy that will return all the data needed.
since it is not that critical we can wait and handle this in the new dashboard

**Comment by A-Harby** [comment]
Verified,

- New dashboard
- Devnet
- [TC2112 - List farms](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348398#case_4147601)

I used the same account, and now it lists the farms with errors as shown before.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/32d427ac-4cf0-4a3b-963b-51126eed3799)
