### ISSUE TITLE
Dashboard: Add already exist public configuration 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/tfgrid-sdk-ts#943]
### Description

If the node has public configurations, the save button will always be enabled, even if the configuration is not changed.

### Steps to reproduce

- go to https://dashboard.dev.grid.tf
- open farms in portal 
- add public configuration to a node if you don't have one with public configuration 
- open public configuration dialog
- click on save button 
will save the current public configuration that not touched

[Screencast from 08 أغس, 2023 EEST 05:12:17 م.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/62248851/510c5bc2-093e-4dc4-be59-06be9000051c)

**Comment by A-Harby** [comment]
Verifed, Devnet 2.1.0-rc9.

Submit button isn't enabled unless new input is added to the conifg.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/30031d3a-9227-46d5-9f7c-135e7da82055)
