### ISSUE TITLE
`You can not transfer to yourself` validation is working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#945]
### Description

`You can not transfer to yourself` validation is displayed to another twin address.

### Logs/Alerts

[Untitled_ Aug 8 2023 6_45 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/023e0b1b-be1b-468f-ba5c-ba3bdbbdeeb7)

**Comment by khaledyoussef24** [comment]
verified on devnet 
[Screencast from 08-10-2023 06:30:29 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/5b736859-f2e3-4cab-bff2-585bc35990c1)
if wrong address 
![Screenshot from 2023-08-10 18-31-41](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/1e6b2598-0be0-4c64-8f27-d41794963614)
