### ISSUE TITLE
Update all global scripts to be structured and up to date.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/tfgrid-sdk-ts#950]
### Description

The entire global script requires restructuring and updating for enhanced functionality. For those intending to adopt this script, it's essential to acknowledge that "the script should be modularized into functions." This improvement is aligned with the idea that the code needs to be compliant with linting tools in the GitHub Actions workflow.

Please refer to the example provided below for guidance:

```ts

function main() {
  const grid = new GridClient();
  grid.connect();

  // List all contracts
  listAllContracts(grid);

  // Uncomment the line below if you intend to perform contract cancellation.
  // cancel(grid);
}

function listAllContracts(grid: GridClient) {
  // Utilize the contract module within the grid client to list all available contracts.
  return grid.contracts.list();
}

function cancel(grid: GridClient, contractID: number) {
  // Utilize the contract module within the grid client to cancel a specific contract.
  return grid.contracts.cancel(contractID);
}
```

**Comment by mohamedamer453** [comment]
Update:

Work Done:

- Updated the structure of 17/38 scripts. #1409 
- The new structure splits the script into functions for each functionality and calls these function in the main() function.

Work In Progress (WIP)

- Updating the rest of the scripts.

**Comment by mohamedamer453** [comment]
Update:

Work Done:
- Updated the rest of the scripts to the new structure.

Work In Progress (WIP):
- A couple of scripts are still remaining, still looking into how i'll re-structure them.
- More structuring to be done for each script to be more like the [`vm_with_qsfs.ts`](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/packages/grid_client/scripts/vm_with_qsfs.ts#L36&L90) script

**Comment by mohamedamer453** [comment]
Update:

Work Done:

**Comment by mohamedamer453** [comment]
Update:

Work Done:

- scripts in the `scripts/tfchain` directory were not updated yet, so i updated them with the correct structure and models.
- Did a final review for the scripts and did a final update.
- PR is ready for review #1409

**Comment by A-Harby** [comment]
Verified,
On development branch, 
The script has been updated to adopt three functions in every script (deploy, get deployment, and cancel).
Other scripts have also been refactored to functions.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/c32e2743-6147-4eaf-bed3-1400ff33a2a9)
