### ISSUE TITLE
add a breathing space between the header and the subheader in the profile connector

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#952]
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/64129/928fa77d-3d80-420e-a704-cae781a9f353)

**Comment by mohamedamer453** [comment]
Verified on devnet.

A space was added between the header and subtext.

![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/a46d771d-c72c-4dcc-8873-5df78c063b63)
