### ISSUE TITLE
deleting contracts shouldn't keep loading in case of error

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/tfgrid-sdk-ts#953]
The issue is resolved but the playground shouldn't be loading forever and show the error happened instead

_Originally posted by @AhmedHanafy725 in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/884#issuecomment-1661930599_

**Comment by A-Harby** [comment]
Verified, devnet a41641d.

Tried few items and get a error when I had a network error, deleting didn't kept loading.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/e23f29eb-991b-4fb7-843e-59d715b97c5a)
