### ISSUE TITLE
FR: allow an alternative way to add a user ssh key using GitHub username

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/tfgrid-sdk-ts#96]
I suggest adding a second way to add a user ssh key to the profile manager, which would be **faster**, and **developer friendly.**

- a direct UI integration is that we could have a toggle button next to the ssh field to allow switching between entering the actual ssh key and GitHub username.
- Another way which less explicit is that, without adding extra UI elements, we could validate the user entry and in case it wasn't an ssh key, we could use it as a GitHub username and try to grab the key.

For gripping the ssh keys for GitHub users, it's known that Github exposes the public ssh keys:
- e.g. https://github.com/[USER-NAME].keys
or using the [API](https://docs.github.com/en/rest/users/keys?apiVersion=2022-11-28#list-public-keys-for-a-user)
- e.g. https://api.github.com/users/[USRE-NAME]/keys

**Comment by xmonader** [comment]
I don't think we should support a specific platform e.g specific vendor 
1- there're other platforms e.g gitlab, gitea (while the popularity of github is out of question), but the other users will be having to copy/paste
2- lots of the users don't even have an sshkey too
