### ISSUE TITLE
Auto-generating docs/api/classes modify files

### ISSUE THREAD

**Issue by Mik-TF** [threefoldtech/tfgrid-sdk-ts#967]
Auto-generating docs/api/classes modify files such as nodes.html

Then it is difficult to fetch the branch as there are uncommitted changes.

Perhaps having 

> packages/grid_client/docs/api

in .gitignore would fix the issue.

**Comment by Mik-TF** [comment]
For example, here's the error that comes up:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'packages/grid_client/docs/api/classes/Nodes.html'
  'packages/grid_client/docs/api/classes/nodes.html'
 
``` 

@Mahmoud-Emad Perhaps you can have a look. You can re-assign someone if it doesn't fit. Thanks!

**Comment by xmonader** [comment]
@Mik-TF please don't assign developers to issues, new issues get sorted by components owners and based on the priority, it gets in the pipeline.

**Comment by Mik-TF** [comment]
@xmonader  thanks it is noted.

Does this apply for PR too?

**Comment by xmonader** [comment]
Thanks! as for PRs, code reviews are automatically requested because of the configured [CODEOWNERS](https://github.com/threefoldtech/tfgrid-sdk-ts/blob/development/CODEOWNERS) file -Configured in most of the repos-

**Comment by maayarosama** [comment]
docs are part in the repo because we use to serve on github, any changes are meant to be tracked.
