### ISSUE TITLE
gett tft balance is not reflected unless you refresh the page

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/tfgrid-sdk-ts#969]
network : [qanet](https://dashboard.qa.grid.tf/explorer/nodes)

### Description

gett tft balance is not reflected unless you refresh the page
[Screencast from 08-10-2023 06:54:58 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/9c452758-073a-4fc5-95ea-3449be07ca9d)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The balance is now updated without reloading the page.

[TF DASHBOARD (10).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/ccc1b4ca-8c2b-4204-ae5c-4a76a518b5d1)
