### ISSUE TITLE
Possible Performance Issues in Playground

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/tfgrid-sdk-ts#973]
### Description

Left the new Playground running in Chrome. An internet outage happened and Chrome suddenly started using the CPU heavily. Chrome was only running the Playground. It may not be a Playground issue but it was the only thing running.

**Comment by mohamedamer453** [comment]
Update:

I've tried to debug this issue and i have reached the following conclusion:
Unfortunately i wasn't able to reproduce this issue, the methodology that i used is the following.
Firstly i monitored the usage of each page in the playground while the internet connection was available, after that i went through each page in the new playground and while i was at each page i turned off my wifi to try and simulate the scenario in the original issue, from that I've noticed that all the pages had a very normal cpu usage if not lower that the one that was monitored while the connection was available.

The only cases where i noticed a slight spike in the cpu usage are the ones where the connection is disconnected while they try to load something. for example:

- Dao page (only if the connection was lost while loading the proposals)
- Any solution (if the connection was lost while loading the node)
- The contracts list (only if the connection was lost while loading the contracts)

And for the previous three cases the cpu usage only went to about 5-9% usage so nothing major.

@AbdelrahmanElawady it would be great if you could provide more info like: what were you doing (deploying something, checking twin info, etc..) or even better if you can remember what page were you at when the high cpu usage took place.

**Comment by AbdelrahmanElawady** [comment]
Well, I do not recall what I was doing at the time but I didn't face this issue again so it could be completely unrelated to the Playground or it was fixed at some point. If it happens again I will open an issue with more details.
