### ISSUE TITLE
Balance doesn't updated after transaction and locked TFT disappear 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/tfgrid-sdk-ts#979]
### Description

After transfering TFT, Locked TFT amount disapear.
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/5c5b9122-1ca0-4c41-bd04-a5ae9ffa87a2)
[Untitled_ Aug 14, 2023 2_28 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/19ca5d0c-e628-41b5-b8cf-cb913c374ca3)

And the twin that TFT transferred to, doesn't updated its balance without a refresh.
In the video the twin should have received 1 TFT, but I had to logout and relogin or refresh to updated my balance.
[Untitled_ Aug 14 2023 2_11 PM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/109473873/8c2b8a1e-2702-4f9c-ba9f-cd142b6fcc60)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The balance now gets updated after a transfer and the locked tft doesn't disappear.

[TF DASHBOARD (11).webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/101194226/9db34044-749a-4463-a440-ea4253c67188)
