### ISSUE TITLE
Select a node causing tab to be invalid without interaction from user

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#982]
This issue exists in every weblet and it's cause because NodeId field isn't valid by default

Expected:
Tab should be in a neither valid nor invalid status unless the user interacted with it

Devnet
![image](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/31689104/f11f80d1-2524-4d8e-a09b-f9fc8dd5b7b7)

**Comment by khaledyoussef24** [comment]
should this work on the playground or on the new playground ?

**Comment by khaledyoussef24** [comment]
verified now works fine 
[Screencast from 10-08-2023 10:37:43 AM.webm](https://github.com/threefoldtech/tfgrid-sdk-ts/assets/110984055/3a7d4ff7-6d17-4d6a-830f-3ff19efe76bc)
