### ISSUE TITLE
Release packages on npm with tags

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#993]
In the case of pre-release, the package shouldn't take the `latest` tag on npm (maybe `edge` tag), so if the user tried to install the client it should take the latest one which works against mainnet. And the other versions should be installed with `edge` or the exact version for the rest networks

**Comment by A-Harby** [comment]
Verified, Workflow https://github.com/threefoldtech/tfgrid-sdk-ts/actions/workflows/publish.yml was updated to add `edge` tag to any rc version.
