### ISSUE TITLE
Introduce error types in clients

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/tfgrid-sdk-ts#995]
Some of the features are depending on checking if the error message contains part of the message which might be re-phrased and break the feature. So it's better to have well-defined error types to check against.

**Comment by 0oM4R** [comment]
#### Status
Investigation and solution:
We may implement a new common package to include the common functionality and types 
we can start with Errors types and class

Here are some [suggestions](https://www.typescriptlang.org/play?#code/KYOwrgtgBA4gTgSwCYGEA2DQBcCic4D2cAzlAN4BQU1UAKgO4IgpzACGWCBIUAvFAEYADEIA0VGgyYAxNgjTAkFAL4UKoSFABKEAEbpMIXPiKlKNOo2asOXECrUboW4AEcwwYlnITqAOQIsaQIwECVVdQAPAAcibwBjbi8oAGUkAGs8QhI+HwsAc0QkAC5YIoNsLNNxCzg9Up19DEqTEhqaVndPLAa3Dy8HNTV4tDZiUjTM1qhgSKxQJFIquDyaRJAvODB4rCIACmiwXQx4qESkYFLwPWA4USgIT2I2fMuoTaZ8gEpVi2piMDRW57R7jF7AL5qP40SbLAB0Y2ItyweywAAsEMRIRYIhZDscEKc+mw0MQ9m9Ya0vqVdAQCAo2DxzNCoKwsGA4DxKdk4cTSaiMcR7hDfFBVBZRfiTu8sLZTpjya1SqF0iACPQQNSZtNMakMstfn82RyeLdslAmF5GfFgAQAGZ6qbZUW4mhSwkyuVQdGEeh7c5va66W73UHPV6lD4gb5XYAAN1uhosPvVUBAwHojuW-oIF1DT3B2Joruo7tOVs4p3iNnmOYuV0gwbuDwLEZliGjWu5RCTHWA7M5aYzWdadeA+bBryL1BLUDLnsrM3cJLJwAEpW7zeAACYN-qqTS6QymaLav2TTMBHxePwd1AAD73qDkgRwgPX2-bt+54BQABkf6XnCYbgh+MxfiBU4ulCbpHNKFYeoiyLknuTpEFqcYEMgD5DgmKzMtCCAOqiACeQL2jM34XFAACEN5QAAREGtwMQ+T5YGRtoOsAwGtr+dH8AxUb5AxPwESy1CbnCKZ+gAtAI9wAAablAKBJFgWw7D2sxAjsijPgGDY3M2kFvMJPy6GA3j5IEz4ACRkDxAbKPcDk8aZyhfIp05-MoUDQREFDrMka65OmmbZgA5GiwBoGgBBQPQRBoEgkWQsF3h3vwUnVuwtZiIxolqERz5SQqa5fGJorBfSPHxfkewMaFuoqfQGLxGiFqkGq3gaR4RV+bFSKGjVChwvVjXNd1tmbgNQwlXsZWrtulUjUktXjQQDVNduXUjuabWEp1uqIPkaJYANQA)

**Comment by 0oM4R** [comment]
1. Work Completed:

discussed with Hanaffy about the aproach and the structure, now we are working on tfchain errors; by creating a class for each error from tfchain defined error  

2. Work in Progress (WIP):
create classes for the rest of tfchain pallets

**Comment by 0oM4R** [comment]
1. Work Completed:
all tfchain errors are implemented now <that comes from tfchain>
2. Work in Progress (WIP):
trying to map the returned error from chain with the implemented errors in types class

**Comment by 0oM4R** [comment]
Work completed:
- A PR #1417 <for tfchain client abd types package> is ready for review 
- the errors classes are applied to rmb client and the pr is ready for review 


Work in progress:
Apply error classes on gridproxy client

**Comment by 0oM4R** [comment]
1. Work Completed:
  rmb and tfchain now merged, but in some cases we need to handle errors, for example:
  transfer method in tfchain client throws pollkadot eroro
  -  apply error classes to grid_client:
    -  clients
    -  helpers
  
 2. Work in progress:
    - #1442 
   apply error classes to :

    - [ ] zos
    - [ ] storage
    - [ ] primitives
    - [ ] highlevel
    - [ ] modules

**Comment by 0oM4R** [comment]
Work Completed:
Error classes is used in Gridclient and the #1443 is ready for review 
Work in progress:
Write docs for types/errors

**Comment by 0oM4R** [comment]
Work completed:
resolved some comments on the PR 

Work In progress:
Writing some readme files for the types package

**Comment by AhmedHanafy725** [comment]
a new package for error types is added and also used in the required clients
